### ISSUE TITLE
Error while using model.visualize_distribution(probabilities)

### ISSUE THREAD

**Issue by theRay07** [MaartenGr/BERTopic#10]
![Capture](https://user-images.githubusercontent.com/48051361/97610854-6aac4700-1a3b-11eb-8d27-4696ee641d08.PNG)

**Comment by MaartenGr** [comment]
What is in the `probabilities` variable? It is supposed to be a bumpy array with only a single dimension. What steps did you do exactly to arrive at this error?

**Comment by theRay07** [comment]
I just ran these two lines which worked fine. 'text' is a list of sentences.

model = BERTopic("distilbert-base-nli-stsb-mean-tokens", verbose=True)
topics, probabilities = model.fit_transform(text)

**Comment by MaartenGr** [comment]
Ah! You should put in only the probabilities of a single document. Use `probabilities[0]` instead!

**Comment by MaartenGr** [comment]
That also means that the readme is unclear. I'll update it.

**Comment by theRay07** [comment]
Yes, it is working now. Thank you for your help.
