### ISSUE TITLE
CountVectorizer after reducing outliers and updating topics

### ISSUE THREAD

**Issue by andrewliew86** [MaartenGr/BERTopic#1000]
Hi Maarten,

Is it possible to apply a vectorizer model (i.e. CountVectorizer(stop_words="english")) to the topic model after running the 'reduce_outliers()' and 'update_topics()' functions? I applied the vectorizer model when I used the fit_transform() so I was hoping I could do the same with the updated topics.

Thank you.

**Comment by MaartenGr** [comment]
Sure, you could use the `.update_topics` function with a custom vectorizer model after doing all of your processing, including `.reduce_outliers`. In `.update_topics`, there is a parameter for passing a vectorizer model, which allows for updating the topic representation after `.fit_transform`.

**Comment by andrewliew86** [comment]
Thanks Maarten. That's working now
