### ISSUE TITLE
ValueError with guided topic modeling on ArXiv abstracts

### ISSUE THREAD

**Issue by damosuzuki** [MaartenGr/BERTopic#1001]
I am trying to perform guided topic modeling using the ArXiv dataset (thanks for putting together [this notebook](https://www.kaggle.com/code/maartengr/topic-modeling-arxiv-abstract-with-bertopic), btw), but I am running into an error:

<img width="998" alt="image" src="https://user-images.githubusercontent.com/404062/218768786-5a3e2c07-b8ba-4290-8115-346384c35b95.png">

Note that this same procedure works fine for me on the 20 Newsgroups dataset, or on the ArXiv dataset without guided topic modeling. So, it seems that this error is somehow dependent on the input data. Note that I am currently using the full tag name as a single seed for each topic.

Thanks!

**Comment by MaartenGr** [comment]
Could you create a fully reproducible example? At the moment, I am not entirely sure what exactly is happening here. Perhaps the length of the seed topics might be larger than the number of topics being generated.

**Comment by damosuzuki** [comment]
Thanks for the reply. I haven't had a chance to create a stand-alone reproducible example, but I will try to do this next week.

**Comment by MaartenGr** [comment]
Due to inactivity, I'll be closing this issue. Let me know if you want me to re-open the issue!
