### ISSUE TITLE
Mismatching topic numbers when using BERTopicAdjusted

### ISSUE THREAD

**Issue by MogwaiMomo** [MaartenGr/BERTopic#1003]
Hello Maarten!

Just a quick note that it appears running the class BERTopicAdjusted(BERTopic) you wrote for adjusting the number of representative docs per topic (https://github.com/MaartenGr/BERTopic/issues/848#issuecomment-1328850406)

appears to create mismatching topic numbers now with the latest version of bertopic (v0.14) — i.e., the topic numbers from .get_representative_docs() end up being different from those in .get_topic_info(). 

Also, switching back to just using BERTopic() without the adjusted class eliminates this mismatch.

_Originally posted by @MogwaiMomo in https://github.com/MaartenGr/BERTopic/issues/848#issuecomment-1430738648_

**Comment by MaartenGr** [comment]
That is correct! In the v0.14 release, it was updated how the representative documents were generated. It now produces a fixed number of representative documents regardless of whether topics were merged/combined. Instead, you can now use the following:

```python
import pandas as pd

# Prepare your documents to be used in a dataframe
documents = pd.DataFrame({"Document": docs,
                          "ID": range(len(docs)),
                          "Topic": topic_model.topics_})

# Extract the top 50 representative documents
repr_docs, _, _ = topic_model._extract_representative_docs(c_tf_idf=topic_model.c_tf_idf_,
                                                          documents=documents,
                                                          topics=topic_model.topic_representations_ ,
                                                          nr_repr_docs=50)
```

Do note though that accessing private functions will always be at risk for changes in future releases and is typically only advised to use if you do version control of BERTopic and its dependencies.

**Comment by MogwaiMomo** [comment]
Thank you! Also just a note that the 'Lego'-esque modularity of the new version and how [it's broken down here](https://maartengr.github.io/BERTopic/algorithm/algorithm.html) is, once again, just fantastic. So helpful.
