### ISSUE TITLE
2D topic mapping differs greatly between visualize_documents and visualize_topics

### ISSUE THREAD

**Issue by zilch42** [MaartenGr/BERTopic#1006]
Hi there, I'm not sure if this is an issue or just a lack of understanding on my part. 

I have a simple dataset of 5k Journal article abstracts (1k each from 5 very distinct topics - dairy, space, immunology, geology and hydrogen fuel storage) so they should cluster pretty distinctly. 

I run a basic topic model:
```
embedding_model = SentenceTransformer("all-MiniLM-L6-v2")
embeddings = embedding_model.encode(sentences, show_progress_bar=True)
vectorizer_model = CountVectorizer(stop_words="english", ngram_range=(1, 2))

topic_model = BERTopic(
    embedding_model=embedding_model,
    vectorizer_model=vectorizer_model,
)

# Fit model with pre-calculated embeddings
topics, probs = topic_model.fit_transform(sentences, embeddings)
```

(This produces more topics than I want, but that's fine, I have other code that improves the clustering.) 
`topic_model.visualize_documents(titles, embeddings=embeddings)` separates these documents pretty well into five distinct groups. Topics 0, 1 and 2 certainly look great and are far apart.

![visualise documents](https://user-images.githubusercontent.com/39004650/219259763-5513971f-7f9f-40f1-8657-9f231a0e7cc9.PNG)

`topic_model.visualise_documents()` produces a very different relationship between the topics in what I expect would be the same 2D space. Topics 0 and 1 are stacked on top of each other and topic 2 is very close by. 

![visualise topics](https://user-images.githubusercontent.com/39004650/219260168-73a8a89d-35e1-498e-b07d-7f20340effc1.PNG)

Is this expected? And if so, why are they so different and what is visualize_topics actually telling me?

Happy to share my data set if that would be useful. 

Same behaviour on both bertopic 0.13 and 0.14.

Thanks for your work on this amazing package :)

**Comment by MaartenGr** [comment]
Yes, this is expected as the UMAP models are trained on different data. In `.visualize_topics`, UMAP is fitted on the c-TF-IDF topic representations, which is just a few datapoints and is equal to the number of clusters. In `.visualize_documents`, however, UMAP is fitted on the representations of each individual document and not the topic itself, therefore UMAP has more data to train on and since it is trained on different data, the output is expected to be different.

**Comment by zilch42** [comment]
Ok Good to know, thanks for such a quick response!
