### ISSUE TITLE
Reason for the difference  between date of earliest timestamp and earliest timestamp given by DTM

### ISSUE THREAD

**Issue by ClaudiusOtt** [MaartenGr/BERTopic#1008]
Hello,

It looks like the timestamp of the earliest date of the dataset and the first timestamp of DTM differ can you explain the reason, or is there a parameter to use to align these values?
If I use the example of Dynamic Topic Modeling with Trump's Tweets I get as first timestamp for topics_over_time the date and time '2009-04-30 12:30:07.596999936'. If I then sort the  list of timestamps I get as the earliest date  '2009-05-04'.

**Comment by MaartenGr** [comment]
It depends on your exact code, the parameters that you passed to `.topics_over_time` but it might be as a result of the binning procedure of pandas which might do some optimization there. You can find the relevant code in `.topics_over_time` here:

https://github.com/MaartenGr/BERTopic/blob/1ee8141d65063a37f6ee3fd56b30e3f9e2f43d6e/bertopic/_bertopic.py#L671-L679

**Comment by ClaudiusOtt** [comment]
Thank you very much!

If I get it right this happens  if x is large and you use an int as parameter for bins.  


![Bild_2023-02-16_214149447](https://user-images.githubusercontent.com/78845252/219482217-462cad8d-574d-47f7-b010-cf8db25b0794.png)
