### ISSUE TITLE
topics_over_time Index Error

### ISSUE THREAD

**Issue by YukunYangNPF** [MaartenGr/BERTopic#101]
Hi, I'm trying to build my own DTM.

```
topics_over_time = model.topics_over_time(
    corpus, 
    new_topics, 
    police_df_ori['approx_created_at_new'].dt.date.to_list(),
    nr_bins=None
)
```

I've checked that the new_topics index and the model's topics.
![image](https://user-images.githubusercontent.com/70721363/115653724-ae528000-a2fd-11eb-974a-ce732496ef93.png)

However, every time I run the code, it throws an index error.

```
IndexError                                Traceback (most recent call last)
<ipython-input-64-4768882a23d7> in <module>
----> 1 topics_over_time = model.topics_over_time(
      2     corpus,
      3     new_topics,
      4     police_df_ori['approx_created_at_new'].dt.date.to_list(),
      5     nr_bins=None

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/bertopic/_bertopic.py in topics_over_time(self, docs, topics, timestamps, nr_bins, datetime_format, evolution_tuning, global_tuning)
    478             # by simply taking the average of the two
    479             if global_tuning:
--> 480                 c_tf_idf = (global_c_tf_idf[documents_per_topic.Topic.values + 1] + c_tf_idf) / 2.0
    481 
    482             # Extract the words per topic

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/scipy/sparse/_index.py in __getitem__(self, key)
     31     """
     32     def __getitem__(self, key):
---> 33         row, col = self._validate_indices(key)
     34         # Dispatch to specialized methods.
     35         if isinstance(row, INT_TYPES):

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/scipy/sparse/_index.py in _validate_indices(self, key)
    136                 row += M
    137         elif not isinstance(row, slice):
--> 138             row = self._asindices(row, M)
    139 
    140         if isintlike(col):

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/scipy/sparse/_index.py in _asindices(self, idx, length)
    168         max_indx = x.max()
    169         if max_indx >= length:
--> 170             raise IndexError('index (%d) out of range' % max_indx)
    171 
    172         min_indx = x.min()

IndexError: index (102) out of range
```
Yeah I don't have 102 in my topic list, but I do have 101. I don't know why it was added by one.

**Comment by YukunYangNPF** [comment]
Hmmm

More information about this one.

I tried the topic reduction before run the topics_over_time. Don't know if this triggers the issue. When I run the vanilla results, it works fine.

**Comment by MaartenGr** [comment]
Thank you for posting this issue with the extensive description! This is a known issue and will be fixed in v0.7 (#87). I did not track the topic values correctly in `topics_over_time` after reducing the number of topics that caused this issue. The new update will come out in the upcoming week.

**Comment by MaartenGr** [comment]
@YukunYangNPF This is now fixed in the new release of BERTopic. Please update with `pip install --upgrade bertopic` and it should work 😄

**Comment by hari-chalise** [comment]
I have faced same Problem "  IndexError: list index out of range" While Training My Model For Topic Modelling By using BERTopic For Nepali Text. I have attach my all code and error with this please find my mistake.
![image](https://github.com/user-attachments/assets/de0fa83b-5ac7-4407-bd97-e4d0fd921e0d)
![image](https://github.com/user-attachments/assets/cfb884f6-0569-42c7-a0c9-a93d69e86266)
![image](https://github.com/user-attachments/assets/086eb2a2-8aa2-462c-9848-eafa1c417e5a)
![image](https://github.com/user-attachments/assets/da4a9695-a39b-449f-9f2a-c643198b4a36)
![image](https://github.com/user-attachments/assets/1c71a596-b04a-43ce-bb13-15b976dac9f4)
![image](https://github.com/user-attachments/assets/f59f0c09-0e4e-4a98-9efa-cb6b41f56693)
![image](https://github.com/user-attachments/assets/d9f3b17d-ee28-493d-8a4a-679500142d13)
And This is Error
![image](https://github.com/user-attachments/assets/4a7e1316-d05d-426d-a447-b8d2eddb466b)
I am trying to only few data for first testing the model.
And the  Version : BERTopic version: 0.16.4

**Comment by MaartenGr** [comment]
@hari-chalise Could you share your code as text instead of pictures? Preferably with the ``` tags so it is nicely formatted. 

Also, you show the truncated error. Could you show the **full** error? You can do that by clicking on the "2 frames".

**Comment by MaartenGr** [comment]
Also, as a quick comment. It is not advised to use `nr_topics` in general but use HDBSCAN (and the `min_cluster_size` param) to control the number of parameters. Also note that you can always reduce the number of topics afterwards, so it is advised to use it without and perhaps update the topics later.

**Comment by hari-chalise** [comment]
!pip install bertopic
!pip install sentence-transformers
!pip install pandas numpy scikit-learn
import bertopic
print(f"BERTopic version: {bertopic.__version__}")
# !pip install pandas --upgrade

**Load Dataset**
from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

data_path = '/content/drive/My Drive/cleaned_ekantipur_news_data.csv'
df = pd.read_csv(data_path, nrows=1000)
df = df.drop('title', axis=1)
df.to_csv('cleaned_ekantipur_news_data.csv', index=False)
print (df.head())
#Extract the news content into a list
documents = df['story'].tolist()
# documents_conv = [str(doc) for doc in documents] #This converts everything to string
documents[0]
# Print the top 10 rows

**Install required Library**

from sentence_transformers import SentenceTransformer
model = SentenceTransformer('paraphrase-multilingual-MiniLM-L12-v2')
# .to('cuda')
model.max_seq_length = 256
model

corpus_embedding = model.encode(documents, show_progress_bar = True)
len(corpus_embedding)


**Dimensionality Reduction**

from umap import UMAP
umap_model = UMAP(n_neighbors=15, n_components= 5, min_dist = 0.0, metric = 'cosine', random_state = 42)
umap_model

**Clustering**
from hdbscan import HDBSCAN
hdbscan_model = HDBSCAN(min_cluster_size=150, metric='euclidean', cluster_selection_method='eom', prediction_data= True)
hdbscan_model

**Count vectorizor**

from sklearn.feature_extraction.text import CountVectorizer
nepali_stop_words =  [
    'र', 'छ', 'को', 'मा', 'हो', 'लागि', 'भएको', 'बाट', 'साथै', 'गरेका',
    'जसले', 'गर्न', 'तर', 'थियो', 'तथा', 'गर्नु', 'सक्छ', 'त्यो', 'छन्', 'हुन्'
    # Add more Nepali stop words as needed
]
vectorizer_model= CountVectorizer(stop_words = nepali_stop_words, min_df=1, max_df=3, ngram_range =(1,2))
vectorizer_model

**Training Model**
from bertopic import BERTopic
topic_model = BERTopic(
    embedding_model = model,
    umap_model= umap_model,
    hdbscan_model= hdbscan_model,
    vectorizer_model= vectorizer_model,
    nr_topics = "auto",
    min_topic_size=2,
    # diversity=0.7,
    #hyperparameter
    top_n_words= 5,
    verbose=True
)
topics, probs=topic_model.fit_transform(documents, corpus_embedding)

**This is the Error**

![image](https://github.com/user-attachments/assets/45b28c3c-7654-43d7-b0c4-2666507dd836)

**Comment by hari-chalise** [comment]
![image](https://github.com/user-attachments/assets/2548ebc9-667d-4db6-ad46-4db75ff8653a)
This is full error

**Comment by hari-chalise** [comment]
Dear Maarten, Thanks for the feedback.
I have shared code in text. If you need i can share my collab code with you
also dataset in your mail. Please let me know what goes wrong in code. I
have no prior knowledge in python and learning With this research.

**Comment by hari-chalise** [comment]
In min_cluster_size param there is another error i.e

TypeError: BERTopic.__init__() got an unexpected keyword argument 'min_cluster_size'

**Comment by MaartenGr** [comment]
@hari-chalise I can imagine that it must be stressful completing your research within a limited timeframe. Do note though that all the time spent on this project comes from my spare time. This is not funded nor do I work on it during my day-to-day work. That means, especially during the holidays, that I will have less time to spend answering issues as my priority during those days is my family over this. I will have to be strict here as I cannot make any promises to answer all questions within a given timeframe. 

That said, the parameter `min_cluster_size` is to be used within `HDBSCAN` and not `BERTopic`. It is generally advised to use `HDBSCAN` parameters to control the number of clusters as that is a more stable procedure. 

With respect to the index issue. Could you tell me how many topics were created before attempting to use that function?

**Comment by hari-chalise** [comment]
Hello @MaartenGr , I sincerely apologize for any inconvenience caused. It’s never my intention to pressure you, as I understand how busy you must be. I’ve been trying to find a solution on my own but have encountered some difficulties. It would truly mean a lot if you could reply whenever it’s convenient for you. Thank you so much!
