### ISSUE TITLE
Specify Number of Workers

### ISSUE THREAD

**Issue by RumiAllbert** [MaartenGr/BERTopic#1013]
Is there any way to specify the number of workers during inference when running .transform()? I work on a server with a group of people; when running transform() all cores are taken up. Ideally, I would like to specify the number of resources that can be taken up.

**Comment by MaartenGr** [comment]
At the moment, this is something to be done manually for each sub-model. For example, many models within scikit-learn support the `n_jobs` parameters which allow you to speed things up quite a bit. So if that is something you are looking for, you would have to specify it for each sub-model that you define.

**Comment by RumiAllbert** [comment]
Thanks @MaartenGr .  I found another way to solve this. You can specify the number of threads available in the environment, limiting the number of cores used up. The following worked for me:

```
import os
os.environ["OMP_NUM_THREADS"] = "32"
```
