### ISSUE TITLE
Unknown error

### ISSUE THREAD

**Issue by sumantabasak** [MaartenGr/BERTopic#1015]
I've a document of 80K rows filled with reviews in each rows. Whenever I'm trying to run the algo, the following error I receive -
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
/opt/conda/lib/python3.7/site-packages/pandas/core/indexes/base.py in get_loc(self, key, method, tolerance)
   3360             try:
-> 3361                 return self._engine.get_loc(casted_key)
   3362             except KeyError as err:

/opt/conda/lib/python3.7/site-packages/pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

/opt/conda/lib/python3.7/site-packages/pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.Int64HashTable.get_item()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.Int64HashTable.get_item()

KeyError: 1688

The above exception was the direct cause of the following exception:

KeyError                                  Traceback (most recent call last)
/tmp/ipykernel_27/759115320.py in <module>
     10 
     11 # Run BERTopic model
---> 12 topics, probabilities = topic_model.fit_transform(amz_review['review_lemmatized_wo_punc'])

/opt/conda/lib/python3.7/site-packages/bertopic/_bertopic.py in fit_transform(self, documents, embeddings, y)
    344             embeddings = self._extract_embeddings(documents.Document,
    345                                                   method="document",
--> 346                                                   verbose=self.verbose)
    347             logger.info("Transformed documents to Embeddings")
    348         else:

/opt/conda/lib/python3.7/site-packages/bertopic/_bertopic.py in _extract_embeddings(self, documents, method, verbose)
   2795             embeddings = self.embedding_model.embed_words(documents, verbose)
   2796         elif method == "document":
-> 2797             embeddings = self.embedding_model.embed_documents(documents, verbose)
   2798         else:
   2799             raise ValueError("Wrong method for extracting document/word embeddings. "

/opt/conda/lib/python3.7/site-packages/bertopic/backend/_base.py in embed_documents(self, document, verbose)
     67             that each have an embeddings size of `m`
     68         """
---> 69         return self.embed(document, verbose)

/opt/conda/lib/python3.7/site-packages/bertopic/backend/_sentencetransformers.py in embed(self, documents, verbose)
     61             that each have an embeddings size of `m`
     62         """
---> 63         embeddings = self.embedding_model.encode(documents, show_progress_bar=verbose)
     64         return embeddings

/opt/conda/lib/python3.7/site-packages/sentence_transformers/SentenceTransformer.py in encode(self, sentences, batch_size, show_progress_bar, output_value, convert_to_numpy, convert_to_tensor, device, normalize_embeddings)
    155         all_embeddings = []
    156         length_sorted_idx = np.argsort([-self._text_length(sen) for sen in sentences])
--> 157         sentences_sorted = [sentences[idx] for idx in length_sorted_idx]
    158 
    159         for start_index in trange(0, len(sentences), batch_size, desc="Batches", disable=not show_progress_bar):

/opt/conda/lib/python3.7/site-packages/sentence_transformers/SentenceTransformer.py in <listcomp>(.0)
    155         all_embeddings = []
    156         length_sorted_idx = np.argsort([-self._text_length(sen) for sen in sentences])
--> 157         sentences_sorted = [sentences[idx] for idx in length_sorted_idx]
    158 
    159         for start_index in trange(0, len(sentences), batch_size, desc="Batches", disable=not show_progress_bar):

/opt/conda/lib/python3.7/site-packages/pandas/core/series.py in __getitem__(self, key)
    940 
    941         elif key_is_scalar:
--> 942             return self._get_value(key)
    943 
    944         if is_hashable(key):

/opt/conda/lib/python3.7/site-packages/pandas/core/series.py in _get_value(self, label, takeable)
   1049 
   1050         # Similar to Index.get_value, but we do not fall back to positional
-> 1051         loc = self.index.get_loc(label)
   1052         return self.index._get_values_for_loc(self, loc, label)
   1053 

/opt/conda/lib/python3.7/site-packages/pandas/core/indexes/base.py in get_loc(self, key, method, tolerance)
   3361                 return self._engine.get_loc(casted_key)
   3362             except KeyError as err:
-> 3363                 raise KeyError(key) from err
   3364 
   3365         if is_scalar(key) and isna(key) and not self.hasnans:

KeyError: 1688

**Comment by MaartenGr** [comment]
Seeing as the issue lies within sentence-transformers, I believe there might be an issue with your environment. I would advise starting from a completely fresh environment and re-installing BERTopic there. Also, I believe python 3.7 will stop getting updates soon, so it might be worthwhile to go with something like 3.9 or 3.10 instead.

**Comment by sumantabasak** [comment]
Tried with a fresh env (Using Kaggle Notebook), but the problem still persists. I'm using the following to block of code (Either of them are giving the same error). I'm using only 2K rows of data.

```
embedding_model = pipeline("feature-extraction", model="bert-base-uncased")
topic_model = BERTopic(embedding_model=embedding_model).fit(amz_review['review_final'])
```

```
# Initiate UMAP
umap_model = UMAP(n_neighbors=15, 
                  n_components=5, 
                  min_dist=0.0, 
                  metric='cosine', 
                  random_state=100)

# Initiate BERTopic
topic_model = BERTopic(umap_model=umap_model, language="english", calculate_probabilities=True)

# Run BERTopic model
topics, probabilities = topic_model.fit_transform(amz_review['review_final'])
```

**Comment by MaartenGr** [comment]
BERTopic takes in a list of str and not a pandas series, so converting to a list of strings might be beneficial in this case, although I am not entirely sure. Could you try that out? Also, if that does not work, could you create a fully reproducible example that I can try out?

**Comment by sumantabasak** [comment]
Converting to list of strings solved the problem. Many thanks.
