### ISSUE TITLE
Half document corpus belonging to topic -1

### ISSUE THREAD

**Issue by VioletRaven** [MaartenGr/BERTopic#1020]
Hello,

I have attempted various approaches to decrease the number of documents that pertain to the topic labeled -1, but my efforts have not yielded the desired outcome. I strongly suspect that the quality of the input documents I am providing may be a contributing factor. Would you happen to have any suggestions for how I might address this issue and achieve a more diversified topic definition?

Thank you!

![image](https://user-images.githubusercontent.com/34713088/220100522-2f00cc1d-36fe-449c-ae99-39f97f50c16e.png)

**Comment by MaartenGr** [comment]
There are a number of ways supported and suggested to use within BERTopic that you can find [here](https://maartengr.github.io/BERTopic/faq.html#how-do-i-reduce-topic-outliers). Seeing your results, I would suggest starting by going through the -1 documents first to see what is happening there. In some cases, the documents themselves might not contain that much information to actually contain a topic or to be contained within a cluster. 

For the topic representation itself, it is generally okay if there are outliers created as large outliers might actually hurt the topic representation step. However, for topic classification purposes this can definitely be troublesome. A nice way to handle this is by setting `calculate_probabilities=True` in HDBSCAN. This allows you to still generate outliers but assign them to clusters based on their soft-cluster probabilities. In other words, although a document is considered to be an outlier, you can still use its probabilities to all clusters to see which non-outlier topic it would suit best. 

Moreover, it is possible to play around with both the `min_samples` and `min_cluster_size` parameters in HDBSCAN as they, to some degree, handle the number of outliers that are being created. 

Finally, BERTopic allows you to reduce the number of outliers **after** having trained your model using `.reduce_outliers`. The benefit to this is that it allows you to quickly iterate over the possible strategies, their parameters, and a possible combination of strategies without having to re-train the model. 

The link mentioned above describes this all a bit more in detail and is the go-to source for outlier reduction in BERTopic.

**Comment by drob-xx** [comment]
@VioletRaven I wrote [TopicTuner](https://github.com/drob-xx/TopicTuner) to facilitate quickly tuning HDBSCAN to test its effect on clustering. I've found it helpful in gaining a deeper understanding about a give corpus including figuring out if there is a problem with the documents themselves.

**Comment by VioletRaven** [comment]
@MaartenGr Thank you for your prompt response, I will try to reduce the with `.reduce_outliers` topics as you suggest. I was already playing around with `min_samples` and `min_cluster_size` but they did not seem to influence topic -1 size for some reason.
@drob-xx Looks cool! The fun fact is that the model I was using had been already optimized by a somewhat similar custom wrapper I implemented myself. It would have been very helpful to know that you already worked on it :/. Nevertheless, asap I will try to check it out fully, so that I try different strategies and compare them to build the best model.

**Comment by MaartenGr** [comment]
Due to inactivity, I'll be closing this issue. Let me know if you want me to re-open the issue!
