### ISSUE TITLE
Further clustering on large topics, merged back into main result

### ISSUE THREAD

**Issue by mark-seamlessiot** [MaartenGr/BERTopic#1022]
Working with a dataset of ~4000 documents, around 80 clusters are created and from what I can see, it does a great job without much tweaking of settings. The issue that I am noticing is that some topics have ~20 documents and are fairly specific while others end up having 150-200 and are a little more generic.

I took the results of one of these topics that had 200 documents and tweaked some umap settings and ran the model again and it was able to fairly decently break these up into ~8 more subtopics.

I noticed in the recent changelog.. "Chain models to perform fine-grained fine-tuning"

Is it at all possible to merge these results together to have those 8 subtopics created replace the 1 large topic from the original?

**Comment by MaartenGr** [comment]
You cannot update the original model as that would require internally re-fitting the HDBSCAN with your new labels which are not possible for most clustering techniques. However, if you have updated labels, you can perform [manual topic modeling](https://maartengr.github.io/BERTopic/getting_started/manual/manual.html) instead. This only requires you to pass the documents and labels to re-create the topic model with the newly updated labels.

**Comment by mark-seamlessiot** [comment]
I will try this, thanks!
