### ISSUE TITLE
Topic Distribution instead of a Single Topic for Test Document

### ISSUE THREAD

**Issue by rudra0713** [MaartenGr/BERTopic#1026]
Hi,
   I have a large number of articles (let's call them training articles) on which I first call `.fit()` method. Once I fit a BertTopic model, I then use the `.transform()` method on a small number of new articles (let's call them test articles). Hoever, the `transform()` method returns only one topic with a probability for each test article. Instead of that, is it possible to get a topic distribution for the test article based on the topics the model learnt based on training articles?

**Comment by MaartenGr** [comment]
There are two ways for creating topic distributions. First, is by leveraging the function `.approximate_distribution` as described in the documentation [here](https://maartengr.github.io/BERTopic/getting_started/distribution/distribution.html). It makes an approximation of the topic distribution in a single document. The second is by leveraging `calculate_probabilities=True`. This creates a topic-document probability matrix that can be used as an approximation of the distribution of topics in a document.

**Comment by rudra0713** [comment]
Thanks.
