### ISSUE TITLE
word-word and word-document similarity

### ISSUE THREAD

**Issue by SjoerdBraaksma** [MaartenGr/BERTopic#1027]
Hello, 

Coming from top2vec to BERTopic, I see some things bertopic does better (better topics with lower amount of documents).
However, one of the features of top2vec is that you can do a semantic search for words/documents, retrieving the closest words/documents/topics to those words (search_topics_by_vector, search_documents_by_documents, search_documents_by_keywords, etc)

This is perfect for my use-case, as my end users want to be able to click on a topic word, and dive deeper into the relationship between that topic word and other words in the topic. Since all words and documents are embedded, this should be possible in theory by running cosine similarity for each word in that topic.

I was however, wondering if this is a built-in function of Berttopic, or if I have to build it on my own? I couldn't find it in the documentation.

**Comment by MaartenGr** [comment]
In BERTopic, there is a `.find_topics` function that allows you to input any word, phrase, or document and find the closest related topic. This is done by embedding the input and applying cosine similarity together with the topic embedding. 

One major component of BERTopic is that the clustering process and topic representation process are relatively independent of one another, the only thing the topic representation needs is some documents and labels. The benefit of this approach is that it prevents the need to save documents, document embeddings, and word embeddings in BERTopic which not only can make the model quite large, it is a difficult dependency to then control for. As a result, however, this means that it is not possible to perform a semantic search for documents, as the embeddings are not saved within BERTopic. Instead, you would have to save the document and word embeddings and create a semantic search engine outside of BERTopic.

**Comment by SjoerdBraaksma** [comment]
Got it, thanks for the quick and complete answer!
