### ISSUE TITLE
Issue importing from bertopic.representation

### ISSUE THREAD

**Issue by ellenealds** [MaartenGr/BERTopic#1028]
Hi Martin, I am getting this 'TypeError: __init__() got an unexpected keyword argument 'custom_msg'' when importing from bertopic.representation. 

I had a similar issue with openai, I ! pip installed it on my IDE and it then gave me the langchain error which pip install does not fix.

from bertopic.representation import MaximalMarginalRelevance

ModuleNotFoundError                       Traceback (most recent call last)
c:\Users\Elle\anaconda3\lib\site-packages\bertopic\representation\__init__.py in <module>
     29 try:
---> 30     from bertopic.representation._langchain import LangChain
     31 except ModuleNotFoundError:

c:\Users\Elle\anaconda3\lib\site-packages\bertopic\representation\_langchain.py in <module>
      3 from typing import Mapping, List, Tuple
----> 4 from langchain.docstore.document import Document
      5 from bertopic.representation._base import BaseRepresentation

ModuleNotFoundError: No module named 'langchain'

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_33368/1712655682.py in <module>
----> 1 from bertopic.representation import MaximalMarginalRelevance

c:\Users\Elle\anaconda3\lib\site-packages\bertopic\representation\__init__.py in <module>
     31 except ModuleNotFoundError:
     32     msg = "`pip install langchain` \n\n"
---> 33     LangChain = NotInstalled("langchain", "langchain", custom_msg=msg)
     34 
     35 # POS using Spacy

TypeError: __init__() got an unexpected keyword argument 'custom_msg'

**Comment by MaartenGr** [comment]
Odd, I have not encountered this issue before and it working well on my side. Could you perhaps start from a fresh environment and install BERTopic there?

**Comment by MaartenGr** [comment]
Due to inactivity, I'll be closing this issue. Let me know if you want me to re-open the issue!
