### ISSUE TITLE
Speeding up BERTopic via Compute resources

### ISSUE THREAD

**Issue by tchopra17** [MaartenGr/BERTopic#1030]
Hi, I've been successfully using BERTopic for a while and have done a lot of the recommended ways to speed up the process such as pre-computing embeddings, using umap, hdbscan, etc. I was wondering if it was possible to utilize more compute such as GPU's or more CPU's to speed up .fit specifically

**Comment by beckernick** [comment]
If you haven't already tried using GPUs for UMAP and HDBSCAN, you may be interested in [this blog post](https://medium.com/rapids-ai/faster-topic-modeling-with-bertopic-and-rapids-cuml-5c7559aba898).

**Comment by MaartenGr** [comment]
Due to inactivity, I'll be closing this issue. Let me know if you want me to re-open the issue!
