### ISSUE TITLE
How Dynamic Topic Modeling was conducted?

### ISSUE THREAD

**Issue by YukunYangNPF** [MaartenGr/BERTopic#104]
I feel like it just adds some post-modeling analysis that counts the number of topics based on the time.

However, shouldn't real Dynamic Topic Modeling also incorporated time as a feature when modeling, like ldaseql models?

**Comment by MaartenGr** [comment]
Fortunately, BERTopic does implement DTM with time as a feature. It is implemented in BERTopic by calculating the c-TF-IDF representation at each timestep. That is where time as a feature can be found first. The resulting visualization shows you how a certain topic is represented at each time if you hover over each point. In other words, aside from counting the number of topics based on the time, it also extracts the topic representation at that time. 

Second, if you set `evolutionary_tuning` to True, then you will see the full potential of DTM. A topic representation at timestep *`t`* can be fine-tuned evolutionary by averaging its c-TF-IDF representation with that of the c-TF-IDF representation at timestep *`t-1`*. This is done for each topic representation allowing for the representations to evolve over time.

You can find the full explanation of how DTM is implemented in BERTopic [here](https://maartengr.github.io/BERTopic/tutorial/topicsovertime/topicsovertime.html). 

Hopefully, this helps a bit. Let me know if you have any other questions!

**Comment by florianlorisch** [comment]
Hi Maarten, I just noticed that the link isn't working anymore. Did the full explanation move to: https://maartengr.github.io/BERTopic/getting_started/topicsovertime/topicsovertime.html ? Do you have any recommendations regarding a detailed explanation of BERTopic and Dynamic Topic Modeling with BERTopic in particular? 

Best
Florian

**Comment by MaartenGr** [comment]
Yes, it indeed moved to the link you provided. It should contain all information about Dynamic Topic Modeling with BERTopic. For BERTopic in general, I would advise going through the [algorithm](https://maartengr.github.io/BERTopic/algorithm/algorithm.html) and the corresponding [quickstart](https://maartengr.github.io/BERTopic/getting_started/quickstart/quickstart.html).

**Comment by ShyamGanesh13** [comment]
Hi Maarten, 
Is it possible to use DTM is cases like on-the-fly training. Like I mean, I get few documents from user at every minute, Can I use DTM with timestamps in those cases. Ig the Online Topic Modelling works better for above mentoined usecase, but still I have timestamps of the documents to be considered.
Thanks in advance...

**Comment by MaartenGr** [comment]
@ShyamGanesh13 That is currently not implemented since the online approach does not consider any previous timestamps. Why would you want the timestamps of the documents to be considered? Are you looking for topic extraction within certain sets of timestamps? If so, you can [`merge`](https://maartengr.github.io/BERTopic/getting_started/merge/merge.html) at each set of timestamp.
