### ISSUE TITLE
How downgrade BERTopic to Version 12

### ISSUE THREAD

**Issue by Na987** [MaartenGr/BERTopic#1040]
Hi all

My model was saved with version BERT V12

Now, After upgrading the BERTopic to 14, some coding does not work 

How can downgrade the Version of the BERTopic from V14 to V12 ?????

**Comment by MaartenGr** [comment]
You can downgrade a pip installed pypi package with `pip install --upgrade bertopic==0.12.0`. However, if you saved a model with BERTopic v0.12, then it might also be necessary to make sure that the entire environments are identical, including dependency versions such as numpy, hdbscan, and umap.
