### ISSUE TITLE
Transformer "gpt2" representation_model produces "few-letter topics"

### ISSUE THREAD

**Issue by fgleRTDCE345** [MaartenGr/BERTopic#1041]
When I don't use the representation_model parameter for BERTopic, it produces the topics as a nice list of understandable keywords, works as expected.

After that I tried using the example Transformers "gpt2" example provided [here](https://github.com/MaartenGr/BERTopic/releases/tag/v0.14.0).

It results in the following topics (using get_topic_info())
<img width="302" alt="Screenshot 2023-02-24 at 10 20 33" src="https://user-images.githubusercontent.com/93039500/221140672-9bc332b3-dbff-4c1c-96b1-17e3db393ffa.png">

Do you know what's up?

**Comment by mplockhart** [comment]
I also had this issue, and an alternative was provided here in issue  https://github.com/MaartenGr/BERTopic/issues/1036.

**Comment by fgleRTDCE345** [comment]
> I also had this issue, and an alternative was provided here in issue #1036.

Thanks, I will try out another transformer model.
