### ISSUE TITLE
Issue with loading BERTopic model with KeyError: 6 ??

### ISSUE THREAD

**Issue by herbertwang0922** [MaartenGr/BERTopic#1046]
Hello, I am trying to load an BERTopic model (over 6 GB): 
topic_model = BERTopic.load("C:\\xxxx\\my_model")

Then I get the following error message:

KeyError                                  Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_11124\2516624883.py in <module>
----> 1 topic_model = BERTopic.load("C:\\xxxx\\my_model")

~\Anaconda3\lib\site-packages\bertopic\_bertopic.py in load(cls, path, embedding_model)
   2748                 topic_model.embedding_model = select_backend(embedding_model)
   2749             else:
-> 2750                 topic_model = joblib.load(file)
   2751             return topic_model
   2752 

~\Anaconda3\lib\site-packages\joblib\numpy_pickle.py in load(filename, mmap_mode)
    575         filename = getattr(fobj, 'name', '')
    576         with _read_fileobject(fobj, filename, mmap_mode) as fobj:
--> 577             obj = _unpickle(fobj)
    578     else:
    579         with open(filename, 'rb') as f:

~\Anaconda3\lib\site-packages\joblib\numpy_pickle.py in _unpickle(fobj, filename, mmap_mode)
    504     obj = None
    505     try:
--> 506         obj = unpickler.load()
    507         if unpickler.compat_mode:
    508             warnings.warn("The file '%s' has been generated with a "

~\Anaconda3\lib\pickle.py in load(self)
   1210                     raise EOFError
   1211                 assert isinstance(key, bytes_types)
-> 1212                 dispatch[key[0]](self)
   1213         except _Stop as stopinst:
   1214             return stopinst.value

KeyError: 6

I am really not sure what KeyError: 6 means? I actually loaded it before successfully but really get confused why it was not working this time. Any suggestion would be appreciated!!

**Comment by MaartenGr** [comment]
Typically, when a model cannot be correclty loaded, there is a difference between the versions of BERTopic and its dependencies when you saved the model and when you tried to load the model. For example, a model trained in BERTopic v0.13 cannot be loaded in v0.14 and vice-versa. In practices, this means that it is important to make sure that version control is performed in order to prevent any conflicts.

**Comment by herbertwang0922** [comment]
> 

Thanks a lot for your prompt response and it is useful. 
 I changed the version of BERTopic and python, it now works for me.
