### ISSUE TITLE
BERTopic generates 1 large topic (27% of docs) and 200 small topics

### ISSUE THREAD

**Issue by wouter-suren** [MaartenGr/BERTopic#1049]
Hi there,

It seems that the major topic is not an actual topic but more like a mix of all different types of topics (I'm not talking about the -1 outlier topic btw, but the first real topic). It's keywords are: food, would, street, like, company, email, products, business, new

Next to that it generates 200 small topics, each holding between 0-2% of the document population. Seems about right.

Is there I way I can configure the clustering so that it tries to spread out this blob of documents of topic 1 into smaller ones?

Here is my code:
```
sentence_model = SentenceTransformer("all-MiniLM-L6-v2")
embeddings = sentence_model.encode(df, show_progress_bar=True)
umap_model = UMAP(n_neighbors=15, n_components=5, min_dist=0.0, metric='cosine', random_state=42)
stopwords = stopwords.words('english').  # this is from nltk.corpus import stopwords
vectorizer_model = CountVectorizer(min_df=20, ngram_range=(1,5), stop_words=stopwords)
hdbscan_model = HDBSCAN(min_cluster_size=60, metric='euclidean', prediction_data=True)
hdbscan_model=hdbscan_model, umap_model=umap_model, nr_topics="auto")
topic_model = BERTopic(vectorizer_model=vectorizer_model, hdbscan_model=hdbscan_model, umap_model=umap_model, nr_topics="auto")
topics, probs = topic_model.fit_transform(df, embeddings)
```

Thanks for your reply!

**Comment by drob-xx** [comment]
Hi @wouter-suren, I wrote [TopicTuner](https://github.com/drob-xx/TopicTuner) as a tool to help BERTopic users quickly iterate over many different HDBSCAN parameters to change the size of HDBSCAN clusters. You might want to try different settings and get a better sense of why you are getting that one large cluster. It all depends on your input data of course but in my experience the clusters created from the transformer embeddings are seldom "wrong" in that I've never seen a cluster that doesn't have some logical connection that sets them apart from the other clusters - but they may be reflecting an imbalance in the overall dataset. In once case I saw a corpus of news articles being essentially divided into "sports/non-sports" and there was no way of getting the "non-sports" to cluster reasonably (entertainment, politics, crime, etc. etc.) until I broke off the "sports". Something like that may be happening here. TopicTuner is completely compatible with BERTopic and you can use the model you have already created or create a new one and then export when you have parameters that work for you.
