### ISSUE TITLE
Divide by Zero error when trying to use KeyphraseCountVectorizer

### ISSUE THREAD

**Issue by Pratik--Patel** [MaartenGr/BERTopic#1050]
I am trying to use `KeyphraseCountVectorizer` using the example provided here https://github.com/TimSchopf/KeyphraseVectorizers#topic-modeling-with-bertopic-and-keyphrasevectorizers

```
from keyphrase_vectorizers import KeyphraseCountVectorizer
from bertopic import BERTopic
from sklearn.datasets import fetch_20newsgroups

# load text documents
docs = fetch_20newsgroups(subset='all',  remove=('headers', 'footers', 'quotes'))['data']
# only use subset of the data 
docs = docs[:5000]

# train topic model with KeyphraseCountVectorizer
keyphrase_topic_model = BERTopic(vectorizer_model=KeyphraseCountVectorizer())
keyphrase_topics, keyphrase_probs = keyphrase_topic_model.fit_transform(docs)

```

This produces following error.

```
RuntimeWarning: divide by zero encountered in true_divide
  idf = np.log((avg_nr_samples / df)+1)
```

Any idea about this would be very helpful.

**Comment by MaartenGr** [comment]
I am not entirely sure, seeing as I am not that closely familiar with the `KeyphraseCountVectorizer` code, but for some reason it seems to create keywords in the document frequency that are zero, which typically should not happen. I think you can account for this by using a different weighting scheme (BM25-inspired):

```python
from bertopic.vectorizers import ClassTfidfTransformer

ctfidf_model = ClassTfidfTransformer(bm25_weighting=True)
```

However, that feels like fixing the error and not the underlying problem. It may be worthwhile to also open an issue at the related package.

Having said that, the `KeyphraseCountVectorizer` can be quite slow as it tries to parse each individual documents which make it difficult to scale to larger datasets. Instead, it might be worthwhile to check out the [`PartOfSpeech`](https://maartengr.github.io/BERTopic/getting_started/representation/representation.html#partofspeech) model in BERTopic. It employs a few tricks to minimize compute and still get POS-based output.

**Comment by Pratik--Patel** [comment]
Thank you very much for the swift response. Using `ClassTfidfTransformer` with `bm25_weighting` does fix the error.

**Comment by Pratik--Patel** [comment]
would it make any difference if we were to first call `fir_transform` on a model with some vectorizer model and then call `update_topics` on the same model with same vectorizer?

```
topic_model = BERTopic(ctfidf_model=ctfidf_model, vectorizer_model=vectorizer_model)

topics, probs = topic_model.fit_transform(docs, embeddings)

topic_model.update_topics(docs, topics, vectorizer_model=vectorizer_model, ctfidf_model=ctfidf_model)
```

Reading up on `update_topics` it seems like it can be useful to fine tune topic representations by providing a vectorizer with different n_gram range for example. However, here the same vectorizer model is used. 

Upon executing this the topics DO get altered which seems puzzling to me. I expected that `update_topics` with same params would be a no-op but it doesn't seem to be!

**Comment by MaartenGr** [comment]
In general, yes it should create the same topics. Could you perhaps create a reproducible example for me to try out? That will make it easier to see if and where something is going wrong.

**Comment by MaartenGr** [comment]
Due to inactivity, I'll be closing this issue. Let me know if you want me to re-open the issue!
