### ISSUE TITLE
top_n_words attribute as no impact

### ISSUE THREAD

**Issue by thomaslprru** [MaartenGr/BERTopic#1053]
Hello, 

I have been using BERTopic for a few weeks and I notice that the **_top_n_words_** variable does not seem to work. 

I tried to specify a **top_n_words** value when training the model _(case 1)_ or when editing the topics _(case 2)_ but no change when I run the `.get_topic()` method I only get 10 items each time (10 is the default value).

Is there something I am doing wrong? 

Case 1 : 
```
model_final = BERTopic(language="french", seed_topic_list=seed_topic_list,
         hdbscan_model=hdbscan_model,vectorizer_model=vectorizer_model,representation_model=representation_model,top_n_words=15)

model_final.get_topic(topic=2)

#10 items
out : [('enfants', 0.05930784344617617),
 ('bébé', 0.02813579118204907),
 ('enfants adorent', 0.02102089660324487),
 ('famille', 0.014705242857345143),
 ('fils adore', 0.012346169507696007),
 ('enfant', 0.011270845628718218),
 ('produit enfants', 0.011137359628723902),
 ('toute famille', 0.010044293076524389),
 ('enfants aiment', 0.009537711781973842),
 ('petits enfants', 0.009226494079153498)]

```

Case 2 :

```
representation_model = MaximalMarginalRelevance(diversity=0.2)
 vectorizer_model = CountVectorizer(stop_words=stop_words_fr, ngram_range=(1, 3),max_features=3_500,min_df=10)
model.update_topics(texts, vectorizer_model=vectorizer_model,representation_model=representation_model,top_n_words=15)

model_final.get_topic(topic=2)

#10 items
out : [('enfants', 0.05930784344617617),
 ('bébé', 0.02813579118204907),
 ('enfants adorent', 0.02102089660324487),
 ('famille', 0.014705242857345143),
 ('fils adore', 0.012346169507696007),
 ('enfant', 0.011270845628718218),
 ('produit enfants', 0.011137359628723902),
 ('toute famille', 0.010044293076524389),
 ('enfants aiment', 0.009537711781973842),
 ('petits enfants', 0.009226494079153498)]
```

I also tried to call `model_final.visualize_barchart(n_words=15)` but I can't see more than 10 items by topic.

Does **top_n_words** have no effect when the ngram range has a value greater than 1 (because we are talking about a word and not a ngram)?

Thanks in advance

### Informations
BERTopic version : 0.14.0
Platform : Google Colab

**Comment by dkirman-re** [comment]
Have you tried passing in the `top_n_words` argument into your `representation_model` as well? 
I can't speak to your first example, but in your second case you're only passing in a value for `diversity`, in which case `top_n_words` will default to 10.

**Comment by thomaslprru** [comment]
for the first case, it seems that using gpu fixes the problem...  

thank you for your help 😄
