### ISSUE TITLE
About document-topic matric

### ISSUE THREAD

**Issue by shaylynch** [MaartenGr/BERTopic#106]
Hello~
I have a question about how to get the document-topic matric.
Can you please help me with it? Thank you~

**Comment by MaartenGr** [comment]
You can extract the topics per document as follows:

```python
from bertopic import BERTopic

topic_model = BERTopic()
topics, _ = topic_model.fit_transform(docs)
```

Then you simply use `topics` to access the topics per document. 

If you want to extract the probabilities of topics per document, run the following:

```python
from bertopic import BERTopic

topic_model = BERTopic(calculate_probabilities=True)
topics, probabilities = topic_model.fit_transform(docs)
```

You can use `probabilities` to access the probabilities of topics per document. You can find more extensive documentation [here](https://maartengr.github.io/BERTopic/).

**Comment by shaylynch** [comment]
Dear Maarten, thank you so much! It works! You help me a lot~
