### ISSUE TITLE
visualize_hierarchy has new merged topics out of order 

### ISSUE THREAD

**Issue by zilch42** [MaartenGr/BERTopic#1063]
Hi Maarten,

I think I have encountered another topic ordering issue though I don't think it is directly related to #1024 (I do have an outlier cluster in this case and the issue appears to be present both in v0.14.0 and v0.14.1 so it wasn't introduced by the recent fix for #1024 - thankyou for that btw)

The descriptions of the merged topics displayed on hover from `visualize_hierarchy()` often don't make any sense with respect to the topics they are apparently merging, and also differ from the hierarchy presented in `get_topic_tree()`. 

Based on the code below, the merged topic from 191 and 2 should be 'test_hello_whatta_ites_cheek' according to `get_topic_tree`, but in `visualize_hierarchy` that topic is 'weaver_trail_spence_cooper_court'.

```
from bertopic import BERTopic
from sklearn.datasets import fetch_20newsgroups
from sentence_transformers import SentenceTransformer
import numpy as np

data = fetch_20newsgroups(subset='all',  remove=('headers', 'footers', 'quotes'))
docs = data['data']

embedding_model = SentenceTransformer("all-MiniLM-L6-v2")
embeddings = embedding_model.encode(docs, show_progress_bar=True)

topic_model = BERTopic(embedding_model=embedding_model)
topics, probs = topic_model.fit_transform(docs, embeddings)

hierarchical_topics = topic_model.hierarchical_topics(docs)

topic_model.visualize_hierarchy(hierarchical_topics=hierarchical_topics)
```

![Hierarchy](https://user-images.githubusercontent.com/39004650/222635712-5e180b50-4a58-42fb-a4e6-cf9e7c103013.png)

```
tree = topic_model.get_topic_tree(hierarchical_topics)
print(tree)
```
![Tree](https://user-images.githubusercontent.com/39004650/222635729-9b6b7eab-bb34-4ce5-824a-d6b68a0e675f.png)

I believe it is an alignment issue in `visualize_hierarchy`. The merged topics in `get_topic_tree` look really good to me. They make a lot of sense. It's just the merged topics on the visualisation that don't seem to line up properly.

**Comment by MaartenGr** [comment]
I believe this issue is related to #1021 and #923. You can find a quick fix there but I am not sure whether that works across all use cases.

**Comment by rubypnchl** [comment]
Hi MaartenGr,

I am trying to have a look at the tree hierarchy of the topics. But, I am not sure why there are two almost distant topics are merged into one topic.

![image](https://github.com/MaartenGr/BERTopic/assets/37774828/d5157cb6-141a-422e-a08b-1039951377d3)

To validate the above, I fetched top representative documents for topic 3 and topic 1 and manually analyze them and also computed cosine similarity and Euclidean distance between these documents of both topics. These metrics also show that these topics are very distant from each other but then why they are merged?
Kindly suggest to me why BERTopic is showing this random behavior.

**Comment by MaartenGr** [comment]
@rubypnchl With hierarchical topic modeling, the representations of each topic is compared to all others and merged with the most similar other topic. It might happen that when no other similar topics are found, they take the one that is most similar even with the most similar isn't actually that similar. Hierarchical topic modeling in BERTopic uses [linkage clustering](https://docs.scipy.org/doc/scipy/reference/generated/scipy.cluster.hierarchy.linkage.html) which might be a good idea to read through to get more feeling with the subject.
