### ISSUE TITLE
Using different new versions of bertopic has completely different results, how to change to the previous one?

### ISSUE THREAD

**Issue by YangRui525** [MaartenGr/BERTopic#1067]
Hello!

A month ago I used bertopic (0.13.0) for analysis, today I used bertopic (0.14.0) and found that the results have changed dramatically, even if I reused bertopic (0.13.0) I can't restore it, how can I sovle it?

Thank you!

**Comment by MaartenGr** [comment]
If you are using the default dimensionality reduction model, then it is likely that the results changed due to its stochastic behavior. You can find more about that in the [FAQ](https://maartengr.github.io/BERTopic/faq.html#why-are-the-results-not-consistent-between-runs).

**Comment by NUSRui** [comment]
Thank you very much!
