### ISSUE TITLE
seed_topic_list not working

### ISSUE THREAD

**Issue by Aymen-lab** [MaartenGr/BERTopic#1070]
Hi, 
first of all thank you for the great work :)
Unfortuanatly seed_topic_list is not working properly. I tried the code below (as in your documentation) but I got this error:
---------------------------------------------------------------------------------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-5-008bea1a088d> in <module>
      9 
     10 topic_model = BERTopic(seed_topic_list=seed_topic_list)
---> 11 topics = topic_model.fit_transform(docs)

/opt/conda/lib/python3.7/site-packages/bertopic/_bertopic.py in fit_transform(self, documents, embeddings, y)
    353         # Reduce dimensionality
    354         if self.seed_topic_list is not None and self.embedding_model is not None:
--> 355             y, embeddings = self._guided_topic_modeling(embeddings)
    356         umap_embeddings = self._reduce_dimensionality(embeddings, y)
    357 

/opt/conda/lib/python3.7/site-packages/bertopic/_bertopic.py in _guided_topic_modeling(self, embeddings)
   2965         for seed_topic in range(len(seed_topic_list)):
   2966             indices = [index for index, topic in enumerate(y) if topic == seed_topic]
-> 2967             embeddings[indices] = np.average([embeddings[indices], seed_topic_embeddings[seed_topic]], weights=[3, 1])
   2968         return y, embeddings
   2969 

<__array_function__ internals> in average(*args, **kwargs)

/opt/conda/lib/python3.7/site-packages/numpy/lib/function_base.py in average(a, axis, weights, returned)
    405             wgt = wgt.swapaxes(-1, axis)
    406 
--> 407         scl = wgt.sum(axis=axis, dtype=result_dtype)
    408         if np.any(scl == 0.0):
    409             raise ZeroDivisionError(

/opt/conda/lib/python3.7/site-packages/numpy/core/_methods.py in _sum(a, axis, dtype, out, keepdims, initial, where)
     45 
     46 def _sum(a, axis=None, dtype=None, out=None, keepdims=False,
---> 47          initial=_NoValue, where=True):
     48     return umr_sum(a, axis, dtype, out, keepdims, initial, where)
     49 

TypeError: No loop matching the specified signature and casting was found for ufunc add

---------------------------------------------------------------------------------------------------------------
Code:

from bertopic import BERTopic
from sklearn.datasets import fetch_20newsgroups

docs = fetch_20newsgroups(subset='all',  remove=('headers', 'footers', 'quotes'))["data"]

seed_topic_list = [["drug", "cancer", "drugs", "doctor"],
                   ["windows", "drive", "dos", "file"],
                   ["space", "launch", "orbit", "lunar"]]

topic_model = BERTopic(seed_topic_list=seed_topic_list)
topics, probs = topic_model.fit_transform(docs)

**Comment by MaartenGr** [comment]
I believe this has something to do with versions of some specific dependencies. This is a known issue for which you can find guidance om [here](https://github.com/MaartenGr/BERTopic/issues/866).

**Comment by Aymen-lab** [comment]
Thank you for the quick response!
