### ISSUE TITLE
Empty topics

### ISSUE THREAD

**Issue by Christixna** [MaartenGr/BERTopic#1072]
Hi Maarten,

I have the problem that I seem to get multiple empty topics. While most of them look good, I get for example "7____" or "24____". I have set min_topic_size to 10. Do you have any idea what the problem might be?

Many thanks
Christina

**Comment by MaartenGr** [comment]
Most likely, that is because the documents that make up that topic are likely to be empty or near-empty. Could you check what kind of documents you have in those topics?

**Comment by Christixna** [comment]
Yes, that's true. I do not have blank documents, but I do have documents that, for instance, consist of only one word. Originally I had longer documents and then I applied sentence splitting to avoid truncating any document (all sentences/documents now contain less or 128 segments). But it is the nature of my text data, that sentences are not always well-formulated, but a bit fragmented (resulting in several "one sentence" phrases).

**Comment by MaartenGr** [comment]
In that case, if the documents only contain a single word they might get removed either due to preprocessing (CountVectorizer) or because they have very low c-TF-IDF values. Personally, I would advise removing those single-word documents as that will prevent those empty topics from being created. Other than that, it is not necessarily something that hurts the model.

**Comment by Christixna** [comment]
I see, thank you, that makes sense. I mean, these smaller documents come from the preprocessing where I split my original documents into smaller pieces to make their length less than or equal to 128 segments. If I instead increased the maximum segment length to 508/509 and kept most of my document in its original length, would you expect any loss in performance (e.g., because the model is optimized for 128 segments)?

**Comment by MaartenGr** [comment]
If it is possible, I would split the documents up into sizes that match with the underlying embedding model's token limit. That would typically result in the most accurate representations. During that process, I would simply remove those smaller pieces that only contain one or two words.

**Comment by Christixna** [comment]
ok, I see! Thank you!
