### ISSUE TITLE
remove stop words from saved model 

### ISSUE THREAD

**Issue by kimkyulim** [MaartenGr/BERTopic#1076]
Hi. @MaartenGr 

I want to remove stop words from the saved BERTopic model and update the model again.

I looked up the official document and found that there was no method to update the keywords.

Maybe I didn't find it?

**Comment by MaartenGr** [comment]
It is actually a core component of BERTopic, namely the `.update_topics` function. It allows you to update the topic representations **after** having trained the model and **without** the need to re-train it. The great advantage of this is that you can then play with representation models, CountVectorizers, etc. to get the type of labels that you are looking for. You can find more about that [here](https://maartengr.github.io/BERTopic/getting_started/topicrepresentation/topicrepresentation.html#update-topic-representation-after-training). 

Having said that, it does seem that this page deserves some more information and some more examples on how to approach it. I think it is an important feature and perhaps the documentation should be a bit more extensive there.
