### ISSUE TITLE
topics_per_class multiprocessing

### ISSUE THREAD

**Issue by pjmnoble** [MaartenGr/BERTopic#1078]
Wow, Bertopic is fantastic.
I am modelling a dataset of 1 million clinical narratives and generate topics per class for a bunch of features. THe fit_transform is beautifully accelerated by my humble A4000 card but when i come to running topics per class for each of my features I end up with a long wait as a single core plods throught the work.

I wondered if I am mis-configuring and could leverage more CPU cores (I have eleven more) to help here. 

Thankes for making BERTopic . .  

PJ

**Comment by MaartenGr** [comment]
The `topics_per_class` method is not doing any GPU-work as it only focuses on creating localized topic representations through c-TF-IDF calculations. You could speed it up by parallelizing the following:

https://github.com/MaartenGr/BERTopic/blob/7d45cf710aefff178d54403989e90432e0c49910/bertopic/_bertopic.py#L781

but that requires some internal structure to change.

**Comment by pjmnoble** [comment]
Yup, guessed the GPU was not needed during this bit.
Have parallelised a few things in the past and will see what I can do
Once again, thanks for producing this fantastic tool

PJ
