### ISSUE TITLE
question with topics_over_time

### ISSUE THREAD

**Issue by MrRabbit12** [MaartenGr/BERTopic#1079]
hello~ GREAT thanks for your elegnant model~
### There is something wrong with your  topics_over_time however, when I try drawing my own graph about topics over time. The language is Chinese.
I find the line  always went horizontally, and every topic value was 1.
`vectorizer = CountVectorizer(tokenizer=tokenize_zh,stop_words=stopwords)` 
`sentence_model = SentenceTransformer("paraphrase-multilingual-mpnet-base-v2")`
`embeddings = sentence_model.encode(contents, show_progress_bar=False)`
`topic_model = BERTopic(
                        language="multilingual",
                        embedding_model=sentence_model, 
                        vectorizer_model=vectorizer
                      )`
`topics, _ = topic_model.fit_transform(contents,embeddings)`
`topics_over_time = topic_model.topics_over_time(contents, timestamps)`
`topic_model.visualize_topics_over_time(topics_over_time, topics=[0, 2, 3, 4, 5, 61])`

## And here's result:
![微信截图_20230308164806](https://user-images.githubusercontent.com/127282425/223666453-704ba62a-9efb-41e4-a431-79b21f23cea4.png)
Then I try your sample code, to my surprise, things still goes wrong:
![微信截图_20230308165202](https://user-images.githubusercontent.com/127282425/223667133-35066bc4-dc44-49b9-9472-6919f35f3bb2.png)

**Comment by MaartenGr** [comment]
When you use `timestamps` in `.topics_over_time`, it tries to create a representation for each unique timestamp. This means that if you have thousands of unique timestamps, there is not enough information for each timestamp to create a representation. In other words, you will need to use `nr_bins=20` when running `.topics_over_time`:

```python
topics_over_time = topic_model.topics_over_time(tweets, timestamps, nr_bins=20)
```

**Comment by MrRabbit12** [comment]
Thank u~VERY helpful!!!And, I wonder if there exists judgement criterion for the topics in this topic model? For example,we have perplexity and corherence to figure out the number about how many topics can have a better understanding of the materials. if there has&nbsp;counterpart in this topic model~?




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Maarten ***@***.***&gt;; 
发送时间: 2023年3月9日(星期四) 晚上8:29
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [MaartenGr/BERTopic] question with topics_over_time (Issue #1079)





 
When you use timestamps in .topics_over_time, it tries to create a representation for each unique timestamp. This means that if you have thousands of unique timestamps, there is not enough information for each timestamp to create a representation. In other words, you will need to use nr_bins=20 when running .topics_over_time:
 topics_over_time = topic_model.topics_over_time(tweets, timestamps, nr_bins=20)

**Comment by MrRabbit12** [comment]
To be specific， i mean the perplexity and corherence in LDA as criterion, if there exists similar criterion in Bertopic?

**Comment by MaartenGr** [comment]
Evaluation metrics are quite a difficult topic since there do not exist ground truths for topic modeling that are perfectly objective. You can find more about this discussion in the thread [here](https://github.com/MaartenGr/BERTopic/issues/90).

**Comment by MrRabbit12** [comment]
Thank u so much!!! I will check this conversation right now
