### ISSUE TITLE
Support for tamil language

### ISSUE THREAD

**Issue by sam9111** [MaartenGr/BERTopic#1084]
Does BERTopic have support for the Tamil language? I have been trying it out but have not gotten good results compared to a simple implementation of LDA.

**Comment by sam9111** [comment]
I can see that Tamil is included in the list of languages [here ](https://github.com/MaartenGr/BERTopic/blob/06dcd47a019854185a39146ed693d16dc3a27651/bertopic/backend/_utils.py). But on the [SBERT website](https://www.sbert.net/docs/pretrained_models.html), they say they support 50+ languages but "ta" is not included.

**Comment by MaartenGr** [comment]
The languages were taken from the SBERT website but it seems that the relevant list has been updated. Perhaps you can find a Tamil-supported model on the [HuggingFace](https://huggingface.co/) site. If not, then it might be worthwhile to use a somewhat language-independent embedding model, like LDA is using. For example, you can use [Scikit-Learn pipelines](https://maartengr.github.io/BERTopic/getting_started/embeddings/embeddings.html#scikit-learn-embeddings
) in BERTopic to perform the vectorization and use TF-IDF as that is somewhat language independent:

```python
from sklearn.pipeline import make_pipeline
from sklearn.decomposition import TruncatedSVD
from sklearn.feature_extraction.text import TfidfVectorizer

pipe = make_pipeline(
    TfidfVectorizer(),
    TruncatedSVD(100)
)

topic_model = BERTopic(embedding_model=pipe)

```

**Comment by sam9111** [comment]
Got it. Thank you! Can I do a PR to update the language list?

**Comment by MaartenGr** [comment]
Sure, that would be great!
