### ISSUE TITLE
seed topics on semi-supervised training ?

### ISSUE THREAD

**Issue by eangius** [MaartenGr/BERTopic#1086]
I have categorical data associated with most of my documents that I need to learn with & passed via the `y` parameter of `fit()`. At the same time, I would like to evolve topics by using `seed_topic_list` with previous time period results.

Are & could both nudging mechanisms be supported? Or are they mutually exclusive?

**Comment by MaartenGr** [comment]
Yes, both are supported simultaneously. More specifically, they are applied sequentially:

https://github.com/MaartenGr/BERTopic/blob/7d45cf710aefff178d54403989e90432e0c49910/bertopic/_bertopic.py#L353-L356

First the `seed_topic_list` and then the `y` parameter.

**Comment by eangius** [comment]
Perfect. That’s what I thought.
