### ISSUE TITLE
Reducing Outlier Topic (-1) and Updating the Probabilities per Doc

### ISSUE THREAD

**Issue by caterinadassergio89** [MaartenGr/BERTopic#1088]
Hello!
I've some trouble in understanding how it is possibile to update the probabilites per doc after removing outliers. 

Here is what I've done so far:
1) I've run the Bertopic model on a set of documents, it provides me 16 topics + 1 outlier topic. 
2) I, then, proceeded by aggregating the topics which were more similar among them and ended up with 3 topics - 1 outlier topic. 
3) I, then, reduced the outliers by using this string of code: 
```
new_topics_4 = topic_model_4.reduce_outliers(docs, topic_model_4.topics_, strategy="c-tf-idf")
topic_model_4.update_topics(docs, topics=new_topics_4)
```

Result: 
If i run:
`topic_model_4.get_topic_info()`
I get:

```
	Topic	Count	Name
0	0	873	0_privacy_policy_update_privacy policy
1	1	378	1_email_receive_want_click
2	2	255	2_personal_information_process_protection
```
Therefore, it seems it has correctly "re-assigned" all the documents to the three meaningful topics. 
However, if I look at the probabilities per doc, I still have a sum per row which does not add up to 1, suggesting me that the outlier topic is still there (if I got the line of reasoning on probabilites per doc correct):
`topic_model_4.probabilities_`
```
array([[4.54066733e-001, 1.65760958e-001, 2.84346496e-001],
       [2.81104844e-001, 5.73491882e-002, 1.18867647e-001],
       [1.95495056e-307, 1.00000000e+000, 6.10839417e-308],
       ...,
       [1.35133937e-001, 5.23869552e-002, 6.02877655e-001],
       [6.97369817e-001, 1.01607685e-001, 1.21526393e-001],
       [1.00000000e+000, 6.75227153e-308, 7.76368555e-308]])
```
`sum(topic_model_4.probabilities_[0])`
`0.9041741868541765`

How can I get also the proabilities_ updated, in addition to the topics?
Thanks a lot for the help and explanations
Have a great day
Caterina

**Comment by MaartenGr** [comment]
Good question, I believe that there might be a bug here. It is indeed the case that the probabilities do not sum to 1 and that what is missing is the probability of a document belonging to topic -1. In your case, you removed all -1 topics which are not taken into account when merging the probabilities. I'll have to look into this a bit deeper to see if there is a quick and easy fix for this.

**Comment by caterinadassergio89** [comment]
Hello Maarteen, 
thank you so much for your very fast and complete reply! I really appreciate it.
Please keep me updated if you have any update on this.
Thanks again
Caterina

**Comment by MaartenGr** [comment]
This should be fixed in the main branch, closing this issue for now.
