### ISSUE TITLE
IndexError when calculating topics_over_time after reducing topics

### ISSUE THREAD

**Issue by eyang9002** [MaartenGr/BERTopic#109]
After training a model with fit_transform() I have 900 topics. After reducing the number of topics to 50 by running reduce_topics(), the IDs of the new 50 topics is not limited to 50, and instead maintain the original ids (up to 900). This is a problem when running topics_over_time() because it attempts to access values within global_c_tf_idf using the original IDs, which only has indexes up to 50 now.

For example, one of the 50 topics that remain after reduction can have an ID of 825. This becomes a problem when I try to topics_over_time() because it is trying to access indexes greater than 50 of global_c_tf_idf. 

It throws an IndexError at line 480 in topics_over_time():

> ---------------------------------------------------------------------------
> IndexError                                Traceback (most recent call last)
> <ipython-input-76-495a50874090> in <module>
> ----> 1 topics_over_time = pc_model.topics_over_time(test_tweets, test_topics, test_times, nr_bins=34)
> 
> ~/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/bertopic/_bertopic.py in topics_over_time(self, docs, topics, timestamps, nr_bins, datetime_format, evolution_tuning, global_tuning)
>     478             # by simply taking the average of the two
>     479             if global_tuning:
> --> 480                 c_tf_idf = (global_c_tf_idf[documents_per_topic.Topic.values + 1] + c_tf_idf) / 2.0
>     481 
>     482             # Extract the words per topic
> 
> ~/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/scipy/sparse/_index.py in __getitem__(self, key)
>      31     """
>      32     def __getitem__(self, key):
> ---> 33         row, col = self._validate_indices(key)
>      34         # Dispatch to specialized methods.
>      35         if isinstance(row, INT_TYPES):
> 
> ~/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/scipy/sparse/_index.py in _validate_indices(self, key)
>     135                 row += M
>     136         elif not isinstance(row, slice):
> --> 137             row = self._asindices(row, M)
>     138 
>     139         if isintlike(col):
> 
> ~/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/scipy/sparse/_index.py in _asindices(self, idx, length)
>     167         max_indx = x.max()
>     168         if max_indx >= length:
> --> 169             raise IndexError('index (%d) out of range' % max_indx)
>     170 
>     171         min_indx = x.min()
> 
> IndexError: index (825) out of range

**Comment by MaartenGr** [comment]
Hmmm, this used to be an issue with v0.6 but I thought I had fixed it in v0.7. Which version are you currently using?

**Comment by eyang9002** [comment]
I ran my pipeline again with v0.7 and still got the same error

**Comment by MaartenGr** [comment]
Strange, I just tried it out with the Trump example and I am not getting this error in BERTopic v0.7. Could you please share the exact steps that you tried? 

Moreover, below is the code I tried, with several values and iteration of `nr_topics` and it is working so far. Are you doing something different than what is shown below? 

Preparing data: 

```python
import re
import pandas as pd

trump = pd.read_csv('https://drive.google.com/uc?export=download&id=1xRKHaP-QwACMydlDnyFPEaFdtskJuBa6')
trump.text = trump.apply(lambda row: re.sub(r"http\S+", "", row.text).lower(), 1)
trump.text = trump.apply(lambda row: " ".join(filter(lambda x:x[0]!="@", row.text.split())), 1)
trump.text = trump.apply(lambda row: " ".join(re.sub("[^a-zA-Z]+", " ", row.text).split()), 1)
trump = trump.loc[(trump.isRetweet == "f") & (trump.text != ""), :]
timestamps = trump.date.to_list()
tweets = trump.text.to_list()
```

Running `topics_over_time`:
```python
from bertopic import BERTopic

# Fit global model
topic_model = BERTopic(verbose=True)
topics, _ = topic_model.fit_transform(tweets)

# Reduce topics
new_topics, _ = topic_model.reduce_topics(tweets, topics, nr_topics=30)

# Calculate DTM
topics_over_time = topic_model.topics_over_time(tweets, new_topics, timestamps, nr_bins=20)
```
