### ISSUE TITLE
Elastic Search  inference model interface? 

### ISSUE THREAD

**Issue by guilharj** [MaartenGr/BERTopic#1098]
Hi guys, does anyone thought about creating a interface at bertopic to deploy model ( probably as a classification model ), at elastic search eland ? 

https://www.elastic.co/guide/en/elasticsearch/reference/master/put-trained-models.html

The main idea is to provide inferences to the documents inside the ingestion pipeline.  

https://www.elastic.co/guide/en/machine-learning/master/ml-nlp.html

Any ideas how to make it happen?

**Comment by MaartenGr** [comment]
Although I have not used elastic yet for inference with BERTopic, it should become much easier with the upcoming [serialization](https://github.com/MaartenGr/BERTopic/pull/1205).
