### ISSUE TITLE
Bug report: TypeError: object of type 'numpy.float64' has no len()

### ISSUE THREAD

**Issue by JiaxiangBU** [MaartenGr/BERTopic#110]
<details>
<summary>TypeError: object of type 'numpy.float64' has no len()</summary>

```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-43-aed98e7d2ef8> in <module>()
      1 topic_model = BERTopic()
      2 # ipdb.set_trace()
----> 3 topics, _ = topic_model.fit_transform(docs[:100],embeddings=embedding_df.iloc[:100,].values)
      4 # 20k数据，就很慢了。

/opt/conda/lib/python3.7/site-packages/bertopic/_bertopic.py in fit_transform(self, documents, embeddings, y)
    282 
    283         # Extract topics by calculating c-TF-IDF
--> 284         self._extract_topics(documents)
    285 
    286         if self.nr_topics:

/opt/conda/lib/python3.7/site-packages/bertopic/_bertopic.py in _extract_topics(self, documents)
   1309         """
   1310         documents_per_topic = documents.groupby(['Topic'], as_index=False).agg({'Document': ' '.join})
-> 1311         self.c_tf_idf, words = self._c_tf_idf(documents_per_topic, m=len(documents))
   1312         self.topics = self._extract_words_per_topic(words)
   1313         self._create_topic_vectors()

/opt/conda/lib/python3.7/site-packages/bertopic/_bertopic.py in _c_tf_idf(self, documents_per_topic, m, fit)
   1375 
   1376         if fit:
-> 1377             self.transformer = ClassTFIDF().fit(X, n_samples=m)
   1378 
   1379         c_tf_idf = self.transformer.transform(X)

/opt/conda/lib/python3.7/site-packages/bertopic/_ctfidf.py in fit(self, X, n_samples)
     42                                       shape=(n_features, n_features),
     43                                       format='csr',
---> 44                                       dtype=dtype)
     45 
     46         return self

/opt/conda/lib/python3.7/site-packages/scipy/sparse/construct.py in diags(diagonals, offsets, shape, format, dtype)
    138     if isscalarlike(offsets):
    139         # now check that there's actually only one diagonal
--> 140         if len(diagonals) == 0 or isscalarlike(diagonals[0]):
    141             diagonals = [np.atleast_1d(diagonals)]
    142         else:

TypeError: object of type 'numpy.float64' has no len()
```

</details>

There are no edge cases in inputs,

```python
np.any(embedding_df.iloc[:100,].isin([np.nan, np.inf, -np.inf])), \
np.any(pd.Series(docs[:100]).isin([np.nan, np.inf, -np.inf])), \
```

    (False, False)

And it is hard to figure out the meaning of this error message, the depends, scipy, use `len()` on a numpy array?

**Comment by MaartenGr** [comment]
Although I am not familiar with this specific error, there is one thing that stands out to me. You are using a very small dataset which can cause issues with creating the c-TF-IDF matrix. I would advise you to use at least a few hundred documents and preferably a few thousand. Can you try it out with more data and see if the problem still persists? 

Also, just a quick check, can you share the BERTopic version, as well as Scipy and Numpy?

**Comment by JiaxiangBU** [comment]
> Although I am not familiar with this specific error, there is one thing that stands out to me. You are using a very small dataset which can cause issues with creating the c-TF-IDF matrix. I would advise you to use at least a few hundred documents and preferably a few thousand. Can you try it out with more data and see if the problem still persists?

<details>
<summary>error message.</summary>


```python
topic_model = BERTopic()
# ipdb.set_trace()
topics, _ = topic_model.fit_transform(docs[:1000],embeddings=embedding_df.iloc[:1000,].values)
# 20k数据，就很慢了。
```

    /opt/conda/lib/python3.7/site-packages/bertopic/_ctfidf.py:40: RuntimeWarning: divide by zero encountered in log
      idf = np.log(avg_nr_samples / df)



    ---------------------------------------------------------------------------

    ValueError                                Traceback (most recent call last)

    <ipython-input-46-140bffa46949> in <module>()
          1 topic_model = BERTopic()
          2 # ipdb.set_trace()
    ----> 3 topics, _ = topic_model.fit_transform(docs[:1000],embeddings=embedding_df.iloc[:1000,].values)
          4 # 20k数据，就很慢了。


    /opt/conda/lib/python3.7/site-packages/bertopic/_bertopic.py in fit_transform(self, documents, embeddings, y)
        282 
        283         # Extract topics by calculating c-TF-IDF
    --> 284         self._extract_topics(documents)
        285 
        286         if self.nr_topics:


    /opt/conda/lib/python3.7/site-packages/bertopic/_bertopic.py in _extract_topics(self, documents)
       1309         """
       1310         documents_per_topic = documents.groupby(['Topic'], as_index=False).agg({'Document': ' '.join})
    -> 1311         self.c_tf_idf, words = self._c_tf_idf(documents_per_topic, m=len(documents))
       1312         self.topics = self._extract_words_per_topic(words)
       1313         self._create_topic_vectors()


    /opt/conda/lib/python3.7/site-packages/bertopic/_bertopic.py in _c_tf_idf(self, documents_per_topic, m, fit)
       1379         c_tf_idf = self.transformer.transform(X)
       1380 
    -> 1381         self.topic_sim_matrix = cosine_similarity(c_tf_idf)
       1382 
       1383         return c_tf_idf, words


    /opt/conda/lib/python3.7/site-packages/sklearn/metrics/pairwise.py in cosine_similarity(X, Y, dense_output)
       1178     # to avoid recursive import
       1179 
    -> 1180     X, Y = check_pairwise_arrays(X, Y)
       1181 
       1182     X_normalized = normalize(X, copy=True)


    /opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py in inner_f(*args, **kwargs)
         61             extra_args = len(args) - len(all_args)
         62             if extra_args <= 0:
    ---> 63                 return f(*args, **kwargs)
         64 
         65             # extra_args > 0


    /opt/conda/lib/python3.7/site-packages/sklearn/metrics/pairwise.py in check_pairwise_arrays(X, Y, precomputed, dtype, accept_sparse, force_all_finite, copy)
        142         X = Y = check_array(X, accept_sparse=accept_sparse, dtype=dtype,
        143                             copy=copy, force_all_finite=force_all_finite,
    --> 144                             estimator=estimator)
        145     else:
        146         X = check_array(X, accept_sparse=accept_sparse, dtype=dtype,


    /opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py in inner_f(*args, **kwargs)
         61             extra_args = len(args) - len(all_args)
         62             if extra_args <= 0:
    ---> 63                 return f(*args, **kwargs)
         64 
         65             # extra_args > 0


    /opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py in check_array(array, accept_sparse, accept_large_sparse, dtype, order, copy, force_all_finite, ensure_2d, allow_nd, ensure_min_samples, ensure_min_features, estimator)
        651                                       dtype=dtype, copy=copy,
        652                                       force_all_finite=force_all_finite,
    --> 653                                       accept_large_sparse=accept_large_sparse)
        654     else:
        655         # If np.array(..) gives ComplexWarning, then we convert the warning


    /opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py in _ensure_sparse_format(spmatrix, accept_sparse, dtype, copy, force_all_finite, accept_large_sparse)
        447         else:
        448             _assert_all_finite(spmatrix.data,
    --> 449                                allow_nan=force_all_finite == 'allow-nan')
        450 
        451     return spmatrix


    /opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py in _assert_all_finite(X, allow_nan, msg_dtype)
        104                     msg_err.format
        105                     (type_err,
    --> 106                      msg_dtype if msg_dtype is not None else X.dtype)
        107             )
        108     # for object dtype data, we only check for NaNs (GH-13254)


    ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

</details>

I train the model using one throusand obs and conrespondding embedding, and I get the same error.



> Also, just a quick check, can you share the BERTopic version, as well as Scipy and Numpy?

```python
for i in [bertopic, scipy, numpy]:
    print(i.__name__,i.__version__)
```

    bertopic 0.7.0
    scipy 1.4.1
    numpy 1.20.2

**Comment by MaartenGr** [comment]
Thank you for the quick response. I tried to replicate your pipeline as closely as possible with the 20 Newsgroup data but could not replicate the issue: 

```python
import pandas as pd
from bertopic import BERTopic
from sklearn.datasets import fetch_20newsgroups
from sentence_transformers import SentenceTransformer

# Prepare data and classes
docs = fetch_20newsgroups(subset='all',  remove=('headers', 'footers', 'quotes'))["data"]
sentence_model = SentenceTransformer("distilbert-base-nli-mean-tokens", device="cuda")
embeddings = sentence_model.encode(docs)
embedding_df = pd.DataFrame(embeddings)

# Create topic model and calculate topics per class
topic_model = BERTopic()
topics, _ = topic_model.fit_transform(docs[:1000], embedding_df.iloc[:1000,].values)
```

To me, this then seems to be an issue with either your `docs` or `embeddings_df` variables as all other variables/classes/modules/versions seem to be similar. Is it possible for you to share the code, assuming you use publicly available documents, to creating those variables? 

Seeing as the issue mostly appears in the c-TF-IDF transformer, I think there is an issue with the documents that you are using. 
It could be that some of the documents are empty or contain characters that the CountVectorizer cannot handle.

**Comment by JiaxiangBU** [comment]
Thanks for your reply.

> To me, this then seems to be an issue with either your `docs` or `embeddings_df` variables as all other variables/classes/modules/versions seem to be similar. Is it possible for you to share the code, assuming you use publicly available documents, to creating those variables?

```python
np.any(embedding_df.iloc[:100,].isin([np.nan, np.inf, -np.inf])), \
np.any(pd.Series(docs[:100]).isin([np.nan, np.inf, -np.inf,""," "])), \
```

(False, False)

I suspect it and do more test, though I use the Chinese characters, there is no edge cases or only space cases in the input sentences (space cases is converted to no token after tokenization).

I should make a reproducible example,  however, and the data is not public. 
I will try a public dataset with Chinese characters to reproduce this error.

**Comment by JiaxiangBU** [comment]
@MaartenGr Hi I make a reproducile example here,https://github.com/JiaxiangBU/bertopic-chinese-example

However, I receive a new error with numpy and list.

<details>
<summary>TypeError: object of type 'numpy.float64' has no len()</summary>


```python
topic_model = BERTopic()
# ipdb.set_trace()
topics, _ = topic_model.fit_transform(docs[:1000],embeddings=embedding_df.iloc[:1000,].values)
# 20k数据，就很慢了。
```

    /opt/conda/lib/python3.7/site-packages/bertopic/_ctfidf.py:40: RuntimeWarning: divide by zero encountered in log
      idf = np.log(avg_nr_samples / df)
    


    ---------------------------------------------------------------------------

    TypeError                                 Traceback (most recent call last)

    <ipython-input-77-a31bff2ac499> in <module>
          1 topic_model = BERTopic()
          2 # ipdb.set_trace()
    ----> 3 topics, _ = topic_model.fit_transform(docs[:1000],embeddings=embedding_df.iloc[:1000,].values)
          4 # 20k数据，就很慢了。
    

    /opt/conda/lib/python3.7/site-packages/bertopic/_bertopic.py in fit_transform(self, documents, embeddings, y)
        282 
        283         # Extract topics by calculating c-TF-IDF
    --> 284         self._extract_topics(documents)
        285 
        286         if self.nr_topics:
    

    /opt/conda/lib/python3.7/site-packages/bertopic/_bertopic.py in _extract_topics(self, documents)
       1309         """
       1310         documents_per_topic = documents.groupby(['Topic'], as_index=False).agg({'Document': ' '.join})
    -> 1311         self.c_tf_idf, words = self._c_tf_idf(documents_per_topic, m=len(documents))
       1312         self.topics = self._extract_words_per_topic(words)
       1313         self._create_topic_vectors()
    

    /opt/conda/lib/python3.7/site-packages/bertopic/_bertopic.py in _c_tf_idf(self, documents_per_topic, m, fit)
       1375 
       1376         if fit:
    -> 1377             self.transformer = ClassTFIDF().fit(X, n_samples=m)
       1378 
       1379         c_tf_idf = self.transformer.transform(X)
    

    /opt/conda/lib/python3.7/site-packages/bertopic/_ctfidf.py in fit(self, X, n_samples)
         42                                       shape=(n_features, n_features),
         43                                       format='csr',
    ---> 44                                       dtype=dtype)
         45 
         46         return self
    

    /opt/conda/lib/python3.7/site-packages/scipy/sparse/construct.py in diags(diagonals, offsets, shape, format, dtype)
        138     if isscalarlike(offsets):
        139         # now check that there's actually only one diagonal
    --> 140         if len(diagonals) == 0 or isscalarlike(diagonals[0]):
        141             diagonals = [np.atleast_1d(diagonals)]
        142         else:
    

    TypeError: object of type 'numpy.float64' has no len()


</details>

**Comment by MaartenGr** [comment]
After some testing, the issue seems to be clear. It seems to be related to tokenizing the Chinese language. Currently, CountVectorizer tokenizes text by splitting whitespace which does not work for Chinese. In order to get it to work, you will have to create a custom `CountVectorizer`  that supports it like this:

First we prepare your example data:

```python
import pandas as pd
df = pd.read_excel("https://github.com/JiaxiangBU/bertopic-chinese-example/blob/master/chinese-sts.xlsx?raw=true",skiprows=1,engine='openpyxl',names=['pair_l','pair_r','scores'])
df = df[df['pair_l'].str.len()>=2][pd.isna(df['pair_l'])==False]
input_list = df['pair_l']
docs = input_list.tolist()
```

Next, we create the embeddings you specified:

```python
from sentence_transformers import SentenceTransformer
model = SentenceTransformer('paraphrase-distilroberta-base-v1')
embeddings = model.encode(docs)
```

Note here that the sentence-transformer model does not support Chinese, you should use `paraphrase-xlm-r-multilingual-v1` instead. 

Then, we create the Chinese tokenizer with `jieba`:

```python
from sklearn.feature_extraction.text import CountVectorizer
import jieba

def tokenize_zh(text):
    words = jieba.lcut(text)
    return words

vectorizer = CountVectorizer(tokenizer=tokenize_zh)
```

Finally, we pass our custom vectorizer to BERTopic and create our topic model:
```python
from bertopic import BERTopic
topic_model = BERTopic(embedding_model=model, verbose=True, vectorizer_model=vectorizer)
topics, _ = topic_model.fit_transform(docs, embeddings=embeddings)
```

**Comment by JiaxiangBU** [comment]
Yeah, I agree with you, when I use keybert, I face the similar problem. I will fix the tokenization process manually, and see what go further. Thanks for your suggestions.



发自我的iPhone


------------------ Original ------------------
From: Maarten Grootendorst ***@***.***&gt;
Date: Sat,May 1,2021 2:33 PM
To: MaartenGr/BERTopic ***@***.***&gt;
Cc: Jiaxiang Li ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [MaartenGr/BERTopic] Bug report: TypeError: object of type 'numpy.float64' has no len() (#110)






After some testing, the issue seems to be clear. It seems to be related to tokenizing the Chinese language. Currently, CountVectorizer tokenizes text by splitting whitespace which does not work for Chinese. In order to get it to work, you will have to create a custom CountVectorizer  that supports it like this:

First we prepare your example data:
import pandas as pddf = pd.read_excel("https://github.com/JiaxiangBU/bertopic-chinese-example/blob/master/chinese-sts.xlsx?raw=true",skiprows=1,engine='openpyxl',names=['pair_l','pair_r','scores'])df = df[df['pair_l'].str.len()&gt;=2][pd.isna(df['pair_l'])==False]input_list = df['pair_l']docs = input_list.tolist()

Next, we create the embeddings you specified:
from sentence_transformers import SentenceTransformermodel = SentenceTransformer('paraphrase-distilroberta-base-v1')embeddings = model.encode(docs)

Note here that the sentence-transformer model does not support Chinese, you should use paraphrase-xlm-r-multilingual-v1 instead.

Then, we create the Chinese tokenizer with jieba:
from sklearn.feature_extraction.text import CountVectorizerimport jiebadef tokenize_zh(text):    words = jieba.lcut(text)    return wordsvectorizer = CountVectorizer(tokenizer=tokenize_zh)

Finally, we pass our custom vectorizer to BERTopic and create our topic model:
from bertopic import BERTopictopic_model = BERTopic(embedding_model=model, verbose=True, vectorizer_model=vectorizer)topics, _ = topic_model.fit_transform(docs, embeddings=embeddings)

**Comment by JiaxiangBU** [comment]
Thanks for your script, I test it and it works well for me.
