### ISSUE TITLE
PROMPT  with the textgeneration

### ISSUE THREAD

**Issue by dineshdisprz** [MaartenGr/BERTopic#1102]
There seems like a error in the code for creating a prompt , when someone try to use both keywords and documents in the prompt to get the topic representation by the text generation. The prompt that is generated is bad.

> The topic is described by the following keywords: keywords
> I have topic that contains the following documents: [DOCUMENTS]
> Based on the above information, can you give a short label of the topic? 
> 
> The topic is described by the following keywords: [KEYWORDS].
> I have topic that contains the following documents: documents
> Based on the above information, can you give a short label of the topic?
> 

this is the format of  prompt that is generated for every cluster .

**keywords** = keywords that are used to represent a topic
**documents** = top 4 documents 

I think there should be a change in the code , when some one wants to create a prompt with keywords and documents.

**Comment by MaartenGr** [comment]
You should be able to use both the keywords and documents using those tags in `bertopic.representation_model.TextGeneration`:

https://github.com/MaartenGr/BERTopic/blob/7d45cf710aefff178d54403989e90432e0c49910/bertopic/representation/_textgeneration.py#L128-L137

Could you explain in a bit more detail where you believe it is going wrong? Also, can you provide a reproducible example in the newest version of BERTopic?

**Comment by dineshdisprz** [comment]
**I have a topic that contains the following documents: 
[DOCUMENTS]
The topic is described by the following keywords: [KEYWORDS]

Based on the information above, extract a short topic label and just return the topic label** 

The above mentioned is the prompt that I am passing as a parameter to the text generative model , but the resulting prompt that i get after passing it to the **_create_prompt** function is the below one :

![12](https://user-images.githubusercontent.com/111870648/226565903-40fe0f96-18ec-41df-b86b-d7e0644c86d5.png)

I think the **_create_prompt**  function doesn't account for the prompt with keywords and documents .



And the prompt that I was expecting is :
![Screenshot 2023-03-21 151308](https://user-images.githubusercontent.com/111870648/226568973-366fc83c-bcd7-4f5e-9489-d2c696bd03f9.png)

**Comment by MaartenGr** [comment]
Ah, I see. I believe the code I mentioned above was fixed before but it seems I only did that for the other representation models. I'll make sure to fix it in the coming days in the main branch.

**Comment by dineshdisprz** [comment]
I have tried some representative models , There it works perfect . Its the only case with the text generative model.

Thanks for the Update.

**Comment by MaartenGr** [comment]
I pushed a commit that should have fixed this issue in the main branch. There are a few more bugs to fix before releasing a new version but it should work now if you install BERTopic from the main branch.
