### ISSUE TITLE
How to acquire the source data of the chart?

### ISSUE THREAD

**Issue by MrRabbit12** [MaartenGr/BERTopic#1107]
I'm useing bertopic model for my Chinese public opinion mining. I need to translate the results(mainly graphs) from Chinese to English which means I need to draw my output pictures relying on the source data of the chart made by bertopic automatically，I wonder if there exists ways to do that?

**Comment by MaartenGr** [comment]
The source of the data from these graphs can best be found in the source code. There is no one set way of extracting that from each graph, so you will have to look into `bertopic.plotting`.

**Comment by MrRabbit12** [comment]
I got it， thank u！~~~



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Maarten ***@***.***&gt;; 
发送时间: 2023年3月22日(星期三) 晚上7:34
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [MaartenGr/BERTopic] How to acquire the source data of the chart? (Issue #1107)





 
The source of the data from these graphs can best be found in the source code. There is no one set way of extracting that from each graph, so you will have to look into bertopic.plotting.
