### ISSUE TITLE
Possible to get topic representations for a subset of topics?

### ISSUE THREAD

**Issue by zilch42** [MaartenGr/BERTopic#1108]
Hi Maarten,

I am really enjoying the OpenAI topic representations, but it can be quite slow using an API with with rate-limiting when there are a large number of topics, not to mention expensive with the more capable models. Often I don't need a good representation for every single micro topic. Would it be possible to only generate fancy topic representations for a subset of topics? e.g. the top 20 topics? If so, how might I go about doing that?

Cheers!

**Comment by MaartenGr** [comment]
For that, you would have to adapt the code in https://github.com/MaartenGr/BERTopic/blob/master/bertopic/representation/_openai.py to make sure it only calculates it for either specific topics or for those that have a high frequency. After adjusting that, you can create your custom representation model as described [here](https://maartengr.github.io/BERTopic/getting_started/representation/representation.html#custom-model).

**Comment by zilch42** [comment]
Thanks I'll give that a shot!
