### ISSUE TITLE
Keyword frequencies for each clusters

### ISSUE THREAD

**Issue by ranjonaa** [MaartenGr/BERTopic#1110]
Hi Maarten,

It is possible plot keyword frequencies for each cluster and show the their probability similar to LDA topic

**Comment by MaartenGr** [comment]
There are a bunch of visualization options for BERTopic that you can find [here](https://maartengr.github.io/BERTopic/getting_started/visualization/visualization.html). Together, they should give sufficient information about the model. Having said that, I believe you can use pyLDAvis according to the issue [here](https://github.com/MaartenGr/BERTopic/issues/196).
