### ISSUE TITLE
Question about topic size

### ISSUE THREAD

**Issue by ericchagnon15** [MaartenGr/BERTopic#1111]
I am working with a corpus of around 2 million documents and set the ```min_topic_size``` to 500. I went and counted the number of documents in each topic via the collections library:

```
counter = collections.Counter(topics)
df = pd.DataFrame(dict(counter).items())
```

and there are topics that have less than 500 documents assigned to them. I was wondering if this was intended, and if so what is the relationship between ```min_topic_size``` and the number of documents assigned to each topic?

**Comment by MaartenGr** [comment]
Generally, the `min_topic_size` should make sure that the topic with the lowest number of documents is at least `min_topic_size`. Could you provide the full code, including the BERTopic version you are using?

**Comment by ericchagnon15** [comment]
I am using the latest v0.14.1 and here are the snippets from the project I am working on. My docs are from the arxiv dataset

```{python}
from bertopic import BERTopic
from sentence_transformers import SentenceTransformer
from cuml.cluster import HDBSCAN
from cuml.manifold import UMAP
import collections
import pandas

language_model = SentenceTransformer('allenai-specter')
cluster_model = HDBSCAN(prediction_data=True)
umap_model = UMAP(n_components = 10)
topic_model = BERTopic(embedding_model=language_model['model'],
                            umap_model = umap_model,
                            hdbscan_model = cluster_model,
                            language="english",
                            nr_topics="auto",
                            min_topic_size = 500,
                            verbose=verbose)



topics, probs = topic_model.fit_transform(docs)

counter = collections.Counter(topics)
df = pd.DataFrame(dict(counter).items())
df.columns = ['Topics', 'Size']
file_path = 'topic_size.csv'
df.to_csv(file_path)
```

**Comment by dkirman-re** [comment]
Looks like your `HDBSCAN(prediction_data=True)` may be the culprit. I believe HDBSCAN's default `min_cluster_size` is 5 if omitted from the constructor, and BERTopic won't override an input model's parameters.
If you'd like to utilize a minimum topic size, try passing it into your HDBSCAN object -
i.e `cluster_model = HDBSCAN(min_cluster_size=500, prediction_data=True)`

**Comment by ericchagnon15** [comment]
Oh i see, it was my understanding that the BERTopic parameter would overwrite if I omitted it in the clustering model. I'll give it a try and see what happens.

**Comment by ericchagnon15** [comment]
I'm using the ```cuml``` library's accelerated HDBSCAN

**Comment by dkirman-re** [comment]
Ah yes, I now see that's why you were overriding the `prediction_data` variable. I believe the `min_cluster_size` is assigned the same default value of 5 in that case as well.

**Comment by MaartenGr** [comment]
Due to inactivity, I'll be closing this issue. Let me know if you want me to re-open the issue!
