### ISSUE TITLE
fit_trasform takes a long time running

### ISSUE THREAD

**Issue by parmidaatg** [MaartenGr/BERTopic#1116]
Hi :)
I came across this repo today and loved how you put all the modules together. I am giving it a shot to create topics in my corpus. In my dataset, the individual document is not that long since it is an image caption , however the corpus contains 63538 documents. I am trying the default setup with `language` set to `english` and the logs show that the dimensionality reduction is done but the code has been stuck there for almost a good 20 min. I was wondering if that is normal and do have any profiling result that shows the time expectancy ? 

I might try the online topic modelling you provide but wanted to verify I am not missing something. Here is where my code is stuck:
```
2023-03-23 21:05:17,930 - BERTopic - Transformed documents to Embeddings
OMP: Info #276: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead.
2023-03-23 21:06:22,847 - BERTopic - Reduced dimensionality
```

**Comment by MaartenGr** [comment]
There might be a number of reasons for this but generally, ~60.000 documents should be doable. Could you provide your entire code for training and instantiating BERTopic? There might be something there.

**Comment by parmidaatg** [comment]
Thanks alot for your response :) 
Here is the code. I do some cleaning at first on my dataframe which reduces around 10k rows but then yesterday running the code on ~60k prompts didn't respond. I ran the code several times and everytime was getting stuck in training and everytime I had to stop the job after an hour and half waiting.

I checked the `sklearn` dataset length you show in your demo so I decided to downsample to ~30,000 still not responsive. And at the end downsampling to 18,000 was able to resolve the full training and transformation for me in like 20 to 25 min.

Would really appreciate your help . 

```

import os
import pandas as pd

from datasets import Dataset
from bertopic import BERTopic
os.environ['TOKENIZERS_PARALLELISM']="false"


df = pd.read_csv('./prompts.csv')
df = df.dropna() 
print(len(df.index)) # total number of rows here is 74,165 


 // some gymnasitics here to remove some duplications and then 

df = df.drop(index=selected_to_prune)
print(len(df.index)) # total number of rows here is 63, 538

ds = Dataset.from_pandas(df)

selected_indices = random.choices(np.arange(len(ds)), k = 18000)
ds_downsampled = ds.select(selected_indices) # I had to reduce to 18000 to be able to have a response within 20 min
prompts = ds_downsampled["prompt"]

topic_model = BERTopic(language="english", top_n_words=3, calculate_probabilities=True, verbose=True)
topics, prob = topic_model.fit_transform(prompts)

```

**Comment by parmidaatg** [comment]
Alright, I set the `calculate_probabilities` to `False` and I could get the model to `fit_transform` in 2 min. Could it be possible that it gets stuck because it is low in memory?

**Comment by MaartenGr** [comment]
Yes, `calculate_probabilities` is computationally quite expensive and can slow down the fitting process significantly. If you would like to speed that up, I would advise using [cuML](https://maartengr.github.io/BERTopic/getting_started/tips_and_tricks/tips_and_tricks.html#gpu-acceleration) instead.

**Comment by parmidaatg** [comment]
Thank you so much. I'll close this issue :)
