### ISSUE TITLE
min_cluster_size vs. min_topic_size?

### ISSUE THREAD

**Issue by ChristianEssen** [MaartenGr/BERTopic#1118]
Maybe I'm lost, but the following is unclear to me: Why is there a distinction between the two hyperparameters `min_cluster_size` and `min_topic_size`? `min_cluster_size` controls, according to the description, the number of clusters during HDBSCAN. And if I understood it correctly, the clusters formed during HDBSCAN correspond to the topics, so e.g. 8 clusters= 8 topics. 
If this is true, at which point does `min_topic_size` start to change the number of clusters? And which algorithm is used for this? (Basically the same question applies to `min_cluster_size` vs. `nr_topics`).

Thanks a lot for your support!

**Comment by MaartenGr** [comment]
`min_cluster_size` and `min_topic_size` are the same parameters. To make it easier for users to control BERTopic without the need to dive into sub-models, like HDBSCAN, `min_topic_size` was exposed to control the `min_cluster_size` parameter of HDBSCAN. 

In contrast, `nr_topics` does affect the topic number creation. It is a way to further reduce the number of topics if too many are created for your use case.

**Comment by ChristianEssen** [comment]
Thank you very much for your super-quick answer!
