### ISSUE TITLE
cuML GPU acceleration Google Colab

### ISSUE THREAD

**Issue by sophvaladou** [MaartenGr/BERTopic#1120]
Hi, 

I am having an issue with the installation of RAPIDS in Google Colab.
I first tried this code:
!pip install bertopic
!pip install cudf-cu11 dask-cudf-cu11 --extra-index-url=https://pypi.ngc.nvidia.com
!pip install cuml-cu11 --extra-index-url=https://pypi.ngc.nvidia.com
!pip install cugraph-cu11 --extra-index-url=https://pypi.ngc.nvidia.com
!pip uninstall cupy-cuda115 -y
!pip uninstall cupy-cuda11x -y
!pip install cupy-cuda11x -f https://pip.cupy.dev/aarch64

But that did not work. Then, I used this code:

!git clone https://github.com/rapidsai/rapidsai-csp-utils.git
!python rapidsai-csp-utils/colab/pip-install.py

Which did work, however, now there is a depedency issue regarding protobuf when I want to pip install bertopic.
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).
 
 I tried downgrading protobuf like this:
 !pip install protobuf==3.20.0
 
 But then all sorts of dependency issues with other packages pop up:
 
 Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting protobuf==3.20.0
  Using cached protobuf-3.20.0-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.whl (1.0 MB)
Installing collected packages: protobuf
  Attempting uninstall: protobuf
    Found existing installation: protobuf 3.19.0
    Uninstalling protobuf-3.19.0:
      Successfully uninstalled protobuf-3.19.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow 2.11.0 requires protobuf<3.20,>=3.9.2, but you have protobuf 3.20.0 which is incompatible.
googleapis-common-protos 1.59.0 requires protobuf!=3.20.0,!=3.20.1,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5, but you have protobuf 3.20.0 which is incompatible.
google-cloud-translate 3.8.4 requires protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5, but you have protobuf 3.20.0 which is incompatible.
google-cloud-language 2.6.1 requires protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5, but you have protobuf 3.20.0 which is incompatible.
google-cloud-firestore 2.7.3 requires protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5, but you have protobuf 3.20.0 which is incompatible.
google-cloud-datastore 2.11.1 requires protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5, but you have protobuf 3.20.0 which is incompatible.
google-cloud-bigquery 3.4.2 requires protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5, but you have protobuf 3.20.0 which is incompatible.
google-cloud-bigquery-storage 2.19.0 requires protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5, but you have protobuf 3.20.0 which is incompatible.
google-api-core 2.11.0 requires protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5, but you have protobuf 3.20.0 which is incompatible.
cudf-cu11 23.2.0 requires protobuf==4.21, but you have protobuf 3.20.0 which is incompatible.
Successfully installed protobuf-3.20.0

Can you help me to properly install both RAPIDS to use the cuML and BERTopic?

Thank you in advance!

**Comment by beckernick** [comment]
NVIDIA has standardized on a new Python package index `pypi.nvidia.com` (note that there is no `.ngc`). RAPIDS libraries like cuML can now be installed on Colab with the following (assuming you're using a GPU runtime): `!pip install cuml-cu11 --extra-index-url=https://pypi.nvidia.com`

It looks like BERTopic wants protobuf 3.20.x, so you can combine cuML with BERTopic like this:

```
!pip install cuml-cu11 --extra-index-url=https://pypi.nvidia.com
!pip install bertopic
!pip install protobuf==3.20
```

You can (generally) ignore the cuDF protobuf incompatibility error.

**Comment by sophvaladou** [comment]
@beckernick It works, thank you very much!!!

**Comment by sophvaladou** [comment]
Hi, I'm sorry, but it's still not working...
I tried:
!pip install cuml-cu11 --extra-index-url=https://pypi.nvidia.com

which gave:
WARNING: The candidate selected for download or install is a yanked version: 'protobuf' candidate (version 4.21.0 at https://files.pythonhosted.org/packages/9d/82/b3131637daf2a27eab76b0de8e139ecf0f6624832c03531dce8a7d59ddc1/protobuf-4.21.0-cp37-abi3-manylinux2014_x86_64.whl#sha256=9a65e012bc06022e98a57165ea48438b3b9f652eee33db7cbecb883588f9f169 (from https://pypi.org/simple/protobuf/))
Reason for being yanked: Required python version not configured correctly (https://github.com/protocolbuffers/protobuf/issues/10076)
Installing collected packages: ptxcompiler-cu11, protobuf, nvtx, cubinlinker-cu11, pynvml, pyarrow, cuda-python, ucx-py-cu11, treelite-runtime, treelite, rmm-cu11, dask, pylibraft-cu11, distributed, cudf-cu11, dask-cudf-cu11, dask-cuda, raft-dask-cu11, cuml-cu11
  Attempting uninstall: protobuf
    Found existing installation: protobuf 3.19.6
    Uninstalling protobuf-3.19.6:
      Successfully uninstalled protobuf-3.19.6
  Attempting uninstall: pyarrow
    Found existing installation: pyarrow 9.0.0
    Uninstalling pyarrow-9.0.0:
      Successfully uninstalled pyarrow-9.0.0
  Attempting uninstall: dask
    Found existing installation: dask 2022.12.1
    Uninstalling dask-2022.12.1:
      Successfully uninstalled dask-2022.12.1
  Attempting uninstall: distributed
    Found existing installation: distributed 2022.12.1
    Uninstalling distributed-2022.12.1:
      Successfully uninstalled distributed-2022.12.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow 2.11.0 requires protobuf<3.20,>=3.9.2, but you have protobuf 4.21.0 which is incompatible.
tensorflow-metadata 1.12.0 requires protobuf<4,>=3.13, but you have protobuf 4.21.0 which is incompatible.
tensorboard 2.11.2 requires protobuf<4,>=3.9.2, but you have protobuf 4.21.0 which is incompatible.
pandas-gbq 0.17.9 requires pyarrow<10.0dev,>=3.0.0, but you have pyarrow 10.0.0 which is incompatible.
google-cloud-translate 3.8.4 requires protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5, but you have protobuf 4.21.0 which is incompatible.
google-cloud-language 2.6.1 requires protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5, but you have protobuf 4.21.0 which is incompatible.
google-cloud-firestore 2.7.3 requires protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5, but you have protobuf 4.21.0 which is incompatible.
google-cloud-datastore 2.11.1 requires protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5, but you have protobuf 4.21.0 which is incompatible.
google-cloud-bigquery 3.4.2 requires protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5, but you have protobuf 4.21.0 which is incompatible.
google-cloud-bigquery-storage 2.19.0 requires protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5, but you have protobuf 4.21.0 which is incompatible.
google-api-core 2.11.0 requires protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5, but you have protobuf 4.21.0 which is incompatible.
Successfully installed cubinlinker-cu11-0.3.0.post1 cuda-python-11.8.1 cudf-cu11-23.2.0 cuml-cu11-23.2.0 dask-2023.1.1 dask-cuda-23.2.1 dask-cudf-cu11-23.2.0 distributed-2023.1.1 nvtx-0.2.5 protobuf-4.21.0 ptxcompiler-cu11-0.7.0.post1 pyarrow-10.0.0 pylibraft-cu11-23.2.0 pynvml-11.4.1 raft-dask-cu11-23.2.0 rmm-cu11-23.2.0 treelite-3.1.0 treelite-runtime-3.1.0 ucx-py-cu11-0.30.0

!pip install bertopic
!pip install protobuf==3.20

from bertopic import BERTopic
which gave:
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

**Comment by sophvaladou** [comment]
I found a way to make it work!
The code has to be run in this specific order, otherwise it does not work for me:

import locale
locale.getpreferredencoding = lambda: "UTF-8"

!pip install cuml-cu11 --extra-index-url=https://pypi.nvidia.com

!pip install protobuf==3.20

from cuml.cluster import HDBSCAN
from cuml.manifold import UMAP

!pip install bertopic

from bertopic import BERTopic

Sometimes the first piece of code gives and error, and running this before helped me:
import locale
locale.getpreferredencoding = lambda: "UTF-8"

**Comment by elashrry** [comment]
Spent hours on this issue and this what worked for me from this [comment](https://github.com/rapidsai/cudf/issues/12762#issuecomment-1462657683) 

```
!pip install dask==2022.9.2 distributed==2022.9.2 ucx-py-cu11==0.29.0 cudf-cu11==22.10 rmm-cu11==22.10 dask-cudf-cu11==22.10 --extra-index-url=https://pypi.nvidia.com

!pip install dask==2022.9.2 distributed==2022.9.2 ucx-py-cu11==0.29.0 raft-dask-cu11==22.10 pylibcugraph-cu11==22.10 pylibraft-cu11==22.10 cuml-cu11==22.10 --extra-index-url=https://pypi.nvidia.com

!pip install dask==2022.9.2 distributed==2022.9.2 ucx-py-cu11==0.29.0 raft-dask-cu11==22.10 pylibcugraph-cu11==22.10 pylibraft-cu11==22.10 cudf-cu11==22.10 cugraph-cu11==22.10 --extra-index-url=https://pypi.nvidia.com

!pip uninstall cupy-cuda115 -y
!pip uninstall cupy-cuda11x -y
!pip install cupy-cuda11x -f https://pip.cupy.dev/aarch64
!pip install nvidia-ml-py3
```

**Comment by beckernick** [comment]
For anyone having an issue on Colab with cuML, could you please try in fresh notebook and provide a reproducible example that includes the full output and potential error?

In a fresh Colab notebook using a GPU runtime, I can run the following code without issue:

```
!pip install cuml-cu11 --extra-index-url=https://pypi.nvidia.com
!pip install bertopic
!pip install protobuf==3.20
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/, https://pypi.nvidia.com/
Collecting cuml-cu11
  Downloading https://pypi.nvidia.com/cuml-cu11/cuml_cu11-23.2.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1586.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 GB 1.1 MB/s eta 0:00:00
...
```

```
from bertopic import BERTopic
from cuml.cluster import HDBSCAN
from cuml.manifold import UMAP
from sklearn.datasets import fetch_20newsgroups

docs = fetch_20newsgroups(subset='all',  remove=('headers', 'footers', 'quotes'))['data']

# Create instances of GPU-accelerated UMAP and HDBSCAN
umap_model = UMAP(n_components=5, n_neighbors=15, min_dist=0.0)
hdbscan_model = HDBSCAN(min_samples=10, gen_min_span_tree=True, prediction_data=True)

# Pass the above models to be used in BERTopic
topic_model = BERTopic(umap_model=umap_model, hdbscan_model=hdbscan_model)
topics, probs = topic_model.fit_transform(docs[:100])
topics
Downloading (…)e9125/.gitattributes: 100%
1.18k/1.18k [00:00<00:00, 49.5kB/s]
Downloading (…)_Pooling/config.json: 100%
190/190 [00:00<00:00, 9.11kB/s]
Downloading (…)7e55de9125/README.md: 100%
10.6k/10.6k [00:00<00:00, 580kB/s]
Downloading (…)55de9125/config.json: 100%
612/612 [00:00<00:00, 28.0kB/s]
Downloading (…)ce_transformers.json: 100%
116/116 [00:00<00:00, 6.44kB/s]
Downloading (…)125/data_config.json: 100%
39.3k/39.3k [00:00<00:00, 1.43MB/s]
Downloading pytorch_model.bin: 100%
90.9M/90.9M [00:00<00:00, 173MB/s]
Downloading (…)nce_bert_config.json: 100%
53.0/53.0 [00:00<00:00, 2.14kB/s]
Downloading (…)cial_tokens_map.json: 100%
112/112 [00:00<00:00, 6.01kB/s]
Downloading (…)e9125/tokenizer.json: 100%
466k/466k [00:00<00:00, 3.46MB/s]
Downloading (…)okenizer_config.json: 100%
350/350 [00:00<00:00, 15.0kB/s]
Downloading (…)9125/train_script.py: 100%
13.2k/13.2k [00:00<00:00, 162kB/s]
Downloading (…)7e55de9125/vocab.txt: 100%
232k/232k [00:00<00:00, 1.38MB/s]
Downloading (…)5de9125/modules.json: 100%
349/349 [00:00<00:00, 5.87kB/s]
[2,
 0,
 1,
 0,
...
```

**Comment by elashrry** [comment]
Hey @beckernick , 
I just tried your solution and it worked. I took the word from the comments before that it didn't work 😅 
While the code is working, we get this dependency errors

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow 2.11.0 requires protobuf<3.20,>=3.9.2, but you have protobuf 4.22.1 which is incompatible.
tensorflow-metadata 1.12.0 requires protobuf<4,>=3.13, but you have protobuf 4.22.1 which is incompatible.
tensorboard 2.11.2 requires protobuf<4,>=3.9.2, but you have protobuf 4.22.1 which is incompatible.
cudf-cu11 22.10.0 requires protobuf<3.21.0a0,>=3.20.1, but you have protobuf 4.22.1 which is incompatible.
```

Thank you !
