### ISSUE TITLE
probably incorrect typings

### ISSUE THREAD

**Issue by demetrius-mp** [MaartenGr/BERTopic#1124]
https://github.com/MaartenGr/BERTopic/blob/1b25ba7810b44bcb9594b42f70787fc2d8bb7015/bertopic/_bertopic.py#L1315

`get_topics` actually returns a `Mappig`, where 
- key is an `int`
- value is a `list[tuple[str, numpy.float64]]` which is a list, with each entry being a tuple with the word, and the score.

## Showing that the key is an `int`, not a `str`
![image](https://user-images.githubusercontent.com/50879193/227622138-16426396-95e3-44a3-acc8-d3a168a56d75.png)

so, the correct signature would be

```python
def get_topics(self) -> Mapping[int, List[Tuple[str, float]]]: 
```

**Comment by MaartenGr** [comment]
That could definitely be the case. I am not type-checking these things as they are merely used for hinting purposes. I believe that this one then also needs updating: 

https://github.com/MaartenGr/BERTopic/blob/1b25ba7810b44bcb9594b42f70787fc2d8bb7015/bertopic/_bertopic.py#L66-L67

If you want, a PR would be appreciated!
