### ISSUE TITLE
Hyperparameters for dimension reduction used in the default BERTopic model

### ISSUE THREAD

**Issue by beeman-93** [MaartenGr/BERTopic#1126]
Greetings, Maarten. 
I would like to ask about the what hyperparameters for dimension reduction were used in the default BERTopic model. 

Code: 
from bertopic import BERTopic
topic_model = BERTopic(language="english", calculate_probabilities=True, verbose=True)
topics, probs = topic_model.fit_transform(texts)

For example, if I use the basic BERTopic model above, I suppose I will not do any dimension reduction because I do not call the hyperparameter, for example, umap_model=umap_model when initiating BERTopic. 

However, in this article (https://maartengr.github.io/BERTopic/getting_started/parameter%20tuning/parametertuning.html#calculate_probabilities), 
it says In BERTopic, it[UMAP] is used to reduce the dimensionality of document embedding into something easier to use with HDBSCAN to create good clusters. So I think dimension reduction is conducted even if I only use the default BERTopic without calling umap_model=umap_model. 

I would like to know is dimension reduction conducted with the out of box BERTopic model. If it is, what are the hyperparameter settings for UMAP. 

Thanks a lot.

**Comment by MaartenGr** [comment]
Yes, UMAP is used as a default in BERTopic. You can find more about the default pipeline in the documentation [here](https://maartengr.github.io/BERTopic/algorithm/algorithm.html). The default parameters are:

https://github.com/MaartenGr/BERTopic/blob/f220ddf14fd339f9731b6f35ad4493713f890d36/bertopic/_bertopic.py#L208-L213

**Comment by beeman-93** [comment]
Oh nice! This helps a lot. Thank you for your help.
