### ISSUE TITLE
Save reduced embeddings

### ISSUE THREAD

**Issue by sophvaladou** [MaartenGr/BERTopic#1127]
Hello,

I was wondering if it would be possible to first perform umap on the embeddings, then save these reduced embeddings, and then pass them to BERTopic in this way, without dimensionality reduction

from bertopic import BERTopic
from bertopic.dimensionality import BaseDimensionalityReduction

empty_dimensionality_model = BaseDimensionalityReduction()
topic_model = BERTopic(umap_model=empty_dimensionality_model).fit_transform(documents = docs, embeddings= reduced_UMAP_embeddings)

Or would this not be the same?

Also, when first performing PCA and then UMAP to speed up the dimensionality reduction, does this have any impact on the quality of the topic model? Does performing UMAP without PCA give better results?

**Comment by MaartenGr** [comment]
Yes, what you propose should indeed skip the dimensionality reduction step and directly use the `reduced_UMAP_embeddings` for clustering. 

> Also, when first performing PCA and then UMAP to speed up the dimensionality reduction, does this have any impact on the quality of the topic model? Does performing UMAP without PCA give better results?

Personally, the results with UMAP only have been better for me. Unfortunately, it highly depends on the use case and there is not one right answer for doing one over the other. If you are running into computational issues, then it might be worthwhile to use PCA first.
