### ISSUE TITLE
min_topic_size

### ISSUE THREAD

**Issue by Christixna** [MaartenGr/BERTopic#1128]
Hi Maarten

I have a question about the min_topic_size argument. I thought it would define how many words are needed at least to define a topic. I currently have it set to 10, which works well for my data. However, I have noticed that the topics (I currently have about 30) do not all have 10 keywords. Some have only 6 or 5 and one topic has only 3 words. The topics make sense and in terms of interpretation it all looks good. I was just wondering what exactly the min_topic_size argument does to make sure everything is fine model-wise.

Thanks a lot!

**Comment by MaartenGr** [comment]
The `min_topic_size` parameter does not refer to the amount of words that make up a topic. Instead, it refers to the amount of documents necessary to make up a topic. To a certain degree, it controls the number of topics that are created.

**Comment by Christixna** [comment]
Thanks for clarifying!
