### ISSUE TITLE
LookupError in fit_transform

### ISSUE THREAD

**Issue by PanosP** [MaartenGr/BERTopic#1130]
Hello,
Running `fit_transform` gave me the following output. 
> LookupError Traceback (most recent call last) Cell In[14], line 1 ----> 1 topics, probabilities = model.fit_transform(cleaned_articles) File ~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\bertopic\_bertopic.py:366, in BERTopic.fit_transform(self, documents, embeddings, y) 363 documents = self._sort_mappings_by_frequency(documents) 365 # Extract topics by calculating c-TF-IDF --> 366 self._extract_topics(documents) 368 # Reduce topics 369 if self.nr_topics: File ~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\bertopic\_bertopic.py:2980, in BERTopic._extract_topics(self, documents) 2971 """ Extract topics from the clusters using a class-based TF-IDF 2972 2973 Arguments: (...) 2977 c_tf_idf: The resulting matrix giving a value (importance score) for each word per topic 2978 """ 2979 documents_per_topic = documents.groupby(['Topic'], as_index=False).agg({'Document': ' '.join}) -> 2980 self.c_tf_idf_, words = self._c_tf_idf(documents_per_topic) 2981 self.topic_representations_ = self._extract_words_per_topic(words, documents) 2982 self._create_topic_vectors() File ~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\bertopic\_bertopic.py:3121, in BERTopic._c_tf_idf(self, documents_per_topic, fit, partial_fit)

A model is produced and I know it because when I save it the file is not empty (it has some MBs). But the error propagates in the following analysis. For example, running `model.get_topic(6)` produces the following output:

> TypeError Traceback (most recent call last) Cell In[18], line 1 ----> 1 model.get_topic(6) File ~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\bertopic\_bertopic.py:1346, in BERTopic.get_topic(self, topic) 1331 """ Return top n words for a specific topic and their c-TF-IDF scores 1332 1333 Arguments: (...) 1343 ``` 1344 """ 1345 check_is_fitted(self) -> 1346 if topic in self.topic_representations_: 1347 return self.topic_representations_[topic] 1348 else: TypeError: argument of type 'NoneType' is not iterable

What could have happened here?

**Comment by MaartenGr** [comment]
It is difficult to say without knowing how you trained the model. Could you provide the full training script as well as the code you used for saving and subsequently loading the model? Also, which version of BERTopic are you using? 

> A model is produced and I know it because when I save it the file is not empty (it has some MBs).

How large is the file exactly?

**Comment by PanosP** [comment]
I used the following code:
`from bertopic import BERTopic
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer

from nltk import word_tokenize          
from nltk.stem import WordNetLemmatizer 

class LemmaTokenizer:
    def __init__(self):
        self.wnl = WordNetLemmatizer()
    def __call__(self, doc):
        return [self.wnl.lemmatize(t) for t in word_tokenize(doc)]
vectorizer_model= CountVectorizer(tokenizer=LemmaTokenizer())
model = BERTopic(vectorizer_model=vectorizer_model)
topics, probabilities = model.fit_transform(cleaned_articles)
`
Then, I saved the model with 
`model.save("first_model")`
and loaded it with 
`BERTopic.load("first_model")`

The size of the model is 385 MB

The version of BERTopic I used was 0.14.1

**Comment by MaartenGr** [comment]
There might be something wrong with your `LemmaTokenizer` as it seems that it did not return any words. Could you check that the tokenizer works correctly?

**Comment by MaartenGr** [comment]
Due to inactivity, I'll be closing this issue. Let me know if you want me to re-open the issue!
