### ISSUE TITLE
typo in jupyter notebook tutorial

### ISSUE THREAD

**Issue by datapumpernickel** [MaartenGr/BERTopic#1131]
Hi,

thanks for the amazing package and the cool tutorials - makes it a breeze to use and apply! 

I think there is a typo in the [notebook ](https://colab.research.google.com/drive/1ClTYut039t-LDtlcd-oQAdXWgcsSGTw9?usp=sharing#scrollTo=pGSwzo0Gjw6R) on advacned customization, specifically the PCA part: 

``` from sklearn.decomposition import PCA

dim_model = PCA(n_components=5)
topic_model = BERTopic(umap_model=umap_model).fit(docs)
```

I suppose `umap_model` should be replaced by `dim_model` here.

**Comment by MaartenGr** [comment]
Thanks! I just fixed the typo. It should be correct now.
