### ISSUE TITLE
.transform() does not generate probability distribution despite calculate_probabilites=True

### ISSUE THREAD

**Issue by kuchenrolle** [MaartenGr/BERTopic#1132]
When I fit BERTopic on my documents and embeddings with fit_transform(), I get a list of topic assignments and a 2d array of soft clustering probability distributions out. But if I then take that fitted model and feed it new or the same data again using .transform, I get a list of topic assignments, but no soft clustering probabilities - instead I get a 1d array with a single value per document (0 for data points considered noise).

How do I get the distributions for new data?

**Comment by MaartenGr** [comment]
Could you share your entire code for initializing the model, fitting and transforming? From what I remember, if you are using cuML's HDBSCAN, then there is not yet an implementation for predicting soft-clustering assignment.

**Comment by kuchenrolle** [comment]
I am using cuML's UMAP/HDBSCAN. Since I do get the distribution when I run fit_transform, I thought [this](https://github.com/rapidsai/cuml/pull/5247) was implemented as well, but it isn't apparently. My bad.

**Comment by MaartenGr** [comment]
In the main branch, `.transform()` should now generate probabilities for cuML's HDBSCAN since they added support for that. A pypi release will likely follow this week.
