### ISSUE TITLE
visualise heat map gives IndexError

### ISSUE THREAD

**Issue by SynBioExplorer** [MaartenGr/BERTopic#1133]
Hi Maarten,

first off, love your package, super nice and modular and thanks for write such an excellent documentation, really is appreciated.

when running
` topic_model.visualize_heatmap()`

I get an IndexError: index 98 is out of bounds for axis 0 with size 98

I retrained used nr_topics=100 during fitting and reduced outliers:
`new_topics=topic_model.reduce_outliers(docs, topics)
topic_model.update_topics(docs, topics=new_topics,representation_model=representation_model, n_gram_range=(1, 4))`

Maybe that has something to do with it? Any chance you have a fix for this?:)

Thanks in advance and all the best,

Felix

**Comment by MaartenGr** [comment]
It might be the case that there are no outliers anymore in `new_topics` right? In that case, the model still thinks there is an outlier topic, which from the perspective the clustering algorithm there still is, but the heatmap function is not aware of that. For now, this might be a bit hacky but if you set `topic_model._outliers = 0`, then it should work.

**Comment by SynBioExplorer** [comment]
That did it, thank you Maarten.

On another note, did you know that fish are statistically speaking the least run-over animal?

cheers
