### ISSUE TITLE
Hierarchical topic modelling: error: ValueError: Linkage 'Z' contains negative distances.

### ISSUE THREAD

**Issue by sophvaladou** [MaartenGr/BERTopic#1137]
Hi,
I wanted to perform the hierarchical topic modeling on my model. The model is a fitted & transformed BERTopic model that uses the default UMAP and HDBSCAN and also uses the default sentence-transformer embeddings.

This is the code I used:
hierarchical_topics = topic_model.hierarchical_topics(docs)

I got the following error:
error: ValueError: Linkage 'Z' contains negative distances.

When making my own linkage functions like this, it did not work either. I tried single, average, complete and ward clustering, but they all gave the same error.

from scipy.cluster import hierarchy as sch
linkage_function_ward = lambda x: sch.linkage(x, 'ward', optimal_ordering=True)
hierarchical_topics = topic_model.hierarchical_topics(docs, linkage_function=linkage_function_ward)

Is it possible that there is an issue with the clustering algorithm HDBSCAN? 

This is the entire error:
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<timed exec> in <module>

[/usr/local/lib/python3.9/dist-packages/bertopic/_bertopic.py](https://localhost:8080/#) in hierarchical_topics(self, docs, linkage_function, distance_function)
    872 
    873         # Use the 1-D condensed distance matrix as an input instead of the raw distance matrix
--> 874         Z = linkage_function(X)
    875 
    876         # Calculate basic bag-of-words to be iteratively merged later

<timed exec> in <lambda>(x)

2 frames
[/usr/local/lib/python3.9/dist-packages/scipy/cluster/hierarchy.py](https://localhost:8080/#) in is_valid_linkage(Z, warning, throw, name)
   2282                                  name_str)
   2283             if (Z[:, 2] < 0).any():
-> 2284                 raise ValueError('Linkage %scontains negative distances.' %
   2285                                  name_str)
   2286             if (Z[:, 3] < 0).any():
error: ValueError: Linkage 'Z' contains negative distances.

Thank you in advance!

**Comment by MaartenGr** [comment]
Thanks for the extensive description! Could you also supply the code as is, from beginning to end? Perhaps something is going on with instantiating the model. Since the distances are calculated from either the topic embeddings or c-TF-IDF matrix, it might stem from the representation model/vectorizer/ctfidf/etc.

**Comment by sophvaladou** [comment]
Below is the entire code. I loaded the BERTopic model from a previously fitted & transformed model that I saved on drive. The fitting of the loaded model can be found at the end below the ------. I used a min_topic_size of 500 since I am working with a dataset with over 3M sentences.

Thank you in advance!

!pip install cuml-cu11 --extra-index-url=https://pypi.nvidia.com
!pip install protobuf==3.20
from cuml.cluster import HDBSCAN
from cuml.manifold import UMAP
!pip install bertopic
from bertopic import BERTopic

import pickle
import pandas as pd

from bertopic import vectorizers
from bertopic.vectorizers import ClassTfidfTransformer
from sklearn.feature_extraction.text import CountVectorizer

from google.colab import drive
drive.mount('/content/drive')

output_dir = "/content/drive/MyDrive/thesis/topic_model_ST_unclean_UMAP_HDBSCAN/"
model_dir = "/content/drive/MyDrive/thesis/BERT_models/topic_model_ST_unclean_UMAP_HDBSCAN"
df = pd.read_csv("/content/drive/MyDrive/thesis/df_final_lim.csv", usecols = ["text_clean", "created_at"])
docs = df["text_clean"].astype(str)
timestamps = df["created_at"]

import numpy as np

topic_model = BERTopic.load(model_dir)

vectorizer_model = CountVectorizer(stop_words="english", ngram_range=(1, 2), min_df=500)

topic_model.update_topics(docs, vectorizer_model=vectorizer_model)

topic_model.save(model_dir + "_update")


topics_over_time_months = topic_model.topics_over_time(docs, timestamps, nr_bins=41)

with open(output_dir + "topics_over_time_months.pkl", "wb") as fOut:
    pickle.dump(topics_over_time_months, fOut, protocol=pickle.HIGHEST_PROTOCOL)


# Hierarchical topic modeling
from scipy.cluster import hierarchy as sch

%%time
linkage_function_single = lambda x: sch.linkage(x, 'single', optimal_ordering=True)
linkage_function_complete = lambda x: sch.linkage(x, 'complete', optimal_ordering=True)
linkage_function_average = lambda x: sch.linkage(x, 'average', optimal_ordering=True)
linkage_function_ward = lambda x: sch.linkage(x, 'ward', optimal_ordering=True)

hierarchical_topics = topic_model.hierarchical_topics(docs)
hierarchical_topics = topic_model.hierarchical_topics(docs, linkage_function=linkage_function_single)


-----------------------------------------------------------------------------------------------------------------------------------------


# Fitting the BERTopic model that was loaded later:
umap_model = UMAP(n_neighbors=15, n_components=5, min_dist=0.0, metric='cosine')

hdbscan_model = HDBSCAN(min_cluster_size=15, metric='euclidean', cluster_selection_method='eom', prediction_data=True)

ctfidf_model = ClassTfidfTransformer(reduce_frequent_words=True)

topic_model_ST_unclean_UMAP_HDBSCAN = BERTopic(umap_model=umap_model, hdbscan_model=hdbscan_model, ctfidf_model=ctfidf_model,
                                               min_topic_size = 500, top_n_words = 15)

**Comment by MaartenGr** [comment]
From a glance, it actually looks alright to me. The negative distances might be a result of your large `min_df` but it is not something I would generally expect. You could try to make sure that `topic_model.c_tf_idf_` only contains positive values. You can do that by accessing the values with `topic_model.c_tf_idf_.data` I believe. Then, setting the negative values to 0, or something small like 0.001 might be the solution. Having said that, I am not sure what exactly is happening here.

**Comment by sophvaladou** [comment]
Hello,

I checked the c_tf_idf_.data for negative values, but all values are positive. There are just some very small values, like 8.95709259e-05, but that's it. Is it possible that the problem is coming from the embeddings themselves?

**Comment by MaartenGr** [comment]
No, that should not happen since no embeddings are used for the hierarchical calculations, only the c-TF-IDF representations for each topic are used. Just to be sure, did you make sure that the environment that you saved the model is **exactly** the same as where you loaded it, including python version and dependencies of packages and subpackages?

**Comment by sophvaladou** [comment]
I am using Google Colab, so the Python version is the same. I installed the cuML from RAPIDS and BERTopic and used the same code for those so the environment should be exactly the same.

**Comment by MaartenGr** [comment]
> I am using Google Colab, so the Python version is the same.

Google Colab has changed its python version over the last few months so this might actually be different. 

> I installed the cuML from RAPIDS and BERTopic and used the same code for those so the environment should be exactly the same.

Not necessarily, the packages in a Google Colab environment can also change as packages are updates and Google decides it is time to change some default versions.

> I tried it with other BERTopic models that I saved and they all give the same error.

Which BERTopic version are you using? Also, is it the same version as when you saved the model? When you run `pip install bertopic` it does not fix the version so there might be a dependency conflict there.

**Comment by sophvaladou** [comment]
It would surprise me that the environments would have changed. I saved the models only a few days before I loaded them and tried to output the hierarchical topics. Both times Colab was used and the loaded packages were exactly the same, so unless the packages were updated in these few days, I don't think that is what is causing the issue.

The bertopic version is 0.14.1 and these are the versions of the other packages installed with bertopic:
Successfully installed bertopic-0.14.1 hdbscan-0.8.29 huggingface-hub-0.13.3 pynndescent-0.5.8 sentence-transformers-2.2.2 sentencepiece-0.1.97 tokenizers-0.13.2 transformers-4.27.4 umap-learn-0.5.3.

These are the packages installed with cuML:
Successfully installed cubinlinker-cu11-0.3.0.post1 cuda-python-11.8.1 cudf-cu11-23.2.0 cuml-cu11-23.2.0 dask-2023.1.1 dask-cuda-23.2.1 dask-cudf-cu11-23.2.0 distributed-2023.1.1 nvtx-0.2.5 protobuf-4.21.0 ptxcompiler-cu11-0.7.0.post1 pyarrow-10.0.0 pylibraft-cu11-23.2.0 pynvml-11.4.1 raft-dask-cu11-23.2.0 rmm-cu11-23.2.0 treelite-3.1.0 treelite-runtime-3.1.0 ucx-py-cu11-0.30.0

I installed cuML first, then downgraded protobuf to 3.20.0 before installing bertopic, since this was the only way that I was able to use both at the same time.

**Comment by MaartenGr** [comment]
> so unless the packages were updated in these few days

It might be that dependencies of dependencies are updated even in a couple of days. That is why it is important to version control the entire environment and not only the direct dependencies of BERTopic. The dependency-tree of BERTopic can be quite large if you also consider the dependencies that, for example, HDBSCAN has. 

Having said that, it might be worthwhile to inspect the distances that are created as a result of the distance function. 

```python

distance_function = lambda x: 1 - cosine_similarity(x)

# Calculate distance
embeddings = topic_model.c_tf_idf_[topic_model._outliers:]
X = distance_function(embeddings)

# Make sure it is the 1-D condensed distance matrix with zeros on the diagonal
np.fill_diagonal(X, 0)
X = squareform(X)
```

If you run the above, could you check whether `X` contains any negative values? Also, before and after the squareform. 

Lastly, I noticed something in your original message. You mentioned that you used `min_topic_size=500` but that will not do anything if you provide it with a custom `hdbscan_model`. You would need to set `min_cluster_size=500` in your HDBSCAN model instead.

**Comment by sophvaladou** [comment]
Hi,

I tried the code you provided and there are indeed negative values in both the original X and squareformed X. These negative values are all the same, i.e. -2.22044605e-16 (or at least up to the last shown decimal).

I don't know if this information is useful, but for the original X, 350 out of the 9507 values had this value of -2.22044605e-16. For the squareform X, this was 175 out of 45186771.

I tried running a model and calculating the hierarchical topics immediately after (so in the same environment) and this also gave the negative distances error.

Regarding the min_topic_size, thank you, I noticed as well and changed it :)

**Comment by MaartenGr** [comment]
In that case, it might be worthwhile to change your distance function such that it only returns positive values. There might be some rounding errors when you have values close to 0 that make it negative.

**Comment by sophvaladou** [comment]
I have tried a number of different linkage functions like this
linkage_function = lambda x: sch.linkage(x, 'ward', optimal_ordering=True, metric="euclidean")

changing the linkage to single, average, complete, ward and using it in different combinations with a metric (euclidean, cosine, jaccard, correlation, chebyshev...), but they all give the same error.

Is it a possibility to manually change the negative distances to 0 in a way? I don't really know how to pass it to the herarchical_topics() that way.

**Comment by MaartenGr** [comment]
You would have to make sure that the distance function itself does not return any negative values. Since the negative values you have are very close to zero, it would be okay to simply take the `abs` of them. I have not tried it out but I think doing something like the following should work:

```python
distance_function = lambda x: np.abs(1 - cosine_similarity(x))
```

**Comment by sophvaladou** [comment]
Hi,

I now tried this code:

distance_function = lambda x: np.abs(1 - cosine_similarity(x))
linkage_function_ward = lambda x: sch.linkage(x, 'ward', metric=distance_function, optimal_ordering=False)

hierarchical_topics = topic_model_ST_unclean_default.hierarchical_topics(text_unclean, linkage_function=linkage_function_average)

Setting  optimal_ordering=False seems to help in getting the algorithm a little further, it now gives a slightly different error message but the problem is still the same, with the negative distances.

This is now the full output:

0%|          | 0/4551 [00:00<?, ?it/s]
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<timed exec> in <module>

[/usr/local/lib/python3.9/dist-packages/bertopic/_bertopic.py](https://localhost:8080/#) in hierarchical_topics(self, docs, linkage_function, distance_function)
    898 
    899             # Find clustered documents
--> 900             clusters = sch.fcluster(Z, t=Z[index][2], criterion='distance') - self._outliers
    901             cluster_df = pd.DataFrame({"Topic": range(len(clusters)), "Cluster": clusters})
    902             cluster_df = cluster_df.groupby("Cluster").agg({'Topic': lambda x: list(x)}).reset_index()

1 frames
[/usr/local/lib/python3.9/dist-packages/scipy/cluster/hierarchy.py](https://localhost:8080/#) in is_valid_linkage(Z, warning, throw, name)
   2282                                  name_str)
   2283             if (Z[:, 2] < 0).any():
-> 2284                 raise ValueError('Linkage %scontains negative distances.' %
   2285                                  name_str)
   2286             if (Z[:, 3] < 0).any():

ValueError: Linkage 'Z' contains negative distances.

I don't see how it can still give negative distances. Is the issue something else? A problem with the scipy package maybe?

**Comment by MaartenGr** [comment]
There is a `distance_function` parameter in `topic_model.hierarchical_topics`. Please pass the distance function to that parameter and not the linkage function.

**Comment by sophvaladou** [comment]
Now it works, thank you very much!!!
