### ISSUE TITLE
Supervised BERTopic Model: Key Error 62527

### ISSUE THREAD

**Issue by apassan** [MaartenGr/BERTopic#1140]
Hello, 
I am trying to run a supervised topic model with BERTopic, but I keep getting the below error. Any advice as to how I can fix this? Thanks!
<img width="571" alt="Screenshot 2023-03-30 at 23 24 16" src="https://user-images.githubusercontent.com/13934597/228968069-b6dbdc4e-3934-40d9-9dfe-5aed15848949.png">

**Comment by MaartenGr** [comment]
I am not entirely sure what is happening here. Which version of BERTopic are you using? Also, could you show the 14 frames of errors that are currently nested?

**Comment by noahberhe** [comment]
try passing `tweets.values` into the fit_transform instead?

**Comment by MaartenGr** [comment]
Due to inactivity, I'll be closing this issue. Let me know if you want me to re-open the issue!
