### ISSUE TITLE
the differences between embedding_model and representation_model

### ISSUE THREAD

**Issue by scn0901** [MaartenGr/BERTopic#1141]
I am a beginner of bertopic, and I am not sure about the differences between embedding_model and representation_model, and how they are used in topic modeling. I guess they are all used to convert text to vector representation. Can someone please answer my question? Thanks!

**Comment by MaartenGr** [comment]
The `embedding_model` is a model that converts text to a numerical representation in order for it to be clusterable. The `representation_model`, in contrast, is used to further fine-tune the topic representations themselves. You can find more about the methods in the documentation [here](https://maartengr.github.io/BERTopic/algorithm/algorithm.html).
