### ISSUE TITLE
MaximalMarginalRelevance gives poor results when combined with PartOfSpeech

### ISSUE THREAD

**Issue by freddyheppell** [MaartenGr/BERTopic#1142]
I'm using the PartOfSpeech and MaximalMarginalRelevance representation models together, but MMR appears to have little to no effect when combined in this way.

If I use just PartOfSpeech, I get the sort of keywords I'd expect, but also with similar keywords included. Here's 3 example categories:
```
elections_election_democrats_president
missile_missiles_building_shelling
refugees_migrants_refugee_accommodation
```

If I enable MaximalMarginalRelevance, and for testing purposes set diversity=1 (I also get similar results at more reasonable values like 0.3), I still get broadly similar results, including those exact 3 categories with one having a different keyword order.
```
president_election_elections_democrats
missile_missiles_building_shelling
refugees_migrants_refugee_accommodation
```

If I use MaximalMarginalRelevance by itself, I get the effect I would expect, although of course with less useful keywords.

This is my code:

```py
umap_model = UMAP(
    n_neighbors=15,
    n_components=5,
    min_dist=0.0,
    metric='cosine',
    low_memory=False,
    random_state=42,
)

vectorizer_model = CountVectorizer(stop_words='english')
ctfidf_model = ClassTfidfTransformer(reduce_frequent_words=True)

topic_model = BERTopic(verbose=True, nr_topics='auto', min_topic_size=50,
    umap_model=umap_model, vectorizer_model=vectorizer_model, ctfidf_model=ctfidf_model,
    representation_model=[
        PartOfSpeech("en_core_web_sm"),
        MaximalMarginalRelevance(diversity=1),
    ])
topics, probs = topic_model.fit_transform(docs)

topic_model.get_topic_info()
```

**Comment by MaartenGr** [comment]
It should have been made more clear in the documentation but there is a reason for this! Maximal Marginal Relevance is an algorithm that allows for selecting a diverse subset of a set of items compared to a baseline. In BERTopic, this set of items is a set of keywords and their embeddings from which a subset of keywords is selected based on the topic embeddings. In other words, if you give MMR 10 keywords and ask it to give back 10 keywords, there will not be much change expect for the order of keywords. Instead, if you were to give MMR 20 keywords and ask it to give back 10 keywords, then it is more likely that the keywords are more diversified. In other words, if you set `top_n_words` in `PartOfSpeech` to a larger value, like 30, you will get much more diversified keywords.

**Comment by freddyheppell** [comment]
I forgot to include that I'd already tried setting it to 20 with no real effect, and 30 didn't do much either. I had to increase it to 60 but that has removed almost all of the plurals now.

**Comment by MaartenGr** [comment]
Found the issue! It seems that there was a hardcoded `top_n_words` of 10 still remaining in the `PartOfSpeech` model which resulted in the `top_n_words` parameter not having any effect. If you install BERTopic from the main branch, it should work now. Do note that a diversity 1 will not anything but a diversity of .9 will. 

Just tested it out and the following worked for me:

```python
from bertopic import BERTopic
from bertopic.representation import PartOfSpeech
from bertopic.representation import MaximalMarginalRelevance

# Create your representation model
pos = PartOfSpeech("en_core_web_sm", top_n_words=30)
mmr = MaximalMarginalRelevance(diversity=.9)
representation_model = [pos, mmr]

# Use the representation model in BERTopic on top of the default pipeline
topic_model = BERTopicNew(representation_model=representation_model, embedding_model=sentence_model).fit(docs, embeddings)
```

I performed the above with a custom dataset but it should work for any dataset. Note that if you are passing `embeddings` manually, you will also need to pass the `embedding_model`.
