### ISSUE TITLE
Stopword problem, easy to fix in source code

### ISSUE THREAD

**Issue by NewsSoup** [MaartenGr/BERTopic#1143]
I have a serious issue with the diagrams being produced - they are full of stop words!

I reproduced the bar graphs myself taking the 30 most frequent words and then filtering out the stopwords before making a graph of the 10 most frequent remaining words, and this worked remarkably well for understandable graphics. BERTopic can be upgraded significantly if this simple filter is applied before data is presented. Think of it as a post-analysis cleanup because the language models require the stopwords in place.

And on that note, BERTopic would be infinitely more useful if you allow us to pass plotly parameters as a kwarg dictionary when making visualisations. You can unpack it directly into the code that already exists, you just need to name a variable for the dictionary. This will make your product easier to integrate into websites.

**Comment by MaartenGr** [comment]
> I have a serious issue with the diagrams being produced - they are full of stop words!
> BERTopic can be upgraded significantly if this simple filter is applied before data is presented. Think of it as a post-analysis cleanup because the language models require the stopwords in place.

If I understand you correctly, this is already implemented in BERTopic. BERTopic allows for a modular selection of models that can update the topic representation **after** generating the clusters. For example, if you want to remove stopwords, you can use the following code:

```python
from bertopic import BERTopic
from sklearn.feature_extraction.text import CountVectorizer

# Remove stopwords by using the CountVectorizer
vectorizer_model = CountVectorizer(stop_words="english")
topic_model = BERTopic(vectorizer_model=vectorizer_model)
```

As a result, stopwords will be removed **after** generating the embeddings and **before** creating the topic representations. Using the CountVectorizer, there are quite some filters that you can apply yourself, either by creating custom vectorizers or by using its `analyzer` and `preprocessors` parameters. Lastly, post-analysis cleanup can also be done using one of the [representation models](https://maartengr.github.io/BERTopic/getting_started/representation/representation.html). These models fine-tune the c-TF-IDF representations using a number of techniques and often allow for nicer representations. 

> And on that note, BERTopic would be infinitely more useful if you allow us to pass plotly parameters as a kwarg dictionary when making visualisations. You can unpack it directly into the code that already exists, you just need to name a variable for the dictionary. This will make your product easier to integrate into websites.

Thanks for the feedback! I'll have to dig into this a little deeper as there are quite some places where potential kwargs could be used. For example, in the plotting function itself there can be kwargs but also the layout functions in plotly, so identifying which would serve it better is important here.

**Comment by NewsSoup** [comment]
Thanks for replying so quick. I will implement it as you suggest.

However, the issue of stopwords (and phrases for 2-grams) will exist for most vectorisers that aren't CountVectoriser. What I suggest as a universal solution is an option that can be set to true when instantiating BERTopic(), which takes any pandas DataFrame produced and deletes any entry that is in the list of stop words/phrases. 

Having a post-processing filter is like a safety net that ensures your software produces clean data even if it incorporates methods later that don't exist today. New vectorisers will come (for example, words could be hashed into smaller numbers before feeding them into neural networks in the future).

One last thing, while I remember, is that HDBSCAN only works on small datasets (100-200 docs) if you set it on leaf mode. This was not written anywhere, even off topic from BERTopic. Please consider adding this advice to your documents.
