### ISSUE TITLE
min_topic_size

### ISSUE THREAD

**Issue by sophvaladou** [MaartenGr/BERTopic#1144]
Hello,

I have an issue with the min_topic_size

I defined my BERTopic model like this:
topic_model_glove_unclean_UMAP_HDBSCAN = BERTopic(umap_model=umap_model, hdbscan_model=hdbscan_model, 
                                                                                             ctfidf_model=ctfidf_model, min_topic_size = 500, top_n_words = 15)

After fitting & transforming my documents, I noticed there are many topics which have a frequency of under 500 (with the lowest frequency being 15). I have around 3M documents and over 10k topics, that is why i set the min_topic_size to 500.

Shouldn't the smallest frequency of a topic thus be 500, or am I interpreting something wrong?

Thank you in advance!

**Comment by MaartenGr** [comment]
The `min_topic_size` parameter is a parameter that is directly passed to an HDBSCAN model, namely `min_cluster_size`. However, if you are using a custom HDBSCAN model, that will be used instead, and the `min_topic_size` will be ignored. In other words, if you set `min_cluster_size` in HDBSCAN to 500, it should work.
