### ISSUE TITLE
What is the difference between find_topic in Bertopic and word_embedding?

### ISSUE THREAD

**Issue by han-1231** [MaartenGr/BERTopic#1147]
I want to use find_topic to search topic that are most similar to a term. However, I am unsure about the underlying process used by the find_topic function to compute the similarity score. Does it employ the same approach as word_embedding, which relies on word co-occurrence? Furthermore, is the similarity score produced by find_topic indicative of the likeness between the target term and the most frequently occurring words in the matched topics? Thank you!

**Comment by MaartenGr** [comment]
To start off, it is important to realize that `find_topic` does not use co-occurences or counts at all but instead leverages embeddings. Embeddings are numeric representations of text (vectors) that typically represent the semantic and contextual nature of texts. 

In BERTopic, topics are often represented by the top 10 words that make up a topic. These 10 words are then converted to embeddings and averaged based on their collective weights. The resulting embeddings are **topic embeddings**, embeddings that should, roughly, semantically represent a topic. The `find_topic` method takes a word or phrase and converts it to an embedding. That embedding is then compared with all topic embeddings, through cosine similarity, and the best matching is then returned.

**Comment by han-1231** [comment]
Many thanks for your explanation! I now have a much better understanding of find_topic in Bertopic!
