### ISSUE TITLE
BERTopic for sentence similarity

### ISSUE THREAD

**Issue by leimish** [MaartenGr/BERTopic#1150]
Hi,
I'm new to NLP, 
I wanted to ask: is there a way to determain similarity between a query and each sentence in a set of sentences?
I've trained the model on my set of sentences

**Comment by MaartenGr** [comment]
If you want to perform sentence similarity, there is no need to use BERTopic for that. Instead, you can calculate the embeddings of the set of sentences and the query and then compare them with cosine similarity. There are more advanced techniques out there but this generally works well when starting out.

**Comment by MaartenGr** [comment]
Due to inactivity, I'll be closing this issue. Let me know if you want me to re-open the issue!
