### ISSUE TITLE
Ubuntu installation problem

### ISSUE THREAD

**Issue by rmbw51** [MaartenGr/BERTopic#1152]
I'm trying to install bertopic (conda install)
I get the followibg error:

UnsatisfiableError: The following specifications were found to be incompatible with each other:
Output in format: Requested package -> Available versions
The following specifications were found to be incompatible with your system:
  - feature:/linux-64::__glibc==2.35=0
  - feature:|@/linux-64::__glibc==2.35=0
Your installed version is: 2.35

I have:
Ubuntu 22.04.2 LTS
Python 3.10.9.final.0
Conda 23.3.1 (Miniconda)
in an environment that contains NLP packages: 
NLTK, scikit-learn, gensim, spacy, scrapy, pattern, textblob, tweepy, 
sentence-transformers

Any ideas of how to go on?
Thanks

**Comment by MaartenGr** [comment]
I am not entirely sure what is happening here. Could you try a `pip install bertopic` and show raw error log?

**Comment by MaartenGr** [comment]
The images are generated with plotly, so it might be worthwhile to check if and how spyder supports plotly output. Also, the resulting `fig` of the visualizations can also be run with `fig.show()`, so that might be worthwhile to try out.

**Comment by rmbw51** [comment]
ok, thanks

**Comment by rmbw51** [comment]
PS a fig.write_html works opening a browser window. better than nothing ;-)
