### ISSUE TITLE
Change node colour in  visualize_documents based on class

### ISSUE THREAD

**Issue by Akseli-Ilmanen** [MaartenGr/BERTopic#1153]
Hi, 

Love the BERTopic library!

I wanted to ask whether in <code>.visualize_documents</code>, it would be possible to change the colour of the document nodes according to my own class labels. All my documents have labels for 'blue', 'white', and 'red', representing slower, faster or normal time perception. It would be great to compare how topics are clustered in <code>.visualize_documents</code> (right) and my own method (left).

![image](https://user-images.githubusercontent.com/107996462/229812921-6dd27fc2-1491-496c-a121-b17b0e5dfe6c.png)

Appreciate the help!

Best
Akseli

**Comment by MaartenGr** [comment]
Although this is not directly possible using BERTopic's API, you can adapt the code in the visualization function. More specifically,  you will need to change the code [here](https://github.com/MaartenGr/BERTopic/blob/master/bertopic/plotting/_documents.py) such that it does not use `topics_per_doc` but your labels instead.

**Comment by Akseli-Ilmanen** [comment]
Hi Maarten, 

Thanks or the quick response! I tried changing <code>topics_per_doc</code> but that would prevent the nodes from getting clustered by their BERTopic topics. I was able to modify the function by passing a dictionary color_map with docs as keys, and RGB as values into the function, and modify one line see below:


'''
        # Selected topics
        for name, topic in zip(names, unique_topics):
            if topic in topics and topic != -1:
                selection = df.loc[df.topic == topic, :]
                selection["text"] = ""

                if not hide_annotations:
                    selection.loc[len(selection), :] = [None, None, selection.x.mean(), selection.y.mean(), name]


                fig.add_trace(
                    go.Scattergl(
                        x=selection.x,
                        y=selection.y,
                        hovertext=selection.doc if not hide_document_hover else None,
                        hoverinfo="text",
                        text=selection.text,
                        mode='markers+text',
                        name=name,
                        textfont=dict(size=12),
                        marker=dict(size=5, 
                        opacity=0.5, 
                        color = [color_map[doc] if doc is not None else [255, 255, 255] for doc in selection.doc]) #CHANGED HERE
                    )
                )
'''

Best
Akseli

**Comment by MaartenGr** [comment]
Glad to hear that it worked and thank you for sharing the solution!
