### ISSUE TITLE
Arrangement of topic embeddings result

### ISSUE THREAD

**Issue by tanstephenjireh** [MaartenGr/BERTopic#1156]
Hi @MaartenGr, thank you for this wonderful package as it really helped in our use case, though I want to clarify the arrangement of the `topic_embeddings_` output. If I have let's say topics output like [-1, 0, 1, ..., 13]. is the `topic_embeddings_` result also ordered in such a way? or [0, 1, ..., 13, -1]. Thank you very much.

**Comment by MaartenGr** [comment]
In principle, every iterable in BERTopic is created in such a way that it is sorted according to the thing it represents. The `.topics_` variable, for example, is ordered by the input documents. The `.topic_embeddings_` are indeed also ordered by the topics.
