### ISSUE TITLE
Pre-trained embeddings give error when nr_topics='auto'

### ISSUE THREAD

**Issue by MarkWClements** [MaartenGr/BERTopic#1162]
I am trying to train the BERTopic model using previously stored embeddings from the `SentenceTransformer()` module. I create the embeddings and save the numpy array to a disk first because I have a lot of documents (200k+) and I don't want to wait an hour for the embeddings to be created each time I train my topic model. However, I also want to retain the ability to call `find_topics()` on the resulting model. I read this post [https://github.com/MaartenGr/BERTopic/issues/280](url) and decided to include the embedding model into the call to the BERTopic class as follows

```python
from bertopic import BERTopic
from bertopic.vectorizers import ClassTfidfTransformer
from umap import UMAP
from hdbscan import HDBSCAN
from sentence_transformers import SentenceTransformer
from sklearn.feature_extraction.text import CountVectorizer

# My list of documents to embed
docs = my_list

# Embed documents
model_object = SentenceTransformer("./mypath/all-MiniLM-L6-v2")
embeddings = model_object.encode(docs, show_progress_bar=True)

# Save embedding
np.save("./my_embeddings/embeding_array.npy", embeddings)

# Load embeddings
my_embeddings = np.load("./my_embeddings/embeding_array.npy")

# Reduce dimensionality.
umap_model = UMAP(n_neighbors=15, n_components=5, metric='cosine', low_memory=False, random_state=1234)

# Cluster reduced embeddings.
hdbscan_model = HDBSCAN(min_cluster_size=50, metric='euclidean', cluster_selection_method='eom', prediction_data=True, min_samples=5)

# Tokenize topics. 
vectorizer_model = CountVectorizer(ngram_range=(1,2), stop_words="english", min_df=20)

# Create topic representation.
ctfidf_model = ClassTfidfTransformer(bm25_weighting=True, reduce_frequent_words=True)

# BERTopic Pipeline.
topic_model = BERTopic(embedding_model = model_object,  
                        umap_model = umap_model, 
                        hdbscan_model = hdbscan_model,
                        vectorizer_model=vectorizer_model, 
                        ctfidf_model=ctfidf_model,
                        top_n_words = 10,
                        min_topic_size = 50,
                        calculate_probabilities = False, 
                        nr_topics = "auto", 
                        verbose=True)

# Fit the topic model using my previously stored embeddings
topics, probs = topic_model.fit_transform(docs, my_embeddings )
```

However, when I run this code, I get the following error

```
2023-04-05 16:47:27,934 - BERTopic - Reduced dimensionality
2023-04-05 16:47:39,370 - BERTopic - Clustered reduced embeddings
Traceback (most recent call last):
  File "bert_topic_model.py", line 367, in <module>
    train_bert('20230228',params)
  File "bert_topic_model.py", line 304, in train_bert
    topics, probs = topic_model.fit_transform(docs, embeddings)
  File "C:\Users\mclements\Anaconda3\envs\topic_modeling\lib\site-packages\bertopic\_bertopic.py", line 370, in fit_transform
    documents = self._reduce_topics(documents)
  File "C:\Users\mclements\Anaconda3\envs\topic_modeling\lib\site-packages\bertopic\_bertopic.py", line 3224, in _reduce_topics
    documents = self._auto_reduce_topics(documents)
  File "C:\Users\mclements\Anaconda3\envs\topic_modeling\lib\site-packages\bertopic\_bertopic.py", line 3304, in _auto_reduce_topics
    self._extract_topics(documents)
  File "C:\Users\mclements\Anaconda3\envs\topic_modeling\lib\site-packages\bertopic\_bertopic.py", line 2980, in _extract_topics
    self.c_tf_idf_, words = self._c_tf_idf(documents_per_topic)
  File "C:\Users\mclements\Anaconda3\envs\topic_modeling\lib\site-packages\bertopic\_bertopic.py", line 3121, in _c_tf_idf
    self.vectorizer_model.fit(documents)
  File "C:\Users\mclements\Anaconda3\envs\topic_modeling\lib\site-packages\sklearn\feature_extraction\text.py", line 1291, in fit
    self.fit_transform(raw_documents)
  File "C:\Users\mclements\Anaconda3\envs\topic_modeling\lib\site-packages\sklearn\feature_extraction\text.py", line 1352, in fit_transform
    raise ValueError("max_df corresponds to < documents than min_df")
ValueError: max_df corresponds to < documents than min_df

```

I do not get the same error if I just remove the code `embedding_model = model_object` when I instantiate the `BERTopic()` class. I would like to be able to store the embeddings to use later as well as have access to the `find_topics()` method on the fitted topic model, but I can't figure out what is happening. Any help would be appreciated!

**Comment by MaartenGr** [comment]
This is most likely due to the `min_df` parameter in your `CountVectorizer`. It removes words that appear infrequently but it will fail if you set it too high. It might be the case that very small topics are created and that the `min_df` parameter removes every single word in a topic. You can find more about it [here](https://github.com/MaartenGr/BERTopic/issues/810).

**Comment by MarkWClements** [comment]
Hi @MaartenGr I'll play around with the `min_df` parameter, however, it is already set at the default value of 20 and I hesitate to reduce it even further. Weirdly though, if I remove the `embedding_model = model_object` from the instantiation of the `BERTopic` class and re-run the code with `nr_topics="auto"` I get a different error that I have never encountered before:

```
2023-04-06 01:37:03,509 - BERTopic - The dimensionality reduction algorithm did not contain the `y` parameter and therefore the `y` parameter was not used
```

Do you know what is causing this? The code runs fine if I leave `nr_topics=None` as is the default.

**Comment by MaartenGr** [comment]
> I'll play around with the min_df parameter, however, it is already set at the default value of 20 and I hesitate to reduce it even further.

If I am not mistaken, 20 is not a default value of the CountVectorizer's `min_df` parameter. By default, it is set at 0, so I think you can safely decrease it. Having said that, if you want to keep it at that value, then it might be worthwhile to read the issue I mentioned before. More specifically, I would advise reading through [this](https://github.com/MaartenGr/BERTopic/issues/810#issuecomment-1296117231) comment as it illustrates what is happening here. Changing `nr_topics="auto"` to at least 20 should solve the issue. 

> I get a different error that I have never encountered before:

Normally, you can safely ignore this as you are not using the `y` parameter in BERTopic and it is merely a logging on info level and not an error. However, it is surprising that you get this output since you are using the default UMAP model which does allow for the `y` parameter to be used. Just to be sure, is the code exactly as you mentioned

**Comment by MaartenGr** [comment]
Due to inactivity, I'll be closing this issue. Let me know if you want me to re-open the issue!
