### ISSUE TITLE
Need 15 words in the topics

### ISSUE THREAD

**Issue by Nee-DS** [MaartenGr/BERTopic#1167]
The topics do not show 15 words, although I am giving the top_n_words=15 in the model . Any suggestion?

topic_model = BERTopic(
    embedding_model=sentence_model,
    umap_model=umap_model,
    hdbscan_model=hdbscan_model,
    vectorizer_model=vectorizer,calculate_probabilities=True,top_n_words=15, representation_model=representation_model).fit(text, embeddings)

**Comment by MaartenGr** [comment]
Could you share the entire code for instantiating the topic model? For example, what is in `representation_model`? You also need to specify `top_n_words` there.

**Comment by Nee-DS** [comment]
# Create embeddings from the documents
sentence_model = SentenceTransformer("all-MiniLM-L6-v2")
embeddings = sentence_model.encode(text)

#avoid repetation of words
representation_model = MaximalMarginalRelevance(diversity=0.2)

# Define sub-models
vectorizer = CountVectorizer(stop_words="english")
umap_model = UMAP(n_neighbors=15, n_components=5, min_dist=0.0, metric='cosine', random_state=42)
hdbscan_model = HDBSCAN(min_cluster_size=10, min_samples=2, metric='euclidean', cluster_selection_method='eom',prediction_data=True)

# Train our topic model with BERTopic
topic_model = BERTopic(
    embedding_model=sentence_model,
    umap_model=umap_model,
    hdbscan_model=hdbscan_model,
    vectorizer_model=vectorizer,calculate_probabilities=True,top_n_words=15, representation_model=representation_model).fit(text, embeddings)

**Comment by Nee-DS** [comment]
does it makes a difference if we specify "top_n_words=15" under vectorizer_model or separately?

**Comment by Nee-DS** [comment]
I am looking for this solution ASAP. Please reply. Thanks

**Comment by MaartenGr** [comment]
You are in luck that I happen to be online but do note that I, unfortunately, cannot guarantee a quick response (< 1 hour or even less than a day) for every issue. Having said that, your representation model also has a `top_n_words` parameter that you will need to set to 15. Each representation model also has this parameter since you might want to have a different number of words passing between representation models if you are chaining them.

**Comment by Nee-DS** [comment]
Sorry! and Thank you for your reply. I really appreciate it. The error is solved :-)
