### ISSUE TITLE
corrupted size vs. prev_size error while running BERTopic

### ISSUE THREAD

**Issue by ankur287** [MaartenGr/BERTopic#1172]
I am facing an issue while running the model for 800K documents. These are large documents and the model works fine when I take the number of documents down to 400K. Below is the screenshot of the error:

<img width="1220" alt="BERTopic Error" src="https://user-images.githubusercontent.com/30616576/230704851-0a7bfa31-e8ed-4064-8245-cede1b15dfb3.png">

I thought it's an issue with countvectorizer vocabulary size being too high but reducing it to a value where other model works fine still gave the same error. Please let me know what to do.

Thanks

**Comment by MaartenGr** [comment]
Could you share your full code, including how you instantiated the model? Also, which version of BERTopic are you using?

**Comment by ankur287** [comment]
Thanks for quick response.

bertopic==0.14.1

Here is the full code:
        
        vectorizer = CountVectorizer(stop_words="english", max_df=0.9, min_df = 0.1)
    
        umap_model = UMAP(n_components=50,
                                          n_neighbors=10,
                                          min_dist=0.0)
        hdbscan_model = HDBSCAN(min_cluster_size=200)

        ctfidf_model = ClassTfidfTransformer(reduce_frequent_words=True)

        topic_model = BERTopic( 
                                embedding_model=embedding_model,
                                vectorizer_model=vectorizer,
                                umap_model=umap_model,
                                hdbscan_model=hdbscan_model,
                                ctfidf_model=ctfidf_model,
                                top_n_words = 30,
                                min_topic_size = 100,
                                low_memory = True,
                                verbose = True
                            )

**Comment by MaartenGr** [comment]
Thanks for sharing! Could you share the full code? As in, the imports, the fitting process, extracting the documents, etc. For example, it is currently not clear whether UMAP is the cpu or gpu version or whether the fitting process was done in a semi-supervised manner or not, etc.

**Comment by ankur287** [comment]
Updated the comment above with full code

**Comment by ankur287** [comment]
Hey, Did you get a chance to look at this ?

**Comment by MaartenGr** [comment]
It is a rather unexpected [error](https://stackoverflow.com/questions/49628615/understanding-corrupted-size-vs-prev-size-glibc-error) that, to me, feels like it is an issue with the environment in which you are working. It might be best to start from a completely fresh environment and re-installing everything there. Also, it might be best to use a python version higher than 3.7 since that will not receive any security updates in the future anymore, so many packages have stopped supporting 3.7 which could also explain the issue.

**Comment by ankur287** [comment]
Thanks for the response. I did a deep dive and issue is with _create_topic_vectors. When i remove embedding model, i don't get an error. Also, adding MaximalMarginalRelevance gives the same error. I have removed them for now and it works.
Thanks
