### ISSUE TITLE
get <ufunc 'invert'> error when trying to load BERTopic

### ISSUE THREAD

**Issue by petra-lo** [MaartenGr/BERTopic#1175]
I get the following message when I try to import BERTopic from bertopic:
KeyError: <ufunc 'invert'>

Would really appreciate any help!!

**Comment by MaartenGr** [comment]
Could you share how you installed BERTopic? Also, which version of BERTopic did you have? Lastly, it might be worthwhile to start from a completely fresh environment and install BERTopic there. Often, these types of errors are due to dependency conflicts.

**Comment by MaartenGr** [comment]
Due to inactivity, I'll be closing this issue. Let me know if you want me to re-open the issue!
