### ISSUE TITLE
Error with min_topic_size=2

### ISSUE THREAD

**Issue by nadiafelix** [MaartenGr/BERTopic#118]
I would like to test the topic model varying the number of topics and calculating the coherence, like this:

for i in range(2,10,2):
      sentence_model = SentenceTransformer("/portuguese_bert")
      topic_model = BERTopic(embedding_model=sentence_model, calculate_probabilities=True, nr_topics=i,min_topic_size=2, verbose=True)
      topics,probabilities = topic_model.fit_transform(comentariosList)

I have this error:
2021-05-11 22:20:36,229 - BERTopic - Transformed documents to Embeddings

2021-05-11 22:20:46,987 - BERTopic - Reduced dimensionality with UMAP
2021-05-11 22:20:47,203 - BERTopic - Clustered UMAP embeddings with HDBSCAN
2021-05-11 22:21:07,474 - BERTopic - Reduced number of topics from 82 to 3
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-8-0e4600a817a8> in <module>()
     46     #               for topic in range(len(set(documents["Topic"]))-1)]
     47     topic_words = [[words for words, _ in topic_model.get_topic(topic)] 
---> 48                   for topic in range(len(set(topics))-1)]
     49 
     50     # Evaluate

<ipython-input-8-0e4600a817a8> in <listcomp>(.0)
     46     #               for topic in range(len(set(documents["Topic"]))-1)]
     47     topic_words = [[words for words, _ in topic_model.get_topic(topic)] 
---> 48                   for topic in range(len(set(topics))-1)]
     49 
     50     # Evaluate

TypeError: 'bool' object is not iterable

What can be this? I suspect that is about min_topic_size=2...

**Comment by MaartenGr** [comment]
From a quick glance, it seems to be related to the low `nr_topics`. However, it is difficult to read what is part of your code, what code is from BERTopic, and what the error message is. Could you separate them into distinct blocks where the code is put into the code blocks? You can do that like this:

<pre>
```python
My code here!
```
</pre>

Also, it seems that on line 50 there is a comment named "# Evaluate" which I believe is not anywhere in the most recent version of BERTopic. Could you share your entire code? It now seems that some evaluation function is missing.
