### ISSUE TITLE
Online topic modeling_Partial_fit

### ISSUE THREAD

**Issue by nfsedaghat** [MaartenGr/BERTopic#1185]
Hi,
I am going to use online topic modeling in my project on a data with 360 documents. I use the below code as I copied it from the BERTopic webpage:

`    # Incrementally fit the topic model by training on 1000 documents at a time and track the topics in each iteration
    chunkSize = 100
    doc_chunks = [df.loc[i:i+chunkSize-1, 'Description'] for i in range(0, len(df), chunkSize)]

    topics = []
    ll = 0
    for docs in doc_chunks:
        ll += len(docs)
        topic_model.partial_fit(docs)
        print('Number of docs as input to the model: ', len(docs), '\n', 'Number of returned topics: ', len(topic_model.topics_), '\n \n')
        print('**********')
        topics.extend(topic_model.topics_)
`
After running this snippet, this is what I get:

```
Number of docs as input to the model:  100 
 Number of returned topics:  100 
 
**********
Number of docs as input to the model:  100 
 Number of returned topics:  95 

**********
Number of docs as input to the model:  100 
 Number of returned topics:  100 

**********
Number of docs as input to the model:  60 
 Number of returned topics:  60 

```
As you see in the second chunck while the number of documents is 100, the number of returned topics is 95. Why such thing happens?
I need to mention that sometimes it runs perfectly but sometimes this case occurs.

**Comment by MaartenGr** [comment]
That is strange indeed! That might be a result of the clustering model but I cannot be sure. Could you share your full code?

**Comment by MaartenGr** [comment]
I am not entirely sure what is happening here. Could you try it with a different clustering algorithm instead?

**Comment by MaartenGr** [comment]
You can do those things if you make sure that you also track the `.topics_`. With respect to interpretation, that depends on your use case. The representation might change over time, so tracking might be worthwhile if it is important to your use case.
