### ISSUE TITLE
How I can increase the number of words per topic

### ISSUE THREAD

**Issue by bahareharandizade** [MaartenGr/BERTopic#119]
Hello,

I am going to increase the number of words per topic to 100 or more. I followed your code and I was thinking that I have to change this line  "indices = c_tf_idf.argsort()[:, -30:]" in "_extract_words_per_topic" function in "_bertopic.py", however I am not sure if it is a correct way to do that or not.... also why you hard coded this number and no parameter is defined for this? Does it have a particular reason?

Thank you so much for your time and this amazing github code.

**Comment by MaartenGr** [comment]
You can use `top_n_words` when initializing BERTopic to select the number of words you would like in a topic. As you have noticed, I have put a hard cap at 30. This was for several reasons. First, when you are using MMR with too many candidates (e.g., 100) then there will be too little emphasis on words that have higher c-TF-IDF values. Second, the top 30 words have some meaning with respect to the topic, words after the top 30 have very little meaning and in practice are not the best representation of a topic. For those reasons, it is highly suggested to only extract the top 30 words.

Having said that, if you would like to extract more words, then it is indeed a manner of changing `c_tf_idf.argsort()[:, -30:]` to, for example, `c_tf_idf.argsort()[:, -100:]` and setting `top_n_words` any value less than 100. However, keep in mind how that will affect the topic model!

**Comment by florianlorisch** [comment]
Hi Maarten, a somewhat related question. Is there a way to increase the words per topic topic_model.topics_over_time? It seems like this is capped at 5, even though top_n_words is set to 10. Is that correct and is there a way to change this? Cheers!

**Comment by florianlorisch** [comment]
Figured it out :)
