### ISSUE TITLE
Running bertopic on a large-scale dataset

### ISSUE THREAD

**Issue by scn0901** [MaartenGr/BERTopic#1190]
Hello, I have a problem running bertopic on a large-scale dataset and would like to ask you for advice.

In my research, I tried to run bertopic on nearly 2 million tweets. I used cuml to accelerate UMAP and HDBSCAN, but the program reported an error during the dimensionality reduction stage of HDBSCAN because of MemoryError. Here are the details (I have hidden some content about my personal information):

**1. Code**
<img width="1059" alt="image" src="https://user-images.githubusercontent.com/68333026/232447633-f5cdca87-a9a6-477f-b688-79eb66a7e61d.png">
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "0"
import pandas as pd
from bertopic import BERTopic
from cuml.cluster import HDBSCAN
from cuml.manifold import UMAP

doc = pd.read_csv('data.csv', index_col='id', lineterminator='\n')

umap_model = UMAP(n_neighbors=15,
                    n_components=5,
                    min_dist=0.0,
                    metric='cosine',
                    low_memory=False,
                    random_state=0)

hdbscan_model = HDBSCAN(min_cluster_size=10,
                        metric='euclidean',
                        cluster_selection_method='eom',
                        prediction_data=True)

topic_model = BERTopic(calculate_probabilities=True, verbose=True, umap_model=umap_model, hdbscan_model=hdbscan_model)

topics, probs = topic_model.fit_transform(list(doc['text']))

**2. Error log**
<img width="1356" alt="image" src="https://user-images.githubusercontent.com/68333026/232447739-cd8658cf-3a2e-48e4-9ae1-a673b64f090a.png">
2023-04-14 10:34:34,597 - BERTopic - Transformed documents to Embeddings
2023-04-14 10:46:17,920 - BERTopic - Reduced dimensionality
Traceback (most recent call last):
  File "bertopic_code.py", line 31, in <module>
    topics, probs = topic_model.fit_transform(list(doc['text']))
  File "/data/private/user/python_envs/bertopic/lib/python3.8/site-packages/bertopic/_bertopic.py", line 359, in fit_transform
    documents, probabilities = self._cluster_embeddings(umap_embeddings, documents, y=y)
  File "/data/private/user/python_envs/bertopic/lib/python3.8/site-packages/bertopic/_bertopic.py", line 2925, in _cluster_embeddings
    probabilities = hdbscan_delegator(self.hdbscan_model, "all_points_membership_vectors")
  File "/data/private/user/python_envs/bertopic/lib/python3.8/site-packages/bertopic/cluster/_utils.py", line 40, in hdbscan_delegator
    return cuml_hdbscan.all_points_membership_vectors(model)
  File "prediction.pyx", line 186, in cuml.cluster.hdbscan.prediction.all_points_membership_vectors
  File "/data/private/user/python_envs/bertopic/lib/python3.8/site-packages/cuml/internals/memory_utils.py", line 85, in cupy_rmm_wrapper
    return func(*args, **kwargs)
  File "/data/private/user/python_envs/bertopic/lib/python3.8/site-packages/nvtx/nvtx.py", line 101, in inner
    result = func(*args, **kwargs)
  File "/data/private/user/python_envs/bertopic/lib/python3.8/site-packages/cuml/internals/array.py", line 822, in empty
    mem_type.xpy.empty(shape, dtype, order), index=index
  File "/data/private/user/python_envs/bertopic/lib/python3.8/site-packages/cupy/_creation/basic.py", line 22, in empty
    return cupy.ndarray(shape, dtype, order=order)
  File "cupy/_core/core.pyx", line 136, in cupy._core.core.ndarray.__new__
  File "cupy/_core/core.pyx", line 224, in cupy._core.core._ndarray_base._init
  File "cupy/cuda/memory.pyx", line 742, in cupy.cuda.memory.alloc
  File "/data/private/user/python_envs/bertopic/lib/python3.8/site-packages/rmm/rmm.py", line 230, in rmm_cupy_allocator
    buf = librmm.device_buffer.DeviceBuffer(size=nbytes, stream=stream)
  File "device_buffer.pyx", line 85, in rmm._lib.device_buffer.DeviceBuffer.__cinit__
MemoryError: std::bad_alloc: out_of_memory: CUDA error at: /project/python/_skbuild/linux-x86_64-3.8/cmake-build/_deps/rmm-src/include/rmm/mr/device/cuda_memory_resource.hpp:70: cudaErrorMemoryAllocation out of memory

**3. Relevant package versions**
bertopic 0.14.1
cuml-cu11 23.2.0

**4. Hardware Configuration**
A100 40GB gpu (cuda 11.2)
500GB memory

I've confirmed that no other gpu-requiring programs were running at the same time, and that my program can run successfully on a sample of 100,000 tweets.

What I want to know are:
1. Why did my program run out of memory?
2. In theory, how much data can I run on with my hardware?
3. How do I need to modify my code to run successfully?

**Comment by scn0901** [comment]
Grateful! It works!

Sorry, because you just mentioned min_cluster_size / min_samples, I have three more questions related to it:
1. What is the difference between min_cluster_size and min_samples in HDBSCAN algorithm?
2. If I need to have fewer topics and each topic is more general, and I hope there are not too many outliers, how should I adjust min_cluster_size and min_samples?
3. Using cuml to run HDBSCAN, when I increase min_cluster_size and min_samples respectively, how will the GPU memory consumption change?

**Comment by beckernick** [comment]
Glad to hear it!

> 1. What is the difference between min_cluster_size and min_samples in HDBSCAN algorithm?

The [HDBSCAN docs](https://hdbscan.readthedocs.io/en/latest/parameter_selection.html#selecting-min-cluster-size) provide an overview. The latter is more related to whether points end up as noise.

> 2. If I need to have fewer topics and each topic is more general, and I hope there are not too many outliers, how should I adjust min_cluster_size and min_samples?

You'll likely need to test this empirically, but it sounds like you may want to try a high value for `min_cluster_size` and a relatively smaller value for `min_samples`.

> 3. Using cuml to run HDBSCAN, when I increase min_cluster_size and min_samples respectively, how will the GPU memory consumption change?

The issue/comments linked above should provide some insight into the memory behavior and how the number of clusters is. a large driver of the memory requirements.

**Comment by gdreiman-insitro** [comment]
Slight hijack (because [4879](https://github.com/rapidsai/cuml/issues/4879) is closed), but is there a reason that `all_points_membership_vectors` has to allocate the entire membership vector at once? I've had similar OOM issues, and I tried to get around them by manually batching my training points and running them through `membership_vector` but I'm not sure that this yields identical cluster predictions (in particular `membership_vector` occasionally returns a row of `nan` predicted probabilities for membership).

If `all_points_membership_vectors` already has a `batch_size` parameter, couldn't it also allocate (`batch_size * n_clusters * sizeof(float)`) sized vectors for computation and store computed portions on RAM instead?

**Comment by MaartenGr** [comment]
Due to inactivity, I'll be closing this issue. Let me know if you want me to re-open the issue!
