### ISSUE TITLE
I ran the quickstart code,but it exited after "Transformed documents to Embeddings"

### ISSUE THREAD

**Issue by Genius-pig** [MaartenGr/BERTopic#1194]
I followed the readme doc, ran the code below
```python
from bertopic import BERTopic
from sklearn.datasets import fetch_20newsgroups

docs = fetch_20newsgroups(subset='all', remove=('headers', 'footers', 'quotes'))['data']


topic_model = BERTopic(verbose= True)
topics, probs = topic_model.fit_transform(docs)
topic_model.get_topic_info()
```
but it existed after this

```
D:\keyword\keybert\venv\Scripts\python.exe D:\keyword\keybert\main.py 
Batches: 100%|██████████| 589/589 [08:23<00:00,  1.17it/s]
2023-04-19 16:59:04,629 - BERTopic - Transformed documents to Embeddings

Process finished with exit code -1073741819 (0xC0000005)

```

### software

```
Python 3.10.10  
```

### my hardware

cpu: AMD Ryzen 9 5950X 16-Core
gpu: NVIDIA GeForce RTX 3070

**Comment by Genius-pig** [comment]
> Hmm, I am not sure what is happening here. I have to say though that it is surprising that the embedding step takes that much time. Are you sure that your GPU is being used? Also, it might be worthwhile to start from a completely fresh environment and installing BERTopic there.

```
import tensorflow as tf
print("GPUs Available: ", tf.config.list_physical_devices('GPU'))
``

gives me

```
D:\keyword\keybert\venv\Scripts\python.exe D:\keyword\keybert\main.py 
GPUs Available:  [PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
```

I think it makes sure GPU is being used.

**Comment by Genius-pig** [comment]
It can't be run on windoes native. I try in wsl, then it succeed.

**Comment by MaartenGr** [comment]
Glad to hear that it worked! Most likely it did not detect the GPU properly in pytorch.
