### ISSUE TITLE
Topics per class  doesn't work after outliers reduction

### ISSUE THREAD

**Issue by zhang9711** [MaartenGr/BERTopic#1195]
I am using the BERTopic to do topic modeling on the Chinese dataset. Specifically, all of my data has a label, so I am going to use topics per class function. In my case: 
I used this : 
new_topics = topic_model.reduce_outliers(docs, topics) 
topic_model.update_topics(docs, topics=new_topics) 

to reduce the outliers. 
And then, I used this:

topics_per_class = topic_model.topics_per_class(docs, classes=classes) 
topic_model.visualize_topics_per_class(topics_per_class, top_n_topics=30) 

to generate the figures, but I don't why I met this issues:

File [~/miniconda3/envs/bertopic/lib/python3.9/site-packages/bertopic/_bertopic.py:793](https://vscode-remote+ssh-002dremote), in BERTopic.topics_per_class(self, docs, classes, global_tuning)
    791 if global_tuning:
    792     c_tf_idf = normalize(c_tf_idf, axis=1, norm='l1', copy=False)
--> 793     c_tf_idf = (global_c_tf_idf[documents_per_topic.Topic.values + self._outliers] + c_tf_idf) [/](https://vscode-remote+ssh-002dremote) 2.0
    795 # Extract the words per topic
    796 words_per_topic = self._extract_words_per_topic(words, selection, c_tf_idf)

File [~/miniconda3/envs/bertopic/lib/python3.9/site-packages/scipy/sparse/_index.py:33](https://vscode-remote+ssh-002dremote), in IndexMixin.__getitem__(self, key)
     32 def __getitem__(self, key):
---> 33     row, col = self._validate_indices(key)
     34     # Dispatch to specialized methods.
     35     if isinstance(row, INT_TYPES):

File [~/miniconda3/envs/bertopic/lib/python3.9/site-packages/scipy/sparse/_index.py:138](https://vscode-remote+ssh-002dremote), in IndexMixin._validate_indices(self, key)
    136         row += M
    137 elif not isinstance(row, slice):
--> 138     row = self._asindices(row, M)
    140 if isintlike(col):
    141     col = int(col)
...
--> 170     raise IndexError('index (%d) out of range' % max_indx)
    172 min_indx = x.min()
    173 if min_indx < 0:

IndexError: index (148) out of range

Here, in my case, I have generated 148 topics in total. But I don't know why there shows IndexError: index (148) out of range. 
Does anyone have the same experience.

**Comment by MaartenGr** [comment]
Do the new topics, `new_topics`, contain any -1 value? If not, then I think that might be the issue. The model still thinks there are outliers in your topics since the underlying cluster model has created them. It might be a bit hacky but if you have enough data, simply setting `new_topics[-1] = -1` or keeping a single outlier would do the trick here. Do not that if you are looking to have no outliers at all, I would not recommend using `.reduce_outliers` but use a clustering algorithm that does not generate any outliers, like k-Means.

**Comment by MaartenGr** [comment]
Yes indeed, the topic model still assumes that there is at least one document clustered into -1 which is not the case after using `.reduce_outliers` to completely remove the -1 topic. Instead, you can also run the following before during the class-based analysis:

```python
topic_model._outliers = 0
```

**Comment by zhang9711** [comment]
Thank you Maarten, I solved my problems. Thank you so much!
