### ISSUE TITLE
When I try to fit an array with 4096 sentences or more, the kernel dies in jupyter

### ISSUE THREAD

**Issue by fernandrez-ai** [MaartenGr/BERTopic#1199]
As simple as that, nor running out of memory at all!

![image](https://user-images.githubusercontent.com/123366303/233437152-35c50f1f-3fd7-46ca-a30b-0cfb827374a2.png)

![image](https://user-images.githubusercontent.com/123366303/233438361-6b0b25b1-2d88-4ef8-b7d7-19c9eed57b4d.png)

**Comment by Windowscoder** [comment]
Same question, 4095 is ok , but crash at 4096, seems like a limit.

**Comment by Windowscoder** [comment]
Try to reinstall pynndescent.
`pip uninstall pynndescent
pip install pynndescent`
It's maybe a bug of UMAP [https://github.com/lmcinnes/umap/issues/452](url)

**Comment by dechantoine** [comment]
> Try to reinstall pynndescent. `pip uninstall pynndescent` `pip install pynndescent` It's maybe a bug of UMAP [https://github.com/lmcinnes/umap/issues/452](url)

Hi, I ran across the same issue as @fernandrez-ai and this solve it straightforward. Thanks a lot @Windowscoder !

**Comment by fernandrez-ai** [comment]
@Windowscoder @dechantoine 
Thank you guys! Will close this as this solved it! Really appreciate the prompt response, amazing!
