### ISSUE TITLE
Making embedding computation more scalable

### ISSUE THREAD

**Issue by DmitryKey** [MaartenGr/BERTopic#12]
Hello!

    2020-10-31 14:35:53,446 - BERTopic - Loaded BERT model
    INFO:BERTopic:Loaded BERT model
    2020-10-31 15:29:37,627 - BERTopic - Transformed documents to Embeddings

It currently takes about an hour to compute embeddings for 20,000 documents in the 20 Newsgroups loaded with:

    docs = fetch_20newsgroups(subset='all')['data']

To scale this better, one way is to use the bert-as-service with multiple workers. Have you thought of a possibility to make embedding computation pluggable?

**Comment by MaartenGr** [comment]
The scalability is also improved if you use GPU-based acceleration. For example, if you run this in Google Colaboratory with a GPU-kernel the model should run much faster! 

I definitely intend to make the embeddings pluggable at some point. However, I started without that option as the sentence transformer embeddings are quite good at creating the clusters needed for computing the topics. 

The easiest way would be to create the embeddings yourself and plug them as a parameter in the `fit`, `transform`, and `fit_transform` methods. How does that sound? Would you use it like that?

**Comment by DmitryKey** [comment]
Hi @MaartenGr thanks for a quick response! Yes, that could work: I could compute the embeddings externally, say with bert-as-service running with multiple workers, and pass them them in. 

Thanks for the hint about GPUs -- I'm thinking from the productization perspective and will be cool to be able to have CPUs as well.

**Comment by MaartenGr** [comment]
Done, you can find the full changes in (#13). I have added the option for custom embeddings also in Pypi, so if you simply do a `pip install --upgrade bertopic` then you should be up-to-date! You can find documentation for custom embeddings in the Readme or on https://maartengr.github.io/BERTopic/

**Comment by DmitryKey** [comment]
This is fantastic, thanks a bunch! Will test and let you know.
