### ISSUE TITLE
Finding new topics in Online model

### ISSUE THREAD

**Issue by guiOsorio** [MaartenGr/BERTopic#1215]
Hi Maarten,

First of all, thanks for your work on BERTopic, it has been very useful!
I have a large dataset (around 2 million documents) that I want to use to train the first batch of an online model, which will be updated with new data periodically. I am currently experimenting with two batches: a 10k dataset (to be used as the initial batch) and a 5k dataset (to be used as the second batch). 
I have two main goals with this:
- create buckets from similar topics, and be able to assign a doc that comes in in production to its bucket
- identify new topics at each update of the model

Regarding creating new buckets, instead of merging topics, I am more interested in having a separate data structure that stores the topics which belong to a bucket. My question is, at each update of the model, will the existing topics change (for example, will topic 50 after training batch 1 still be topic 50 after batch 2?

Regarding my other goal, I am working on creating an online model as described in the docs with the river package. Here is the code I used to create the river class:
```
from river import stream

class CustomRiver:
    def __init__(self, model):
        self.model = model

    def partial_fit(self, umap_embeddings):
        for umap_embedding, _ in stream.iter_array(umap_embeddings):
            self.model = self.model.learn_one(umap_embedding)

        labels = []
        for umap_embedding, _ in stream.iter_array(umap_embeddings):
            label = self.model.predict_one(umap_embedding)
            proba = self.model.predict_proba_one(umap_embedding)
            labels.append(label)

        
        self.labels_ = labels
        return self
```
And here is the code I am using to train the model:
```
from river import cluster
from bertopic.vectorizers import OnlineCountVectorizer
from bertopic.vectorizers import ClassTfidfTransformer
from variables import CustomRiver

# Using DBSTREAM to detect new topics as they come in
cluster_model = CustomRiver(cluster.DBSTREAM())
vectorizer_model = OnlineCountVectorizer(stop_words="english")
ctfidf_model = ClassTfidfTransformer(reduce_frequent_words=True, bm25_weighting=True)

# Prepare model
online_model = BERTopic(
    embedding_model="all-MiniLM-L6-v2",
    hdbscan_model=cluster_model, 
    vectorizer_model=vectorizer_model, 
    ctfidf_model=ctfidf_model,
    calculate_probabilities=True,
    verbose=True
)

topics = []
# First chunk (10k)
online_model.partial_fit(docs)
topics.extend(online_model.topics_)
online_model.save("./static/models/bertopic_online_10k")

# Second chunk (5k)
online_model.partial_fit(docs_to_add)
topics.extend(online_model.topics_)
online_model.topics_ = topics
online_model.save("./static/models/bertopic_online_15k")
```

First, is there a way for me to get each topic's representative docs with this approach? (I'm currently getting an empty dict).
Second, is there a way for me to get the topic probabilities? If not, perhaps I can incorporate river's predict_proba_one() on the CustomRiver class, but unsure how I would be able to do that and store the results as the model's probabilities, similar to how self.labels_ is stored as topics.
Third, why is river recommended to find new topics as they come in? I'm not very familiar with the package, so I'm unsure on what I'm supposed to do in order to identify the new topics/clusters after an update. Perhaps you can point me to some useful resources for my case?
Lastly, related to the last question, what is the advantage of using the river package approach vs the example with the regular partial_fit()? Is mostly for identifying new topics?

I realize my question is long so sorry about that. Would appreciate any insight or resources you believe might be useful for me.
Thank you!

**Comment by MaartenGr** [comment]
> Regarding creating new buckets, instead of merging topics, I am more interested in having a separate data structure that stores the topics which belong to a bucket. My question is, at each update of the model, will the existing topics change (for example, will topic 50 after training batch 1 still be topic 50 after batch 2?

From my understanding of how River works, yes, I believe that the initial assignment stays. But it might be worthwhile to dive into the River documentation to know that for sure. 

> First, is there a way for me to get each topic's representative docs with this approach? (I'm currently getting an empty dict).

At the moment there is no method as the representative docs might chance with each update. You could, however, calculate the c-TF-IDF representations of each input document and compare that with the topic c-TF-IDF representation.

> Second, is there a way for me to get the topic probabilities? If not, perhaps I can incorporate river's predict_proba_one() on the CustomRiver class, but unsure how I would be able to do that and store the results as the model's probabilities, similar to how self.labels_ is stored as topics.

You might be able to save them in the custom River class as a `self` variable and then access that variable after fitting the model. 

> Third, why is river recommended to find new topics as they come in? I'm not very familiar with the package, so I'm unsure on what I'm supposed to do in order to identify the new topics/clusters after an update. Perhaps you can point me to some useful resources for my case?

The reason for this is that there are not many clustering algorithms out there that have the capability to find new topics as they come in. Currently, I believe that the River package is one of the only, and most popular packages for doing so. 

> Lastly, related to the last question, what is the advantage of using the river package approach vs the example with the regular partial_fit()? Is mostly for identifying new topics?

Yes, River is an online machine learning package that aims to update the model as new entities come in and define them as such.
