### ISSUE TITLE
Problem with topic result 

### ISSUE THREAD

**Issue by wilhelmlofsten** [MaartenGr/BERTopic#1218]
Hello,

Me and my classmate are writing a thesis about media opinions of chatgpt and are trying to run BERTopic on the Instagram posts (only 580 posts)  and get only 2 topics (see picture below)
![image](https://user-images.githubusercontent.com/107505740/234913122-9977ab40-5edc-476c-b7a3-654cb703e2ee.png)

Is there a way to improve the result with the given code below? For the other platforms (Twitter and Facebook), we got good results with the topics (with around ~2500 and 1300 posts). Also, we noticed also that each Instagram post had a lot more text written in them (if somehow that is the reason?? ).

the code that was used:
```

import pandas as pd
import numpy as np

from umap import UMAP
from bertopic import BERTopic
import re


import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords


stop_words = stopwords.words('english') 

instagramOutput = pd.read_csv('statistics/april26/instagramPosts.csv')

#regex +stopwords
instagramOutput.text = instagramOutput.apply(lambda row: re.sub(r"http\S+", "", row.text).lower(), 1)
instagramOutput.text = instagramOutput.apply(lambda row: " ".join(filter(lambda x:x[0]!="@", row.text.split())), 1)
instagramOutput.text = instagramOutput.apply(lambda row: " ".join(re.sub("[^a-zA-Z]+", " ", row.text).split()), 1)
instagramOutput.text = instagramOutput.text.apply(lambda row: " ".join([word for word in row.split() if word not in stop_words]), 1)


timestamps = instagramOutput.created_at.to_list()
instaPosts= instagramOutput.text.to_list()

topic_model = BERTopic(embedding_model="paraphrase-MiniLM-L6-v2",verbose=True,calculate_probabilities=True)
topics, probs = topic_model.fit_transform(instaPosts)

```

Thanks in advance!

**Comment by MaartenGr** [comment]
The `min_topic_size` is the main parameter for you to tweak as it indirectly influences the number of topics that are created. The lower this value is, the more topics generally are created. If the value is set too high, it cannot find enough topics. In other words, setting that value a bit lower, like at `10` or even at `5` might help. 

Other than that, if you do not expect any outliers, then using a method like [k-Means](https://maartengr.github.io/BERTopic/getting_started/clustering/clustering.html#k-means) instead could be beneficial.

**Comment by wilhelmlofsten** [comment]
Hello Maarten,

Thank you very much for you answer! It was enough by decreasing the `min_topic_size` 👍
