### ISSUE TITLE
Empty topic representation for online topic modeling

### ISSUE THREAD

**Issue by florine-henriot** [MaartenGr/BERTopic#1222]
Hello Maarten!

I am trying to cluster articles with the online topic modeling method. I have separated my dataset by months, and I am doing a .partial_fit() on each month of my dataset. I am using IncrementalPCA, MiniBatchKMeans and Online Count Vectorizer. Once I have trained the model on all of my dataset, I noticed that I have some topics without any representation and no keywords, and I realized that it happens when I have no new documents added to a topic. For example, this is the topic representation I have for one partial fit : 

![image](https://user-images.githubusercontent.com/91048608/235094912-f2260545-c023-459b-ac38-fc8a6722eb64.png)

And then what I have for the next partial fit : 

![image](https://user-images.githubusercontent.com/91048608/235095075-e3bd91fe-6634-472f-91a6-f2575c78a9df.png)

I noticed that no new documents have been adeed to the topic 8, so I have no representation for the topic. And every time I get no topic representation is when no new documents is added to the topic. I tried to change the decay and min_df parameter, but I still get the same problem. I have not found anything to fix this issue. Do you know if there is a way to fix this ?

Thank you!

**Comment by MaartenGr** [comment]
That is strange indeed! Could you share your entire code? That will make it a bit easier to see what is happening here.

**Comment by florine-henriot** [comment]
Thank you for your quick answer!
Sure, here is the code for my BERTopic model : 
![image](https://user-images.githubusercontent.com/91048608/235112346-c08e7931-1b89-4f0a-95a4-6e579c9d7980.png)

And here is my code for the partial_fit method:
![image](https://user-images.githubusercontent.com/91048608/235113263-78670d8c-898a-4e2b-bca9-c6efe5c4a1d2.png)


I'm just writing a txt file at each iteration to see what is happening at each iteration.

**Comment by jburdo1** [comment]
Following on with this, I think there may be an issue with the decay argument in OnlineCountVectorizer. For my model when I remove that argument, the vectors are generated to completion. When I include decay=.01 (as florine has above), I get a "RuntimeWarning:verflow encountered in true_divide" along with numpy errors following on that seem to (maybe?) indicate a null or nan value within a vector.

**Comment by MaartenGr** [comment]
That is how the `decay` parameter works. It reduces the counts in the bag-of-word matrix with each iteration to make sure that newer information has more weight. It might be that the value of `.01` is simply too high for the frequency with which there is being trained. Either lowering the value further or simply not setting it should solve the issue.

**Comment by MaartenGr** [comment]
Just to be sure, the code is **exactly** as you mentioned in your previous message except for omitting the `decay` parameter? The rest is the same? 

If so, then it might be worthwhile to minimize the code that you currently have and try to create a minimal example. For example, perhaps the `nr_topics="auto"` is the culprit here. Omitting that might help. Same with `n_gram_range`, `top_n_words`, etc.

**Comment by florine-henriot** [comment]
Thanks for your answer. Yes, I am using exactly the same code as I mentioned before. I tried to test each parameter one by one, and I found out what is the problem, it's not because of the decay parameter I'm using, it's because I'm using the Part Of Speech representation model. I don't have this problem without it.

**Comment by MaartenGr** [comment]
Glad to hear that you resolved the issue! Most likely, there were not sufficient documents for each topic for the PartOfSpeech model to accurately extract the words in each partial fit.

**Comment by noahberhe** [comment]
Interesting... it looks like you shouldn't use any representation models for Online learning in that case, I had the same with KeyBert which is similarly remedied by removing.

**Comment by MaartenGr** [comment]
@noahberhe That is currently not possible but I do not think using it the first time during partial fit would be the solution here. I believe after having trained your model by passing all data through several partial fits, you can then use `update_topics` with any representation model to get better representations of your topics.
