### ISSUE TITLE
get_feature_names error

### ISSUE THREAD

**Issue by srilamaiti** [MaartenGr/BERTopic#1226]
I am trying to execute the below code from the documentation:-

from bertopic import BERTopic
from sklearn.datasets import fetch_20newsgroups

docs = fetch_20newsgroups(subset='all',  remove=('headers', 'footers', 'quotes'))['data']

topic_model = BERTopic()
topics, probs = topic_model.fit_transform(docs)

It's failing with the error "AttributeError: 'CountVectorizer' object has no attribute 'get_feature_names'"
Can you please help me here?

Thanks in advance
Srila

**Comment by MaartenGr** [comment]
I think you are using an older version of BERTopic. Making sure you have the newest version should solve your issue.

**Comment by srilamaiti** [comment]
Thanks for your reply. I tried installing bertopic version 0.14.1. Still, I am getting the same error. I am running my code in Google Colab. 
![image](https://user-images.githubusercontent.com/11797217/235236886-bd8bdb75-a72b-4e09-ad31-26f7f82c038f.png)

**Comment by srilamaiti** [comment]
After restarting the kernel, it seems to work now.

**Comment by srilamaiti** [comment]
After restarting the kernel, it seems to work now.
