### ISSUE TITLE
Ensemble Bertopic with other Topic Models

### ISSUE THREAD

**Issue by jmtrinidad6** [MaartenGr/BERTopic#1227]
Hello,

Curious question, how do you ensemble BERTopic with other Topic Models? Like NMF or Top2Vec? Any information or have you tried implementing it?

**Comment by MaartenGr** [comment]
That is currently not possible as it would require significant dependencies on other topic modeling frameworks and techniques. In a future release, however, it might be possible to ensemble (or combine) BERTopic models with the upcoming HuggingFace Hub [serialization updated](https://github.com/MaartenGr/BERTopic/pull/1205).
