### ISSUE TITLE
Keep punctuation in topic representations

### ISSUE THREAD

**Issue by 19Musa96** [MaartenGr/BERTopic#1228]
Hi guys, I noticed that Bertopic removes punctuation in the final topics representation. Is there a way I can make it keep the puntuation? (In this case, the punctuation is round brackets)

**Comment by MaartenGr** [comment]
Whether punctuation is removed depends on the settings for the [`CountVectorizer`](https://maartengr.github.io/BERTopic/getting_started/vectorizers/vectorizers.html#tokenizer) that you use. You can also find more information about it [here](https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html).

**Comment by 19Musa96** [comment]
Thanks Maarten!

**Comment by 19Musa96** [comment]
Hey Maarten, I tried changing the count vectorizer to this:

`
def my_tokenizer(text):
    return re.split("\\s+",text)
cv_ = CountVectorizer(preprocessor=None,tokenizer=my_tokenizer,stop_words=None,token_pattern=None,lowercase=False,ngram_range=(1,1))
`
But the topic outputs still remove punctuation. When I tried this outside of BERTopic, the count vectorizer doesn't remove the punctuation from the tokens, here is an example below:

`
import re
from sklearn.feature_extraction.text import CountVectorizer

def my_tokenizer(text):
    return re.split("\\s+",text)

cv_ = CountVectorizer(preprocessor=None,tokenizer=my_tokenizer,stop_words=None,token_pattern=None,lowercase=False,ngram_range=(1,1))


docs = ["A sentence with (some) punctuation", "A sentence with no punctuation"]

cv_.fit(docs)
print(cv_.vocabulary_)

output: 

{'A': 1, 'sentence': 4, 'with': 5, '(some)': 0, 'punctuation': 3, 'no': 2}
`

For context, I am trying to process some legal text and some statutes have parentheses which I would like to retain in the topic representations because Section 12(3) of Some Act is very different to Section 123 of Some Act.

**Comment by MaartenGr** [comment]
I believe you will have to set a custom embedding model, instead of leaving it to the `english` default as that will do some slight preprocessing. Instead, doing the following should help:

```python
from sentence_transformers import SentenceTransformer
sentence_model = SentenceTransformer("all-MiniLM-L6-v2")

topic_model = BERTopic(embedding_model=sentence_model, vectorizer_model=vectorizer_model)
```

**Comment by 19Musa96** [comment]
That worked! Thanks MaartenGr
