### ISSUE TITLE
python3.11 run quickstart , numba 0.59.0 deprecation decorator warning

### ISSUE THREAD

**Issue by desean** [MaartenGr/BERTopic#1231]
NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  @numba.jit()

**Comment by MaartenGr** [comment]
Thanks for sharing this. I believe it will be fixed in an [upcoming UMAP release](https://github.com/lmcinnes/umap/issues/1004).

**Comment by zhimin-z** [comment]
I have the same issue appearing

**Comment by zhimin-z** [comment]
Maybe we should refer to [this](https://github.com/numba/numba/issues/4908)
