### ISSUE TITLE
Intuition .fit() to .transform() - Large corpus

### ISSUE THREAD

**Issue by CarlArthur** [MaartenGr/BERTopic#1233]
Hi!

Thanks for a wonderful work on BERTopic and its applications!

As of now, I am implementing the model on a large corpus of approx. 10.000 documents that are divided in paragraphs of max length 384 words (a majority of them are a lot smaller, around 20-50). All in all, I hav approx. 2.6 million paragraphs that ought to be assigned to a relevant topic. Which is a bit computational heavy to manage. However, I figured that I should be able to fit the model on an arbitrary sample of ca. 100k paragraphs in order to obtain a set of topics. Which I have, using a downstream trained ESG model from HuggingFace with flair. 

The thing that I am wondering is how I can place new instances, from the rest of the corpus, in the "buckets" of topics that I have generated. And furthermore, how to scale the topic representations back to document level? With this, what is the intuition of fitting the model on a sample set of paragraphs and then transforming on the rest?

I have considered turning to online topic modeling or DocumentPooling with flair but I am a bit at lost here and hope that you Maarten or somebody else more familiar with this unsupervised modeling approach could assist with this matter.  

You are most welcome to ask if I have failed to capture the problem. 
Best wishes

**Comment by MaartenGr** [comment]
If you want to place unseen documents/sentences/paragraphs in the topics that were created, you will have to use `.transform` for that. Moreover, if you want to scale it back to the document level you could either simply count the number of times a topic appears in a full document or you can use [topic distributions](https://maartengr.github.io/BERTopic/getting_started/distribution/distribution.html) in BERTopic.
