### ISSUE TITLE
Visualization issues when using pycharm

### ISSUE THREAD

**Issue by aligagag** [MaartenGr/BERTopic#1239]
Hello, the author. When I use bertopic topic model for visualization, I use
 topic_ model.visualize_ Barchart (top_n_topics=10)
how to display and save an image when using pycharm

**Comment by MaartenGr** [comment]
I believe you can call `fig.show()` on the resulting figure to show it in pycharm.

**Comment by aligagag** [comment]
Thank you for your answer, it was very helpful
