### ISSUE TITLE
about sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2 model

### ISSUE THREAD

**Issue by yutiansh4** [MaartenGr/BERTopic#1242]
Hi MaartenGr，
The huggingface don't support this model, please recommend a different model

**Comment by MaartenGr** [comment]
This is a [known issue with HuggingFace](https://twitter.com/huggingface/status/1655760648926642178) at the moment. You can find more information about that [here](https://github.com/UKPLab/sentence-transformers/issues/1915). I would advise waiting until HuggingFace has restored those models. You could also see if you have any of the models cached and load them locally but I am quite sure HuggingFace is working hard on a fix seeing the large dependencies of OSS on sentence-transformers.

**Comment by MaartenGr** [comment]
It seems that the [models](https://huggingface.co/sentence-transformers) are [online](https://twitter.com/huggingface/status/1656004153162756100) again, so the issue should be resolved!

**Comment by yutiansh4** [comment]
The sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2 model is still offline.

> It seems that the [models](https://huggingface.co/sentence-transformers) are [online](https://twitter.com/huggingface/status/1656004153162756100) again, so the issue should be resolved!

**Comment by yutiansh4** [comment]
I just took a look at the huggingface, the model is online again.

**Comment by yutiansh4** [comment]
I just took a look at the huggingface, the model is online again.
