### ISSUE TITLE
Repository Not Found for url: https://huggingface.co/api/models/sentence-transformers/all-MiniLM-L6-v2.

### ISSUE THREAD

**Issue by arefeh-k** [MaartenGr/BERTopic#1243]
Hi,

I was working with BERTopic for months, but today it gets this error.

Repository Not Found for url: https://huggingface.co/api/models/sentence-transformers/all-MiniLM-L6-v2.

Could you please help how can I resolve the issue?

**Comment by MaartenGr** [comment]
This is a [known issue with HuggingFace](https://twitter.com/huggingface/status/1655760648926642178) at the moment. You can find more information about that [here](https://github.com/UKPLab/sentence-transformers/issues/1915). I would advise waiting until HuggingFace has restored those models. You could also see if you have any of the models cached and load them locally but I am quite sure HuggingFace is working hard on a fix seeing the large dependencies of OSS on sentence-transformers.

**Comment by MaartenGr** [comment]
It seems that the [models](https://huggingface.co/sentence-transformers) are [online](https://twitter.com/huggingface/status/1656004153162756100) again, so the issue should be resolved!
