### ISSUE TITLE
Repository Not Found for url: https://huggingface.co/api/models/sentence-transformers/distilbert-base-nli-mean-tokens.

### ISSUE THREAD

**Issue by ShathaAlghamdi2007** [MaartenGr/BERTopic#1244]
Hi everyone
I have this line of code and it was running perfectly until yesterday

`sentence_model = SentenceTransformer("distilbert-base-nli-mean-tokens")`

Now when I tried to run it the following error raised ..

```

RepositoryNotFoundError: 401 Client Error. (Request ID: Root=1-645a0801-003551080903725b044045e8)

Repository Not Found for url: https://huggingface.co/api/models/sentence-transformers/distilbert-base-nli-mean-tokens.
Please make sure you specified the correct `repo_id` and `repo_type`.
If you are trying to access a private or gated repo, make sure you are authenticated.
Invalid username or password.

```
Anyone can help please..

**Comment by MaartenGr** [comment]
This is a [known issue with HuggingFace](https://twitter.com/huggingface/status/1655760648926642178) at the moment. You can find more information about that [here](https://github.com/UKPLab/sentence-transformers/issues/1915). I would advise waiting until HuggingFace has restored those models. You could also see if you have any of the models cached and load them locally but I am quite sure HuggingFace is working hard on a fix seeing the large dependencies of OSS on sentence-transformers.

**Comment by ShathaAlghamdi2007** [comment]
Oh thanks 
We will be waiting and praying for them to fix it soon..

**Comment by MaartenGr** [comment]
It seems that the [models](https://huggingface.co/sentence-transformers) are [online](https://twitter.com/huggingface/status/1656004153162756100) again, so the issue should be resolved!

**Comment by ShathaAlghamdi2007** [comment]
yah, it works again ..
Thanks alot..
