### ISSUE TITLE
Can I have mapping document : topic with BERTopic?

### ISSUE THREAD

**Issue by breadfan** [MaartenGr/BERTopic#125]
Hi! I'm trying to make the model that maps topics to documents.
Can I do it with BERTopic? I.e.: I have ID for each document in my corpus, can I have a dictionary {ID of the document: topic of the document} with this model? And how can I do that? I only have now ```fit_transform``` method, which fits my data as a blackbox.

**Comment by MaartenGr** [comment]
Yes, after you have fitted the model with `fit`  you can use `transform` to predict the topics of new documents. Or you can use the `fit_transform`  function to do those steps at the same time. Consider, the following scenario where `docs` and `ids`  represent the documents and ids of those documents. 

```python
from bertopic import BERTopic
from sklearn.datasets import fetch_20newsgroups
 
topic_model = BERTopic()
topics, _ = topic_model.fit_transform(docs)
```

After having fitted the model and generated topics, we can simply map the resulting `topics`  to the ids of the documents:

```python
results = {id: topic for id, topic in zip(ids, topics)}
```

If you would rather have the description of the topic as value, use the following:

```python
results = {id: topic_model.get_topic(topic) for id, topic in zip(ids, topics)}
```

I would also like to refer you to the documentation [here](https://maartengr.github.io/BERTopic/) which contains many examples as well as tutorials you can find [here](https://github.com/MaartenGr/BERTopic#getting-started). Does this answer your question?
