### ISSUE TITLE
ModuleNotFoundError: No module named 'bertopic.dimensionality'

### ISSUE THREAD

**Issue by yhliu2022** [MaartenGr/BERTopic#1250]
Hi Maarten,

I am trying to run "from bertopic.dimensionality import BaseDimensionalityReduction" to set "empty_dimensionality_model = BaseDimensionalityReduction()", so that I can directly use my reduced embedding without run UMAP again.
However, I encounter the ModuleNotFoundError: No module named 'bertopic.dimensionality'.

I have pip install bertopic and the other embedding models. I am wondering if the module was removed or I should install other dependences.

Thank you in advance for your time and attention!

Best, Colin

**Comment by MaartenGr** [comment]
You typically get this error if you do not have the correct BERTopic version. Could you try out the latest version? Also, make sure to start from a completely fresh environment.
