### ISSUE TITLE
Term scores values in barchart graph

### ISSUE THREAD

**Issue by ShathaAlghamdi2007** [MaartenGr/BERTopic#1253]
Hi

I am a beginner in BERTopic and not sure if i got good results or there is a problem...
is it ok to have term scores less than 0.5 for all topics ???

<img width="123" alt="image" src="https://github.com/MaartenGr/BERTopic/assets/132994416/5a26e205-ecb1-4c86-a994-2b959923aae2">

<img width="128" alt="image" src="https://github.com/MaartenGr/BERTopic/assets/132994416/66761f46-05b5-4e9d-92fe-2157aab38da4">

**Comment by MaartenGr** [comment]
That's alright. BERTopic, and its underlying weighting algorithm c-TF-IDF, does not have set values for which you can judge the output. It is a relative measure and not an absolute measure.

**Comment by ShathaAlghamdi2007** [comment]
Thanks alot
