### ISSUE TITLE
Tokenizing the document

### ISSUE THREAD

**Issue by Keamww2021** [MaartenGr/BERTopic#1254]
Greeting Maarten & all,

As we know for topic modeling: we first prepare our documents and then train our topic model. We can pass the CountVectorizer before and after (to remove stop words and some irrelevant words) training our topic model, which helps generate an interpretable topic representation.
my question is about the documents, should I apply the tokenization step on them before training our model or keep them as raw data (only remove irrelevant characters)?

**Comment by MaartenGr** [comment]
> my question is about the documents, should I apply the tokenization step on them before training our model or keep them as raw data (only remove irrelevant characters)?

The tokenization step, namely `vectorizer_model`, is applied **after** clustering the documents and **before** creating the topic representations. As such, the input documents should generally be unpreprocessed as the tokenization, and processing of the documents, will be done within BERTopic.
