### ISSUE TITLE
Value Error when computing topics representation using MMR.

### ISSUE THREAD

**Issue by piotrcelinski** [MaartenGr/BERTopic#1259]
Hi, when computing representation using MaximalMarginalRelevance I got the ValueError as below. I enclose the traceback. The error occures everytime I try to use MMR.

2023-05-12 21:50:39,078 - BERTopic - Transformed documents to Embeddings
2023-05-12 21:54:19,894 - BERTopic - Reduced dimensionality
2023-05-12 21:54:33,166 - BERTopic - Clustered reduced embeddings
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ C:\Users\piotr\onedrive\PycharmProjects\tematy-bert-310\slupsk-ria-tass.py:148 in <module>       │
│                                                                                                  │
│   145 │   # my_topics.make_wordcloud_from_topic_model(basepath, base_full_path)                  │
│   146                                                                                            │
│   147 if __name__ =='__main__':                                                                  │
│ ❱ 148 │   main()                                                                                 │
│   149                                                                                            │
│                                                                                                  │
│ C:\Users\piotr\onedrive\PycharmProjects\tematy-bert-310\slupsk-ria-tass.py:141 in main           │
│                                                                                                  │
│   138 │   │   │   │   │   logger.info(f'CURRENT DATA: REPRMODEL: {repr_model}, SRC: {src}, LEM   │
│   139 │   │   │   │   │   filename = re.sub(r'\.', '_', src) + f'_{lemorig}'                     │
│   140 │   │   │   │   │   stopwords = Filters.stopwords_ru + ['новости', 'новость', 'риа', 'та   │
│ ❱ 141 │   │   │   │   │   make_topics(corp_by_src[src][lemorig], corp_by_src[src]['date'], sto   │
│   142 │   │   │   │   │   │   │   │   f'{basepath}{filename}')                                   │
│   143 │   # my_topics = Topics()                                                                 │
│   144 │   # my_topics.load_model(f'{basepath}Ria_ru_lemma_Base_outliers_reduced.model')          │
│                                                                                                  │
│ C:\Users\piotr\onedrive\PycharmProjects\tematy-bert-310\slupsk-ria-tass.py:101 in make_topics    │
│                                                                                                  │
│    98 │   │   │   │   │      outliers_reduction_strategy='embeddings'                            │
│    99 │   │   │   │   │      )                                                                   │
│   100 │   logger.info(f'Topics search')                                                          │
│ ❱ 101 │   my_topics.topics_from_corpus(f'{filename}')                                            │
│   102 │   logger.info('Reducing outliers')                                                       │
│   103 │   my_topics.reduce_outliers(f'{filename}')                                               │
│   104 │   logger.info('Reducing topics')                                                         │
│                                                                                                  │
│ C:\Users\piotr\OneDrive\python\pgc\nlp\topics.py:193 in topics_from_corpus                       │
│                                                                                                  │
│   190 │                                                                                          │
│   191 │   def topics_from_corpus(self, filename):                                                │
│   192 │   │   self.logger.info(f'Transforming corpus')                                           │
│ ❱ 193 │   │   self.topics, self.probs = self.topic_model.fit_transform(self.corpus)              │
│   194 │   │   self.generate_and_set_topic_labels()                                               │
│   195 │   │   self.save_model_and_topics(filename, 'initial')                                    │
│   196                                                                                            │
│                                                                                                  │
│ C:\Users\piotr\OneDrive\PycharmProjects\tematy-bert-310\lib\site-packages\bertopic\_bertopic.py: │
│ 366 in fit_transform                                                                             │
│                                                                                                  │
│    363 │   │   │   documents = self._sort_mappings_by_frequency(documents)                       │
│    364 │   │                                                                                     │
│    365 │   │   # Extract topics by calculating c-TF-IDF                                          │
│ ❱  366 │   │   self._extract_topics(documents)                                                   │
│    367 │   │                                                                                     │
│    368 │   │   # Reduce topics                                                                   │
│    369 │   │   if self.nr_topics:                                                                │
│                                                                                                  │
│ C:\Users\piotr\OneDrive\PycharmProjects\tematy-bert-310\lib\site-packages\bertopic\_bertopic.py: │
│ 2982 in _extract_topics                                                                          │
│                                                                                                  │
│   2979 │   │   documents_per_topic = documents.groupby(['Topic'], as_index=False).agg({'Documen  │
│   2980 │   │   self.c_tf_idf_, words = self._c_tf_idf(documents_per_topic)                       │
│   2981 │   │   self.topic_representations_ = self._extract_words_per_topic(words, documents)     │
│ ❱ 2982 │   │   self._create_topic_vectors()                                                      │
│   2983 │   │   self.topic_labels_ = {key: f"{key}_" + "_".join([word[0] for word in values[:4]]  │
│   2984 │   │   │   │   │   │   │     for key, values in                                          │
│   2985 │   │   │   │   │   │   │     self.topic_representations_.items()}                        │
│                                                                                                  │
│ C:\Users\piotr\OneDrive\PycharmProjects\tematy-bert-310\lib\site-packages\bertopic\_bertopic.py: │
│ 3094 in _create_topic_vectors                                                                    │
│                                                                                                  │
│   3091 │   │   │   │   word_importance = [val[1] for val in self.get_topic(topic)]               │
│   3092 │   │   │   │   if sum(word_importance) == 0:                                             │
│   3093 │   │   │   │   │   word_importance = [1 for _ in range(len(self.get_topic(topic)))]      │
│ ❱ 3094 │   │   │   │   topic_embedding = np.average(embeddings[i * n: n + (i * n)], weights=wor  │
│   3095 │   │   │   │   topic_embeddings.append(topic_embedding)                                  │
│   3096 │   │   │                                                                                 │
│   3097 │   │   │   self.topic_embeddings_ = topic_embeddings                                     │
│ <__array_function__ internals>:180 in average                                                    │
│                                                                                                  │
│ C:\Users\piotr\OneDrive\PycharmProjects\tematy-bert-310\lib\site-packages\numpy\lib\function_bas │
│ e.py:538 in average                                                                              │
│                                                                                                  │
│    535 │   │   │   │   raise TypeError(                                                          │
│    536 │   │   │   │   │   "1D weights expected when shapes of a and weights differ.")           │
│    537 │   │   │   if wgt.shape[0] != a.shape[axis]:                                             │
│ ❱  538 │   │   │   │   raise ValueError(                                                         │
│    539 │   │   │   │   │   "Length of weights not compatible with specified axis.")              │
│    540 │   │   │                                                                                 │
│    541 │   │   │   # setup wgt to broadcast along axis                                           │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ValueError: Length of weights not compatible with specified axis.

**Comment by MaartenGr** [comment]
Which version of BERTopic are you using? Also, could you provide your full code for getting this error?

**Comment by MaartenGr** [comment]
You did not send a file. Please share it in the comments and make sure to use python syntax in markdown such that python is shown clearly.

**Comment by piotrcelinski** [comment]
Here you are. I replied via email with attachment previously.
[pgc.zip](https://github.com/MaartenGr/BERTopic/files/11477871/pgc.zip)

**Comment by MaartenGr** [comment]
It is very difficult to say what exactly might be going wrong here. The code you shared seems to be an entire codebase and distilling that into a very minimal and reproducible example is quite the work. Did you make sure to set the `diversity` to a float higher than 0 and lower than 1? Also, I believe [this](https://github.com/MaartenGr/BERTopic/issues/1054) issue might be relevant.

NOTE: I deleted the .zip file you shared since it seems to contain sensitive data.

**Comment by piotrcelinski** [comment]
Thank you, it happened due to different values of top_n_words. Now it is OK.
Thank you for file deletion.
BERTopic is simply great!
