### ISSUE TITLE
[Feature Request] Modify dimensionality reduction function to support PaCMAP

### ISSUE THREAD

**Issue by sean-doody** [MaartenGr/BERTopic#1266]
Hey @MaartenGr ,

Awesome work with BERTopic! 

I was wondering if you are familiar with the PaCMAP algorithm and have any plans to incorporate it into BERTopic for dimensionality reduction? I know that BERTopic allows for the use of almost any dimensionality reduction technique, which is great. However, currently, the way that PaCMAP works, it can't follow the `.fit(...)` and `.transform(...)` schema used by BERTopic when fitting dimensionality reduction models. This is because the way that `.transform(...)` is handled by PaCMAP, [it treats the data being transformed as an entirely distinct dataset that will be projected onto a previously fit embedding space](https://github.com/YingfanWang/PaCMAP/blob/9771fb31503a94dad09de3966fe9d9d31e233a92/source/pacmap/pacmap.py#L949). In order to use PaCMAP, BERTopic would need to call `PaCMAP(...).fit_transform(embeddings)`. Or within BERTopic, `umap_embeddings = self.umap_model.fit_transform(embeddings)`.

PaCMAP has been show to have advantages over UMAP in terms of [preserving both local and global structure](https://jmlr.org/papers/volume22/20-1061/20-1061.pdf) and [being robust to pre-processing and less sensitive to parameter choices](https://www.nature.com/articles/s42003-022-03628-x). It'd be great to be able to use PaCMAP directly in BERTopic and experiment with its performance.

Thanks!

Sean D.

**Comment by sean-doody** [comment]
Thanks @MaartenGr : this is an elegant solution that appears to have worked! I'm going to try it on a full set of observations now. I appreciate your prompt response and help with this!

**Comment by MaartenGr** [comment]
Glad to hear that it worked. If you run into any issues, please let me know!

**Comment by sean-doody** [comment]
For what it's worth, after experimenting with `PaCMAP` on my dataset of several hundred thousand social media posts, I found `UMAP` to be (qualitatively) better. `PaCMAP` tends to result in `HDBSCAN` finding an implausibly small number of clusters across a variety of values of `min_cluster_size` and `min_samples`. However, at least in my case, `PaCMAP` did lead to `HDBSCAN` having only a tiny number of outliers whereas `UMAP` tends to result in more predicted noise. However, the clusters found by `PaCMAP` tended  to be too general (and there really _should_ be more noise than `PaCMAP` found). So I'll be sticking with `UMAP` after all.

But thanks for this solution nonetheless!

**Comment by MaartenGr** [comment]
Thanks for sharing this! It will definitely help out other users wanting to explore PaCMAP. Interesting though that PaCMAP actually creates so few outliers when you expected more. Definitely not an issue that you hear often, it is mostly the other way around.
