### ISSUE TITLE
Reduce_topics doesn't affect the outliers

### ISSUE THREAD

**Issue by lttatiana** [MaartenGr/BERTopic#1273]
Hello, I'm trying to use the method reduce_topics and before I updated the package to the latest version, it used to alter the -1 topic assignment. Now, in contrast, only the non-outlier topics change their values. The proportion of outliers, their exact assignments are kept constant. 

Moreover, the majority of topics are just falling into the 0 group now. As if all excessive topics just get merged to topic 0.

Could someone please help me resolve this issue? Thank you!

**Comment by MaartenGr** [comment]
In one of the last releases, the method was changed to make sure that the `-1` topics remain the same as otherwise they tend to get inflated quite a bit if we put regular topics into the outlier topic.

**Comment by lttatiana** [comment]
Got it, thank you very much!
