### ISSUE TITLE
Numba issue when importing cuML

### ISSUE THREAD

**Issue by noahberhe** [MaartenGr/BERTopic#1274]
Hi Maarten

I have python 3.8, and installed cuML:

```
!pip install cugraph-cu11 cudf-cu11 cuml-cu11 --extra-index-url=https://pypi.nvidia.com
!pip uninstall cupy-cuda115 -y
!pip uninstall cupy-cuda11x -y
!pip install cupy-cuda11x -f https://pip.cupy.dev/aarch64
```

When I then try to:
`from cuml.cluster import HDBSCAN`

I get this error:
`AttributeError: module 'numba._helperlib' has no attribute 'npymath_exports'`

What could be the issue?

**Comment by MaartenGr** [comment]
I would advise posting this in the [cuML repo](https://github.com/rapidsai/cuml/issues) as the issue you have seems to relate to that package and not necessarily BERTopic.
