### ISSUE TITLE
OSError: libcudart.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by noahberhe** [MaartenGr/BERTopic#1277]
Having already done:
```
!pip install cugraph-cu11 cudf-cu11 cuml-cu11 --extra-index-url=https://pypi.nvidia.com
!pip uninstall cupy-cuda115 -y
!pip uninstall cupy-cuda11x -y
!pip install cupy-cuda11x -f https://pip.cupy.dev/aarch64
```

When trying to:
`from cuml.cluster import HDBSCAN
`

I get:
`OSError: libcudart.so: cannot open shared object file: No such file or directory
`

**Comment by MaartenGr** [comment]
I would advise posting this in the [cuML repo](https://github.com/rapidsai/cuml/issues) as the issue you have seems to relate to that package and not necessarily BERTopic.

**Comment by noahberhe** [comment]
Have done, thank you!
