### ISSUE TITLE
The sum of the probabilities of the topics is not equal to 1

### ISSUE THREAD

**Issue by naokityokoyama** [MaartenGr/BERTopic#1278]
I'm doing topic modeling but when calculating the probability of each topic the sum is not equal to 1
below a simple example that I am applying

Version: 0.14.1
model = BERTopic(language='Portuguese', calculate_probabilities=True)
topics, prob = model.fit_transform(corpus)

The result showed 2 topics
set(topics)
{0, 1}

The sum of the probability is not equal to 1
Below the sum of the probabilities of the first line

prob[0]
array([0.01342076, 0.78132301])
the sum of this array is not 1

**Comment by MaartenGr** [comment]
That is correct. HDBSCAN does not generate probabilities for the `-1` class which is represented by 1 minus the sum of the probabilities.

**Comment by noahberhe** [comment]
Hi @MaartenGr,
So from your answer it seems that 1 = sum(probs) + implied probability of being an outlier.
Now for an example doc in my own dataset (which was assigned to one of 120 topics with a probability = 0.14), the sum of it's probability array = 0.6, which would imply a probability of it being an outlier of 0.4, which is > 0.14.

Is the algorithm first checking if the doc is an outlier or not, and as 0.4 < 0.5 then it assigns the doc to the most probable topic?

Thanks

**Comment by MaartenGr** [comment]
> So from your answer it seems that 1 = sum(probs) + implied probability of being an outlier.

That is generally what happens. It also depends on the underlying clustering model that you use. For more information about how they are calculated, I would advise looking at [this](https://hdbscan.readthedocs.io/en/latest/soft_clustering.html) and [this](https://hdbscan.readthedocs.io/en/latest/soft_clustering_explanation.html).
