### ISSUE TITLE
Online topic modeling, 'shape' elements cannot be negative

### ISSUE THREAD

**Issue by nfsedaghat** [MaartenGr/BERTopic#1281]
Hi,
I am going to use online topic modeling. 
In order to do this, I train the model using batches of documents in a for loop. Then, I save the model, and load it after getting some new documents to train it again using partial fit.
I get the below error while documents are not null for sure:

 ```
File "Online_BERTopic.py", line 284, in train_model
    topic_model.partial_fit(docs)
  File "/home/nafiseh/.local/lib/python3.8/site-packages/bertopic/_bertopic.py", line 576, in partial_fit
    self.c_tf_idf_, updated_words = self._c_tf_idf(documents_per_topic, partial_fit=True)
  File "/home/nafiseh/.local/lib/python3.8/site-packages/bertopic/_bertopic.py", line 3095, in _c_tf_idf
    X = self.vectorizer_model.partial_fit(documents).update_bow(documents)
  File "/home/nafiseh/.local/lib/python3.8/site-packages/bertopic/vectorizers/_online_cv.py", line 126, in update_bow
    rows = csr_matrix((X.shape[0] - self.X_.shape[0], self.X_.shape[1]), dtype=int)
  File "/home/nafiseh/.local/lib/python3.8/site-packages/scipy/sparse/_compressed.py", line 40, in __init__
    self._shape = check_shape(arg1)
  File "/home/nafiseh/.local/lib/python3.8/site-packages/scipy/sparse/_sputils.py", line 310, in check_shape
    raise ValueError("'shape' elements cannot be negative")
ValueError: 'shape' elements cannot be negative
```

This is my code if you are interested to see it:

```
bert_model = BERTopic.load(model_name, 
                  embedding_model=tensorflow_hub.load("https://tfhub.dev/google/universal-sentence-encoder/4"))
    chunkSize = 200
    doc_chunks = [df.loc[i: i + chunkSize-1, 'Description'] for i in range(0, len(df), chunkSize)]
    print('len(doc_chunks) : ', len(doc_chunks))
    topics = []
    ll = 0
    for docs in doc_chunks:
        ll += len(docs)
        print('size of docs: ', len(docs))
        topic_model.partial_fit(docs)
        print('Number of docs as input to the model: ', len(docs), '\n', 'Number of returned topics: ', len(topic_model.topics_), '\n \n')
        print('**********')
        topics.extend(topic_model.topics_)

    topic_model.topics_ = topics
```

Any suggestions to resolve the issue?

**Comment by MaartenGr** [comment]
Thanks for sharing and describing your issue. Could you perhaps reformat the error log and the code such that it is easier to read? Currently, I am having a hard time reading through the code as there isn't any spacing, the same with the error log.

**Comment by MaartenGr** [comment]
Hmm, not entirely sure what is happening. I do see that you load a saved model. Was that model trained before? If so, could you share how, including code?

**Comment by MaartenGr** [comment]
> Can it be because of doing topic reduction before saving the model?

Ah yes, that indeed might be the case. The `.partial_fit` works by focusing on the original topics and when reducing them, they get aggregated and in a way independent from the clustering algorithm. Instead, doing the `.reduce_topics` after all training has been finished might be best.

**Comment by MaartenGr** [comment]
I am not entirely sure whether that is the issue here. Those empty rows are necessary for the model to not throw any errors when creating the c-TF-IDF matrix as the number of topics, and thereby the topic assignment itself is different. I am not seeing why this specifically should procedure the shape error.

**Comment by MaartenGr** [comment]
Glad to hear that you found the issue! Also, thank you for sharing the solution.
