### ISSUE TITLE
Building wheel for hdbscan (pyproject.toml) did not run successfully.

### ISSUE THREAD

**Issue by BezawadaKalyan** [MaartenGr/BERTopic#1293]
Hi MaartenGR,
I tried to install bertopic on my laptop with python version 3.11. I am getting the below error.
Using python 3.11
jupyter notebook 5.5

Unable to install bertopic due to below error.
please help me to install bertopic in my laptop.
Note: hdbscan Installed manually. still it is unable to build the wheel for hdbscan.

Building wheels for collected packages: hdbscan
  Building wheel for hdbscan (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for hdbscan (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [40 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-311
      creating build\lib.win-amd64-cpython-311\hdbscan
      copying hdbscan\flat.py -> build\lib.win-amd64-cpython-311\hdbscan
      copying hdbscan\hdbscan_.py -> build\lib.win-amd64-cpython-311\hdbscan
      copying hdbscan\plots.py -> build\lib.win-amd64-cpython-311\hdbscan
      copying hdbscan\prediction.py -> build\lib.win-amd64-cpython-311\hdbscan
      copying hdbscan\robust_single_linkage_.py -> build\lib.win-amd64-cpython-311\hdbscan
      copying hdbscan\validity.py -> build\lib.win-amd64-cpython-311\hdbscan
      copying hdbscan\__init__.py -> build\lib.win-amd64-cpython-311\hdbscan
      creating build\lib.win-amd64-cpython-311\hdbscan\tests
      copying hdbscan\tests\test_flat.py -> build\lib.win-amd64-cpython-311\hdbscan\tests
      copying hdbscan\tests\test_hdbscan.py -> build\lib.win-amd64-cpython-311\hdbscan\tests
      copying hdbscan\tests\test_prediction_utils.py -> build\lib.win-amd64-cpython-311\hdbscan\tests
      copying hdbscan\tests\test_rsl.py -> build\lib.win-amd64-cpython-311\hdbscan\tests
      copying hdbscan\tests\__init__.py -> build\lib.win-amd64-cpython-311\hdbscan\tests
      running build_ext
      cythoning hdbscan/_hdbscan_tree.pyx to hdbscan\_hdbscan_tree.c
      C:\Users\bezasr7\AppData\Local\Temp\pip-build-env-y7oa9oju\overlay\Lib\site-packages\Cython\Compiler\Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: C:\Users\bezasr7\AppData\Local\Temp\pip-install-9777uco1\hdbscan_7598aa7e62bf47c4b7e213c1aa6d5a1c\hdbscan\_hdbscan_tree.pyx
        tree = Parsing.p_module(s, pxd, full_module_name)
      cythoning hdbscan/_hdbscan_linkage.pyx to hdbscan\_hdbscan_linkage.c
      C:\Users\bezasr7\AppData\Local\Temp\pip-build-env-y7oa9oju\overlay\Lib\site-packages\Cython\Compiler\Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: C:\Users\bezasr7\AppData\Local\Temp\pip-install-9777uco1\hdbscan_7598aa7e62bf47c4b7e213c1aa6d5a1c\hdbscan\_hdbscan_linkage.pyx
        tree = Parsing.p_module(s, pxd, full_module_name)
      cythoning hdbscan/_hdbscan_boruvka.pyx to hdbscan\_hdbscan_boruvka.c
      C:\Users\bezasr7\AppData\Local\Temp\pip-build-env-y7oa9oju\overlay\Lib\site-packages\Cython\Compiler\Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: C:\Users\bezasr7\AppData\Local\Temp\pip-install-9777uco1\hdbscan_7598aa7e62bf47c4b7e213c1aa6d5a1c\hdbscan\_hdbscan_boruvka.pyx
        tree = Parsing.p_module(s, pxd, full_module_name)
      cythoning hdbscan/_hdbscan_reachability.pyx to hdbscan\_hdbscan_reachability.c
      C:\Users\bezasr7\AppData\Local\Temp\pip-build-env-y7oa9oju\overlay\Lib\site-packages\Cython\Compiler\Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: C:\Users\bezasr7\AppData\Local\Temp\pip-install-9777uco1\hdbscan_7598aa7e62bf47c4b7e213c1aa6d5a1c\hdbscan\_hdbscan_reachability.pyx
        tree = Parsing.p_module(s, pxd, full_module_name)
      cythoning hdbscan/_prediction_utils.pyx to hdbscan\_prediction_utils.c
      C:\Users\bezasr7\AppData\Local\Temp\pip-build-env-y7oa9oju\overlay\Lib\site-packages\Cython\Compiler\Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: C:\Users\bezasr7\AppData\Local\Temp\pip-install-9777uco1\hdbscan_7598aa7e62bf47c4b7e213c1aa6d5a1c\hdbscan\_prediction_utils.pyx
        tree = Parsing.p_module(s, pxd, full_module_name)
      cythoning hdbscan/dist_metrics.pyx to hdbscan\dist_metrics.c
      C:\Users\bezasr7\AppData\Local\Temp\pip-build-env-y7oa9oju\overlay\Lib\site-packages\Cython\Compiler\Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: C:\Users\bezasr7\AppData\Local\Temp\pip-install-9777uco1\hdbscan_7598aa7e62bf47c4b7e213c1aa6d5a1c\hdbscan\dist_metrics.pxd
        tree = Parsing.p_module(s, pxd, full_module_name)
      building 'hdbscan._hdbscan_tree' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for hdbscan
Failed to build hdbscan
ERROR: Could not build wheels for hdbscan, which is required to install pyproject.toml-based projects

**Comment by MaartenGr** [comment]
It seems that although you have it installed, it cannot seem to find it. Perhaps adding it to your path might solve your issue. Also, I believe there are a number of [issues](https://github.com/scikit-learn-contrib/hdbscan/issues?q=is%3Aissue+is%3Aopen+wheels) on the HDBSCAN repo that go into this a bit more in-depth. Lastly, installing it through conda before installing BERTopic might also be a quick fix.
