### ISSUE TITLE
AttributeError: module 'numpy' has no attribute 'int', module 'numpy' has no attribute 'float' 

### ISSUE THREAD

**Issue by iamsanchitagrawal** [MaartenGr/BERTopic#1295]
pip install bertopic==0.11.0
pip install numpy==1.19.5

With these two versions, the following library calls are not getting executed:
from bertopic import BERTopic
from sklearn.feature_extraction.text import CountVectorizer
from hdbscan import HDBSCAN
from umap import UMAP

I am using databricks to perform topic modelling with BERT and encoutering the errors mentioned in the SUBJECT.

KINDLY HELP WITH THE COMPATIBLE VERSIONS in Azure Databricks

**Comment by iamsanchitagrawal** [comment]
I tried changing the versions in iterations to not get this error but still no help.
If you can suggest the versions of both BERTopic and numpy that are compatible, I will test that combination and update here

**Comment by MaartenGr** [comment]
I would advise starting from a completely fresh environment with no packages installed and then installing BERTopic without explicitly installing numpy first. That way, you should not have the issues you are referring to. It stems from an old version of numpy that is quite difficult to fix in the environment you are working in, so a new environment should resolve the issue.

**Comment by iamsanchitagrawal** [comment]
Warnings with a fresh environment

/local_disk0/.ephemeral_nfs/envs/pythonEnv-93e80842-d379-4382-98d4-c52182c44d63/lib/python3.8/site-packages/umap/distances.py:1063: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  @numba.jit()
  
/local_disk0/.ephemeral_nfs/envs/pythonEnv-93e80842-d379-4382-98d4-c52182c44d63/lib/python3.8/site-packages/umap/distances.py:1071: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  @numba.jit()
  
/local_disk0/.ephemeral_nfs/envs/pythonEnv-93e80842-d379-4382-98d4-c52182c44d63/lib/python3.8/site-packages/umap/distances.py:1086: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  @numba.jit()
  
/local_disk0/.ephemeral_nfs/envs/pythonEnv-93e80842-d379-4382-98d4-c52182c44d63/lib/python3.8/site-packages/umap/umap_.py:660: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  @numba.jit()

**Comment by MaartenGr** [comment]
That is related to https://github.com/lmcinnes/umap/issues/1004 but can safely be ignored for now.
