### ISSUE TITLE
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 80 from PyObject

### ISSUE THREAD

**Issue by iamsanchitagrawal** [MaartenGr/BERTopic#1296]
Changing the numpy version to any value except 1.19.5, the mentioned error in the subject was encountered for the following call:
from bertopic import BERTopic

Kindly help resolving the same

**Comment by MaartenGr** [comment]
Is this issue related to #1295? If so, which one is more recent and which one can we close?

**Comment by iamsanchitagrawal** [comment]
so, if I keep numpy constant at 1.95.0, and change BERTopic version, I see this error.
And if I keep Bertopic constant and change numpy versions, I see the Issue #1296

**Comment by MaartenGr** [comment]
Ah, then I will close this in favor of #1296.
