### ISSUE TITLE
AttributeError: 'list' object has no attribute 'topics_over_time'

### ISSUE THREAD

**Issue by feusagittaire** [MaartenGr/BERTopic#130]
Hi Marteen!

First I want to thank you for making such a good model!
Well, I'm experiencing this problem, that once I put the line `topics_over_time = topics.topics_over_time(tweets, topics, timestamps)` as you recommend in the documentation about visualization i get this error that says that list object has no attribute 'topics_over_time', which's at least odd since in the code we have to transform the df column into a list in order to pass it in the function, right?

I found an issue #66  that was opened about the same problem and you recommended installing the version 0.6 since the person had the 0.5. I installed the current version 0.8 and still it give me the error. There's something that I can do to overpass it?

Ty in advance!

The code that I'm using:

`import re
import pandas as pd
from bertopic import BERTopic
import dateutil

df = pd.read_csv('unico.csv', sep = ',', encoding = 'utf-8', engine = 'python')
df1 = df[['description', 'pubdate']]
df1['description'] = df1['description'].astype(str)
df1['description'] = df1['description'].apply(lambda description: preprocess_text(description))
df1['pubdate']=pd.to_datetime(df1["pubdate"]).dt.strftime("%Y-%m-%d")
timestamps = df1.pubdate.to_list()
tweets = df1.description.to_list()

# Create topics over time
topic_model = BERTopic(verbose=True,language= "portuguese", low_memory= True )
topics, _ = topic_model.fit_transform(tweets)
topics_over_time = topics.topics_over_time(tweets, topics, timestamps)`

**Comment by feusagittaire** [comment]
I found out that creating the variable in the same cell as the bertopic lead to the erro i'm not sure why. So I separeted them and it worked! I'm so sorry for opening the issue so precipitately!

**Comment by MaartenGr** [comment]
Don't worry, I am just glad it works for you! Just a quick note, I did notice that you used `topics.topics_over_time()` while it should be `topic_model.topics_over_time()`. It seems that you tried to extract topics over time from a list instead of extracting them from your BERTopic model.

**Comment by feusagittaire** [comment]
Oh my god, that was definetly my problem hahah
I'm so sorry! When i wrote another cell with the code, I corrected this without even knowing, that's propably why it worked!

Nonetheless, Maaten, I'm having a problem with twitter topic modeling analysis. The topics are generated with the same word but wrote diferently, as the singular and plural forms of a given word, or a verb and it's conjugated form put in the same or different clusters depending of course of the context. For example:

topic 1: vaccin, vaccines, to vaccin, vaccinated
topic 2: food, foods, to food, fooding, fed
you know?

This makes the topics somewhat noisy and repetitive. 

So, is there any way to pass the list of texts to a lemmatizer before/after puting the textual input into the model in order to lemmatize the words? I've found some solutions, but all of them tokenize the words, resulting in no desired input right? Since the whole idea is to let the tranformers tokenizer tokenize the texts based on context....

ty!

**Comment by MaartenGr** [comment]
Haha, that has definitely happened to me before! 

The difficulty here is that the words that represent the topic are actually the best for that topic. If you want more variety within a topic representation then that would lower the quality of the topic representation. Having said that, there might be some ways to prevent that from happening but it all depends on your code. 

Did you instantiate BERTopic as mentioned before like this? 

```python
topic_model = BERTopic(verbose=True, language= "portuguese", low_memory= True )
topics, _ = topic_model.fit_transform(tweets)
```

If so, then it might be worthwhile to check out different embedding models that can create better word/document representations as synonyms should typically be removed due to the MMR procedure. 

One other thing you can try is to adjust the MMR diversity parameter in BERTopic. This should result in more diverse topics but will reduce the quality of the topic representations, so it is typically not recommended:

```python
from bertopic import BERTopic
from bertopic._mmr import mmr


class NewBERTopic(BERTopic):
    def _extract_words_per_topic(self,
                                     words,
                                     c_tf_idf,
                                     labels):
            """ Based on tf_idf scores per topic, extract the top n words per topic
            If the top words per topic need to be extracted, then only the `words` parameter
            needs to be passed. If the top words per topic in a specific timestamp, then it
            is important to pass the timestamp-based c-TF-IDF matrix and its corresponding
            labels.
            Arguments:
                words: List of all words (sorted according to tf_idf matrix position)
                c_tf_idf: A c-TF-IDF matrix from which to calculate the top words
                labels: A list of topic labels
            Returns:
                topics: The top words per topic
            """
            if c_tf_idf is None:
                c_tf_idf = self.c_tf_idf.toarray()
            else:
                c_tf_idf = c_tf_idf.toarray()
    
            if labels is None:
                labels = sorted(list(self.topic_sizes.keys()))
    
            # Get top 30 words per topic based on c-TF-IDF score
            indices = c_tf_idf.argsort()[:, -30:]
            topics = {label: [(words[j], c_tf_idf[i][j])
                              for j in indices[i]][::-1]
                      for i, label in enumerate(labels)}
    
            # Extract word embeddings for the top 30 words per topic and compare it
            # with the topic embedding to keep only the words most similar to the topic embedding
            if self.embedding_model is not None:
    
                for topic, topic_words in topics.items():
                    words = [word[0] for word in topic_words]
                    word_embeddings = self._extract_embeddings(words,
                                                               method="word",
                                                               verbose=False)
                    topic_embedding = self._extract_embeddings(" ".join(words),
                                                               method="word",
                                                               verbose=False).reshape(1, -1)
    
                    topic_words = mmr(topic_embedding, word_embeddings, words,
                                      top_n=self.top_n_words, diversity=0)  # CHANGE DIVERSITY VALUE HERE 0-1
                    topics[topic] = [(word, value) for word, value in topics[topic] if word in topic_words]
    
            return topics
```

Then, simply run the model like this:

```python
topic_model = NewBERTopic(verbose=True, language= "portuguese", low_memory= True )
topics, _ = topic_model.fit_transform(tweets)
```

All in all, I would try different embedding techniques and see if that improves things, for example `"paraphrase-xlm-r-multilingual-v1"`.

**Comment by feusagittaire** [comment]
Maarten, Thank you so much for the time that you put into trying to help me solve my problem, you're the best! It actually worked just fine with your recommendations! I tried to use different embedding techniques and the one that you recommneded worked like charm!
