### ISSUE TITLE
visualize_barchart(n_words=10) shows the barchart with 10 bars but only shows 5 words instead of 10 

### ISSUE THREAD

**Issue by eneimdrop** [MaartenGr/BERTopic#1302]
Hi maarten, I'm trying to create visualizations for my paper using the visualize_barchart() method. But when i pass n_words = 10, the visualization only shows top 5 words instead of 10, when it correctly visualizes the 10 bars. Do you have any idea why this is happening ?
![newplot](https://github.com/MaartenGr/BERTopic/assets/98854246/b32a33eb-9b2c-468c-b098-8dd64c2caaf2)

**Comment by eneimdrop** [comment]
edit : don't pay attention to the previous plot, for some reason topic 1 is empty, here is the correct one :
![newplot (1)](https://github.com/MaartenGr/BERTopic/assets/98854246/c4e8ddd1-2b2d-4a86-82d2-8f7373d2df24)

**Comment by pratijayguha** [comment]
I had this issue too. One of the workarounds I found was to increase the figure height.

With default size:
![image](https://github.com/MaartenGr/BERTopic/assets/30014483/1678e723-00f8-4d66-9473-d09143d7f415)

With increased height:
![image](https://github.com/MaartenGr/BERTopic/assets/30014483/9955ef18-9dfb-41f7-bc10-6fc760d3500c)

**Comment by MaartenGr** [comment]
You can also zoom in (since it is an interactive plot) and it will also show the words.
