### ISSUE TITLE
A Problem on the Probability of Accurate Text Classification

### ISSUE THREAD

**Issue by aligagag** [MaartenGr/BERTopic#1304]
Hello author, may I know the probability of a certain document belonging to all categories of Bertopic's classification results? For example, if a document i is classified as Class 1, its probability of belonging to Class 1 is 0.9, and its probability of belonging to Class 2 is 0.4. Due to the highest probability of document i belonging to the first category, it belongs to category 1. How do I obtain the probability that it belongs to each category. May I ask if the author Bertopic activated classification through the above logic?

**Comment by MaartenGr** [comment]
You can get the probabilities from the `probs` variable or from `topic_model.probabilities_` if you set `calculate_probabilities=True` when instantiating the model.

**Comment by aligagag** [comment]
thanks very much
