### ISSUE TITLE
Problems with seed_topic_list

### ISSUE THREAD

**Issue by jiannan-xu** [MaartenGr/BERTopic#1309]
I recevied the following error message after running the code below:

"ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part."

Code:
```
from bertopic import BERTopic
from sklearn.datasets import fetch_20newsgroups

docs = fetch_20newsgroups(subset='train',  remove=('headers', 'footers', 'quotes'))["data"]

seed_topic_list = [["drug", "cancer", "drugs", "doctor"],
                   ["windows", "drive", "dos", "file"],
                   ["space", "launch", "orbit", "lunar"]]

topic_model = BERTopic(seed_topic_list=seed_topic_list)
topics, probs = topic_model.fit_transform(docs)
```

My dependent packages:
appnope @ file:///home/conda/feedstock_root/build_artifacts/appnope_1649077682618/work
asttokens @ file:///home/conda/feedstock_root/build_artifacts/asttokens_1670263926556/work
backcall @ file:///home/conda/feedstock_root/build_artifacts/backcall_1592338393461/work
backports.functools-lru-cache @ file:///home/conda/feedstock_root/build_artifacts/backports.functools_lru_cache_1618230623929/work
bertopic==0.15.0
certifi==2023.5.7
charset-normalizer==3.1.0
click==8.1.3
Cython==0.29.35
debugpy @ file:///Users/builder/miniconda3/envs/prefect/conda-bld/debugpy_1637092214173/work
decorator @ file:///home/conda/feedstock_root/build_artifacts/decorator_1641555617451/work
entrypoints @ file:///home/conda/feedstock_root/build_artifacts/entrypoints_1643888246732/work
executing @ file:///home/conda/feedstock_root/build_artifacts/executing_1667317341051/work
filelock==3.12.0
fsspec==2023.5.0
hdbscan==0.8.29
huggingface-hub==0.14.1
idna==3.4
importlib-metadata==6.6.0
ipykernel @ file:///Users/runner/miniforge3/conda-bld/ipykernel_1655369698656/work
ipython @ file:///private/var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_2bkl1d0l7u/croot/ipython_1680701883396/work
ipywidgets==8.0.6
jedi @ file:///home/conda/feedstock_root/build_artifacts/jedi_1669134318875/work
Jinja2==3.1.2
joblib==1.2.0
jupyter-client @ file:///home/conda/feedstock_root/build_artifacts/jupyter_client_1654730843242/work
jupyter_core @ file:///private/var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_d1sy1hlz9t/croot/jupyter_core_1679906585151/work
jupyterlab-widgets==3.0.7
llvmlite==0.40.0
MarkupSafe==2.1.2
matplotlib-inline @ file:///home/conda/feedstock_root/build_artifacts/matplotlib-inline_1660814786464/work
mpmath==1.3.0
nest-asyncio @ file:///home/conda/feedstock_root/build_artifacts/nest-asyncio_1664684991461/work
networkx==3.1
nltk==3.8.1
numba==0.57.0
numpy==1.24.3
packaging @ file:///home/conda/feedstock_root/build_artifacts/packaging_1681337016113/work
pandas==2.0.2
parso @ file:///home/conda/feedstock_root/build_artifacts/parso_1638334955874/work
pexpect @ file:///home/conda/feedstock_root/build_artifacts/pexpect_1667297516076/work
pickleshare @ file:///home/conda/feedstock_root/build_artifacts/pickleshare_1602536217715/work
Pillow==9.5.0
platformdirs @ file:///home/conda/feedstock_root/build_artifacts/platformdirs_1683850015520/work
plotly==5.14.1
prompt-toolkit @ file:///home/conda/feedstock_root/build_artifacts/prompt-toolkit_1677600924538/work
psutil @ file:///private/var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_1310b568-21f4-4cb0-b0e3-2f3d31e39728k9coaga5/croots/recipe/psutil_1656431280844/work
ptyprocess @ file:///home/conda/feedstock_root/build_artifacts/ptyprocess_1609419310487/work/dist/ptyprocess-0.7.0-py2.py3-none-any.whl
pure-eval @ file:///home/conda/feedstock_root/build_artifacts/pure_eval_1642875951954/work
Pygments @ file:///home/conda/feedstock_root/build_artifacts/pygments_1681904169130/work
pynndescent==0.5.10
python-dateutil @ file:///home/conda/feedstock_root/build_artifacts/python-dateutil_1626286286081/work
pytz==2023.3
PyYAML==6.0
pyzmq @ file:///private/var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_a7d9jpero7/croot/pyzmq_1682697648735/work
regex==2023.5.5
requests==2.31.0
scikit-learn==1.2.2
scipy==1.10.1
sentence-transformers==2.2.2
sentencepiece==0.1.99
six @ file:///home/conda/feedstock_root/build_artifacts/six_1620240208055/work
stack-data @ file:///home/conda/feedstock_root/build_artifacts/stack_data_1669632077133/work
sympy==1.12
tenacity==8.2.2
threadpoolctl==3.1.0
tokenizers==0.13.3
torch==2.0.1
torchvision==0.15.2
tornado @ file:///Users/runner/miniforge3/conda-bld/tornado_1625488911690/work
tqdm==4.65.0
traitlets @ file:///home/conda/feedstock_root/build_artifacts/traitlets_1675110562325/work
transformers==4.29.2
typing_extensions @ file:///home/conda/feedstock_root/build_artifacts/typing_extensions_1685045523825/work
tzdata==2023.3
umap-learn==0.5.3
urllib3==2.0.2
wcwidth @ file:///home/conda/feedstock_root/build_artifacts/wcwidth_1673864653149/work
widgetsnbextension==4.0.7
zipp==3.15.0

**Comment by MaartenGr** [comment]
Hm, I am not getting this issue with a new Kaggle environment. Could you share your full error log? That way, it is easier to see where the issue happens. Also, I used numpy 1.23.5, which might be worth trying out.

**Comment by jiannan-xu** [comment]
<img width="888" alt="Screenshot 2023-05-31 at 2 48 10 AM" src="https://github.com/MaartenGr/BERTopic/assets/114712392/1a9ead11-fa88-46a7-b33c-a09aec2401e3">

Thank you!

**Comment by that-alex13** [comment]
Hi,
I have the exact same issue. Tried your numpy version, but the issue persists. 

`Output exceeds the [size limit](command:workbench.action.openSettings?[). Open the full output data [in a text editor](command:workbench.action.openLargeOutput?2c14672b-2745-4714-8214-8d81be8f6ec0)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[252], line 1
----> 1 topics, probs = topic_model.fit_transform(texts)

File /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/bertopic/_bertopic.py:355, in BERTopic.fit_transform(self, documents, embeddings, y)
    353 # Reduce dimensionality
    354 if self.seed_topic_list is not None and self.embedding_model is not None:
--> 355     y, embeddings = self._guided_topic_modeling(embeddings)
    356 umap_embeddings = self._reduce_dimensionality(embeddings, y)
    358 # Cluster reduced embeddings

File /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/bertopic/_bertopic.py:2967, in BERTopic._guided_topic_modeling(self, embeddings)
   2965 for seed_topic in range(len(seed_topic_list)):
   2966     indices = [index for index, topic in enumerate(y) if topic == seed_topic]
-> 2967     embeddings[indices] = np.average([embeddings[indices], seed_topic_embeddings[seed_topic]], weights=[3, 1])
   2968 return y, embeddings

File <__array_function__ internals>:200, in average(*args, **kwargs)

File /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/numpy/lib/function_base.py:509, in average(a, axis, weights, returned, keepdims)
    396 @array_function_dispatch(_average_dispatcher)
    397 def average(a, axis=None, weights=None, returned=False, *,
    398             keepdims=np._NoValue):
    399     """
...
    511     if keepdims is np._NoValue:
    512         # Don't pass on the keepdims argument if one wasn't given.
    513         keepdims_kw = {}

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.`

**Comment by MaartenGr** [comment]
@that-alex13 Could you also share your BERTopic version, the versions of packages in your environment, and the code you used as was done above?

**Comment by MaartenGr** [comment]
Ah, it might be numba that causes the issue here. Perhaps using 0.56.4 or earlier fixes the issue.

**Comment by that-alex13** [comment]
This was the solution! Thank you so much @MaartenGr. 

Numba 0.56.4 solved it.

**Comment by MaartenGr** [comment]
Glad to hear that that fixed your issue! I have had issues with `np.average` in the past, so it might be worthwhile to check for an alternative to it that is still performant. For now, using Numba 0.56.4 would be the solution for other users.

**Comment by jiannan-xu** [comment]
Thank you! My problem was resolved!
