### ISSUE TITLE
error message 'KeyboardInterrupt' and others

### ISSUE THREAD

**Issue by bowenkhong** [MaartenGr/BERTopic#131]
Hi, I was following the quick guide and somehow i couldn't get the below work (I'm running on Jupyter):

docs = fetch_20newsgroups(subset='all',  remove=('headers', 'footers', 'quotes'))['data']
topic_model = BERTopic()
topics, _ = topic_model.fit_transform(docs)

**Error message**

---------------------------------------------------------------------------
KeyboardInterrupt                         Traceback (most recent call last)
<ipython-input-6-65762cef9a67> in <module>
      1 docs = fetch_20newsgroups(subset='all',  remove=('headers', 'footers', 'quotes'))['data']
      2 topic_model = BERTopic()
----> 3 topics, _ = topic_model.fit_transform(docs)

~/opt/anaconda3/lib/python3.8/site-packages/bertopic/_bertopic.py in fit_transform(self, documents, embeddings, y)
    266             self.embedding_model = select_backend(self.embedding_model,
    267                                                   language=self.language)
--> 268             embeddings = self._extract_embeddings(documents.Document,
    269                                                   method="document",
    270                                                   verbose=self.verbose)

~/opt/anaconda3/lib/python3.8/site-packages/bertopic/_bertopic.py in _extract_embeddings(self, documents, method, verbose)
   1233             embeddings = self.embedding_model.embed_words(documents, verbose)
   1234         elif method == "document":
-> 1235             embeddings = self.embedding_model.embed_documents(documents, verbose)
   1236         else:
   1237             raise ValueError("Wrong method for extracting document/word embeddings. "

~/opt/anaconda3/lib/python3.8/site-packages/bertopic/backend/_base.py in embed_documents(self, document, verbose)
     67             that each have an embeddings size of `m`
     68         """
---> 69         return self.embed(document, verbose)

~/opt/anaconda3/lib/python3.8/site-packages/bertopic/backend/_sentencetransformers.py in embed(self, documents, verbose)
     61             that each have an embeddings size of `m`
     62         """
---> 63         embeddings = self.embedding_model.encode(documents, show_progress_bar=verbose)
     64         return embeddings

~/opt/anaconda3/lib/python3.8/site-packages/sentence_transformers/SentenceTransformer.py in encode(self, sentences, batch_size, show_progress_bar, output_value, convert_to_numpy, convert_to_tensor, device, normalize_embeddings)
    188         for start_index in trange(0, len(sentences), batch_size, desc="Batches", disable=not show_progress_bar):
    189             sentences_batch = sentences_sorted[start_index:start_index+batch_size]
--> 190             features = self.tokenize(sentences_batch)
    191             features = batch_to_device(features, device)
    192 

~/opt/anaconda3/lib/python3.8/site-packages/sentence_transformers/SentenceTransformer.py in tokenize(self, text)
    340         Tokenizes the text
    341         """
--> 342         return self._first_module().tokenize(text)
    343 
    344     def get_sentence_features(self, *features):

~/opt/anaconda3/lib/python3.8/site-packages/sentence_transformers/models/Transformer.py in tokenize(self, texts)
     85 
     86 
---> 87         output.update(self.tokenizer(*to_tokenize, padding=True, truncation='longest_first', return_tensors="pt", max_length=self.max_seq_length))
     88         return output
     89 

~/opt/anaconda3/lib/python3.8/site-packages/transformers/tokenization_utils_base.py in __call__(self, text, text_pair, add_special_tokens, padding, truncation, max_length, stride, is_split_into_words, pad_to_multiple_of, return_tensors, return_token_type_ids, return_attention_mask, return_overflowing_tokens, return_special_tokens_mask, return_offsets_mapping, return_length, verbose, **kwargs)
   2286                 )
   2287             batch_text_or_text_pairs = list(zip(text, text_pair)) if text_pair is not None else text
-> 2288             return self.batch_encode_plus(
   2289                 batch_text_or_text_pairs=batch_text_or_text_pairs,
   2290                 add_special_tokens=add_special_tokens,

~/opt/anaconda3/lib/python3.8/site-packages/transformers/tokenization_utils_base.py in batch_encode_plus(self, batch_text_or_text_pairs, add_special_tokens, padding, truncation, max_length, stride, is_split_into_words, pad_to_multiple_of, return_tensors, return_token_type_ids, return_attention_mask, return_overflowing_tokens, return_special_tokens_mask, return_offsets_mapping, return_length, verbose, **kwargs)
   2471         )
   2472 
-> 2473         return self._batch_encode_plus(
   2474             batch_text_or_text_pairs=batch_text_or_text_pairs,
   2475             add_special_tokens=add_special_tokens,

~/opt/anaconda3/lib/python3.8/site-packages/transformers/tokenization_utils_fast.py in _batch_encode_plus(self, batch_text_or_text_pairs, add_special_tokens, padding_strategy, truncation_strategy, max_length, stride, is_split_into_words, pad_to_multiple_of, return_tensors, return_token_type_ids, return_attention_mask, return_overflowing_tokens, return_special_tokens_mask, return_offsets_mapping, return_length, verbose)
    383         )
    384 
--> 385         encodings = self._tokenizer.encode_batch(
    386             batch_text_or_text_pairs,
    387             add_special_tokens=add_special_tokens,

KeyboardInterrupt: `

**Comment by MaartenGr** [comment]
Typically, a `KeyboardInterrupt` will happen when the user forces the code to stop running by either pressing control-c or by forcing the kernel, if you are using a jupyter notebook, to stop running. Can you try it again, without stopping the code, and see what happens?

**Comment by bowenkhong** [comment]
Oh… actually it was running endlessly that I had to hit stop to see what happened.

**Comment by MaartenGr** [comment]
If I read the traceback correctly, then it seems it was stuck on extracting the embeddings. Did you use a GPU when running this code? The model runs significantly faster if you use a GPU. Without one, it can take much longer for the code to finish. 

Also, if you do use a GPU, could you set `verbose=True` and run the model again? This helps in identifying where the code might slow down.
