### ISSUE TITLE
Issue with reduce_outliers

### ISSUE THREAD

**Issue by Manuel445** [MaartenGr/BERTopic#1310]
The reduce_outliers function throws an exception if the documents are a dataframe with a not reset index. 

outlier_ids = [index for index, topic in enumerate(topics) if topic == -1]            #This return index 0, 1, 2, 3 for each element in topics
outlier_docs = [documents[index] for index in outlier_ids]                                  #This line throws an exception if there is no element for 
                                                                                                                              #indices that are not in documents
                                                                                                                              
Throws an error for a dataframe and topics that looks like this:
data = {
    'Items': [
        'value1',
        'value2',
        'value3',
        'value4',
        'value5'
    ]
}
df = pd.DataFrame(data, index=[0, 8, 11, 14, 17])
topics = [-1, -1, 1, 1, 2]

**Comment by MaartenGr** [comment]
If I remember correctly, the `documents` parameter in `.reduce_outliers` is typed as a list of strings, so anything else is currently not directly supported unless it is an iterable that does indexation the same way as a list.
