### ISSUE TITLE
find_topics() not working with a loaded model

### ISSUE THREAD

**Issue by ericchagnon15** [MaartenGr/BERTopic#1323]
I am running BERTopic with the following usage
```python
topic_model = BERTopic(embedding_model = model, verbose = True)
topic_model.fit_transform(docs)
topics, similarity = topic_model.find_topics("search term", top_n=5)
```
and this works as intended, returning the topics and their cosine similarities.

But when i have the following usage:
```python
topic_model = BERTopic(embedding_model = model, verbose = True)
topic_model.fit_transform(springer_clean_docs)

topic_model.save("test_model", serialization="safetensors", save_ctfidf=True)

topic_model = BERTopic.load("test_model")

topics, similarity = topic_model.find_topics("search term", top_n=5)
```

I get the following error:

  File "/home/username/miniconda3/envs/benchmarking/lib/python3.8/site-packages/bertopic/_bertopic.py", line 1287, in find_topics
    search_embedding = self._extract_embeddings([search_term],
AttributeError: 'NoneType' object has no attribute 'flatten'

I am using the most up to date version of BERTopic 0.15

I tried setting the embedding model attribute on the saved model and that did not work either.

**Comment by MaartenGr** [comment]
Only a pointer to the embedding model on HuggingFace will be saved if `embedding_model` is a string. If that is not the case but a model itself is passed to `embedding_model` then it cannot be saved. Instead, you will have to either manually assign the embedding model when running [`.save`](https://maartengr.github.io/BERTopic/getting_started/serialization/serialization.html#saving) or define it when using [`.load`](https://maartengr.github.io/BERTopic/getting_started/serialization/serialization.html#loading). In other words, the [documentation about serialization](https://maartengr.github.io/BERTopic/getting_started/serialization/serialization.html) should help you out.

**Comment by ericchagnon15** [comment]
Thanks for the quick response! This did the trick, I missed this page when I was looking through the documentation
