### ISSUE TITLE
Dynamic Topic modelling - reducing number of bins for visualisation

### ISSUE THREAD

**Issue by SallyBean** [MaartenGr/BERTopic#1327]
Hi Maarten, 

I love BERTopic it's really useful....I just want to say a big thank you for all of your work on this. 

I am having an issue, I have data containing 3 time stamps and I want the visualisation to only show these 3 time stamps, however this is not the case it's currently giving me 8.  Dates are currently in this format: 01/02/2021, do you know where I'm going wrong?

![image](https://github.com/MaartenGr/BERTopic/assets/22819773/cc151ee3-b05d-41fc-aa00-7d7a755047e2)

**Comment by MaartenGr** [comment]
Strange, it should generate 3 bins when you specifically set `nr_bins`. Could you show the output? As in, can you show that `topics_over_time` has 8 timestamps?

**Comment by MaartenGr** [comment]
Thanks, but the x-axis does not necessarily mean that there are 8 timestamps. They merely show the dates between two extremes. Could you check the variable, `topics_over_time` instead?

**Comment by SallyBean** [comment]
I see, thank you.  it seems likely that there are 3 bins looking at my code and from what you say. Is there a way to get the visualisation to present the 3 bins only?

**Comment by MaartenGr** [comment]
@SallyBean I think you would have to adjust the axes yourself using plotly in order to show only the 3 bins.

**Comment by SallyBean** [comment]
Thanks @MaartenGr I'm not familiar with Plotly, do you know how I would go about doing this?

**Comment by MaartenGr** [comment]
You can find more about formatting ticks [here](https://plotly.com/python/tick-formatting/).
