### ISSUE TITLE
How to view all documents of per topic?

### ISSUE THREAD

**Issue by sunlight1230** [MaartenGr/BERTopic#1328]
I need to know the contents in the topic. And there is an error" 'BERTopic' object has no attribute 'get_document_info'".

**Comment by MaartenGr** [comment]
Did you make sure you have the newest version of BERTopic?

**Comment by sunlight1230** [comment]
My version of BERTopic is 0.12.0.  The newest version is not compatible with some packages, causing some errors which I can't solve. Does this method 'get_document_info' allow me to see the document in the topic? If so，which version should I install?
Thank you for your reply.

**Comment by MaartenGr** [comment]
It is generally advised to install the latest version of BERTopic (0.15). `.get_document_info` is merely a wrapper to see the documents in a topic. You can also do that yourself by accessing `topics` since those are in the same order as the document.

**Comment by sunlight1230** [comment]
I have installed the version 0.15 successfully, thank you very much!
