### ISSUE TITLE
Results after outliers reduction

### ISSUE THREAD

**Issue by piotrcelinski** [MaartenGr/BERTopic#1329]
Hi,
As you adviced, after outliers reduction I did:
`self.topic_model.update_topics(self.corpus, topics=self.new_topics)`
as a last step of my workflow. I realized that topic descriptions after updating topics contain stopwords. The KKeyBERT, MMR nad POS descriptions did not change. I tried to:
`self.topic_model.generate_topic_labels`
but the results was the same. Please see attached:
ria_ru_keybert_mmr_pos_orig_outliers_reduced_embeddings.xlsx
[ria_ru_keybert_mmr_pos_orig_outliers_reduced_embeddings.xlsx](https://github.com/MaartenGr/BERTopic/files/11709212/ria_ru_keybert_mmr_pos_orig_outliers_reduced_embeddings.xlsx)
Where should I set stopwords list  for outliers reduction?

**Comment by MaartenGr** [comment]
You did not set the `representation_model` parameter of `.update_topics`. It should be exactly the same as the representation_model that you used to instantiate the model. The docstrings of `.update_topics` should give some more information. 

In other words, when you use `.update_topics` you describe every single step you want for the topic representations as it overwrites the representation model back to the default.

**Comment by piotrcelinski** [comment]
Thank you.
