### ISSUE TITLE
Expected type 'Optional[UMAP]', got 'BaseDimensionalityReduction' instead

### ISSUE THREAD

**Issue by hemantvikani** [MaartenGr/BERTopic#1333]
Getting warning when i pass UMAP model  = BaseDimensionalityReduction() , i want to bypass umap, but it gives a warning while i pass this parameter instead of umap. Attaching screenshot.

Using Bertopic 0.15.0, and tried with 0.13.0 also
<img width="589" alt="warning1" src="https://github.com/MaartenGr/BERTopic/assets/40485500/8b254e0f-bb73-4c6c-a539-38cd138169d9">

**Comment by MaartenGr** [comment]
That should be no problem. It might just be an old type-hint that should be updated but passing an empty dimensionality reduction model is definitely supported.

**Comment by hemantvikani** [comment]
Yeah its supported and working fine, just to get rid of warnings its good to be updated. Thanks @MaartenGr

**Comment by MaartenGr** [comment]
If you or anyone else has time, a PR would be appreciated. Otherwise, I'll put it on the list for later.

**Comment by hemantvikani** [comment]
Sure, i will create a PR tomorrow. Thanks
