### ISSUE TITLE
ImportError: background_gradient requires matplotlib.

### ISSUE THREAD

**Issue by JohannesNutz** [MaartenGr/BERTopic#1338]
Hello Marten, 

I am trying to run this code: 

# Calculate the topic distributions on a token-level
topic_distr, topic_token_distr = topic_model.approximate_distribution(filtered_docs, calculate_tokens=True)

# Visualize the token-level distributions
df = topic_model.visualize_approximate_distribution(filtered_docs[1], topic_token_distr[1])
df

While trying to run it I get a ImportError: background_gradient requires matplotlib.

I checked and matplotlib is installed in the environment I'm trying to run the code. 
Any ideas?

Best regards

**Comment by MaartenGr** [comment]
That error is new to me. Have you tried restarting the notebook or starting from a fresh environment?

**Comment by JohannesNutz** [comment]
Restarting worked, thanks.
