### ISSUE TITLE
Extracting c_tf_idf_ for each timestamp in topics_over_time

### ISSUE THREAD

**Issue by raefkazi** [MaartenGr/BERTopic#1340]
Hi Maarten,

For my use case, I am trying to find the terms contributing the most to the topic representations at each timestamp, created using the topics_over_time() method. I figured that creating a topic-term matrix using the c-tf-idf values as the similarity measure is the way to go (this works fine for the global representation). However, I also want the topic-term matrix for each timestamp.
Is there a way to extract this matrix for each timestamp after fitting the topics_over_time (since the topics_over_time method does not necessarily return the c-tf-idf matrix)?

**Comment by MaartenGr** [comment]
That is not directly possible at the moment since saving many c-TF-IDF matrices could lead to memory errors. However, you could adjust the `topics_over_time` function such that it saves the local c-TF-IDF matrices and returns those.
