### ISSUE TITLE
Error with custom labels

### ISSUE THREAD

**Issue by wongkh33** [MaartenGr/BERTopic#1352]
Hello, I've tried to assign custom labels to a model after outlier reduction using a dictionary where the keys are the topic IDs and its keys the topic labels with .set_topic_labels. However, the last topic's custom label is always NaN, regardless of whether a custom topic label was passed through the dictionary or not. This prevents me from using custom labels in visualisation as well, with the error message: "IndexError: list index out of range". Appreciate if you can advise on whether there is a workaround for this? I am using bertopic version 0.15.0. thank you.

**Comment by MaartenGr** [comment]
Could you share your full code? It's difficult to day what is happening without it. Also, how many topics are you left with after topic reduction? Is the -1 topic still included?

**Comment by wongkh33** [comment]
The initial run had 10 topics and a -1 outlier. After the outlier reduction step, the -1 topic was removed and I have 10 topics left. 

The code is here:

# creating sentence embeddings
embedding_model = SentenceTransformer("all-MiniLM-L6-v2")

# TFIDF for vectorising and CountVectorizer for removing stopwords
ctfidf_model = ClassTfidfTransformer(reduce_frequent_words=True)
vectorizer_model = CountVectorizer(stop_words="english")

# UMAP for dimensionality reduction and to ensure reproducible results with a random seed
umap_model = UMAP(n_neighbors=15,
                  n_components=5,
                  metric='cosine', 
                  random_state=42)

# HDBSCAN for clustering data and reducing outliers
hdbscan_model = HDBSCAN(min_cluster_size=10, 
                        metric='euclidean', 
                        cluster_selection_method='eom', 
                        prediction_data=True)

# Step 6 - (Optional) Fine-tune topic representations 
from bertopic.representation import MaximalMarginalRelevance
representation_model = MaximalMarginalRelevance(diversity=0.5)

# Fitting the model
topic_model = BERTopic(embedding_model=embedding_model,
                       umap_model=umap_model,
                       hdbscan_model=hdbscan_model,
                       vectorizer_model=vectorizer_model,
                       ctfidf_model=ctfidf_model,
                       top_n_words=10,
                       n_gram_range=(1,3),
                       #seed_topic_list=seed_topic_list,
                       representation_model=representation_model,
                       min_topic_size=20,
                       calculate_probabilities=True
                      )
topics, probs = topic_model.fit_transform(usa_text)

# Attempt to reduce outliers 
new_topics = topic_model.reduce_outliers(usa_text, topics, strategy="c-tf-idf")

# Update the model with the latest topic assignment 
topic_model.update_topics(usa_text, topics=new_topics, vectorizer_model=vectorizer_model)

# Getting the representative documents
topic_model.get_topic_info()

# Reviewing the labels and associated words
topic_labels = topic_model.generate_topic_labels(nr_words=10,
                                                 topic_prefix=True,
                                                 word_length=20,
                                                 separator=", ")

# Creating custom labels
topic_model.set_topic_labels(
    {
    0 : '0: xx',
    1 : "1: yy",
    2 : "2: ww",
    3 : "3: qq",
    4 : "4: tt",
    5 : "5: vv"
    6 : "5: hh"
    7 : "5: jj"
    8 : "5: kk"
    9 : "5: mm"
    })
    
Under the new 'Custom Label' column, the value for the last topic is always NaN.. had expected it to show the original topic name or the assigned custom label instead.

**Comment by MaartenGr** [comment]
Right before you run `topic_model.set_topic_labels(...` could you run the following:

```python
topic_model._outliers = 0


# Reviewing the labels and associated words
topic_labels = topic_model.generate_topic_labels(nr_words=10,
                                                 topic_prefix=True,
                                                 word_length=20,
                                                 separator=", ")

# Creating custom labels
topic_model.set_topic_labels(topic_labels)
```

I believe that might solve your issue.
