### ISSUE TITLE
Streamlining the pipeline

### ISSUE THREAD

**Issue by jpcompartir** [MaartenGr/BERTopic#1354]
Hi Maarten & collaborators,

First, thank you so much for the fantastic work you do on this library, it's very much appreciated.

My issue: I'm looking at ways to optimise/speed up the pipeline, I've followed the docs and have noticed that we can pre-compute embeddings and reduce them to cut down on processing time. However, we can't feed in pre-computed clusters without modifying the fit()/fit_transform() methods, from what I could see.

I was wondering if there is a specific reason for this, as hdbscan in particular can be quite costly (even on dimensionality reduced embeddings - especially for Apple silicon users). Is the idea that a user happy with the clusters, but looking to tune something else like the representation, or the vectoriser, should just use the update_topics function rather than run the full pipeline again, or is there another reason why it wouldn't make sense to implement this?

I was thinking I'd locally edit the _bertopic.py script to allow for pre-computed clusters, but wouldn't want to if it doesn't make sense to do so. 

Thanks again for the work you do!

**Comment by MaartenGr** [comment]
> However, we can't feed in pre-computed clusters without modifying the fit()/fit_transform() methods, from what I could see.

You can! You can actually already feed the model with pre-computed clusters which is called [manual BERTopic](https://maartengr.github.io/BERTopic/getting_started/manual/manual.html). This should speed up the representation of clusters quite a bit. 

With respect to `.update_topics`, that functionality was indeed created to prevent running the entire pipeline and quickly try out different representations. For that reason, you could also use [multi-aspect topic modeling](https://maartengr.github.io/BERTopic/getting_started/multiaspect/multiaspect.html) if you want to model several representations side-by-side.

**Comment by jpcompartir** [comment]
Ooo, excellent - that's exactly what I wanted to do! Thanks. I must've skipped the manual topic modelling section as it didn't seem like what I was looking for - my bad!

Minor suggestion - may be worth adding 'pre-compute clusters' to the tips & tricks to go with 'pre-compute embeddings', or 'skip clustering' as a similar section to 'skip dimensionality reduction' in the sub-model documentation? 

That said, I must add the documentation really is excellent

**Comment by MaartenGr** [comment]
Thanks! I'll definitely take that into account 😄

**Comment by jpcompartir** [comment]
Cool, will close up this issue!

Thanks for the speedy replies & once more for the awesome work you do.
