### ISSUE TITLE
reduce_outliers cancels the representation_model

### ISSUE THREAD

**Issue by RamyTheEngineer** [MaartenGr/BERTopic#1357]
Hello Maarten,

I have been experimenting with topics reduction and outliers reduction when clustering using HDBSCAN. 
I also used Cohere for representation.
```python
hdbscan_model = HDBSCAN(min_cluster_size=20, metric='euclidean', cluster_selection_method='eom', prediction_data=True)
vectorizer_model = OnlineCountVectorizer(stop_words="english")
ctfidf_model = ClassTfidfTransformer(reduce_frequent_words=True, bm25_weighting=True)
umap_model = UMAP(n_neighbors=70, n_components=5, min_dist=0.0, metric='cosine', random_state=42)
co = cohere.Client('------------------------------')
representation_model = Cohere(co,delay_in_seconds=10)
topic_model=BERTopic(embedding_model = 'all-MiniLM-L6-v2',
                       umap_model = umap_model,
                       hdbscan_model = hdbscan_model, 
                       vectorizer_model = vectorizer_model, 
                       ctfidf_model = ctfidf_model,
                       n_gram_range=(3, 4),
                       representation_model=representation_model)
```
Whenever I apply these lines of code, which reduces the outliers: 
```python
new_topics = topic_model.reduce_outliers(docs_train['Document'], topics, strategy="distributions")
topic_model.update_topics(docs_train['Document'], topics=new_topics)
topic_model.get_topic_info()
```
All representation is gone. 
Is there any way to apply Cohere, or more generally the representation model after fit_transform() is executed?

**Comment by MaartenGr** [comment]
Yes, if you check the parameters of `.update_topics` you will notice that you can supply it with arguments very similar when initializing your topic model. This means that when you use `.update_topics` and you want to keep the same sort of representations, you will need to set the exact same parameters. In this case, using `ctfidf_model`, `vectorizer_model`, and `representation_model`. In other words, you should do this instead:

```python
topic_model.update_topics(
    docs_train['Document'], 
    topics=new_topics, 
    vectorizer_model=vectorizer_model, 
    ctfidf_model=ctfidf_model,
    representation_model=representation_model)
```

Note that you can find more about updating topics in the [documentation](https://maartengr.github.io/BERTopic/getting_started/topicrepresentation/topicrepresentation.html).

**Comment by jburdo1** [comment]
> Yes, if you check the parameters of `.update_topics` you will notice that you can supply it with arguments very similar when initializing your topic model. This means that when you use `.update_topics` and you want to keep the same sort of representations, you will need to set the exact same parameters. In this case, using `ctfidf_model`, `vectorizer_model`, and `representation_model`. <

Hi Maarten, I'm having a similar issue with the re-inclusion of stop words after using reduce.outliers. When I call .update_topics and try to include vectorizer_model as an argument, I get an 'unexpected keyword argument' error (I also get the same error when trying to include ctfidf_model): 

`# Reduce outliers in original model using the `probabilities` strategy

vectorizer_model = CountVectorizer(stop_words="english")
ctfidf_model = ClassTfidfTransformer(reduce_frequent_words=True)

new_topics = topic_model.reduce_outliers(df_list, topics, vectorizer_model = vectorizer_model, probabilities=probs, strategy="probabilities")
topic_model.update_topics(df_list, topics=new_topics)`

Produces the error: 

TypeError                                 Traceback (most recent call last)
[<ipython-input-55-44ec8f7eb003>](https://localhost:8080/#) in <cell line: 6>()
      4 ctfidf_model = ClassTfidfTransformer(reduce_frequent_words=True)
      5 
----> 6 new_topics = topic_model.reduce_outliers(df_list, topics, vectorizer_model = vectorizer_model, probabilities=probs, strategy="probabilities")
      7 topic_model.update_topics(df_list, topics=new_topics)

TypeError: BERTopic.reduce_outliers() got an unexpected keyword argument 'vectorizer_model'
