### ISSUE TITLE
typing error in hierarchical_topics

### ISSUE THREAD

**Issue by dschwalm** [MaartenGr/BERTopic#1359]
I think type of docs should be List[str] and not List[int] in hierarchical_topics:

def hierarchical_topics(self,
                            docs: List[**int**],
                            linkage_function: Callable[[csr_matrix], np.ndarray] = None,
                            distance_function: Callable[[csr_matrix], csr_matrix] = None) -> pd.DataFrame:

**Comment by MaartenGr** [comment]
You are correct, I indeed believe that should be str and not int. For those interested, a PR would be appreciated!
