### ISSUE TITLE
Error related to go.Figure when importing BERTopic

### ISSUE THREAD

**Issue by tvinner** [MaartenGr/BERTopic#1360]
Hello,

I have installed BERTopic using pip. In a Spyder environment, I run the following: 

from bertopic import BERTopic

and get an error> 

  File "C:\Anaconda3\Lib\site-packages\bertopic\plotting\_topics.py", line 17, in <module>
    height: int = 650) -> go.Figure:

AttributeError: module 'plotly.graph_objects' has no attribute 'Figure'

I have tried re-installing BERTopic, plotly, plotly.express etc.

**Comment by MaartenGr** [comment]
It seems that is something going on with your environment. Instead of re-installing, I would advise starting from a completely fresh environment and installing BERTopic there.
