### ISSUE TITLE
Way to treat outlier as one single topic

### ISSUE THREAD

**Issue by dlrudgnsdlek** [MaartenGr/BERTopic#1363]
![image](https://github.com/MaartenGr/BERTopic/assets/76735881/bb72ddc9-a53e-452a-a55a-a93cc9d7fa8e)

I want to explore the topic with the keyword 'autoclave', 'hydrothermal' in detail. I'm curious about how the outliers can be grouped together as a single topic instead of being treated as outliers.

**Comment by dlrudgnsdlek** [comment]
Also, how can i get get_topic_info() with the result of new_topics (Result of reduce_outliers)?

**Comment by MaartenGr** [comment]
> Also, how can i get get_topic_info() with the result of new_topics (Result of reduce_outliers)?

You will need to update the model with `.update_topics`  as is described [here](https://maartengr.github.io/BERTopic/getting_started/outlier_reduction/outlier_reduction.html#update-topics). 

> I want to explore the topic with the keyword 'autoclave', 'hydrothermal' in detail. I'm curious about how the outliers can be grouped together as a single topic instead of being treated as outliers.

Generally, I would not advise making the outliers a single topic as they often are just random points that do not fit with other clusters. As such, doing a 2D visualization or inspecting the individual documents will make that more clear.

**Comment by dlrudgnsdlek** [comment]
Thank you for the comment.

I have one more question.

When using get_topic_info(), I can only see a limited number of keywords by default.  If I want to see 20 keywords for each topic, what should I do?
