### ISSUE TITLE
BERTopic with SpaCy

### ISSUE THREAD

**Issue by trivikram18** [MaartenGr/BERTopic#1366]
Hello Maarten,

Good day!

I am trying to use spacy with BERTopic and I think there is some issue with it. I get the following error ...

AttributeError: [E046] Can't retrieve unregistered extension attribute 'trf_data'. Did you forget to call the `set_extension` method?

I am simply running the code given in the colab example.

from bertopic import BERTopic
from sklearn.datasets import fetch_20newsgroups
docs = fetch_20newsgroups(subset='train',  remove=('headers', 'footers', 'quotes'))['data']

import spacy
nlp = spacy.load("en_core_web_md", exclude=['tagger', 'parser', 'ner', 'attribute_ruler', 'lemmatizer'])
topic_model = BERTopic(embedding_model=nlp, verbose=True).fit(docs)

The versions of the packages which I am using are as follows.
Python - 3.9.12
BERTopic - 0.15
spaCy - 3.5.2

Any insight into this? 
Much appreciate your efforts in creating something amazing like BERTopic.

Best Wishes
Trivikram

**Comment by MaartenGr** [comment]
Could you share the full error log? That helps me understand where the issue stems from. Also, it might be worthwhile to remove everything in the `exclude` parameter and just load in the model without excluding anything. Lastly, which colab example are you referring to?

**Comment by trivikram18** [comment]
The example is from the following colab file.

https://colab.research.google.com/drive/18arPPe50szvcCp_Y6xS56H2tY0m-RLqv?usp=sharing#scrollTo=EdBn0ZwDKoCX

I tried just loading the model removing the 'exclude' but I still get the error ...

Full error log:

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[4], line 6
      3 # nlp = spacy.load("en_core_web_md", exclude=['tagger', 'parser', 'ner', 'attribute_ruler', 'lemmatizer'])
      4 nlp = spacy.load("en_core_web_md")
----> 6 topic_model = BERTopic(embedding_model=nlp, verbose=True).fit(docs)

File C:\MyInstalledSoftware\Miniconda\envs\all3912\lib\site-packages\bertopic\_bertopic.py:303, in BERTopic.fit(self, documents, embeddings, images, y)
    262 def fit(self,
    263         documents: List[str],
    264         embeddings: np.ndarray = None,
    265         images: List[str] = None,
    266         y: Union[List[int], np.ndarray] = None):
    267     """ Fit the models (Bert, UMAP, and, HDBSCAN) on a collection of documents and generate topics
    268 
    269     Arguments:
   (...)
    301     ```
    302     """
--> 303     self.fit_transform(documents=documents, embeddings=embeddings, y=y, images=images)
    304     return self

File C:\MyInstalledSoftware\Miniconda\envs\all3912\lib\site-packages\bertopic\_bertopic.py:373, in BERTopic.fit_transform(self, documents, embeddings, images, y)
    370 if embeddings is None:
    371     self.embedding_model = select_backend(self.embedding_model,
    372                                           language=self.language)
--> 373     embeddings = self._extract_embeddings(documents.Document.values.tolist(),
    374                                           images=images,
    375                                           method="document",
    376                                           verbose=self.verbose)
    377     logger.info("Transformed documents to Embeddings")
    378 else:

File C:\MyInstalledSoftware\Miniconda\envs\all3912\lib\site-packages\bertopic\_bertopic.py:3126, in BERTopic._extract_embeddings(self, documents, images, method, verbose)
   3124     embeddings = self.embedding_model.embed_words(words=documents, verbose=verbose)
   3125 elif method == "document":
-> 3126     embeddings = self.embedding_model.embed_documents(documents, verbose=verbose)
   3127 elif documents[0] is None and images is None:
   3128     raise ValueError("Make sure to use an embedding model that can either embed documents"
   3129                      "or images depending on which you want to embed.")

File C:\MyInstalledSoftware\Miniconda\envs\all3912\lib\site-packages\bertopic\backend\_base.py:69, in BaseEmbedder.embed_documents(self, document, verbose)
     55 def embed_documents(self,
     56                     document: List[str],
     57                     verbose: bool = False) -> np.ndarray:
     58     """ Embed a list of n words into an n-dimensional
     59     matrix of embeddings
     60 
   (...)
     67         that each have an embeddings size of `m`
     68     """
---> 69     return self.embed(document, verbose)

File C:\MyInstalledSoftware\Miniconda\envs\all3912\lib\site-packages\bertopic\backend\_spacy.py:87, in SpacyBackend.embed(self, documents, verbose)
     85     embedding = embedding.vector
     86 else:
---> 87     embedding = embedding._.trf_data.tensors[-1][0]
     89 if not isinstance(embedding, np.ndarray) and hasattr(embedding, 'get'):
     90     # Convert cupy array to numpy array
     91     embedding = embedding.get()

File C:\MyInstalledSoftware\Miniconda\envs\all3912\lib\site-packages\spacy\tokens\underscore.py:47, in Underscore.__getattr__(self, name)
     45 def __getattr__(self, name: str) -> Any:
     46     if name not in self._extensions:
---> 47         raise AttributeError(Errors.E046.format(name=name))
     48     default, method, getter, setter = self._extensions[name]
     49     if getter is not None:

AttributeError: [E046] Can't retrieve unregistered extension attribute 'trf_data'. Did you forget to call the `set_extension` method?

**Comment by MaartenGr** [comment]
I think this relates to #1179 where there was still an issue with accessing the right type of data. I think changing the following:

https://github.com/MaartenGr/BERTopic/blob/94064441233564f29b5ac03ff5c38669067ba4e1/bertopic/backend/_spacy.py#L85C45-L85C45

to this might resolve the issue:

```python
if embedding.has_vector or hasattr(embedding, "vector"):
    embedding = embedding.vector
```

**Comment by trivikram18** [comment]
Thanks for the update Maarten, however, I won't be able to make this change if I am deploying the code right. I am currently trying to deploy code to AWS via a docker image. In fact, I took this route because I having some issues deploying when using sentence_transformers. The docker size is large there and it also gives me some read-only error.

**Comment by MaartenGr** [comment]
I would definitely advise using sentence-transformers wherever possible. Could you show the code and error log for using sentence-transformers? Perhaps I can be of help.

**Comment by trivikram18** [comment]
I have opened that as a discussion and you already replied it here 
https://github.com/MaartenGr/BERTopic/discussions/1370

**Comment by wkiri** [comment]
> I think this relates to #1179 where there was still an issue with accessing the right type of data. I think changing the following:
> 
> https://github.com/MaartenGr/BERTopic/blob/94064441233564f29b5ac03ff5c38669067ba4e1/bertopic/backend/_spacy.py#L85C45-L85C45
> 
> to this might resolve the issue:
> 
> ```python
> if embedding.has_vector or hasattr(embedding, "vector"):
>     embedding = embedding.vector
> ```

Thank you - I experienced the same error with `trf_data`, and this fix worked for me!
