### ISSUE TITLE
typing issue for threshold in reduce_outliers

### ISSUE THREAD

**Issue by dschwalm** [MaartenGr/BERTopic#1367]
Hi,

Type of threshold argument in reduce_outliers should be float and not int IMO.

def reduce_outliers(self,
                        documents: List[str],
                        topics: List[int],
                        images: List[str] = None,
                        strategy: str = "distributions",
                        probabilities: np.ndarray = None,
                        threshold: int = 0,

I use it as a probability threshold and assumed that it should be a float between 0 and 1. But pylint complains that it should be an int.
Either it represents a probability threshold or a minimum similarity, I think it should be float.
Happy to open a PR if you agree.

Thanks,
Daniel

**Comment by MaartenGr** [comment]
Thanks, a PR would be appreciated! If you find more, then combining that into a single PR would be preferred otherwise it will turn out to be quite the number of PRs/commits.

**Comment by dschwalm** [comment]
Sure. I did not find more typing issues in my usage of bertopic. Should I find any in the future I will fix them in a single PR.
Thanks,
Daniel
