### ISSUE TITLE
nr_topics does not work as expected

### ISSUE THREAD

**Issue by sokol11** [MaartenGr/BERTopic#137]
I noticed that setting `nr_topics` to an integer, e.g., `nr_topics=40`, does not, in fact, reduce the number of topics to that number. I am still getting 100s of topics, though I believe fewer than if nr_topics is not set. I am on BERTopic version 0.8. Thank you!

**Comment by MaartenGr** [comment]
Hmm, I am not getting that from a few use cases. Could you share your code or a reproducible example? That way, I can try to see if I can pinpoint the issue.

**Comment by sokol11** [comment]
Yep, sorry, I realized I was not using the API correctly. Closing this.
