### ISSUE TITLE
Getting distance to center of cluster to use as a proxy for confidence

### ISSUE THREAD

**Issue by ronykrell** [MaartenGr/BERTopic#1373]
I'd like to output a confidence metric per document corresponding to its embedding's distance from the cluster center. So if a document's embedding was close to the cluster center it would have a high confidence score for example.

For KMeans I'd want to calculate this distances using code similar to [this](https://stackoverflow.com/questions/54240144/distance-between-nodes-and-the-centroid-in-a-kmeans-cluster)

Does BERTopic expose the ability to add callbacks to the clustering flow such as the code above? Otherwise, what is the best way to incorporate this calculation into a BERTopic-based pipeline?

I am thinking specifically about KMeans but would love if this could apply to the other clustering methods BERTopic supports(HDBscan and agglomerative clustering).

**Comment by MaartenGr** [comment]
You can use the topic embeddings to do such a thing. In the most recent version, the topic embeddings represent a cluster's centroid. You can access the topic embeddings with `topic_model.topic_embeddings_`. You can then calculate the document embeddings yourself and compare their distance with the topic embeddings. Do note though that in the case of density-based algorithms like HDBSCAN, the centroid is less representative than a centroid-based method like k-Means.

**Comment by MaartenGr** [comment]
> I am thinking this would be expensive computationally as I would need to recalculate the embedding for each document and also re-do the dimensionality reduction step to be able to compare apples to apples.

The dimensionality reduction is not necessary as the topic embeddings are created from the input embeddings. You would indeed have to re-calculate the document embeddings if they were not already saved.
