### ISSUE TITLE
How to get both default representation & other representation with BERTopic

### ISSUE THREAD

**Issue by vsean103** [MaartenGr/BERTopic#1375]
<img width="570" alt="Screen Shot 2023-06-29 at 11 14 21 AM" src="https://github.com/MaartenGr/BERTopic/assets/49629460/af009308-711d-4a41-a6e6-86ac049cea91">

Hi Maarten! Thanks for your documentation on fine tuning BERTopic using LLM here https://maartengr.github.io/BERTopic/getting_started/representation/llm.html#prompts

Do you know how to get both default representations (top N keywords) that correspond to other representation such as 🤗 Transformers or OpenAI?

I'm looking forward to hearing from you. I appreciate your help.

**Comment by MaartenGr** [comment]
To get multiple representations, I would advise looking at [multi-aspect topic modeling](https://maartengr.github.io/BERTopic/getting_started/multiaspect/multiaspect.html) with BERTopic.

**Comment by vsean103** [comment]
Awesome! Thank you

**Comment by vsean103** [comment]
Hi Maarten! I tried multi-aspect topic modeling with BERTopic as you suggested but I didn't get the result with multiple representation as in your example.

Can you please take a look?

<img width="839" alt="image" src="https://github.com/MaartenGr/BERTopic/assets/49629460/65260907-167a-4090-9e55-2265f38be6fe">

**Comment by vsean103** [comment]
Hi Maarten! I tried multi-aspect topic modeling as you suggested but the result didn't show multiple representations like in your example.

Can you please take a look?

<img width="782" alt="image" src="https://github.com/MaartenGr/BERTopic/assets/49629460/d2f0b42c-aae0-47c9-8541-9bec04060063">

**Comment by MaartenGr** [comment]
Strange, it should have calculated those. Are you using BERTopic v0.15?

**Comment by vsean103** [comment]
I updated to v0.15 and it worked. Thanks again :)

**Comment by keyeun** [comment]
I'm using BERTopic v0.15 and the same issue appears.

<img width="1104" alt="image" src="https://github.com/MaartenGr/BERTopic/assets/76188991/502d6386-df1c-44cc-80ec-6f5bf4c85f23">

**Comment by MaartenGr** [comment]
@keyeun Could you also show the output? As in, could you demonstrate where exactly it is going wrong? 

When you specify `"Main"` it will overwrite the c-TF-IDF representations and not perform multi-aspect topic modeling. If you want multiple aspects, you should change `"Main"` to something else. For example, `"ChatGPT"`.

**Comment by keyeun** [comment]
@MaartenGr Ah you are right. After changing 'Main' to 'ChatGPT', it works well! Thank you so much for your kind explanation.
