### ISSUE TITLE
Repeated generation of embeddings: issue and suggestion

### ISSUE THREAD

**Issue by NewsSoup** [MaartenGr/BERTopic#1376]
So I have a use case that uses BERTopic at least three times with three different setups, and each time it generates embeddings from scratch. I am now moving my code from development to production, where paying to generate the embeddings repeatedly is an issue.

My solution was to create a subclass of BERTopic that allows the embedding_model to be a string representing the name of the embedding column. I then rewrote the function that gets the embedding (name is on the tip of my tongue) to see if the input is a string and if True it gets the list of embeddings from the DataFrame. I get embeddings from OpenAI in any way, so I don't need that functionality from BERTopic.

It is a small issue, but it makes a huge difference in the development environment. The aim here is to inform you of the issue and an easy solution, so you can close the issue once you read this. If there is another way of bypassing embedding generation, please consider adding a sentence or two to your user guide.

**Comment by MaartenGr** [comment]
That is actually already a possibility, you can pass pre-computed embeddings as such:

```python
from sklearn.datasets import fetch_20newsgroups
from sentence_transformers import SentenceTransformer

# Prepare embeddings
docs = fetch_20newsgroups(subset='all',  remove=('headers', 'footers', 'quotes'))['data']
sentence_model = SentenceTransformer("all-MiniLM-L6-v2")
embeddings = sentence_model.encode(docs, show_progress_bar=False)

# Train our topic model using our pre-trained sentence-transformers embeddings
topic_model = BERTopic()
topics, probs = topic_model.fit_transform(docs, embeddings)
```

You can find more about that [here](https://maartengr.github.io/BERTopic/getting_started/embeddings/embeddings.html#custom-embeddings) and [here](https://maartengr.github.io/BERTopic/getting_started/tips_and_tricks/tips_and_tricks.html#pre-compute-embeddings) amongst others.
