### ISSUE TITLE
Expired link contained in the document page

### ISSUE THREAD

**Issue by burugaria7** [MaartenGr/BERTopic#1383]
Hello. I found a expired link in the documentation.

The link included in the tips in section 4 Bag-of-words of the algorithm on the documentation page has expired.

page containing expired link:
https://maartengr.github.io/BERTopic/algorithm/algorithm.html#3-cluster-documents

expired link:
https://maartengr.github.io/BERTopic/getting_started/countvectorizer/countvectorizer.html

**Comment by MaartenGr** [comment]
Thanks for sharing this! If you want, a PR is definitely appreciated. Otherwise, I'll make sure to fix it myself.

**Comment by MaartenGr** [comment]
Thanks, the first option would be best I think!
