### ISSUE TITLE
Keywords used in OpenAI prompt

### ISSUE THREAD

**Issue by bexy-b** [MaartenGr/BERTopic#1386]
Hi there,

I'm using the OpenAI representation model, but I'm wondering how to change the variable that is passed as KEYWORDS in the prompt? As far as I can tell, I can't provide multiple representations as the Main representation because `extract_topics` throws an error. How can I pass the words extracted from a multi-aspect representation to the OpenAi model?

For example I want to do the following:

`kb= KeyBERTInspired(top_n_words=30)`
`mmr = MaximalMarginalRelevance(diversity=0.9)`
`openai_model = OpenAI(model="gpt-3.5-turbo", delay_in_seconds=10, chat=True, prompt=prompt)`

`representation_model = {"Main":  [kb, mmr], "Open AI": openai_model}`

Is this possible?

Thanks
Rebecca

**Comment by MaartenGr** [comment]
That is currently not possible. `[KEYWORDS]` uses the main representation and extracts those keywords to pass to OpenAI. You would have to set the keywords that you want from the "Main" representation.

**Comment by bexy-b** [comment]
Ok thanks, I thought that was the case. Unless I'm missing something, does this mean having to re-write `extract_topics`?

**Comment by MaartenGr** [comment]
Yes, I believe so, but you could also adjust the `bertopic.representation_model.OpenAI` model to get the keywords from multiple representations instead.

**Comment by bexy-b** [comment]
Great, i'll look into that. Thanks again!
