### ISSUE TITLE
Model tracking for BERTopic models

### ISSUE THREAD

**Issue by manjunath-hanmantgad** [MaartenGr/BERTopic#1389]
Hi, 
Thank you for this amazing lib. We are using BERTopic in our daily use and we would like to keep track of models and hyperparameters. (I went through open/closed issues) but couldn't find a concrete evidence. Is it possible to use any loss tracking tools (mlflow ex.) with it ? I went through the documentation of mlflow but couldn't find a way to do so.

Thank you much for assisting me.

**Comment by manjunath-hanmantgad** [comment]
I could find this : https://huggingface.co/blog/bertopic
any other alternative ?

**Comment by MaartenGr** [comment]
I believe that should be no problem. Mlflow is a flexible framework that essentially allows you to track whatever model and parameters that you are interested. So I foresee no issues using that together with BERTopic. I believe custom tracking should be something like this:

```python
with mlflow.start_run() as run:
      mlflow.log_param("min_topic_size", str(min_topic_size))
      mlflow.log_param("top_n_words", str(top_n_words))
      etc...
```

**Comment by manjunath-hanmantgad** [comment]
Thank you for your reply. 
I also found a very helpful doc in mlfow site. 
mlflow.transformers.load_model() and ..save_model()

**Comment by manjunath-hanmantgad** [comment]
Thank you for the quick revert.
