### ISSUE TITLE
Keyword extraction

### ISSUE THREAD

**Issue by geo47** [MaartenGr/BERTopic#139]
Hi @MaartenGr ,

How to extract keywords using BERTopic similar to [KeyBERT](https://github.com/MaartenGr/KeyBERT).

Thanks

**Comment by geo47** [comment]
Hi @MaartenGr,

Thanks for your response.
Would you please tell, what is difference between using topics from BERTopic as keywords and generating keywords separately from KeyBERT?
As far as I understand, the BERTopic generated topics based on the keywords from the document. So Intuitively, there should not be any difference between both.
Thanks...

**Comment by MaartenGr** [comment]
There is actually quite a big difference between the two methods and the corresponding results. This not only stems from a difference in methodology but also their end-goals: one is for extracting keywords specific to a single document whereas the other tries to create more generalized representations of topics across documents. Thus, the results will differ almost by definition. 

KeyBERT, for instance, uses cosine similarity to compare word embeddings from a document with its document embedding. This means that it will only extract words that are found in that specific document and not anywhere else. Each document will most likely have its own unique set of keywords. 

In contrast, BERTopic does not generate topics based on the keywords from the document. Instead, it leverages a class-based TF-IDF procedure to extract topic representations from a collection of documents. The resulting topic representation is achieved by comparing which words are typical for one topic but not for all others. That way, you keep what makes a topic interesting which in turn maximizes the separability between topics.

**Comment by geo47** [comment]
Thanks @MaartenGr for your detailed and clear explanation.
I totally got the concept behind it.

Thanks again :-)
