### ISSUE TITLE
words get concatenated

### ISSUE THREAD

**Issue by donottakemyusername** [MaartenGr/BERTopic#1393]
Hi, I noticed there is an index number beside each topic (-1 is outlier, and other topics are either 0 or positive numbers). Do those numbers have any meanings or they are just cluster identification numbers that are generated randomly? Thanks!

**Comment by MaartenGr** [comment]
They are the topic IDs. Positive values (including 0) are topics which should have some coherent representation. -1, in contrast, is an outlier cluster and represents random documents. That cluster should not generally be considered a topic.

**Comment by donottakemyusername** [comment]
I see. Thank you!
