### ISSUE TITLE
Concatenated words during the workflow

### ISSUE THREAD

**Issue by donottakemyusername** [MaartenGr/BERTopic#1397]
Hi, I am trying to extract topics with n-gram using BERTopic. I used my own embeddings. When I generated the results, I saw that sometimes some words will be concatenated into a single word. For example, if there is a http link "http:www.abc.com", the resulting topic will be "httpwwwabccom". Is it an internal tokenization process that handles the concatenation? I am currently trying to add all the http links to the stopword library, but for all the tokenization methods I tried (countvectorizer, nltk, spacy), I am not able to identify them as a single word. Do you have any suggestions how I can handle this issue? Thank you!

**Comment by MaartenGr** [comment]
This is indeed a result of the tokenization of scikit-learn's [CountVectorizer](https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html). You could adjust the tokenization [yourself](https://maartengr.github.io/BERTopic/getting_started/vectorizers/vectorizers.html#tokenizer) but seeing your data, I would advise using [beautifulsoup](https://www.crummy.com/software/BeautifulSoup/bs4/doc/) to remove all HTML tags from your data. Generally, these HTML tags do not give much information and are also generally removed when pre-training language models.

**Comment by donottakemyusername** [comment]
Thanks for the suggestion! I was actually passing in NLTK tokenizer in CountVectorizer. Does it sometimes concatenate things after removing the punctuations also?

**Comment by MaartenGr** [comment]
Ah, I should have explained it a bit more in detail. The CountVectorizer is essentially doing two things, cleaning up the data and then applying the tokenizer. What is most likely happening here is that a `.` is simply removed from the text which results in those words looking like they were concatenated. Still, using beautifulsoup would definitely be the way to go here. HTML-tags seldom contribute to topics, at least in my experience, and can safely be removed.

**Comment by donottakemyusername** [comment]
I see. Thank you!
