### ISSUE TITLE
No module named 'transformers.models' under 0.8.1

### ISSUE THREAD

**Issue by fireindark707** [MaartenGr/BERTopic#140]
When I load the BERTopic model created under 0.8 version, I got the below error. It looks like this involves some problems with the transformers package, and I haven't studied what's going on in detail.

When I forced pip to install version 0.8, everything was back to normal.

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-6-925ce2eace2f> in <module>()
----> 1 topic_model = BERTopic.load("model/nCov_"+model_name.split("/")[-1]+".model")
      2 with open("output/topics_all_"+model_name.split("/")[-1]+".json","r") as f:
      3   topics = json.load(f)

5 frames
/usr/local/lib/python3.7/dist-packages/bertopic/_bertopic.py in load(cls, path, embedding_model)
   1234                 topic_model.embedding_model = embedding_model
   1235             else:
-> 1236                 topic_model = joblib.load(file)
   1237             return topic_model
   1238 

/usr/local/lib/python3.7/dist-packages/joblib/numpy_pickle.py in load(filename, mmap_mode)
    573         filename = getattr(fobj, 'name', '')
    574         with _read_fileobject(fobj, filename, mmap_mode) as fobj:
--> 575             obj = _unpickle(fobj)
    576     else:
    577         with open(filename, 'rb') as f:

/usr/local/lib/python3.7/dist-packages/joblib/numpy_pickle.py in _unpickle(fobj, filename, mmap_mode)
    502     obj = None
    503     try:
--> 504         obj = unpickler.load()
    505         if unpickler.compat_mode:
    506             warnings.warn("The file '%s' has been generated with a "

/usr/lib/python3.7/pickle.py in load(self)
   1086                     raise EOFError
   1087                 assert isinstance(key, bytes_types)
-> 1088                 dispatch[key[0]](self)
   1089         except _Stop as stopinst:
   1090             return stopinst.value

/usr/lib/python3.7/pickle.py in load_global(self)
   1374         module = self.readline()[:-1].decode("utf-8")
   1375         name = self.readline()[:-1].decode("utf-8")
-> 1376         klass = self.find_class(module, name)
   1377         self.append(klass)
   1378     dispatch[GLOBAL[0]] = load_global

/usr/lib/python3.7/pickle.py in find_class(self, module, name)
   1424             elif module in _compat_pickle.IMPORT_MAPPING:
   1425                 module = _compat_pickle.IMPORT_MAPPING[module]
-> 1426         __import__(module, level=0)
   1427         if self.proto >= 4:
   1428             return _getattribute(sys.modules[module], name)[0]

ModuleNotFoundError: No module named 'transformers.models'

**Comment by MaartenGr** [comment]
BERTopic v0.8.1 has different transformer versions specified which might affect loading in the model. In general, I would advise using pre-trained BERTopic models only for the versions on which they were trained. Other than that, you can re-train the model with the newest version. 

Fortunately, there is no difference between v0.8.1 and v0.8.0 when it comes to features and performance. The main difference is that a different default model is selected in the newer version. So I would suggest keeping v0.8.0 for your model.

**Comment by fireindark707** [comment]
Thanks for the response.
