### ISSUE TITLE
Evaluation baseline.

### ISSUE THREAD

**Issue by abhijithneilabraham** [MaartenGr/BERTopic#141]
Hi,

Please let me know where to find the evaluation data that you compared with your work against LDA.

Thank you.

**Comment by MaartenGr** [comment]
Evaluation is a difficult and, to a certain extent, subjective topic in topic modeling. Although methods exist such as c_v and c_npmi, they are merely proxies for a topic model's performance. They are by no means a ground truth and can have significant issues (e.g., sensitive to the number of words in a topic). So whether you find a low or high score, I would advise you to look at the topics yourself and see if they make sense to you.

Having said that, there is currently no evaluation procedure using these methods as I am trying to research the correct methods for evaluating this method (including DTM). However, you are free to experiment with some evaluation measures that are mentioned in #90.

**Comment by abhijithneilabraham** [comment]
Thanks.
