### ISSUE TITLE
Option to set seed for reproduceability

### ISSUE THREAD

**Issue by MalteHB** [MaartenGr/BERTopic#143]
Hi @MaartenGr!

Thank you so much for your project. It is truly awesome, and i really enjoy working with it. 

It would, however, be awesome to include the option to set a seed for reproducible results with the topic modelling. 

Have a nice day! 💯

**Comment by MaartenGr** [comment]
Thank you for the kind words! 

BERTopic makes use of UMAP, which is a stochastic model. Currently, it is not possible to set a seed in UMAP without reducing its performance (see [this](https://umap-learn.readthedocs.io/en/latest/reproducibility.html)). Having said that, if you are set on wanting reproducible results, you can use a custom UMAP model with the random_state set to any value like this:

```python
from bertopic import BERTopic
from umap import UMAP

umap_model = UMAP(random_state=42)

topic_model = BERTopic(umap_model=umap_model)
```

Hopefully, this answers your question!
