### ISSUE TITLE
Receiving Invalid Request Error when using OpenAI module in representation

### ISSUE THREAD

**Issue by kulzen24** [MaartenGr/BERTopic#1437]
When I instantiate an OpenAI function call (from the representation module) with the following arguments:

`OpenAI(model="text-davinci-003", delay_in_seconds=0.5, generator_kwargs={"temperature": 0.4})`

I am returned an error upon running `topic_model.fit_transform` (`topic_model` is my `BERTopic` object). The error states "InvalidRequestError: Must provide an 'engine' or 'deployment_id' parameter to create a <class 'openai.api_resources.completion.Completion'>"

We were able to remediate this in our local environment by changing the name of the parameter "model" to "engine." But in our managed environment we are unable to change the base package quickly. Could this issue be looked into and verified? Thank you.

bertopic > representation > _openai.py under extract_topics function.

**Comment by MaartenGr** [comment]
Could you share the versions in your environment? Could you also share your code? The following is actually working for me:

```python
import openai
from bertopic.backend import OpenAIBackend
from bertopic.representation import OpenAI
from bertopic import BERTopic
from sklearn.datasets import fetch_20newsgroups

# Embedding model
openai.api_key = "sk-..."
embedding_model = OpenAIBackend("text-embedding-ada-002")

# Representation model
representation_model = OpenAI(model="text-davinci-003", delay_in_seconds=0.5, generator_kwargs={"temperature": 0.4})

# Documents
docs = fetch_20newsgroups(subset='all',  remove=('headers', 'footers', 'quotes'))['data'][:200]
docs = [doc for doc in docs if len(doc) > 0]

# Training
topic_model = BERTopic(embedding_model=embedding_model, representation_model=representation_model)
topics, probs = topic_model.fit_transform(docs)
```

**Comment by kulzen24** [comment]
Thanks for the quick response. I'm using version 0.15.0 and have also tried 0.14.1.

`from bertopic import BERTopic
from sklearn.feature_extraction.text import CountVectorizer
from bertopic.representation import KeyBERTInspired, MaximalMarginalRelevance, PartOfSpeech, OpenAI
from sentence_transformers import SentenceTransformer
import openai

openai.api_type = "azure"
openai.api_base = "https://xxx.openai.azure.com/"
openai.api_version = "2023-03-15-preview"
openai.api_key = openaikey

vectorizer_model = CountVectorizer(ngram_range=(1,2), stop_words="english")
representation_model = OpenAI(model="text-davinci-003", delay_in_seconds=0.5, generator_kwargs={"temperature": 0.4})

topic_model = BERTopic(
    vectorizer_model=vectorizer_model,
    min_topic_size=30,
    top_n_words=20,
    representation_model=representation_model,
    embedding_model="all-mpnet-base-v2",
    )

topics, probs = topic_model.fit_transform(docs, embeddings)`

docs is a list of type string that I compute earlier in my code and embeddings is a numpy array.

This returns: "InvalidRequestError: Must provide an 'engine' or 'deployment_id' parameter to create a <class 'openai.api_resources.completion.Completion'>"

**Comment by MaartenGr** [comment]
Ah, I believe this relates to #1263. You should specify the embedding model as follows:

```python
from bertopic.representation import OpenAI
representation_model= OpenAI(generator_kwargs={"engine":"my-custom-embedding_model")
```

**Comment by kulzen24** [comment]
Thanks for the response @MaartenGr. This argument worked for me.
