### ISSUE TITLE
reduce_outliers followed by update_topics: resulting get_topic_info() does not sort by new Count

### ISSUE THREAD

**Issue by davidtweddell** [MaartenGr/BERTopic#1448]
Hi there - 

This is a great project and I very much appreciate all the work that goes into it.

I have noticed what may be a bug in the process of reducing outliers (`v0.15`). The data set I've used to document this is a conventional set of [CS articles](https://www.kaggle.com/datasets/shivanandmn/multilabel-classification-dataset?select=train.csv), but I first noticed it on my proprietary dataset.

First, I set up a topic model as shown below, then `fit_transform` and inspect the topics. As expected, the topics are sorted by `Count`. 

```
# embedding model
from sentence_transformers import SentenceTransformer
embedding_model = SentenceTransformer("all-MiniLM-L6-v2", device="mps")
sm_parms = {
    'show_progress_bar': True,
    'normalize_embeddings': True
}
# precalculate embeddings
embeddings = sentence_model.encode(docs, **sm_parms)

# get english stopwords
from nltk.corpus import stopwords
default_sw = stopwords.words('english')
custom_sw = ['research', 'project', 'proposal', 'study']
sw = default_sw + custom_sw

# vectorizer model
from sklearn.feature_extraction.text import CountVectorizer
vectorizer_model = CountVectorizer(stop_words=sw)

# umap and hdbscan not shown for brevity

# assemble the topic model
topic_model = BERTopic(
                        vectorizer_model = vectorizer_model,
                        hdbscan_model   = hdbscan_model,
                        umap_model      = umap_model,
                        embedding_model = embedding_model,
                        calculate_probabilities = True
                        )

# fit and transform the model
topics, probs = topic_model.fit_transform(docs, embeddings=embeddings)

# inspect the topics
topic_model.get_topic_info()[['Topic', 'Count', 'Name']]
```

**Result**: Correctly sorted by `Count`
 Topic | Count | Name
-- | -- | -- 
-1 | 5013 | -1_data_model_based_paper
0 | 803 | 0_mass_10_star_galaxies
1 | 695 | 1_mathbb_group_algebra_groups
2 | 604 | 2_data_model_models_method
3 | 392 | 3_spin_magnetic_phase_temperature
4 | 306 | 4_learning_robot_reinforcement_control
5 | 207 | 5_mathbb_solutions_equation_infty
6 | 178 | 6_network_networks_community_nodes
7 | 165 | 7_quantum_states_light_optical
8 | 165 | 8_graphs_graph_problem_time
9 | 147 | 9_flow_fluid_flows_turbulence
10 | 127 | 10_data_privacy_iot_security
11 | 101 | 11_neural_networks_deep_network
12 | 86 | 12_adversarial_domain_learning_deep

Now, using `reduce_outliers` followed by `update_topics`:

```
# Reduce outliers
ro_parms = {
    # note that this behaviour occurs regardless of which strategy is used
    # 'strategy': 'probabilities',
    # 'probabilities': probs,
    # 'strategy': 'embeddings',
    # 'embeddings': embeddings,
    'strategy': 'c-tf-idf',
}

new_topics = topic_model.reduce_outliers(docs, topics, **ro_parms)

topic_model.update_topics(docs, 
                            topics           = new_topics, 
                            vectorizer_model = vectorizer_model
                        )

# inspect the updated topics
topic_model.get_topic_info()[['Topic', 'Count', 'Name']]
```
**Result**: Not sorted by `Count`
Topic | Count | Name
-- | -- | -- 
0 | 905 | 0_mass_10_star_galaxies
1 | 994 | 1_group_mathbb_algebra_groups
2 | 1984 | 2_data_model_algorithm_method
3 | 629 | 3_spin_magnetic_phase_temperature
4 | 673 | 4_learning_control_robot_policy
5 | 540 | 5_mathbb_equation_prove_solutions
6 | 553 | 6_network_networks_social_model
7 | 480 | 7_quantum_states_optical_energy
8 | 349 | 8_graph_graphs_problem_algorithm
9 | 383 | 9_flow_fluid_equations_numerical
10 | 511 | 10_data_system_systems_paper
11 | 522 | 11_neural_deep_networks_network
12 | 466 | 12_learning_training_adversarial_image

EDITED: removed a hypothetical suggestion to fix, which was wrong. Still thinking about it.

**Comment by MaartenGr** [comment]
From the top of my head, I believe this was intentional. If the topics remain the same but their counts differ, then you would want to have the same ordering as before reducing outliers. The topics themselves do not change, merely that there are more documents assigned to them. So I do not think updating the ordering of the topics is a nice user experience since they would have to manually find the old topics and match them with the new topics. This way, they have the same output but with merely updated counts and topic representations. By keeping everything else the same, there is a sense of similarity between the previous and current output that makes it easier to compare what has changed after outlier reduction.

**Comment by davidtweddell** [comment]
Thanks Maarten. That's a very good point, and I hadn't considered that. I'm happy to close this issue because it's not an issue.

As an aside, my motivation was that I was thinking of a very specific use case: for presentation to a specific target audience, re-naming the topics based on their rank by count would be helpful. But there are other ways to achieve that (it's essentially a cosmetic change only). 

Thanks!

**Comment by lynn1885** [comment]
Hi, May I ask how to rank by count after  `reduce_outliers` and `update_topics`. In my case ranking topics by count would be helpful. Thanks!

**Comment by MaartenGr** [comment]
@lynn1885 This is not officially supported by BERTopic and is unlikely that it will be currently. You would have to re-order them manually using private functions (which is generally not recommended as they can change often with new versions):

https://github.com/MaartenGr/BERTopic/blob/6c9eb6e72a881077ac59c35752d26e391bfe4c49/bertopic/_bertopic.py#L4205

**Comment by davidtweddell** [comment]
@lynn1885 If all you need to do is present the results in a nicely ranked order (that was my use case), it's safer to just make a new dataframe with the results, sort it by the `Count`, and assign a new topic number by reindexing (and updating the topic name depending on what you want).

**Comment by lynn1885** [comment]
@MaartenGr  @davidtweddell  Thank you very much for your advice, it's very helpful!
