### ISSUE TITLE
Using a model trained on one sample to classify new documents

### ISSUE THREAD

**Issue by petercohanlon** [MaartenGr/BERTopic#1453]
hello @MaartenGr
Your documentation is excellent but I have been unable to find the answer I seek. I have trained a model on a subset of data that I am very happy with. I'd now like to apply it to a much larger dataset to create topic labels without retraining the model. I am wondering how to do this. I note in https://github.com/MaartenGr/BERTopic/issues/454 you refer to using the .transform() function. Would this be a way to do so and if so how?
Otherwise, do I need to build a separate classifier using the topic labels?

Kind regards

**Comment by MaartenGr** [comment]
Indeed, if you want to classify new documents based on the topics you have found before, you can use `.transform` for that.

**Comment by petercohanlon** [comment]
Great. I assumed as much. I'm double learning at the moment so forgive me if that was a dumb one. Thanks for the quick response. I'm really loving how modular BERTopic is.

**Comment by MaartenGr** [comment]
Thank you for the kind words and there is no such thing as a dumb question! Feel free to ask anything if you face any issues, problems, or anything else.

**Comment by petercohanlon** [comment]
Thanks again for your help. I am progressing but have hit another issue - I'm not sure I understand what arguments are needed for the .transform() function. If I pass it the docs that I perform fit_transform on, it seems to want embeddings. 
AttributeError: 'NoneType' object has no attribute 'embed_documents' 

If I pass it the original embeddings that I created to train the model:
embeddings = vectorizer.fit_transform(docs)
labels = topic_model.transform (docs, embeddings) 
I get a list of topic IDs for the docs. Seems OK.

If I now pass it new data 
new_labels = topic_model.transform(new_docs, embeddings)
I get an error because I probably need new embeddings for the new data as the shape is wrong "valueError: Make sure that the embeddings are a numpy array with shape:..."

If I create new embeddings for my new data
new_embeddings = vectorizer.fit_transform(new_docs)
new_labels = topic_model.transform(new_docs,new_embeddings)
I am getting
ValueError: incompatible dimension for X and Y matrices: 

I couldn't find a list or necessary argument for .transform() to work properly on the website. Can you suggest what I might be doing wrong? 

As an aside my dataset is quite unusual and consists of documents often containing just one or two words, and often some non-dictionary word character combinations (codes). Essentially I am compressing a database field to have a reduced set of values in it and the hierarchy of topics that I have extracted is really pleasing to those that understand the data in that database field.

Kind regards

**Comment by petercohanlon** [comment]
Hello again @MaartenGr
I think I solved this one for myself. I hadn't realised that embeddings were dimensioned by the number of documents. I needed to pass separate pre-trained embeddings to the .transform() function which was created using the same method of embedding.
