### ISSUE TITLE
Failed to build hdbscan ERROR: Could not build wheels for hdbscan, which is required to install pyproject.toml-based projects

### ISSUE THREAD

**Issue by manjunath-hanmantgad** [MaartenGr/BERTopic#1454]
Hi @MaartenGr , 
Greetings for the day.
I am facing an issue while installing bertopic.
Also tried installing hdbscan(v0.8.33) but the error persists.

Checked the build tools (c++) these too are present.
Could you please help in this regards ?

Thank you.

**Comment by manjunath-hanmantgad** [comment]
`Complete error in console:

Building wheels for collected packages: hdbscan
  Building wheel for hdbscan (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for hdbscan (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [40 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-310
      creating build\lib.win-amd64-cpython-310\hdbscan
      copying hdbscan\flat.py -> build\lib.win-amd64-cpython-310\hdbscan
      copying hdbscan\hdbscan_.py -> build\lib.win-amd64-cpython-310\hdbscan
      copying hdbscan\plots.py -> build\lib.win-amd64-cpython-310\hdbscan
      copying hdbscan\prediction.py -> build\lib.win-amd64-cpython-310\hdbscan
      copying hdbscan\robust_single_linkage_.py -> build\lib.win-amd64-cpython-310\hdbscan
      copying hdbscan\validity.py -> build\lib.win-amd64-cpython-310\hdbscan
      copying hdbscan\__init__.py -> build\lib.win-amd64-cpython-310\hdbscan
      creating build\lib.win-amd64-cpython-310\hdbscan\tests
      copying hdbscan\tests\test_flat.py -> build\lib.win-amd64-cpython-310\hdbscan\tests
      copying hdbscan\tests\test_hdbscan.py -> build\lib.win-amd64-cpython-310\hdbscan\tests
      copying hdbscan\tests\test_prediction_utils.py -> build\lib.win-amd64-cpython-310\hdbscan\tests
      copying hdbscan\tests\test_rsl.py -> build\lib.win-amd64-cpython-310\hdbscan\tests
      copying hdbscan\tests\__init__.py -> build\lib.win-amd64-cpython-310\hdbscan\tests
      running build_ext
      cythoning hdbscan/_hdbscan_tree.pyx to hdbscan\_hdbscan_tree.c
      C:\Users\<>\AppData\Local\Temp\pip-build-env-yo01jm2m\overlay\Lib\site-packages\Cython\Compiler\Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: C:\Users\<USERNAME>\AppData\Local\Temp\pip-install-hqmu9gll\hdbscan_4f8589bbd4694a67981ddc20544733da\hdbscan\_hdbscan_tree.pyx
        tree = Parsing.p_module(s, pxd, full_module_name)
      cythoning hdbscan/_hdbscan_linkage.pyx to hdbscan\_hdbscan_linkage.c
      C:\Users\<USERNAME>\AppData\Local\Temp\pip-build-env-yo01jm2m\overlay\Lib\site-packages\Cython\Compiler\Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: C:\Users\<USERNAME>\AppData\Local\Temp\pip-install-hqmu9gll\hdbscan_4f8589bbd4694a67981ddc20544733da\hdbscan\_hdbscan_linkage.pyx
        tree = Parsing.p_module(s, pxd, full_module_name)
      cythoning hdbscan/_hdbscan_boruvka.pyx to hdbscan\_hdbscan_boruvka.c
      C:\Users\<USERNAME>\AppData\Local\Temp\pip-build-env-yo01jm2m\overlay\Lib\site-packages\Cython\Compiler\Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: C:\Users\<USERNAME>\AppData\Local\Temp\pip-install-hqmu9gll\hdbscan_4f8589bbd4694a67981ddc20544733da\hdbscan\_hdbscan_boruvka.pyx
        tree = Parsing.p_module(s, pxd, full_module_name)
      cythoning hdbscan/_hdbscan_reachability.pyx to hdbscan\_hdbscan_reachability.c
      C:\Users\<USERNAME>\AppData\Local\Temp\pip-build-env-yo01jm2m\overlay\Lib\site-packages\Cython\Compiler\Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: C:\Users\<USERNAME>\AppData\Local\Temp\pip-install-hqmu9gll\hdbscan_4f8589bbd4694a67981ddc20544733da\hdbscan\_hdbscan_reachability.pyx
        tree = Parsing.p_module(s, pxd, full_module_name)
      cythoning hdbscan/_prediction_utils.pyx to hdbscan\_prediction_utils.c
      C:\Users\<USERNAME>\AppData\Local\Temp\pip-build-env-yo01jm2m\overlay\Lib\site-packages\Cython\Compiler\Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: C:\Users\<USERNAME>\AppData\Local\Temp\pip-install-hqmu9gll\hdbscan_4f8589bbd4694a67981ddc20544733da\hdbscan\_prediction_utils.pyx
        tree = Parsing.p_module(s, pxd, full_module_name)
      cythoning hdbscan/dist_metrics.pyx to hdbscan\dist_metrics.c
      C:\Users\<USERNAME>\AppData\Local\Temp\pip-build-env-yo01jm2m\overlay\Lib\site-packages\Cython\Compiler\Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: C:\Users\<USERNAME>\AppData\Local\Temp\pip-install-hqmu9gll\hdbscan_4f8589bbd4694a67981ddc20544733da\hdbscan\dist_metrics.pxd
        tree = Parsing.p_module(s, pxd, full_module_name)
      building 'hdbscan._hdbscan_tree' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for hdbscan
Failed to build hdbscan
ERROR: Could not build wheels for hdbscan, which is required to install pyproject.toml-based projects`

**Comment by manjunath-hanmantgad** [comment]
Attaching screenshot for build tools.
<img width="940" alt="image" src="https://github.com/MaartenGr/BERTopic/assets/3494671/94e240ad-eb5a-4aaf-9acc-b9145347cc92">

**Comment by manjunath-hanmantgad** [comment]
<img width="820" alt="image" src="https://github.com/MaartenGr/BERTopic/assets/3494671/abbc2941-8dd1-4334-85ca-a2a0c2dfb08f">

**Comment by MaartenGr** [comment]
I think it still has something to do with your specific environment not finding Microsoft Visual C++ 14.0 or greater. Just because it was installed does not necessarily mean that it was added to your path or can be accessed from within your environment. 

There are a [number of issues](https://github.com/scikit-learn-contrib/hdbscan/issues?q=is%3Aissue+visual+is%3Aclosed) that you can check out on the HDBSCAN page for this.

**Comment by RenukaRajendra** [comment]
Hi, I also faced the same issue, installing bertopic in VS code IDE. please let me know any solution for this.

**Comment by MaartenGr** [comment]
@RenukaRajendra Please check #293 for more information. There are a bunch of helpful tips there!
