### ISSUE TITLE
NaN Representative_Docs

### ISSUE THREAD

**Issue by annm802** [MaartenGr/BERTopic#1457]
Hi @MaartenGr,

I keep getting NaN values as representative documents when I load my model, after saving it with either 'safetensors' or 'pytorch'.
Here is my code:
`
embedding_model = SentenceTransformer('all-MiniLM-L6-v2')
topic_model.save('/content/drive/MyDrive/boombust_cs_model', serialization="safetensors", 
save_embedding_model= embedding_model )`
`BERTopic.load('/content/drive/MyDrive/boombust_cs_model', embedding_model= embedding_model)`

What might be the issue?

**Comment by MaartenGr** [comment]
The documents themselves are not saved to file in order to prevent sensitive data from being saved. This is different when you use pickle though, then everything will be saved.

**Comment by huycke** [comment]
> The documents themselves are not saved to file in order to prevent sensitive data from being saved. This is different when you use pickle though, then everything will be saved.

Is there a way to load the model and associated docs without using pickle?

**Comment by huycke** [comment]
I'm still just goofing around, but I saved the list of topics to a dataframe that had the documents and other data saved. It's not perfect, because I have to sort through docs in a different manner and can't access the representative docs functions.

Would be interested in hearing alternatve options (maybe .pickle is it?).

**Comment by MaartenGr** [comment]
You can save the representative documents from `topic_model.representative_docs_` using whatever method you are interested in. It can be `pickle` but you can also choose to save it to `.txt`. Then, you can load in your topic model and the saved representative docs and assign them to `topic_model.representative_docs_`. That should do it.

**Comment by annm802** [comment]
> The documents themselves are not saved to file in order to prevent sensitive data from being saved. This is different when you use pickle though, then everything will be saved.

Thank you this worked!

**Comment by MaartenGr** [comment]
@mepearson Thanks for the feedback and kind words! If you want, a PR would be much appreciated!
