### ISSUE TITLE
Partially initialized module 'pandas'

### ISSUE THREAD

**Issue by PriyaDCosta** [MaartenGr/BERTopic#1479]
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[/Users/priyadcosta/Documents/GitHub/team-process-map/feature_engine/features/BERTopicFinal.ipynb](https://file+.vscode-resource.vscode-cdn.net/Users/priyadcosta/Documents/GitHub/team-process-map/feature_engine/features/BERTopicFinal.ipynb) Cell 2 in 1
----> [1](vscode-notebook-cell:/Users/priyadcosta/Documents/GitHub/team-process-map/feature_engine/features/BERTopicFinal.ipynb#W1sZmlsZQ%3D%3D?line=0) from bertopic import BERTopic
      [2](vscode-notebook-cell:/Users/priyadcosta/Documents/GitHub/team-process-map/feature_engine/features/BERTopicFinal.ipynb#W1sZmlsZQ%3D%3D?line=1) import ssl
      [3](vscode-notebook-cell:/Users/priyadcosta/Documents/GitHub/team-process-map/feature_engine/features/BERTopicFinal.ipynb#W1sZmlsZQ%3D%3D?line=2) import pandas as pd

File [/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/bertopic/__init__.py:1](https://file+.vscode-resource.vscode-cdn.net/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/bertopic/__init__.py:1)
----> 1 from bertopic._bertopic import BERTopic
      3 __version__ = "0.15.0"
      5 __all__ = [
      6     "BERTopic",
      7 ]

File [/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/bertopic/_bertopic.py:17](https://file+.vscode-resource.vscode-cdn.net/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/bertopic/_bertopic.py:17)
     15 import collections
     16 import numpy as np
---> 17 import pandas as pd
     18 import scipy.sparse as sp
     20 from tqdm import tqdm

File [/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pandas/__init__.py:138](https://file+.vscode-resource.vscode-cdn.net/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pandas/__init__.py:138)
    120 from pandas.core.reshape.api import (
    121     concat,
    122     lreshape,
   (...)
    134     qcut,
    135 )
    137 from pandas import api, arrays, errors, io, plotting, tseries
--> 138 from pandas import testing  # noqa:PDF015
    139 from pandas.util._print_versions import show_versions
    141 from pandas.io.api import (
    142     # excel
    143     ExcelFile,
   (...)
    171     read_spss,
    172 )

File [/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pandas/testing.py:6](https://file+.vscode-resource.vscode-cdn.net/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pandas/testing.py:6)
      1 """
      2 Public testing utility functions.
      3 """
----> 6 from pandas._testing import (
      7     assert_extension_array_equal,
      8     assert_frame_equal,
      9     assert_index_equal,
     10     assert_series_equal,
     11 )
     13 __all__ = [
     14     "assert_extension_array_equal",
     15     "assert_frame_equal",
     16     "assert_series_equal",
     17     "assert_index_equal",
     18 ]

File [/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pandas/_testing/__init__.py:903](https://file+.vscode-resource.vscode-cdn.net/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pandas/_testing/__init__.py:903)
    898     import pytest
    900     return pytest.raises(expected_exception, match=None)  # noqa: PDF010
--> 903 cython_table = pd.core.common._cython_table.items()
    906 def get_cython_table_params(ndframe, func_names_and_expected):
    907     """
    908     Combine frame, functions from com._cython_table
    909     keys and expected result.
   (...)
    921         List of three items (DataFrame, function, expected result)
    922     """

AttributeError: partially initialized module 'pandas' has no attribute 'core' (most likely due to a circular import)

**Comment by PriyaDCosta** [comment]
Has anyone faced this issue: AttributeError: partially initialized module 'pandas' has no attribute 'core' (most likely due to a circular import). It began happening just today for me.

**Comment by PriyaDCosta** [comment]
Resolved by restarting my Mac

**Comment by shizhediao** [comment]
I encountered the same issue and solved it by restarting the kernel in `notebook`
