### ISSUE TITLE
Getting AttributeError: extract_topics when using Azure OpenAI models as bertopic representation model.

### ISSUE THREAD

**Issue by imprateekagarwal** [MaartenGr/BERTopic#1483]
Here is full error message and code:
Error code: KeyError                                  Traceback (most recent call last)
File /anaconda/envs/azureml_py38/lib/python3.8/site-packages/openai/openai_object.py:59, in OpenAIObject.__getattr__(self, k)
     58 try:
---> 59     return self[k]
     60 except KeyError as err:

KeyError: 'extract_topics'

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
Input In [20], in <cell line: 5>()
      1 topic_model_pmt = BERTopic(embedding_model="all-MiniLM-L6-v2", 
      2                             representation_model=representation_models, 
      3                             vectorizer_model=vectorizer_model)
----> 5 topics_pmt, probs_pmt = topic_model_pmt.fit_transform(df_detractors['verbatim'].tolist())

File /anaconda/envs/azureml_py38/lib/python3.8/site-packages/bertopic/_bertopic.py:411, in BERTopic.fit_transform(self, documents, embeddings, images, y)
    408     self._save_representative_docs(custom_documents)
    409 else:
    410      # Extract topics by calculating c-TF-IDF
--> 411     self._extract_topics(documents, embeddings=embeddings)
    413     # Reduce topics
    414     if self.nr_topics:

File /anaconda/envs/azureml_py38/lib/python3.8/site-packages/bertopic/_bertopic.py:3296, in BERTopic._extract_topics(self, documents, embeddings, mappings)
   3294 documents_per_topic = documents.groupby(['Topic'], as_index=False).agg({'Document': ' '.join})
   3295 self.c_tf_idf_, words = self._c_tf_idf(documents_per_topic)
-> 3296 self.topic_representations_ = self._extract_words_per_topic(words, documents)
   3297 self._create_topic_vectors(documents=documents, embeddings=embeddings, mappings=mappings)
   3298 self.topic_labels_ = {key: f"{key}_" + "_".join([word[0] for word in values[:4]])
   3299                       for key, values in
   3300                       self.topic_representations_.items()}

File /anaconda/envs/azureml_py38/lib/python3.8/site-packages/bertopic/_bertopic.py:3568, in BERTopic._extract_words_per_topic(self, words, documents, c_tf_idf, calculate_aspects)
   3566 if isinstance(self.representation_model, list):
   3567     for tuner in self.representation_model:
-> 3568         topics = tuner.extract_topics(self, documents, c_tf_idf, topics)
   3569 elif isinstance(self.representation_model, BaseRepresentation):
   3570     topics = self.representation_model.extract_topics(self, documents, c_tf_idf, topics)

File /anaconda/envs/azureml_py38/lib/python3.8/site-packages/openai/openai_object.py:61, in OpenAIObject.__getattr__(self, k)
     59     return self[k]
     60 except KeyError as err:
---> 61     raise AttributeError(*err.args)

AttributeError: extract_topics

Code:
from bertopic import BERTopic
from bertopic.representation import MaximalMarginalRelevance
from bertopic.representation import OpenAI
from sklearn.feature_extraction.text import CountVectorizer

vectorizer_model = CountVectorizer(stop_words="english")

openai.api_key = "XXXXX"
openai.api_type = "azure"
openai.api_base = "XXXXX"
openai.api_version = "2023-05-15"

prompt = """
I have a topic that contains the following documents: 
[DOCUMENTS]
The topic is described by the following keywords: [KEYWORDS]

Based on the information above, extract a short topic label in the following format:
topic: <topic label>
"""

response = openai.ChatCompletion.create(engine="gpt-35-turbo",messages=[{"role": "user", "content": prompt}], temperature=0.2, )

mmr = MaximalMarginalRelevance(diversity=0.2)
openai_generator = response
representation_models = [mmr, openai_generator]

topic_model_pmt = BERTopic(embedding_model="all-MiniLM-L6-v2", 
                            representation_model=representation_models, 
                            vectorizer_model=vectorizer_model)

topics_pmt, probs_pmt = topic_model_pmt.fit_transform(df_detractors['verbatim'].tolist())

**Comment by MaartenGr** [comment]
Make sure to use the `OpenAI` representation model as instructed in the [documentation](https://maartengr.github.io/BERTopic/getting_started/representation/llm.html#openai). You should pass a `bertopic.representation.OpenAI` object and not the response that you created.

**Comment by imprateekagarwal** [comment]
Thanks @MaartenGr for the reply. It worked using with OpenAI representation passing deployment name as one of the generator_kwargs.

**Comment by dheerajvarma24** [comment]
Hi @imprateekagarwal if possible, can you please share the working config. I am using AzureOpenAI with BERTopic representations. I faced the same issue as yours.
