### ISSUE TITLE
Does BERTopic only produce one topic per document？

### ISSUE THREAD

**Issue by HanweiLi-cqu** [MaartenGr/BERTopic#1485]
I trained a BERTopic model, and when I went to get the topics for the training set, I found that there was only one topic for each document in the training set.
For example:
I was expecting
doc1: [topic0, topic1,topic2]
doc2: [topic5, topic 9]
But what I get is:
doc1: topic0
doc2: topic5
So I'm asking if BERTopic is designed that way?

**Comment by MaartenGr** [comment]
Yes! BERTopic is essentially a clustering task that tries to primarily find topics and represent them. You can find more about the underlying algorithm [here](https://maartengr.github.io/BERTopic/algorithm/algorithm.html). 

Having said that, if you want multiple topics per document, then I would advise using the [`.approximate_distribution `](https://maartengr.github.io/BERTopic/getting_started/distribution/distribution.html) function for that which allows BERTopic to go from a single document assignment to multi-assignment on a token-level. 

All in all, the documentation is quite extensive if I so say myself for you to find many helpful tips, tricks, best practices, etc. 😉

**Comment by HanweiLi-cqu** [comment]
Thank you so much for your quick response!
