### ISSUE TITLE
Probabilities (Documents)

### ISSUE THREAD

**Issue by firmai** [MaartenGr/BERTopic#149]
What method do you believe should be used to obtain some aggregate probability (like topic 2 Vec) to see if the document belongs to a search query: 

![image](https://user-images.githubusercontent.com/26666267/122393442-c98fe380-cf6c-11eb-8703-ac57d79b28fb.png)

**Comment by MaartenGr** [comment]
This is something that most likely will not be implemented in the future. The only way to do this is to save the embeddings from the documents, and the documents themselves, into the model. Imagine you have a few million documents worth several gigabytes saved in the model. That would explode its size and make it very difficult to use. 

So from a user-experience standpoint, this feature may actually diminish its usability. 

What could be done is creating a function that takes in documents and a keyword and finds the documents that best represent that keyword. However, that would mean that everytime you run that function it needs to re-calculate the embeddings.
