### ISSUE TITLE
how to rank documents within the topics from most relevant to least

### ISSUE THREAD

**Issue by bhutkie** [MaartenGr/BERTopic#1497]
I am using Kmeans as my cluster model for modelling topics. I would like to understand which documents are the closest match to the topic and which are the least. I would like to generate a similarity index for each document in the data frame based on the topic it was assigned to. Is there a way to do that?

**Comment by MaartenGr** [comment]
There are a couple of ways to do that:

* Calculate the similarity between document embeddings and topic embeddings
* Calculate similarity between document c-TF-IDF and topic c-TF-IDF 

In practice, the first would be the easiest to perform yourself by simply calculating the cosine similarity between the input embeddings and `topic_model.topic_embeddings_`. 

The second is a bit more involved but fortunately has an easy solution with [`.approximate_distribution`](https://maartengr.github.io/BERTopic/getting_started/distribution/distribution.html) which gives a sense of how much a document is about a certain topic.

**Comment by bhutkie** [comment]
Hi Maarten, 
Another question..
I have also tried using 'similarity' value from topic_model.find_topics method to reclassify (and rank) each document to the topics. How does the algorithm calculates 'similarity' value because I am getting a different Topic as higher similarity than what was assigned during generating the clusters-topics? I am actually getting more relevant results, once I reassign them. Will that be a valid process?  ** my clustering algorithm is k means.

**Comment by MaartenGr** [comment]
@bhutkie What is happening is that the documents are converted to embeddings and the cosine similarity is then taken between the document and topic embeddings. The ones with the highest score will then be chosen. Sure, it would be reasonable to go that route. Do note though that if you save and load the model with `safetensors`, the internal `.transform` function will do just that and a bit more efficiently.

**Comment by bhutkie** [comment]
Thanks for your prompt reply! its clear now. :) .
This whole 'Issues' board with your solutions to the issues, has been super helpful
