### ISSUE TITLE
MMR doesn't work in multi aspect with no 'Main'

### ISSUE THREAD

**Issue by zilch42** [MaartenGr/BERTopic#1505]
Hi Maarten, 

This is related to #1320. I was interested in the same end (getting multiple representations while keeping the original c-tf-idf representation). I took your advice provided there but it seems that when I include MMR in a representation model without a 'Main' model, the MMR representation output is identical to the main output. i.e. diversification doesn't occur. See three examples below:

# Standard representation (None)

```
from bertopic.representation import KeyBERTInspired
from bertopic.representation import MaximalMarginalRelevance
from sklearn.datasets import fetch_20newsgroups
from bertopic import BERTopic
from umap import UMAP

# Documents to train on
docs = fetch_20newsgroups(subset='all',  remove=('headers', 'footers', 'quotes'))['data']

umap_model = UMAP(n_neighbors=15, n_components=5, min_dist=0.0, metric='cosine', random_state=42)
representation_model = None
topic_model = BERTopic(umap_model=umap_model, representation_model=representation_model).fit(docs)

topic_model.get_topic_info()
```
![Standard](https://github.com/MaartenGr/BERTopic/assets/39004650/eeb38a83-df13-46e1-945b-acc0e7108326)

# MMR (diversity = 0.4)

```
representation_model = MaximalMarginalRelevance(diversity=0.4)

topic_model = BERTopic(umap_model=umap_model, representation_model=representation_model).fit(docs)

topic_model.get_topic_info()
```
![MMR](https://github.com/MaartenGr/BERTopic/assets/39004650/ee681f59-a7d7-43ed-8b62-45319d556e16)

# Multi-Aspect without Main

```
representation_model = {
                    'KeyBert': KeyBERTInspired(random_state=42),
                    'KeyBertMMR': [
                        KeyBERTInspired(top_n_words=30, random_state=42), 
                        MaximalMarginalRelevance(diversity=0.4)],
                    'MMR': MaximalMarginalRelevance(diversity=0.4)
                }

topic_model = BERTopic(umap_model=umap_model, representation_model=representation_model).fit(docs)

topic_model.get_topic_info()
```
![Multi](https://github.com/MaartenGr/BERTopic/assets/39004650/1ae89213-2b95-4b18-8c7b-e4b09a406aa8)

The MMR representation here should be the same as the MMR (diversity = 0.4) representation above, but instead it is the same as the standard representation. 

Sorry if I'm going mad and doing something wrong

**Comment by MaartenGr** [comment]
I believe you should set the `top_n_words` higher when instantiating BERTopic. I think that it is an order issue in BERTopic, namely that `top_n_words` is applied to the multi-aspects but not to the direct representations. Either way, increasing `top_n_words` to something like 30 should solve your issue!

**Comment by zilch42** [comment]
Thanks Maarten! I don't fully understand why that works, but it works so that's good enough for now!
