### ISSUE TITLE
Sentence tokenisation & embeddings

### ISSUE THREAD

**Issue by fcndata** [MaartenGr/BERTopic#1506]
Hi Marteen,

I have been working with BERTopic using roBERTa for the embeddings, and is extremely powerful.

However, I feel I can improve my tokenizing; using the 'punkt' tokenizer from nltk feels awkward as I lose the context of the whole paragraph. Having said that,  how do you suggest I do it?

To give you some context, I'm working with Reddit, so most of the comments are not too extensive. 

Thanks!

**Comment by MaartenGr** [comment]
When you refer to the tokenization, do you mean with respect to the CountVectorizer or when the input documents are converted to embeddings? Also, why are you looking to improve the tokenization? That helps me understand what kind of improvements you are looking for.
