### ISSUE TITLE
Loading saved topic model with custom embedding model

### ISSUE THREAD

**Issue by zilch42** [MaartenGr/BERTopic#1522]
Hi Maarten, 

I have a whole bunch of embedding models saved locally, and not all of them are sentencetransformer models so I'm using custom classes for all of them. I'm having trouble when I save a topic model, reload it and try and load the custom embedding model again. 

It looks like BERTopic originally accepts the custom model straight up:

https://github.com/MaartenGr/BERTopic/blob/004d828bf892d2c1316646dbb25e3cdbc97e0779/bertopic/_bertopic.py#L217C11-L217C11

Whereas when the model was reloaded it uses `select_backend` which doesn't handle my custom classes. 

https://github.com/MaartenGr/BERTopic/blob/004d828bf892d2c1316646dbb25e3cdbc97e0779/bertopic/_bertopic.py#L3012C58-L3014C73

Even though it can find the models locally it's either re-downloading them if they-re sentence transformer models or creating empty blank ones with mean pooling if they're transformer models. 

Can `load()` be made to handle taking an embedding model directly?

Here's an example of a custom class. Sorry I don't have a full reprex. If you need one let me know. It seemed a bit complex with local saved models. 

```
class InstructorEmbedder(BaseEmbedder):
    """Instructor embedding model"""
    def __init__(self, model, device=None):
        """:param model: Not currently used"""
        super().__init__()
        self.device = device
        self.model = model
        self.embedding_model = INSTRUCTOR('hkunlp/instructor-large')

    def embed(self, documents, verbose=True, device=None):
        """
        Calculate document embeddings 
        :param documents: List of documents to embed 
        :param device: String of device name to use e.g. "cpu", "cuda".
        :param verbose: Logical 
        :return: ndarray of embeddings 
        """
        if device is None:
            device = self.device
        
        # add query to texts 
        texts_with_instructions = []
        for d in documents:
            text_type = "sentence" if len(TextBlob(d).raw_sentences) == 1 else "paragraph"
            instruction = "Represent the Science {} for clustering: ".format(text_type)
            texts_with_instructions.append([instruction, d])

        # calculate embeddings
        embeddings = self.embedding_model.encode(texts_with_instructions, show_progress_bar = verbose, device = device)
        
        return embeddings 
```

**Comment by MaartenGr** [comment]
> It looks like BERTopic originally accepts the custom model straight up:

Yes and no. Although it does accept it straight up during the `init`, when you run `fit` or `fit_transform` it is assigned using `select_backend`. 

> Can load() be made to handle taking an embedding model directly?

It already is. If you give it a model that inherits from `BaseEmbedder`, then it should choose that model in the `select_backend`:

https://github.com/MaartenGr/BERTopic/blob/004d828bf892d2c1316646dbb25e3cdbc97e0779/bertopic/backend/_utils.py#L77-L79

If that does not work, could you give me the full code? Otherwise, it is difficult to know what exactly we are dealing with here.

**Comment by zilch42** [comment]
Fair point. Ok here is a reprex, and I've figured out where my issue lies. It will take the custom model in `load` as long as I haven't included it in `save`. 

See this example using a transformers model. Don't worry about the "Some weights of the model checkpoint at KM4STfulltext/SSCI-SciBERT-e2 were not used when initializing BertModel..." message that you may get running this. That's not the focus of this issue.

Generating and saving the model 
```
from sklearn.datasets import fetch_20newsgroups
from bertopic import BERTopic
import numpy as np
import pandas as pd
from bertopic.backend import BaseEmbedder
from sentence_transformers import SentenceTransformer
from transformers import AutoTokenizer, AutoModel
import torch

def batch_embeddings(iterable, n=1):
    """Breakup embeddings into batches
    :param iterable: iterable object e.g. a list
    :param n: int batch size 
    :return: iterable
    """
    l = len(iterable)    
    for ndx in range(0, l, n):
        yield iterable[ndx:min(ndx + n, l)]


class TransformerEmbedder(BaseEmbedder):
    """Hugging face transformer embedder class"""
    def __init__(self, model, device=None):
        """:param model: str model name or path to model"""
        super().__init__()
        self.device = device
        self.model = model
        self.tokenizer = AutoTokenizer.from_pretrained(model)
        self.embedding_model = AutoModel.from_pretrained(model)

    def embed(self, documents, verbose=True, device=None):
        """Calculate document embeddings 
        :param documents: List of documents to embed 
        :param device: String of device name to use e.g. "cpu", "cuda".
        :param verbose: Logical 
        :return: ndarray of embeddings 
        """
        
        print("embedding with my custom model")

        if device is None:
            device = self.device
        if device is None:
            device = "cuda:0" if torch.cuda.is_available() else "cpu"
            
        self.embedding_model = self.embedding_model.to(device)
            
        # TODO can or something Flair handle this?
        def mean_pooling(model_output, attention_mask):
            token_embeddings = model_output[0] #First element of model_output contains all token embeddings
            input_mask_expanded = attention_mask.unsqueeze(-1).expand(token_embeddings.size()).float()
            sum_embeddings = torch.sum(token_embeddings * input_mask_expanded, 1)
            sum_mask = torch.clamp(input_mask_expanded.sum(1), min=1e-9)
            return sum_embeddings / sum_mask
        
        embeddings = []
        for d in batch_embeddings(documents, 16):     
            
            # fix document format if required 
            if isinstance(documents, np.ndarray) or \
                isinstance(documents, pd.Series) or \
                isinstance(documents, str):
                documents.tolist()

            # Tokenize sentences
            encoded_input = self.tokenizer(
                d, 
                padding=True, 
                truncation=True, 
                max_length=512, 
                return_tensors='pt').to(device)

            # Compute token embeddings
            with torch.no_grad():
                model_output = self.embedding_model(**encoded_input)

            # Perform pooling. In this case, mean pooling
            embeddings.append(mean_pooling(model_output, encoded_input['attention_mask']).detach().cpu().numpy())

        return np.vstack(embeddings) 
    

# Documents to train on
docs = fetch_20newsgroups(subset='all',  remove=('headers', 'footers', 'quotes'))['data'][0:200]

embedding_model = TransformerEmbedder("KM4STfulltext/SSCI-SciBERT-e2")

topic_model = BERTopic(embedding_model = embedding_model, verbose=True).fit(docs)
topic_model.save("example_model/", "safetensors", "KM4STfulltext/SSCI-SciBERT-e2")   # here's my problem

topic_model.get_topic_info()
```

Loading the model:
```
from bertopic import BERTopic
from sklearn.datasets import fetch_20newsgroups
from bertopic.representation import KeyBERTInspired

docs = fetch_20newsgroups(subset='all',  remove=('headers', 'footers', 'quotes'))['data'][0:200]

embedding_model = TransformerEmbedder("KM4STfulltext/SSCI-SciBERT-e2")

topic_model = BERTopic.load("example_model/", embedding_model=embedding_model)
topic_model = topic_model.update_topics(docs, representation_model=KeyBERTInspired())
```
```
No sentence-transformers model found with name [C:\Users\ABB064/.cache\torch\sentence_transformers\KM4STfulltext_SSCI-SciBERT-e2.](file:///C:/Users/ABB064/.cache/torch/sentence_transformers/KM4STfulltext_SSCI-SciBERT-e2.) Creating a new one with MEAN pooling.
```

Rather than taking the embedding model provided it has assumed that the name of the model that was saved with the topic model during `save` was the name of a `sentence_transformers model` and tried to load that. 

I can solve my problem by not saving the embedding_model name with the topic model, and I note that the docs for `load` do state that the `embedding_model` can be provided "if it was not saved in the BERTopic model file or directory". It's up to you, but I think this is a bit unintuitive and limits flexibility. I would have expected that if `embedding_model` was provided in `load` it should supersede anything saved with the topic model, because it is explicitly provided. 

Another use case for this just with sentence transformers is changing the device of the `sentence_transformer` model after loading the topic model. I have been training some topic models on a larger GPU then transferring them back to my local machine which only has a GPU with 2GB vRAM. Some of my sentence_transformer models haven't fit in that ram but I have been unable to reload them with `device="cpu"` because `load` has just been taking the model name from the saved topic model and creating a new embedding model with the default `device=None`, rather than taking the embedding_model that I pass to `load`. 

If you want a reprex for that use case let me know

**Comment by MaartenGr** [comment]
> topic_model.save("example_model/", "safetensors", "KM4STfulltext/SSCI-SciBERT-e2")   # here's my problem

This will indeed not work since saving the embedding model can only be done as a pointer used in SentenceTransformers. Anything else is not supported since that would require saving the original code, which compared to safetensors, is relatively unsafe. 

So it would be assumed that whatever was passed to `embedding_model` during save would be the same as it would during load since it only supports sentencetransformers. 

Having said that, it could be changed from this:

https://github.com/MaartenGr/BERTopic/blob/58d90bc65e95a11718e63a0834809d156dcf431d/bertopic/_bertopic.py#L3012-L3014

to this to make it less strict:

```python
# Replace embedding model if one is specifically chosen
if embedding_model is not None:
    topic_model.embedding_model = select_backend(embedding_model)
```

However, it would introduce some difficulties if the user provided a different embedding model than it was originally trained on. This could cause errors if, for example, the dimensions of the generated embeddings differ.

**Comment by zilch42** [comment]
That's true. I'll just keep away from saving the model name. Thanks
