### ISSUE TITLE
Frequency in topic over time chart

### ISSUE THREAD

**Issue by randomrdrand** [MaartenGr/BERTopic#154]
There is no clear explanation of what frequency is being counted. Is it the frequency of documents that are mentioning certain topics over time? or is it the frequency of the topic that is being mentioned (even in one document several times)?

**Comment by MaartenGr** [comment]
In the calculation of `topics_over_time` the frequency of documents in a topic is counted. Here, only a hard clustering is counted. In other words, each document is assigned to a single topic at a single timestep *t*. Each document can only be counted towards a single topic at a single timestep *t*. 

Hopefully, this clears things up a bit. Let me know if you have any further questions!

**Comment by randomrdrand** [comment]
Yes you did thank you for your time and help

**Comment by randomrdrand** [comment]
I have another question, As i understood BERTopic uses transformers architerture (encoder-decoder). At the same time it uses UMAP for dimension reduction and HDBSCAN for clustering. Is it correct to say that the encoder is doing the UMAP part and the decoder is doing the HDBSCAN part?

**Comment by MaartenGr** [comment]
Hmmm, I wouldn't phrase it like that. You can view UMAP and HDBSCAN as lego blocks that help understand/expose the underlying structure of potential clusters. The encoder-decoder architecture is quite different from that since it tries to extract features from something and then recreate that something (in a very shallow nutshell). Personally, I would prevent using the encoder-decoder term for the UMAP + HDBSCAN part of the algorithm. Below is an overview of the major components of the algorithm and you can find the description of it [here](https://maartengr.github.io/BERTopic/tutorial/algorithm/algorithm.html). 

![image](https://user-images.githubusercontent.com/25746895/123219721-81714380-d4cd-11eb-8ce1-a91170fde834.png)

**Comment by randomrdrand** [comment]
> Hmmm, I wouldn't phrase it like that. You can view UMAP and HDBSCAN as lego blocks that help understand/expose the underlying structure of potential clusters. The encoder-decoder architecture is quite different from that since it tries to extract features from something and then recreate that something (in a very shallow nutshell). Personally, I would prevent using the encoder-decoder term for the UMAP + HDBSCAN part of the algorithm. Below is an overview of the major components of the algorithm and you can find the description of it [here](https://maartengr.github.io/BERTopic/tutorial/algorithm/algorithm.html).
> 
> ![image](https://user-images.githubusercontent.com/25746895/123219721-81714380-d4cd-11eb-8ce1-a91170fde834.png)

Thus the encoder-decoder architecture is just responsible for the embedding in general? or do they do specific roles during the embedding process?

**Comment by MaartenGr** [comment]
Yes, the transformer architecture is only responsible to construct the embeddings. They construct both the document embeddings as well the word embeddings when creating the topic representations. Since word embeddings are needed for MMR, the candidate topic representations are embedded.

**Comment by doubianimehdi** [comment]
> In the calculation of `topics_over_time` the frequency of documents in a topic is counted. Here, only a hard clustering is counted. In other words, each document is assigned to a single topic at a single timestep _t_. Each document can only be counted towards a single topic at a single timestep _t_.
> 
> Hopefully, this clears things up a bit. Let me know if you have any further questions!

I'm having a hard time understanding this normalization process, i've seen in the code that you use normalize from scikit learn and reshape the frequency values column but i don't know what the end result means ... could you explain more ? thanks !!!
