### ISSUE TITLE
Is there a way to send a different document to LLM representation models?

### ISSUE THREAD

**Issue by zilch42** [MaartenGr/BERTopic#1545]
Hi Maarten, 

Related to #1527 and #1539, 

Depending on the topic, I sometimes find that LLM representations can focus too much on the content of an individual representative document rather than the topic as a whole (I know that's been noted in another issue too but I can't find it). 

I have a theory (still untested) that sending more short documents would be better than sending fewer longer documents. E.g. if working with journal abstracts which can be 100s of words (my doc is generally the title and abstract concatenated together), sending 10 titles + keywords to the LLM may produce a better result than 3 representative docs + keywords. 

Is there a way I can do this? I see that `update_topics` takes a `docs` parameter so I could pass the titles in there, but I think that will also recalculate the keywords and I would like to keep the keywords as being calculated from titles and abstracts. 

Short of providing `docs` directly too a `representation_model`, the other way I thought of doing this was concatenating the title and abstract with some sequence of characters that I could use to split and truncate on with `doc_length = 1`. Would that be the best way to go? If so, the `decode` and `encode` instructions that you mentioned in the PR #1539 would be handy. 

Cheers

**Comment by zilch42** [comment]
Ah just found the examples for a custom tokenizer in your updated code.

**Comment by MaartenGr** [comment]
I might add the option to provide a list of custom strings to the LLM in the future that can be accessed with the `[LIST]` tag in the prompt but that would require those strings to be saved internally. I believe that for now, you can indeed use the custom tokenizer.

**Comment by zilch42** [comment]
Yep, I've been doing that today and thats working for me so far!
