### ISSUE TITLE
small dataset and n_grams

### ISSUE THREAD

**Issue by frasercrichton** [MaartenGr/BERTopic#1553]
Hi Maarten,

I'm afraid I'm new to topic modelling so forgive me if this a question that's come up before.

If I give you some context it may help. My dataset isn't very large as it's examining the TikTok account of a far-right politician in Italy who has only 225 posts. I've transcribed and translated the audio from their account and I've parsed each post into a list of sentences for topic modelling in BertTopic. One thing I've come across is that 'brothers of Italy' is one of the terms I'd expect to see a topic around.

I think the combination of stop words and ngram in the CountVectorizer might impact this. My CountVectorizer looks like this:

```
count_vectorizer_model = CountVectorizer(ngram_range=(1, 3), stop_words="english")
```

Would this be an edge case where some preprocessing might actually be a good thing? So say replace  'brothers of Italy' with brothers-of-Italy' in the text. 

Any other advice on working with a small set of data would be great - thanks!

**Comment by MaartenGr** [comment]
That is indeed a result of removing stop words before creating the topic representations. Here, it might be worthwhile to keep the stopwords in order to still have brother of Italy, or, as you suggested, use brothers-of-italy instead. If you remove stopwords, then it might still be worthwhile to use something like [KeyBERTInspired](https://maartengr.github.io/BERTopic/getting_started/representation/representation.html#keybertinspired) to fine-tune the representations.

**Comment by frasercrichton** [comment]
Brilliant - thanks Maarten! I went through some of the doco in more detail including adding an OpenAI prompt model which seemed to work well as it recognised the Brothers of Italy. I'll have a look at KeyBERTInspired next and refine things a bit more. It's a pretty amazing toolbox so thanks for this.

**Comment by frasercrichton** [comment]
Hi Maarten,

A quick follow-up question I'm afraid - I know you must be busy.

I've now got a basic Topic Model and I'm about to start refining it by maybe merging some of the topics that are close to each other on the Similarity Matrix. I was looking at the Document Visualisation last night and there's a bit of drift with some of the topics. I am sure this won't be a surprise as the model uses sentences without any context so I see some topics that aren't present in the original TikTok post.     

I've only a couple of hundred posts and I'm wondering if maybe labelling them so I could use a [supervised](https://maartengr.github.io/BERTopic/getting_started/supervised/supervised.html
) approach might help? But that does feel a bit counter-intuitive.  

Another thing I've noticed is that apostrophes seem to split words so there are a few weird outliers. 

Have been using [KeyBERTInspired](https://maartengr.github.io/BERTopic/getting_started/representation/representation.html#keybertinspired) and not removing stopwords initially and it seems great apart from the minor niggles.

**Comment by MaartenGr** [comment]
> I've now got a basic Topic Model and I'm about to start refining it by maybe merging some of the topics that are close to each other on the Similarity Matrix. I was looking at the Document Visualisation last night and there's a bit of drift with some of the topics.

I am not sure if I understand you correctly. What do you mean by `a bit of drift`? Do you mean that certain documents are not labeled?

>  I am sure this won't be a surprise as the model uses sentences without any context so I see some topics that aren't present in the original TikTok post.

Could you give a concrete example of `some topics that aren't present in the original TikTok post`? It is not entirely clear to me what you mean by that. Are the labels not correct? 

> Another thing I've noticed is that apostrophes seem to split words so there are a few weird outliers.

That is a result of the tokenizer. You can change the way it does splitting in the `CountVectorizer`.

**Comment by frasercrichton** [comment]
Sorry, yes, bit hard to explain without context.

By drift, I mean that some of the topics contain documents that don't appear to have anything to do with the topic. So for instance when I look at the documents in `visualize_documents() ` under the topic of **immigration_migrants_refugees** :

![Screenshot 2023-10-06 at 10 44 38 AM](https://github.com/MaartenGr/BERTopic/assets/52700324/8e67a593-e68f-4bcb-a26a-696bbf2d3a8a)

The topic accurately identifies documents (sentences) with the words **immigrant**, **trafficker**, etc. but there are a few weird inclusions like:

'Pets are part of the family in every respect and Fratelli D'Italia intends to fight to guarantee them a dignified and loving life among our initiatives already launched in this legislature.'

which has nothing to do with immigration obviously. I'd not expect 100% accuracy and there aren't many of these instances but it seems a bit odd.

**Comment by frasercrichton** [comment]
Fixed this by tweaking the seed topics.
