### ISSUE TITLE
Extracting colored cluster assignments from hierarchy tree

### ISSUE THREAD

**Issue by mjmacarthur** [MaartenGr/BERTopic#1558]
When creating the hierarchy visualization, is there any way to extract information about which colored cluster a topic belongs to? I would like to add another column to the topic info summary table with a value indicating the cluster assignment. To be clear, I’m not looking for something indicating the color itself, since they repeat sometimes – I’d like each group identified.

**Comment by MaartenGr** [comment]
I believe that is currently not possible. The colors are created through Plotly's `ff.create_dendrogram` which is controlled by the `color_threshold` parameter. I personally would stick with the distance measures defined in the resulting dataframe instead to identify the clusters. It is essentially the same procedure.

**Comment by mjmacarthur** [comment]
Thank you for your response! The dataframe resulting from building the hierarchy tree gave me the information I needed.

**Comment by MaartenGr** [comment]
Glad to hear you resolved it!
