### ISSUE TITLE
Cleaning data?

### ISSUE THREAD

**Issue by drob-xx** [MaartenGr/BERTopic#156]
I have a corpus of congressional press releases. The data has been thoroughly processed with NERs, POS, and lemmatizations. I have also created stopwords particular to the corpus as well as created common bi and trigrams (some of which can be removed from the text - e.g. "press_release").  However, when I started to run tests using cleaned up data I got very poor results (topic creation went haywire with hundreds of essentially empty, duplicated topics).  It is apparent that I don't yet understand what the sentence transformer is really doing or what it expects as input. Should I be looking to clean up the corpus beyond the absolute basics? What do I do about congressional "noise" terms? For example It turns out that congressmembers love to have their names plastered all throughout their press releases. When I run the data leaving them in I get many topics that include them. What about ngrams that seem important (e.g. "health_care")? Should I just be leaving this work to the algorithms, or should I be proactive? From what I can tell extensive "cleaning" of the data going in results in absolute garbage coming out, is there a happy medium? I'm happy to study up on my own, but I am having trouble finding sources for this kind of info, references appreciated! Thanks in advance!

**Comment by MaartenGr** [comment]
In general, you do not need to clean any data (see the [FAQ](https://maartengr.github.io/BERTopic/faq.html#should-i-preprocess-the-data)). It is even suggested not to do so as the embedding techniques expect nicely written text. For example, sentences make little sense when you remove stopwords or create n-grams. Even lemmatizations can actually hurt the quality of the embeddings that are being generated. Transformer-based models typically work great on nicely-written text, so anything you do that makes it more difficult to read will actually hurt the resulting topics.  

I would advise you to not clean the data at all except if you find HTML tags and the like in them.

**Comment by drob-xx** [comment]
Thanks so much Maarten, that is what I expected. I'm not sure how I missed the FAQ, but again, thanks.

**Comment by RamyTheEngineer** [comment]
> In general, you do not need to clean any data (see the [FAQ](https://maartengr.github.io/BERTopic/faq.html#should-i-preprocess-the-data)). It is even suggested not to do so as the embedding techniques expect nicely written text. For example, sentences make little sense when you remove stopwords or create n-grams. Even lemmatizations can actually hurt the quality of the embeddings that are being generated. Transformer-based models typically work great on nicely-written text, so anything you do that makes it more difficult to read will actually hurt the resulting topics.
> 
> I would advise you to not clean the data at all except if you find HTML tags and the like in them.

M. Maarten, I have one particular use case, where the data is a set of customer service emails. I retrieved the body of the emails.

My approach is the following:
1-Remove urls and hashtags.
2-Remove greetings, signatures and disclaimers.
3-Contraction replacement: "didn't" -> "did not"
4-Split attached words: "ForTheWin" -> "For the win"
5-Convert to lower case
6-Standardizing and spell check: "I missss this" -> "I miss this"
7-Remove slang words.
8-Remove punctuations.


Can you please advise on what steps are to be avoided or not necessary in my data cleansing approach?

**Comment by MaartenGr** [comment]
@RamyTheEngineer It is difficult to say without full confidence since it also depends on the underlying embedding model, the representation model, etc. And even then, trying out some of the above might unexpectedly help. There have been users stating that some preprocessing worked actually quite well for their use cases but not for others. 

In practice, if you are using a transformer-based embedding model, such as the default, then steps 3, 5, and 8 are generally not necessary. There can be discussions about the others but that depends on the underlying embedding model. I would advise reading through the specifics of your embedding model and how that works.
