### ISSUE TITLE
Mismatching between topics and probabilities

### ISSUE THREAD

**Issue by SunnyXu1** [MaartenGr/BERTopic#157]
Hi Maarten,

I have a question about the function **_fit_transform()_**. In this function, after getting the list of topics and corresponding probabilities generated by HDBSCAN, there is a step called "Sort and Map Topic IDs by their frequency":

```
# Sort and Map Topic IDs by their frequency
if not self.nr_topics:
    documents = self._sort_mappings_by_frequency(documents)

```
However, in this step, only the topics are sorted, and the probabilities are still in the original order. This might lead to the mismatching between topics and probabilities. I think there should be another step to map the sorted topics and their corresponding probabilities. Here are some sample codes for this additional step:

```
probabilities_ = np.zeros(probabilities.shape)
for j in range((np.max(list(topic_model.mapped_topics.keys())) + 1)):
    probabilities_[:, topic_model.mapped_topics[j]] = probabilities[:, j]
```

Hope this helps! By the way, if there exists such step in the original codes, please let me know. Thank you very much!

**Comment by MaartenGr** [comment]
Thank you for the extensive description! This is an issue that was mentioned before [here](https://github.com/MaartenGr/BERTopic/issues/146) that indeed will be corrected in a future version. As of right now, I would follow along with that issue to make sure you have the correct probabilities. I hope to have fixed this in the coming week but it might take a bit longer as it will require significant testing.

**Comment by MaartenGr** [comment]
@SunnyXu1 The new release of BERTopic ([v0.9](https://maartengr.github.io/BERTopic/changelog.html#version-09)) should fix this issue. I am closing this for now. However, if you run into any issues, please let me know!
