### ISSUE TITLE
Azure OpenAI embeddings

### ISSUE THREAD

**Issue by Ioannis-Pikoulis** [MaartenGr/BERTopic#1577]
Azure OpenAI embeddings requires `engine` or `deployment_id` to be passed as extra parameters. This is not supported by the current embedder class.

**Comment by Ioannis-Pikoulis** [comment]
Azure OpenAI embedding models require `deployment_id` or `engine` as extra argument. This is not taken into consideration with the current implementation of the embedder classes

**Comment by MaartenGr** [comment]
Could you show the error you are getting and an example of the code you are trying to run? It makes it easier for me to reproduce if I have an example. That way, I can go a bit more in-depth into what the necessary changes might be. Please make sure to provide a full example. Which version of BERTopic are you using? Are you using BERTopic from its main branch? Etc.
