### ISSUE TITLE
"permanent" install of bertopic in colab

### ISSUE THREAD

**Issue by drob-xx** [MaartenGr/BERTopic#158]
I'm trying to install bertopic to my gdrive so that I can just link to it when I start a new colab session instead of having to import it fresh every time. When I attempt to import bertopic I'm getting the error message:

DistributionNotFound: The 'pynndescent' distribution was not found and is required by the application

Yet pynndescent is installed in the gdrive directory - I've installed, uninstalled, re-installed and upgraded, all successfully, The files all seem like they are in the correct directory etc.  I've installed, get a success report (with some warnings about libraries that are incmpatible with tensorflow, then rebooted the instance and re-set my variables. Yet when I try to import pynndescent directly or attempt to import bertopic it reports that pynndescent is not installed. In addition to pynndescent I had to install hdbscan and anoher package, all worked without a problem (afaik). On the web I found a reference to this problem on [stackflow](https://stackoverflow.com/questions/66886819/the-pynndescent-distribution-was-not-found-and-is-required-by-the-application) but the solution involves changing the order of some code execution that I don't see how it applies to my situation. I figure some folks have likely done this already in their work. Any hints appreciated.

**Comment by MaartenGr** [comment]
Unfortunately, this is something I have not done before as I simply use `!pip install bertopic` each time I use a new Google Colab session since it also makes sure I have the newest version of the package. I did find something [here](https://stackoverflow.com/questions/55253498/how-do-i-install-a-library-permanently-in-colab) but I am afraid I cannot be of much use here.

**Comment by drob-xx** [comment]
Yup. The link you pointed to is exactly what I'm doing. It works but that one package won't install correctly. Doing an import every session isn't a huge problem - it would just be a bit cleaner not to bother. Although, you make a point about guaranteeing the latest version of BERTopic. I'll leave this open for a couple of days to see if anyone else has a solution and then I'll close it. Thanks for taking the time to read through.
