### ISSUE TITLE
Comparing tf-idf and mmr

### ISSUE THREAD

**Issue by maticar92** [MaartenGr/BERTopic#1587]
I want to compare the difference between tf-idf represenations and mmr represenations but when I add mmr as a representation model it replaces the tf-idf represenations. How can i see them side by side like in 6C. Multiple Representations

**Comment by MaartenGr** [comment]
6C describes that for alternative representations, you would need not using the "Main" key. So, the code would be as follows:

```python
from bertopic.representation import MaximalMarginalRelevance

mmr = MaximalMarginalRelevance(diversity=.5)
representation_model = {
   "mmr":  mmr
}
topic_model = BERTopic(representation_model=representation_model)
```

This way, the "mmr" representation model will be run alongside the c-TF-IDF representations. Note that we are running c-TF-IDF as a default and not TF-IDF.
