### ISSUE TITLE
InvalidRequestError when using OpenAI Embedding APIs

### ISSUE THREAD

**Issue by Annette0127** [MaartenGr/BERTopic#1594]
Hi @MaartenGr,

I encountered an issue while trying to run the example code for the OpenAI Embedding APIs from the [BERTopic documentation](https://maartengr.github.io/BERTopic/getting_started/embeddings/embeddings.html#openai).

Error Message:
```
openai.error.InvalidRequestError: '$.input' is invalid. Please check the API reference: https://platform.openai.com/docs/api-reference.
```

Source Code:
```
from sklearn.datasets import fetch_20newsgroups

docs = fetch_20newsgroups(subset='all', remove=('headers', 'footers', 'quotes'))['data']
openai.api_key = "sk-..."
embedding_model = OpenAIBackend("text-embedding-ada-002", delay_in_seconds=1, batch_size=1)
topic_model = BERTopic(embedding_model=embedding_model)
topics, probs = topic_model.fit_transform(docs)
```

I was wondering whether you'll have any insights into why this issue occurs and potential solutions to fix it? Any assistance would be greatly appreciated. Thanks in advance!

**Comment by MaartenGr** [comment]
Did you check whether one of the documents was empty? I believe that might be the cause of the error.

**Comment by Annette0127** [comment]
Thank you for the guidance, the issue has been resolved! There are empty strings in the example dataset indeed. :)
