### ISSUE TITLE
ImportError: cannot import name 'BERTopic' from partially initialized module 'bertopic'

### ISSUE THREAD

**Issue by shyzzz521** [MaartenGr/BERTopic#1595]
ImportError: cannot import name 'BERTopic' from partially initialized module 'bertopic'

Why is that?

**Comment by MaartenGr** [comment]
It's difficult to say without knowing a bit more context but generally, this is due to your environment. Start from a fresh environment and install BERTopic there.

**Comment by shyzzz521** [comment]
Thank you. I'll try

**Comment by shyzzz521** [comment]
> It's difficult to say without knowing a bit more context but generally, this is due to your environment. Start from a fresh environment and install BERTopic there.

pip install bertopic

I reinstalled bertopic, and again this error occurred

ImportError: cannot import name 'BERTopic' from partially initialized module 'bertopic'

**Comment by shyzzz521** [comment]
> It's difficult to say without knowing a bit more context but generally, this is due to your environment. Start from a fresh environment and install BERTopic there.



> It's difficult to say without knowing a bit more context but generally, this is due to your environment. Start from a fresh environment and install BERTopic there.

I re-created the Conda environment and re-installed bertopic, but still reported an error:
ImportError: cannot import name 'BERTopic' from partially initialized module 'bertopic' (most likely due to a circular import)

**Comment by MaartenGr** [comment]
Could you share how you re-created the Conda environment and how you re-installed BERTopic? Also, did you try to import it in a notebook? If so, did you make sure to select the correct kernel? Lastly, do you by chance have a folder named 'bertopic'?

**Comment by shyzzz521** [comment]
> Could you share how you re-created the Conda environment and how you re-installed BERTopic? Also, did you try to import it in a notebook? If so, did you make sure to select the correct kernel? Lastly, do you by chance have a folder named 'bertopic'?

Thank you for your prompt and helpful suggestion. The problem has been resolved. It turns out that I made a naming mistake. Sorry for the inconvenience caused.

**Comment by MaartenGr** [comment]
No problem! Glad I could help.
