### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'embed_documents'

### ISSUE THREAD

**Issue by shyzzz521** [MaartenGr/BERTopic#1601]
Hi, sorry to bother you.
I have generated some embeddings myself, and the input format is np.array([
[],[],[]
]). However, I encountered an error. Could you please explain why this happened?

Traceback (most recent call last):
  File "/home/labels/bertopic11.py", line 43, in <module>
    topic = topic_model.fit_transform(docs, embeddings)
  File "/home/hdpconda/envs/bertos/lib/python3.10/site-packages/bertopic/_bertopic.py", line 411, in fit_transform
    self._extract_topics(documents, embeddings=embeddings)
  File "/home/hdpconda/envs/bertos/lib/python3.10/site-packages/bertopic/_bertopic.py", line 3296, in _extract_topics
    self.topic_representations_ = self._extract_words_per_topic(words, documents)
  File "/home/hdpconda/envs/bertos/lib/python3.10/site-packages/bertopic/_bertopic.py", line 3570, in _extract_words_per_topic
    topics = self.representation_model.extract_topics(self, documents, c_tf_idf, topics)
  File "/home/hdpconda/envs/bertos/lib/python3.10/site-packages/bertopic/representation/_keybert.py", line 91, in extract_topics
    sim_matrix, words = self._extract_embeddings(topic_model, topics, representative_docs, repr_doc_indices)
  File "/home/hdpconda/envs/bertos/lib/python3.10/site-packages/bertopic/representation/_keybert.py", line 163, in _extract_embeddings
    repr_embeddings = topic_model._extract_embeddings(representative_docs, method="document", verbose=False)
  File "/home/hdpconda/envs/bertos/lib/python3.10/site-packages/bertopic/_bertopic.py", line 3126, in _extract_embeddings
    embeddings = self.embedding_model.embed_documents(documents, verbose=verbose)
AttributeError: 'NoneType' object has no attribute 'embed_documents'

**Comment by MaartenGr** [comment]
Most likely, you are using a technique that requires an embedding model to be specifically set in when initializing BERTopic. Did you set an embedding model?

**Comment by shyzzz521** [comment]
> Most likely, you are using a technique that requires an embedding model to be specifically set in when initializing BERTopic. Did you set an embedding model?

Thank you for the response.
If i generate my own embeddings, do i still need to set up an embedding model? Does setting it up generate embeddings again? I added an embedding model, and it seems to have run successfully.

**Comment by MaartenGr** [comment]
> If i generate my own embeddings, do i still need to set up an embedding model? Does setting it up generate embeddings again? I added an embedding model, and it seems to have run successfully.

No, it will not run the embeddings again but if you are using word-level methods like KeyBERTInspired, then embeddings for a small subset of words will have to be generated. For that reason, you will need to have set an embedding model.

**Comment by shyzzz521** [comment]
> No, it will not run the embeddings again but if you are using word-level methods like KeyBERTInspired, then embeddings for a small subset of words will have to be generated. For that reason, you will need to have set an embedding model.

Thanks for your reply and for this great project!

My question has been resolved!

**Comment by MaartenGr** [comment]
Glad to hear that the issue is resolved!
