### ISSUE TITLE
ValueError: setting an array element with a sequence - when using guided topic modeling

### ISSUE THREAD

**Issue by ilanit1997** [MaartenGr/BERTopic#1602]
Hello,

I'm encountering an issue with guided topic modeling on different dataset sizes. With a smaller dataset, the same code and same seed topic list work seamlessly. However, when applied to a larger dataset, it fails. 

The specific problem I'm facing is:

`line 385, in fit_transform
    y, embeddings = self._guided_topic_modeling(embeddings)
  File "/home/****/anaconda3/envs/llms_env/lib/python3.9/site-packages/bertopic/_bertopic.py", line 3282, in _guided_topic_modeling
    embeddings[indices] = np.average([embeddings[indices], seed_topic_embeddings[seed_topic]], weights=[3, 1])
  File "/home/****/anaconda3/envs/llms_env/lib/python3.9/site-packages/numpy/lib/function_base.py", line 511, in average
    a = np.asanyarray(a)
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.`

`bertopic == 0.15.0
`

**Comment by MaartenGr** [comment]
I believe this might be related to specific versions of sub-dependencies. Could you share your full code and all versions? Also, have you checked the solutions in other issues posts? I believe this issue was posted a couple of times before.

**Comment by phuclh** [comment]
I have the same issue when using `seed_topic_list`

**Comment by cindy579** [comment]
I also have the same issue when using seed_topic_list. I am using bertopic==0.15.0 &
numpy==1.25.0

**Comment by ilanit1997** [comment]
I use guided topic modeling with one topic related to religion -
`seed_topic_list = ["god", "religion", "church", "faith", "christ"]`

when I debug the function `_guided_topic_modeling` I get see only 2 topics - outliers and the topic from the seed. 
i.e.:
````
def _guided_topic_modeling(self, embeddings: np.ndarray) -> Tuple[List[int], np.array]:
        seed_topic_list = [" ".join(seed_topic) for seed_topic in self.seed_topic_list]
        seed_topic_embeddings = self._extract_embeddings(seed_topic_list, verbose=self.verbose)
        seed_topic_embeddings = np.vstack([seed_topic_embeddings, embeddings.mean(axis=0)])

        sim_matrix = cosine_similarity(embeddings, seed_topic_embeddings)
        y = [np.argmax(sim_matrix[index]) for index in range(sim_matrix.shape[0])]
        y = [val if val != len(seed_topic_list) else -1 for val in y]

        # Average the document embeddings related to the seeded topics with the
        # embedding of the seeded topic to force the documents in a cluster
        for seed_topic in range(len(seed_topic_list)):
            indices = [index for index, topic in enumerate(y) if topic == seed_topic]
            embeddings[indices] = np.average([embeddings[indices], seed_topic_embeddings[seed_topic]], weights=[3, 1])
        return y, embeddings
```

Then 
`np.unique(y) = [-1,  0]`

**Comment by MaartenGr** [comment]
@ilanit1997 @phuclh @cindy579 

The reason why I asked the following:

> I believe this might be related to specific versions of sub-dependencies. Could you share your full code and all versions? Also, have you checked the solutions in other issues posts? I believe this issue was posted a couple of times before.

Is for two reasons:
* First, I expect it to be related to your environment. So knowing **all** versions of the environment might be helpful since I think it might be related to one or more packages.
* Second, this issue is a duplicate. After copy-pasting the error in the search bar on the issues page I found the following two issues that are related: #1309 and #1421

I would highly advise going through those issues since it is likely you will find the answer there.

**Comment by ilanit1997** [comment]
Thank you, you were correct - when looking into previous issues, I found that downgrading numba to 0.56 solved the problem!

**Comment by cosmozhang** [comment]
Downgrade numba to 0.56 works. 0.56.4 is still too high (or maybe the numpy dependency is still too high).
