### ISSUE TITLE
EuclidianDistance error when loading model

### ISSUE THREAD

**Issue by emilbakke** [MaartenGr/BERTopic#1608]
I have trained +1000 models using BERTopic and saved the resulting models to disk in the format .model (all named YYYY-MM-DD.model). Unfortunately, I did not account for the proposed saving procedures when I saved the models to disk using `topic_model.save("bertopic_test/topic_models/{}.model".format(date))`

Now, when loading the topic models to evaluate their topicdiversity with OCTIS, most of the models load fine, but a subset throws the error: `Can't get attribute 'EuclideanDistance' on <module 'sklearn.metrics._dist_metrics' from '/home/ucloud/.local/lib/python3.10/site-packages/sklearn/metrics/_dist_metrics.cpython-310-x86_64-linux-gnu.so'>`

Any ideas on how to fix this? I have tried downgrading scikit-learn to 1.2.0, but getting the same error.

scitkit-learn version = 1.3.2
imbalanced-learn version = 0.11.0
bertopic version = 0.15.0

Here is the code I am running:
```python
import os
from bertopic import BERTopic
from octis.evaluation_metrics.diversity_metrics import TopicDiversity
import pandas as pd
from tqdm import tqdm

model_directory = 'bertopic_test/topic_models'

skipped = []

with open('topic_diversity_eval_skip.txt', 'rb') as f:
    lines = f.readlines()

for line in lines:
    date = line.strip().split()[0].decode('utf-8')
    skipped.append(date)

skipped_dates = []
topic_diversity_scores = []
dates = []

for model_filename in tqdm(os.listdir(model_directory)):
    if model_filename.endswith(".model"):
        if model_filename.split(".")[0] in skipped:
            try:
                date = model_filename.split(".")[0]

                topic_model = BERTopic.load(os.path.join(model_directory, model_filename), embedding_model='distiluse-base-multilingual-cased')

                model_output = {key: value for key, value in topic_model.topic_representations_.items() if key != -1}
                topics = []
                for topic_id, topic_words in model_output.items():
                    top_words = [word for word, _ in topic_words]
                    topics.append(top_words)
                model_output = {'topics': topics}

                metric = TopicDiversity(topk=10) 
                topic_diversity_score = metric.score(model_output)
                topic_diversity_scores.append(topic_diversity_score)
                dates.append(date)
            except Exception as e:
                print(e)
                skipped_dates.append(date)

results_df = pd.DataFrame()
results_df['Date'] = dates
results_df['TopicDiversityScore'] = topic_diversity_scores
results_df.to_csv('topic_diversity_scores_2.csv', index=False)

with open('topic_diversity_eval_skip_2.txt', 'w') as skip_file:
    for date in skipped_dates:
        skip_file.write(f"{date}\n")
```

**Comment by MaartenGr** [comment]
Unfortunately, I have not seen this issue before. It might be worthwhile to check whether other version of scikit-learn might be relevant here. [This](https://stackoverflow.com/questions/76631305/attributeerror-cant-get-attribute-euclideandistance-on-module-sklearn-metr) suggests that you might need 1.2.2 instead. Having said that, it definitely seems like an environment issue.

**Comment by emilbakke** [comment]
Thanks for the swift response! Reverting to scikit-learn 1.2.2 unfortunately did not solve the issue.

I have tried setting up a new virtual environment as well and run the same code with no luck. Unless you mean something else by environment issue?

**Comment by MaartenGr** [comment]
Did you make sure that the new virtual environment was **exactly** the same as where you saved the model? When you pickle a model, it generally wants all packages in the entire environment to be the same.

**Comment by emilbakke** [comment]
I was too quick there, I mistakenly installed scikit-learn 1.3.0 instead of 1.2.2. However, reverting to 1.2.2 after a fresh environment seemed to solve the issue.

Thanks a lot for taking the time to help, and sorry for not being thorough in testing before responding. Also, thanks a lot for your great work with BERTopic!

**Comment by MaartenGr** [comment]
No problem! Glad I could help 😄
