### ISSUE TITLE
nr_topics to utilize doc embeddings instead of topic embeddings

### ISSUE THREAD

**Issue by thisisclement** [MaartenGr/BERTopic#161]
Hello there, thanks for your helpful work using embeddings for topic modelling! It has helped alot in my info processing esp for new data sets!~

I have been running this for some time now and i realised that sometimes the topic words does not most accurately describe the topic. Understand that in the reduction of topics, the topic embeddings are used. In that light, I am wondering if it is possible to instead use the doc embeddings for further reduction of topics based on its similarity?

Thanks!

**Comment by MaartenGr** [comment]
In order to use the document embeddings for reducing the topics, they will have to be either saved within BERTopic or re-generated every time you reduce topics. The former option creates a very large model as the embeddings are quite large in size. The latter is time-consuming as we do not want to recalculate the embeddings every single time. 

To give you a bit of insight into the calculation of the topic vectors. They are created by calculating the weighted average of the word embeddings in a topic representation. For example, if you have a topic with 10 words. Then we extract the word embeddings for all 10 words and average them based on their respective c-TF-IDF score. This will give more emphasis on words that are more important to a topic. 

There are several instances where reduction of topics might actually lead to poor representation of topics. Imagine you have 100 topics that are created. If you reduce them to 90, then there should be enough overlap between topics to merge several of them. However, if you were to reduce them to 10, then you are forcing topics together that might not actually belong together. 

It was a bit longer than I anticipated before writing, but hopefully, this answers your question a bit! If not, or if you have any feedback or interesting solutions, please let me know 😄

**Comment by thisisclement** [comment]
I think I am more keen to save the embeddings into a DB of some sort :) Then access it to compute the similarity. 

Agree to the reduction of topics might lead to poor representation of topics if we use `nr_topics=int`, we might be forcing the documents to cluster when they shouldnt actually belong to a cluster. So far, I like the idea of empirically reducing the topics with `0.9` similarity. I've tried `nr_topics="auto"` to achieve a good balance, just that I would think that using document embeddings might be a better indication of their relation. 

When running it first time, does the embeddings get saved to anywhere? If not, is there a way I access it so that I can save it somewhere for further computation where needed? 

Thanks!

**Comment by MaartenGr** [comment]
The embeddings do not get saved anywhere in order to reduce the size of the model. However, you can adjust the code slightly to save them in the BERTopic class like so:


```python

class BERTopicNew(BERTopic):
    def fit_transform(self,
                      documents: List[str],
                      embeddings: np.ndarray = None,
                      y: Union[List[int], np.ndarray] = None) -> Tuple[List[int],
                                                                       Union[np.ndarray, None]]:
        """ Fit the models on a collection of documents, generate topics, and return the docs with topics
        Arguments:
            documents: A list of documents to fit on
            embeddings: Pre-trained document embeddings. These can be used
                        instead of the sentence-transformer model
            y: The target class for (semi)-supervised modeling. Use -1 if no class for a
               specific instance is specified.
        Returns:
            predictions: Topic predictions for each documents
            probabilities: The topic probability distribution which is returned by default.
                           If `calculate_probabilities` in BERTopic is set to False, then the
                           probabilities are not calculated to speed up computation and
                           decrease memory usage.
        Usage:
        ```python
        from bertopic import BERTopic
        from sklearn.datasets import fetch_20newsgroups
        docs = fetch_20newsgroups(subset='all')['data']
        topic_model = BERTopic(calculate_probabilities=True)
        topics, probs = topic_model.fit_transform(docs)
        ```
        If you want to use your own embeddings, use it as follows:
        ```python
        from bertopic import BERTopic
        from sklearn.datasets import fetch_20newsgroups
        from sentence_transformers import SentenceTransformer
        # Create embeddings
        docs = fetch_20newsgroups(subset='all')['data']
        sentence_model = SentenceTransformer("paraphrase-MiniLM-L6-v2")
        embeddings = sentence_model.encode(docs, show_progress_bar=True)
        # Create topic model
        topic_model = BERTopic(calculate_probabilities=True)
        topics, probs = topic_model.fit_transform(docs, embeddings)
        ```
        """
        check_documents_type(documents)
        check_embeddings_shape(embeddings, documents)

        documents = pd.DataFrame({"Document": documents,
                                  "ID": range(len(documents)),
                                  "Topic": None})

        # Extract embeddings
        if embeddings is None:
            self.embedding_model = select_backend(self.embedding_model,
                                                  language=self.language)
            embeddings = self._extract_embeddings(documents.Document,
                                                  method="document",
                                                  verbose=self.verbose)

            self.embeddings = embeddings  # THIS WAS CHANGED!!!!

            logger.info("Transformed documents to Embeddings")
        else:
            if self.embedding_model is not None:
                self.embedding_model = select_backend(self.embedding_model,
                                                      language=self.language)

        # Reduce dimensionality with UMAP
        umap_embeddings = self._reduce_dimensionality(embeddings, y)

        # Cluster UMAP embeddings with HDBSCAN
        documents, probabilities = self._cluster_embeddings(umap_embeddings, documents)

        # Sort and Map Topic IDs by their frequency
        if not self.nr_topics:
            documents = self._sort_mappings_by_frequency(documents)

        # Extract topics by calculating c-TF-IDF
        self._extract_topics(documents)

        # Reduce topics
        if self.nr_topics:
            documents = self._reduce_topics(documents)
            probabilities = self._map_probabilities(probabilities)
        predictions = documents.Topic.to_list()

        return predictions, probabilities
```

Then, you can access the embeddings with `model.embeddings`.
