### ISSUE TITLE
Documents that belong to certain topics

### ISSUE THREAD

**Issue by randomrdrand** [MaartenGr/BERTopic#162]
I am wondering if it's possible to have the topic cluster sizes? in other words is it possible to know which documents are belonging to certain topics?

**Comment by sgdantas** [comment]
If I recall correctly, the fitted `bert_topic` returns a list of topics, so you can just map it back based on the documents you used to fit the model

**Comment by MaartenGr** [comment]
Let's assume you have run the code below:

```python
from bertopic import BERTopic
from sklearn.datasets import fetch_20newsgroups
 
docs = fetch_20newsgroups(subset='all',  remove=('headers', 'footers', 'quotes'))['data']

topic_model = BERTopic()
topics, _ = topic_model.fit_transform(docs)
```

You can then find the topics that the documents belong to in `topics`. This means that the topic for `docs[0]` is `topics[0]`. With respect to the cluster sizes, you can simply run `topic_model.get_topic_info()` to get a Pandas DataFrame containing the size of topics, IDs, and their topic representation.

**Comment by randomrdrand** [comment]
Thanks that was useful!
