### ISSUE TITLE
Duplicate words in multilingual representation

### ISSUE THREAD

**Issue by yzGao22** [MaartenGr/BERTopic#1621]
Hi @MaartenGr,

I trained Bertopic on multilingual data and noticed that sometimes the representation of a cluster has serval words which have same meaning, but in different language. For example, in representation:
```
['juego', 'jeu', 'pc', 'juegos', 'jeux', '게임', 'lanzamiento', 'series', 'play', 'disponible']
```
'juego', 'jeu' and '게임' all means 'game' in Spanish, French and Korean respectively. And 'juegos' and 'jeux' are the plural form of 'juego' and 'jeu'. 
This will cause the information lose in the topic. Do you have any idea how to handle this? Like making each word in a representation has different meaning.
Thank you.

**Comment by MaartenGr** [comment]
There are a number of things that you can try but I believe the most straightforward solution is to use [MaximalMarginalRelevance](https://maartengr.github.io/BERTopic/getting_started/representation/representation.html#maximalmarginalrelevance) which controls the diversity of the output.

**Comment by yzGao22** [comment]
Thank you for replying @MaartenGr. I tried to set different mmr values but still many duplicate things. I noticed that in the source code, BERTopic gets 30 top words for each topic based on c-TF-IDF, then the mmr is applied to those words to get the representation.
I wonder is there any way I can check the selected 30 words of each topic? Thx

**Comment by MaartenGr** [comment]
You can create [multiple representations](https://maartengr.github.io/BERTopic/getting_started/multiaspect/multiaspect.html) of a single topic which allows you to use both MMR and c-TF-IDF separately. You can set `top_n_words` in BERTopic to increase the number of words per topic.

**Comment by yzGao22** [comment]
I got another issue when I tried to set ```top_n_words```. Below is my code for model setting:
```
vectorizer_model = CountVectorizer(stop_words=all_stopwords, min_df=0.10, ngram_range=(1, 2))

cluster_model = HDBSCAN(min_cluster_size=10, metric='euclidean', cluster_selection_method='eom', prediction_data=True)
umap_model = UMAP(n_neighbors=10, n_components=150, min_dist=0.0, metric='cosine')

topic_model = BERTopic(
    umap_model=umap_model, 
    hdbscan_model=cluster_model,
    vectorizer_model=vectorizer_model,
    verbose=True,
    language="multilingual",
    n_gram_range=(1,2),
    representation_model = MaximalMarginalRelevance(diversity=0.9, top_n_words=1),
)
```
But the output have representations with 10 words for every topic still. Like this:```['saison', 'bayern', 'team', 'spiel', 'tour', 'sport', 'étape', 'platz', 'münchen', 'spielen']```.
Do you know the possible reasons for why this happens? Thx

**Comment by MaartenGr** [comment]
Assuming you are using the latest version of BERTopic, the `top_n_words` can be set in both `BERTopic()` as well as in `MaximalMarginalRelevance`. I would advise setting the `top_n_words` in BERTopic to 30, that will generate 30 candidate words to be passed to `MaximalMarginalRelevance`. Then, in `MaximalMarginalRelevance`, set `top_n_words` to 10 to distill the 30 candidate words to 10. 

Small note, `n_gram_range` in `BERTopic()` does not do anything if you have set `vectorizer_model`, so you can skip that one.

**Comment by yzGao22** [comment]
Thx and I tried the setting you recommended. Below is the code:
```
topic_model = BERTopic(
    umap_model=umap_model, 
    hdbscan_model=cluster_model,
    vectorizer_model=vectorizer_model,
    verbose=True,
    language="multilingual",
    top_n_words=30,
    representation_model = MaximalMarginalRelevance(diversity=0.9, top_n_words=10),
)
```
I want to check the final 10 candidate words for each topic. I tried ```topic_model.topic_representations_``` but it returns me the whole 30 candidate words for each topic. So how can I check the final representations? thx

**Comment by MaartenGr** [comment]
If I run the following code, I get the top 10 final candidate words for each topic using `topic_model.topic_representations_`:

```python
from datasets import load_dataset

from umap import UMAP
from hdbscan import HDBSCAN
from sklearn.feature_extraction.text import CountVectorizer

from bertopic import BERTopic
from bertopic.representation import MaximalMarginalRelevance

# We select a subsample of 5000 abstracts from ArXiv
dataset = load_dataset("CShorten/ML-ArXiv-Papers")["train"]
docs = dataset["abstract"][:5_000]

# Sub Models
umap_model = UMAP(n_neighbors=15, n_components=5, min_dist=0.0, metric='cosine', random_state=42)
vectorizer_model = CountVectorizer(stop_words="english", min_df=0.10, ngram_range=(1, 2))
cluster_model = HDBSCAN(min_cluster_size=10, metric='euclidean', cluster_selection_method='eom', prediction_data=True)

# Fit Topic Model
topic_model = BERTopic(
    umap_model=umap_model, 
    hdbscan_model=cluster_model,
    vectorizer_model=vectorizer_model,
    verbose=True,
    language="multilingual",
    top_n_words=30,
    representation_model = MaximalMarginalRelevance(diversity=0.9, top_n_words=10),
)
topics, probs = topic_model.fit_transform(docs)
```

**Comment by yzGao22** [comment]
I find that if the doc embeddings is pre-calculated and passed to the model, the output of ```topic_model.topic_representations_``` is 30 words for each topic. But if the embedding is calculated during the ```fit_transform``` the output is 10 words for each topic. 

Problem solved, thank you so much for the patience and help @MaartenGr !

**Comment by MaartenGr** [comment]
No problem, glad I could help!
