### ISSUE TITLE
Cannot import a model locally

### ISSUE THREAD

**Issue by pierremotard** [MaartenGr/BERTopic#163]
Hello, I used bertopic on colab and saved the model using bertopic.save("my_model"). Now I need this model locally but always get an error (I tried changing python version between 3.8 and 3.9)
<img width="914" alt="Screenshot 2021-06-29 at 08 34 42" src="https://user-images.githubusercontent.com/6213616/123748890-1a7cd180-d8b5-11eb-9501-0fe24e0a8fbf.png">

Any idea how to solve this?
Thanks!

**Comment by MaartenGr** [comment]
Hi Pierre, 

There could be many reasons for this happening. In general, this issue typically stems from a mismatch between environments. For example, if you were to have different versions of sentence-transformers in the environment, there is a good chance that you will find incompatibility issues. I would suggest applying version control to you environments with something like Conda, pyenv, poetry, or something else to make sure your saved model will be loaded in the same environment.

**Comment by MaartenGr** [comment]
Since there hasn't been a response, I am closing this for now. If you still have any issues, feel free to re-open the issue and we'll take another look at!

**Comment by pierremotard** [comment]
Indeed it had to do with saving the model and loading it on machines using the same python version, as well as either both on CPU or both on GPU. My specific use was to save it on my machine and load it on in docker container so I chose the same python version in the Dockerfile and it works now. Thanks for helping!

**Comment by MaartenGr** [comment]
Glad to hear that it worked out! If you encounter any other issues, please let me know.
