### ISSUE TITLE
Plotly Graphy produced shows datetime values as absolute numbers 

### ISSUE THREAD

**Issue by APVB12** [MaartenGr/BERTopic#1631]
<img width="1023" alt="image" src="https://github.com/MaartenGr/BERTopic/assets/147594747/05dbc751-e03c-4275-9be1-fa0e2d4bfb5f">

Hello BERTopic team, I am having an issue where the datetime values shown on the plotly graphy created from the visualize_topics_over_time function only show themselves as absolute numbers instead of being visualized in date format. Im not sure how to solve this issue as I have tried upgrading the plotly package. I am using pip as my package manager and currently running this app locally and on streamlit with the same issue.

**Comment by MaartenGr** [comment]
That might be a result of the specific datetime format that you have. Have you tried using `datetime_format` in `.topics_over_time`?

**Comment by APVB12** [comment]
<img width="1155" alt="image" src="https://github.com/MaartenGr/BERTopic/assets/147594747/8e535ede-c8c3-42aa-b323-e154deaa87bb">

<img width="1023" alt="image" src="https://github.com/MaartenGr/BERTopic/assets/147594747/0cb692ed-af6e-4874-9c44-0025f2d46685">

Hello Maarten, thanks for the fast response and for your work on BERTopic. 

So I tried inputing the `datetime_format = "%b%d` in my code however there wasn't any changes. I have even tried converting each datetime element in my dataset to a datatime format to make sure that it is in the correct datatype. I have tried this same code in Google Colab with this issue occuring though.

**Comment by MaartenGr** [comment]
Did you see the datetime properly formatted in the `topics_over_time` dataframe? Could you show the first couple of rows? Also, please check whether a specific date is formatted like you indicated.

**Comment by APVB12** [comment]
<img width="947" alt="image" src="https://github.com/MaartenGr/BERTopic/assets/147594747/05ee9a5b-5471-4711-b63e-2ed73beb78a5">

Hi Maarten so `datetime_format = "%b%d` did not change the Timestamp type that was in a Unix epoch format. I found this answer https://stackoverflow.com/questions/62995700/timestamp-too-large-for-datetime, and used `topics_over_time["Timestamp"].apply(lambda x : datetime.date.fromtimestamp(x/1e9))`. That worked and managed to convert the unix epoch to a datetime format. Thanks for the help I will close this thread

<img width="947" alt="image" src="https://github.com/MaartenGr/BERTopic/assets/147594747/4a795ad2-8343-4253-97f6-63e05c5fe854">
