### ISSUE TITLE
Visualization in Jupyter notebook

### ISSUE THREAD

**Issue by JoshuaE1** [MaartenGr/BERTopic#164]
Hi there, Great package, congratulations on thatI am trying to use the visualization functionalities in a Jupyter notebook but keep i getting empty output cells. No error warning or anything like that, just an empty cell. Do you perhaps have an idea what might be going on here, or a fix for this issue :-)? Many thanks in advance and thanks for your time!

**Comment by firmai** [comment]
you could try this:

Simple solution: jupyter labextension install jupyterlab-plotly

Restart Jupyter Lab after installing the extension.

**Comment by MaartenGr** [comment]
Although I have some thoughts on this issue, it very much depends on how you have executed your code and what you have installed in your environment. Could you share your code and the BERTopic version?

**Comment by JoshuaE1** [comment]
I fixed this by running `jupyter labextension install jupyterlab-plotly`
