### ISSUE TITLE
[QST] Is it possible to run fit_transform on a cloud?

### ISSUE THREAD

**Issue by bjpietrzak** [MaartenGr/BERTopic#1640]
Is it possible to run fit_transform of a BERTopic model on a cloud (gcs)? I plan on using BERTopic as an unsupervised model, retrieving document topics and document classification to topic each time the inference is performed.

**Comment by MaartenGr** [comment]
Yes, that should be no problem. Make sure to load the model as [`safetensors`](https://maartengr.github.io/BERTopic/getting_started/serialization/serialization.html) since that generalizes better to different environments which should also speed up inference.
