### ISSUE TITLE
Documentation website is not up to date

### ISSUE THREAD

**Issue by saeedesmaili** [MaartenGr/BERTopic#1643]
I've come across a few issues on the documentation and wanted to open PRs, but realized all of them are fixed and merged in the repo but the website still has the outdated info.

As an example, [this pr](https://github.com/MaartenGr/BERTopic/pull/1408) which was merged in Aug has fixed the incorrect parameter name but [the website](https://maartengr.github.io/BERTopic/getting_started/best_practices/best_practices.html#preventing-stochastic-behavior) still has `min_topic_size`.

I wonder if this is intentional or if there is an issue in the process of deployment of the documentation website.

**Comment by MaartenGr** [comment]
That is correct! Currently, the main branch has a number of updates that are not yet in an official release (I am aiming for the update to be released within the week). As a result, I purposefully did not update the website yet as that would suggest these new features are already within an official release of BERTopic, which is not the case. When a new version is released, I will update the website.
