### ISSUE TITLE
Extend Color Range for visualize_topics_over_time()

### ISSUE THREAD

**Issue by MaggieMeow** [MaartenGr/BERTopic#1645]
Hi there! I'm working on a research project on historical documents and the topics_over_time feature is immensely useful.

I've encountered a limitation with the visualize_topics_over_time() function. It currently supports only 7 distinct colors. This restriction causes color repetition when visualizing more than 7 topics, which can lead to confusion, especially in a static image format suitable for research papers.

May I know how to extend the color range or incorporate my own color map for this function?

Thank you very much!

**Comment by MaartenGr** [comment]
Thank you for your kind words! Although this is currently not implemented, it should be rather straightforward to change it yourself. You can simply change the following line of code to include whatever colors you are interested in:

https://github.com/MaartenGr/BERTopic/blob/7d07e1e94e69be278f79a48d73602cdc4df0885f/bertopic/plotting/_topics_over_time.py#L53

Do note though that having more colors does not necessarily entail an improved reading experience, especially concerning those with some form of colorblindness.

**Comment by MaggieMeow** [comment]
Thank you very much for your kind help!
