### ISSUE TITLE
Merge topics and get new probablity

### ISSUE THREAD

**Issue by juxiepao** [MaartenGr/BERTopic#1647]
Hello, I am attempting to use Hierarchical Topic Modeling. 
After merging topics based on the hierarchical clustering, I tried to calculate the probability of each document belonging to the different topics (e.g., doc1 has a 1% probability of belonging to topic 0, a 2% probability of belonging to topic 1, etc.). However, it doesn't seem to work.

Could this be because the topic merger only creates a new representation and does not generate new probabilities? 

If that is the case, how can I obtain the updated probabilities as described above? 

Thank you in advance for your kind assistance!

**Comment by MaartenGr** [comment]
You can find the updated probabilities in `Model_11.probabilities_`. Any updated topics or probabilities, or any attribute of the model for that matter, should be accessed directly from the model. All "outside" variables will not be updated (since they shouldn't).

**Comment by juxiepao** [comment]
Thank you so much! It really works quite well!

However, I encountered a new issue when I tried to apply it to the loaded model. It seems that I'm not getting the probability matrix in Model_8.probabilities_.

Also, when I executed:

`print(data["content"][79])
Model_8.visualize_distribution(probs[79])`
The chart turned out to be odd...

Do you know how I can obtain the probabilities for a loaded model? I still want to perform the same operation as our previous discussion, where we converted and merged probabilities.

Thanks again!!!

here is the code below: 

`embedding_model = "sentence-transformers/all-MiniLM-L6-v2"
Model_8.save("my_model_dir_8", serialization="safetensors", save_ctfidf=True, save_embedding_model=embedding_model)

from sentence_transformers import SentenceTransformer


embedding_model = SentenceTransformer("all-MiniLM-L6-v2")

Model_8 = BERTopic.load("/my_model_dir_8", embedding_model=embedding_model)

topics, probs = Model_8.transform(data["content"])

Model_8.probabilities_
`

**Comment by MaartenGr** [comment]
> print(data["content"][79]) Model_8.visualize_distribution(probs[79])
> The chart turned out to be odd...

What do you mean by this? Could you describe the issue you are facing in a bit more detail?


> Model_8.probabilities_

Could you share your full code? As in, the code you used to train `Model_8` and then the code you used to load it in. In your previous messages, I did not see `Model_8` there and we need the exact code to understand what is happening here.

**Comment by juxiepao** [comment]
Dear Maarten,

Thank you so much! Model_8 is exactly the same as Model_11. As required for an academic paper, we have to run it multiple times to ensure the stability of the model.

Here is the code for Model_8:

Model_8 = BERTopic(
embedding_model=embedding_model,
umap_model=umap_model,
hdbscan_model=hdbscan_model,
vectorizer_model=vectorizer_model,
ctfidf_model=ctfidf_model,
representation_model=representation_model,
language="english", calculate_probabilities=True, verbose=True,
top_n_words=10
)

topics, probs = Model_8.fit_transform(data["content"])

from bertopic import BERTopic
from sentence_transformers import SentenceTransformer

Define embedding model
embedding_model = SentenceTransformer("all-MiniLM-L6-v2")

Load model and add embedding model
Model_8 = BERTopic.load("/content/drive/My Drive/my_model_dir_8", embedding_model=embedding_model)

topics, probs = Model_8.transform(data["content"])

before merge
print(data["content"][79])
Model_8.visualize_distribution(probs[79])

Model_8.probabilities_

merge
Model_8.visualize_hierarchy()

topics_to_merge = [[5,34,47,3,76,96,37,42,38,94,95,74,21,41,54,60,81,88,87,16,33,83,53,25,86,48,78,55,1,12,72,89,6,26],
[80,46,43,75,97,22,58,52],[11,49,14,17,13,66], [92,98],[90,79,44,45,59],[62,2],[82,57,84],[32,70,30],[20,7,8,40,65],[61,35,64],[18,71,24,93,77,67,15,9,36],
[39,29,56,63,10,73,91,50,51],[68,19,23,28,69,4,27,31,85]]

Model_8.merge_topics(data["content"], topics_to_merge)

print(data["content"][79])
Model_11.visualize_distribution(probs[79])

Model_8.probabilities_

Problem 1: for the loaded model (Model_8),  It seems that I'm not getting the probability matrix in Model_8.probabilities_.

Problem 2: 
print(data["content"][79]) 
Model_8.visualize_distribution(probs[79])

The chart did not display the correct probabilities compared with a newly trained model. 
For instance, using the newly trained model, I can obtain the matrix using Model_8.probabilities_, and the chart accurately indicates the probability of documents belonging to various topics. 
However, when using the loaded model, the chart does not correctly reflect the probabilities of the documents belonging to the topics.

Thanks again for your kind help!

**Comment by MaartenGr** [comment]
When you run the following:

```python
topics, probs = Model_8.transform(data["content"])
```

It generates probabilities that are different from the internal representations. This means that the probabilities between `fit` and `transform` are different from one another. This is a result of HDBSCAN which does an approximation of the probabilities which might be different between training and inference. 

This means that you have to be careful when comparing the results of `fit` with `transform`.

To make this more concrete, first run the following (and in the future, make sure to format your code with "```python"):

```python
Model_8 = BERTopic(
embedding_model=embedding_model,
umap_model=umap_model,
hdbscan_model=hdbscan_model,
vectorizer_model=vectorizer_model,
ctfidf_model=ctfidf_model,
representation_model=representation_model,
language="english", calculate_probabilities=True, verbose=True,
top_n_words=10
)

topics, probs = Model_8.fit_transform(data["content"])
```

The `probs` should be the same as `Model_8.probabilities_`. Then, when you load the model:

```python
from bertopic import BERTopic
from sentence_transformers import SentenceTransformer

# Define embedding model
embedding_model = SentenceTransformer("all-MiniLM-L6-v2")

# Load model and add embedding model
Model_8 = BERTopic.load("/content/drive/My Drive/my_model_dir_8", embedding_model=embedding_model)
```

You should not need to run the following:

```python
topics, probs = Model_8.transform(data["content"])
```

Since the probabilities should still be stored in `Model_8.probabilities_`. 

Then, when you run the visualization, use it like so:

```python
Model_8.visualize_distribution(Model_8.probabilities_[79])
```

Then, after your merging step, you still do not use the `probs` variable but use the internal probabilities instead:

```python
topics_to_merge = [[5,34,47,3,76,96,37,42,38,94,95,74,21,41,54,60,81,88,87,16,33,83,53,25,86,48,78,55,1,12,72,89,6,26],
[80,46,43,75,97,22,58,52],[11,49,14,17,13,66], [92,98],[90,79,44,45,59],[62,2],[82,57,84],[32,70,30],[20,7,8,40,65],[61,35,64],[18,71,24,93,77,67,15,9,36],
[39,29,56,63,10,73,91,50,51],[68,19,23,28,69,4,27,31,85]]

Model_8.merge_topics(data["content"], topics_to_merge)

Model_8.visualize_distribution(Model_8.probabilities_[79])
```

What is important here is that the `probs` variable is local. This means that any changes you make to the topic model will **not** influence `probs` and should therefore not be used. It is generally bad practice to update local variables that way.

**Small tip**: When you share your code, make sure to format it with ```python and make sure to accurately show the order of steps. For instance, I am missing the saving step which makes me wonder what else might be missing in your code. Also, you use `Model_11` when it was never mentioned which convinces me that the code you shared is not accurate.

**Comment by juxiepao** [comment]
Dear Maarten,

I apologize for the confusion; it is indeed my fault. 

Now I understand that I should not use a local variable. However, after loading the model and `print(Model_8.probabilities_)` it returns "None". It seems that the probability matrix is not being saved.

To clarify, I used the following method to save the model:

```python 
embedding_model = "sentence-transformers/all-MiniLM-L6-v2"
Model_8.save("my_model_dir_8", serialization="safetensors", save_ctfidf=True, save_embedding_model=embedding_model)

**Comment by juxiepao** [comment]
Dear Maarten,

Is the issue I'm experiencing due to a mistake I made, perhaps not saving the probability matrix, when saving the model? Today, when I tried again to use the model after reconnecting to Colab, I still couldn't retrieve the probabilities.

Thank you once again for your help!
