### ISSUE TITLE
 intfloat/multilingual-e5-large embeddings

### ISSUE THREAD

**Issue by stygmate** [MaartenGr/BERTopic#1650]
I want to use **intfloat/multilingual-e5-large** for embeddings but **cosine similarities** calculated on vectors outputed by this model are **all between 0.7 and 1.0**.
How to apply this simple linear correction in UMAP:
https://huggingface.co/intfloat/multilingual-e5-large/discussions/10#64d23868cdde782940e6357a
(i guess it go here but i may be wrong)

**Comment by MaartenGr** [comment]
You indeed might need to apply this in UMAP since the distance calculations are done there. I believe you can even implement your own distance measures but you will have to check UMAP's documentation.

**Comment by stygmate** [comment]
Done :)

(ugly code because i don't know numba)
```python
@numba.njit()
def rectified_metric(a, b):
    cos_similarity = np.dot(a, b) / (norm(a) * norm(b))
    rectified_similarity = 2 * (cos_similarity - 0.85) / (1.0 - 0.7)
    distance = 1.0 - rectified_similarity
    if distance < 0.0:
        distance = 0.0
    elif distance > 2.0:
        distance = 2.0
    return distance
```

```python
UMAP(n_neighbors=15, n_components=5, min_dist=0.0, metric=rectified_metric, low_memory=False)
```
