### ISSUE TITLE
fit_transform with custom embedder downloads sentence_transformer

### ISSUE THREAD

**Issue by abhincho** [MaartenGr/BERTopic#1651]
Hey

I am performing a bertopic clustering using a custom Embedder (Azure endpoint with the underlying embedding model being hkunlp/instructor-large).
```
custom_embedder = CustomEmbedder()
representation_model = bertopic.representation.MaximalMarginalRelevance(diversity=0.3)
embedding_model = custom_embedder 
ctfidf_model = bertopic.vectorizers.ClassTfidfTransformer(bm25_weighting=True,reduce_frequent_words=True)
obj = bertopic.BERTopic(ctfidf_model=ctfidf_model,embedding_model=embedding_model,representation_model=representation_model,min_topic_size=15,nr_topics=4)
x = obj.fit_transform(docs,embeddings)
```
But when ever I run `fit_transform`,  the `sentence-transformers ('all-MiniLM-L6-v2')` keeps getting downloaded, when I have explicitly defined a custom embedding using the `CustomEmbedder `class defined in [BERTopic](https://maartengr.github.io/BERTopic/getting_started/embeddings/embeddings.html#multimodal
)

I need to deploy the bertclustering as azure endpoint and the endpoint creation keeps failing because the sentence transformer model keeps on downloading.

**Comment by MaartenGr** [comment]
Could you share your full code? As in, what exactly is in `CustomEmbedder()`? Since the issue relates to how you have built up that class, that is where the issue might be. Also, which version of BERTopic are you using?

**Comment by abhincho** [comment]
Thanks so much for your quick response!
Bertopic version: 0.15.0
```
from Model_endpoint.endpoint import model_endpoint

class CustomEmbedder():
    def __init__(self,url,api_key):
        self.embedding_model = model_endpoint(url,api_key) 

    def embed_documents(self, documents):
        embeddings = self.embedding_model.send_json_input(category='clustering', data=documents)['embedding']
        return embeddings 
    def embed_query(self, documents):
        embeddings = self.embedding_model.send_json_input(category='clustering', data=documents)['embedding']
        return embeddings 

```

**Comment by MaartenGr** [comment]
Ah, you are not following the example in the [documentation](https://maartengr.github.io/BERTopic/getting_started/embeddings/embeddings.html#custom-backend). Make sure that your custom class inherits from `bertopic.backend.BaseEmbedder`

**Comment by abhincho** [comment]
Hi, Thank you for your reply, it cleared the issue. 
I have a doubt though when I do not inherit the `bertopic.backend.BaseEmbedder` class, while still setting the embedding model to the custom model (as I had done in the code above). The embeddings generated are by the custom model or by `sentence-transformers ('all-MiniLM-L6-v2')`?

**Comment by MaartenGr** [comment]
There are checks done with respect to the input of the embedding model. If no compatible model is given, then it will default to the sentence-transformer model. This allows for users to still be able to use the topic model without the need to always specify an embedding model.

**Comment by abhincho** [comment]
Thank you. And this is some impressive work you have done. I really like using BERTopic
