### ISSUE TITLE
Using embedding model from local folder while BERTopic.load()

### ISSUE THREAD

**Issue by alokpadhi** [MaartenGr/BERTopic#1653]
This is how I saved my topic_model.
```
embedding_model = "sentence-transformers/all-MiniLM-L6-v2"
topic_model.save(model_dir, serialization="pytorch", save_ctfidf=True, embedding_model=embedding_model)
```
And later I was trying to load as below. Just FYI because of SSL Error I wanted to pass the SentenceTransformer model which I downloaded.
```
embedding_model = SentenceTransformer(MINILM_model_dir)

topic_model = BERTopic.load(topic_model_dir, embedding_model=embedding_model)
```
What am I doing wrong, or Is there any way I can pass the embedding model from the local folder? As currently it tries to download the MiniLM model which is not possible inside the Docker container due to SSL error.

Can anyone please help me on this?

**Comment by MaartenGr** [comment]
> embedding_model = SentenceTransformer(MINILM_model_dir)
> topic_model = BERTopic.load(topic_model_dir, embedding_model=embedding_model)

That should be correct as long as you specify the folder and not the model which is hosted online. Perhaps changing the foldername might work. Having said that, SBERT can load local models, so definitely check out its documentation on doing so.

**Comment by alokpadhi** [comment]
Yes I passed the MINIML directory path in the embedding_model param. But I'm getting warning 
`"You are loading a BERTopic model without explicitly defining an embedding model."
                        "If you want to also load in an embedding model, make sure to use"
                        "BERTopic.load(my_model, embedding_model=my_embedding_model)."
`
And it starts downloading from huggingface.

**Comment by MaartenGr** [comment]
Could you try it without saving a reference to the embedding model? 

Like so:

```python
embedding_model = "sentence-transformers/all-MiniLM-L6-v2"
topic_model.save(model_dir, serialization="pytorch", save_ctfidf=True)
```

and then loading it:

```python
embedding_model = SentenceTransformer("THE_LOCAL_PATH_TO_THE_MODEL")
topic_model = BERTopic.load(topic_model_dir, embedding_model=embedding_model)
```

**Comment by alokpadhi** [comment]
Yeah it worked. Thanks @MaartenGr
