### ISSUE TITLE
Could not build wheels for hdbscan / Microsoft Visual C++ 14.0 is required (solved!)

### ISSUE THREAD

**Issue by Au2mater** [MaartenGr/BERTopic#1656]

**Comment by Au2mater** [comment]
the problem seems to originate for the hdbscan dependancy.
I have not been able to resolve this.
Is it possible to install bertopic wíthout hdbscan and suplement that module with another variation?

**Comment by MaartenGr** [comment]
Could you share your full error message? When you mention that you can't install BERTopic because of HDBSCAN it is still not clear what that exactly means. Make sure to provide as much information as you can about the issue that might seem relevant. Otherwise, it is difficult to help you out.

**Comment by Au2mater** [comment]
I'm running windows 10. 
I have traced the issue back to not being able to install HDBscan on my machine.
Pip casts the following error:
...
     error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for hdbscan
Failed to build hdbscan
....
I have installed 
I have tried conda and pip, python 3.9/3.10/3.11 without any luck

**Comment by MaartenGr** [comment]
Could you check some of the [closed issues](https://github.com/MaartenGr/BERTopic/issues?q=is%3Aissue+visual+c%2B%2B+is%3Aclosed) that relate to this? There are a number of helpful tips there that help you get started. In particular, #816 has great solutions.

**Comment by Au2mater** [comment]
Solved :-)
Solution required admin access, and installing packages separatly using conda and pip
Solution steps
1. Install Microsoft Build Tools for Visual Studio.
Select: Workloads → Desktop development with C++, then for Individual Components, select only:
	Windows SDK
	C++ x64/x86 build tools
This required admin access
guide: https://www.scivision.dev/python-windows-visual-c-14-required/
2. create a new environment using conda (not venv)
3. conda install -c conda-forge hdbscan
4. pip install --upgrade pip
5. pip install --upgrade setuptools
6. pip install bertopic (do not install using conda)

Thank you very much for your replies and patience! 
Much appreciated!
And thank you for creating BERTopic!
We have already had great success topic modelling support tickets using BERTopic in my organisation.
