### ISSUE TITLE
Sorted topics

### ISSUE THREAD

**Issue by ozyurtf** [MaartenGr/BERTopic#166]
Hi Maarten,

I have a question about the part where you sort the topics based on frequencies. Let's say that we have a list of documents and put that into the function: 

topic_model = BERTopic()
topics, probs = topic_model.fit_transform(docs)

In this case, can we say that the topics we obtained will not be representative of the docs ? In other words, will topics[k] belong to the predicted topic of the docs[k] ?

**Comment by MaartenGr** [comment]
Only the topic ID was sorted based on the frequency. So only the name was changed without changing the actual order of topics in the variable `topics`. In other words, for any *i* in *n*, where *n* is the number of documents, `topics[i]` will be the topic related to `docs[i]`. Thus, we can say that the topics obtained **will be representative** of the docs. 

Hopefully, this answers your question!

**Comment by ozyurtf** [comment]
That was fast, thank you Maarten!
