### ISSUE TITLE
Topic Distribution Output Matrix

### ISSUE THREAD

**Issue by MansourShahhosseini** [MaartenGr/BERTopic#1663]
Hi, I am following the instructions in [here](https://maartengr.github.io/BERTopic/getting_started/distribution/distribution.html) to get a distribution of all topics for all the documents. I have around 100,000 documents and 90 topics, and I expected to get a 100000 * 90 matrix; however, the output of "topic_distr, _ = topic_model.approximate_distribution(docs)" is a 1394 * 90 matrix. I deeply appreciate it if you please let me what I should do

**Comment by MaartenGr** [comment]
Thanks for sharing this. Could you share your full code? Without it, it is quite hard to say what is happening here. Also, what version of BERTopic are you using?

**Comment by MaartenGr** [comment]
Hmmm, could you try two things for me? First, instead of using `df.clean_text` everywhere, use `df_clean_text.tolist()` instead? The reason is that a list of strings is expected in all instances and not a pandas series. Second, could you try to run the pipeline without reducing outliers? 

Perhaps one of those can be the source of the issue.

**Comment by MansourShahhosseini** [comment]
> Hmmm, could you try two things for me? First, instead of using `df.clean_text` everywhere, use `df_clean_text.tolist()` instead? The reason is that a list of strings is expected in all instances and not a pandas series. Second, could you try to run the pipeline without reducing outliers?
> 
> Perhaps one of those can be the source of the issue. 

Thank you so much. df_clean_text.tolist() worked great, with and without reducing outliers.

**Comment by MaartenGr** [comment]
Great! Glad to hear that resolved the issue. If you have any other problems, feel free to reach out.
