### ISSUE TITLE
A ValueError occurred while calculating the c-tf-idf score

### ISSUE THREAD

**Issue by eiklnot1973** [MaartenGr/BERTopic#1673]
Hello, I was training the BERTopic model to extract topics from Korean documents. However, the following error occurred during training:

<img width="1332" alt="스크린샷 2023-12-07 오후 2 36 19" src="https://github.com/MaartenGr/BERTopic/assets/82483058/fc90f9d0-6008-4894-b373-dcd7a67cd493">

The ValueError occurred probably because of the above issue, 'Runtimewarning: divide by zero encountered in divide idf = np.log((avg_nr_samples / df)+1)'. But if I understand correctly how c-tf-idf works, this seems like something that can't happen. This is because df is 'frequency of word x across all classes' and therefore cannot be 0.

I passed a custom tokenizer as an argument to CountVectorizer to tokenize Korean documents, so maybe that has something to do with the problem. The tokenizer I customized works by extracting morphemes from Korean documents and removing morphemes with specific parts of speech. But no matter what tokenizer I use (e.g. a weird tokenizer like tokenizer=lambda x: ['a', 'b', 'c']) it seems like df being 0 cannot happen. The code used is as follows:

<img width="916" alt="스크린샷 2023-12-07 오후 8 45 32" src="https://github.com/MaartenGr/BERTopic/assets/82483058/a2e67fa9-1da9-4caf-b2d1-8e1f028318c4">

The docs passed to the model are a list of 3241 strs, and each string is approximately 250 characters. Other parts of my BERTopic model followed almost exactly what was presented in Best Practices. I ran the code on a Colab notebook and used the GPU.

I would appreciate any help in resolving this issue.

**Comment by MaartenGr** [comment]
Could you share the full code from beginning to end? That makes it easier to see what is happening here. 

Having said that, it might just be that the tokenizer you are using results in some topics having no words at all. To resolve that, it might make sense to either use a more lenient tokenizer, remove your tokenizer, or create larger topics by increasing the `min_cluster_size` parameter. See if any of those things work and let me know!
