### ISSUE TITLE
TypeError: float object is not subscriptable -

### ISSUE THREAD

**Issue by vatsaldin** [MaartenGr/BERTopic#1677]
<img width="1475" alt="Screenshot 2023-12-08 at 12 01 39 PM" src="https://github.com/MaartenGr/BERTopic/assets/1464312/efb98810-949e-4da5-b152-195fd2ca0275">

<img width="1429" alt="Screenshot 2023-12-08 at 11 57 13 AM" src="https://github.com/MaartenGr/BERTopic/assets/1464312/3c5a10e5-b957-4ba1-8861-e2eb7737f159">

I  am using list of Strings , still getting this error message

Tried with Python 3.8.x and Python 3.9.x

**Comment by MaartenGr** [comment]
Please share your **full** code. Without it, it is difficult to say what exactly is happening here. For instance, it seems to relate to an embedding model but I can't see which one.

**Comment by vatsaldin** [comment]
<img width="1473" alt="Screenshot 2023-12-08 at 12 37 31 PM" src="https://github.com/MaartenGr/BERTopic/assets/1464312/faaab5ba-b40d-4a84-bc4e-718d25d2a1c7">

Please refer the above 

`pip install bertopic `

Above used to install package so default embedding may be in use

**Comment by MaartenGr** [comment]
Did you make sure that all documents in the your `docs` variable are strings and not a single of them are float? Also, make sure that each document in `docs` not only is a string but is also non-empty. Empty documents will raise errors.

**Comment by MaartenGr** [comment]
No problem! Glad I could help.
