### ISSUE TITLE
Error while installing BERTopic in Anaconda ( OS - Windows10)

### ISSUE THREAD

**Issue by Shriyanshidixit** [MaartenGr/BERTopic#168]
Hey @MaartenGr,
I have been trying to resolve this error for the past few days, **please help!**
I think it's the issue with hdbscan, what could be done to resolve this error?

OS - windows 10

_I have already saved and downloaded a pre-trained model from google collab, now I am trying to deploy it with flask( developing a web app)_

c:\users\hp\anaconda3\envs\bertmodel\include\pyconfig.h(59): fatal error C1083: Cannot open include file: 'io.h': No such file or directory
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30037\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2

ERROR: Failed building wheel for hdbscan
Failed to build hdbscan
ERROR: Could not build wheels for hdbscan which use PEP 517 and cannot be installed directly

**Comment by MaartenGr** [comment]
Although I am not familiar with this issue, it does seem that there are some environment issues going on. Perhaps [this](https://stackoverflow.com/questions/40018405/cannot-open-include-file-io-h-no-such-file-or-directory) could be of help to you. Also, have you tried installing BERTopic in a fresh environment?

**Comment by MaartenGr** [comment]
Since there hasn't been a response, I am closing this for now. If you still have any issues, feel free to re-open the issue and we'll take another look at!
