### ISSUE TITLE
[Feature Request] Save/Load from cloud services

### ISSUE THREAD

**Issue by Dref360** [MaartenGr/BERTopic#1680]
Hello!

I love this library and I use it quite a lot!
A problem that I face is that I need to save/load models in the Cloud. Currently, I need to mount a volume on Google Cloud to do so which is often unreliable and cumbersome to setup.

Could we use `fsspec` to do this? Huggingface datasets are save on the cloud this way and it's a pretty common library. Would look something like:

```python
topic_model: BERTopic = ...
topic_model.save('gs://$bucket/topic_model')
topic_model = BERTopic.load('gs://$bucket/topic_model')
```

I would be happy to work on it if you are happy with this proposition. Worst case I'll publish a gist here with an implementation.

**Comment by MaartenGr** [comment]
Thanks for sharing this! Although I would like to add this type of functionality, I am quite hesitant to add another dependency to BERTopic. The reason for this is that every single dependency you add to a project, regardless of whether they have dependencies themselves, increases the complexity of dependency management and the likelihood of dependency conflicts/issues to arise.

It could be an additional dependency, although those typically relate to embedding backends. Instead, it can be an additional dependency without actually specifying it as such, similar to how SpaCy, OpenAI, Cohere, etc. are handled.

**Comment by Dref360** [comment]
For future reference, one can load BERTopic pickle models by using `fsspec.open` instead of `open` [here](https://github.com/MaartenGr/BERTopic/blob/master/bertopic/_bertopic.py#L2975)

To save BERTopic pickle models, you can use something similar to:

```python
@classmethod
def load(cls,
         path: str,
         embedding_model=None):
    fs = fsspec.core.url_to_fs(path)[0]
    file_or_dir = Path(path)

    # Load from Pickle
    if not fs.isdir(path):
        with fs.open(path, 'rb') as file:
            if embedding_model:
                topic_model = joblib.load(file)
                topic_model.embedding_model = select_backend(embedding_model)
            else:
                topic_model = joblib.load(file)
            return topic_model
```

I hope this helps!
