### ISSUE TITLE
Import error in bertopic._ctfidf

### ISSUE THREAD

**Issue by SapnilPatel** [MaartenGr/BERTopic#1681]
Code:- from bertopic._ctfidf import ClassTFIDF

error:- ModuleNotFoundError: No module named 'bertopic._ctfidf'

IDE :- Google colab

**Comment by MaartenGr** [comment]
That's correct. There is no module named `bertopic._ctfidf` nor should you access these private functions. Instead, I refer you to the documentation that shows how to use this representation model: https://maartengr.github.io/BERTopic/getting_started/ctfidf/ctfidf.html

**Comment by SapnilPatel** [comment]
Got it. 

Thanks for your help.
