### ISSUE TITLE
LLM Representation tokenizer 

### ISSUE THREAD

**Issue by thundergore** [MaartenGr/BERTopic#1685]
I'm trying to pass a slightly larger dataset to OpenAI for the representation stage. The whole dataset doesn't need to be passed ofc, so I'm passing the keywords of only 100 topics and then truncating 1 document to 100 tokens. 

The tokenizer (tried `tiktoken`and `vectorizer` as mentioned in the documentation) starts a very slow tokenization step.

I'm wondering if there's a method of pre-calculating that?

**Comment by MaartenGr** [comment]
There currently is no way of pre-tokenizing the documents since only a very small subset of the data will be tokenized during the OpenAI representation step. 

Could you share your full training code? Also, how many topics are you creating? In practice, the number of documents it will tokenize is equal to the number of representative documents (typically 4) times the number of topics.

**Comment by thundergore** [comment]
The openAI client: 

```python
client = openai.OpenAI(api_key=os.environ.get("OPENAI_KEY"))
openai_model = OpenAI(client,
                      model="gpt-3.5-turbo", 
                      exponential_backoff=True, 
                      chat=True, 
                      nr_docs=1,
                      doc_length=100,
                      tokenizer="vectorizer", #using built in countvectorizer <- maybe slow
                      diversity=0.1, 
                      prompt=prompt,
                     )
```
In the model I'm setting:
```python
                       nr_topics=25

```
I also ran a test without the openAI representation to get the topics_nr naturally (it's 38 in that test run) in case the nr_topics happens after the representation stage. 

So it's between 25 and 38 topics - 1 document each. I guess the documents themselves are maybe between 500 and 1000 words long (articles). Even so I thought they'd tokenise faster.

 10%|████████████▏                                                                                                          | 4/39 [22:01<2:29:16, 255.89s/it]

I stopped my last test run at around 20 minutes as it'd take much too long for the full dataset if it's around about 2.5 hrs for the sample set.

**Comment by linxule** [comment]
The time took to label 39 documents seem quite long. It seems that there might be some issues with the `openai_model` function may have some issues.

`doc_length` does not seem to be a standard parameter in OpenAI client. Without seeing the full code, it is hard to say how it is impacting your script. Perhaps consider the following steps:
1. Extract the representative documents to a data frame 
2. Truncate the documents 
3. Feed it to OpenAI API
4. Add the GPT generated labels to the model using `topic_model.set_topic_labels`

Rep_Docs Extraction: 
```python
rep_docs = model.get_representative_docs()
rep_docs_df = pd.DataFrame.from_dict(rep_docs, orient='index')
```
Count tokens to truncate documents:
I used tiktoken to calculate token counts for the gpt-4 turbo model. For around 5,300 representative documents (full length around 512 tokens per document), counting tokens and calling the API took me less than 7 minutes. 

```python
tokenizer = tiktoken.encoding_for_model("gpt-4-1106-preview")
num_input_tokens = len(tokenizer.encode(prompt))
```
Consideration for rate limit:
Furthermore, depending on the tier of your OpenAI account, try to include a rate limit when calling the `openai_model`. With a few topics, it seems only the TPM (token limit per minute) would apply. 

I hope this can help with the discussion.

**Comment by thundergore** [comment]
Hey! Thanks for taking the time to reply.

Yes, given my aim here is just to get reader friendly labels, I think extraction of the representative documents and feeding those to the api separately from the topic modelling process is probably a nice trick. I'll give it a whirl.

**Comment by MaartenGr** [comment]
@thundergore I would not advise doing this outside of BERTopic. The representative documents are actually used within BERTopic to create the representations. An easier alternative would be to use tiktoken as the tokenizer variable. Definitely worth trying out!

**Comment by linxule** [comment]
Agreed. Using tiktoken correctly count tokens would be my first choice too. Sorry I didn't realize there's a new function for `bertopic.representation.OpenAI` to truncate documents and specify `nr_docs`. That makes things much easier!

**Comment by thundergore** [comment]
Thanks for the continued feedback guys - `tiktoken`was also very very slow unfortunately.

I'll keep iterating and see if I can improve speeds somehow.

**Comment by MaartenGr** [comment]
@thundergore Could you share your **full** code? An end-to-end example. Make sure to leave nothing out. 

The reason why I ask is because the following is working perfectly fine for me:

```python
from datasets import load_dataset
from bertopic import BERTopic
from sentence_transformers import SentenceTransformer
import tiktoken
import openai
from bertopic.representation import OpenAI
from bertopic import BERTopic
from umap import UMAP

# We select a subsample of 5000 abstracts from ArXiv
dataset = load_dataset("CShorten/ML-ArXiv-Papers")["train"]
docs = dataset["abstract"][:5_000]

# Embed documents
sentence_model = SentenceTransformer("thenlper/gte-small")
embeddings = sentence_model.encode(docs)

# Fix seed
umap_model = UMAP(n_neighbors=15, n_components=5, min_dist=0.0, metric='cosine', random_state=42)

# Tokenizer
tokenizer= tiktoken.encoding_for_model("gpt-3.5-turbo")
client = openai.OpenAI(api_key="sk-...")
openai_model = OpenAI(
    client,
    model="gpt-3.5-turbo", 
    exponential_backoff=True, 
    chat=True, 
    nr_docs=1,
    doc_length=100,
    tokenizer=tokenizer,
    diversity=0.1, 
)

# Use the representation model in BERTopic on top of the default pipeline
topic_model = BERTopic(
    umap_model=umap_model,
    min_topic_size=30,
    representation_model=openai_model,
    verbose=True
).fit(docs, embeddings)
```

**Comment by thundergore** [comment]
Thank you for your time and feedback guys. 

I have come to the following conclusions: 

- The script you included above _does not_ work for me 
- The script you included above _works_ for me if I adjust the parameters to generate an output of less than 3 final topics
- My code  _works_ for me if I adjust the parameters to generate an output of less than 3 final topics
- - Both the script above and my own code get stuck when it goes above 3 requests (I think you might see where I'm going now)

The OpenAI details I was given - which I thought were a touch better than the free tier - appear to be on the standard rate limit structure: https://platform.openai.com/docs/guides/rate-limits?context=tier-free

So... basically, the 3 RPM limit appears to be what is causing this. 

There are a few tests I can do to 100% confirm this. But right now I'm satisfied that it's nothing to continue a github discussion around :)

Note/

I have managed to sanitize the code I need to share now (if I need further support on this topic) so next time I won't be so unhelpful in terms of what code I'm sending :)

**Comment by thundergore** [comment]
I got my hands on a proper tier and I can confirm there are no more speed concerns. 

Thank you for your time guys.
