### ISSUE TITLE
Store topic embeddings in a vector database for search over a list of docs

### ISSUE THREAD

**Issue by z3ugma** [MaartenGr/BERTopic#1689]
Hi there - here's my intended workflow: 

1. Gather `docs`, each of which is a row in a database 
2. Use BERTopic to model topics and get the probabilities of each topic for a given document, e.g. by `all_points_membership_vectors` 
3. Store an embedding vector related to that document in a vector database. That vector will store the probabilities of every topic for the given document.
4. _User "likes" a series of documents_
5. Pass in the list of documents to a "find more like these" search function.
6. This function takes the multiple documents, calculates the embedding vector for each, and calculate some derived "average vector" of the whole list of "more like these" documents.
7. Use that average vector to find the top N documents that are similar to the list of already "liked" documents. 

Is BERTopic the right tool for this job, and if so, what's the right vector to store in a vector DB for similarity search **of a list of documents**? 

Most of the documentation shows how to get the similarity of exactly one document.

**Comment by MaartenGr** [comment]
Thanks for sharing this! I have a few questions:

> Use BERTopic to model topics and get the probabilities of each topic for a given document, e.g. by all_points_membership_vectors

This is done by setting `calculate_probabilities=True` right? Or are you calculating those yourself? 

> Store an embedding vector related to that document in a vector database. That vector will store the probabilities of every topic for the given document.

I am a bit confused, are you reffering to the actual embedding of the document (e.g., through SBERT) or the probability vector of the document?

> Is BERTopic the right tool for this job, and if so, what's the right vector to store in a vector DB for similarity search of a list of documents?

Sure, BERTopic can be used for this. I am just wondering where the actual topic modeling is here. Do you also want additional topic representations for these documents? If you are only interested in getting similar documents, why not just create embeddings for each document and run an input document through cosine similarity? A vector database, like FAISS, could easily handle this. 

> Most of the documentation shows how to get the similarity of exactly one document.

Just pass more than one document in the cosine similarity metric and just will get a distance matrix.

**Comment by z3ugma** [comment]
> Thanks for sharing this! I have a few questions:
> 
> > Use BERTopic to model topics and get the probabilities of each topic for a given document, e.g. by all_points_membership_vectors
> 
> This is done by setting `calculate_probabilities=True` right? Or are you calculating those yourself?
yes, by setting calculate_probabilities=True


> 
> > Store an embedding vector related to that document in a vector database. That vector will store the probabilities of every topic for the given document.
> 
> I am a bit confused, are you reffering to the actual embedding of the document (e.g., through SBERT) or the probability vector of the document?

The probability vector of the document - the likelihood that the document belongs to a given topic 

> 
> > Is BERTopic the right tool for this job, and if so, what's the right vector to store in a vector DB for similarity search of a list of documents?
> 
> Sure, BERTopic can be used for this. I am just wondering where the actual topic modeling is here. Do you also want additional topic representations for these documents? If you are only interested in getting similar documents, why not just create embeddings for each document and run an input document through cosine similarity? A vector database, like FAISS, could easily handle this.

Yes exactly! I want to take some vector and stored that in a vector store like FAISS.


> > Most of the documentation shows how to get the similarity of exactly one document.
> 
> Just pass more than one document in the cosine similarity metric and just will get a distance matrix.

What will be the shape of the distance matrix? e.g. if I pass in 10 documents, will I get a (10,1) vector? 
I want to pass in 10 documents and be recommended the 1 document that is most close to all 10, or most close to the "average" of the 10.

**Comment by MaartenGr** [comment]
> What will be the shape of the distance matrix? e.g. if I pass in 10 documents, will I get a (10,1) vector?
I want to pass in 10 documents and be recommended the 1 document that is most close to all 10, or most close to the "average" of the 10.

That depends on the two sets of things you are comparing. If you pass 10 documents and you want it to compare to all other documents, for instance 10_000, you will get a 10 x 10_000 matrix. Then, you can simply extract the highest matching document. If you average the 10 documents and then pass it to the similarity function, you will get a 1 x 10_000 matrix and you only need to extract a single value instead of 10.

**Comment by z3ugma** [comment]
>If you average the 10 documents and then pass it to the similarity function, you will get a 1 x 10_000 matrix and you only need to extract a single value instead of 10. 

yes, an average of the 10 documents and the (1,10k) matrix where I pick the highest single value. 

Is this literally calculating the average? There's not a more complicated math operation I need to be doing with the 10 probability vectors, just elementwise average the 10 across all topics?

**Comment by MaartenGr** [comment]
For now, that should be a good start. You could always go into more complex methodologies but I believe this should be a good baseline. You could consider running an embedding-based vector database instead of a probability-based vector database, but I would start as simple as possible. Then, with enough experience, you can start building up.
