### ISSUE TITLE
hierarchical_topics: unused variable cluster_df significantly slowing down performance

### ISSUE THREAD

**Issue by shadiakiki1986** [MaartenGr/BERTopic#1698]
The variable `cluster_df` seems not to be used anywhere in the function: https://github.com/MaartenGr/BERTopic/blob/master/bertopic/_bertopic.py#L1008

The `groupby` call in it is the slowest line in the function too.

Maybe better remove it

**Comment by MaartenGr** [comment]
Thanks! Should be indeed removed. If you want, a PR is appreciated. Otherwise, I'll put it on the list for next year.
