### ISSUE TITLE
 NumbaWarning: The TBB threading layer is disabled

### ISSUE THREAD

**Issue by ElisaDistante** [MaartenGr/BERTopic#170]
![photo_2021-07-06_13-28-55](https://user-images.githubusercontent.com/34309167/124598973-7cb17580-de65-11eb-9100-04a308ac05dd.jpg)

Hi, 
I'm facing this issue while running the notebook in Colab. I've been using the package for some weeks and I've never seen this error. It seems related with numba, I've tried to install tpp as suggested in the error message, but it was already installed. 
The installed version of numba was 0.51.2, I've upgraded it to 0.53.1, but it did not solve.

Any suggestions?
Thank you,
Elisa

**Comment by enliktjioe** [comment]
I've got the exactly same issue in Google Colab, waiting for the updates

**Comment by MaartenGr** [comment]
This seems to be a `pynndescent` issue which is used within `umap`. The solution seems to be downgrading pynndescent with `pip install pynndescent==0.5` after installing BERTopic. There seem to be more users with this issue ([here](https://github.com/lmcinnes/pynndescent/issues/129), [here](https://github.com/theislab/scanpy/issues/1931), and [here](https://github.com/lmcinnes/umap/issues/717)). 

It is not the perfect solution but we will unfortunately have to wait until pynndescent gets updated.

**Comment by keshav-b** [comment]
@MaartenGr Downgrading seems to work, but what's the permanent fix for this?

**Comment by ElisaDistante** [comment]
Thank you @MaartenGr 
But downgrading did not work for me, I get this error when I import BERTopic. 

![Cattura](https://user-images.githubusercontent.com/34309167/124637469-10953880-de8a-11eb-98ba-2787200b3b25.PNG)

Maybe I'm missing something.
However now I'm running the notebook on my local machine and it works.

**Comment by feusagittaire** [comment]
I'm having this issue too, gonna try Marteen solution ;/

**Comment by MaartenGr** [comment]
@enliktjioe @keshav-b @ElisaDistante @feusagittaire 
It seems that a newer version of `pynndescent` was already released which seemed to have fixed the issue. I would advise starting from a fresh environment and install BERTopic from there. That will allow `pynndescent` v0.5.4 to be installed.

**Comment by feusagittaire** [comment]
@MaartenGr I tried your tip of downgrading `pynndescent` and it worked! I tried to start a new google colab notebook, but it doesn't seemed to do any change. But thanks for the suggestion, saved my life!
