### ISSUE TITLE
OpenAI embedding Backend

### ISSUE THREAD

**Issue by Afsulami** [MaartenGr/BERTopic#1707]
I was trying to use the OpenAI embedding for a TopicModelling task when I stumbled on this issue.
"""
APIRemovedInV1: 

You tried to access openai.Embedding, but this is no longer supported in openai>=1.0.0 - see the README at https://github.com/openai/openai-python for the API.

You can run `openai migrate` to automatically upgrade your codebase to use the 1.0.0 interface. 

Alternatively, you can pin your installation to the old version, e.g. `pip install openai==0.28`

A detailed migration guide is available here: https://github.com/openai/openai-python/discussions/742
"""

**Comment by MaartenGr** [comment]
Thanks for sharing this! This should indeed be updated to be in line with the new openai version. You might be able to use an earlier version of openai though in the mean time.

With respect to a fix, I do not have much time the coming weeks so if anyone else wants to tackle this, it would be appreciated! It should be rather straightforward as I already did the same here: 

https://github.com/MaartenGr/BERTopic/blob/master/bertopic/representation/_openai.py

**Comment by chentitus** [comment]
I got stuck in the same issue when I (1) implemented topic_model.update_topics, or (2) initialized a BERTopic model with KeyBERT as the representation_model. I can implement both of them after downgrading the version of openai to 0.28, but then I can't implement client = openai.OpenAI(api_key="sk...").

**Comment by peguerosdc** [comment]
I was facing the issue and opened a PR with the fix! Please let me know what do you think.

**Comment by uahmad235** [comment]
Is it strange that the PR is merged but i still get older code in `bertopic/backend/_openai.py` file:
I installed using `pip install bertopic`. 
I am using Azure deployment like this:
```python
import openai
from bertopic import BERTopic
from bertopic.backend import OpenAIBackend
embedding_model = OpenAIBackend(client, "xyz", batch_size=50)
topic_model = BERTopic(embedding_model=embedding_model)
```
Here's my code from `_openai.py` file which is apparently different from the one in repo:
```python
def embed(self,
              documents: List[str],
              verbose: bool = False) -> np.ndarray:
        """ Embed a list of n documents/words into an n-dimensional
        matrix of embeddings

        Arguments:
            documents: A list of documents or words to be embedded
            verbose: Controls the verbosity of the process

        Returns:
            Document/words embeddings with shape (n, m) with `n` documents/words
            that each have an embeddings size of `m`
        """
        # Batch-wise embedding extraction
        if self.batch_size is not None:
            embeddings = []
            for batch in tqdm(self._chunks(documents), disable=not verbose):
                response = openai.Embedding.create(input=batch, **self.generator_kwargs)
                embeddings.extend([r["embedding"] for r in response["data"]])

                # Delay subsequent calls
                if self.delay_in_seconds:
                    time.sleep(self.delay_in_seconds)

        # Extract embeddings all at once
        else:
            response = openai.Embedding.create(input=documents, **self.generator_kwargs)
            embeddings = [r["embedding"] for r in response["data"]]
        return np.array(embeddings)
 ```

Python version: 3.8.10
BERTopic version: 0.16.0
openai version: 1.10.0

Am i missing something here?

**Comment by MaartenGr** [comment]
@uahmad235 

> Is it strange that the PR is merged but i still get older code in bertopic/backend/_openai.py file:

Not really since you installed the package through `pip install bertopic` and not via the latest commit. I would advise installing BERTopic from the main branch.
