### ISSUE TITLE
How to visualize topics from own embeddings? 

### ISSUE THREAD

**Issue by saikot-paul** [MaartenGr/BERTopic#1730]
Hello, 

I have a question regarding using your own embeddings to create plots. Below is the code I am using, the issue I am having is that when passing the embeddings to the visualize documents method, I am not getting the same plot

`
def get_zeroshot_topics(docs, zeroshot_topic_list):
    topic_model = BERTopic(
        embedding_model="sentence-transformers/all-MiniLM-L6-v2",
        min_topic_size=15,
        zeroshot_topic_list=zeroshot_topic_list,
        zeroshot_min_similarity=.55,
        representation_model=KeyBERTInspired()
    )
    topics, _ = topic_model.fit_transform(docs)

    return topics, topic_model

#Dataframe has dimension reduced embeddings 
df = pd.read_csv('./data.csv')
docs = df['Text']

topics, topic_model = get_zeroshot_topics(docs, zeroshot_topic_list)

embeddings = df[['Dim1', 'Dim2']].values

topic_model.visualize_documents(docs)

topic_model.visualize_documents(docs, embeddings)
`

**Comment by MaartenGr** [comment]
You cannot pass embedding to `visualize_topics`. See the documentation here: https://github.com/MaartenGr/BERTopic/blob/master/bertopic/plotting/_topics.py and here: https://maartengr.github.io/BERTopic/api/plotting/topics.html

**Comment by saikot-paul** [comment]
There was an error in the code, I meant to reference the visualize documents method

**Comment by MaartenGr** [comment]
Did you check the docstrings of the method? You should use the same way of reducing embeddings to get the same results: https://maartengr.github.io/BERTopic/api/plotting/documents.html

**Comment by saikot-paul** [comment]
Thank you, so the issue was with a difference of reducing dimensions in the BERTopic class and my own reduced embeddings.

**Comment by MaartenGr** [comment]
Most likely yes, it depends on what kind of embeddings you passed, whether they were reduced and whether you passed to the embeddings or reduced embeddings param. Either way, the link above should provide the explanation together with how the embeddings are reduced within the function:

https://github.com/MaartenGr/BERTopic/blob/e2191f052d1461e95634ba52ccc44e4626a13db3/bertopic/plotting/_documents.py#L122
