### ISSUE TITLE
Incorrect label in ZeroShot doc SVG

### ISSUE THREAD

**Issue by nicholsonjf** [MaartenGr/BERTopic#1732]
Link to page containing the SVG: https://maartengr.github.io/BERTopic/getting_started/zeroshot/zeroshot.html

In the first image that appears on the above page, the "Zero-shot topic 1" in the "embed the labels" step is labeled as "Religion" when it should be "Clustering."

<img width="748" alt="Screenshot 2024-01-09 at 8 29 18 PM" src="https://github.com/MaartenGr/BERTopic/assets/4286084/b291f0d3-68af-4e15-8b4c-8ea95794a73d">

**Comment by MaartenGr** [comment]
Thanks! That should indeed be "Clustering". I'll update it somewhere in the coming weeks.

**Comment by MaartenGr** [comment]
I added a new version of the image in the main branch and will update the docs when a new release is available.
