### ISSUE TITLE
Language embedding in KeyBertInspired

### ISSUE THREAD

**Issue by hubernst** [MaartenGr/BERTopic#1739]
Hello, 

1000 thanks for your fantastic work. 

I am currently running BERTopic with German language and using TransformerDocumentEmbeddings('dbmdz/bert-base-german-uncased') for the embedding_model in the first step. It shows better results than "paraphrase-multilingual-MiniLM-L12-v2".
I would like to make sure, and unfortunately I can't find any other way than writing to you, if the embeddings from step 1 are used in KeyBERTInspired?

Thank you very much

**Comment by MaartenGr** [comment]
Yes, the embeddings are indeed used together with the same embedding model for calculating the words in KeyBERT.

**Comment by hubernst** [comment]
I had hoped so. Thanks for your quick response.
