### ISSUE TITLE
Get all the topics a document belongs to

### ISSUE THREAD

**Issue by alexdutheil** [MaartenGr/BERTopic#1742]
Hi,

I am using a BERTopic model and I want to get all the topics a document belongs to.
I tried using `.approximate_distribution()` but when I analyse the `topic_distr` it returns, I find 74 documents for which I only have 0s, whereas `.get_topic_info()` inform me there are only 28 outliers.
 
Did I misunderstand something? Or does anyone have a solution to this?

Thanks in advance

**Comment by MaartenGr** [comment]
You can use `get_doc_info` to get the topics associated with each document. If you want the distribution of topics, you can use the `probs` that were calculated with `calculate_probabilities=True`

**Comment by alexdutheil** [comment]
Thank you for your answer!
However, `.get_document_info()` doesn't solve my problem because it only returns THE topic a document belongs to, and not every topics (if I'm not wrong).
I also thought about using `probs`, but I don't know how to update it after I used `.reduce_outliers()`.  Is there a way to do this ?

**Comment by MaartenGr** [comment]
You can access the probs with topic_model.probs_

**Comment by alexdutheil** [comment]
`topic_model.probabilities_` returns the same output before and after I use `.reduce_outliers()`. 
Moreover, I don't really understand how the probs work. Is there a probability-threshold for a topic to be associated with a document?
Sorry to disturb you and thanks a lot for your help.

**Comment by MaartenGr** [comment]
Did you update the topics after running `.reduce_outliers`? You need to update the internal topics which `reduce_outliers` doesn't do for experimentation purposes. You can find the full documentation about it here: https://maartengr.github.io/BERTopic/getting_started/outlier_reduction/outlier_reduction.html

The threshold is one for you to decide.

**Comment by alexdutheil** [comment]
Here is what I did:
```python
topic_model = BERTopic(
    embedding_model = embedding_model,    # Embeddings
    umap_model = umap_model,    # Dimensionality Reduction
    hdbscan_model = hdbscan_model,    # Clustering
    vectorizer_model = vectorizer_model,    # Tokenizer
    ctfidf_model = ctfidf_model,    # Weighting Scheme
    representation_model = representation_model,    # Fine-tuning
    calculate_probabilities = True
)

topics, probs = topic_model.fit_transform(docs)
``` 

```python
topic_model.topics_[8]
``` 
Output: `-1`

```python
print(topic_model.probabilities_[8])
``` 
`[0.00618228 0.00619034 0.00507448 0.0108743  0.00510572 0.00943717
 0.00463788 0.00696931 0.00590711 0.00766384 0.00909726 0.0089643
 0.01004111 0.00937928 0.00719003 0.00285193 0.00392913 0.00976448
 0.00076294 0.00333003 0.00585592 0.00879746 0.00553511 0.00126459
 0.00770484 0.00549343 0.01950007 0.00360455 0.02253529 0.01004729
 0.02826133 0.00765457 0.00924663 0.0105192  0.00511417 0.00927131
 0.00562799 0.00796138]`

After that I run:
```python
new_topics = topic_model.reduce_outliers(docs, topics, strategy = 'distributions')

topic_model.update_topics(
    docs, 
    topics = new_topics,
    vectorizer_model = vectorizer_model,
    ctfidf_model = ctfidf_model,
    representation_model = representation_model
)
``` 

```python
topic_model.topics_[8]
``` 
Output: `4`

```python
print(topic_model.probabilities_[8])
``` 
Output: 
`[0.00618228 0.00619034 0.00507448 0.0108743  0.00510572 0.00943717
 0.00463788 0.00696931 0.00590711 0.00766384 0.00909726 0.0089643
 0.01004111 0.00937928 0.00719003 0.00285193 0.00392913 0.00976448
 0.00076294 0.00333003 0.00585592 0.00879746 0.00553511 0.00126459
 0.00770484 0.00549343 0.01950007 0.00360455 0.02253529 0.01004729
 0.02826133 0.00765457 0.00924663 0.0105192  0.00511417 0.00927131
 0.00562799 0.00796138]`

So the probs didn't change. 

And moreover, if for instance I print this:
```python
print(topic_model.probabilities_[0])
``` 
`[0.00731677 0.02172591 0.00652732 0.00936177 0.00678475 0.01113554
 0.00675337 0.01810555 0.01160561 0.01076525 0.01128493 0.01164117
 0.0111034  0.01349915 0.12364177 0.00513609 0.00940835 0.0101068
 0.00155713 0.0060548  0.00720698 0.01219292 0.00793597 0.0027621
 0.01286715 0.01198767 0.01534488 0.00882314 0.00915669 0.01108257
 0.01402651 0.0138075  0.01175892 0.01265278 0.0097994  0.01866897
 0.00823272 0.02072858]`
How do I know which topics document 0 is associated to? This is what I meant when I talked about threshold (in document 0, we find topics whose probs > threshold).

**Comment by MaartenGr** [comment]
> So the probs didn't change.

That is actually to be expected since the topics themselves did not change. The underlying HDBSCAN model did not change nor were any of the topics merged (which would lead to probability matrices needing to be merged). In other words, the probabilities should not change if we are not affecting the underlying HDBSCAN soft-clustering process. `.reduce_outliers` changes the assignment process and instead of assigning to -1, it takes the next most logical topic but that does not change the probability. 

> How do I know which topics document 0 is associated to? This is what I meant when I talked about threshold (in document 0, we find topics whose probs > threshold).

The threshold is one for you to decide based on introspection of the distributions. There is not one set value that you should pursue. In practice, this would therefore be a manual selection since distributions can change drastically.

**Comment by alexdutheil** [comment]
Oh ok I understand! 

Thank you very much for your time and your pedagogy. Have a nice day!
