### ISSUE TITLE
tbb warning

### ISSUE THREAD

**Issue by makkarss929** [MaartenGr/BERTopic#175]
```
/usr/local/lib/python3.7/dist-packages/numba/np/ufunc/parallel.py:363: NumbaWarning: The TBB threading layer requires TBB version 2019.5 or later i.e., TBB_INTERFACE_VERSION >= 11005. Found TBB_INTERFACE_VERSION = 9107. The TBB threading layer is disabled.warnings.warn(problem)
```
In umap, I am seeing this warning

**Comment by MaartenGr** [comment]
This is an issue with a previous version of `pynndescent`. It should be resolved by starting from a fresh environment and reinstalling BERTopic. Make sure you then check you have the newest version of `pynndescent`. You can find more about that in [this](https://github.com/MaartenGr/BERTopic/issues/170) thread which is currently opened. I will close this for now as there already is a larger thread open with the same issue.
