### ISSUE TITLE
How to stabilize number of topics across runs?

### ISSUE THREAD

**Issue by MaggieMeow** [MaartenGr/BERTopic#1763]
Hi, there! Thank you very much for the great package!

I understand that BERTopic is stochastic so it's impossible to keep the topic number constant across runs. However, while keeping input and all hyperparameters constant (including random_state for UMAP), BERTopic can generate vastly different number of topics across runs (e.g. 8 topics for one iteration and 20 for the next). Is there any way to help stabilize the number of topics across runs?

**Comment by MaartenGr** [comment]
Thanks for the kind words!

It is not so much that BERTopic is inherently stochastic but that UMAP is (if you are using default settings). However, if you use `random_state` in UMAP, then it should make sure that the output is consistent between runs as it prevents that stochastic behavior. In other words, that should stabilize the number of topics across runs. 

If that is not the case, then it might be that you have selected other underlying models (`embedding_model`, `umap_model`, `hdbscan_model`, etc.) that additionally introduce some randomness. 

Either way, if everything is set to default, if you set the random state of UMAP it should completely prevent stochastic behavior as mentioned in the [FAQ](https://maartengr.github.io/BERTopic/faq.html#why-are-the-results-not-consistent-between-runs).

**Comment by MaggieMeow** [comment]
Thank you for the prompt reply.

The FAQ suggests setting random_state for UMAP which I have done and I'm using pre-generated sentence embeddings which are fixed across runs. For hdbscan_model, I'm using HDBSCAN with a set random_state. Yet I'm still getting very different number of topics across runs, which is baffling.

Here's my code for the model setup:
```
umap_model = UMAP(n_neighbors=10, n_components=6, min_dist=0.0, metric='cosine', random_state=0)
hdbscan_model = HDBSCAN(min_cluster_size=10, metric='euclidean', cluster_selection_method='eom', prediction_data=True, random_state=0)
vectorizer_model = CountVectorizer(stop_words="english")
ctfidf_model = ClassTfidfTransformer(reduce_frequent_words=True)
pos_model = PartOfSpeech("en_core_web_sm")

topic_model = BERTopic(n_gram_range=(1, 2), verbose=True, nr_topics=None, min_topic_size=10,
                       top_n_words=20,
                       vectorizer_model=vectorizer_model,
                       ctfidf_model=ctfidf_model,
                       representation_model = pos_model,
                       )

topics, probs = topic_model.fit_transform(bertopic_df['cleanedTextBert'], embeddings=embedding)
```

**Comment by MaggieMeow** [comment]
Thank you very much for your kind reply. It turned out that my umap_model hyperparameters with random_state were not successfully applied during training and fixing that has ensured reproducible topics.
