### ISSUE TITLE
How to find the most dissimilar topics for a given search term or topic id

### ISSUE THREAD

**Issue by vblagoje** [MaartenGr/BERTopic#177]
Hi, is there a way to find the topk most dissimilar topics for a given query or topic id? TIA

**Comment by MaartenGr** [comment]
You can use `topic_model.visualize_heatmap()` to get a similarity matrix of all topics. This should help in identifying dissimilar topics. However, if you are looking for a specific topic, you can use the following:

```python
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np 

topic = 1

embeddings = np.array(topic_model.topic_embeddings)
distance_matrix = cosine_similarity(embeddings)
dissimilar_topic = np.argmin(distance_matrix[topic])
```

You can also using `embeddings = topic_model.c_tf_idf` instead to use a different topic representation.

**Comment by vblagoje** [comment]
Thanks @MaartenGr I got the ten topk dissimilar topics using: `torch.topk(torch.from_numpy(distance_matrix[topic]), k=10, largest=False)[1].tolist()`

**Comment by MaartenGr** [comment]
Great, glad to hear it worked out!
