### ISSUE TITLE
topic_model.topics_over_time raises an error 'index (3407) out of range'

### ISSUE THREAD

**Issue by kungmo** [MaartenGr/BERTopic#1772]
Hello.

Thanks for distributing a great text mining package.

I got an error like this.

![스크린샷 2024-01-29 오후 5 30 51](https://github.com/MaartenGr/BERTopic/assets/19389927/1a8a4fb6-d304-407c-a4cb-48a41ae89b39)

When I execute the last line, it raises an error.

![스크린샷 2024-01-29 오후 5 27 32](https://github.com/MaartenGr/BERTopic/assets/19389927/2fa45ccd-1eaf-4039-8e73-75c781d36016)

The lists - question_list, topics, timestamps - have all same length.

And timestamps list has a type like this.
![스크린샷 2024-01-29 오후 5 32 45](https://github.com/MaartenGr/BERTopic/assets/19389927/e615c4d2-b11b-4928-a6a2-6ce6e8019549)

How can I solve this problem?

Thank you.

**Comment by MaartenGr** [comment]
Make sure to always check the order of parameters you are passing to a function. it is `docs, timestamps, topics` and not `docs, topics, timestamps`:

https://github.com/MaartenGr/BERTopic/blob/c38d1c804ac518f6accad4ef49dcd873e955cb41/bertopic/_bertopic.py#L700-L704

I would advise using keyword arguments instead to prevent these kinds of issues.

**Comment by kungmo** [comment]
> Make sure to always check the order of parameters you are passing to a function. it is `docs, timestamps, topics` and not `docs, topics, timestamps`:
> 
> https://github.com/MaartenGr/BERTopic/blob/c38d1c804ac518f6accad4ef49dcd873e955cb41/bertopic/_bertopic.py#L700-L704
> 
> I would advise using keyword arguments instead to prevent these kinds of issues.

I apologize my careless for checking parameters. Thank you. It works!
