### ISSUE TITLE
AttributeError: 'Pooling' object has no attribute 'pooling_mode_weightedmean_tokens'

### ISSUE THREAD

**Issue by lillyhope** [MaartenGr/BERTopic#1778]
After  a year and half running fine, these couple of days I started getting below error.. Can you please tell me what changes i have to make.
AttributeError: 'Pooling' object has no attribute 'pooling_mode_weightedmean_tokens'
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<command-3261006126844853> in <cell line: 4>()
      2 doc=list(df_10["final_clean"].values)
      3 freq=model_10.get_topic_info()
----> 4 pred=model_10.transform(doc)
      5 gh=pred[0]
      6 df_10['Topic']=gh

This is the code for prediction. 
model_10=joblib.load(file_path)
doc=list(df_10["final_clean"].values)
freq=model_10.get_topic_info()
pred=model_10.transform(doc)
gh=pred[0]
df_10['Topic']=gh
result=pd.merge(df_10,freq,on="Topic")

**Comment by MaartenGr** [comment]
Please share your full code and error messages. Without it, it is difficult to know what is happening here. Could you also describe in more detail what your environment is? For instance, the difference in our environment (Python, BERTopic versions) between then and now.

**Comment by tonizzz** [comment]
The issue comes from the sentence-transformers package. installing the version 2.2.2 (the one previous to 30 of jan) makes bertopic to work again fine

**Comment by SitwalaM** [comment]
I can confirm that this is a sentence-transformers issue. I could not run predictions on a trained SetFit model after loading it using joblib. Initially, I was simply installing the latest sentence-transformers in google colab. Going back to sentence_transformers==2.2.1 fixed the problem for me. Model was trained using setfit==0.5.0. The code below produced the same error.

```python
trainer = joblib.load(<path to trained setfit model>)
trainer.model.predict(["text"])
```

**Comment by lillyhope** [comment]
Thank you all for response. True i read some where that is it with transformer update, but since i didn't manually install transformer separately from Bertopic, i didn't know what to do with it.  Now installing sentence-transformer==2.2.1 and bertopic ==0.15.0.. I started getting a new error on joblib.load(file_path)...    "type error: _ rebuild() got an unexpected keyword argument 'impl_kind' "

**Comment by MaartenGr** [comment]
@lillyhope 

> Please share your full code and error messages. Without it, it is difficult to know what is happening here. Could you also describe in more detail what your environment is? For instance, the difference in our environment (Python, BERTopic versions) between then and now.

The above is still necessary to get a complete picture. For instance, did you make sure that the environment in which you loaded and saved BERTopic is **exactly** the same? Are all (sub-)dependencies being version-controlled and kept the same? If not, then that is your issue. 

Whenever you use pickle and joblib to save any model, you will need to make sure that you load and save your model in the same environment. That is to prevent any break changes to sub-dependencies that the model cannot take into account.

**Comment by lillyhope** [comment]
@MaartenGr  for both training and predicting using python , pyspark but converted the df to pandas. I trained and saved the model a year ago, I didn't specify the version when I installed it. Since then it is been predicting the daily incremental data. End of January is when the error started to occur. For prediction I was using Bertopic version 0.15.0. It Is in spark. Please  let me know if you want me to specify anything else.  The short code for training, saving and predicting is below
cluster_model = KMeans(n_clusters=50)
#topic_model = BERTopic(hdbscan_model=cluster_model)
#doc=list(processed_issue_pandas['final'].values)
hdbscan_model=HDBSCAN(min_samples=30,gen_min_span_tree=True,prediction_data=True)
ctfidf_model = ClassTfidfTransformer(reduce_frequent_words=True)
#vectorizer_model = CountVectorizer(stop_words="english")
umap_model = UMAP.UMAP(n_neighbors=25, n_components=5, min_dist=0.0, metric='cosine', random_state=42)
model=BERTopic(umap_model=umap_model,hdbscan_model=cluster_model,verbose=True,embedding_model='all-MiniLM-L6-v2')

pickled_model = pickle.dumps(model)
# Create a DataFrame with a single column 'model' containing the pickled model
df = spark.createDataFrame([(pickled_model,)], ['model'])
================
model_10=joblib.load(file_path)
doc=list(df_10["final_clean"].values)
freq=model_10.get_topic_info()
pred=model_10.transform(doc)
gh=pred[0]
df_10['Topic']=gh
result=pd.merge(df_10,freq,on="Topic")

**Comment by MaartenGr** [comment]
> I trained and saved the model a year ago, I didn't specify the version when I installed it. Since then it is been predicting the daily incremental data. End of January is when the error started to occur. For prediction I was using Bertopic version 0.15.0. It Is in spark. Please let me know if you want me to specify anything else. The short code for training, saving and predicting is below

The problem lies with your environment. Whenever you use `pickle`, it is vital that you save an **exact** replica of your environment since `pickle` assumes that the environment stays relatively similar between saving and loading the model. This is why additional [serialization options](https://maartengr.github.io/BERTopic/getting_started/serialization/serialization.html) were introduced in BERTopic to circumvent some of these difficulties. 

However, since you are using `pickle`, make sure that you track back which packages you likely used when you saved the model a year ago. A good strategy would be to look at the dependencies of BERTopic and check their latest version at that date (e.g., [sentence-transformers](https://pypi.org/project/sentence-transformers/#history)). If you install those, before installing BERTopic v0.15 (if you used that version to save the model), then it might just work. 

Next time, I would highly advise version controlling your entire environment when using something in production. It prevents a lot of headaches when saving/loading models.

**Comment by MaartenGr** [comment]
Glad to hear that you solved the issue!
