### ISSUE TITLE
visualize_hierarchy() fails - scipy.array deprecated

### ISSUE THREAD

**Issue by aadityabhatia** [MaartenGr/BERTopic#1791]
With scipy v1.12.0, `topic_model.visualize_hierarchy()` fails with the error `AttributeError: Module 'scipy' has no attribute 'array'`. 

This appears to be a result of scipy/scipy#19067 also noted in scipy/scipy#19972.

**Comment by zengql97** [comment]
Thanks for sharing, I met the same issue as well. Should we downgrade our scipy to solve it? I didn’t see scipy.array or something similar is used in the code explicitly.

**Comment by kamaldsingh** [comment]
facing the same issue. Downgrading scipy to 1.11.4 worked for me.

**Comment by MaartenGr** [comment]
It was fixed in the main branch of Plotly (https://github.com/plotly/plotly.py/pull/4487, which is where this issue originates from) so you can also install Plotly from the latest commit or wait until they release a new version.

**Comment by zengql97** [comment]
Thx guys. Solved.

**Comment by scottadvancingscientists** [comment]
@MaartenGr I'm new to this. Can you provide the specific command to install plotly from latest commit? 

pip install -e git+https://github.com/plotly/plotly.py/tree/23b42327b070133a0f6361c095634d9cb618f6d2#egg=plotly

Obtaining plotly from git+https://github.com/plotly/plotly.py/tree/23b42327b070133a0f6361c095634d9cb618f6d2#egg=plotly
  Cloning https://github.com/plotly/plotly.py/tree/23b42327b070133a0f6361c095634d9cb618f6d2 to ./src/plotly
  Running command git clone --filter=blob:none --quiet https://github.com/plotly/plotly.py/tree/23b42327b070133a0f6361c095634d9cb618f6d2 /home/ec2-user/src/plotly
  fatal: repository 'https://github.com/plotly/plotly.py/tree/23b42327b070133a0f6361c095634d9cb618f6d2/' not found
  error: subprocess-exited-with-error
  
  × git clone --filter=blob:none --quiet https://github.com/plotly/plotly.py/tree/23b42327b070133a0f6361c095634d9cb618f6d2 /home/ec2-user/src/plotly did not run successfully.
  │ exit code: 128
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× git clone --filter=blob:none --quiet https://github.com/plotly/plotly.py/tree/23b42327b070133a0f6361c095634d9cb618f6d2 /home/ec2-user/src/plotly did not run successfully.
│ exit code: 128
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by aadityabhatia** [comment]
The python setup file is located in a subdirectory, not at the top level of the repository. You have to add the subdirectory to the URL. Try the following:

```
$ pip install git+https://github.com/plotly/plotly.py.git#subdirectory=packages/python/plotly

...
Installing collected packages: plotly
  Attempting uninstall: plotly
    Found existing installation: plotly 5.18.0
    Uninstalling plotly-5.18.0:
      Successfully uninstalled plotly-5.18.0
Successfully installed plotly-5.18.0+88.g23b42327
```

**Comment by matallanas** [comment]
They have pushed a new version to pipy and everything seems to work fine again. So now you can directly install the package `pip install -U plotly==5.19.0`

**Comment by aadityabhatia** [comment]
Also available through [conda forge](https://anaconda.org/conda-forge/plotly). Closing the issue as resolved.
