### ISSUE TITLE
Zero-shot Topic Modeling and visualization "topics_per_class"

### ISSUE THREAD

**Issue by hubernst** [MaartenGr/BERTopic#1792]
Hello, I am currently working intensively with the great Zero Shot model.  I'm a fan of the visualizations, but in contrast to experiments with the Base model, I don't get any visualizations regarding _topics_over_time_ and _topics_per_class_. They both end with following error message. 

```
topic_model = BERTopic(
    verbose=True,
    min_topic_size = 30,
    #nr_topics = 5,
    zeroshot_topic_list=kategorien_1,
    zeroshot_min_similarity=.8,
    embedding_model=embedding_model,          # Step 1 - Extract embeddings
    umap_model=umap_model,                    # Step 2 - Reduce dimensionality
    hdbscan_model=hdbscan_model,              # Step 3 - Cluster reduced embeddings
    vectorizer_model=vectorizer_model,        # Step 4 - Tokenize topics
    ctfidf_model=ctfidf_model,                # Step 5 - Extract topic words
    representation_model=representation_model # Step 6 - (Optional) Fine-tune topic represenations
)

print(type(freitextantwort_list))
print(type(target_names_list))
topics_per_class = topic_model.topics_per_class(freitextantwort_list, target_names_list)

<class 'list'>
<class 'list'>
---------------------------------------------------------------------------
---------------------------------------------------------------------------
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Input In [171], in <cell line: 3>()
      1 print(type(freitextantwort_list))
      2 print(type(target_names_list))
----> 3 topics_per_class = topic_model.topics_per_class(freitextantwort_list, target_names_list)

File /opt/conda/envs/Python-3.10-Premium/lib/python3.10/site-packages/bertopic/_bertopic.py:880, in topics_per_class(self, docs, classes, global_tuning)
    878 check_documents_type(docs)
    879 documents = pd.DataFrame({"Document": docs, "Topic": self.topics_, "Class": classes})
--> 880 global_c_tf_idf = normalize(self.c_tf_idf_, axis=1, norm='l1', copy=False)
    881 
    882 # For each unique timestamp, create topic representations

File /opt/conda/envs/Python-3.10-Premium/lib/python3.10/site-packages/sklearn/preprocessing/_data.py:1786, in normalize(X, norm, axis, copy, return_norm)
   1783 else:
   1784     raise ValueError("'%d' is not a supported axis" % axis)
-> 1786 X = check_array(
   1787     X,
   1788     accept_sparse=sparse_format,
   1789     copy=copy,
   1790     estimator="the normalize function",
   1791     dtype=FLOAT_DTYPES,
   1792 )
   1793 if axis == 0:
   1794     X = X.T

File /opt/conda/envs/Python-3.10-Premium/lib/python3.10/site-packages/sklearn/utils/validation.py:871, in check_array(array, accept_sparse, accept_large_sparse, dtype, order, copy, force_all_finite, ensure_2d, allow_nd, ensure_min_samples, ensure_min_features, estimator, input_name)
    868 if ensure_2d:
    869     # If input is scalar raise error
    870     if array.ndim == 0:
--> 871         raise ValueError(
    872             "Expected 2D array, got scalar array instead:\narray={}.\n"
    873             "Reshape your data either using array.reshape(-1, 1) if "
    874             "your data has a single feature or array.reshape(1, -1) "
    875             "if it contains a single sample.".format(array)
    876         )
    877     # If input is 1D raise error
    878     if array.ndim == 1:

ValueError: Expected 2D array, got scalar array instead:
array=nan.
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.
```

Is it theoritically possible, just my fault, or impossible with Zero Shot? 
Thanks in advance

**Comment by MaartenGr** [comment]
Based on your code, you did not fit the model. I am assuming you did but that also means that there is missing code. Just in case, make sure to fit the model first. 

If that does not work, you can try checking whether you followed the parameters of `topics_per_class correctly`. 

If everything else fails, make sure to provide your **full* code and info related to your environment such as versions of BERTopic and Python.

**Comment by hubernst** [comment]
Hey, yes, code is missing sorry for that. 
I fitted the model via _fit_transfom()_. I copy my code right here, hopefully sufficient. 
Python = 3.10
Bertopic = 0.16.0


```
import pandas as pd 
import numpy as np

import spacy
import nltk 
from nltk.corpus import stopwords
from nltk.tokenize import sent_tokenize

from bertopic import BERTopic
from flair.embeddings import TransformerDocumentEmbeddings
from bertopic.representation import KeyBERTInspired
from keyphrase_vectorizers import KeyphraseCountVectorizer
#Plotly-Darstellung
import plotly.io as pio
pio.renderers.default = 'notebook_connected'

from umap import UMAP
from hdbscan import HDBSCAN
import sentence_transformers
from sklearn.feature_extraction.text import CountVectorizer

from bertopic import BERTopic
from bertopic.representation import KeyBERTInspired
from bertopic.vectorizers import ClassTfidfTransformer

# Step 1 - Extract embeddings
embedding_model = sentence_transformers.SentenceTransformer('/userfs/assets/data_asset/huggingface/paraphrase-multilingual-MiniLM-L12-v2')
# Step 2 - Reduce dimensionality
umap_model = UMAP(n_neighbors=10, n_components=10, min_dist=0.0, metric='cosine', random_state=42)
# Step 3 - Cluster reduced embeddings
hdbscan_model = HDBSCAN(min_cluster_size=30, metric='euclidean', cluster_selection_method='eom', prediction_data=False)
# Step 4 - Tokenize topics
stopwords_german=set(stopwords.words('german'))
vectorizer_model = CountVectorizer(ngram_range=(1, 3), stop_words=stopwords_german)
# Step 5 - Create topic representation
ctfidf_model = ClassTfidfTransformer(reduce_frequent_words=True, bm25_weighting=True)
# Step 6 - (Optional) Fine-tune topic representations with 
# a `bertopic.representation` model
representation_model = KeyBERTInspired()
# All steps together
topic_model = BERTopic(
    verbose=True,
    min_topic_size = 30,
    #nr_topics = 5,
    zeroshot_topic_list=kategorien_1,
    zeroshot_min_similarity=.5,
    embedding_model=embedding_model,          # Step 1 - Extract embeddings
    umap_model=umap_model,                    # Step 2 - Reduce dimensionality
    hdbscan_model=hdbscan_model,              # Step 3 - Cluster reduced embeddings
    vectorizer_model=vectorizer_model,        # Step 4 - Tokenize topics
    ctfidf_model=ctfidf_model,                # Step 5 - Extract topic words
    representation_model=representation_model # Step 6 - (Optional) Fine-tune topic represenations
)
topics = topic_model.fit_transform(freitextantwort_list)
topic_model.get_topic_freq()
```
![image](https://github.com/MaartenGr/BERTopic/assets/10818197/420b5c88-b399-4980-b6a0-bb28b46c26d6)
```
topic_model.visualize_topics()
```
![image](https://github.com/MaartenGr/BERTopic/assets/10818197/17253185-c153-4dd1-a5a9-27d97c35363b)
```
target_names = df_work["Kategorie 1"].fillna('missing')
target_names_list = target_names.to_list()
print(type(freitextantwort_list))
print(type(target_names_list))
print(len(freitextantwort_list))
print(len(target_names_list))

<class 'list'>
<class 'list'>
1341
1341

print(topic_model)
```
BERTopic(calculate_probabilities=False, ctfidf_model=ClassTfidfTransformer(...), embedding_model=<bertopic.backend._sentencetransformers.SentenceTransformerBackend object at 0x7f4c95f7ded0>, hdbscan_model=<bertopic.cluster._base.BaseCluster object at 0x7f4c4d6d4c10>, language=None, low_memory=False, min_topic_size=10, n_gram_range=(1, 1), nr_topics=None, representation_model=None, seed_topic_list=None, top_n_words=10, umap_model=<bertopic.dimensionality._base.BaseDimensionalityReduction object at 0x7f4c4d6d6650>, vectorizer_model=CountVectorizer(...), verbose=True, zeroshot_min_similarity=0.7, zeroshot_topic_list=None)
topics_per_class = topic_model.topics_per_class(freitextantwort_list, target_names_list)
```
topic_model.visualize_topics_per_class(topics_per_class)
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Input In [79], in <cell line: 1>()
----> 1 topics_per_class = topic_model.topics_per_class(freitextantwort_list, target_names_list)
      2 topic_model.visualize_topics_per_class(topics_per_class)

File /opt/conda/envs/Python-3.10-Premium/lib/python3.10/site-packages/bertopic/_bertopic.py:880, in BERTopic.topics_per_class(self, docs, classes, global_tuning)
    878 check_documents_type(docs)
    879 documents = pd.DataFrame({"Document": docs, "Topic": self.topics_, "Class": classes})
--> 880 global_c_tf_idf = normalize(self.c_tf_idf_, axis=1, norm='l1', copy=False)
    882 # For each unique timestamp, create topic representations
    883 topics_per_class = []

File /opt/conda/envs/Python-3.10-Premium/lib/python3.10/site-packages/sklearn/preprocessing/_data.py:1786, in normalize(X, norm, axis, copy, return_norm)
   1783 else:
   1784     raise ValueError("'%d' is not a supported axis" % axis)
-> 1786 X = check_array(
   1787     X,
   1788     accept_sparse=sparse_format,
   1789     copy=copy,
   1790     estimator="the normalize function",
   1791     dtype=FLOAT_DTYPES,
   1792 )
   1793 if axis == 0:
   1794     X = X.T
...
    878     if array.ndim == 1:

ValueError: Expected 2D array, got scalar array instead:
array=nan.
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.



I hope that's enough. It' interesting - same behaviour with a Base-Model - that the fitted topic-object does not show the instantiated BERTtopic-object-metadata after _fit_transform()_

**Comment by MaartenGr** [comment]
Hmmm, I am not too sure what is happening but it might be related to zero-shot topic modeling. Could you try it again but this time without zero-shot topic modeling? Perhaps there is some issue with the location of the outlier topic.

**Comment by hubernst** [comment]
Hi, 
yes tried it without zero-shot topic modeling and it works fine:

```
# All steps together
topic_model = BERTopic(
    verbose=True,
    min_topic_size = 30,
    #nr_topics = 5,
    #zeroshot_topic_list=kategorien_1,
    #zeroshot_min_similarity=.5,
    embedding_model=embedding_model,          # Step 1 - Extract embeddings
    umap_model=umap_model,                    # Step 2 - Reduce dimensionality
    hdbscan_model=hdbscan_model,              # Step 3 - Cluster reduced embeddings
    vectorizer_model=vectorizer_model,        # Step 4 - Tokenize topics
    ctfidf_model=ctfidf_model,                # Step 5 - Extract topic words
    representation_model=representation_model # Step 6 - (Optional) Fine-tune topic represenations


topics_per_class = topic_model.topics_per_class(freitextantwort_list, target_names_list)
topic_model.visualize_topics_per_class(topics_per_class)
```
![image](https://github.com/MaartenGr/BERTopic/assets/10818197/9a6292c8-f0a2-423e-9a48-7f8fccf5c6ae)

**Comment by MaartenGr** [comment]
Ah, then it indeed seems to be related to the location of the outlier class as we see for example in #1797. I would advise keeping an eye on that issue where I will update on a potential fix after I figure out the best way to approach it.

**Comment by hubernst** [comment]
Hi and thank you, then I know... 
_"Perhaps an error message describing this phenomenon would be more appropriate here to prevent these kinds of unclarities."_
Sorry for that, I had hoped to be sufficient. Thanks for all

**Comment by MaartenGr** [comment]
> "Perhaps an error message describing this phenomenon would be more appropriate here to prevent these kinds of unclarities."
Sorry for that, I had hoped to be sufficient. Thanks for all

That was not aimed at you but definitely at me! I should have put an error message there describing the issue in more detail. My bad, sorry!
