### ISSUE TITLE
Can I find full lists of sentences for each topic instead of get_representative_docs() method?

### ISSUE THREAD

**Issue by kungmo** [MaartenGr/BERTopic#1794]
Hello.
BERTopic is so good for grouping dataset composed of my 3000+ short sentences. Thanks for making fantastic tools.

When I ran .fit_transform method, I could get about 30 topics using my dataset.

I was able to know 3 sentences for each topic using representative_docs method, but I could not find functionality for showing full list of each topic.

Can I find full lists of sentences for each topic? For example, I want to list of all 933 sentences which were grouped topic -1 (not grouped).

Or are there any way to recalculate topic number of each sentences in the dataset?

Thanks in advance of your answer.

![스크린샷 2024-02-07 오후 8 56 07](https://github.com/MaartenGr/BERTopic/assets/19389927/ab5d4907-2d3d-4ecf-a576-9bf8ca8be288)

**Comment by kungmo** [comment]
I got the solution.

topic_model.get_document_info(question_list)

This method works well. Thank you!

**Comment by MaartenGr** [comment]
Great, glad to hear that it worked!
