### ISSUE TITLE
Question about visualize_documents

### ISSUE THREAD

**Issue by Isalia20** [MaartenGr/BERTopic#1795]
First of all thanks for this wonderful package. It truly has great functionalities which is quite useful.

One question I have is about the grayed out points when I run visualize_documents. These are in the Llama example colab notebook as well. I couldn't find what it means, does it mean that, that document has no topic assigned to it or what is the general explanation?

Thanks in advance

**Comment by MaartenGr** [comment]
Those are the outlier topics. Topics that, according to HDBSCAN, could not be assigned to any cluster. If you go the [documentation](https://maartengr.github.io/BERTopic/index.html) you can search on the top right search bar for "outlier" and find more resources regarding this phenomenon.

**Comment by Isalia20** [comment]
Thank you
