### ISSUE TITLE
a error of loading model:  ''NNDescent' object has no attribute '_visited''

### ISSUE THREAD

**Issue by qiangjiaodeyugang** [MaartenGr/BERTopic#180]
Thanks Maarten for your great work!
I can save the model smoothly, but when I read the model, I will encounter this problem: ''NNDescent' object has no attribute '_visited''.
Here are my codes:

`from bertopic import BERTopic

vectorizer_model  =  CountVectorizer (min_df=0.01)
umap_model = umap.UMAP(n_neighbors=100, n_components=2, min_dist=0.0, metric='cosine')
hdbscan_model = hdbscan.HDBSCAN(min_cluster_size=300, metric='euclidean', cluster_selection_method='eom', prediction_data=True)
embedding_model = SentenceTransformer('paraphrase-MiniLM-L6-v2',device='cuda')

model = BERTopic(
                #language="multilingual",
                 embedding_model=embedding_model,
                 #low_memory=True, 
                 vectorizer_model=vectorizer_model,
                 umap_model=umap_model,
                 hdbscan_model=hdbscan_model
                 )
topics, probabilities = model.fit_transform(data)

model.save('./model/miniBERTTopic_model')
model = BERTopic.load("./model/miniBERTTopic_model")`

And here are my error  report:

Tarck (most recent call last)
<ipython-input-55-082a5728fbd7> in <module>()
----> 1 model = BERTopic.load("./model/miniBERTTopic_model")

7 frames
/usr/local/lib/python3.7/dist-packages/pynndescent/pynndescent_.py in _init_search_function(self)
   1283         query_data = self._raw_data[:1]
   1284         _ = self._search_function(
-> 1285             query_data, 5, 0.0, self._visited, self.search_rng_state
   1286         )
   1287 

AttributeError: 'NNDescent' object has no attribute '_visited'

Thank you very much again for your work, I will be very grateful for your help.

**Comment by qiangjiaodeyugang** [comment]
I’m very sorry, I’m a green-hand, and I don’t have a good format for editing questions, which makes it difficult to read my help.

**Comment by Jonathanpro** [comment]
Hello everyone,
I have the same problem as well !

**Comment by MaartenGr** [comment]
It seems this is an issue with pynndescent that has recently some changes to the way it handles certain numba computations. For now, I would advise you to create a fresh environment, install BERTopic and then update numba with `pip install --upgrade numba`. I just tested it out a few times in a google colab session and it seems to work. 

However, more testing needs to be done before I will put this fix in the next release.

**Comment by Jonathanpro** [comment]
Works for me !
Thanks

**Comment by YuanyuanLi96** [comment]
Hi, I am already updated numba to 0.53.1 version, but I still got the same issue. Which version of numba do you use to solve this problem?

**Comment by YuanyuanLi96** [comment]
I think my issue related to memory. I added "low_memory=True" in BERTopic(), then I can successfully save and load the model now !
