### ISSUE TITLE
Using BERTopic with Azure OpenAI Endpoint

### ISSUE THREAD

**Issue by saabster091** [MaartenGr/BERTopic#1812]
I can successfully generate custom embeddings using Azure OpenAI, but BERTopic seems to default back to SentenceTransformers when I'm trying to pass the Azure OpenAI endpoint as the embedding_model. 

`az_topic_model = BERTopic(
embedding_model=azure_embedder,
umap_model=umap_model,
hdbscan_model=az_hdbscan_model,
vectorizer_model=vectoriser_model,
ctfidf_model=ctfidf_model,
representation_model=representation_model,
verbose=True)`

Here is the output Model Parameters:
{'calculate_probabilities': False, 'ctfidf_model': ClassTfidfTransformer(), **'embedding_model': <bertopic.backend._sentencetransformers.SentenceTransformerBackend object at 0x0000027DCB7D84F0>**, 'hdbscan_model': HDBSCAN(min_cluster_size=250, min_samples=50), 'language': None, 'low_memory': False, 'min_topic_size': 10, 'n_gram_range': (1, 1), 'nr_topics': None, 'representation_model': KeyBERTInspired(), 'seed_topic_list': None, 'top_n_words': 10, 'umap_model': UMAP(angular_rp_forest=True, metric='cosine', min_dist=0.0, n_components=5, n_neighbors=20, random_state=42, tqdm_kwds={'bar_format': '{desc}: {percentage:3.0f}%| {bar} {n_fmt}/{total_fmt} [{elapsed}]', 'desc': 'Epochs completed', 'disable': True}), 'vectorizer_model': CountVectorizer(stop_words='english'), 'verbose': True}

Is there any guidance on integrating BERTopic with Azure OpenAI endpoint? Thank you!

**Comment by MaartenGr** [comment]
Could you provide the **full** code? It is not entirely clear what is in `azure_embedding` nor how you train the model.

**Comment by MaartenGr** [comment]
Thanks for sharing the code. When you create a custom embedding backend, you should inherit from BERTopic's BaseEmbedder as documented [here](https://maartengr.github.io/BERTopic/getting_started/embeddings/embeddings.html#custom-backend).

**Comment by saabster091** [comment]
Dank u wel, Maarten! Appreciate your help.
