### ISSUE TITLE
Are there any tutorials for classification task using ZeroShot from BERTopic? 

### ISSUE THREAD

**Issue by saikot-paul** [MaartenGr/BERTopic#1813]
I am looking for some tutorials that use ZeroShot to identify previous topics and also discover new ones. Then do some extrinsic analysis. I do know that BERTopic provides a topic generating model but it is not relevant to my use case.

**Comment by MaartenGr** [comment]
You can find more about zero-shot topic modeling [here](https://maartengr.github.io/BERTopic/getting_started/zeroshot/zeroshot.html) which is a method for identifying known topics whilst also discovering new topics. In BERTopic, zero-shot topic modeling is more than just assigning documents to previously identified topics. It also finds new topics if documents could not be fit to those previously known topics.
