### ISSUE TITLE
Empty representation lists with Traditional Chinese text despite using jieba

### ISSUE THREAD

**Issue by radvanyimome** [MaartenGr/BERTopic#1821]
Hi!

I'm working on a small project, where I do topic modeling on a corpus of buddhist text written in Traditional Chinese.
Everything seems fine and dandy, I managed to create the text embeddings (with several transformers models).
While .fit_transform runs without issues, the list of representations are empty.
(I also tried to play around with ctfidf_model arguments, but alas; representations are still empty.)

````
from sklearn.feature_extraction.text import CountVectorizer
import jieba

def tokenize_zh(text):
    words = jieba.lcut(text)
    return words

vectorizer = CountVectorizer(tokenizer=tokenize_zh)
topic_model = BERTopic(verbose=True, vectorizer_model=vectorizer)
topics, probs = topic_model.fit_transform(docs, embeddings)
topic_model.get_topic_info()
````

I tried tokenize_zh on a few examples, it works, the output is a list of tokens as expected.

The sample of documents is ~35000 with ~130 topics generated, but with the exeption of outliers ([ , 2, 1, 4, 3, buddha, b, 12, a, 123]), the representation all look like: [ , , , , , , , , , ]

I also tried topic_model.update_topics(docs, vectorizer_model=vectorizer) but no success.

The output of topic_model.get_topic is also weird:

```
[(' ', <some small number>),
 (' ', 1e-5),
 (' ',1e-5),
 (' ', 1e-5),
 (' ', 1e-5),
 (' ', 1e-5),
 (' ', 1e-5),
 (' ', 1e-5),
 (' ', 1e-5),
 (' ', 1e-57)]
```
I'm also linking a sample output of the  topic_model.get_document_info(docs)
[data.csv](https://github.com/MaartenGr/BERTopic/files/14330440/data.csv)

I feel I'm missing something obvious.
Any help is appreciated!

**Comment by MaartenGr** [comment]
Have you also tried using a multi-lingual or Chinese embedding model? You are now currently using an English model as that is the default.

**Comment by radvanyimome** [comment]
Thank you! I completely skipped over that argument!
