### ISSUE TITLE
Error when load previously saved Bertopic Model

### ISSUE THREAD

**Issue by jooyeriel** [MaartenGr/BERTopic#1828]
I used bertopic==0.14.0 and not sure which version I used for python and tensorflow when I saved my model. 
When I saved the bertopic model, which was July 2023, I can load the model using BERTopic.load("bert_model_3_7"). 
But now, I encounter this error. 

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[16], line 1
----> 1 topic_model = BERTopic.load("bert_model_3_7")

File ~\Anaconda3\lib\site-packages\bertopic\_bertopic.py:2750, in BERTopic.load(cls, path, embedding_model)
   2748     topic_model.embedding_model = select_backend(embedding_model)
   2749 else:
-> 2750     topic_model = joblib.load(file)
   2751 return topic_model

File ~\Anaconda3\lib\site-packages\joblib\numpy_pickle.py:648, in load(filename, mmap_mode)
    646     filename = getattr(fobj, 'name', '')
    647     with _read_fileobject(fobj, filename, mmap_mode) as fobj:
--> 648         obj = _unpickle(fobj)
    649 else:
    650     with open(filename, 'rb') as f:

File ~\Anaconda3\lib\site-packages\joblib\numpy_pickle.py:577, in _unpickle(fobj, filename, mmap_mode)
    575 obj = None
    576 try:
--> 577     obj = unpickler.load()
    578     if unpickler.compat_mode:
    579         warnings.warn("The file '%s' has been generated with a "
    580                       "joblib version less than 0.10. "
    581                       "Please regenerate this pickle file."
    582                       % filename,
    583                       DeprecationWarning, stacklevel=3)

File ~\Anaconda3\lib\pickle.py:1212, in _Unpickler.load(self)
   1210             raise EOFError
   1211         assert isinstance(key, bytes_types)
-> 1212         dispatch[key[0]](self)
   1213 except _Stop as stopinst:
   1214     return stopinst.value

File ~\Anaconda3\lib\pickle.py:1589, in _Unpickler.load_reduce(self)
   1587 args = stack.pop()
   1588 func = stack[-1]
-> 1589 stack[-1] = func(*args)

File ~\Anaconda3\lib\site-packages\numba\core\serialize.py:110, in _unpickle__CustomPickled(serialized)
    105 def _unpickle__CustomPickled(serialized):
    106     """standard unpickling for `_CustomPickled`.
    107 
    108     Uses `NumbaPickler` to load.
    109     """
--> 110     ctor, states = loads(serialized)
    111     return _CustomPickled(ctor, states)

TypeError: code() takes at most 16 arguments (18 given)

I am not sure if it is due to the incompatibility between bertopic and other packages, for example, numpy. 
Please help me to resolve this error.

**Comment by MaartenGr** [comment]
> I am not sure if it is due to the incompatibility between bertopic and other packages, for example, numpy.
Please help me to resolve this error.

Most likely, this is indeed the case. Whenever you use pickle, regardless of whether you are using BERTopic or any other package, it is important that the environment between saving and loading are identical. So version controlling your environment is extra important when you are using pickle. 

I would advise checking which versions of numpy, HDBSCAN, numba, UMAP, etc. where latest at the moment of saving your BERTopic model (July 2023).
