### ISSUE TITLE
Bug in V0.9 with reducing the number of topics

### ISSUE THREAD

**Issue by Akhamis01** [MaartenGr/BERTopic#184]
Hello!

Just wanted to note that this update to improve the probabilities and to fix the mappings has introduced a new bug. When using the Bertopic() function with the 'nr_topics' parameter, it will return a key error.

To reproduce this error, run:
topic_model = BERTopic(nr_topics=10)

or:
new_topics, new_probs = topic_model.reduce_topics(tweets, topics, probs, nr_topics=10)

Both of these functions will return an error:
(Key error: 10)

**Comment by MaartenGr** [comment]
There is a fix coming in the related pull request. Since you also mentioned this issue there, I will close this for now to keep the discussion at a single place.
