### ISSUE TITLE
AttributeError: 'TextGeneration' object has no attribute 'random_state'

### ISSUE THREAD

**Issue by vinitkothari24** [MaartenGr/BERTopic#1856]
Error when using this code:

AttributeError: 'TextGeneration' object has no attribute 'random_state'

from bertopic.representation import TextGeneration
generator_google_flan_t5_base = pipeline(task ='text2text-generation', model='google/flan-t5-large')
representation_model_google_flan_t5_base = TextGeneration(generator_google_flan_t5_base)

**Comment by MaartenGr** [comment]
Thank you for sharing this. Could you share the **full** error message? Also, which version of BERTopic are you using?

**Comment by MaartenGr** [comment]
I believe this was related to an update of scikit-learn which should be resolved if you install BERTopic from its main branch.
