### ISSUE TITLE
cannot build wheel hdbscan

### ISSUE THREAD

**Issue by stageadss** [MaartenGr/BERTopic#1859]
Hello,

I have checked a lot of posts to fix this but nothing is working. I am on windows, I have installed Visual Studio Build Tools and on Build Tools I have literally installed everything : Windows 10 SDK, MSVC v143 ... and nothing is working still. I have attempted to solve also with conda, I installed hdbscan with it but when pip install Bertopic, it didnt work. The only time I can install hdbscan is when I install the 0.8.31 version but then I have the TypeError: 'numpy.float64' object cannot be interpreted as an intege . Here is the error message ( without conda ) when pip installing bertopic with hdbscan 0.8.33 : 

      C:\Users\AppData\Local\Programs\Python\Python311\include\pyconfig.h(59): fatal error C1083: Cannot open include file: 'io.h': No such file or directory
      error: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Professional\\VC\\Tools\\MSVC\\14.33.31629\\bin\\HostX86\\x86\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for hdbscan
Failed to build hdbscan
ERROR: Could not build wheels for hdbscan, which is required to install pyproject.toml-based projects

If someone could help, I really dont know what to do

**Comment by MaartenGr** [comment]
>  I have attempted to solve also with conda, I installed hdbscan with it but when pip install Bertopic, it didnt work. 

What is the error that you get when you approach it like this? I thought that it was fixed with version 0.8.33 of HDBSCAN but it seems like you still have those known issues. Perhaps that [this thread](https://github.com/scikit-learn-contrib/hdbscan/issues/600) might be of help to you.

**Comment by stageadss** [comment]
Everytime I do conda activate, it tells me to do conda init which I did and it still doesnt work. I try to create a conda env and go in there to install hdbscan to follow this tutorial from another person that solved the issue : 

create a new environment using conda (not venv)
conda install -c conda-forge hdbscan
pip install --upgrade pip
pip install --upgrade setuptools
pip install bertopic (do not install using conda)

**Comment by stageadss** [comment]
Ok I managed to make it work. I just created a conda environment through vscode, installed bertopic through this environment and activate it to run my code

**Comment by stageadss** [comment]
Use conda conda env to install bertopic and use it for execution
