### ISSUE TITLE
topic_model.fit_transform(tweets) does not run without a wifi connection

### ISSUE THREAD

**Issue by Akhamis01** [MaartenGr/BERTopic#186]
Hello,

I'm currently attempting to use Bertopic on a dataset through a remote computer that does not have an internet connection when using Jupyter Notebook.

I'm attempting to run the following lines:

```
vectorizer_model = CountVectorizer(ngram_range=(1, 2), stop_words=all_stopwords)
num_of_topics = 15

topic_model = BERTopic(vectorizer_model=vectorizer_model,
                                        verbose=True,
                                        nr_topics=num_of_topics,
                                        calculate_probabilities=True)

topics, probs = topic_model.fit_transform(tweets)
```
However, it seems that the `fit_transform()` function returns the error:

```
HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/sentence-transformers/paraphrase-MiniLM-L6-v2 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x2bab3a1cb400>: Failed to establish a new connection: [Errno 110] Connection timed out'))
```
Is it possible to avoid creating any HTTP requests when running this function? Thanks you.

**Comment by d4buss** [comment]
It looks like it's trying to download the huggingface model. You'd have to somehow get the model to the remote computer. And then point huggingface/transformers to that model

**Comment by MaartenGr** [comment]
Fortunately, you already can use it locally! The great thing about using sentence-transformers is that it searches automatically for an embedding model locally. If it cannot find one, it will download the pre-trained model from its servers. Make sure that you set the correct path for sentence-transformers to work. You can find a bit more about that [here](https://github.com/UKPLab/sentence-transformers/issues/888)

You can download the corresponding model [here](https://public.ukp.informatik.tu-darmstadt.de/reimers/sentence-transformers/v0.2/) and unzip it. Then, simply use the following to create your embedding model:

```python
from sentence_transformers import SentenceTransformer
embedding_model = SentenceTransformer('path/to/unzipped/model')
```

Then, pass it to BERTopic:
```python
from bertopic import BERTopic
topic_model = BERTopic(embedding_model=embedding_model)
```

**Comment by Akhamis01** [comment]
Thank you! This solution worked for me :)

**Comment by MaartenGr** [comment]
Glad that it worked out! 👍
