### ISSUE TITLE
Question about pooling method used in the paper.

### ISSUE THREAD

**Issue by dkoterwa** [MaartenGr/BERTopic#1868]
Hi,
I've just wanted to ask if you had used the SentenceTransformers default setting of creating a document embedding in your research paper, which is basically performing mean pooling on the hidden states from the last layer.

Best,
Dominik

**Comment by MaartenGr** [comment]
I used the default functionality of sentence-transformers. You can find more about how I went about it in the corresponding [repo here](https://github.com/MaartenGr/BERTopic_evaluation).
