### ISSUE TITLE
transform() does not produce a list of topic predictions instead throws AttributeError

### ISSUE THREAD

**Issue by FrankSchilderTR** [MaartenGr/BERTopic#187]
after using fit_transform on a list of documents, new documents can not be used with transform():

topic_model.transform(ListOfNewDocuments)

~/Library/Caches/pypoetry/virtualenvs/clusterExperiments-XQHRKN7F-py3.8/lib/python3.8/site-packages/bertopic/_bertopic.py in transform(self, documents, embeddings)
    353                                                   verbose=self.verbose)
    354 
--> 355         umap_embeddings = self.umap_model.transform(embeddings)
    356         predictions, _ = hdbscan.approximate_predict(self.hdbscan_model, umap_embeddings)
    357 

~/Library/Caches/pypoetry/virtualenvs/clusterExperiments-XQHRKN7F-py3.8/lib/python3.8/site-packages/umap/umap_.py in transform(self, X)
   2715         else:
   2716             epsilon = 0.24 if self._knn_search_index._angular_trees else 0.12
-> 2717             indices, dists = self._knn_search_index.query(
   2718                 X, self.n_neighbors, epsilon=epsilon
   2719             )

~/Library/Caches/pypoetry/virtualenvs/clusterExperiments/lib/python3.8/site-packages/pynndescent/pynndescent_.py in query(self, query_data, k, epsilon)
   1573             query_data = np.asarray(query_data).astype(np.float32, order="C")
   1574             result = self._search_function(
-> 1575                 query_data, k, epsilon, self._visited, self.search_rng_state
   1576             )
   1577         else:

AttributeError: 'NNDescent' object has no attribute '_visited'

**Comment by MaartenGr** [comment]
This seems like a known issue with `pynndescent`. I would advise you to start from a new environment and create a fresh install BERTopic. Also, you can upgrade pynndescent with `pip install --upgrade pynndescent`.

**Comment by FrankSchilderTR** [comment]
that fixed the problem. Thank you!
