### ISSUE TITLE
Retrieve text docs for each topic

### ISSUE THREAD

**Issue by mediote** [MaartenGr/BERTopic#189]
Hi, 

Is there any method that I can retrieve text docs for each topic?

Ex: topic_model.get_documents_by_topic(10)

The output would be the text docs of topic 10.

Tks.

**Comment by mediote** [comment]
Thank you, 
Your answer was very helpful. I just need to check some examples to better understand certain topics.

**Comment by lisanka93** [comment]
@MaartenGr I have a question - how come top2vec does save the documents even if these are represented using BERT embeddings and it doesnt explode in size?

**Comment by MaartenGr** [comment]
@lisanka93 

Whether they are represented using BERT embeddings is actually not that relevant for model size. In the discussion above I meant that saving documents within the BERTopic model simply adds to the size of that model whilst there is actually no need to do so. Saving millions of documents should be done in a database that is optimized to handle those documents.

**Comment by lisanka93** [comment]
@MaartenGr thank you fir your fast reply :) really appreciated. 

yea that's what I thought - I am just wondering how I could compare the performance of my current top2vec model with BERTopic. By giving the model a new document I want to retrieve similar ones without having to loop through the whole dataset and calculate similarity

**Comment by MaartenGr** [comment]
@lisanka93 Finding similar documents is a different use-case from BERTopic. However, you can predict the topics of unseen documents using `.transform(doc)` to find out to which topic the document belongs. That way, you do not have to loop through the whole dataset. With respect to performance, it highly depends on the evaluation metric you are interested in. Typically, `npmi` is used in academic research, along with topic diversity, to evaluate the quality of a topic model. However, I would focus on trusting your instinct when reading through the topics that were generated. Sanity checks go a long way!
