### ISSUE TITLE
Unable to merge models when there are more than one representation model.

### ISSUE THREAD

**Issue by hrdyam** [MaartenGr/BERTopic#1911]
Below code gives error when we have a dictionary of representative models.
representation_model = {
    "KeyBERT": keybert,
    "MMR": mmr
}
base_model= BERTopic(representation_model=representation_model, nr_topics="auto",embedding_model= model).fit(docs, embeddings)
new_model= BERTopic(representation_model=representation_model, nr_topics="auto",embedding_model= model).fit(docs1, embeddings1)
merged_model = BERTopic.merge_models([base_model, new_model])

error :
----> 1 merged_model = BERTopic.merge_models([base_model, new_model])

File ~/topic_modelling/env/lib/python3.10/site-packages/bertopic/_bertopic.py:3150, in BERTopic.merge_models(cls, models, min_similarity, embedding_model)
   3147 merged_topics["topic_labels"][str(new_topic_val)] = selected_topics["topic_labels"][str(new_topic)]
   3149 if selected_topics["topic_aspects"]:
-> 3150     merged_topics["topic_aspects"][str(new_topic_val)] = selected_topics["topic_aspects"][str(new_topic)]
   3152 # Add new embeddings
   3153 new_tensors = tensors[new_topic - selected_topics["_outliers"]]

KeyError: '71'

===============================================================================
Below code works fine when there is only one representation model.

representation_model = KeyBERTInspired()
base_model= BERTopic(representation_model=representation_model, nr_topics="auto",embedding_model= model).fit(docs, embeddings)
new_model= BERTopic(representation_model=representation_model, nr_topics="auto",embedding_model= model).fit(docs1, embeddings1)
merged_model = BERTopic.merge_models([base_model, new_model])

**Comment by MaartenGr** [comment]
Have you tried installing BERTopic from its main branch? I believe it was fixed there.

**Comment by hrdyam** [comment]
Thanks for your reply. 
It worked after installing from main branch.
