### ISSUE TITLE
Bertopic generating too many topics for large dataset

### ISSUE THREAD

**Issue by Akhamis01** [MaartenGr/BERTopic#193]
Hello,

I was experimenting with a larger dataset (6 million tweets) using Bertopic, and when setting "auto" to the nr_topics parameter, it would generate around 3000 topics. Is this normal for a large dataset like this? What options do I have besides setting the nr_topics parameter to a number of my choice? Is this dataset too big?

Thank you :)

**Comment by MaartenGr** [comment]
Good question! Indeed, with many documents (> 100_000) it tends to generate quite a number of topics as is in your case. It is not unsurprising that many topics exist in the documents as you simply have many documents that could reasonably contain a topic. Although I am not familiar with your specific dataset, it would make sense that 6 million tweets simply contain quite a number of topics. 

Having said that, there are a number of ways, aside from setting the `nr_topics`, to reduce the number of generated topics. 

First, we can set the `min_topic_size` in the BERTopic initialization much higher (e.g., 300) to make sure that those small clusters will not be generated. This is a HDBSCAN parameter that specifies what the minimum number of documents are needed in a cluster. More documents in a cluster means less topics will be generated. 

Second, you can create a custom UMAP model and set `n_neighbors` much higher than the default 15 (e.g., 200). This also prevents those micro clusters to be generated as it will needs quite a number of neighboring documents to create a cluster.

**Comment by Akhamis01** [comment]
Thank you so much! Makes a lot of sense. I'm just wondering, how can I incorporate a custom UMAP model into Bertopic? Can you please provide a link that could help me with this? :)

**Comment by MaartenGr** [comment]
Sure, you can find it in the documentation here: https://maartengr.github.io/BERTopic/tutorial/models/models.html

**Comment by Akhamis01** [comment]
Thank you! So in my case, I'd just use 
umap_model = UMAP(n_neighbors=200) and leave the rest as default?

**Comment by MaartenGr** [comment]
I would advise using the following settings as they are default in BERTopic:
```python
UMAP(n_neighbors=200, n_components=5, min_dist=0.0, metric='cosine')
```

**Comment by Akhamis01** [comment]
Great, thank you so much for your help!
