### ISSUE TITLE
Problem with fitting and transforming model

### ISSUE THREAD

**Issue by SijfWillem** [MaartenGr/BERTopic#1935]
Hi @MaartenGr, 
Thanks for the package!

I am working on a use case and am trying to fit a BERTopic model on documents with embeddings. I want to save the model so it can be loaded in another notebook. However, I also want to predict on the same documents I use to fit the model. 

Right now when I .fit the model, save it, and then .fit_transform on the same documents the output differs slightly. 

The code I have now is the following: 

topic_model.fit(docs, embeds)
topic_model.save(..............)

topics, probabilities = topic_model.fit_transform(docs, embeds)

Is there a proper way of doing this? I looked into .transform() but this works with new documents. I want to use the same.

Thanks in advance!

**Comment by MaartenGr** [comment]
As with scikit-learn, whenever you run any variant of `.fit` it re-trains the model from scratch. Instead, you will need to use `.transform` on the current documents. If you want to access the previously generated topics, you can run `topic_model.topics_` without the need to run `.transform`.

**Comment by SijfWillem** [comment]
Clear! Thanks.
