### ISSUE TITLE
Drop support for Python 3.7

### ISSUE THREAD

**Issue by afuetterer** [MaartenGr/BERTopic#1942]
Python 3.7 reached its end of life in 2023. I suggest dropping support.

That would mean to touch:
https://github.com/MaartenGr/BERTopic/blob/e7369d0bb9f39ce23735f4f23d5b9fa3ca296667/setup.py#L90
and
https://github.com/MaartenGr/BERTopic/blob/e7369d0bb9f39ce23735f4f23d5b9fa3ca296667/setup.py#L106

In your CI job, you test 3.8 and 3.9 anyway, not 3.7.

I am happy to submit a PR. What do you think?

Refs:
- https://devguide.python.org/versions/

**Comment by MaartenGr** [comment]
Ah, right. I meant to do that but totally forgot about it. Sure, let's drop it! It should also be changed in the README where it currently mentions 3.7+. Other than that, I think those were all places.

**Comment by afuetterer** [comment]
Should I submit a PR then? Happy to.

**Comment by MaartenGr** [comment]
@afuetterer Thanks for the PR, I'll go ahead and merge it.
