### ISSUE TITLE
BERTopic with large dataset (10-20 Million)

### ISSUE THREAD

**Issue by jwratten** [MaartenGr/BERTopic#1954]
I have been attempting to use BERTopic on between 10 and 20 Million sentences. However, I haven't got it to work yet!
Within Azure Databricks I am using a NC24ads_A100_v4 GPU (220 GB memory and 24 cores) and also cuML's UMAP and HDBSCAN.
So far I have been able to successful run on 1M and 2M complaints. 2M complaints takes around 25 minutes.
It appears like the embedding step scales linearly, but not the UMAP and HDBSCAN steps. They almost seem to grow quadratic with number of sentences, based on some tests I have run.
So, 16 M appears impossible.
Note: I have tried using a large min_df and min_cluster_size.
So, based on comments by other posters here, I tried to just do fit on 2M complaints and then separately call transform on the rest of the data, but I still was unable to do it. Transform, especially for UMAP seems to be quite slow and almost as slow as the train itself?
Any advice would be appreciated!

**Comment by MaartenGr** [comment]
A trick that you can use (which I should document at some point), is to fit on 2M complaints, save the model using `safetensors`, then load the model, and finally use a separate `transform` call on the rest of the data. 

The reason why the above will work is that when you save BERTopic using `safetensors`, it removes the underlying UMAP and HDBSCAN model. Inference (using `.transform`) will instead be done through a cosine similarity between document and topic embeddings which is incredibly fast and only requires you to embed the input documents.

**Comment by beckernick** [comment]
As a note, we recently [_significantly_ improved the performance and scalability of GPU-accelerated UMAP](https://developer.nvidia.com/blog/even-faster-and-more-scalable-umap-on-the-gpu-with-rapids-cuml/) in RAPIDS cuML.

It should now be quite feasible to run UMAP on 10-20M sentence embeddings fairly quickly. Happy to provide more info, if interested.
