### ISSUE TITLE
Wrong link in Algorithm Documentation

### ISSUE THREAD

**Issue by naeyn** [MaartenGr/BERTopic#1965]
Hey, first of all thank you for this great package!
While reading the documentation I noticed, that the Clustering Link on the Algorithm package refers to dimensionality reduction instead to the clustering subpage

Snippet from the markdown below

`3. [Clustering](../getting_started/dim_reduction/dim_reduction.html)`

**Comment by MaartenGr** [comment]
Thanks for sharing! If you want, a PR would be highly appreciated.

**Comment by naeyn** [comment]
Sure!
PR attached below
#1970
