### ISSUE TITLE
Visualization in html page

### ISSUE THREAD

**Issue by mzhadigerov** [MaartenGr/BERTopic#1989]
Hi! I like the visualizations used in the library.

e.g.:

```python
topic_model.visualize_documents()
```

The thing is, displaying those plots in jupyter notebook is not enough.

 Is there a way to easily render them in a html page? 
 If no, Could you guide me to appropriate documentations, so I can try to develop such a feature myself?

**Comment by MaartenGr** [comment]
The output of most visualizations are a Plotly figure that you can convert to [HTML](https://plotly.com/python/interactive-html-export/) with `.write_html`.
