### ISSUE TITLE
About the `gen_min_span_tree` param of hdbsacn

### ISSUE THREAD

**Issue by mymusise** [MaartenGr/BERTopic#199]
Hey guy, thanks for sharing the great technique `BERTopic`, it's very effective for my work!

But I wonder why not set `gen_min_span_tree=True` when initializing `HDBSCAN`, I think the minimum spanning tree is one of the improvements of `HDBSCAN`.

**Comment by MaartenGr** [comment]
Thank you for your kind words!

The `gen_min_span_tree` only generates, from what I can tell from the documentation, the minimum spanning true to be used in later analysis when you are, for example, visualizing clusters. This should not affect the quality of clusters. The `approx_min_span_tree` parameter however can influence the quality of clusters but sacrifices speed to do so. In practice, the parameters as set in

**Comment by MaartenGr** [comment]
Sorry, accidentally clicked "close with comment" since I was answering this issue on my phone. Hopefully, the answer above helped a bit.

**Comment by mymusise** [comment]
> Sorry, accidentally clicked "close with comment" since I was answering this issue on my phone. Hopefully, the answer above helped a bit.

Never mind.

> The gen_min_span_tree only generates, from what I can tell from the documentation...

Thank you for sharing the experience, which solved my doubts!
