### ISSUE TITLE
ValueError: k must be less than or equal to the number of training points`

### ISSUE THREAD

**Issue by Siegi96** [MaartenGr/BERTopic#20]
Hi,

I want to use your pipeline with my own embeddings. However, I always get this error:

`2020-12-03 15:04:21,143 - BERTopic - Reduced dimensionality with UMAP
2020-12-03 15:04:21 - Reduced dimensionality with UMAP
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-94-78348f5339cf> in <module>()
      9 npcorpus_embeds = np.array(corpus_embeds)
     10 
---> 11 topics = bmodel.fit_transform(cats, npcorpus_embeds)

4 frames
/usr/local/lib/python3.6/dist-packages/hdbscan/prediction.py in __init__(self, data, condensed_tree, min_samples, tree_type, metric, **kwargs)
    102         self.tree = self._tree_type_map[tree_type](self.raw_data,
    103                                                    metric=metric, **kwargs)
--> 104         self.core_distances = self.tree.query(data, k=min_samples)[0][:, -1]
    105         self.dist_metric = DistanceMetric.get_metric(metric, **kwargs)
    106 

sklearn/neighbors/_binary_tree.pxi in sklearn.neighbors._kd_tree.BinaryTree.query()

ValueError: k must be less than or equal to the number of training points`

I also tried using the built in embedding creation but got the same error. Do you know, what the problem could be?

**Comment by MaartenGr** [comment]
Considering the error message, it seems that your data is either very small or does not have the right shape. 

In the first case, either lower `min_topic_size` or increase the amount of data that you have. 

In the second case, it might be worthwhile to transpose your data as the embeddings might be expected to have a different shape.

**Comment by sheth7** [comment]
I got the same ValueError with a less data.  It was solved with increasing the data.
