### ISSUE TITLE
Error at Combining clustered topics with the zeroshot model

### ISSUE THREAD

**Issue by akalra03** [MaartenGr/BERTopic#2006]
I am getting error while using zeroshot topic list. 

![image](https://github.com/MaartenGr/BERTopic/assets/139199834/02443090-7817-49b8-b497-4c5a6459e672)

![image](https://github.com/MaartenGr/BERTopic/assets/139199834/6da74788-42eb-46eb-8962-c5f2c9f078ee)

![image](https://github.com/MaartenGr/BERTopic/assets/139199834/829019d7-2ab0-46f5-b662-79186fb70816)

**Comment by MaartenGr** [comment]
Which version of BERTopic are you using? Also, could you share your full code? Raw would be preferred as that is much easier to read and potentially use without me having to type it over.

**Comment by akalra03** [comment]
It worked for me with the latest version however zeroshot model is giving good results. I ran it on the same data I created topics earlier and it was only able to recognize 5 out 400 documents. Thanks for the help. The main issue got resolved.
