### ISSUE TITLE
Why outliers are shown in visualize_documents after outlier reduction?

### ISSUE THREAD

**Issue by mzhadigerov** [MaartenGr/BERTopic#2015]
Hi! As I understand, using outlier reduction functions, we assign all outliers to a topic. And I can see that there are no outliers left, after I call `get_topic_info` after updating my model:

```python
# Reduce outliers
new_topics = topic_model.reduce_outliers(texts, topics)

# Reduce outliers with pre-calculate embeddings instead
new_topics = topic_model.reduce_outliers(texts, topics, strategy="embeddings", embeddings=embeddings)

topic_model.update_topics(texts, topics=new_topics)

topic_model.get_topic_info()
```

But why I still see outliers when I visualize my documents?

```python
reduced_embeddings = UMAP(n_neighbors=10, n_components=2, min_dist=0.0, metric='cosine').fit_transform(embeddings)
topic_model.visualize_documents(texts, reduced_embeddings=reduced_embeddings, custom_labels=True)
```
![image](https://github.com/MaartenGr/BERTopic/assets/55549813/84da34f5-f436-43d6-800c-9abaaea77072)

**Comment by MaartenGr** [comment]
Which version of BERTopic are you using? Also, are you 100% sure that the variable `new_topics` **does not** contain any -1 values? 

```python
new_topics = topic_model.reduce_outliers(texts, topics, strategy="embeddings", embeddings=embeddings)
```

If that's the case, then it might be worthwhile to set `custom_labels=False` to check whether there lies the issue.

**Comment by mzhadigerov** [comment]
Sorry, I wasn't able to reproduce after I tried to run the notebook again. Maybe I did something wrong. Will re-open, If I encounter the same issue again. Thanks
