### ISSUE TITLE
'can't pickle weakref objects' error when trying to predict on  new instances

### ISSUE THREAD

**Issue by yomnashaban** [MaartenGr/BERTopic#203]
Hello!
Great work!, Bertopic is really awseome,
I've been facing this error  whenever I try to predict topics for a new doc ( topic_model.transform([new_doc]) ) or a bunch of docs (  topic_model.transform(docs[4:8]) ), any help with this ?
![Screenshot (332)](https://user-images.githubusercontent.com/57356128/129568049-f4aeeeeb-a120-4985-ae27-f141f136fe49.png)
![Screenshot (333)](https://user-images.githubusercontent.com/57356128/129568072-0b07f6b3-66cf-4bda-bf20-4a179785b6e6.png)

**Comment by MaartenGr** [comment]
Could you share the versions of all packages in your environment? I am not entirely sure but it seems to be a problem with numba. I suggest starting out with upgrading numba to the newest version and trying again: `pip install --upgrade numba`.

**Comment by yomnashaban** [comment]
Thank you for the fast reply! it workedd!
i did  `pip install --upgrade numba`  and  `pip install --upgrade tbb`.
