### ISSUE TITLE
returning N of Words per topic in topics_over_time method

### ISSUE THREAD

**Issue by hp0404** [MaartenGr/BERTopic#204]
Hi there!

I'm trying to change the amount of words `topics_over_time` method returns

---

By default, you return 5 words (506 line):
https://github.com/MaartenGr/BERTopic/blob/80c9fa174e4671b49f1697b44368e23ee0d9bd18/bertopic/_bertopic.py#L505-L508

I slightly changed the code (see here: https://github.com/hcss-utils/hcss-BERTopic/commit/081388a30524239d14f2085d525e6e156f76fbb1), but instead of, say, 15 words, the function only returns 10. 

Could we return more than 10 words, and if so, what am I doing wrong? 

Thanks!

**Comment by MaartenGr** [comment]
There are two things happening here. First, to increase the number of words per topic, you'll need to change `top_n_words` when initializing BERTopic. Next, you will indeed need to change the code as you'll have done before and it should work. 

Do note that I purposefully did not allow users to change that value as topic representations are typically best with a maximum of 5 words. Adding words do add information but not significantly. 

Hopefully, this helps a bit. Let me know if you have any other questions!

**Comment by hp0404** [comment]
ok, totally makes sense! 
thanks for the reply
