### ISSUE TITLE
get_topic() with KeyBERTInspired?

### ISSUE THREAD

**Issue by mzhadigerov** [MaartenGr/BERTopic#2042]
I can get representative terms along with their weights using:

```python
topic_model.get_topic(i)
```
The thing is I don't really like the default representations, but terms extracted by KeyBERTInspired seems better.

Is there a way to do something like this:

```python
topic_model.get_topic(i, representation="KeyBERTInspired")
```

**Comment by MaartenGr** [comment]
There is the `full` parameter which returns all the representations as a dictionary that you can access. You can use that to access the KeyBERTInspired representations.
