### ISSUE TITLE
Is there an issue is using visualization for probabilities?

### ISSUE THREAD

**Issue by gsalfourn** [MaartenGr/BERTopic#205]
I have been running a model, with probabilities=True, but when I try to visualize the probabilities, it gives me an error. I am able to get other visualizations, except for the probabilities. Below is the model

```
# import bertopic module
from bertopic import BERTopic

# create bertopic model
topic_model = BERTopic(top_n_words=10,
                        min_topic_size=10,
                        n_gram_range=(1,2),
                        calculate_probabilities=True,
                        umap_model=umap_model,
                        hdbscan_model=hdbscan_model,
                        embedding_model=sentence_model,
                        seed_topic_list=seed_topic_list,
                        low_memory=False,
                        verbose=True)

# train model, extract topics and probabilities
topics, probabilities = topic_model.fit_transform(docs)
```

Printing probabilities
```
>>> probabilities

array([[1.04108667e-003, 8.21988479e-004, 8.68390813e-004, ...,
        2.25507432e-003, 3.18212081e-003, 5.01478308e-003],
       [1.97291031e-003, 1.28916155e-003, 1.41348074e-003, ...,
        5.22005376e-003, 1.04340104e-002, 1.70166771e-002],
       [1.44893359e-003, 1.35030158e-003, 1.35488221e-003, ...,
        1.74136763e-003, 1.65450774e-003, 1.47356192e-003],
       ...,
       [1.65158917e-003, 1.27629734e-003, 1.39456544e-003, ...,
        3.84233662e-003, 7.79596349e-003, 1.25878790e-002],
       [8.33483356e-308, 6.60175654e-308, 7.20870882e-308, ...,
        2.03299069e-307, 4.31515947e-307, 7.41736567e-307],
       [8.33366179e-308, 6.60142444e-308, 7.20777411e-308, ...,
        2.03285762e-307, 4.31191953e-307, 7.42987242e-307]])
```

Other visualizations (that work without an error)
```
# visualize top_n topics
>>> topic_model.visualize_barchart(top_n_topics=10, height=700)
- produces bar graphs

>>> topic_model.visualize_topics(top_n_topics=25)
- produces topic chart
```
The visualization that results in an error message

```
>>> topic_model.visualize_distribution(probabilities[0], min_probability=0.015)

ValueError: This visualization cannot be used if you have set `calculate_probabilities` to False as it uses the topic probabilities of all topics. 
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_20624/2804172298.py in <module>
----> 1 topic_model.visualize_distribution(probabilities[0], min_probability=0.015)

d:\Python\content analysis\bertopic\inMoment topicsmodels\bertopicENV\lib\site-packages\bertopic\_bertopic.py in visualize_distribution(self, probabilities, min_probability, width, height)
   1074         """
   1075         check_is_fitted(self)
-> 1076         return plotting.visualize_distribution(self,
   1077                                                probabilities=probabilities,
   1078                                                min_probability=min_probability,

d:\Python\content analysis\bertopic\inMoment topicsmodels\bertopicENV\lib\site-packages\bertopic\plotting\_distribution.py in visualize_distribution(topic_model, probabilities, min_probability, width, height)
     37     """
     38     if len(probabilities.shape) != 2:
---> 39         raise ValueError("This visualization cannot be used if you have set `calculate_probabilities` to False "
     40                          "as it uses the topic probabilities of all topics. ")
     41     if len(probabilities[probabilities > min_probability]) == 0:

ValueError: This visualization cannot be used if you have set `calculate_probabilities` to False as it uses the topic probabilities of all topics. 
```

**Comment by vidhig** [comment]
I have been facing a similar issue

**Comment by MaartenGr** [comment]
I think something might went wrong when pushing to pypi as some features are missing from the plots. I'll look into this the coming week!

**Comment by MaartenGr** [comment]
A fix for this issue has been released (v0.9.1). To use this fix, update BERTopic with: `pip install --upgrade bertopic`. If there any other issues you are experiencing, please let me know!

**Comment by liping2084** [comment]
-The visualization that results in an error message--------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-53-6f5dfff36389> in <module>
----> 1 model.visualize_distribution(probs[0])

~\anaconda3\lib\site-packages\bertopic\_bertopic.py in visualize_distribution(self, probabilities, min_probability, width, height)
   1107         """
   1108         check_is_fitted(self)
-> 1109         return plotting.visualize_distribution(self,
   1110                                                probabilities=probabilities,
   1111                                                min_probability=min_probability,

~\anaconda3\lib\site-packages\bertopic\plotting\_distribution.py in visualize_distribution(topic_model, probabilities, min_probability, width, height)
     37     """
     38     if len(probabilities.shape) != 1:
---> 39         raise ValueError("This visualization cannot be used if you have set `calculate_probabilities` to False "
     40                          "as it uses the topic probabilities of all topics. ")
     41     if len(probabilities[probabilities > min_probability]) == 0:

ValueError: This visualization cannot be used if you have set `calculate_probabilities` to False as it uses the topic probabilities of all topics.

**Comment by MaartenGr** [comment]
@liping2084 When instantiating BERTopic, you need to set the parameter `calculate_probabilities=True` in order to make this visualization technique work.
