### ISSUE TITLE
TypeError: unhashable type: 'numpy.ndarray'

### ISSUE THREAD

**Issue by cindyangelira** [MaartenGr/BERTopic#2149]
Hi. 
I follow the tutorial [here ](https://huggingface.co/docs/hub/en/bertopic#:~:text=topic%2C%20prob%20%3D%20topic_model.transform(%22This%20is%20an%20incredible%20movie!%22)%0Atopic_model.topic_labels_%5Btopic%5D)

but got error
`topic_model.topic_labels_[topic]`
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[36], line 1
----> 1 topic_model.topic_labels_[topic]

TypeError: unhashable type: 'numpy.ndarray'
```

Then I try,
```
if isinstance(topic, np.ndarray):
    topic = topic[0]  
label = topic_model.topic_labels_[int(topic)]
```
is it correct approach or am I missing something?

Thanks.

**Comment by MaartenGr** [comment]
Ah right, this seems to be a documentation error. It should indeed have been this:

```python
topics, probs = topic_model.transform("This is an incredible movie!")
topic_model.topic_labels_[topics[0]]
```  

since `topics` is a list of integers, you should indeed select the content.

**Comment by cindyangelira** [comment]
okay, thanks.

**Comment by cindyangelira** [comment]
okay, thanks.
