### ISSUE TITLE
Probabilities from fit_transform and transform methods are quite different for the same set of documents

### ISSUE THREAD

**Issue by dlu-lv** [MaartenGr/BERTopic#218]
I have the following codes

```
topic_model = BERTopic(language="english", calculate_probabilities=True)
topics, probs = topic_model.fit_transform(docs)
topics_tr, probs_tr = topic_model.transform(docs)
```
Methods `fit_transform` and `transform` operates on the same set of docs. It looks like "topics" and "topics_tr" are the same, but "probs" are quite different from "probs_tr", especially for documents with topic number assigned, that is, given an index `i`, `topics[i]` is the same as `topics_tr[i]`, but `probs[i]` can be quite different from `probs_tr[i]`. For instance

```
doc num is 31
fit_transform result:
topic is 7
prob is [0.01433402 0.01480345 0.03016759 0.00744076 0.00907584 0.02106986
 0.00182571 0.46184079 0.01251561 0.01369095 0.00218655 0.01234251
 0.00179474 0.00207723 0.01023785 0.02121211 0.01321986 0.0017692
 0.00198681 0.01165707 0.00226677 0.01132043 0.00203275 0.00534123
 0.00584168 0.00623881 0.00497031 0.00515378 0.01712167 0.01047932
 0.02984628 0.00202933 0.01026871 0.02370249 0.00390701 0.00810369
 0.00665189 0.01986709 0.00385349 0.00623962 0.00857101 0.00218987
 0.01485938 0.01074844 0.010943   0.01433514 0.00558189 0.00566514
 0.0021897  0.00206539 0.00597513]

transform result:
topic is 7
prob is [9.27129033e-12 9.42188102e-12 1.34501319e-11 2.89119381e-13
 4.80363627e-12 1.12405364e-11 4.59301754e-14 9.33608969e-01
 6.25869668e-12 9.06093502e-12 5.02644621e-14 8.44592896e-12
 4.55389025e-14 4.89919159e-14 7.83538911e-12 1.12784172e-11
 1.45983299e-12 4.52137766e-14 4.79137622e-14 8.36086011e-12
 5.11782534e-14 8.23925167e-12 4.84645236e-14 2.02009072e-12
 2.11261030e-12 2.18323865e-12 5.46968721e-13 1.98432749e-12
 1.01327951e-11 1.29973965e-12 1.33783129e-11 4.84237486e-14
 7.84719030e-12 1.19221126e-11 7.53192131e-14 2.48823710e-12
 2.25435819e-12 2.00070703e-12 1.16456901e-13 2.18338011e-12
 2.18763028e-12 5.03026662e-14 6.81959018e-12 8.02839816e-12
 8.10073570e-12 9.27165283e-12 2.06509902e-12 1.26259396e-13
 5.03007678e-14 4.88520839e-14 2.13660455e-12]
```
For this particular doc, `probs[7]` is `0.46184079` or `46%`, while `probs_tr[7]` is `9.33608969e-01`, or `93%`.

I can understand that the probabilities can never be exactly the same, but should they be rather close to each other? I'd expect it to be between 40% to 50%, and I just wonder how confident I am to tell others the probability of a prediction is 93%.

I'd like to hear your opinions and suggestions. Thanks in advance.

**Comment by MaartenGr** [comment]
Yes, this typically happens when using `HDBSCAN`. The way it predicts new instances is different from training on these instances. In practice, there is a good chance the probabilities may differ when using these methods. You can find a little bit more about that [here](https://hdbscan.readthedocs.io/en/latest/prediction_tutorial.html).

**Comment by dlu-lv** [comment]
Thank you very much for the explanation.
