### ISSUE TITLE
using transformers' models with BERTopic 

### ISSUE THREAD

**Issue by hp0404** [MaartenGr/BERTopic#219]
Is it possible to use huggingface/transformers' model with BERTopic? 
For example, if I want to use [DeepPavlov's models](https://huggingface.co/DeepPavlov), what should I do (if it's possible)?

**Comment by MaartenGr** [comment]
You can use huggingface's transformers models by using `Flair` in BERTopic. You can find more about that in the documentation [here](https://maartengr.github.io/BERTopic/tutorial/embeddings/embeddings.html). If that doesn't work, please let me know!

**Comment by hp0404** [comment]
Yes, thank you! That was helpful.

When I tried running transformers' model, I encountered [this issue](https://github.com/flairNLP/flair/issues/2181), but setting `model_max_length` to 512 did help (in case anyone else gets this error). 

Works great.
