### ISSUE TITLE
the new_topics from reduce_topics does not have the largest probability in new_probs.

### ISSUE THREAD

**Issue by dlu-lv** [MaartenGr/BERTopic#220]
I tested Bertopic and tried to reduce the number of topics. I expected that the newly assigned topics should have the largest probability, but they don't seem to. With the following code snippet, 

```
from sklearn.datasets import fetch_20newsgroups
from bertopic import BERTopic

docs = fetch_20newsgroups(subset='all',  remove=('headers', 'footers', 'quotes'))['data']
topic_model = BERTopic(language="english", calculate_probabilities=True)
topics, probs = topic_model.fit_transform(docs)
new_topics, new_probs = topic_model.reduce_topics(docs, topics, probs, nr_topics=30)

print(new_topics[0])
print(new_probs[0])
```
I got
```
0
[0.01162362 0.01197486 0.008518   0.06038103 0.16473175 0.04079475
 0.04811648 0.05457505 0.00921362 0.05799419 0.04065328 0.05116384
 0.01711968 0.02168007 0.02459595 0.03512971 0.03317996 0.04225039
 0.01767583 0.01367553 0.01373571 0.00673203 0.02632893 0.01785869
 0.02088126 0.02590666 0.0126927  0.01983599 0.02199862 0.0084086 ]
```
But `new_probs[0][0] (0.01162362)` is not the largest. In fact, most numbers are larger than it, and it seems it should be assigned to topic 4 with `0.16473175` as probability. 

Am I wrong in my interpretation?

**Comment by MaartenGr** [comment]
Are you using the latest version (v0.9 or [v0.9.1](https://github.com/MaartenGr/BERTopic/pull/211)) of BERTopic? If so, I would advise you to use the `nr_topics` parameter when instantiating BERTopic: `topic_model = BERTopic(language="english", calculate_probabilities=True, nr_topics=30)`. That might solve your issue. Otherwise, updating to the latest version might be the solution.

**Comment by dlu-lv** [comment]
Thanks for the response. I'm using v0.9.1. 

Initializing `topic_model = BERTopic(language="english", calculate_probabilities=True, nr_topics=30)` works, but that means I have to `fit-transform` every time I want to check on a new `nr_topics`, which I assume will be more expensive and time consuming than if I could `fit-transform` once and use `reduce_topics` multiple times.  Well, it is what it is, and I will avoid using `reduce_topics` for now.

Thanks for your help.
