### ISSUE TITLE
Attempt to use Seeded Topics throws an exception

### ISSUE THREAD

**Issue by pramodith** [MaartenGr/BERTopic#221]
Hi, I've been trying to play around with the use of seeded topics based on the example [here](https://maartengr.github.io/BERTopic/tutorial/guided/guided.html). However I see the error shown below.

![image](https://user-images.githubusercontent.com/16939722/131710827-ece4edff-a12f-4944-880a-3f1831ad8b6c.png)

TypeError: No loop matching the specified signature and casting was found for ufunc add`

I also made sure that I was using the latest version of the library.
![image](https://user-images.githubusercontent.com/16939722/131710427-50e66c94-d9c8-4199-b5f5-293d44d3f375.png)

Any guidance on this would be appreciated.

**Comment by MaartenGr** [comment]
This is a known issue with numpy and numba not properly working together. If you follow along the steps [here](https://github.com/MaartenGr/BERTopic/issues/202#issuecomment-904494090) then it should work.

**Comment by pramodith** [comment]
The solution works! Thanks, closing this issue.
