### ISSUE TITLE
TypeError: visualize_topics_over_time() got multiple values for argument 'top_n_topics'

### ISSUE THREAD

**Issue by doubianimehdi** [MaartenGr/BERTopic#222]
Hi,

I've run this code with BERTopic 0.9.1 
from bertopic import BERTopic
from sklearn.feature_extraction.text import CountVectorizer
#topic_model = BERTopic.load("my_model")
vectorizer_model = CountVectorizer(ngram_range=(1, 2),stop_words=final_stop_words, min_df=10)
topic_model = BERTopic(low_memory=True,verbose=True, embedding_model="paraphrase-MiniLM-L12-v2", nr_topics=25,calculate_probabilities=True,vectorizer_model=vectorizer_model)
abstract=list(df_reduced['Title+Abstract'])
years = list(df_reduced['pubyear'])
#topics, _ = topic_model.fit_transform(abstract); len(topic_model.get_topic_info())
topics, probabilities = topic_model.fit_transform(abstract)

But when I try to visualize topics over time I have the following message :
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_5264/1813177034.py in <module>
----> 1 topic_model.visualize_topics_over_time(topic_model, topics_over_time, top_n_topics=25, width=900, height=500,normalize_frequency=True)

TypeError: visualize_topics_over_time() got multiple values for argument 'top_n_topics'

Thanks for your help ...

**Comment by MaartenGr** [comment]
There is no need to pass the topic model to itself. You only need to pass the topic model if you are using the `plotting` library. In other words, simply use it like this:

```python
topic_model.visualize_topics_over_time(topics_over_time, top_n_topics=25, width=900, height=500,normalize_frequency=True)

**Comment by doubianimehdi** [comment]
oh right ! yes that's the workaround you gave me until 0.9.1 came out ! Thanks that makes more sense !
