### ISSUE TITLE
v0.9.1?

### ISSUE THREAD

**Issue by kailiwu** [MaartenGr/BERTopic#223]
Why I can't install v0.9.1?
![image](https://user-images.githubusercontent.com/15731867/131843751-f8160709-1f2c-4405-ad99-cc7b18eb14fa.png)

**Comment by kailiwu** [comment]
OS: ubuntu
python:3.8.8 
pip: 21.2.4

**Comment by kailiwu** [comment]
> Have you tried upgrading `pip` to the latest version? Also, which OS are you currently running?

OS: ubuntu
python:3.8.8
pip: 21.2.4

**Comment by MaartenGr** [comment]
Could you try running it from a fresh environment with a stable internet connection?

**Comment by kailiwu** [comment]
I made it. Thank you very much!

**Comment by MaartenGr** [comment]
Glad to help 😄
