### ISSUE TITLE
Clarification on the meaning of normalized frequency

### ISSUE THREAD

**Issue by doubianimehdi** [MaartenGr/BERTopic#224]
Hi,

On one issue you answered about the definition of normalized frequency : 
-------------------------------------------------------------------------------------------------------------------------------------------
In the calculation of topics_over_time the frequency of documents in a topic is counted. Here, only a hard clustering is counted. In other words, each document is assigned to a single topic at a single timestep t. Each document can only be counted towards a single topic at a single timestep t.

Hopefully, this clears things up a bit. Let me know if you have any further questions!
-------------------------------------------------------------------------------------------------------------------------------------------

I'm having a hard time understanding this normalization process, i've seen in the code that you use normalize from scikit learn and reshape the frequency values column but i don't know what the end result means ... could you explain more ? thanks !!!

**Comment by MaartenGr** [comment]
My answer to the question you refer to seems to be unrelated to the normalized frequency. It is merely a counting action rather than a normalization procedure. Which exact code are you referring to?

**Comment by doubianimehdi** [comment]
I am referring to this piece of code in visualize_topics_over_time function : 
if normalize_frequency:
            y = normalize(trace_data.Frequency.values.reshape(1, -1))[0]
        else:
            y = trace_data.Frequency

**Comment by MaartenGr** [comment]
Ah, that piece of code is meant to normalize each line in the generated time series. The goal is to make sure that the curve of the lines can be compared to each other. For example, if you have a topic that has a frequency of 10000 and a topic that has a frequency of 100, then it will be difficult to compare the lines in a graph as the latter will seem to have a flat line. By normalizing the lines, we can compare them more easily with each other.

**Comment by doubianimehdi** [comment]
Ok ! But normalization isn't it supposed , if we add every point in time, to add up to 1 ? which is not the case here ... that's why i'm a bit confused ...

**Comment by MaartenGr** [comment]
Could you create a reproducible example of the issue that you are facing? That way, I can more accurately analyse the issue.

**Comment by doubianimehdi** [comment]
After reflecting on the matter, it's just that the naming Normalized Frequency is a bit misleading, it's just a reduction between 0 and 1 to allow better plotting of values with a big gap like you said, it shouldn't be interpreted in term of frequency but just a mean to visualize the trend and not the values themselves (frequency is enough for that). I won't bother you again with that thank you very much for your help !
