### ISSUE TITLE
Drop support for Python 3.8

### ISSUE THREAD

**Issue by afuetterer** [MaartenGr/BERTopic#2240]
### Feature request

This is not really a feature request nor a bug report. It is in between. 

Python 3.8 reached EOL in October. I suggest dropping it.

### Motivation

See #1942 and https://devguide.python.org/versions

### Your contribution

Would you like me to submit a PR?

**Comment by afuetterer** [comment]
Also you will run into trouble, when dependencies only support 3.9+. 

For example datamapplot is 3.9+ only.

**Comment by MaartenGr** [comment]
@afuetterer Thanks for sharing this! Fully agree, dropping support would be best as main dependencies are also dropping it (e.g., [sentence-transformers](https://github.com/UKPLab/sentence-transformers/blob/master/pyproject.toml)). A PR would be appreciated!
