### ISSUE TITLE
save failing on Colab

### ISSUE THREAD

**Issue by drob-xx** [MaartenGr/BERTopic#225]
I'm attempting to call save in Colab environment, writing to the same dir that I read the corpus from. I get the error below, hints appreciated.

MY CODE: 
----------------------
docs = []
fh = open('/content/drive/MyDrive/Projects2/Congweb/TEXT_ALLRECS_090521.txt',"r")
docs = fh.readlines()
fh.close()
print("Fitting All Data")
model = BERTopic(calculate_probabilities=False, low_memory=True)
topics, probabilities = model.fit_transform(docs)
print("Saving model")
model.save('/content/drive/MyDrive/Projects2/Congweb/model_ALLRECS_090521')
print("done")

ERROR:
------------------------------------
KeyError                                  Traceback (most recent call last)
/usr/local/lib/python3.7/dist-packages/numba/core/caching.py in save(self, key, data)
    486             # If key already exists, we will overwrite the file
--> 487             data_name = overloads[key]
    488         except KeyError:

KeyError: ((array(int32, 1d, C), array(int32, 1d, C), array(float32, 1d, C), array(float32, 2d, C), type(CPUDispatcher(<function alternative_cosine at 0x7ff771180320>)), array(int64, 1d, C), float64), ('x86_64-unknown-linux-gnu', 'broadwell', '+64bit,+adx,+aes,+avx,+avx2,-avx512bf16,-avx512bitalg,-avx512bw,-avx512cd,-avx512dq,-avx512er,-avx512f,-avx512ifma,-avx512pf,-avx512vbmi,-avx512vbmi2,-avx512vl,-avx512vnni,-avx512vpopcntdq,+bmi,+bmi2,-cldemote,-clflushopt,-clwb,-clzero,+cmov,+cx16,+cx8,-enqcmd,+f16c,+fma,-fma4,+fsgsbase,+fxsr,-gfni,+invpcid,-lwp,+lzcnt,+mmx,+movbe,-movdir64b,-movdiri,-mwaitx,+pclmul,-pconfig,-pku,+popcnt,-prefetchwt1,+prfchw,-ptwrite,-rdpid,+rdrnd,+rdseed,+rtm,+sahf,-sgx,-sha,-shstk,+sse,+sse2,+sse3,+sse4.1,+sse4.2,-sse4a,+ssse3,-tbm,-vaes,-vpclmulqdq,-waitpkg,-wbnoinvd,-xop,+xsave,-xsavec,+xsaveopt,-xsaves'), ('308c49885ad3c35a475c360e21af1359caa88c78eb495fa0f5e8c6676ae5019e', 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855'))

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
30 frames
/usr/local/lib/python3.7/dist-packages/numba/core/caching.py in _dump(self, obj)
    568 
    569     def _dump(self, obj):
--> 570         return pickle.dumps(obj, protocol=-1)
    571 
    572     @contextlib.contextmanager

TypeError: can't pickle weakref objects

**Comment by MaartenGr** [comment]
I believe there is currently an [issue](https://github.com/MaartenGr/BERTopic/issues/203) with numba that prevents proper saving. I suggest starting out with upgrading numba to the newest version and trying again: `pip install --upgrade numba`.

**Comment by drob-xx** [comment]
That worked! Thanks a bunch.
