### ISSUE TITLE
RuntimeError: Failed to import transformers.integrations.integration_utils because of the following error (look up to see its traceback): Failed to import transformers.modeling_utils because of the following error (look up to see its traceback): partially initialized module 'torch._dynamo' has no attribute 'external_utils' (most likely due to a circular import)

### ISSUE THREAD

**Issue by tempdeltavalue** [MaartenGr/BERTopic#2255]
### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Desribe the bug

!pip install bertopic
from bertopic import BERTopic

RuntimeError: Failed to import transformers.integrations.integration_utils because of the following error (look up to see its traceback):
Failed to import transformers.modeling_utils because of the following error (look up to see its traceback):
partially initialized module 'torch._dynamo' has no attribute 'external_utils' (most likely due to a circular import)

![Screenshot 2024-12-24 182529](https://github.com/user-attachments/assets/ee251e7c-1518-43c8-ba51-c7faeb22da52)

### Reproduction

```python
from bertopic import BERTopic

```

### BERTopic Version

I don't know

**Comment by MaartenGr** [comment]
It seems like there is something going on with your environment. I would suggest starting from a completely fresh environment and installing BERTopic there before installing something else. 

Also note that I can only provide limited help without knowing the BERTopic version.

**Comment by tempdeltavalue** [comment]
@MaartenGr 
Issue inside of colab environment
https://colab.research.google.com/drive/1lKW7YIIIsNAK08CFvbHVKjHY4GYpg9_k?usp=sharing

version is 0.16.4

**Comment by MaartenGr** [comment]
@tempdeltavalue Did you try to restart your environment? When I run your code I get no errors.
