### ISSUE TITLE
A Question on Ensemble Models for BERTopic

### ISSUE THREAD

**Issue by gsalfourn** [MaartenGr/BERTopic#228]
Hi Maarten,

I was just thinking  about an ensemble model using BERTopic, and I have a question for you in that regard. I was wondering if you have any advice about ensembling topics from different Embedding models - Sentence Transformers, Flair, Spacy, and USE.

**Comment by MaartenGr** [comment]
There are a few ways of approaching this. 

First, you can use Flair ([here](https://github.com/flairNLP/flair/blob/master/resources/docs/TUTORIAL_4_ELMO_BERT_FLAIR_EMBEDDING.md) or [here](https://github.com/flairNLP/flair/blob/master/resources/docs/TUTORIAL_5_DOCUMENT_EMBEDDINGS.md)) to combine/stack/pool different embedding models. The resulting model can simply be passed to BERTopic.

Second, you can create your own custom embedding model and pass that to BERTopic (see documentation [here](https://maartengr.github.io/BERTopic/tutorial/embeddings/embeddings.html#custom-backend)). If you have a custom way of combining/ensembling embedding models, then that might be the preferred method. 

Does that answer your question?

**Comment by gsalfourn** [comment]
yes, it does. Thanks so much
