### ISSUE TITLE
Annotate documents using topics!

### ISSUE THREAD

**Issue by Fati-Hei** [MaartenGr/BERTopic#229]
I don't see how can make topics available per each document? (attache topic to its document)

**Comment by MaartenGr** [comment]
When you run BERTopic like this:

```python
from bertopic import BERTopic
from sklearn.datasets import fetch_20newsgroups
 
docs = fetch_20newsgroups(subset='all',  remove=('headers', 'footers', 'quotes'))['data']

topic_model = BERTopic()
topics, probs = topic_model.fit_transform(docs)
```

Then each topic in `topics` corresponds to a document in `docs`. That way, you know which topic relates to which document.

**Comment by Fati-Hei** [comment]
Oh , I see then I used model.get_topic_info(topic_number) to get topic words.
Thanks for a great job you have done. :)
