### ISSUE TITLE
fit_transform error TF-IDF embeddings

### ISSUE THREAD

**Issue by soumitra9** [MaartenGr/BERTopic#230]
Hi,

I am getting the following error: "_**TypeError: can't pickle weakref objects**_" when using

vectorizer = TfidfVectorizer(min_df=5)
embeddings = vectorizer.fit_transform(docs)

model = BERTopic(low_memory=True, calculate_probabilities=False)
topics, _ = model_neu.fit_transform(docs, embeddings)

Could you please help?

**Comment by MaartenGr** [comment]
I believe this is related to numba interacting strangely with UMAP/pynndescent.  I suggest starting out with upgrading numba to the newest version and trying again: `pip install --upgrade numba`.
