### ISSUE TITLE
Predict topics on unseen data.

### ISSUE THREAD

**Issue by Fati-Hei** [MaartenGr/BERTopic#231]
Is it possible to predict topics on unseen data from model which has been fitted on another dataset?

**Comment by MaartenGr** [comment]
Yes! After training your model like this:

```python
from bertopic import BERTopic
from sklearn.datasets import fetch_20newsgroups
 
docs = fetch_20newsgroups(subset='all',  remove=('headers', 'footers', 'quotes'))['data']

topic_model = BERTopic()
topics, probs = topic_model.fit_transform(docs)
```

You can then predict for new instances like this:
```python
other_topics, other_probs = topic_model.transform(other_docs)
```

**Comment by Fati-Hei** [comment]
Actually I performed it in that way but it returns a KeyError: 0 with a long traceback.

This is the error, it would be great if you take a look.

`KeyError: 0
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
/usr/local/homebrew/Cellar/python@3.7/3.7.11/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pandas/core/indexes/base.py in get_loc(self, key, method, tolerance)
   3360             try:
-> 3361                 return self._engine.get_loc(casted_key)
   3362             except KeyError as err:

/usr/local/homebrew/Cellar/python@3.7/3.7.11/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

/usr/local/homebrew/Cellar/python@3.7/3.7.11/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: 0

The above exception was the direct cause of the following exception:

KeyError                                  Traceback (most recent call last)
/var/folders/cr/9p_j91q947b4zv1gp0xf_21r0000gn/T/ipykernel_73778/1487294494.py in <module>
----> 1 d2topics, d2probs = b_topic_model.transform(data2)

/usr/local/homebrew/Cellar/python@3.7/3.7.11/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/bertopic/_bertopic.py in transform(self, documents, embeddings)
    362             embeddings = self._extract_embeddings(documents,
    363                                                   method="document",
--> 364                                                   verbose=self.verbose)
    365 
    366         umap_embeddings = self.umap_model.transform(embeddings)

/usr/local/homebrew/Cellar/python@3.7/3.7.11/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/bertopic/_bertopic.py in _extract_embeddings(self, documents, method, verbose)
   1322             embeddings = self.embedding_model.embed_words(documents, verbose)
   1323         elif method == "document":
-> 1324             embeddings = self.embedding_model.embed_documents(documents, verbose)
   1325         else:
   1326             raise ValueError("Wrong method for extracting document/word embeddings. "

/usr/local/homebrew/Cellar/python@3.7/3.7.11/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/bertopic/backend/_base.py in embed_documents(self, document, verbose)
     67             that each have an embeddings size of `m`
     68         """
---> 69         return self.embed(document, verbose)

/usr/local/homebrew/Cellar/python@3.7/3.7.11/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/bertopic/backend/_sentencetransformers.py in embed(self, documents, verbose)
     61             that each have an embeddings size of `m`
     62         """
---> 63         embeddings = self.embedding_model.encode(documents, show_progress_bar=verbose)
     64         return embeddings

/usr/local/homebrew/Cellar/python@3.7/3.7.11/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sentence_transformers/SentenceTransformer.py in encode(self, sentences, batch_size, show_progress_bar, output_value, convert_to_numpy, convert_to_tensor, device, normalize_embeddings)
    150         all_embeddings = []
    151         length_sorted_idx = np.argsort([-self._text_length(sen) for sen in sentences])
--> 152         sentences_sorted = [sentences[idx] for idx in length_sorted_idx]
    153 
    154         for start_index in trange(0, len(sentences), batch_size, desc="Batches", disable=not show_progress_bar):

/usr/local/homebrew/Cellar/python@3.7/3.7.11/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sentence_transformers/SentenceTransformer.py in <listcomp>(.0)
    150         all_embeddings = []
    151         length_sorted_idx = np.argsort([-self._text_length(sen) for sen in sentences])
--> 152         sentences_sorted = [sentences[idx] for idx in length_sorted_idx]
    153 
    154         for start_index in trange(0, len(sentences), batch_size, desc="Batches", disable=not show_progress_bar):

/usr/local/homebrew/Cellar/python@3.7/3.7.11/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pandas/core/frame.py in __getitem__(self, key)
   3453             if self.columns.nlevels > 1:
   3454                 return self._getitem_multilevel(key)
-> 3455             indexer = self.columns.get_loc(key)
   3456             if is_integer(indexer):
   3457                 indexer = [indexer]

/usr/local/homebrew/Cellar/python@3.7/3.7.11/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pandas/core/indexes/base.py in get_loc(self, key, method, tolerance)
   3361                 return self._engine.get_loc(casted_key)
   3362             except KeyError as err:
-> 3363                 raise KeyError(key) from err
   3364 
   3365         if is_scalar(key) and isna(key) and not self.hasnans:

KeyError: 0`

**Comment by MaartenGr** [comment]
Which version of BERTopic are you currently using? If you do not have 0.9.1 installed it might be an idea to try out that version. Also, what kind of type is `data2`  in `d2topics, d2probs = b_topic_model.transform(data2)`?

**Comment by Fati-Hei** [comment]
The version is 0.9.0 and python version is 3.7. Data2 is a list of string values.
But when I try it with new values which they are also list of strings I get this error:
/usr/local/homebrew/Cellar/python@3.7/3.7.11/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/scipy/sparse/_index.py:126: SparseEfficiencyWarning: Changing the sparsity structure of a csr_matrix is expensive. lil_matrix is more efficient.
  self._set_arrayXarray(i, j, x)
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by MaartenGr** [comment]
This seems like an issue that was resolved in v0.9.1. Could you update BERTopic to the newest version and try again?

**Comment by Fati-Hei** [comment]
Yes, the upgrade resolved the problem. Now I am able to predict on new data.
pip install bertopic --upgrade
Thanks :)

**Comment by MaartenGr** [comment]
Great! I am glad that it all worked out. Let me know if you have any other questions.
