### ISSUE TITLE
save topic model

### ISSUE THREAD

**Issue by aph61** [MaartenGr/BERTopic#237]
Hi,

When running the "classical" (nothing fancy) BERTopic and wish to save the model I receive the following error

```
topic_model = BERTopic(embedding_model=sentence_model,
                               min_topic_size=min_topic_size)
topic_model.save(os.path.join(models_dir, filename_model_prefix + "_" + "topic.model"))
```
I run this on the GCP in a GPU environment. A regular pickle dump does not work either. 

If I run the same code on my laptop the topic_model.save() does not work, a regular pickle does. Unfortunately the GCP and laptop are not binary compatible.

Suggestions, hints??

thanks, 

Andreas

"TypeError: can't pickle weakref objects" (details below)

KeyError                                  Traceback (most recent call last)
/usr/local/lib/python3.7/dist-packages/numba/core/caching.py in save(self, key, data)
    486             # If key already exists, we will overwrite the file
--> 487             data_name = overloads[key]
    488         except KeyError:

KeyError: ((array(int64, 2d, C), array(float32, 2d, C), array(float32, 2d, C), type(CPUDispatcher(<function alternative_cosine at 0x7fc9980ec050>)), array(int64, 1d, C), float64), ('x86_64-unknown-linux-gnu', 'haswell', '+64bit,-adx,+aes,+avx,+avx2,-avx512bf16,-avx512bitalg,-avx512bw,-avx512cd,-avx512dq,-avx512er,-avx512f,-avx512ifma,-avx512pf,-avx512vbmi,-avx512vbmi2,-avx512vl,-avx512vnni,-avx512vpopcntdq,+bmi,+bmi2,-cldemote,-clflushopt,-clwb,-clzero,+cmov,+cx16,+cx8,-enqcmd,+f16c,+fma,-fma4,+fsgsbase,+fxsr,-gfni,+invpcid,-lwp,+lzcnt,+mmx,+movbe,-movdir64b,-movdiri,-mwaitx,+pclmul,-pconfig,-pku,+popcnt,-prefetchwt1,-prfchw,-ptwrite,-rdpid,+rdrnd,-rdseed,-rtm,+sahf,-sgx,-sha,-shstk,+sse,+sse2,+sse3,+sse4.1,+sse4.2,-sse4a,+ssse3,-tbm,-vaes,-vpclmulqdq,-waitpkg,-wbnoinvd,-xop,+xsave,-xsavec,+xsaveopt,-xsaves'), ('1566b624ec4710ff21277d163ff1d5d780943ac8328dcb5962340daf38986bdc', 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855'))

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
12 frames
/usr/local/lib/python3.7/dist-packages/numba/core/caching.py in _dump(self, obj)
    568 
    569     def _dump(self, obj):
--> 570         return pickle.dumps(obj, protocol=-1)
    571 
    572     @contextlib.contextmanager

TypeError: can't pickle weakref objects

**Comment by MaartenGr** [comment]
I believe there is currently an [issue](https://github.com/MaartenGr/BERTopic/issues/203) with numba that prevents proper saving. I suggest starting out with upgrading numba to the newest version and trying again: `pip install --upgrade numba`.

**Comment by aph61** [comment]
Hi MaartenGr/BERTopic

Thanks for the pointer. I added

!pip install --upgrade numba

to the code and the problem was solved.

thanks,

Andreas
