### ISSUE TITLE
'Transformer' object has no attribute 'do_lower_case'

### ISSUE THREAD

**Issue by bonadossouroche** [MaartenGr/BERTopic#238]
bertopic_model= BERTopic.load("path/models/bertopic_models/")
bertopic_model.calculate_probabilities=True

print(cause_statement_bertopic.fit_transform(['Here is a sample text']))

Then I have the following errior: "'Transformer' object has no attribute 'do_lower_case'"

Here is the trace:
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-16-2e714fbe5de1> in <module>

/usr/local/lib/python3.7/site-packages/bertopic/_bertopic.py in fit_transform(self, documents, embeddings, y)
    276             embeddings = self._extract_embeddings(documents.Document,
    277                                                   method="document",
--> 278                                                   verbose=self.verbose)
    279             logger.info("Transformed documents to Embeddings")
    280         else:

/usr/local/lib/python3.7/site-packages/bertopic/_bertopic.py in _extract_embeddings(self, documents, method, verbose)
   1322             embeddings = self.embedding_model.embed_words(documents, verbose)
   1323         elif method == "document":
-> 1324             embeddings = self.embedding_model.embed_documents(documents, verbose)
   1325         else:
   1326             raise ValueError("Wrong method for extracting document/word embeddings. "

/usr/local/lib/python3.7/site-packages/bertopic/backend/_base.py in embed_documents(self, document, verbose)
     67             that each have an embeddings size of `m`
     68         """
---> 69         return self.embed(document, verbose)

/usr/local/lib/python3.7/site-packages/bertopic/backend/_sentencetransformers.py in embed(self, documents, verbose)
     61             that each have an embeddings size of `m`
     62         """
---> 63         embeddings = self.embedding_model.encode(documents, show_progress_bar=verbose)
     64         return embeddings

/usr/local/lib/python3.7/site-packages/sentence_transformers/SentenceTransformer.py in encode(self, sentences, batch_size, show_progress_bar, output_value, convert_to_numpy, convert_to_tensor, device, normalize_embeddings)
    154         for start_index in trange(0, len(sentences), batch_size, desc="Batches", disable=not show_progress_bar):
    155             sentences_batch = sentences_sorted[start_index:start_index+batch_size]
--> 156             features = self.tokenize(sentences_batch)
    157             features = batch_to_device(features, device)
    158 

/usr/local/lib/python3.7/site-packages/sentence_transformers/SentenceTransformer.py in tokenize(self, texts)
    307         Tokenizes the texts
    308         """
--> 309         return self._first_module().tokenize(texts)
    310 
    311     def get_sentence_features(self, *features):

/usr/local/lib/python3.7/site-packages/sentence_transformers/models/Transformer.py in tokenize(self, texts)
     94 
     95         #Lowercase
---> 96         if self.do_lower_case:
     97             to_tokenize = [[s.lower() for s in col] for col in to_tokenize]
     98 

/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py in __getattr__(self, name)
   1129                 return modules[name]
   1130         raise AttributeError("'{}' object has no attribute '{}'".format(
-> 1131             type(self).__name__, name))
   1132 
   1133     def __setattr__(self, name: str, value: Union[Tensor, 'Module']) -> None:

AttributeError: 'Transformer' object has no attribute 'do_lower_case'

**Comment by MaartenGr** [comment]
This has happened before in a previous issue and I believe that the environments in which the models were trained and loaded are different. It could be that you are trying out a different environment than the one in which the model was trained which could lead to this issue. 

Did you update any packages between training and loading the model?

**Comment by bonadossouroche** [comment]
Not really. I tried this template you provided on the pip page, and it worked.

import re
import pandas as pd
trump = pd.read_csv('https://drive.google.com/uc?export=download&id=1xRKHaP-QwACMydlDnyFPEaFdtskJuBa6')
trump.text = trump.apply(lambda row: re.sub(r"http\S+", "", row.text).lower(), 1)
trump.text = trump.apply(lambda row: " ".join(filter(lambda x:x[0]!="@", row.text.split())), 1)
trump.text = trump.apply(lambda row: " ".join(re.sub("[^a-zA-Z]+", " ", row.text).split()), 1)
trump = trump.loc[(trump.isRetweet == "f") & (trump.text != ""), :]
timestamps = trump.date.to_list()
tweets = trump.text.to_list()

topic_model = BERTopic(verbose=True)
topics, probs = topic_model.fit_transform(tweets)

But as soon as I changed it with the loaded model, it crashes with the error: "'Transformer' object has no attribute 'do_lower_case'"

**Comment by bonadossouroche** [comment]
What is the syntax to load a model, please?

**Comment by MaartenGr** [comment]
You can find the syntax to load and save a model in the documentation [here](https://maartengr.github.io/BERTopic/tutorial/quickstart/quickstart.html#saveload-bertopic-model). I would advise making sure you stay in the same environment and follow along with the posted link.

**Comment by bonadossouroche** [comment]
Thanks, it finally worked :)
