### ISSUE TITLE
Is there working Dockerfile with BERTopic?

### ISSUE THREAD

**Issue by takiholadi** [MaartenGr/BERTopic#240]
Since I faced with multiple version troubles.

**Comment by takiholadi** [comment]
`_pickle.PicklingError: Can't pickle <class 'tensorflow.python.saved_model.load.Loader._recreate_base_user_object.<locals>._UserObject'>: it's not found as tensorflow.python.saved_model.load.Loader._recreate_base_user_object.<locals>._UserObject
`

sample of problem on `topic_model.save()`

**Comment by MaartenGr** [comment]
Could you share your entire code (including the dockerfile)? It is difficult to see where the issue stems from without your code. It might be related to the embedding model that you use but I cannot be sure.

**Comment by MaartenGr** [comment]
I am closing this now due to inactivity. However, if you are still experiencing this issue or another, please let me know!
