### ISSUE TITLE
Is it OK to increase `core_dist_n_jobs` for hdbscan under the hood?

### ISSUE THREAD

**Issue by takiholadi** [MaartenGr/BERTopic#244]
Or something could go wrong. Since such extra param is not provided.

**Comment by MaartenGr** [comment]
You can adapt the parameters of HDBSCAN by following [this](https://maartengr.github.io/BERTopic/tutorial/models/models.html) page in the documentation. 

In practice, it would work something like this: 
```python
from bertopic import BERTopic
from hdbscan import HDBSCAN

hdbscan_model = HDBSCAN(min_cluster_size=10, metric='euclidean', 
                        cluster_selection_method='eom', prediction_data=True, core_dist_n_job=-1)

topic_model = BERTopic(hdbscan_model=hdbscan_model)
```

Make sure to use the same default parameters as can be found here:
https://github.com/MaartenGr/BERTopic/blob/0b321678ffe4eab0a28484faf76728f584a94ebd/bertopic/_bertopic.py#L157-L160
