### ISSUE TITLE
ModelLoading problem

### ISSUE THREAD

**Issue by randomrdrand** [MaartenGr/BERTopic#252]
I previously saved my model as following: 

    topic_model.save("RoBERTa_4Grams3.0final")  

now when i try to load it with this code it gives me an EOFError:

     topic_model = BERTopic.load("/content/RoBERTa", embedding_model=model)

I also tried loading the model without specifying the embedding model but it's not working, I appreciate your help and time. Looking forward to hearing from you

Ps. I imported Bertopic with all flair

**Comment by MaartenGr** [comment]
I have a few questions that hopefully give me the entire picture. Did you change anything within your environment between saving and loading the model? Could you share the entire code? Could you share the entire EOFError? It is difficult to pinpoint the issue without knowing how you exactly run the code and what the exact error is.

**Comment by randomrdrand** [comment]
Here is the EOFERROR: 

    ---------------------------------------------------------------------------
    EOFError                                  Traceback (most recent call last)
    <ipython-input-10-1ca684c95775> in <module>()
     ----> 1 topic_model = BERTopic.load("/content/RoBERTa", embedding_model=model)

      3 frames
       /usr/lib/python3.7/pickle.py in load(self)
       1084                 key = read(1)
       1085                 if not key:
       -> 1086                     raise EOFError
       1087                 assert isinstance(key, bytes_types)
       1088                 dispatch[key[0]](self)

     EOFError: 


Also I saved the model using Google AI Platform enviroment now I'm trying to load it in Google Colaboratory enviroment. Also the model saved file has text on it so it's not empty

**Comment by randomrdrand** [comment]
UPDATE: running the same code today i came across this new error and not the EOFERROR


  KeyError                                  Traceback (most recent call last)
  <ipython-input-7-3e92b5887812> in <module>()
  ----> 1 topic_model = BERTopic.load("/content/RoBERTa_4G")
  
          3 frames
          /usr/lib/python3.7/pickle.py in load(self)
          1086                     raise EOFError
          1087                 assert isinstance(key, bytes_types)
          -> 1088                 dispatch[key[0]](self)
          1089         except _Stop as stopinst:
          1090             return stopinst.value
          
          KeyError: 30

**Comment by MaartenGr** [comment]
Hmmmm, I would advise using the exact same environment (package-wise) for loading the model as when you saved it. The dependencies in BERTopic make it difficult at times to load and save the model between environments.

**Comment by randomrdrand** [comment]
I am importing the same packages but the problem is not resolved yet. I think that I need to rerun the model

**Comment by MaartenGr** [comment]
It is not just about the same packages but making sure that they have the same version as in the environment you trained them. For example, if you trained BERTopic with numpy==1.20.1, then it is highly advised to keep the same numpy version in the new environment.

**Comment by randomrdrand** [comment]
I totally understand you. I didn't make so much attention when I saved the model. So I don't know all the package versions at that time. Thank you very much for your help and time!
