### ISSUE TITLE
search docments by topic

### ISSUE THREAD

**Issue by yutiansh4** [MaartenGr/BERTopic#256]
hi, 
 Firstly, thank you very much for providing this service. Can you provide an interface to search the most similar documents by topic?

**Comment by MaartenGr** [comment]
You can match the `topics` output to the documents and simply extract the documents per topic from there. However, if you want to extract the documents that best represent the topics, I would advise using `topic_model.get_representative_docs(topic=5)`.

**Comment by yutiansh4** [comment]
Ok, Thank you very much!
