### ISSUE TITLE
Having problems running BERT model 

### ISSUE THREAD

**Issue by randomrdrand** [MaartenGr/BERTopic#259]
This is the error I am getting can someone help?

/usr/local/lib/python3.7/dist-packages/distributed/config.py:20: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  defaults = yaml.load(f)
Batches: 100%
5081/5082 [37:48<00:00, 7.61it/s]
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-7-c40829dbf77a> in <module>()
      2 
      3 topic_model = BERTopic(embedding_model="roberta-base-nli-stsb-mean-tokens", n_gram_range= [1,3], vectorizer_model=vectorizer_model, calculate_probabilities=False, low_memory=True, verbose=True)
----> 4 topics, _ = topic_model.fit_transform(doc_list)

8 frames
/usr/local/lib/python3.7/dist-packages/sentence_transformers/models/Transformer.py in <listcomp>(.0)
     82 
     83         #strip
---> 84         to_tokenize = [[s.strip() for s in col] for col in to_tokenize]
     85 
     86         #Lowercase

AttributeError: 'float' object has no attribute 'strip'

**Comment by randomrdrand** [comment]
Update:

/usr/local/lib/python3.7/dist-packages/distributed/config.py:20: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  defaults = yaml.load(f)
Batches: 100%
5082/5082 [37:03<00:00, 10.61it/s]
2021-09-27 19:40:21,706 - BERTopic - Transformed documents to Embeddings
/usr/local/lib/python3.7/dist-packages/numba/np/ufunc/parallel.py:363: NumbaWarning: The TBB threading layer requires TBB version 2019.5 or later i.e., TBB_INTERFACE_VERSION >= 11005. Found TBB_INTERFACE_VERSION = 9107. The TBB threading layer is disabled.
  warnings.warn(problem)
2021-09-27 19:45:19,382 - BERTopic - Reduced dimensionality with UMAP
2021-09-27 19:45:47,658 - BERTopic - Clustered UMAP embeddings with HDBSCAN
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-6-c40829dbf77a> in <module>()
      2 
      3 topic_model = BERTopic(embedding_model="roberta-base-nli-stsb-mean-tokens", n_gram_range= [1,3], vectorizer_model=vectorizer_model, calculate_probabilities=False, low_memory=True, verbose=True)
----> 4 topics, _ = topic_model.fit_transform(doc_list)

10 frames
/usr/local/lib/python3.7/dist-packages/pandas/core/groupby/groupby.py in <lambda>(x)
   1060         func = self._is_builtin_func(func)
   1061         if engine != "numba":
-> 1062             f = lambda x: func(x, *args, **kwargs)
   1063 
   1064         # iterate through "columns" ex exclusions to populate output dict

TypeError: sequence item 73701: expected str instance, float found


Ps. I'm running the Bertopic library in colab

**Comment by MaartenGr** [comment]
Could you share the entire code for setting up BERTopic? Also, are you sure you are passing only strings?

**Comment by randomrdrand** [comment]
Here it is:

      !pip install bertopic[all]
      import pandas as pd
      data = pd.read_csv("/content/CompleteShortData.csv")
    
      from sentence_transformers import SentenceTransformer
      model = SentenceTransformer('roberta-base-nli-stsb-mean-tokens')
     
      from sklearn.feature_extraction.text import CountVectorizer
      
      vectorizer_model = CountVectorizer(ngram_range=(1, 3), stop_words="english", min_df=2)
      
      from bertopic import BERTopic
      
      topic_model = BERTopic(embedding_model="roberta-base-nli-stsb-mean-tokens", n_gram_range= [1,3], vectorizer_model=vectorizer_model, calculate_probabilities=False, low_memory=True, verbose=True)
      topics, _ = topic_model.fit_transform(doc_list)

**Comment by randomrdrand** [comment]
By the way, I ran the same code and it was working pretty good

**Comment by randomrdrand** [comment]
Yes i started from the Colab environment. I previously tried "pip install bertopic" but i think that resulted in the first error. While the second one was cause by the "[all]" I think. I want to use a RoBERTa model implementation that is why I mentioned that specific embedding model. Can you provide RoBERTa implementation alternatives?

**Comment by MaartenGr** [comment]
The following worked for me in a fresh Google Colab session:

```
!pip install bertopic
```

I restarted the notebook and ran the following:

```python
import pandas as pd
from bertopic import BERTopic
from sklearn.datasets import fetch_20newsgroups
from sklearn.feature_extraction.text import CountVectorizer

# Prepare data and classes
data = fetch_20newsgroups(subset='all',  remove=('headers', 'footers', 'quotes'))
docs = data["data"]
classes = [data["target_names"][i] for i in data["target"]]

# Train model
vectorizer_model = CountVectorizer(ngram_range=(1, 3), stop_words="english", min_df=2)
topic_model = BERTopic(embedding_model="roberta-base-nli-stsb-mean-tokens", vectorizer_model=vectorizer_model, calculate_probabilities=False, low_memory=True, verbose=True)
topics, _ = topic_model.fit_transform(docs)
```

Could you try it again following the above steps?

**Comment by randomrdrand** [comment]
I ran the code mentioned on my data(so not the one you prepared) and I got this:

usr/local/lib/python3.7/dist-packages/distributed/config.py:20: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  defaults = yaml.load(f)
Downloading: 100%
748/748 [00:00<00:00, 17.6kB/s]
Downloading: 100%
4.00k/4.00k [00:00<00:00, 116kB/s]
Downloading: 100%
2.00/2.00 [00:00<00:00, 42.5B/s]
Downloading: 100%
688/688 [00:00<00:00, 12.8kB/s]
Downloading: 100%
122/122 [00:00<00:00, 2.50kB/s]
Downloading: 100%
456k/456k [00:00<00:00, 988kB/s]
Downloading: 100%
229/229 [00:00<00:00, 5.90kB/s]
Downloading: 100%
499M/499M [00:15<00:00, 34.2MB/s]
Downloading: 100%
52.0/52.0 [00:00<00:00, 1.31kB/s]
Downloading: 100%
52.0/52.0 [00:00<00:00, 1.07kB/s]
Downloading: 100%
239/239 [00:00<00:00, 7.04kB/s]
Downloading: 100%
1.36M/1.36M [00:00<00:00, 5.20MB/s]
Downloading: 100%
334/334 [00:00<00:00, 5.49kB/s]
Downloading: 100%
798k/798k [00:00<00:00, 3.52MB/s]
Downloading: 100%
190/190 [00:00<00:00, 4.02kB/s]
Batches: 100%
5082/5082 [38:43<00:00, 10.20it/s]
2021-09-28 14:46:58,499 - BERTopic - Transformed documents to Embeddings
/usr/local/lib/python3.7/dist-packages/numba/np/ufunc/parallel.py:363: NumbaWarning: The TBB threading layer requires TBB version 2019.5 or later i.e., TBB_INTERFACE_VERSION >= 11005. Found TBB_INTERFACE_VERSION = 9107. The TBB threading layer is disabled.
  warnings.warn(problem)
2021-09-28 14:51:32,337 - BERTopic - Reduced dimensionality with UMAP
2021-09-28 14:51:56,283 - BERTopic - Clustered UMAP embeddings with HDBSCAN
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-db8ce4b8c971> in <module>()
      5 vectorizer_model = CountVectorizer(ngram_range=(1, 3), stop_words="english", min_df=2)
      6 topic_model = BERTopic(embedding_model="roberta-base-nli-stsb-mean-tokens", vectorizer_model=vectorizer_model, calculate_probabilities=False, low_memory=True, verbose=True)
----> 7 topics, _ = topic_model.fit_transform(doc_list)

10 frames
/usr/local/lib/python3.7/dist-packages/pandas/core/groupby/groupby.py in <lambda>(x)
   1060         func = self._is_builtin_func(func)
   1061         if engine != "numba":
-> 1062             f = lambda x: func(x, *args, **kwargs)
   1063 
   1064         # iterate through "columns" ex exclusions to populate output dict

TypeError: sequence item 69141: expected str instance, float found

**Comment by MaartenGr** [comment]
Hmmm, then it seems that something is going on with your dataset. To be sure, can you run the following before passing it to BERTopic:

```python
doc_list = [str(doc) for doc in doc_list if len(str(doc)) > 0]
```

This forces the documents to be strings and removes any empty strings or nan values.

**Comment by randomrdrand** [comment]
Thank you very much that resolved the problem. I really appreciate your time and help, wish you a good day/night

**Comment by MaartenGr** [comment]
No problem, glad I could help!
