### ISSUE TITLE
`Transform` Throws an Error.

### ISSUE THREAD

**Issue by HAMZA310** [MaartenGr/BERTopic#260]
When I try to [transform a new document](https://maartengr.github.io/BERTopic/api/bertopic.html#bertopic._bertopic.BERTopic.transform), I see the following error:
```
AttributeError: 'NNDescent' object has no attribute '_visited'
```

I'm using [your Colab with `fetch_20newsgroups` dataset](https://colab.research.google.com/drive/1FieRA9fLdkQEGDIMYl0I3MCjSUKVF8C-?usp=sharing#scrollTo=FGGujopQGVOW&uniqifier=3)

I've tried passing it a `list` and `string`; Neither worked.

**Comment by MaartenGr** [comment]
Did you restart the notebook after pip installing BERTopic? I am not getting this issue when transforming a new document.

**Comment by HAMZA310** [comment]
Thank you @MaartenGr  for your fast response. 

_When I fit and transform the entire dataset, it works._
```
from bertopic import BERTopic
from sklearn.datasets import fetch_20newsgroups

docs = fetch_20newsgroups(subset='all')['data']
topic_model = BERTopic().fit(docs)
topics, probs = topic_model.transform(docs)
```


_When I try to fit a string or subset of the dataset (list) it fails._

`topic_model.transform(docs[0]) # Throws Error`
`topic_model.transform(docs[0:500]) # Throws Error`

```
unseen_doc = """
 '28 March 2021 Note: This table relates only to the provisions of this instrument as originally made. It will not be amended to deal with any later amendments of this instrument. (2) Any information in column 3 of the table is not part of this instrument. Information may be inserted in this column or information in it may be edited in any published version of this instrument.',
"""

topic_model.transform([unseen_doc]) # Throws Error
````

Thanks in advance!

**Comment by MaartenGr** [comment]
I think this would solve your issue:

```
!pip install bertopic
!pip install --upgrade numba
```
Do note that it is important to restart the notebook after having run the above code. Also, it seems that in your use case it would be sufficient to do a `fit_transform` once without the need to call `transform` if you already have all documents available.

**Comment by HAMZA310** [comment]
Thank you so much for your help. It worked.
