### ISSUE TITLE
AttributeError: 'BERTopic' object has no attribute 'get_representative_docs'

### ISSUE THREAD

**Issue by MitraMitraMitra** [MaartenGr/BERTopic#262]
Hi there!

I was looking in the documentation for a function that could help me with what I need and I found ```get_representative_topics```. The problem is, when I run it, I get the error
```python
AttributeError: 'BERTopic' object has no attribute 'get_representative_docs'
```
as if it wouldn't exist - which is weird, I saw it in the code and read the issues related to it.
My code is
```python
topic_model_descriptions = BERTopic(language="multilingual")
topics_descriptions, probs_descriptions = topic_model_descriptions.fit_transform(descriptions)
docs = topic_model_descriptions.get_representative_docs()
```
I tried adding ```python calculate_probabilities = True``` in ``` BERTopic(language="multilingual")``` and it didn't solve it.
Any idea what could be causing this error?
I use JupyterLab

**Comment by MaartenGr** [comment]
Which version of BERTopic are you using? Have you tried updating it to the newest version?

**Comment by MitraMitraMitra** [comment]
I use bertopic==0.6.0

**Comment by MaartenGr** [comment]
After upgrading BERTopic, did you restart the notebook?

**Comment by MitraMitraMitra** [comment]
I restarted the kernel and then I restarted the notebook... still nothing.

**Comment by MaartenGr** [comment]
Then I would advise creating a new environment and install BERTopic there. The newest version supports `get_representative_topics` which I just tested in a fresh google colab so I would expect that starting from a fresh env would solve the issue.

**Comment by MaartenGr** [comment]
Glad to hear that it worked out! Let me know if you have any other issues.
