### ISSUE TITLE
Extract information about "Super Clusters"

### ISSUE THREAD

**Issue by doubianimehdi** [MaartenGr/BERTopic#265]
Hi,

I have a rather unusual request , I have the following clustering : 
![image](https://user-images.githubusercontent.com/33954127/135584973-96600cda-020d-448a-be48-2dcd0d843eaa.png)

I was wondering if I can extract information about the "super" cluster that are located on 1.75 (X-Axis) and 2.25 (words , distance ...) so that for example researchers that are interested in zooming into the "super" cluster and have more detailed clustered and so until they reached the left part of the graphic .... I don't if that's clear ...

**Comment by MaartenGr** [comment]
That definitely seems like an interesting idea to explore a bit further. 

Let me start off by saying that the hierarchical nature of the clusters that you see above is a rather simplified version compared to the actual reduction of topics as performed by HDBSCAN or manually. This means that there needs to be a fixed definition of the hierarchical nature of the topics. 

However, in theory, this should be possible but is likely to require significant coding on my side. This unfortunately means that it could be a while before it is implemented. 

Awesome idea though and I'll keep this issue open for now!

**Comment by doubianimehdi** [comment]
@MaartenGr Wow ! Thank you so much ! That's gonna be valuable !!! Side note, have you heard of doc2map package ? https://towardsdatascience.com/doc2map-travel-your-documents-like-a-walk-on-google-map-1e8b827fdc04
https://github.com/louisgeisler/Doc2Map

I've tried it but it seems to have a bug that shows the same document on the map multiple times ... otherwise it's a really nice way to visualize the data !
If you could have a look into it and maybe use it in BERTopic in the future that would be great !

**Comment by doubianimehdi** [comment]
@MaartenGr Indeed for the first three visualization , you don't need additional package ! it works with matpotlib ! I think you should dig deeper into it because it's the best approach i've seen so far !

**Comment by MaartenGr** [comment]
> Indeed for the first three visualization , you don't need additional package ! it works with matpotlib ! 

Which visualizations are you referring to? From the link you posted, I see mostly interactive visualizations that cannot be created with something like matplotlib. 

> I think you should dig deeper into it because it's the best approach i've seen so far !

I'll do my best but unfortunately cannot make any promises.

**Comment by doubianimehdi** [comment]
![image](https://user-images.githubusercontent.com/33954127/175470459-54d9dd0f-7e2e-42de-a664-81b3fb8d1f62.png)
I'm talking about this one ! It doesn't require the markleaflet applet JS

**Comment by MaartenGr** [comment]
@doubianimehdi For the last few weeks, several visualization functions have been in the making that might support what you have been looking for. The main difficulty with these kinds of visualizations is the number of points that can be plotted on the 2D plane which is not easily supported by Plotly without additional dependencies. 

Having said that... I think you might be interested in some new visualizations to the pull request that I mentioned earlier, namely `.visualize_documents` and `.visualize_hierarchical_documents`. The former visualizes all documents on a 2D plane and the latter then creates a hierarchical format of it based on the hierarchy that was trained with BERTopic. 

### `.visualize_documents()`
![visualize_documents](https://user-images.githubusercontent.com/25746895/176181128-3e7f15f2-43e9-4aa7-acf9-0f691a602461.gif)

### `.visualize_hierarchical_documents()`

![visualize_hierarchical_documents](https://user-images.githubusercontent.com/25746895/176181002-7749126d-24cf-43a9-9ea4-c750415985c8.gif)

To perform these visualizations, I would highly advise reading through the preliminary documentation in the PR [here](https://github.com/MaartenGr/BERTopic/pull/578) as some optimization might be necessary to limit any RAM issues. In practice, sampling and not showing the document's content on hover typically help quite a bit. 

Hope this helps!

**Comment by doubianimehdi** [comment]
@MaartenGr I think it might be what i've been looking for ! Thank you so much !!! I'll tell you when it's finalised !
