### ISSUE TITLE
AttributeError: Can't get attribute '_rebuild_function' on <module 'numba.core.serialize'

### ISSUE THREAD

**Issue by MitraMitraMitra** [MaartenGr/BERTopic#266]
Hi!
     I'm trying to load a saved BERTopic model, but I get the following error:
```python
AttributeError: Can't get attribute '_rebuild_function' on <module 'numba.core.serialize' from '/home/ec2-user/anaconda3/envs/amazonei_pytorch_latest_p37/lib/python3.7/site-packages/numba/core/serialize.py'>
```
I've tried changing the environment and it didn't work...
While doing that, I noticed something unusual, but I wasn't sure if I should put it in a separate issue:
In one environment, installing bertopic ends with this warning:
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pytest-astropy 0.8.0 requires pytest-cov>=2.0, which is not installed.
pytest-astropy 0.8.0 requires pytest-filter-subpackage>=0.1, which is not installed.
tensorflow 1.15.5 requires numpy<1.19.0,>=1.16.0, but you have numpy 1.19.5 which is incompatible.
```
In the last line, it says ```tensorflow 1.15.5 requires numpy<1.19.0```, so I tried downgrading to numpy version 1.18.5 in another environment and I got this:
```
Looking in indexes: https://pypi.org/simple, https://pip.repos.neuron.amazonaws.com
Collecting numpy==1.18.5
  Downloading numpy-1.18.5-cp37-cp37m-manylinux1_x86_64.whl (20.1 MB)
     |████████████████████████████████| 20.1 MB 7.2 MB/s eta 0:00:01
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 1.20.3
    Uninstalling numpy-1.20.3:
      Successfully uninstalled numpy-1.20.3
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
bertopic 0.9.1 requires numpy>=1.20.0, but you have numpy 1.18.5 which is incompatible.
Successfully installed numpy-1.18.5
Note: you may need to restart the kernel to use updated packages.
```
It says ```bertopic 0.9.1 requires numpy>=1.20.0```. It sounds contradictory. I'm pretty sure there's an issue with my environment, but I thought I'd let you know.

**Comment by MaartenGr** [comment]
Yes, Tensorflow does not work well with the current Numpy version. Earlier versions of Numpy introduce quite a number of issues with respect to UMAP and HDBSCAN. I am not sure but I believe that newer versions of Tensorflow do support the correct Numpy versions. So updating Tensorflow might resolve your issue.

**Comment by MaartenGr** [comment]
Due to inactivity, I'll be closing this issue for now. However, if you are still experiencing this issue or want to discuss it further, please let me know and I'll reopen it.

**Comment by hp0404** [comment]
encountered this error as well with numpy == 1.20.0

**Comment by MaartenGr** [comment]
@hp0404 numpy < 1.20.0 is not supported due to a number of issues with UMAP, HDBSCAN, and pynndescent. Unfortunately, this also means that the specific tensorflow version as indicated above is also not compatible with BERTopic. Lowering the numpy requirement in BERTopic is therefore not possible. You are free to take the risk though by lowering the numpy version yourself after installing BERTopic.

**Comment by eyang9002** [comment]
encountered this error as well with numpy == 1.21.0

**Comment by pratik98** [comment]
@MitraMitraMitra did you manage to resolve the issue? i am facing the same issue.

**Comment by MitraMitraMitra** [comment]
@pratik98 yes. I was working in a AWS appliance, and the way I solved it is I tried multiple environments. It worked when I used a pytorch_36 environment.

**Comment by bipsen** [comment]
I am having this issue trying to use streamlit and bertopic in the same environment. At the moment, this is my requirements file:
```
bertopic
flair
streamlit
```
I also noticed [someone over in streamlit world](https://discuss.streamlit.io/t/error-after-long-time-using-the-app-attributeerror-module-numba-core-serialize/18031/2) is having a similar problem, who managed to fix it using numba==0.51.0. Pinning this in requirements.txt, however, I get problems with the regex library. I get the error when I try to load a model. I would love to hear if anyone manages to fix this problem.

**Comment by mrafayaleem** [comment]
I pinned numba to `numba==0.51.2` but I am getting the following error now:
```bash

File "/usr/local/lib/python3.8/site-packages/pandas/io/pickle.py", line 187, in read_pickle
 return pc.load(f, encoding=None)
File "/usr/local/lib/python3.8/site-packages/pandas/compat/pickle_compat.py", line 241, in load
 return up.load()
File "/usr/local/lib/python3.8/pickle.py", line 1212, in load
 dispatch[key[0]](self)
File "/usr/local/lib/python3.8/pickle.py", line 1705, in load_build
 setstate(state)
File "/usr/local/lib/python3.8/site-packages/pynndescent/pynndescent_.py", line 938, in __setstate__
 self._init_search_function()
File "/usr/local/lib/python3.8/site-packages/pynndescent/pynndescent_.py", line 1189, in _init_search_function
 parallel_search = self.parallel_batch_queries
AttributeError: 'NNDescent' object has no attribute 'parallel_batch_queries'
```

This is my requirements file:
```
umap-learn==0.5.2
numba==0.51.2
```

**Comment by MaartenGr** [comment]
Seeing as you are trying to load a trained BERTopic instance, did you make sure that the dependencies that BERTopic relies on are the same in the environment where you trained the model and the environment where you load the model?

**Comment by bipsen** [comment]
> Seeing as you are trying to load a trained BERTopic instance, did you make sure that the dependencies that BERTopic relies on are the same in the environment where you trained the model and the environment where you load the model?

That worked, thanks! I trained the model in the same environment, and everything is working fine. Can't believe I didn't think of that. Thank you so much!

My environment.yml, if anyone is interested:

```
name: streambert
channels:
  - microsoft
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - streamlit
  - bertopic
  - pandas
  - bokeh=2.4.1
  - pip
  - pip:
    - flair
```

**Comment by eyang9002** [comment]
Running into this issue recently (when my container was working fine with the same dependencies) for some reason now. Are there specific versions of dependencies we can use as a template for BERTopic 0.9.4?

I'm currently using:
numpy==1.21.1
numba==0.51.2
umap-learn==0.5.2
scipy
pandas>=1.1.5
sentence-transformers==2.1.0
sklearn
scikit-learn>=1.0.1
scipy
hdbscan>=0.8.27
bertopic==0.9.4

**Comment by recurrence** [comment]
I was able to load a saved BERTopic model that was exploding after installing numba==0.51.0

**Comment by yitelee** [comment]
To load numba-0.51.2 pickled UMAP transformer in 0.55.2 environment, you can inject removed codes (extracted from numba archive) like:

```
import numba

import marshal
import sys
from types import FunctionType, ModuleType
from importlib.util import MAGIC_NUMBER as bc_magic

def _dummy_closure(x):
    """
    A dummy function allowing us to build cell objects.
    """
    return lambda: x

def _rebuild_function(code_reduced, globals, name, cell_values, defaults):
    """
    Rebuild a function from its _reduce_function() results.
    """
    if cell_values:
        cells = tuple(_dummy_closure(v).__closure__[0] for v in cell_values)
    else:
        cells = ()
    code = _rebuild_code(*code_reduced)
    modname = globals['__name__']
    try:
        _rebuild_module(modname)
    except ImportError:
        # If the module can't be found, avoid passing it (it would produce
        # errors when lowering).
        del globals['__name__']
    return FunctionType(code, globals, name, defaults, cells)

def _rebuild_code(marshal_version, bytecode_magic, marshalled):
    """
    Rebuild a code object from its _reduce_code() results.
    """
    if marshal.version != marshal_version:
        raise RuntimeError("incompatible marshal version: "
                           "interpreter has %r, marshalled code has %r"
                           % (marshal.version, marshal_version))
    if bc_magic != bytecode_magic:
        raise RuntimeError("incompatible bytecode version")
    return marshal.loads(marshalled)

def _rebuild_module(name):
    if name is None:
        raise ImportError("cannot import None")
    __import__(name)
    return sys.modules[name]

numba.core.serialize._rebuild_function = _rebuild_function
numba.core.serialize._rebuild_module = _rebuild_module
numba.core.serialize._rebuild_code = _rebuild_code
```
