### ISSUE TITLE
Getting error while using transform

### ISSUE THREAD

**Issue by soumitra9** [MaartenGr/BERTopic#271]
AttributeError: 'BertEncoder' object has no attribute 'gradient_checkpointing'.

Error Trace:

/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
    887             result = self._slow_forward(*input, **kwargs)
    888         else:
--> 889             result = self.forward(*input, **kwargs)
    890         for hook in itertools.chain(
    891                 _global_forward_hooks.values(),

/usr/local/lib/python3.7/dist-packages/sentence_transformers/models/Transformer.py in forward(self, features)
     49             trans_features['token_type_ids'] = features['token_type_ids']
     50 
---> 51         output_states = self.auto_model(**trans_features, return_dict=False)
     52         output_tokens = output_states[0]
     53 

/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
    887             result = self._slow_forward(*input, **kwargs)
    888         else:
--> 889             result = self.forward(*input, **kwargs)
    890         for hook in itertools.chain(
    891                 _global_forward_hooks.values(),

/usr/local/lib/python3.7/dist-packages/transformers/models/bert/modeling_bert.py in forward(self, input_ids, attention_mask, token_type_ids, position_ids, head_mask, inputs_embeds, encoder_hidden_states, encoder_attention_mask, past_key_values, use_cache, output_attentions, output_hidden_states, return_dict)
   1003             output_attentions=output_attentions,
   1004             output_hidden_states=output_hidden_states,
-> 1005             return_dict=return_dict,
   1006         )
   1007         sequence_output = encoder_outputs[0]

/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
    887             result = self._slow_forward(*input, **kwargs)
    888         else:
--> 889             result = self.forward(*input, **kwargs)
    890         for hook in itertools.chain(
    891                 _global_forward_hooks.values(),

/usr/local/lib/python3.7/dist-packages/transformers/models/bert/modeling_bert.py in forward(self, hidden_states, attention_mask, head_mask, encoder_hidden_states, encoder_attention_mask, past_key_values, use_cache, output_attentions, output_hidden_states, return_dict)
    557             past_key_value = past_key_values[i] if past_key_values is not None else None
    558 
--> 559             if self.gradient_checkpointing and self.training:
    560 
    561                 if use_cache:

/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py in __getattr__(self, name)
    946                 return modules[name]
    947         raise AttributeError("'{}' object has no attribute '{}'".format(
--> 948             type(self).__name__, name))
    949 
    950     def __setattr__(self, name: str, value: Union[Tensor, 'Module']) -> None:

AttributeError: 'BertEncoder' object has no attribute 'gradient_checkpointing'

**Comment by MaartenGr** [comment]
Could you share the code you have used to initialized BERTopic and the versions of BERTopic and sentence-transformer? It seems that something is going wrong with the embedding model.

**Comment by MaartenGr** [comment]
Issues with loading a trained BERTopic might stem from different versions in the environment. Did you update any package in between? If this issue persists I would advise re-training the model and making sure that it is used in the same environment.

**Comment by MaartenGr** [comment]
Since the issue has been without activity for some time, I am closing this for now. However, if you are running into this issue still or want to discuss it further, please let me know! I'll reopen it and see if we can fix the issue.
