### ISSUE TITLE
Sorting topic ids creating visual output

### ISSUE THREAD

**Issue by yusufcakmakk** [MaartenGr/BERTopic#274]
Hi,

When I try to use visualization option which is visualize_barchart, model creates an output with outliers. 
So I have checked [here](https://github.com/MaartenGr/BERTopic/blob/master/bertopic/plotting/_barchart.py#L49) and model assumes -1 is always most frequency in list. 
However my model output is like this:
![image](https://user-images.githubusercontent.com/3153146/136532930-7b2cc8db-beec-436a-8e78-773d91558b6a.png)
I am giving topic list manually to overcome this but could you fix this on new releases? Thanks! 😊

**Comment by MaartenGr** [comment]
Since the issue has been without activity for some time, I am closing this for now. However, if you are running into this issue still or want to discuss it further, please let me know! I'll reopen it and see if we can fix the issue.
