### ISSUE TITLE
Train and Predict BERTopic

### ISSUE THREAD

**Issue by mjavedgohar** [MaartenGr/BERTopic#278]
Hi @MaartenGr ,

As I understand about BERTopic; fit_transform() is to train model while transform() is for prediction. Am I right??
what is the best method to train the model for data from different sources e.g. twitter, reddit, facebook comments etc. I want to train the model once and use it for various datasets?
should I have to divide data in sentences because some sources has very large comments (paragraphs) e.g. reddit or news articles?

Thanks

**Comment by MaartenGr** [comment]
You are correct. You can use `fit_transform()` to train the model. The `transform()` function is indeed used for prediction. Do note that `fit_transform()` not only trains the model but also predicts the data on which it was trained. 

In practice, I would try to combine as many sources as possible before training the model. If you have various datasets, then you can simply combine them and train over all of the models. However, if there is a specific reason for training it on only a single dataset and predict for all others, then that is also possible. I can imagine it could be computationally expensive to train on all datasets or that you only want the topics from a single source represented. In those cases, it should be fine to train it on a single dataset although training on all of them is preferred. 

This depends on the content of the large paragraphs. If you feel like or assume, that those paragraphs may contain multiple topics then I would advise splitting them up into sentences. You can use Spacy to split them up into sentences. However, if you think that there is only a single topic in the large paragraph then there is no need to split them up into sentences. 

If possible, I would try training it on the data without splitting it up into sentences and see if they make sense. If not, then a sentence splitter would be your next step.

**Comment by MaartenGr** [comment]
Yes! You can train the model and save it for other datasets just like other ML models. Do note that it is important that the versions of packages stay the same when switching between environments. Most issues related to model loading can be solved by looking at the environment. 

This is actually quite a complex subject. Although there are methods that you can employ, such as `c_v` for evaluation they suffer from a number of issues. Topic modeling creates a highly subjective output in a way and evaluation that output is quite difficult. Do you focus on the topic coherence, its clustering capabilities, predictive power, or anything else? Those questions, in part, are what makes it difficult. 

So while I am definitely not against evaluation metrics. I do think it is important to realize that they by no means represent a ground truth and can be misleading in some cases. 

You can look towards [Gensim](https://radimrehurek.com/gensim/models/coherencemodel.html) or [Octis](https://github.com/MIND-Lab/OCTIS) for evaluation metrics/functions/libraries.

**Comment by MaartenGr** [comment]
@mjavedgohar A new version of BERTopic ([v0.9.3](https://maartengr.github.io/BERTopic/changelog.html#version-093)) was released that should fix this issue and some others that should be helpful. You can install that version through `pip install --upgrade bertopic`. If you have any questions regarding this issue, release, or some other issue, please let me know!

**Comment by MaartenGr** [comment]
Yes, it should be okay to train on your training docs and to predict them on only new docs.

**Comment by mjavedgohar** [comment]
Thanks @MaartenGr  It worked
Just another thing to discuss. I am getting the following error when number of topics are very low. Can visualize the topics >=2

 fig = topic_model.visualize_topics()
  File "/home/muhammad.javed/.local/lib/python3.7/site-packages/bertopic/_bertopic.py", line 909, in visualize_topics
    height=height)
  File "/home/muhammad.javed/.local/lib/python3.7/site-packages/bertopic/plotting/_topics.py", line 63, in visualize_topics
    embeddings = UMAP(n_neighbors=2, n_components=2, metric='hellinger').fit_transform(embeddings)
  File "/home/muhammad.javed/.local/lib/python3.7/site-packages/umap/umap_.py", line 2634, in fit_transform
    self.fit(X, y)
  File "/home/muhammad.javed/.local/lib/python3.7/site-packages/umap/umap_.py", line 2554, in fit
    self._raw_data[index], n_epochs, init, random_state,  # JH why raw data?
  File "/home/muhammad.javed/.local/lib/python3.7/site-packages/umap/umap_.py", line 2601, in _fit_embed_data
    self.verbose,
  File "/home/muhammad.javed/.local/lib/python3.7/site-packages/umap/umap_.py", line 1060, in simplicial_set_embedding
    metric_kwds=metric_kwds,
  File "/home/muhammad.javed/.local/lib/python3.7/site-packages/umap/spectral.py", line 334, in spectral_layout
    maxiter=graph.shape[0] * 5,
  File "/home/muhammad.javed/.local/lib/python3.7/site-packages/scipy/sparse/linalg/eigen/arpack/arpack.py", line 1598, in eigsh
    raise TypeError("Cannot use scipy.linalg.eigh for sparse A with "
TypeError: Cannot use scipy.linalg.eigh for sparse A with k >= N. Use scipy.linalg.eigh(A.toarray()) or reduce k.

**Comment by MaartenGr** [comment]
That is more an issue with the number of topics than necessarily the method. Typically, BERTopic would result in tens or hundreds of topics. Any less and you likely have too little data to work with, or you have set the `min_topic_size` to high. I would advise trying to increase the number of topics as that would most likely be the best representation of the data.

**Comment by mjavedgohar** [comment]
Thanks @MaartenGr,

If I run the following code on my PC its works fine but on HPC (server) I am getting Error with same data. can you please help me for this.

timestamps = review_data.timestamp.to_list()
topics_over_time = topic_model.topics_over_time(docs, topics, timestamps, nr_bins=10)
topic_over_time=topic_model.visualize_topics_over_time(topics_over_time, top_n_topics=100)
topic_over_time.write_html(filename.split('.')[0]+"_customize3_Model_topicovertime.html")

**Error**

 topics_over_time = topic_model.topics_over_time(docs, topics, timestamps, nr_bins=10)

  File "/home/muhammad.javed/.local/lib/python3.7/site-packages/bertopic/_bertopic.py", line 457, in topics_over_time
    format=datetime_format)
  File "/home/muhammad.javed/.local/lib/python3.7/site-packages/pandas/core/tools/datetimes.py", line 887, in to_datetime
    values = convert_listlike(arg._values, format)
  File "/home/muhammad.javed/.local/lib/python3.7/site-packages/pandas/core/tools/datetimes.py", line 408, in _convert_listlike_datetimes
    allow_object=True,
  File "/home/muhammad.javed/.local/lib/python3.7/site-packages/pandas/core/arrays/datetimes.py", line 2193, in objects_to_datetime64ns
    raise err
  File "/home/muhammad.javed/.local/lib/python3.7/site-packages/pandas/core/arrays/datetimes.py", line 2182, in objects_to_datetime64ns
    allow_mixed=allow_mixed,
  File "pandas/_libs/tslib.pyx", line 379, in pandas._libs.tslib.array_to_datetime
  File "pandas/_libs/tslib.pyx", line 611, in pandas._libs.tslib.array_to_datetime
  File "pandas/_libs/tslib.pyx", line 749, in pandas._libs.tslib._array_to_datetime_object
  File "pandas/_libs/tslib.pyx", line 740, in pandas._libs.tslib._array_to_datetime_object
  File "pandas/_libs/tslibs/parsing.pyx", line 257, in pandas._libs.tslibs.parsing.parse_datetime_string
  File "/home/muhammad.javed/.local/lib/python3.7/site-packages/dateutil/parser/_parser.py", line 1368, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/home/muhammad.javed/.local/lib/python3.7/site-packages/dateutil/parser/_parser.py", line 643, in parse
    raise ParserError("Unknown string format: %s", timestr)
dateutil.parser._parser.ParserError: Unknown string format: timestamp

**Comment by MaartenGr** [comment]
If you run into issues when switching environments it is most likely a version control issue. Did you make sure to use the same versions of packages between environments? Also, is the code exactly the same between environments?

**Comment by mjavedgohar** [comment]
Hi @MaartenGr ,

I am tring to use the Guided Topic Modeling using the following code. Its working fine in Colab notebooks but getting error on my local machine. I am using BERTopic 0.12.0. Can you please help me for this??? Thanks

**Code:**

topic_model = BERTopic(language="english", verbose=True, seed_topic_list=seed_topic_list) 
topics, probs = topic_model.fit_transform(docs)

**Error:**
  topics, probs = topic_model.fit_transform(docs)
  File "...\Local\Programs\Python\Python38\lib\site-packages\bertopic\_bertopic.py", line 344, in fit_transform
    y, embeddings = self._guided_topic_modeling(embeddings)
  File "...\Local\Programs\Python\Python38\lib\site-packages\bertopic\_bertopic.py", line 2376, in _guided_topic_modeling
    embeddings[indices] = np.average([embeddings[indices], seed_topic_embeddings[seed_topic]], weights=[3, 1])
  File "<__array_function__ internals>", line 5, in average
  File "..\Local\Programs\Python\Python38\lib\site-packages\numpy\lib\function_base.py", line 407, in average
    scl = wgt.sum(axis=axis, dtype=result_dtype)
  File "..\Local\Programs\Python\Python38\lib\site-packages\numpy\core\_methods.py", line 47, in _sum
    return umr_sum(a, axis, dtype, out, keepdims, initial, where)
TypeError: No loop matching the specified signature and casting was found for ufunc add

**Comment by elenacandellone** [comment]
Hi @MaartenGr,

I have two datasets (train and test), and I would like to predict the topics for both, while fitting only the first one. This is my code:

```
eps = 1e-6
min_sample = 1

embedding_model = SentenceTransformer('sentence-transformers/paraphrase-multilingual-mpnet-base-v2')


umap_model = UMAP(n_components=150, n_neighbors=50, random_state=42, metric="cosine")


hdbscan_model_arccos = HDBSCAN(
                            min_samples = min_sample,
                            min_cluster_size = 50, 
                            cluster_selection_epsilon = eps,
                            metric='cosine', algorithm = 'generic', cluster_selection_method = 'eom', 
                            prediction_data = True, core_dist_n_jobs=1)


vectorizer_model = CountVectorizer(vocabulary=vocab, 
                                max_features=10000,
                                stop_words = stopwords)


ctfidf_model = ClassTfidfTransformer(reduce_frequent_words=True)


representation_model = MaximalMarginalRelevance(diversity=0.2)

topic_model= BERTopic(
        low_memory =True,
        language = 'spanish',
        embedding_model=embedding_model,
        umap_model=umap_model,
        hdbscan_model=hdbscan_model_arccos,
        vectorizer_model=vectorizer_model,
        ctfidf_model=ctfidf_model, 
        representation_model=representation_model,
        top_n_words = 20,
        n_gram_range = (1,3)
)

topics_train, probabilities_train = topic_model.fit_transform(docs_train, embeddings_train)

predicted_topics, predicted_probs = topic_model.transform(docs_test)
```

The problem is that, while doing the last step, I encountered the following error:
attribute error: no prediction data was generated 


I guess the problem is related to the fact that the function approximate_predict of hdbscan is unaware of the parameter cluster_selection_epsilon.
Would you happen to have any idea on how to solve this issue?

Thanks in advance!

**Comment by MaartenGr** [comment]
@elenacandellone Hmmm, it indeed seems to be related to HDBSCAN. If it is a bug with HDBSCAN that cannot be solved within that package, you can instead save the topic model as `safetensors` and then load it in. Saving with `safetensors` removes the underlying HDBSCAN and UMAP and does inference through the embeddings only. This should prevent the issue you are having.

**Comment by ChristinaBarz** [comment]
Hi :) I just trained a model and am trying to proceed with dynamic topic modeling. I tried everything I could think of but keep receiving this: ValueError: All arrays must be of the same length. However, my docs and timestamps seem to have the same lenghts.. I am thankful for any help, best!!


My first try: 
final_df['UTC Date'] = pd.to_datetime(final_df['UTC Date'], format="%Y-%m-%d %H:%M:%S")

docs = final_df['Tweet'].tolist()  
timestamps = final_df['UTC Date'].tolist()

topics_over_time = topic_model.topics_over_time(docs, timestamps, datetime_format="%Y-%m-%d %H:%M:%S", nr_bins=20)




My last try in which I transformed the UTC Date to timestamp format looked like this: 
final_df['UTC Date'] = pd.to_datetime(final_df['UTC Date'], errors='coerce', format="%Y-%m-%d %H:%M:%S")

final_df = final_df.dropna(subset=['UTC Date'])

timestamps = final_df['UTC Date'].astype(int) // 10**9

docs = final_df['Tweet'].tolist()

print("Initial length of docs:", len(docs))
print("Initial length of timestamps:", len(timestamps))

assert len(docs) == len(timestamps), "The lengths of docs and timestamps do not match!"

topics_over_time = topic_model.topics_over_time(docs, timestamps, nr_bins=20)

Output: 
Initial length of docs: 53291
Initial length of timestamps: 53291
... ValueError: All arrays must be of the same length.




Also, here is the code from the trained model: 
docs = final_df['Tweet'].tolist()

embedding_model = SentenceTransformer("all-MiniLM-L6-v2")
embeddings = embedding_model.encode(docs, show_progress_bar=True)

os.environ["OMP_NUM_THREADS"] = "1"
os.environ["OPENBLAS_NUM_THREADS"] = "1"
os.environ["MKL_NUM_THREADS"] = "1"
os.environ["VECLIB_MAXIMUM_THREADS"] = "1"
os.environ["NUMEXPR_NUM_THREADS"] = "1"

umap_model = UMAP(random_state=777, n_neighbors=50)

hdbscan_model = HDBSCAN(min_cluster_size=100, metric='euclidean',
                        cluster_selection_method='eom', prediction_data=True, min_samples=3)

ctfidf_model = ClassTfidfTransformer(reduce_frequent_words=True)

vectorizer_model = CountVectorizer(stop_words="english", min_df=2, ngram_range=(1, 2))

keybert_model = KeyBERTInspired()
pos_model = PartOfSpeech("en_core_web_sm")
mmr_model = MaximalMarginalRelevance(diversity=0.3)

representation_model = {
    "KeyBERT": keybert_model,
    "MMR": mmr_model,
    "POS": pos_model
}

topic_model = BERTopic(umap_model=umap_model, hdbscan_model=hdbscan_model, ctfidf_model=ctfidf_model, embedding_model=embedding_model, vectorizer_model=vectorizer_model, representation_model=representation_model)

with parallel_backend('loky'):
    topics, probs = topic_model.fit_transform(docs)

**Comment by MaartenGr** [comment]
@ChristinaBarz Which version of BERTopic are you using? Also, can you format your code in markdown using those ``` tags? It is quite difficult to read.

**Comment by ChristinaBarz** [comment]
Hi @MaartenGr! Thanks for trying to help me out here :) I'm using version 0.16.2 and here is my code again (sorry about that):

My first try:
```
final_df['UTC Date'] = pd.to_datetime(final_df['UTC Date'], format="%Y-%m-%d %H:%M:%S")

docs = final_df['Tweet'].tolist()
timestamps = final_df['UTC Date'].tolist()

topics_over_time = topic_model.topics_over_time(docs, timestamps, datetime_format="%Y-%m-%d %H:%M:%S", nr_bins=20)
```

My last try, in which I transformed the UTC Date to timestamp format, looked like this:
```
final_df['UTC Date'] = pd.to_datetime(final_df['UTC Date'], errors='coerce', format="%Y-%m-%d %H:%M:%S")

final_df = final_df.dropna(subset=['UTC Date'])

timestamps = final_df['UTC Date'].astype(int) // 10**9

docs = final_df['Tweet'].tolist()

print("Initial length of docs:", len(docs))
print("Initial length of timestamps:", len(timestamps))

assert len(docs) == len(timestamps), "The lengths of docs and timestamps do not match!"

topics_over_time = topic_model.topics_over_time(docs, timestamps, nr_bins=20)
```

Output:
Initial length of docs: 53291
Initial length of timestamps: 53291
... ValueError: All arrays must be of the same length.

Also, here is the code from the trained model:
```
docs = final_df['Tweet'].tolist()

embedding_model = SentenceTransformer("all-MiniLM-L6-v2")
embeddings = embedding_model.encode(docs, show_progress_bar=True)

os.environ["OMP_NUM_THREADS"] = "1"
os.environ["OPENBLAS_NUM_THREADS"] = "1"
os.environ["MKL_NUM_THREADS"] = "1"
os.environ["VECLIB_MAXIMUM_THREADS"] = "1"
os.environ["NUMEXPR_NUM_THREADS"] = "1"

umap_model = UMAP(random_state=777, n_neighbors=50)

hdbscan_model = HDBSCAN(min_cluster_size=100, metric='euclidean',
cluster_selection_method='eom', prediction_data=True, min_samples=3)

ctfidf_model = ClassTfidfTransformer(reduce_frequent_words=True)

vectorizer_model = CountVectorizer(stop_words="english", min_df=2, ngram_range=(1, 2))

keybert_model = KeyBERTInspired()
pos_model = PartOfSpeech("en_core_web_sm")
mmr_model = MaximalMarginalRelevance(diversity=0.3)

representation_model = {
"KeyBERT": keybert_model,
"MMR": mmr_model,
"POS": pos_model
}

topic_model = BERTopic(umap_model=umap_model, hdbscan_model=hdbscan_model, ctfidf_model=ctfidf_model, embedding_model=embedding_model, vectorizer_model=vectorizer_model, representation_model=representation_model)

with parallel_backend('loky'):
topics, probs = topic_model.fit_transform(docs)
```

**Comment by MaartenGr** [comment]
@ChristinaBarz It is not clear from your code but are the `docs` you used to train the model (`.fit_transform(docs)`) the same documents as you using for dynamic topic modeling (`.topics_over_time(docs)`). They need to be the same documents or at the very least, the same size.

**Comment by ChristinaBarz** [comment]
@MaartenGr yes they are exactly the same!

**Comment by MaartenGr** [comment]
@ChristinaBarz Hmmm, then I'm not sure. Is the code you shared the complete code? You didn't load and save the model in between?

**Comment by ChristinaBarz** [comment]
@MaartenGr thank you for your help :) I found the problem! Unfortunately, a few rows had a divergent date format..
