### ISSUE TITLE
Not being able to import bertopic in a Kaggle notebook

### ISSUE THREAD

**Issue by akshaydevml** [MaartenGr/BERTopic#279]
Error while trying to import Bertopic in a notebook. Throws 'numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject' error. Trying with different numpy versions also didn't help

**Comment by bitmman** [comment]
> This error typically happens when you use an incompatible version of numpy. This means that the active numpy version in the notebook is < 1.20.0. If you update numpy to > 1.20.0 the issue should disappear. However, if you are still getting that error, I would advise simply restarting the notebook. When a package is in use in the current environment and you update it in the same active environment, the old one will be used until you restart the notebook.
> 
> I haven't tried that in a Kaggle notebook but the same issue can be found in Jupyter notebooks and Google Colab. So, simply update numpy and restart the notebook should solve the issue.

I have run the [example notebook](https://www.kaggle.com/maartengr/topic-modeling-arxiv-abstract-with-bertopic) on kaggle and it reports the same error. I have also tried to upgrade numpy > 1.20.0 version, but failed in kaggle.

**Comment by MaartenGr** [comment]
@bitmman Did you make sure to restart the notebook as follows after installing BERTopic?

![image](https://user-images.githubusercontent.com/25746895/139523329-288028d7-95ce-4d8a-b25e-51f04ad608db.png)

I just tried it out and after running `pip install bertopic`, I restart the notebook, and then can correctly import and run BERTopic without any issues.

**Comment by bitmman** [comment]
> @bitmman Did you make sure to restart the notebook as follows after installing BERTopic?
> 
> ![image](https://user-images.githubusercontent.com/25746895/139523329-288028d7-95ce-4d8a-b25e-51f04ad608db.png)
> 
> I just tried it out and after running `pip install bertopic`, I restart the notebook, and then can correctly import and run BERTopic without any issues.

Hi MaaartenGr,

Thanks. it works fine after restart the notebook.
