### ISSUE TITLE
More progressbars

### ISSUE THREAD

**Issue by Karol-G** [MaartenGr/BERTopic#28]
Hi,

I see that there is an option for a tqdm progressbar in `_extract_embeddings` but no actual access to it. As the dataset I am working on is quite big I would like to have an estimate how long things are going to take.
Would it be possible to enable the progress bar from `fit_transform`?
I don't know if it is possible, but can you add progress bars for the other steps as well?

Best
Karol

**Comment by MaartenGr** [comment]
Hi Karol,

This was removed in v0.4 as there a few steps that do not have a tqdm process bar accessible. There are roughly four steps in BERTopic:
1. Extract embeddings (tqdm possible)
2. Create clusters with HDBSCAN+UMAP (tqdm not possible)
3. Create c-TF-IDF matrix (tqdm not possible)
4. Improve coherence words (tqdm possible)

So it is possible to construct tqdm bar for steps 1 and 4 but unfortunately not for steps 2 and 3. Therefore, it is quite difficult to get an estimate of the entire training duration. 

Having said that, I might add the progress bars for steps 1 and 4 in a future version.

**Comment by HCSS-StratBase** [comment]
Is this still on the list? It would be really useful for large corpora...

**Comment by MaartenGr** [comment]
I believe this is implemented in BERTopic if you set `verbose=True` when instantiating the model. It might be different for certain models but it should work for the default SBERT models.
