### ISSUE TITLE
Topics do not match with the results of probability distributions when using transform()

### ISSUE THREAD

**Issue by DonuBogdan** [MaartenGr/BERTopic#282]
For some documents, topics obtained with transform() are different from the topics that I get from the probability distributions obtained with transform().

Check example below.

![image](https://user-images.githubusercontent.com/37671228/136936888-301c44a7-3dac-4d3a-a51b-7de4cda58a6a.png)

Thank you !

**Comment by MaartenGr** [comment]
I just tried the following with BERTopic v0.9.2 and the probabilities mostly match:

```python
from bertopic import BERTopic
from sklearn.datasets import fetch_20newsgroups
 
docs = fetch_20newsgroups(subset='all',  remove=('headers', 'footers', 'quotes'))['data']
topic_model = BERTopic(embedding_model="paraphrase-MiniLM-L3-v2", calculate_probabilities=True, nr_topics="auto")
topics, probs = topic_model.fit_transform(docs)
```

Could you try running it from a fresh environment with a clean BERTopic install? When updating packages within an environment sometimes you need to restart it. Running from a fresh environment would make sure none of that has happened.

**Comment by MaartenGr** [comment]
Ah, I see. It seems that although the `fit_transform` function now works properly when reducing and mapping topics and probabilities, the same cannot be said for `transform`. Perhaps a bug was introduced in the newest version. Let me check quickly and I'll get back to you!

**Comment by nilsblessing** [comment]
For me, a similar issue shows up when predicting the topic ID via .transform() with the latest version. Qualitatively evaluated, the predicted topics do not match the texts.

In my case the problem was solved by going back to version 0.9.1. (Maybe that helps.)


Best
Nils

**Comment by MaartenGr** [comment]
@DonuBogdan @nilsblessing A new version of BERTopic ([v0.9.3](https://maartengr.github.io/BERTopic/changelog.html#version-093)) was released that should fix this issue and some others that should be helpful. You can install that version through `pip install --upgrade bertopic`. If you have any questions regarding this issue, release or some other issue, please let me know!

**Comment by juli-sch** [comment]
Hello Maarten, 

when I use fit_transform(), the assigned topic in topics does not match the probability distributions either. When I run the steps of BERTopic one after the other (embeddings, umap, hdbscan) I have the same issues, so I don't think it's your implementation. 

![image](https://user-images.githubusercontent.com/75275925/157110005-af61d5fb-2fb0-475a-8036-3537bd38cf0f.png)

> Second, some instability may appear using the probabilities supplied by HDBSCAN. Although it happens quite infrequently, in same cases this may happen.

 Is this the instability you were talking about? Are there ways (e.g. parameter settings) to prevent these instabilities?

Can you tell me which is more reliable, the values from the list of probability distributions or the individual value of the assigned topic?

As always, thank you very much in advance for your time and help.

**Comment by MaartenGr** [comment]
@juli-sch Yes, the probabilities that you can extract from HDBSCAN, unfortunately, do not always perfectly represent the clusters they have formed. At least, to my understanding. I do not believe there is currently a fix for this as the issues I have seen on the repo seem quite old. 

Personally, I would go with the individual value of the assigned topic as that does not require additional computations and is likely to be more accurate. Do note though, that on the whole, you can still use the probability distributions if you are, for example, trying to explore which topics are frequently found together.

**Comment by LuccaMartins** [comment]
Hi, 

I've also faced this issue, and decided to use only the individual value of the assigned topic, as you mentioned. 

But I would like to highlight that there is a relation between the assigned topic and the probs' indexes. In the image, the column 'topic' contains the assigned topics, and in the other column I'm showing the index of the highest probability, followed by the probability itself. As we can see, the relation between the topic and the probs' indexes is:

0 -> 0
1 -> 2
2 -> 3
3 -> 1 (doesn't appear in this image)

Well, I believe hat these correspondences can be useful for insights regarding how to fix this problem. I hope it helps somehow.

![image](https://user-images.githubusercontent.com/58174925/212076213-3bfa2efd-2c7d-45e8-a403-9a0262921a2b.png)

Btw, thanks for this amazing library!
