### ISSUE TITLE
Searched topics not found in text

### ISSUE THREAD

**Issue by ginward** [MaartenGr/BERTopic#289]
@MaartenGr 

I am trying to search topics by keyword, but it seems that the searched topics have no corresponding keyword in the original document. Any idea why? 

For example, my model is loaded from a file `bert_model_graham`.

```
model = BERTopic.load("bert_model_graham")

model.embedding_model = select_backend(embeddings_model)

model._create_topic_vectors()
```

Next, I get the topic predictions from the BERTopic model for each document. 

```
topics = model._map_predictions(model.hdbscan_model.labels_)

probs = model.hdbscan_model.probabilities_
```

Then I assign the topic prediction to the original DataFrame for each document:

```
df = pd.read_csv("data.csv")

df['topics'] = topics

df['probs'] = probs
```

Finally, I search the topic by the keyword creativity, and found the topic id `956`, which correspond to the following TFIDF keywords.:

```

innovation_topics, innovation_similarity = model.find_topics("creativity", top_n=5)

model.get_topic(innovation_topics[0])

[('adobe', 0.025211062959638018),
 ('creative', 0.023439029504272773),
 ('creative cloud', 0.019700119820127267),
 ('acrobat', 0.011074831493140204),
 ('docusign', 0.007779916926076105),
 ('cloud', 0.006265223149380872),
 ('creative suite', 0.006216439653006454),
 ('document cloud', 0.0058058917235438556),
 ('document', 0.005597536103990317),
 ('esignature', 0.0051324488963327515)]
```

However, when I pull up the documents with topic assignment `956`, I cannot find the keyword `esignature` in any of the texts. 

```
test=df[df['topics']==innovation_topics[0]]

test[test['componenttext'].str.lower().str.contains('esignature')]
```

Empty data frame. 

This is just weird.

**Comment by MaartenGr** [comment]
Yes, documents from the same topics are concatenated. However, if you concatenate two documents "e" and "signature", that results in the documents "esignature". This means that "esignature" cannot be found in either "e" or "signature".

**Comment by ginward** [comment]
@MaartenGr I don't think it is the case. Because I cannot find any of the following keywords from the documents: 

```
[('adobe', 0.025211062959638018),
 ('creative', 0.023439029504272773),
 ('creative cloud', 0.019700119820127267),
 ('acrobat', 0.011074831493140204),
 ('docusign', 0.007779916926076105),
 ('cloud', 0.006265223149380872),
 ('creative suite', 0.006216439653006454),
 ('document cloud', 0.0058058917235438556),
 ('document', 0.005597536103990317),
 ('esignature', 0.0051324488963327515)]
```

I think there must be some document ordering issue somewhere?

**Comment by MaartenGr** [comment]
Hmmmm, just to be sure. Which version of BERTopic are you using? Also, if you look at the documents in topic `956`, do you agree with the topic representation it has created? If not, then it might be an issue with the topic assignment.
