### ISSUE TITLE
search topic not working anymore in 0.9.2

### ISSUE THREAD

**Issue by doubianimehdi** [MaartenGr/BERTopic#290]
Hi,

This piece of code used to work (no modification of the data or the data structure done) before 0.9.2
import pprint
pp = pprint.PrettyPrinter(indent=3)
similar_topics, similarity = topic_model.find_topics("polymer", top_n=5)
pp.pprint(topic_model.get_topic(similar_topics))
pp.pprint(similarity)

Now I have this error : 
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_11564/873401312.py in <module>
      2 pp = pprint.PrettyPrinter(indent=3)
      3 similar_topics, similarity = topic_model.find_topics("polymer", top_n=5)
----> 4 pp.pprint(topic_model.get_topic(similar_topics))
      5 pp.pprint(similarity)

c:\users\doub2420\appdata\local\programs\python\python39\lib\site-packages\bertopic\_bertopic.py in get_topic(self, topic)
    720         """
    721         check_is_fitted(self)
--> 722         if topic in self.topics:
    723             return self.topics[topic]
    724         else:

TypeError: unhashable type: 'list'

**Comment by MaartenGr** [comment]
I am not sure in which version this previously worked but it should not have. Use `get_topics` instead of `get_topic` and the issue should be solved.
