### ISSUE TITLE
How to predict the topic of new document without using topic_model.fit_transform() before

### ISSUE THREAD

**Issue by hcanuzuner** [MaartenGr/BERTopic#293]
Hi,

I have a 50000 documents dataset. I want to train a model and predict documents. When I use custom model and feed the model with the dataset. It works perfectly.

``topic_model = BERTopic(language="english", calculate_probabilities=True, verbose=True, nr_topics="auto", low_memory=True)

topics, probs = topic_model.fit_transform(documents)

topic_model.transform([documents[0]])
``

However, what if I don't want to feed BERTopic with my dataset and try to predict them without using topic_model.fit_transform(). Can I do that ?

For example, I don't have any dataset but a document and I want to learn the topic. How can I do that ? 
``
sentence_model = SentenceTransformer("all-MiniLM-L6-v2")
topic_model = BERTopic(embedding_model=sentence_model, language="english", calculate_probabilities=True, verbose=True, nr_topics="auto", low_memory=True)

topic_model.transform([documents[0]])
``

ERROR : This BERTopic instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.

**Comment by MaartenGr** [comment]
Since the issue has been without activity for some time, I am closing this for now. However, if you are running into this issue still or want to discuss it further, please let me know! I'll reopen it and see if we can fix the issue.
