### ISSUE TITLE
BERTopic can't work with new versions of `pyyaml` in Colab

### ISSUE THREAD

**Issue by KickItLikeShika** [MaartenGr/BERTopic#294]
Hey, After installing BERTopic in colab, I was not able to import it, I was getting this
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-6-1d2f5f7c9d67> in <module>()
----> 1 from bertopic import BERTopic

13 frames
/usr/local/lib/python3.7/dist-packages/distributed/config.py in <module>()
     18 
     19 with open(fn) as f:
---> 20     defaults = yaml.load(f)
     21 
     22 dask.config.update_defaults(defaults)

TypeError: load() missing 1 required positional argument: 'Loader'
```
After that I downgraded `pyyaml` to `5.4.1` and that made it work, I need to know if I can make it work without trying to downgrade `pyyaml`?
Thanks in advance!

**Comment by MaartenGr** [comment]
Thank you for posting your solution. This is a [known issue](https://github.com/MaartenGr/BERTopic/issues/288) for which you can find a fix in [this pull request](https://github.com/MaartenGr/BERTopic/pull/284). However, it seems that pyyaml 6.0 breaks quite a bit of code so a downgrade is required.
