### ISSUE TITLE
Multilabel Support

### ISSUE THREAD

**Issue by eyang9002** [MaartenGr/BERTopic#295]
Given the hierarchical nature of topics, one can reason that it's very possible that any given document can belong to multiple topics. Are there any plans to support multi-label classification? Instead of taking argmax of the probabilities (I know its more sophisticated than that with HDBSCAN), but setting probability thresholds per topic, allowing for multi-label classification?

**Comment by MaartenGr** [comment]
As of right now, there are no plans to allow for multi-label classification. However, as you said, by setting a threshold we can try to shoot for multi-label classification. Fortunately, by leveraging `calculate_probabilities=True`  in BERTopic, we can already extract the soft cluster membership for each point. Then, it is a manner of how a multi-label classification is interpreted. You could either set a threshold, which becomes difficult as the threshold may depend on the number of topics, or you can try to extract the top n probabilities as long as they do not differ more than x %. What do you think? 

The main concern I have with going for multi-label classification is that it would require significant changes to the package... Having said that, all tips and ideas are welcome!

**Comment by MaartenGr** [comment]
Since the issue has been without activity for some time, I am closing this for now. However, if you are running into this issue still or want to discuss it further, please let me know! I'll reopen it and see if we can fix the issue.

**Comment by ShivamSrng** [comment]
> Since the issue has been without activity for some time, I am closing this for now. However, if you are running into this issue still or want to discuss it further, please let me know! I'll reopen it and see if we can fix the issue.

Hey MaartenGr,

Thanks for this great library, I have been recently understanding it through the documentation, and my aim is something like that that was being conversed here. So, currently, does BERTopic have support for multilabel?

**Comment by ShivamSrng** [comment]
> [@ShivamSrng](https://github.com/ShivamSrng) You can have multiple topics per document as shown [here](https://maartengr.github.io/BERTopic/getting_started/distribution/distribution.html). You can also use the topic-doc probabilities to model the topics inside a document.

Thank you very much, I will have a look through the link.
