### ISSUE TITLE
Having trouble loading model

### ISSUE THREAD

**Issue by sebastianmarinc** [MaartenGr/BERTopic#299]
I saved the model output and when I try to load it back I get the following error:
```
BERTopic.load("bertopic_model")
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-6-7c6d6a885e38> in <module>()
----> 1 BERTopic.load("bertopic_model")

NameError: name 'BERTopic' is not defined
```
I'm using the same environment as I trained the model. Any advice?

**Comment by MaartenGr** [comment]
Ah, you need to run `from bertopic import BERTopic` instead of `import bertopic as BERTopic`. Also, you can remove the `device` parameter in the sentence transformer as it will automatically detect whether a gpu can be used or not.

**Comment by MaartenGr** [comment]
Due to inactivity, I'll be closing this issue for now. However, if you have any questions regarding this, please let me know!

**Comment by kbhardwaj** [comment]
I saw the same error as @alicehua11: `ModuleNotFoundError: No module named 'bertopic.backend'`, when trying to `load` a model on my local, after a `save` from google colab. 

When I load and save from the same environment I don't have a problem. BERTopic is installed in both environments.

Very cool project btw!

**Comment by mhdr-hami** [comment]
Hii, I too have a problem with loading the model. I hope you could help me.
I am using google colab, and this is my code.

`from bertopic import BERTopic
model = BERTopic.load("/content/drive/MyDrive/myModels/lds2")`

clearly the path, is the path I saved my model.

I get this Error:
Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.

Thanks for helping me.

**Comment by Abdur-rahmaanJ** [comment]
@mhdr-hami Same in 2023 XD
