### ISSUE TITLE
topic_model = BERTopic(language="multilingual", calculate_probabilities=True, verbose=True)

### ISSUE THREAD

**Issue by alexsomoza** [MaartenGr/BERTopic#300]
I tried run

_topic_model = BERTopic(language="multilingual", calculate_probabilities=True, verbose=True)_

and next using a simple list array with "docs" in spanish

_topics, probs = topic_model.fit_transform(docs)_

and I got this exception
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-12-92e58c27f742> in <module>
----> 1 topics, probs = topic_model.fit_transform(docs)

c:\python\python37\lib\site-packages\bertopic\_bertopic.py in fit_transform(self, documents, embeddings, y)
    279         if embeddings is None:
    280             self.embedding_model = select_backend(self.embedding_model,
--> 281                                                   language=self.language)
    282             embeddings = self._extract_embeddings(documents.Document,
    283                                                   method="document",

c:\python\python37\lib\site-packages\bertopic\backend\_utils.py in select_backend(embedding_model, language)
     65             return SentenceTransformerBackend("all-MiniLM-L6-v2")
     66         elif language.lower() in languages or language == "multilingual":
---> 67             return SentenceTransformerBackend("paraphrase-multilingual-MiniLM-L12-v2")
     68         else:
     69             raise ValueError(f"{language} is currently not supported. However, you can "

c:\python\python37\lib\site-packages\bertopic\backend\_sentencetransformers.py in __init__(self, embedding_model)
     41             self.embedding_model = embedding_model
     42         elif isinstance(embedding_model, str):
---> 43             self.embedding_model = SentenceTransformer(embedding_model)
     44         else:
     45             raise ValueError("Please select a correct SentenceTransformers model: \n"

c:\python\python37\lib\site-packages\sentence_transformers\SentenceTransformer.py in __init__(self, model_name_or_path, modules, device, cache_folder)
     88 
     89             if os.path.exists(os.path.join(model_path, 'modules.json')):    #Load as SentenceTransformer model
---> 90                 modules = self._load_sbert_model(model_path)
     91             else:   #Load with AutoModel
     92                 modules = self._load_auto_model(model_path)

c:\python\python37\lib\site-packages\sentence_transformers\SentenceTransformer.py in _load_sbert_model(self, model_path)
    820         for module_config in modules_config:
    821             module_class = import_from_string(module_config['type'])
--> 822             module = module_class.load(os.path.join(model_path, module_config['path']))
    823             modules[module_config['name']] = module
    824 

c:\python\python37\lib\site-packages\sentence_transformers\models\Transformer.py in load(input_path)
    122         with open(sbert_config_path) as fIn:
    123             config = json.load(fIn)
--> 124         return Transformer(model_name_or_path=input_path, **config)
    125 
    126 

c:\python\python37\lib\site-packages\sentence_transformers\models\Transformer.py in __init__(self, model_name_or_path, max_seq_length, model_args, cache_dir, tokenizer_args, do_lower_case, tokenizer_name_or_path)
     28         config = AutoConfig.from_pretrained(model_name_or_path, **model_args, cache_dir=cache_dir)
     29         self.auto_model = AutoModel.from_pretrained(model_name_or_path, config=config, cache_dir=cache_dir)
---> 30         self.tokenizer = AutoTokenizer.from_pretrained(tokenizer_name_or_path if tokenizer_name_or_path is not None else model_name_or_path, cache_dir=cache_dir, **tokenizer_args)
     31 
     32         #No max_seq_length set. Try to infer from model

c:\python\python37\lib\site-packages\transformers\models\auto\tokenization_auto.py in from_pretrained(cls, pretrained_model_name_or_path, *inputs, **kwargs)
    414             tokenizer_class_py, tokenizer_class_fast = TOKENIZER_MAPPING[type(config)]
    415             if tokenizer_class_fast and (use_fast or tokenizer_class_py is None):
--> 416                 return tokenizer_class_fast.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
    417             else:
    418                 if tokenizer_class_py is not None:

c:\python\python37\lib\site-packages\transformers\tokenization_utils_base.py in from_pretrained(cls, pretrained_model_name_or_path, *init_inputs, **kwargs)
   1703 
   1704         return cls._from_pretrained(
-> 1705             resolved_vocab_files, pretrained_model_name_or_path, init_configuration, *init_inputs, **kwargs
   1706         )
   1707 

c:\python\python37\lib\site-packages\transformers\tokenization_utils_base.py in _from_pretrained(cls, resolved_vocab_files, pretrained_model_name_or_path, init_configuration, *init_inputs, **kwargs)
   1774         # Instantiate tokenizer.
   1775         try:
-> 1776             tokenizer = cls(*init_inputs, **init_kwargs)
   1777         except OSError:
   1778             raise OSError(

c:\python\python37\lib\site-packages\transformers\models\bert\tokenization_bert_fast.py in __init__(self, vocab_file, tokenizer_file, do_lower_case, unk_token, sep_token, pad_token, cls_token, mask_token, tokenize_chinese_chars, strip_accents, **kwargs)
    186             tokenize_chinese_chars=tokenize_chinese_chars,
    187             strip_accents=strip_accents,
--> 188             **kwargs,
    189         )
    190 

c:\python\python37\lib\site-packages\transformers\tokenization_utils_fast.py in __init__(self, *args, **kwargs)
     85         if fast_tokenizer_file is not None and not from_slow:
     86             # We have a serialization from tokenizers which let us directly build the backend
---> 87             fast_tokenizer = TokenizerFast.from_file(fast_tokenizer_file)
     88         elif slow_tokenizer is not None:
     89             # We need to convert a slow tokenizer to build the backend

Exception: data did not match any variant of untagged enum PyPreTokenizerTypeWrapper at line 1 column 317718

**Comment by nzaw96** [comment]
> Which version of `BERTopic`, `sentence-transformers`, and `tokenizers` are you currently using? I believe updating them to the latest versions might solve the issue.

Hi Maarten,
    How can I check or update my tokenizers or BERTopic? I'm getting the error that says "Ignored unknown kwarg option direction" in my console when I employed a BERTopic() without specifying the embedding model or other parameters. Do you think this has to do with the version of the tokenizer I have? Actually I didn't use any tokenizer explicitly and just passing a list of texts/docs to BERTopic.
