### ISSUE TITLE
docs importance distribution

### ISSUE THREAD

**Issue by MitraMitraMitra** [MaartenGr/BERTopic#301]
Hi!

Is there a way to get the importance each document had in the generation of a specific topic? I used the get_representative_docs() method, but I would like to see more docs and their importance.

Thank you!

**Comment by MaartenGr** [comment]
Since the issue has been without activity for some time, I am closing this for now. However, if you are running into this issue still or want to discuss it further, please let me know! I'll reopen it and see if we can fix the issue.
