### ISSUE TITLE
Posts in each topic

### ISSUE THREAD

**Issue by sukriti1** [MaartenGr/BERTopic#304]
Hey!

I was wondering if there is a way to see:
1. The posts/sentences within each topic with their time they were posted(if we have the time series for each post). 
2. The frequency of each topic model on a day to day basis in a non-graph format.

Thanks!

**Comment by shohil-kishore** [comment]
Hey @MaartenGr, first of all thanks for creating such a great package! I have a related question - is there a way of obtaining all docs that are part of a topic? For example, when I use `topic_model.get_topic_info()` I see the column "Count" for each topic, can we extract those docs? Seeing all docs that make up a topic is great for a bit of manual validation. Thanks in advance for any help!

**Comment by MaartenGr** [comment]
@shohil-kishore Yes! This is the easiest way of achieving this. Simply put all related documents in a dictionary: 

```python
from bertopic import BERTopic
from sklearn.datasets import fetch_20newsgroups

docs = fetch_20newsgroups(subset='all',  remove=('headers', 'footers', 'quotes'))

topic_model = BERTopic()
topics, probs = topic_model.fit_transform(docs)
```

You can then use the list of topics (`topics`) to map them to the documents (`docs`):

```python
topic_docs = {topic: [] for topic in set(topics)}
for topic, doc in zip(topics, docs):
    topic_docs[topic].append(doc)
```

You can also do the above in a one-liner but that might be a bit difficult to read.

**Comment by shohil-kishore** [comment]
Thanks for your detailed answer, @MaartenGr! Very much appreciated. 👍

More than happy to [buy you a coffee](https://www.buymeacoffee.com/) or something else if you have a link active!

**Comment by MaartenGr** [comment]
That is a real nice gesture! Do not worry about it. I like working on these things 😄 

If you find any issues or have any suggestions for interesting features, let me know!
