### ISSUE TITLE
words in topics over time

### ISSUE THREAD

**Issue by doubianimehdi** [MaartenGr/BERTopic#309]
Hi Maarten,

I was looking at the topics over time and I've notice that the words in the hover bubble are different from one year to another for a particular topic, why is that ? What are those words ? Are they supposed to be topic words or words from the document ?

Thank you !

**Comment by MaartenGr** [comment]
Yes, you can find them in the `topics_over_time` variable that you retrieve when you run:

```python
topics_over_time = topic_model.topics_over_time(tweets, topics, timestamps, nr_bins=20)
```

**Comment by MaartenGr** [comment]
Due to inactivity, I'll be closing this issue for now. However, if you have any questions regarding modeling the topics over time or anything else, please let me know!
