### ISSUE TITLE
HDBSCAN step takes too much time

### ISSUE THREAD

**Issue by yutiansh4** [MaartenGr/BERTopic#311]
Hi, Mr MaartenGr,
I have a problem about HDSCAN step. I am using bertopic to train 1 Million data  on my machine with 48 cpu and 512G merory, but the HDSCAN step just use one cpu.  Does the HDSCAN support using multi-cpu? And, is HDSCAN gpu-accelerated？

**Comment by MaartenGr** [comment]
There are only certain parts in HDBSCAN that support multi-cpu. Currently, not everything in HDBSCAN, as I can remember, is parallelizable. With 1 million data points, did you make sure to set a high enough `min_topic_size`? Also, it should be more than enough to only train on a subset of the data. Try it out with 100k datapoints and predict all others.

**Comment by yutiansh4** [comment]
Thanks very much for your reply!  I have set the min_topic_size 100. Yestorday,  i set the calculate_probabilities False,then, HDSCAN step spent less time than before.

**Comment by MaartenGr** [comment]
You could even set the `min_topic_size` to a few hundred if you have a million data points. Great! Indeed, calculating probabilities is quite a time-consuming job, and setting to False typically helps. Other than that, training on a subset might be helpful.

**Comment by yutiansh4** [comment]
Thanks very much.
