### ISSUE TITLE
have issue about saving bertopic model

### ISSUE THREAD

**Issue by yutiansh4** [MaartenGr/BERTopic#313]
hi,  
 In the past i had no issue saving model, but yestorday I use 3 Millon docments to train bertopic with min_topic_size=100 and min_df =10, then  I've been unable to save the model:

Traceback (most recent call last):
  File "/data/anaconda3/envs/tf_1/lib/python3.6/site-packages/numba/core/serialize.py", line 305, in save
    return super().save(obj)
  File "/data/anaconda3/envs/tf_1/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "/data/anaconda3/envs/tf_1/lib/python3.6/pickle.py", line 701, in save_bytes
    self.write(BINBYTES + pack("<I", n) + obj)
struct.error: 'I' format requires 0 <= number <= 4294967295

and I use numba version is 0.53.1.

**Comment by MaartenGr** [comment]
Reading the error it seems that you are hitting the limits of pickling within joblib. Without changing the core structure of BERTopic, I would advise setting `topic_model. save("my_model.bt", save_embedding_model=False)`. This prevents saving the embedding model and might reduce the model's size to below 4GB (which is the limit). 

Also, upgrading joblib/pickle might do the trick if you are using an older version.

Lastly, you can try to change the `protocol` parameter in the joblib.dump method (although I have not tested this):

```python
import joblib
from bertopic import BERTopic

class UpdatedBERTopic(BERTopic):
    def save(self,
             path: str,
             save_embedding_model: bool = True) -> None:
        """ Saves the model to the specified path
        Arguments:
            path: the location and name of the file you want to save
            save_embedding_model: Whether to save the embedding model in this class
                                  as you might have selected a local model or one that
                                  is downloaded automatically from the cloud.
        Usage:
        ```python
        topic_model.save("my_model")
        ```
        or if you do not want the embedding_model to be saved locally:
        ```python
        topic_model.save("my_model", save_embedding_model=False)
        ```
        """
        with open(path, 'wb') as file:
            if not save_embedding_model:
                embedding_model = self.embedding_model
                self.embedding_model = None
                joblib.dump(self, file, protocol=4)
                self.embedding_model = embedding_model
            else:
                joblib.dump(self, file, protocol=4)

topic_model = UpdatedBERTopic(verbose=True)
topics, probs = topic_model.fit_transform(docs)
```

**Comment by MaartenGr** [comment]
Due to inactivity, I'll be closing this issue for now. However, if you have any questions regarding this, please let me know!
