### ISSUE TITLE
ValueError: Buffer has wrong number of dimensions (expected 1, got 2)

### ISSUE THREAD

**Issue by PiyushKyushu** [MaartenGr/BERTopic#314]
Hi Maarten,

Thanks for developing a cool alternative to the traditional topic modeling methods.
I am excited to use it but I am facing some issues. I hope you can guide me.
I am trying to use BERTopic on my dataset [my dataset has around 10,000 rows and only one column]. But I am getting below error. Can you please tell me the probable reason and to resolve this issue.

Thank you in advance!

I was following this tutorial [https://colab.research.google.com/drive/1FieRA9fLdkQEGDIMYl0I3MCjSUKVF8C-?usp=sharing#scrollTo=TfhfzqkoSJ1I]. 
First I load my dataset (rather than 20 newsgroups dataset which tutorial used).

```
data = pd.read_csv("My_Dataset.csv")
data.head()
```
Then I used the below code (as tutorial).

```
from bertopic import BERTopic

topic_model = BERTopic(language="english", calculate_probabilities=True, verbose=True)
topics, probs = topic_model.fit_transform(data)
```
But I got this error.

> ---------------------------------------------------------------------------
> ValueError                                Traceback (most recent call last)
> /var/folders/dq/cswf4bms1278238j6tqvzb800000gn/T/ipykernel_9597/615010994.py in <module>
>       2 
>       3 topic_model = BERTopic(language="english", calculate_probabilities=True, verbose=True)
> ----> 4 topics, probs = topic_model.fit_transform(data)
> 
> ~/opt/anaconda3/envs/tokyotech/lib/python3.7/site-packages/bertopic/_bertopic.py in fit_transform(self, documents, embeddings, y)
>     274         documents = pd.DataFrame({"Document": documents,
>     275                                   "ID": range(len(documents)),
> --> 276                                   "Topic": None})
>     277 
>     278         # Extract embeddings
> 
> ~/opt/anaconda3/envs/tokyotech/lib/python3.7/site-packages/pandas/core/frame.py in __init__(self, data, index, columns, dtype, copy)
>     612         elif isinstance(data, dict):
>     613             # GH#38939 de facto copy defaults to False only in non-dict cases
> --> 614             mgr = dict_to_mgr(data, index, columns, dtype=dtype, copy=copy, typ=manager)
>     615         elif isinstance(data, ma.MaskedArray):
>     616             import numpy.ma.mrecords as mrecords
> 
> ~/opt/anaconda3/envs/tokyotech/lib/python3.7/site-packages/pandas/core/internals/construction.py in dict_to_mgr(data, index, columns, dtype, typ, copy)
>     463 
>     464     return arrays_to_mgr(
> --> 465         arrays, data_names, index, columns, dtype=dtype, typ=typ, consolidate=copy
>     466     )
>     467 
> 
> ~/opt/anaconda3/envs/tokyotech/lib/python3.7/site-packages/pandas/core/internals/construction.py in arrays_to_mgr(arrays, arr_names, index, columns, dtype, verify_integrity, typ, consolidate)
>     122 
>     123         # don't force copy because getting jammed in an ndarray anyway
> --> 124         arrays = _homogenize(arrays, index, dtype)
>     125 
>     126     else:
> 
> ~/opt/anaconda3/envs/tokyotech/lib/python3.7/site-packages/pandas/core/internals/construction.py in _homogenize(data, index, dtype)
>     588 
>     589             val = sanitize_array(
> --> 590                 val, index, dtype=dtype, copy=False, raise_cast_failure=False
>     591             )
>     592 
> 
> ~/opt/anaconda3/envs/tokyotech/lib/python3.7/site-packages/pandas/core/construction.py in sanitize_array(data, index, dtype, copy, raise_cast_failure, allow_2d)
>     569             subarr = _try_cast(data, dtype, copy, raise_cast_failure)
>     570         else:
> --> 571             subarr = maybe_convert_platform(data)
>     572             if subarr.dtype == object:
>     573                 subarr = cast(np.ndarray, subarr)
> 
> ~/opt/anaconda3/envs/tokyotech/lib/python3.7/site-packages/pandas/core/dtypes/cast.py in maybe_convert_platform(values)
>     124     if arr.dtype == object:
>     125         arr = cast(np.ndarray, arr)
> --> 126         arr = lib.maybe_convert_objects(arr)
>     127 
>     128     return arr
> 
> ~/opt/anaconda3/envs/tokyotech/lib/python3.7/site-packages/pandas/_libs/lib.pyx in pandas._libs.lib.maybe_convert_objects()
> 
> ValueError: Buffer has wrong number of dimensions (expected 1, got 2)

I am new to BERTopic. Kindly help me.

**Comment by MaartenGr** [comment]
Ah, BERTopic expects a list of strings as its input. Your input, the `data` variable, is a dataframe. If you transform the column to a list, then it should work! For example, if you have a columns `"Documents"`, simply run 

```python 
topics, probs = topic_model.fit_transform(data.Documents.tolist())
```

**Comment by PiyushKyushu** [comment]
Thank you so much for your reply. It solved the error.

Since the problem is solved I am closing the issue. 

Thank you.
