### ISSUE TITLE
Clustering on multilingual data, but use english c-tf-idf

### ISSUE THREAD

**Issue by timpal0l** [MaartenGr/BERTopic#315]
I have a dataset that contains of around 20 different languages, where they all talk about the same topics. But I wish to use only english when creating the c-tf-idf words (for interpretation purposes) from the multilingual clusters that are based on multilingual embeddings with: `paraphrase-multilingual-mpnet-base-v2`

However, when I run:
`topic_model.get_topic_info()`

I get a bunch of non-english words, so it seems that the vocabulary got updated based on the multilingual docs. Is there any way to force the vocabulary to be fixed to english only?

My attempt below:

`count_vectorizer_en = CountVectorizer().fit(english_docs)`

```
topic_model = BERTopic(verbose=True, min_topic_size=50, 
                       nr_topics='auto', 
                       embedding_model='paraphrase-multilingual-mpnet-base-v2', 
                       vectorizer_model=count_vectorizer_en)
```
`topics, probs = topic_model.fit_transform(multilingual_docs)`

To verify, the:

`count_vectorizer_en.get_feature_names()` yields different vocabularies before and after the `fit_transform()` has been run by the `topic_model`

Is it possible to only make the `count_vectorizer_en` use `.transform()` method on new data?

**Comment by MaartenGr** [comment]
Interesting use-case! Glad to see some creative approaches to using BERTopic. 

The behavior is as expected as the `vectorizer_model` is always fitted inside BERTopic. At the moment it does not support a fitted vectorizer. Having said that, I believe your use-case should be possible by focusing on parameters when instantiating the vectorizer instead of fitting the vectorizer. 

That would basically mean the following:

```python
# Create a vocabulary to use within CountVectorizer without fitting
count_vectorizer_en = CountVectorizer().fit(english_docs)
count_vectorizer_en = CountVectorizer(vocabulary=count_vectorizer_en.vocabulary_)

# Pass the vectorizer to BERTopic and let it use only the vocab from the vectorizer
topic_model = BERTopic(verbose=True, min_topic_size=50, 
                       nr_topics='auto', 
                       embedding_model='paraphrase-multilingual-mpnet-base-v2', 
                       vectorizer_model=count_vectorizer_en)
```

I did not try this out but it seems that this should do the trick without fitting the vectorizer beforehand.

**Comment by timpal0l** [comment]
@MaartenGr Thanks for the fast reply and what an effort you have made in this framework! 

Your solution worked quite well! (It still had a few non english words, but that was just because a small number of docs in my "english" docs were apparently non-english 😄) 

They could easily be filtered out with the `min_df=100` in the CountVectorizer :)

```python
# Create a vocabulary to use within CountVectorizer without fitting
count_vectorizer_en = CountVectorizer(min_df=100).fit(english_docs)
count_vectorizer_en = CountVectorizer(vocabulary=count_vectorizer_en.vocabulary_)

# Pass the vectorizer to BERTopic and let it use only the vocab from the vectorizer
topic_model = BERTopic(verbose=True, min_topic_size=50, 
                       nr_topics='auto', 
                       embedding_model='paraphrase-multilingual-mpnet-base-v2', 
                       vectorizer_model=count_vectorizer_en)
```

**Comment by MaartenGr** [comment]
Great! Glad to hear that it worked out. If you have any other issues, please let me know!
