### ISSUE TITLE
docs of a topic

### ISSUE THREAD

**Issue by MitraMitraMitra** [MaartenGr/BERTopic#316]
Hi there!

Is there a way to get all the docs of a topic, after creating a model? It would be nice to be able to browse the docs by topic, but the get_representative_docs() method returns too few docs.

Thanks!

**Comment by MaartenGr** [comment]
The `get_representative_docs()` method is not meant to return all documents per topic as that would defeat its purpose of returning the most representative documents. It is a method used primarily for further understanding the topics that were created. 

When you have called the `transform()` or `fit_transform()` method on your documents, you already know which documents relate to which topics. Let's use the following code as an example:

```python
from bertopic import BERTopic
from sklearn.datasets import fetch_20newsgroups
 
docs = fetch_20newsgroups(subset='all',  remove=('headers', 'footers', 'quotes'))['data']

topic_model = BERTopic()
topics, probs = topic_model.fit_transform(docs)
``` 

Here, each topic in `topics` relates to the document at the same index in `docs`. In other words, 
* `topics[0]` relates to `docs[0]`
* `topics[1]` relates to `docs[1]`
* etc. 

Thus, you can create a dictionary yourself with all documents per topic:

```python
topic_docs = {topic: [] for topic in set(topics)}
for topic, doc in zip(topics, docs):
    topic_docs[topic].append(doc)
```

You can also do the above in a one-liner but that might be a bit difficult to read.
