### ISSUE TITLE
Using pretrained models

### ISSUE THREAD

**Issue by gouthamgithub** [MaartenGr/BERTopic#317]
Hi Maarten,

When using pretrained embedding models like USE, are we fine-tuning the existing model with our new dataset or are we just passing the new documents to find respective word and document embedding?

If fine-tuning is not happening here, how is bertopic creating embeddings for new unseen words?

**Comment by MaartenGr** [comment]
The pre-trained embedding models are not fine-tuned and are primarily used to generate the word and document embeddings. Some of these models can easily generalize the creation of embeddings to words it has not seen before, for example, based on the context in which the words were supplied. 

Does that answer your questions?

**Comment by gouthamgithub** [comment]
I read an article that talks about pretrained models breaking down out-of-vocabulary words into sub words to find character n-gram embeddings and generalize them, which might also be the case for USE. 

Anyway, thanks for your reply :)

**Comment by MaartenGr** [comment]
No problem, glad I could help! What you are referring to is typically the FastText model which has put out of vocabulary embeddings on the map. Feel free to let me know whenever you run into any problems!
