### ISSUE TITLE
Installation on Windows 7 64bit is missing libcblas.dll

### ISSUE THREAD

**Issue by padmalcom** [MaartenGr/BERTopic#319]
Hi, I tried to install bertopic via pip install on windows 7 using anaconda. Here are the issues I'm facing:

- hdbscan cannot be installed as dependency, so I installed it using conda
- Then I can install bertopic using pip but when I create an instance of BERTopic, python tells me libcblas.dll is missing

Can someone help me out?

**Comment by MaartenGr** [comment]
Strange, I would advise starting from a fresh conda environment. Make sure that no global conda packages are installed and then install BERTopic through a pip install without installing hdbscan first. Hopefully, starting from a fresh environment solves the issue. If that does not work, could you share the steps, in code, of installing the packages and the resulting errors?

**Comment by MaartenGr** [comment]
Due to inactivity, I'll be closing this issue for now. However, if you are still running into this issue or one related, please let me know, and hopefully, we can fix it!

**Comment by padmalcom** [comment]
Sorry @MaartenGr for the missing reply. I went back to LDA due to my issue. Eben with a clean env I couldn't install the library. We'll soon move to containers so that I'll try again when I have a linux backend.
