### ISSUE TITLE
Question about topic trajectory at group level

### ISSUE THREAD

**Issue by kjaksic** [MaartenGr/BERTopic#323]
Hi, 

first of all, thank you for the amazing work.  

I have a bit specific research problem and I use dynamic topic modeling to solve it. 

Basically, what I would like to do is to compare topic distribution between different groups of participants at specific time point t. So, I want to run the model on the whole data set to establish topics and then to extract topic frequencies for different groups of participants at time point t so I can compare how similar their distributions are. 

To do this, I would need to extract topic frequencies for each participant in the sample at time point t. Is it possible to somehow get this kind of data? 

Thank you for the response.

**Comment by Kaleemullahqasim** [comment]
```
from bertopic import BERTopic
topic_model = BERTopic()
topics, probs = topic_model.fit_transform(docs)
topics_over_time = topic_model.topics_over_time(docs, topics, timestamps, nr_bins=20)
```
i think this will do the job in your case. you can check the topic distribution over time..

Note:: 
Make sure to use a limited number of unique timestamps (<100) as the
c-TF-IDF representation will be calculated at each single unique timestamp.
Having a large number of unique timestamps can take some time to be calculated.
Moreover, there aren't many use-cased where you would like to see the difference
in topic representations over more than 100 different timestamps.
Copied from docomentations.

**Comment by MaartenGr** [comment]
@kjaksic Let me see if I understand it correctly. Aside from modeling topics over time, so different topic representations at different timestamps, you also want to create different topic representations for different groups of people. 

Quite an interesting use-case and rather difficult to model in one go. `topics_over_time` only takes into account the topic distributions over time and disregards any groups that you might have. In contrast, `topics_per_class` only takes into account the topics per group and disregards any timestamps you might have. 

Fortunately, we can try to approach this, albeit a bit hacky 😅

Whenever you use `topics_per_class` you need to pass it a number of documents, topics and the related classes like so:
```python
topics_per_class = topic_model.topics_per_class(docs, topics, classes=classes)
```

Here, you are free to choose the `docs`, `topics`, and `classes` that you pass to the function. So, if you would pass those variables at time *t* you would get the topic representation at that time *t* per group. The only downside is that you will have to do this for each time *t*. 

To make this a bit more concrete, image you have the following variables:

```python
docs = ["document 1", "document 2", "document 3", "document 4", "document 5"]
topics = [0, 1, 0, 1, 1]
timestamps = [0, 0, 1, 1, 0]
classes = ["Class 1", "Class 2", "Class 1", "Class 3", "Class 2"]
```

You would then only need to slice the variables to match timestamp 0 and pass those to BERTopic:

```python
timestamp = 0
selected_docs = [doc for doc, time in zip(docs, timestamps) if time == timestamp]
selected_topics = [topic for topic, time in zip(topics, timestamps) if time == timestamp]
selected_classes = [group for group, time in zip(classes, timestamps) if time == timestamp]

topics_per_class = topic_model.topics_per_class(selected_docs , selected_topics , classes=selected_classes )
```

**Comment by kjaksic** [comment]
Hi @MaartenGr, 

thank you for the quick response :)

Yes, I would like to model topics over time and to see how frequencies of topics at some time point t differ between groups of participants (for example males and females). 

I think your approach should work. So basically, I have to run the algorithm on the whole dataset to establish topics, and then to run topics_per_class at a specific time point t to be able to compare topic frequency (and its representation) for different classes (or genders as in the example) at that particular time point. 

Thank you a lot for the help.

**Comment by MaartenGr** [comment]
No problem! 

Yes, run the algorithm on the whole dataset and then `topics_per_class` after filtering your data to only represent a certain time point *t*. If, for some reason, it does not work out, let me know!

**Comment by kjaksic** [comment]
Hi,

just to let you know, the code works perfectly :)

Thank you.

pet, 12. stu 2021. u 07:41 Maarten Grootendorst ***@***.***>
napisao je:

**Comment by MaartenGr** [comment]
Great! Glad to hear that it is working. If you have any other issues or questions, feel free to post them here or create another issue!
