### ISSUE TITLE
N of words in the name of the topic. 

### ISSUE THREAD

**Issue by bohdanbaliuk2020** [MaartenGr/BERTopic#325]
Hi!

Does there any way to increase the number of words in a topic name (which we get using get_topic_info())? Currently, it displays 4 terms in a name but I need more (at least 20) for a better understanding of the meaning of the topic. 
Thank you in advance.

**Comment by MaartenGr** [comment]
To get the full representation of a topic, you need to run `topic_model.get_topic(topic=12)`  to get all words related to topic 12. The topic name that you see in `.get_topic_info()` is merely a quick representation of the topic for easier reading. It is advised to use `.get_topic` to extract all related words.

**Comment by qinyuexiao** [comment]
> To get the full representation of a topic, you need to run `topic_model.get_topic(topic=12)` to get all words related to topic 12. The topic name that you see in `.get_topic_info()` is merely a quick representation of the topic for easier reading. It is advised to use `.get_topic` to extract all related words.

`topic_model.get_topic()` can only get top n words with maximum of 10 by default. Is there a way to get more top words from a topic?

**Comment by MaartenGr** [comment]
That is a result of the default value of `top_n_words` when instantiating BERTopic. If you set that value higher, you will get more words in `.get_topic()`. However, there will be a maximum of 30 words with how BERTopic currently works. This might be increased in a new release but there is typically little use case for having more than 30 words as the significance of words in a topic greatly decreases with each word.

**Comment by bohdanbaliuk2020** [comment]
Sorry for the great delay. Now I resolved my issue after implementing your suggestion. 
Much obliged! Thank you!

**Comment by MaartenGr** [comment]
Glad to hear that it worked out!
