### ISSUE TITLE
Getting empty string topic

### ISSUE THREAD

**Issue by christopherfeld** [MaartenGr/BERTopic#327]
Running 0.9.3

Any ideas why I would get an empty topic, despite that there are no original documents that were empty?

![image](https://user-images.githubusercontent.com/82411398/141541113-5f2aed25-7b91-424b-a58a-e1a3f8b1377a.png)
![image](https://user-images.githubusercontent.com/82411398/141541143-d485609d-1ad0-46bf-ad1b-5898ca3ec9a4.png)

**Comment by christopherfeld** [comment]
user error, I missed a preprocessing step where the result was blank :/

**Comment by sanketjoshi2012** [comment]
Hi, could you please elaborate on the problem? I am facing the same issue

**Comment by christopherfeld** [comment]
> Hi, could you please elaborate on the problem? I am facing the same issue

Double check your preprocessing step and make sure there are no blank documents.
