### ISSUE TITLE
How are the representative docs found?

### ISSUE THREAD

**Issue by MitraMitraMitra** [MaartenGr/BERTopic#328]
Hi there!

I'm trying to understand what the representative docs mean, more exactly. I imagine they're the docs closest to the 'center' of a cluster. Could you provide some resources where I can find more about what makes representative docs stand out?

Thank you!

**Comment by MitraMitraMitra** [comment]
I have some additional questions and I would very much appreciate it if you could help me with them. I read about Class-based TF-IDF in the documentation (https://maartengr.github.io/BERTopic/api/ctfidf.html) and I liked the clear explanation. This being said, is a class a topic in bertopic?
Is it correct to say that the last denominator in the formula ('the total sum of word i across all classes') is actually the total sum of word i across all documents found to be in a topic with id != -1?
Seeing that calculating the word score is done based on clusters that are already formed, I have to ask - how are clusters/topics formed?

**Comment by MaartenGr** [comment]
> I'm trying to understand what the representative docs mean, more exactly. I imagine they're the docs closest to the 'center' of a cluster. Could you provide some resources where I can find more about what makes representative docs stand out?

The representative docs are those that are called "exemplars" in HDBSCAN. They are the most representative documents for a cluster and often not those closest to the center of the cluster. You can find more about that [here](https://hdbscan.readthedocs.io/en/latest/soft_clustering_explanation.html#distance-based-membership).

> This being said, is a class a topic in bertopic?

Yes, in BERTopic, a topic is regarded as being a class/cluster/group. 

> Is it correct to say that the last denominator in the formula ('the total sum of word i across all classes') is actually the total sum of word i across all documents found to be in a topic with id != -1?

Not necessarily, it is the sum of word *i* across all documents, regardless of its topic or class. 

> Seeing that calculating the word score is done based on clusters that are already formed, I have to ask - how are clusters/topics formed?

Clusters are formed by clustering the embeddings created through your language model. You can find more about the clustering steps in the documentation [here](https://maartengr.github.io/BERTopic/tutorial/algorithm/algorithm.html). 

Hopefully, this answers some of your questions!
