### ISSUE TITLE
Force no outliers (topic -1 count = 0) in BERTopic topic modelling results

### ISSUE THREAD

**Issue by lighteternal** [MaartenGr/BERTopic#329]
HI there, 

First of all, kudos for this amazing package! 

I am working on a project where each a topic **must** be assigned to each doc. 
That means that `get_topic_info()` should return no outliers. I experimented a bit with HDBSCAN and UMAP parameters, however I was unable to find a correct combination in order to effectively reduce outliers (acknowledging that this will also reduce the resulting topic quality of course). 

This is the current topic distribution. Almost half of the 50k docs belong to the -1 topic (outlier) class : 
![image](https://user-images.githubusercontent.com/22905968/141977815-8aab0c27-44df-4049-8f1c-9fe5b62e0bfe.png)

Are there any ideas on how to achieve this?

**Comment by MaartenGr** [comment]
Although there are ways of reducing the number of outliers, as mentioned [here](https://hdbscan.readthedocs.io/en/latest/faq.html#q-most-of-data-is-classified-as-noise-why), HDBSCAN almost always generates outliers. It is not meant to force data points together when they are not supposed to. The link above should help in reducing the number of outliers by lowering both `min_samples` and `min_cluster_size` in the HDBSCAN configuration. However, you most likely will still have some outliers to work with. 

Having said that, I can definitely imagine needing to find a topic for every single document. After having done the above step to reduce as many outliers as possible, you can simply use the probability matrix to assign topics yourself. So, set `calculate_probabilities=True` when instantiating BERTopic and use the resulting `probs` variable to see which topic most likely belongs to the outliers. That way, each document will be classified to a specific topic even though an outlier class exists. BERTopic will still have an outlier class in `get_topic_info()`, which should not be a problem as you can simply ignore the -1 class.

**Comment by lighteternal** [comment]
Your advice of leveraging the argmax of the `probs` to manually assign a topic for each doc worked like a charm.
Many thanks for the fast response!

**Comment by MaartenGr** [comment]
Glad to hear that it worked out. If you find yourself finding any other issues or want to discuss this issue further, please let me know!

**Comment by schetudiante** [comment]
Hey @MaartenGr and @lighteternal 
> Your advice of leveraging the argmax of the `probs` to manually assign a topic for each doc worked like a charm. Many thanks for the fast response!

hey, I am also facing the same issue can you share the code snippet you used?
currently, I rely on :
`reduce_topics(self, docs, topics, probabilities=probs, nr_topics=20)` but I still get like 60% of my docs as outliers.
Help would be appreciated! 
Thanks
