### ISSUE TITLE
Languages bug

### ISSUE THREAD

**Issue by krolikowskib** [MaartenGr/BERTopic#33]
In https://github.com/MaartenGr/BERTopic/blob/1ec0313038bda7a4e54c6ef5be7f420ba76d8588/bertopic/_bertopic.py#L892 you check whether language argument is in `languages` list. But lowercase is applied first and `languages` list elements start with uppercase, so it is not possible to initialize BERTopic with any language from this list besides English (as another if case handles this).

**Comment by mawic** [comment]
Same issue!

**Comment by MaartenGr** [comment]
Good call! I hadn't noticed it since I mostly worked with either `"english"` or `"multilingual"`. For now, you can use `"multilingual"` to select the model that corresponds to the languages in `languages`.

**Comment by MaartenGr** [comment]
Fixed! Just update to v0.4.1 with `pip install --upgrade bertopic` and it should work as intended.
