### ISSUE TITLE
How to include Outlier topic in Visualisation in BERTopic

### ISSUE THREAD

**Issue by PiyushKyushu** [MaartenGr/BERTopic#332]
Hi Maarten,
In my dataset of around 9000 rows when I use BERTopic, it produce a topic model with around 3700 documents as outlier topic. But I want all topics to be included in the topic model. When I search for this issue I found that a similar question has been ask, answered, and closed. The link for that is [https://github.com/MaartenGr/BERTopic/issues/329](url) However, I couldn't understand it properly (maybe because of my little experience/knowledge). 

As mentioned in that answer, I also used `calculate_probabilities=True` and run the model. This give the topic model with outliers and by using `topic_model.get_topic(-1)` I understood the topic. But is it possible that when we visualise the model with   `topic_model.visualize_topics()` this outliers is also included in that ?

Also, I hate to open another issue that is why I asking it here. I don't understand _**topic probability distribution**_ and its significance. Can you please tell me any resource where I can read about it and understand it.

Thank you so much in advance for all the help!

**Comment by MaartenGr** [comment]
> However, I couldn't understand it properly (maybe because of my little experience/knowledge).

No problem! Let me see if I can clarify this with an example. When you set `calculate_probabilities=True` the resulting `probs` variable contains, for each document, the probability of belonging to each topic.

```python
from bertopic import BERTopic
from sklearn.datasets import fetch_20newsgroups
 
docs = fetch_20newsgroups(subset='all',  remove=('headers', 'footers', 'quotes'))['data']

topic_model = BERTopic(calculate_probabilities=True)
topics, probs = topic_model.fit_transform(docs)
```

In the code above, we generate a `topics` and a `probs` variable. In `topics` we will find clearly defined topics but also the -1 outlier class. To make sure that all documents are assigned to a proper topic, we look at the `probs` variable. Let's say that `docs[5]` is assigned to -1. This means that `topics[5]` will be -1. To find the topic it most likely belongs to, we can check the highest probability in `probs[5]`. The index of the highest probability then belongs to the related topic. So, you can use a `np.argmax(docs[5])` to find the best fitting topic. Do this for each document assigned to -1 and you will have each document assigned to a proper topic. 

> But is it possible that when we visualise the model with `topic_model.visualize_topics()` this outliers is also included in that ?
The `visualize_topics()` method only shows you the topics and not the documents. Visualizing the outlier topic is typically not meaningful as the outlier topic should actually not be a topic. We can assume that the documents in the outlier topic have little relationship with each other. Thus, we do not visualize the outlier class in this method. 

> I don't understand topic probability distribution and its significance.
This relates to my answer to your first question. The topic probability distribution is contained within the `probs` variable. Basically, it contains the probability that document 1 belongs to topic 1, topic 2, topic 3, etc. In other words, we can use those values to see what the likelihood is that document 1 belongs to a specific topic. The significance of this, in part, is that we can see which topics are most related to a specific document. 

Hopefully, this answers your questions a bit!

**Comment by PiyushKyushu** [comment]
Thank you for the explanation Maarten. It certainly further my understanding.

Can I add `np.argmax(docs[5])` line in Colab code or I have to do it somewhere else?
 
Also when we write this line of code `topic_model.visualize_distribution(probs[1], min_probability=0.0)` what is the parameter in probs[?]? What do we mean/asking for when we write this line?

**Comment by MaartenGr** [comment]
> Can I add np.argmax(docs[5]) line in Colab code or I have to do it somewhere else?

Yes, you can add `np.argmax(probs[5])` after you have generated the `probs` variable. The `5` represents the document for which you want to find the topic. 

> Also when we write this line of code topic_model.visualize_distribution(probs[1], min_probability=0.0) what is the parameter in probs[?]? What do we mean/asking for when we write this line?

The `probs` variable is a matrix and when we want to extract the probabilities for a single document, we slice the `probs` variable like so: `probs[1]` to access the document with index `1`.

**Comment by PiyushKyushu** [comment]
Thank you Maarten. This is very helpful. 

Now I am closing the issue.
