### ISSUE TITLE
numpy >=1.20.0 doesn't support Python3.6 causing BERTopic installation failure

### ISSUE THREAD

**Issue by electrowizard** [MaartenGr/BERTopic#333]
Hi Maarten,

Thanks for maintaining this amazing project!

I recently tried to upgrade to the latest version of BERTopic from [v0.6.0](https://github.com/MaartenGr/BERTopic/releases/tag/v0.6.0) while using Python 3.6. The installation failed with the error `ERROR: No matching distribution found for numpy>=1.20.0`

On digging deeper, I noticed that even though BERTopic claims support for [Python 3.6](https://github.com/MaartenGr/BERTopic/blob/15ea0cd804d35c1f11c6692f33c3666b648dd6c8/setup.py#L81), numpy versions 1.20.0 and above has depreciated support for Python 3.6. Since the latest version of BERTopic required numpy>=1.20.0, the installation failed.

From the [numpy 1.20.0 release notes](https://numpy.org/devdocs/release/1.20.0-notes.html):

>The Python versions supported for this release are 3.7-3.9, support for Python 3.6 has been dropped

It might be worth re-visiting the minimum supported Python version for BERTopic.

Hope it helps!
Sathvik

**Comment by MaartenGr** [comment]
Nice catch! It indeed does not support python 3.6 anymore and it seems that I did not properly update the readme. Thank you for noticing the inconsistency! I'll make sure to fix this in the next release 😃

**Comment by doubianimehdi** [comment]
I'm not sure what the implications of that are ... does that mean that we can no longer have the latest bertopic version on python 3.6 ? if so what is the latest version we can have on 3.6 ? I'm struggling to install it on dataiku maybe because of that i'm stuck on 0.6.0 ...

**Comment by MaartenGr** [comment]
Typically, this should not affect that many applications as most support at least python 3.7. [Dataiku also supports 3.7](https://doc.dataiku.com/dss/latest/code-envs/operations-python.html) so it should be no problem using the newest version of BERTopic there. If, however, you need to have 3.6 for some reason, you could try an earlier version of BERTopic but many features will be missing. 

Which python version do you have on dataiku? Which issues are you running into?

**Comment by doubianimehdi** [comment]
I have a 3.6 python environnement and i'm trying to have the topics over time and other visualization graphics to run on dataiku so I can make a dashboard out of it and i have 3 weeks left to do that ....

**Comment by MaartenGr** [comment]
@doubianimehdi To make it concrete, which issue are you exactly running into? Could you share how you tried to install and run BERTopic? Also, which specific errors are you running into?

With respect to the environment, a quick fix would be to load up a python 3.7 environment in Dataiku if you have permissions to do so.

**Comment by doubianimehdi** [comment]
This issue is that I end up with bertopic 0.6.0 maximum on python 3.6 on dataiku ... and it doesn't seem to have visualization rank and so on ... I'd like to know from which version, compatible with 3.6 of python I could deploy to have at least topics over time visualization ?

I don't have permission to have Python 3.7 for now ...

**Comment by MaartenGr** [comment]
In your case, you could try to install the newest version with BERTopic but force the dependencies to fit with your environment. In other words, something like this:

```
pip install bertopic --no-dependencies
```

Then, you can install the newest versions of all base packages excluding numpy:

```
base_packages = [
    "hdbscan>=0.8.27",
    "umap-learn>=0.5.0",
    "pandas>=1.1.5",
    "scikit-learn>=0.22.2.post1",
    "tqdm>=4.41.1",
    "sentence-transformers>=0.4.1",
    "plotly>=4.7.0,<4.14.3",
    "pyyaml<6.0"
]
```

This should make the newest version of BERTopic work with python 3.6. However, I cannot make any promises that your code will break at some point. The numpy version was increased to circumvent several issues that users were experiencing. So use this at your own risk.

**Comment by doubianimehdi** [comment]
what is this command base packages ? how do you execute it ?

**Comment by MaartenGr** [comment]
These are the versions of packages you need to install in order to get BERTopic working. Those are the dependencies you need to have installed (except for numpy) with their corresponding version.

**Comment by MaartenGr** [comment]
The issue from OP was fixed in the v0.9.4 release of BERTopic so I'll be closing this issue for now. Let me know if you run into any other issues!

**Comment by ysadre** [comment]
Hello @MaartenGr,

First, thanks for the package:). I have installed Bertopic through Pypi and I have been trying to run it on my Jupyter Notebook but whenever I try to import it, I got the same error message: "numpy.ndarray size changed, may indicate binary incompatibility."

I have tried to uninstall, then reinstall NumPy on another version but didn't work. I'm trying to run it on Python 3.9.7, and my current NumPy version is 1.22.1. 

Let me know if you have any idea on how to solve that, thank you:)

**Comment by MaartenGr** [comment]
@ysadre There currently is an issue with HDBSCAN not working well with Numpy which generates the error message that you mentioned. You can find solutions for that issue [here](https://github.com/MaartenGr/BERTopic/issues/392#issuecomment-1006333143) and [here](https://github.com/MaartenGr/BERTopic/issues/392#issuecomment-1021243094). Basically, the easiest options are to either use python 3.7 or install BERTopic through conda.
