### ISSUE TITLE
KeyError 1033

### ISSUE THREAD

**Issue by Tunguyen485** [MaartenGr/BERTopic#337]
Hi Maarten,
Thank you for your amazing work. 
I have an issue when I try to apply embeddings to find the topics and probabilities. 
Could you help me to solve this problem?

sentence_model = SentenceTransformer("all-MiniLM-L6-v2")
embeddings = sentence_model.encode(docs, show_progress_bar=True)

vectorizer_model = CountVectorizer(ngram_range=(1, 3), stop_words="english", min_df=5)

topic_model = BERTopic(nr_topics = 40,
                 language = 'english',
                 vectorizer_model = vectorizer_model, 
                 calculate_probabilities = True,
                 verbose=True)
 
topics, probabilities = model.fit_transform(docs, embeddings)

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-72-1c9e2f44769b> in <module>
     16                  verbose=True)
     17 
---> 18 topics, probabilities = model.fit_transform(docs, embeddings)

~\Anaconda3\lib\site-packages\bertopic\_bertopic.py in fit_transform(self, documents, embeddings, y)
    302             documents = self._reduce_topics(documents)
    303 
--> 304         self._map_representative_docs()
    305         probabilities = self._map_probabilities(probabilities)
    306         predictions = documents.Topic.to_list()

~\Anaconda3\lib\site-packages\bertopic\_bertopic.py in _map_representative_docs(self)
   1503         if self.merged_topics:
   1504             for topic_to_remove in self.merged_topics:
-> 1505                 del representative_docs[topic_to_remove]
   1506 
   1507         # Update the representative documents

KeyError: 1033

**Comment by MaartenGr** [comment]
I just tried out the following with BERTopic v0.9.3 in a Google Colab session and did not get your error:

```python
from sklearn.datasets import fetch_20newsgroups
from sentence_transformers import SentenceTransformer
from sklearn.feature_extraction.text import CountVectorizer
from bertopic import BERTopic

# Prepare embeddings
docs = fetch_20newsgroups(subset='all',  remove=('headers', 'footers', 'quotes'))['data']
sentence_model = SentenceTransformer("all-MiniLM-L6-v2")
embeddings = sentence_model.encode(docs, show_progress_bar=True)

vectorizer_model = CountVectorizer(ngram_range=(1, 3), stop_words="english", min_df=5)

topic_model = BERTopic(nr_topics = 40,
                       language = 'english',
                       vectorizer_model = vectorizer_model,
                       calculate_probabilities = True,
                       verbose=True)

topics, probabilities = topic_model.fit_transform(docs, embeddings)
```

Which version of BERTopic are you using? Also, did you try it out in a fresh environment?

**Comment by Tunguyen485** [comment]
Hi Maarten,
When I try it in the Google Colab environment and upgrade the bertopic, the code does run. 
Thank you for your quick response.
