### ISSUE TITLE
The visualize topics does not work 

### ISSUE THREAD

**Issue by majidebraa** [MaartenGr/BERTopic#339]
Hello. I run visualize topics methods in my Windows OS with PyCharm and Python 3.8. when print this method get JSON object for visualizing, but not show a charts and diagrams.

**Comment by MaartenGr** [comment]
The `visualize_topics` method returns a plotly figure which cannot be printed. Instead, you can run `fig.show()` or simply `fig` in the terminal within pycharm to visualize the image. If that does not work, you can either run it in a jupyter/ipython session or there might be an issue with the settings in pycharm.

**Comment by MaartenGr** [comment]
Due to inactivity, I am going to close this issue. If you are still experiencing this issue, let me know! I'll reopen it and we can discuss it further.

**Comment by MaartenGr** [comment]
@AbuBakarrr It might be helpful to look into the documentation of Plotly [here](https://plotly.com/python/getting-started/) that can help you out when installing it to work within jupyter notebooks. Also, there is an issue [here](https://github.com/MaartenGr/BERTopic/issues/764) that might help you out.

**Comment by NiekPas** [comment]
This seems like a documentation problem to me. The Readme very clearly shows the function call `topic_model.visualize_topics()` followed a gif of an interactive application. It's not surprising that newcomers would be confused. Adding a brief disclaimer to the readme would help.

**Comment by tmsss** [comment]
I had the same issue while calling the function in a python script and using topic_model.visualize_topics().show() worked for me.

**Comment by smadwer** [comment]
@tmsss it works here too!! thanks man for tip

**Comment by RomanBlaaas** [comment]
@tmsss it works for me too!! Great, thank you very much.

**Comment by kungmo** [comment]
@PeggyFan I had this issue once and solved it by setting the plotly.io renderers to **iframe.**

`import plotly.io as pio`
`pio.renderers.default='iframe'`

_Originally posted by @psyronika in https://github.com/MaartenGr/BERTopic/issues/764#issuecomment-1271431205_
            

I am using jupytrlab 4.2.5, and this code worked.

**import plotly.io as pio
pio.renderers.default = "colab"** # 안 나오면 https://plotly.com/python/renderers/ 참조하여 렌더러 변경

topic_model.visualize_barchart(top_n_topics=len(topic_model.get_topic_info()))

**Comment by Ravi2712** [comment]
> ```
>           @PeggyFan I had this issue once and solved it by setting the plotly.io renderers to **iframe.**
> ```
> 
> `import plotly.io as pio` `pio.renderers.default='iframe'`
> 
> _Originally posted by @psyronika in [#764 (comment)](https://github.com/MaartenGr/BERTopic/issues/764#issuecomment-1271431205)_
> 
> I am using jupytrlab 4.2.5, and this code worked.
> 
> **import plotly.io as pio pio.renderers.default = "colab"** # 안 나오면 https://plotly.com/python/renderers/ 참조하여 렌더러 변경
> 
> topic_model.visualize_barchart(top_n_topics=len(topic_model.get_topic_info()))

You can render in Notebook this way. Thanks @kungmo
