### ISSUE TITLE
min_cluster_size and min_samples

### ISSUE THREAD

**Issue by Ariannaperla** [MaartenGr/BERTopic#340]
I'm working with 12k docs and I'm trying to modify parameters in order to suit my use case. I've worked with min_cluster_size parameter iteratively raising its value but, having obtained a lot (something as 6/7K) of docs classified as outliers, I read about  min_samples parameter that, correct me if I'm wrong, by default, it is set to the same value as min_cluster_size.
But my problem is that I can not get the correlation among these two parameters (min_cluster_size and min_samples) and therefore how I can obtain less outliers but keeping a good number of interpretable cluster.

**Comment by MaartenGr** [comment]
As a start, you can find a little bit more about those parameters [here](https://hdbscan.readthedocs.io/en/latest/faq.html#q-most-of-data-is-classified-as-noise-why). 

Using the link above you can start playing around with those values. A trick might be to lower `min_samples` iteratively and use `nr_topics=some_int` to reduce the resulting microclusters to a number of clusters that suit your use case. 

The problem though is that obtaining fewer outliers and keeping interpretable clusters do not go hand in hand. Whenever you add outliers to a cluster it gets muddled and the interpretation and quality of that cluster decreases. So make sure you do not try to remove all outliers as that may lead to strange results when trying to predict the topics of unseen documents.

**Comment by Ariannaperla** [comment]
Hello and thanks for your reply.
I read your tips about the selection of parameters and I started playing with them with my dataset. Playing with UMAP and HDBSCAN's parameters, knowing that there is no one-size-fits-all solution,  I was wondering: which are the default values - in BERTopic - for n_neighbors, n_components, min_dist and metric in UMAP?

**Comment by MaartenGr** [comment]
You can find the default parameters UMAP here:

https://github.com/MaartenGr/BERTopic/blob/15ea0cd804d35c1f11c6692f33c3666b648dd6c8/bertopic/_bertopic.py#L156-L160

and the default parameters of HDBSCAN here:

https://github.com/MaartenGr/BERTopic/blob/15ea0cd804d35c1f11c6692f33c3666b648dd6c8/bertopic/_bertopic.py#L163-L166

where `min_topic_size` is set to 10 and `low_memory` to False.

**Comment by MaartenGr** [comment]
Since this has not been active for a while now, I am going to close this issue. Having said that, to those that will read this issues, you can find more information about parameter tuning in the documentation [here](https://maartengr.github.io/BERTopic/getting_started/parameter%20tuning/parametertuning.html).
