### ISSUE TITLE
Key Error when transforming new documents

### ISSUE THREAD

**Issue by grainnecasey** [MaartenGr/BERTopic#352]
Hello, I was hoping you could help me debug this error I am getting when transforming new documents with BERTopic. I have been able to fit the model on a list of documents, but when finding topic probabilities/predictions on new documents, I periodically run into a key error with this error trace: 
`/usr/local/lib/python3.7/dist-packages/bertopic/_bertopic.py in transform(self, documents, embeddings)
    374 
    375         if self.calculate_probabilities:
--> 376             probabilities = hdbscan.membership_vector(self.hdbscan_model, umap_embeddings)
    377         else:
    378             probabilities = None

/usr/local/lib/python3.7/dist-packages/hdbscan/prediction.py in membership_vector(clusterer, points_to_predict)
    585             clusterer.condensed_tree_._raw_tree,
    586             clusterer.prediction_data_.leaf_max_lambdas,
--> 587             clusterer.prediction_data_.cluster_tree)
    588 
    589         result[i] = distance_vec ** 0.5 * outlier_vec ** 2.0

hdbscan/_prediction_utils.pyx in hdbscan._prediction_utils.outlier_membership_vector()

hdbscan/_prediction_utils.pyx in hdbscan._prediction_utils.outlier_membership_vector()

hdbscan/_prediction_utils.pyx in hdbscan._prediction_utils.per_cluster_scores()

KeyError: 28`

Do you know what this could mean? Would this be a problem with the documents I have, or an issue with the structure of the list? 

Thank you for your help!

**Comment by MaartenGr** [comment]
This is not an issue I am familiar with. However, could you share the code for training BERTopic and the code you used for making predictions? Also, which version of BERTopic are you using?

**Comment by grainnecasey** [comment]
[Here](https://gist.github.com/grainnecasey/18477dcfd5ddf98410aded167acbf122) is my code, with training starting around line 35 and predicting topics happening around line 91. 

I believe I am using version bertopic-0.9.3

**Comment by grainnecasey** [comment]
Thank you for that insight. I think you are correct, I do not have enough data to train on. I looked at the topic info for the models after training, and for the models that are failing, there is only the -1 topic, and the count of that topic is equal to the number from the key error. 

Thank you for the help!
