### ISSUE TITLE
probability predictions

### ISSUE THREAD

**Issue by aph61** [MaartenGr/BERTopic#353]
The use case is to predict probabilities of unknown sentences. For that I make a topic model according to 
```
sentence_model = SentenceTransformer("paraphrase-MiniLM-L6-v2", device="cpu")
topic_model = BERTopic(embedding_model=sentence_model,
                           n_gram_range=(1,1),
                           min_topic_size=100,
                           calculate_probabilities=True,
                           verbose=True)
topics, probabilities = topic_model.fit_transform(txt_to_fit)
```
After embedding, UMAP and clustering I have the following error
```
Batches: 100%
4484/4484 [28:53<00:00, 2.59it/s]

2021-12-02 16:41:35,851 - BERTopic - Transformed documents to Embeddings
2021-12-02 16:42:40,102 - BERTopic - Reduced dimensionality with UMAP
2021-12-02 16:45:31,219 - BERTopic - Clustered UMAP embeddings with HDBSCAN
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<timed exec> in <module>

~/.local/lib/python3.8/site-packages/pandas/core/frame.py in __init__(self, data, index, columns, dtype, copy)
    527 
    528         elif isinstance(data, dict):
--> 529             mgr = init_dict(data, index, columns, dtype=dtype)
    530         elif isinstance(data, ma.MaskedArray):
    531             import numpy.ma.mrecords as mrecords

~/.local/lib/python3.8/site-packages/pandas/core/internals/construction.py in init_dict(data, index, columns, dtype)
    285             arr if not is_datetime64tz_dtype(arr) else arr.copy() for arr in arrays
    286         ]
--> 287     return arrays_to_mgr(arrays, data_names, index, columns, dtype=dtype)
    288 
    289 

~/.local/lib/python3.8/site-packages/pandas/core/internals/construction.py in arrays_to_mgr(arrays, arr_names, index, columns, dtype, verify_integrity)
     83 
     84         # don't force copy because getting jammed in an ndarray anyway
---> 85         arrays = _homogenize(arrays, index, dtype)
     86 
     87         columns = ensure_index(columns)

~/.local/lib/python3.8/site-packages/pandas/core/internals/construction.py in _homogenize(data, index, dtype)
    353                     val = dict(val)
    354                 val = lib.fast_multiget(val, oindex._values, default=np.nan)
--> 355             val = sanitize_array(
    356                 val, index, dtype=dtype, copy=False, raise_cast_failure=False
    357             )

~/.local/lib/python3.8/site-packages/pandas/core/construction.py in sanitize_array(data, index, dtype, copy, raise_cast_failure)
    527     elif subarr.ndim > 1:
    528         if isinstance(data, np.ndarray):
--> 529             raise ValueError("Data must be 1-dimensional")
    530         else:
    531             subarr = com.asarray_tuplesafe(data, dtype=dtype)

ValueError: Data must be 1-dimensional
```
Running the code with ```calculate_probabilities=True``` runs smoothly; I also get the probabilities of training sentences. But in this case the sentences I'm interested in are not used to create the model. 

Anyone an idea where the magic goes wrong?

thanks,

Andreas

**Comment by MaartenGr** [comment]
Strange, this is not an issue I have seen before. Is this the entire trace? It seems it is not going to any direct place within BERTopic so understanding the issue might be difficult. 

Two things though, how many documents do you pass to BERTopic and why are you setting the device to cpu?

**Comment by aph61** [comment]
The datafile is 78MB, pickled, about 143474 lines. It's not a memory issue, I've 32G, and I've run larger datafiles (200k lines) without a hitch (but more patience). However, these computations were also done with ```calculate_probabilities=False```.

I ran the code again with ```calculate_probabilities=True``` (without ```device="cpu"```) but the result is the same value-error. After that I ran the code with ```calculate_probabilities=False``` and the routine completed successfully. The dump I showed is the complete dump.

PS: I vaguely recall I did run simulations with ```calculate_probabilities=True``` without problems. After that I needed to install some packages that do use pandas. My working hypothesis now is that it is a version error: your code works with pandas==1.3.2, not with 1.3.4 (the latest version). I will re-install pandas==1.3.2 and see how that works. I'll keep you updated

**Comment by aph61** [comment]
Unfortunately, downgrading pandas didn't help. The dump is 
```
Batches: 100%
4484/4484 [31:50<00:00, 2.35it/s]

2021-12-02 21:01:16,988 - BERTopic - Transformed documents to Embeddings
2021-12-02 21:02:40,243 - BERTopic - Reduced dimensionality with UMAP
2021-12-02 21:05:19,405 - BERTopic - Clustered UMAP embeddings with HDBSCAN
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<timed exec> in <module>

~/.local/lib/python3.8/site-packages/pandas/core/frame.py in __init__(self, data, index, columns, dtype, copy)
    612         elif isinstance(data, dict):
    613             # GH#38939 de facto copy defaults to False only in non-dict cases
--> 614             mgr = dict_to_mgr(data, index, columns, dtype=dtype, copy=copy, typ=manager)
    615         elif isinstance(data, ma.MaskedArray):
    616             import numpy.ma.mrecords as mrecords

~/.local/lib/python3.8/site-packages/pandas/core/internals/construction.py in dict_to_mgr(data, index, columns, dtype, typ, copy)
    462         # TODO: can we get rid of the dt64tz special case above?
    463 
--> 464     return arrays_to_mgr(
    465         arrays, data_names, index, columns, dtype=dtype, typ=typ, consolidate=copy
    466     )

~/.local/lib/python3.8/site-packages/pandas/core/internals/construction.py in arrays_to_mgr(arrays, arr_names, index, columns, dtype, verify_integrity, typ, consolidate)
    122 
    123         # don't force copy because getting jammed in an ndarray anyway
--> 124         arrays = _homogenize(arrays, index, dtype)
    125 
    126     else:

~/.local/lib/python3.8/site-packages/pandas/core/internals/construction.py in _homogenize(data, index, dtype)
    587                 val = lib.fast_multiget(val, oindex._values, default=np.nan)
    588 
--> 589             val = sanitize_array(
    590                 val, index, dtype=dtype, copy=False, raise_cast_failure=False
    591             )

~/.local/lib/python3.8/site-packages/pandas/core/construction.py in sanitize_array(data, index, dtype, copy, raise_cast_failure, allow_2d)
    575                 subarr = maybe_infer_to_datetimelike(subarr)
    576 
--> 577     subarr = _sanitize_ndim(subarr, data, dtype, index, allow_2d=allow_2d)
    578 
    579     if isinstance(subarr, np.ndarray):

~/.local/lib/python3.8/site-packages/pandas/core/construction.py in _sanitize_ndim(result, data, dtype, index, allow_2d)
    626             if allow_2d:
    627                 return result
--> 628             raise ValueError("Data must be 1-dimensional")
    629         if is_object_dtype(dtype) and isinstance(dtype, ExtensionDtype):
    630             # i.e. PandasDtype("O")

ValueError: Data must be 1-dimensional
```

**Comment by MaartenGr** [comment]
In that case, could you start from a completely fresh environment? There still might be some issues with dependencies not matching nicely and a fresh environment might resolve that.

**Comment by aph61** [comment]
Hi Maarten,

thanks, no problems in a virtual environment. I should have known that, earlier problems were also solved with that. You may want to include that in your installation instructions; often people try to get away with not using venvs, 

Thanks again,

Andreas

**Comment by aph61** [comment]
Hi Maarten,

thanks, no problems in a virtual environment. I should have known that, earlier problems were also solved with that. You may want to include that in your installation instructions; often people try to get away with not using venvs,

Thanks again,

Andreas

**Comment by aph61** [comment]
Unfortunately the new virtual environment didn't solve the problem. I made a CLI script of the notebook, and also here the computations gave an error message (see below). So still open
Andreas
![Selection_140](https://user-images.githubusercontent.com/22915035/144631435-b0a46f1e-cab6-468a-bb2f-d436ea734f78.png)

**Comment by MaartenGr** [comment]
It seems that we will have to dig a little deeper. Could you share the code you have been using for instantiating BERTopic and what you do with it afterward? 

Also, in the traceback, I see the code `df_topics_certainty = pd.DataFrame{("topic": topics`, is that code that you used anywhere? I cannot find the usage of it anywhere within BERTopic.

**Comment by aph61** [comment]
Hi,

I debugged a bit more, and this is this is the relevant snippet
```
topics, certainty = topic_model.fit_transform(txt_to_fit)

df_topics_certainty = pd.DataFrame({"topic": topics,
                                    "certainty": certainty})
```
The line where it went haywire is not in your code, but in
```
df_topics_certainty = pd.DataFrame({"topic": topics, certainty": certainty})
```
I did not realize that ```certainty``` is a numpy 2D-array, not a list. And you can't put a numpy array in a data frame (apparently) I'm now working to make  a better data structure, but I think the problem is solved.

thanks for your time, 

Andreas

**Comment by MaartenGr** [comment]
No problem! Glad to hear that the problem is solved.
