### ISSUE TITLE
Guided BERTopic

### ISSUE THREAD

**Issue by sumedha05** [MaartenGr/BERTopic#355]
Hi Maarten,

First of all, thanks for this excellent work of yours. 

I need some help related to text classification.
I have a collection of news articles corresponding to 11 labels, and I wish to use BERTopic to make prediction of label for similar news articles. Is it possible to use Guided BERTopic for the same, i.e. I am planning to provide key-words for those 11 labels to Guided BERTopic in the training phase to give hints about the type of labels we have?

Correct me if I am wrong with my concept of Guided BERTopic. 

Thanks in advance.

**Comment by MaartenGr** [comment]
Thank you for the kind words!

Yes, you can use Guided BERTopic to push the topic creation a bit more towards the labels that you have created, especially if those labels have several keywords associated with them. Also, you can use semi-supervised BERTopic to directly use the labels when training the model. 

Having said that, BERTopic is not necessarily meant for text classification but more for finding topics in the text. They are similar use cases but you might get better results by training a supervised classifier than using a semi-supervised topic modeling technique like BERTopic. 

Does this answer your questions?

**Comment by MaartenGr** [comment]
Due to inactivity, I am going to close this issue. If you want to discuss this issue further let me know and I'll reopen it!
