### ISSUE TITLE
Where are the SentenceTransformers embeddings stored? How can I retrieve them for all the documents?

### ISSUE THREAD

**Issue by oq-9** [MaartenGr/BERTopic#358]
Where are the SentenceTransformers embeddings stored? How can I retrieve them for all the documents?

**Comment by MaartenGr** [comment]
The embeddings are not stored in BERTopic. Doing so would take up too much space when saving BERTopic. You can, however, embed the documents yourself and pass them to BERtopic as described [here](https://maartengr.github.io/BERTopic/tutorial/embeddings/embeddings.html#custom-embeddings).

**Comment by oq-9** [comment]
Perfect!! Thank you so much
