### ISSUE TITLE
Generating embeddings beforehand

### ISSUE THREAD

**Issue by anderslangballe** [MaartenGr/BERTopic#359]
Hi,

In the FAQ, under how one can increase the speed of BERTopic, it says that using pre-generated embeddings is not advised.

I can see some downsides to these pre-generated embeddings, e.g. if you change/adapt the underlying model, but why is this not advised in particular? Thanks!

**Comment by MaartenGr** [comment]
Good question! This is actually something that will be changed in v0.9.4 as this does not hold anymore. I made some stability changes a few releases ago that circumvents the issue of using pre-generated embeddings and their effect on the MMR representation. In other words, go ahead and use them as much as you'd like! 

One note though, make sure to also then supply an embedding model through `embedding_model=my_embedding_model` as that will allow you to use all functions of BERTopic.
