### ISSUE TITLE
load gensim doc2vec model

### ISSUE THREAD

**Issue by jmichellec** [MaartenGr/BERTopic#364]
Is there a possibility to load a gensim not pretrained doc2vec model that is saved locally (to compare the outcome words with top2vec)?
If I currently load my own model with: `trained_model = Doc2Vec.load("d2v.model")`

I get:
ValueError: Please select a correct Gensim model: 
`import gensim.downloader as api` 
`ft = api.load('fasttext-wiki-news-subwords-300')`

**Comment by MaartenGr** [comment]
Yes and no! At the moment, BERTopic only support `Word2VecKeyedVectors` directly from the Gensim library. This indeed means that you can only use `api.load()` as an embedding model in BERTopic. However, you can use your trained embedding model to generate the document embeddings instead and give those to BERTopic:

```python
topic_model = BERTopic()
topics, probs = topic_model.transform(docs, my_embeddings)
```

I would, however, advise using a sentence-transformer model as that typically results in better results.
