### ISSUE TITLE
setting HDBSCAN and UMAP parameters 

### ISSUE THREAD

**Issue by Ariannaperla** [MaartenGr/BERTopic#368]
Hi Maarten,
I'm working with two dataset: the first one is made of 12500 docs and the second one is made of 85000 docs. The docs are quite short especially in the second dataset. On the basis of the size of these two dataset, I was wondering which values for HDBSCAN and UMAP parameters might be the best. 
Any suggestions?
Thanks in advance

**Comment by MaartenGr** [comment]
It is very difficult to advise on parameters as it highly depends on the use case and even then it might require some experimentation. How many topics do you want? How big do you want your clusters? How do you define "best"? Is that the topic coherence, quality, diversity, or something else? Etc. 

I would advise reading through the `parameter tuning` section of the documentation [here](https://maartengr.github.io/BERTopic/getting_started/parameter%20tuning/parametertuning.html) as it goes through important parameters of BERTopic, HDBSCAN, and UMAP.

**Comment by MaartenGr** [comment]
The last response is a while ago, so I am going to close this for now. However, if this issue is not yet resolved let me know and I'll reopen the issue to see if we can figure this out.
