### ISSUE TITLE
Widget Javascript not detected

### ISSUE THREAD

**Issue by aph61** [MaartenGr/BERTopic#369]
Hi,
on a new server, new virtual environment I installed bertopic, and took care of the numpy/numba problem. When executing the code 

`sentence_model = SentenceTransformer("paraphrase-MiniLM-L6-v2")`

the response (local, full dump below). 

> `Widget Javascript not detected.  It may not be installed or enabled properly.
> 
> AttributeError                            Traceback (most recent call last)
> <timed exec> in <module>
> 
> ~/.local/lib/python3.8/site-packages/sentence_transformers/SentenceTransformer.py in __init__(self, model_name_or_path, modules, device, cache_folder)

and remote

> On the server side the [IPKernelApp] ERROR | No such comm target registered: jupyter.widget.version
> [IPKernelApp] WARNING | Widget Javascript not detected.  It may not be installed or enabled properly.

The environment was a jupyter instance on the AWS cloud started with 

`jupyter nbextension enable --py --sys-prefix widgetsnbextension`
`jupyter notebook --no-browser --ip=127.0.0.1 --port=8891` (remote) and
`ssh -N -f -L localhost:8890:localhost:8890 ubuntu@xxx.amazonaws.com` (local)

Suggestions? 

Thanks,

Andreas

---
Full dump

`Widget Javascript not detected.  It may not be installed or enabled properly.

AttributeError                            Traceback (most recent call last)
<timed exec> in <module>

~/.local/lib/python3.8/site-packages/sentence_transformers/SentenceTransformer.py in __init__(self, model_name_or_path, modules, device, cache_folder)`

     78 
     79                 # Download from hub with caching
---> 80                 snapshot_download(model_name_or_path,
     81                                     cache_dir=cache_folder,
     82                                     library_name='sentence-transformers',

~/.local/lib/python3.8/site-packages/sentence_transformers/util.py in snapshot_download(repo_id, revision, cache_dir, library_name, library_version, user_agent, ignore_files)
    452         os.makedirs(nested_dirname, exist_ok=True)
    453 
--> 454         path = cached_download(
    455             url,
    456             cache_dir=storage_folder,

~/.local/lib/python3.8/site-packages/huggingface_hub/file_download.py in cached_download(url, library_name, library_version, cache_dir, user_agent, force_download, force_filename, proxies, etag_timeout, resume_download, use_auth_token, local_files_only)
    465             logger.info("downloading %s to %s", url, temp_file.name)
    466 
--> 467             http_get(
    468                 url_to_download,
    469                 temp_file,

~/.local/lib/python3.8/site-packages/huggingface_hub/file_download.py in http_get(url, temp_file, proxies, resume_size, headers, timeout, max_retries)
    275     content_length = r.headers.get("Content-Length")
    276     total = resume_size + int(content_length) if content_length is not None else None
--> 277     progress = tqdm(
    278         unit="B",
    279         unit_scale=True,

~/.local/lib/python3.8/site-packages/tqdm/notebook.py in __init__(self, *args, **kwargs)
    247             self.displayed = True
    248         self.disp = self.display
--> 249         self.colour = colour
    250 
    251         # Print initial bar state

~/.local/lib/python3.8/site-packages/tqdm/notebook.py in colour(self, bar_color)
    206     def colour(self, bar_color):
    207         if hasattr(self, 'container'):
--> 208             self.container.children[-2].style.bar_color = bar_color
    209 
    210     def __init__(self, *args, **kwargs):

AttributeError: 'FloatProgress' object has no attribute 'style'`

**Comment by MaartenGr** [comment]
It seems that this is an issue with `tqdm` not properly loading the progress bar in your environment. Although I am not familiar with this issue, there seem to be some things you can try [here](https://github.com/NVIDIA-AI-IOT/trt_pose/issues/77) and [here](https://githubmemory.com/repo/tqdm/tqdm/issues/1156). Hopefully, this helps!

**Comment by aph61** [comment]
The problem is solved. There was a version mismatch on the AWS python and your code. 
Upgrading solved the problem

`pip install --upgrade ipywidgets 
`
