### ISSUE TITLE
 issue due to the _plotly_topic_visualization() method

### ISSUE THREAD

**Issue by Amine-OMRI** [MaartenGr/BERTopic#37]
there is an issue related to the **_plotly_topic_visualization()** method.
python 3.x, d.keys() returns an iterator (not an iterator), so giving a dictionary to the hove_data parameter when creating the **fig** will cause an error.
here is the code:
```
# plotting subjects
        fig = px.scatter(df, x="x", y="y", size="Size", size_max=40, template="simple_white", labels={"x": "", "y": ""},
                         hover_data={"x": False, "y": False, "Subject": True, "Words": True, "Size": True})
```
To solve this problem, simply use a list () :
```
# Plotting topics
        fig = px.scatter(df, x="x", y="y", size="Size", size_max=40, template="simple_white", labels={"x": "", "y": ""},
                         hover_data=list({"x": False, "y": False, "Topic": True, "Words": True, "Size": True}))
```

**Comment by MaartenGr** [comment]
What is exactly the error you are getting? What code did you run that gave you this error? I am not getting any issues with running `_plotly_topic_visualization` unless the number of topics is really low (<3).

**Comment by Amine-OMRI** [comment]
The error occurred on Colab since it uses Python 3.6
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-8-97974c2b045c> in <module>()
----> 1 model.visualize_topics()

5 frames
/usr/local/lib/python3.6/dist-packages/plotly/express/_core.py in build_dataframe(args, attrables, array_attrables)
    911         # argument_list and field_list ready, iterate over them
    912         # Core of the loop starts here
--> 913         for i, (argument, field) in enumerate(zip(argument_list, field_list)):
    914             length = len(df_output)
    915             if argument is None:

RuntimeError: dictionary changed size during iteration
```

**Comment by MaartenGr** [comment]
Could you share the exact code that you used? It helps if I can understand the context in which you ran `model.visualize_topics()` so that I can more easily figure out what is going wrong.

**Comment by Amine-OMRI** [comment]
Just running this on Colab
```
!pip install bertopic
from bertopic import BERTopic
from sklearn.datasets import fetch_20newsgroups
docs = fetch_20newsgroups(subset='all',  remove=('headers', 'footers', 'quotes'))['data']
model = BERTopic(language="english")
topics, probs = model.fit_transform(docs)
model.visualize_topics()
```

**Comment by MaartenGr** [comment]
Ah! You should use ```!pip install bertopic[visualization]``` instead. Plotly needs to be at least `4.7.0` otherwise this will not work.

**Comment by Amine-OMRI** [comment]
Thank you, it works fine now, I'm working on French data and I tested multilingual models like **distiller-based-multilingual-cased**
and I also tested **bert-base-nli-stsb-mean-tokens**.
I found that bert-base-nli-stsb-mean-tokens was well on the French data knowing that this model was not pre-trained on French data; it was only pre-trained on English data.
what do you think and what do you suggest as a model for Frenche data?

**Comment by MaartenGr** [comment]
Great, glad to hear that it works now! 

If the `bert-base-nli-stsb-mean-token` worked quite well on your data, then it might be interesting to try out `stsb-xlm-r-multilingual` as it is a multi-lingual version of the former. Other than that, I have had good success with `paraphrase-xlm-r-multilingual-v1`.

**Comment by Amine-OMRI** [comment]
Ok, I'm going to try them and see wich one perform well, again thank you.
