### ISSUE TITLE
The result for same data set is not equivalent between fit and transform for same saved model.

### ISSUE THREAD

**Issue by sanjugahara** [MaartenGr/BERTopic#370]
Hi Maarten,
Thank you for building this gorgeous project and your dedication! We are trying to use BERTopic in a practice. And our purpose is sth like the 5th option as described in: https://github.com/MaartenGr/BERTopic/issues/354 
While what we are doing right now is:
1. Using a training data set to fit the model and save it to a local path along with the embedding model. We even set a umap model for reducing the stochastisch. 
2. And then we load the trained model again and trying to use the same training data set to run a transform(). 

However, the outcome clusters seems does not match between the fit() and transform() for the same dataset and same model. It 
concerns us that transform() on new documents would not fall into any of the old clusters for the training data set.  
Could you share any advise on this?  

Thank you in advance!

**Comment by MaartenGr** [comment]
Thank you for your kind words! I can imagine this is frustrating! 

I just tried to replicate the issue that you are having but so far I did not succeed. I ran the following code:

```python
from sklearn.datasets import fetch_20newsgroups
from sentence_transformers import SentenceTransformer
from bertopic import BERTopic
from umap import UMAP

# Prepare embeddings
docs = fetch_20newsgroups(subset='all',  remove=('headers', 'footers', 'quotes'))['data']
sentence_model = SentenceTransformer("all-MiniLM-L6-v2")
embeddings = sentence_model.encode(docs, show_progress_bar=False)

# Set the random state in the UMAP model to prevent stochastic behavior 
umap_model = UMAP(n_neighbors=15, n_components=5, 
                  min_dist=0.0, metric='cosine', random_state=42)

# Train model
topic_model = BERTopic(umap_model=umap_model, verbose=True)
topics, probs = topic_model.fit_transform(docs, embeddings)

# Transform same documents and check if the predicted topics are the same
new_topics, new_probs = topic_model.transform(docs, embeddings)
assert topics == new_topics
```

Did you make sure to set a `random_state` in UMAP to control for stochastic behavior?

**Comment by sanjugahara** [comment]
Hi Maarten,
Thank you so much for the reply! Yes we did use random_state=42 for the umap model. The only difference between your code and ours is we are doing a save and load between 2 runs. Do you think that would affect the result? Thank you again and do appreciate your help in this case!

**Comment by MaartenGr** [comment]
There is a small chance that the `approximate_predict` of HDBSCAN will not entirely be the same between runs but it should not be significant. I also tried with saving and loading the model in between and I did not replicate your issue:

```python
from sklearn.datasets import fetch_20newsgroups
from sentence_transformers import SentenceTransformer
from bertopic import BERTopic
from umap import UMAP

# Prepare embeddings
docs = fetch_20newsgroups(subset='all',  remove=('headers', 'footers', 'quotes'))['data']
sentence_model = SentenceTransformer("all-MiniLM-L6-v2")
embeddings = sentence_model.encode(docs, show_progress_bar=False)

# Set the random state in the UMAP model to prevent stochastic behavior 
umap_model = UMAP(n_neighbors=15, n_components=5, 
                  min_dist=0.0, metric='cosine', random_state=42)

# Train model
topic_model = BERTopic(umap_model=umap_model, verbose=True)
topics, probs = topic_model.fit_transform(docs, embeddings)

# Transform same documents and check if the predicted topics are the same
new_topics, new_probs = topic_model.transform(docs, embeddings)
assert topics == new_topics

# Save and load model
topic_model.save("my_model")
my_model = BERTopic.load("my_model")
new_topics, new_probs = my_model.transform(docs, embeddings)
assert topics == new_topics
```

Which version of BERTopic are you using? I remember that earlier versions had issues with the `.transform()` function that should be fixed in the newest release.

**Comment by MaartenGr** [comment]
There is a small chance that the `approximate_predict` of HDBSCAN will not entirely be the same between runs but it should not be significant. I also tried with saving and loading the model in between and I did not replicate your issue:

```python
from sklearn.datasets import fetch_20newsgroups
from sentence_transformers import SentenceTransformer
from bertopic import BERTopic
from umap import UMAP

# Prepare embeddings
docs = fetch_20newsgroups(subset='all',  remove=('headers', 'footers', 'quotes'))['data']
sentence_model = SentenceTransformer("all-MiniLM-L6-v2")
embeddings = sentence_model.encode(docs, show_progress_bar=False)

# Set the random state in the UMAP model to prevent stochastic behavior 
umap_model = UMAP(n_neighbors=15, n_components=5, 
                  min_dist=0.0, metric='cosine', random_state=42)

# Train model
topic_model = BERTopic(umap_model=umap_model, verbose=True)
topics, probs = topic_model.fit_transform(docs, embeddings)

# Transform same documents and check if the predicted topics are the same
new_topics, new_probs = topic_model.transform(docs, embeddings)
assert topics == new_topics

# Save and load model
topic_model.save("my_model")
my_model = BERTopic.load("my_model")
new_topics, new_probs = my_model.transform(docs, embeddings)
assert topics == new_topics
```

Which version of BERTopic are you using? I remember that earlier versions had issues with the `.transform()` function that should be fixed in the newest release.

**Comment by sanjugahara** [comment]
Oh Good point! We are on a 0.70 version and I do see you have updates for load in Version 0.9 and transform in 0.93. I think may be thats the reason?

**Comment by MaartenGr** [comment]
Yes! That might be the reason that you are finding inconsistent results. I would definitely advise making use of the most recent version as they often involve a bunch of fixes that users find.

**Comment by MaartenGr** [comment]
Due to inactivity, I am going to close this issue for now. Let me know if you want to discuss this further and I'll make sure to reopen the issue.
