### ISSUE TITLE
Issues loading glove-twitter-embedding

### ISSUE THREAD

**Issue by neel6762** [MaartenGr/BERTopic#371]
Hello, I came across this wonderful project while completing a study and I am stuck at this point. I am basically trying to load the glove-twitter-50d data using gensim, but it throws the following error.

Code : 
<img width="509" alt="image" src="https://user-images.githubusercontent.com/38160394/146272748-6169099b-5bfa-4405-b6bc-f7901d1c7922.png">

Error:
<img width="847" alt="image" src="https://user-images.githubusercontent.com/38160394/146272947-79b181cf-0db2-47ca-856f-3cb9cabe0d01.png">

I was not sure, so didn't touch the original code.

Any help would be really appreciated.
Thank you!

**Comment by MaartenGr** [comment]
It seems that you are using Gensim 4.0.0 whilst I only accounted for Gensim<4.0.0 since they changed the way you access the resulting embeddings. For now, I would advise lowering your Gensim version:

```
pip install --upgrade gensim==3.8.3
```

I will put this on the to-do list for a future version 😄

**Comment by neel6762** [comment]
Thank you for your reply, this never striked my mind 😅.

**Comment by neel6762** [comment]
Also, I was wondering by any chance are the topics returned by BERTopic sorted in a manner such that the first topic is the most relevant. Suppose, I get a list of 40 topics from the topic model, is there any chance that the first few topics are the most relevant. Thank you !

**Comment by MaartenGr** [comment]
Yes! Topic 0 appears more frequently in the data than topic 1 and topic 1 more than 2, etc. If you run `topic_model.get_topic_info()` you will also see a sorted list of topics together with their frequencies and their topic representations.

**Comment by neel6762** [comment]
Thank you so much Maarten.
