### ISSUE TITLE
ERROR: No matching distribution found for bertopic==0.9.4

### ISSUE THREAD

**Issue by dibsandy** [MaartenGr/BERTopic#373]
Hi @MaartenGr 

Thank You so much for this, It really helps a lot. I wanna use guided topic modelling for one of my project. But I noticed it is not available bertopic version==0.6.0. As when I am looking into the arguments we can pass in the model, I am not seeing "seed_topic_list". I believe it release after 0.6.0 version. But when I am trying to install the bertopic version==0.9.4 In order to use the guided modeling feature it gives me error "ERROR: No matching distribution found for bertopic==0.9.4". When I install the bertopic using "pip install bertopic" by default it installed the 0.6.0 version but I am not able to upgrade it to 0.9.4. Can you please help me.

Below is the image of the error which I am getting while installing the newer verision
![image](https://user-images.githubusercontent.com/96224663/146319312-49738509-0d13-405d-9437-6819fed5c04d.png)
 
And below is the error when I tried to use seed_topic_list as argument in bertopic version==0.6.0
![image](https://user-images.githubusercontent.com/96224663/146319570-a8136b49-3f42-496c-933d-0234dd84d90e.png)

Do let me if you need any other information from my end in order to understand the issue.

**Comment by MaartenGr** [comment]
Hmmm, if you cannot download that specific version of BERTopic that I believe one of two things might be happening here. Either there is an issue with pip not finding the package (although it definitely works for me in multiple environments) or you are working in Python 3.6 which is not supported anymore. Which python version are you currently using?

**Comment by dibsandy** [comment]
Thank you @MaartenGr. I checked and noticed I was using python 3.6 and when I tried the same on python 3.7 it worked without any issue. Thank You so much :-)
