### ISSUE TITLE
AttributeError: 'UMAP' object has no attribute 'tqdm_kwds'

### ISSUE THREAD

**Issue by DSTeamTsteps** [MaartenGr/BERTopic#374]
Hi,
loading my model:
model_2 = BERTopic.load("My_Model_Name", embedding_model="multi-qa-MiniLM-L6-cos-v1")
Using below code for getting the topics with my new dataset
topics, probabilities = model_2.transform(docs)

Error: AttributeError: 'UMAP' object has no attribute 'tqdm_kwds'
I am getting this error, Please help me to resolve this

**Comment by MaartenGr** [comment]
It seems that there is an issue with the UMAP package. Could you try installing BERTopic in a fresh environment? Also, did you make sure that the package versions are the same between saving and loading the model? Lastly, perhaps removing UMAP and re-installing it might resolve your issue.

**Comment by DSTeamTsteps** [comment]
Thank you MaartenGr,
After downgrading the umap-learn version, it is working fine.
Thanks a lot for all your support

**Comment by actopozipc** [comment]
> After downgrading the umap-learn version, it is working fine.

Any more details on this? Which umap-learn version caused this, which downgraded version fixed this? I am running into the same problem with umap-learn==0.5.9.post2  
**Edit: This doesnt seem to happen for umap-learn-0.5.1**
