### ISSUE TITLE
Task has failed to un-serialize HDBSCAN

### ISSUE THREAD

**Issue by aph61** [MaartenGr/BERTopic#375]
Hi,

I ran into the following problem on a remote server,

> _RemoteTraceback                          Traceback (most recent call last)
> _RemoteTraceback: 
> """
> Traceback (most recent call last):
>   File "/home/ubuntu/bertopic/bt-env-deb/lib/python3.8/site-packages/joblib/externals/loky/process_executor.py", line 407, in _process_worker
>     call_item = call_queue.get(block=True, timeout=timeout)
>   File "/usr/lib/python3.8/multiprocessing/queues.py", line 116, in get
>     return _ForkingPickler.loads(res)
>   File "sklearn/neighbors/_binary_tree.pxi", line 1057, in sklearn.neighbors._kd_tree.BinaryTree.__setstate__
>   File "sklearn/neighbors/_binary_tree.pxi", line 999, in sklearn.neighbors._kd_tree.BinaryTree._update_memviews
>   File "stringsource", line 658, in View.MemoryView.memoryview_cwrapper
>   File "stringsource", line 349, in View.MemoryView.memoryview.__cinit__
> ValueError: buffer source array is read-only
> """

It appears to have to do with pickling/unpickling sth, and that's pretty deep in the code. Suggestions how to solve this one?

thanks,

Andreas

--- full dump ---

The above exception was the direct cause of the following exception:

BrokenProcessPool                         Traceback (most recent call last)
/tmp/ipykernel_230698/3434862483.py in <module>
      2 # Calculate new topic_ids etc. The data in df_content have to be overwritten
      3 #
----> 4 topics, probability_distribution = topic_model.fit_transform(txt_to_fit)
      5 #
      6 #

~/bertopic/bt-env-deb/lib/python3.8/site-packages/bertopic/_bertopic.py in fit_transform(self, documents, embeddings, y)
    299 
    300         # Cluster UMAP embeddings with HDBSCAN
--> 301         documents, probabilities = self._cluster_embeddings(umap_embeddings, documents)
    302 
    303         # Sort and Map Topic IDs by their frequency

~/bertopic/bt-env-deb/lib/python3.8/site-packages/bertopic/_bertopic.py in _cluster_embeddings(self, umap_embeddings, documents)
   1395             probabilities: The distribution of probabilities
   1396         """
-> 1397         self.hdbscan_model.fit(umap_embeddings)
   1398         documents['Topic'] = self.hdbscan_model.labels_
   1399         probabilities = self.hdbscan_model.probabilities_

~/bertopic/bt-env-deb/lib/python3.8/site-packages/hdbscan/hdbscan_.py in fit(self, X, y)
    917          self._condensed_tree,
    918          self._single_linkage_tree,
--> 919          self._min_spanning_tree) = hdbscan(X, **kwargs)
    920 
    921         if self.prediction_data:

~/bertopic/bt-env-deb/lib/python3.8/site-packages/hdbscan/hdbscan_.py in hdbscan(X, min_cluster_size, min_samples, alpha, cluster_selection_epsilon, metric, p, leaf_size, algorithm, memory, approx_min_span_tree, gen_min_span_tree, core_dist_n_jobs, cluster_selection_method, allow_single_cluster, match_reference_implementation, **kwargs)
    608                                            gen_min_span_tree, **kwargs)
    609             else:
--> 610                 (single_linkage_tree, result_min_span_tree) = memory.cache(
    611                     _hdbscan_boruvka_kdtree)(X, min_samples, alpha,
    612                                              metric, p, leaf_size,

~/bertopic/bt-env-deb/lib/python3.8/site-packages/joblib/memory.py in __call__(self, *args, **kwargs)
    347 
    348     def __call__(self, *args, **kwargs):
--> 349         return self.func(*args, **kwargs)
    350 
    351     def call_and_shelve(self, *args, **kwargs):

~/bertopic/bt-env-deb/lib/python3.8/site-packages/hdbscan/hdbscan_.py in _hdbscan_boruvka_kdtree(X, min_samples, alpha, metric, p, leaf_size, approx_min_span_tree, gen_min_span_tree, core_dist_n_jobs, **kwargs)
    273 
    274     tree = KDTree(X, metric=metric, leaf_size=leaf_size, **kwargs)
--> 275     alg = KDTreeBoruvkaAlgorithm(tree, min_samples, metric=metric,
    276                                  leaf_size=leaf_size // 3,
    277                                  approx_min_span_tree=approx_min_span_tree,

hdbscan/_hdbscan_boruvka.pyx in hdbscan._hdbscan_boruvka.KDTreeBoruvkaAlgorithm.__init__()

hdbscan/_hdbscan_boruvka.pyx in hdbscan._hdbscan_boruvka.KDTreeBoruvkaAlgorithm._compute_bounds()

~/bertopic/bt-env-deb/lib/python3.8/site-packages/joblib/parallel.py in __call__(self, iterable)
   1054 
   1055             with self._backend.retrieval_context():
-> 1056                 self.retrieve()
   1057             # Make sure that we get a last message telling us we are done
   1058             elapsed_time = time.time() - self._start_time

~/bertopic/bt-env-deb/lib/python3.8/site-packages/joblib/parallel.py in retrieve(self)
    933             try:
    934                 if getattr(self._backend, 'supports_timeout', False):
--> 935                     self._output.extend(job.get(timeout=self.timeout))
    936                 else:
    937                     self._output.extend(job.get())

~/bertopic/bt-env-deb/lib/python3.8/site-packages/joblib/_parallel_backends.py in wrap_future_result(future, timeout)
    540         AsyncResults.get from multiprocessing."""
    541         try:
--> 542             return future.result(timeout=timeout)
    543         except CfTimeoutError as e:
    544             raise TimeoutError from e

/usr/lib/python3.8/concurrent/futures/_base.py in result(self, timeout)
    442                     raise CancelledError()
    443                 elif self._state == FINISHED:
--> 444                     return self.__get_result()
    445                 else:
    446                     raise TimeoutError()

/usr/lib/python3.8/concurrent/futures/_base.py in __get_result(self)
    387         if self._exception:
    388             try:
--> 389                 raise self._exception
    390             finally:
    391                 # Break a reference cycle with the exception in self._exception

BrokenProcessPool: A task has failed to un-serialize. Please ensure that the arguments of the function are all picklable.

**Comment by MaartenGr** [comment]
This might be a result of an [issue](https://github.com/MaartenGr/BERTopic/issues/151) within HDBSCAN that is currently not yet released in PyPi. However, you can install the latest version from the main branch: 

```
pip install --upgrade git+https://github.com/scikit-learn-contrib/hdbscan
```

Hopefully, this fixes your issue!

**Comment by aph61** [comment]
Hi,

thanks for the pointer. I did as you suggested, and it solved this specific problem and a few more (5+ problems)

**Comment by MaartenGr** [comment]
Glad to hear that it solved the issue!
