### ISSUE TITLE
visualize_topics () returns the error "ValueError: zero-size array to reduction operation maximum which has no identity"

### ISSUE THREAD

**Issue by felipelopezp726** [MaartenGr/BERTopic#378]
Hi MaartenGr, first of all, thank you for the implementation of BERTopic!

I am using the BERTopic model and when I try to visualize the topics with the "visualize_topics" function I get the following error: "ValueError: zero-size array to reduction operation maximum which has no identity". Here is the part of the code I use:

topic_model = BERTopic(embedding_model='distiluse-base-multilingual-cased-v2',
                      calculate_probabilities=False,
                      low_memory=True,
                      verbose=False,
                      nr_topics=10
                      )
topics = topic_model.fit_transform(docs)   
fig = topic_model.visualize_topics()

I have not been able to find the solution, as there is no discussion on this topic. I hope you can help me, thank you!

**Comment by MaartenGr** [comment]
Which version of BERTopic are you using? Also, could you share the versions of Numpy, UMAP, HDBSCAN, and Plotly?

I just tried it out in a fresh environment and I am not able to replicate your issue:

```python
from bertopic import BERTopic
from sklearn.datasets import fetch_20newsgroups

docs = fetch_20newsgroups(subset='all',  remove=('headers', 'footers', 'quotes'))['data']

topic_model = BERTopic(embedding_model='distiluse-base-multilingual-cased-v2',
                       calculate_probabilities=False,
                       low_memory=True,
                       verbose=False,
                       nr_topics=10)
topics, probs = topic_model.fit_transform(docs)
fig = topic_model.visualize_topics()
```
Note that it should be `topics, probs = topic_model.fit_transform(docs)` instead of `topics = topic_model.fit_transform(docs)` as two variables are returned.

**Comment by felipelopezp726** [comment]
Hi MaartenGr, thanks for the prompt reply.

I am using the versions:
BERTopic: 0.9.4
Numpy: 1.20.3
UMAP: 0.5.2
HDBSCAN: It was not possible to find the version of this library.
Plotly: 5.4.0

I was investigating, testing with different databases and it seems that the problem occurs when I have a small database (less than five hundred documents), as you mention in this [issue](https://github.com/MaartenGr/BERTopic/issues/110) For example, when I test the algorithm with databases containing at least a thousand documents, the problem does not occur.

I have corrected the line of code:` topics, probs = topic_model.fit_transform(docs)`, thanks!

Please let me know if the error may be due to document size or library versions or what the error is due to,

**Comment by MaartenGr** [comment]
Ah yes, then it is most likely that the dataset was too small. It might also be fixed by setting a much smaller `min_topic_size` as too few topics might be created. It indeed does not seem to be due to the packages but merely the size of the data that you are using.
