### ISSUE TITLE
No graphs in Jupyter Lab

### ISSUE THREAD

**Issue by eliassz** [MaartenGr/BERTopic#379]
Hi! Nice work! Thx! But...I don't have graphs when use methods visualize_topics(), visualize_barchart(). Work in Jupyter Lab. It looks like this on pic.
<img width="701" alt="Снимок экрана 2021-12-20 в 5 26 05 PM" src="https://user-images.githubusercontent.com/62444495/146782360-553d7d54-8c8d-4385-8b16-1199c337a398.png">

**Comment by eliassz** [comment]
Please help!

**Comment by MaartenGr** [comment]
Most likely your installation of Jupyter Lab does not support Plotly yet. I would advise following the guide [here](https://plotly.com/python/getting-started/#jupyterlab-support) to allow for plotly output in jupyter.

**Comment by eliassz** [comment]
Thank you sooo much! It works!
