### ISSUE TITLE
visualize_topics() not returning the value of "Words" and "Size"

### ISSUE THREAD

**Issue by shsh88** [MaartenGr/BERTopic#39]
When trying the same example posted, visualize_topics()  returns a visualization that for each cluster shows the following when hovering over it:

Words:%{customdata[3]}
Size:%{customdata[4]}

**Comment by MaartenGr** [comment]
Hmmm, that's strange! Have you installed BERTopic with `pip install bertopic[visualisation]`? It might be an issue with your plotly version.

**Comment by shsh88** [comment]
Yes, I did install it. I'll check my plotly version.

**Comment by ClaudiaSchulz** [comment]
I had the same issue - downgrading plotly from 4.14.3 to 4.7.0 fixed it.

**Comment by MaartenGr** [comment]
Like @ClaudiaSchulz said, turns out it is an issue with the newest version of Plotly. For now, either downgrade or install BERTopic v0.4.3 as I fixed the plotly version in setup.py. Thus, simply upgrade with `pip install --upgrade bertopic`.
