### ISSUE TITLE
Help with error trying to run semi supervised data 

### ISSUE THREAD

**Issue by Terela62** [MaartenGr/BERTopic#393]
Hi thanks for your work on this project to date. 
I am trying to load labelled data from a csv file. This consists of adding two columns and assigning target and target names in Libre Office (had trouble with saving with utf-8 in excel). Having got it into a dataframe I am treating it as per your help section on semi-supervised data. (https://maartengr.github.io/BERTopic/getting_started/supervised/supervised.html)
 
I am getting the following error regarding flo

```
~\anaconda3\lib\site-packages\sentence_transformers\models\Transformer.py in tokenize(self, texts)
     85             batch1, batch2 = [], []
     86             for text_tuple in texts:
---> 87                 batch1.append(text_tuple[0])
     88                 batch2.append(text_tuple[1])
     89             to_tokenize = [batch1, batch2]

TypeError: 'float' object is not subscriptable
```
I am using the custom the sub-models method for greater control of clustering

```
sentence_model = SentenceTransformer('sentence-transformers/all-MiniLM-L6-v2')
topic_model = BERTopic(embedding_model=sentence_model,
                       umap_model=umap_model, 
                       hdbscan_model=hdbscan_model, 
                       vectorizer_model=vectorizer_model,
                      top_n_words=5,verbose=True).fit(docs,y=y1)
```
I have had to manipulate the data frame columns to emulate the input of the 20_newsgroups data as follows and things ive tried to get rid of any floats... :-/
```
docs = tweets_df['Doc'].tolist()
categories = tweets_df["Target"]
category_names = tweets_df["Target_Names"]

labels_to_add = category_names.dropna().unique().tolist() #convert full list of categories to unique values and dropping the NaN
y = [int(label) if label in indices else -1 for label in categories] #using int() to convert from float taken from csv 
y1=np.array([np.array(xi) for xi in y]) # to convert y list to numpy.ndarray
```
my labels_to_add are all the category names I have so I am not sure if this is confusing matters. 

Any help gratefully recieved

**Comment by MaartenGr** [comment]
Hmmm, from the error message it seems that there is an issue with transforming the documents to embeddings. Could try the following to see if some errors pop up:

```python
from sentence_transformers import SentenceTransformer
sentence_model = SentenceTransformer("all-MiniLM-L6-v2")
embeddings = sentence_model.encode(docs, show_progress_bar=True)
```

If `embeddings` will be generated without any issues, then we at least know that the issue must stem from another place. Also, do you have any documents that are empty or nearly empty? Perhaps removing them would solve your issue. Lastly, you could also run `[str(doc) for doc in tweets_df['Doc'].tolist()]` to force each doc to be strings. I am not sure if these things will solve it but I want to get that out of the way first 😅

**Comment by MaartenGr** [comment]
Due to inactivity, this issue will be closed. Let me know if you want to re-open the issue and I'll be glad to help out!

**Comment by Terela62** [comment]
Hi, Apologies for the delay, after working with a new dataset I am finally back round to running the semisupervised process again. 
I have completed your suggestions, and I no longer receive the error. There was no issue with embeddings but there were some blank entries - getting rid of them solved the issue above. 

I am now getting the following error.  **TypeError: cannot unpack non-iterable BERTopic object**

**Comment by Terela62** [comment]
Further to the above 

topics, probs = topic_model.fit(docs,y=y) produces the error
topics, probs = topic_model.fit_transform(docs,y=y) does not produce the error

**Comment by MaartenGr** [comment]
The `.fit()` method is used to only fit the model, not transform the data to extract the fitted topics. In other words, you should run `.fit()` as follows:

```python
topic_model = BERTopic()
topic_model.fit(docs, y=y)
```

If you want to also extract the topics and probabilities, run `.fit_transform()` instead:

```python
topic_model = BERTopic()
topics, probs = topic_model.fit_transform(docs,y=y)
```
