### ISSUE TITLE
Mypy throws error?

### ISSUE THREAD

**Issue by Rysias** [MaartenGr/BERTopic#394]
Hi Maarten, 

Thanks again again for your great package and top class support! I am developing a project using BERTopic, where I am experimenting with mypy. However, when I try to run mypy it gives the following error:
`error: Skipping analyzing "bertopic": found module but no type hints or library stub`
This is unexpected as the library seems to be type hinted. Do you have any idea how to fix this? (apart from just ignoring typing in the library)

**Comment by MaartenGr** [comment]
I have not used mypy with BERTopic yet so I am not quite sure what is happening there. Perhaps going through mypy's issue page might give you some explanation as to why that is happening because it may not be BERTopic related.

**Comment by MaartenGr** [comment]
Due to inactivity, this issue will be closed. If you run into any other issues, let me know and I'll be glad to help out.
