### ISSUE TITLE
Filter keywords of Topic model

### ISSUE THREAD

**Issue by boa19941212** [MaartenGr/BERTopic#395]
Hi Maarten,
Thank you for great project!
I am facing some issues now  and my dataset is Chinese , hope you can help me..

1. There are many persons' names in my docs, and they have high probability of be included in topic model words,should I need to remove they before train topic model?

2. If I only want to keep "nouns" in my topic model words result, waht sould I do before use topic model.  

Looking forward to your reply ,Thank you!

**Comment by MaartenGr** [comment]
> 1. There are many persons' names in my docs, and they have high probability of be included in topic model words,should I need to remove they before train topic model?

That depends, it might be the case that those people typically write about certain subjects or that they are very related to certain topics. For example, if you have documents about books then it would make sense that certain authors appear in topics about fiction but not so much in non-fiction. However, if you feel that these names do not contribute much to the topic and are unnecessary, then you can try to replace them. Make sure that you then replace all names with the exact same name. It is then unlikely that they will appear. 

> 2. If I only want to keep "nouns" in my topic model words result, waht sould I do before use topic model.

If you only want to keep nouns in your topic model, then I would advise extracting all nouns from all your documents and then pass them to the `CountVectorizer` as the `vocabulary`. You can find a bit more about that [here](https://maartengr.github.io/BERTopic/getting_started/models/models.html) and [here](https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html). 

So it would be something like this:

```python
from bertopic import BERTopic
from sklearn.feature_extraction.text import CountVectorizer

vectorizer_model = CountVectorizer(vocabulary=my_nouns)
topic_model = BERTopic(vectorizer_model=vectorizer_model)
```
where `my_nouns` is a list of the nouns you extracted. How you do that is up to you. 

To me, this is a nice feature of splitting up creating the clusters and creating the representations. The CountVectorizer only cleans up the documents after they have been clustered, thereby keeping them intact when creating the clusters. After the clusters have been generated, we can start processing the documents to get the topic representations that we are looking for. Whether that is only nouns in the topics or something different is up to you and can easily be done using the CountVectorizer.

**Comment by boa19941212** [comment]
Hi Maarten,Thank you for quick and detail reply! I will try your suggestions.

May I ask  you another question?
I have aound 90K docs in my dataset,when I do clustering, it may have many outliers .
Is it a good way that  I pick outliers do clustering again until the number of outliers is nearly a number which I set?
Or should I choose other clustering ways if I hope most of docs can be clusted?

Thank you!

**Comment by MaartenGr** [comment]
The difficulty with outliers is that you can seldom assume that the data does not have any amount of data. HDBSCAN, however, might generate more outliers than what you have expected. In that case, I would advise following along with the documentation of BERTopic [here](https://maartengr.github.io/BERTopic/faq.html#how-do-i-reduce-topic-outliers) for some pointers on how to reduce them.

**Comment by boa19941212** [comment]
Hi Maarten, Thanks for suggestions, I will try it!
