### ISSUE TITLE
Error when importing BERTopic in GCP AI Platform

### ISSUE THREAD

**Issue by emeanacj14** [MaartenGr/BERTopic#397]
@MaartenGr pls could you advise how to remove this error while trying to import BERTopic in GCP notebook AI instance. my pls see below my code snippet and error msg:

!pip install bertopic==0.9.4
(.................................................................
Successfully installed bertopic-0.9.4 cython-0.29.26 filelock-3.4.2 hdbscan-0.8.27 huggingface-hub-0.2.1 nltk-3.6.7 numpy-1.20.3 plotly-5.5.0 pynndescent-0.5.5 pyyaml-5.4.1 regex-2021.11.10 sacremoses-0.0.46 sentence-transformers-2.1.0 sentencepiece-0.1.96 tokenizers-0.10.3 transformers-4.15.0 umap-learn-0.5.2)

from bertopic import BERTopic

ValueError Traceback (most recent call last)
/tmp/ipykernel_3264/2806191270.py in
----> 1 from bertopic import BERTopic

/opt/conda/lib/python3.7/site-packages/bertopic/init.py in
----> 1 from bertopic._bertopic import BERTopic
2
3 version = "0.9.4"
4
5 all = [

/opt/conda/lib/python3.7/site-packages/bertopic/_bertopic.py in
19
20 # Models
---> 21 import hdbscan
22 from umap import UMAP
23 from sklearn.feature_extraction.text import CountVectorizer

/opt/conda/lib/python3.7/site-packages/hdbscan/init.py in
----> 1 from .hdbscan_ import HDBSCAN, hdbscan
2 from .robust_single_linkage_ import RobustSingleLinkage, robust_single_linkage
3 from .validity import validity_index
4 from .prediction import (approximate_predict,
5 membership_vector,

/opt/conda/lib/python3.7/site-packages/hdbscan/hdbscan_.py in
19 from scipy.sparse import csgraph
20
---> 21 from ._hdbscan_linkage import (single_linkage,
22 mst_linkage_core,
23 mst_linkage_core_vector,

hdbscan/_hdbscan_linkage.pyx in init hdbscan._hdbscan_linkage()

ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject

**Comment by MaartenGr** [comment]
That is an [issue](https://github.com/numpy/numpy/issues/18709) that has popped up a few days ago. It seems that HDBSCAN does not like the new numpy release if it's installed together with UMAP 😅 The solution, however, is straightforward:

```bash
pip install bertopic
pip uninstall numpy -y
pip install numpy==1.22.0 --no-cache-dir 
```

If you are on python 3.7, then you will most likely find no issues. The fix above is for python>=3.8.

**Comment by emeanacj14** [comment]
@MaartenGr  many thanks for your response.

I am trying to install BERTopic in a **venv** within a GCP VM instance machine where i have initially installed Anaconda globally with python version 3.7.6.

The issue was not resolved using your earlier fix. because I am using python 3.7.6. and still I cant be able to install BERTopic due to it Failed to build hdbscan.

ERROR: Could not build wheels for hdbscan which use PEP 517 and cannot be installed directly


![image](https://user-images.githubusercontent.com/92374527/150915454-8ea7195a-71ce-41c0-af89-62b90393524b.png)

**Comment by emeanacj14** [comment]
![image](https://user-images.githubusercontent.com/92374527/150916428-163a0b0b-40ca-41f4-94c7-954f038ee06a.png)

**Comment by emeanacj14** [comment]
Please do you know any other solution for this error:
ERROR: Could not build wheels for hdbscan which use PEP 517 and cannot be installed directly. Thus be able to install and use BERTopic in GCP VM instance machine.

**Comment by MaartenGr** [comment]
Ah, this is actually a separate bug that I believe can be resolved by following [this](https://github.com/scikit-learn-contrib/hdbscan/issues/230#issuecomment-415687658) or [this](https://stackoverflow.com/questions/26053982/setup-script-exited-with-error-command-x86-64-linux-gnu-gcc-failed-with-exit/33874511#33874511). It seems that you need to have gcc installed before installing your package. 

This issue has happened to me before with other packages and is related to some essentials missing from the linux instance that you are using.

**Comment by emeanacj14** [comment]
Thanks for your quick response. I ran the following codes:

sudo apt-get install gcc python3.7-dev
pip install bertopic==0.9.4

from bertopic import BERTopic

then got the below errors:

![image](https://user-images.githubusercontent.com/92374527/151006231-77dd1c83-9ecb-4368-85e9-3c4817680097.png)
![image](https://user-images.githubusercontent.com/92374527/151007147-0b920952-2c2b-4b30-b8af-d80f86544211.png)

**Comment by emeanacj14** [comment]
tried this:
sudo apt-get install gcc python3.7-dev
pip install llvmlite –ignore-installed

and it worked but having a new error:
ImportError: tokenizers>=0.10.1,<0.11 is required for a normal functioning of this module, but found tokenizers==0.1
1.4.

**Comment by emeanacj14** [comment]
below are the codes i ran and it now works:
sudo apt-get install gcc python3.7-dev
pip install llvmlite –ignore-installed
pip install bertopic==0.9.4
pip install transformers -U

**Comment by emeanacj14** [comment]
![image](https://user-images.githubusercontent.com/92374527/151031734-7645fe38-d509-469e-af3e-6930c63d32d3.png)

**Comment by emeanacj14** [comment]
Please I am have this issues: see below, 

when I run BERTopic as described above: I get this right up ...HBox(children...
HBox(children=(FloatProgress(value=0.0, description='Batches', max=425.0, style=ProgressStyle(description_widt…

I also dont see any image graphs when, see below:
![image](https://user-images.githubusercontent.com/92374527/151033125-6fe82c7d-432b-4d14-804f-d1e6601bfc51.png)

**Comment by emeanacj14** [comment]
its Jupyter Notebook issue and i resolved it using this produce:

curl -fsSL https://deb.nodesource.com/setup_15.x | sudo -E bash -
sudo apt-get install -y nodejs
conda install -c conda-forge nodejs
jupyter labextension install @jupyter-widgets/jupyterlab-manager
conda install -c conda-forge ipywidgets
jupyter labextension install js
import ipywidgets as widgets
widgets.IntSlider()

**Comment by emeanacj14** [comment]
BERTopic and its visualisation is now working perfectly via GCP VM instance using python 3.7.6:
![image](https://user-images.githubusercontent.com/92374527/151039123-4ff5a527-468f-4e51-bb25-8da1c9f0eaea.png)
![image](https://user-images.githubusercontent.com/92374527/151039245-b11ac77c-4c5c-41db-ae22-c26daba6b834.png)

**Comment by MaartenGr** [comment]
Glad to hear that it is now working for you! Let me know if you run into any other issues and I'll be glad to help out.
