### ISSUE TITLE
Have the list of documents and the identifiers of those documents per topics

### ISSUE THREAD

**Issue by doubianimehdi** [MaartenGr/BERTopic#398]
Hi Maarten,

Happy new year and thank you again for your amazing work !
It's so amazing that I'm trying to make a product out of the results your package gives me !
For that purpose i'm trying to have the list of all the documents (for me it's abstracts of scientific publications) BUT i'm also trying to have the DOI of the paper along with it ... i'm using this piece of code but when I try to add the DOI , it's not working and i don't know why : 
abstract and doi are lists

topic_docs = {topic: [] for topic in set(topics)}
for topic, abstr, numdoi in zip(topics, abstract, doi):
    topic_docs[topic].append((abstr,doi))

It executes well but when I try to display topic_docs , the notebook runs for at least 5 minutes and then I have no error or displays !

Thanks for your help

**Comment by MaartenGr** [comment]
Ah, it seems that you should do `.append((abstr, numdoi))` and not `.append((abstr,doi))` since `doi` refers to all dois.

**Comment by doubianimehdi** [comment]
Indeed ! I noticed that ! Thank you ! But would you have advice to have a "Nicer" way of displaying all these information, I find the current form not very practical ...

**Comment by MaartenGr** [comment]
It might be more helpful if you use a pandas dataframe instead of a list of tuples. That allows you to sort through and filter the data for your specific use case.

**Comment by MaartenGr** [comment]
Due to inactivity, I will be closing this issue for now. Let me know if you want to continue the discussion and I'll re-open the issue.
