### ISSUE TITLE
[Error] numpy.core._exceptions.UFuncTypeError: ufunc 'correct_alternative_cosine' did not contain a loop with signature matching types <class 'numpy.dtype[float32]'> -> None

### ISSUE THREAD

**Issue by yihsiang123** [MaartenGr/BERTopic#400]
encounter some problem when implimenting

> model.fit_transform()

Have anyone encountered this problem? My version of numy is 

numpy                     1.22.0                   pypi_0    pypi

Thanks. 

![Capture](https://user-images.githubusercontent.com/80025118/148626095-f5757808-a1b1-49ac-8f56-a0c8e0536d89.PNG)

**Comment by MaartenGr** [comment]
This is a known issue with a certain combination of numpy, numba, UMAP, and HDBSCAN. Fortunately, there are a few fixes for this that you can find [here](https://github.com/MaartenGr/BERTopic/issues/392#issuecomment-1006333143).

**Comment by yihsiang123** [comment]
thanks. works now. appreciate it.

**Comment by shoegazerstella** [comment]
Hi,
I still have this error, I tried many solutions of the other issue but did not worked for me.
I am running the code in a jupyter server inside a docker container. Python version is 3.8.8

**Comment by MaartenGr** [comment]
@shoegazerstella Could you share the code for installing BERTopic? Also, the `correct_alternative_cosine` is an issue with UMAP if you have a numpy version >= 1.21 so make sure to install numpy 1.20.3.

**Comment by shoegazerstella** [comment]
Hi @MaartenGr ,
Thanks for replying. I finally managed to solve it with:

```
numpy==1.20.2
UMAP==0.1.1 
```
also numpy==1.20.3 should work
