### ISSUE TITLE
Unable to visualize distribution

### ISSUE THREAD

**Issue by sanketjoshi2012** [MaartenGr/BERTopic#406]
I am training(fit) a BERTopic model with calculate_probabilties=True on a certain dataset, saving the model, and then loading it and using it on a smaller dataset(I am using transform()), but I am not able to visualize the distribution. This is the error I get "Occurrences of metals and their counts in the crawled data where companies did not follow circular economy and sustainability"

Can someone help me with this?

**Comment by MaartenGr** [comment]
Could you share the entire code you have been using as well as the full error message? Right now, without seeing the code and the error log it is very difficult to understand what exactly is going on.
