### ISSUE TITLE
topic_model.visualize_***() in a custom function cannnot show up chart

### ISSUE THREAD

**Issue by fishfree** [MaartenGr/BERTopic#407]
```
def bert_tweets(csvfilepath, min_topic_size=20):
    ...
    print('Visualize inter-topics distance:')
    topic_model.visualize_topics()
    print('Visualize Topic Probabilities:')
    topic_model.visualize_distribution(probs[200], min_probability=0.015)
    print('Visualize Topic hierarchies')
    topic_model.visualize_hierarchy(top_n_topics=50)
    ...
```
I define a custom function as above in a code cell in a Google Colab notebook, then in another code cell run the function as below:
`bert_tweets('mytweets.csv')`
But no chart shows up. If I directly run the  topic_model.visualize_topics() function according to the [example](https://colab.research.google.com/drive/1FieRA9fLdkQEGDIMYl0I3MCjSUKVF8C-?usp=sharing#scrollTo=_ak_CLR164mx), it works. Is there any related configurations in the Google Colab?

**Comment by MaartenGr** [comment]
`topic_model.visualize_topics()` returns a plotly figure, so it is important to also return that variable in your function. In other words, you should run `fig = topic_model.visualize_topics()` instead and return the `fig` variable.

**Comment by fishfree** [comment]
@MaartenGr Thank you! I want to sequently show up the visualizations when I call my custom function. But I'm sorry I forgot adding those lines in the function code. I just updated my issue. Please review.

**Comment by MaartenGr** [comment]
@fishfree The same applies here, each visualization function returns a plotly figure, so you would need to adjust you function to something like this:

```
def bert_tweets(csvfilepath, min_topic_size=20):
    ...
    fig_1 = topic_model.visualize_topics()
    fig_2 = topic_model.visualize_distribution(probs[200], min_probability=0.015)
    fig_3 = topic_model.visualize_hierarchy(top_n_topics=50)
    return fig_1, fig_2, fig_3
    ...
```

**Comment by fishfree** [comment]
@MaartenGr I returned the charts in the custom function. After I run this fucntion in a note: `bert_tweets('my-csv-file-path')` Still no charts show up in Google Colab notebook.

**Comment by MaartenGr** [comment]
The function should be run as follows: `fig1, fig2, fig3 = bert_tweets(csvfilepath, min_topic_size=20)`. Then, after generating the figures, you can show them with `fig1.show()`. You can find a bit more about that [here](https://plotly.com/python/renderers/).

**Comment by fishfree** [comment]
@MaartenGr Thank you very much!
