### ISSUE TITLE
C-BM25 as opposed to C-TFIDF / Evaluating topics

### ISSUE THREAD

**Issue by Naeem120** [MaartenGr/BERTopic#408]
First of all, thank you very much for BERTopic!

I was wondering, BM25 is a superior version of TFIDF, so is there any specific reason as to why TFIDF was chosen instead? 
Also, what methods do you recommend using for evaluating the topics? I thought checking the cosine similarly of all the documents under a topic would be a good indicator but it's giving me poor results (not sure why).
As i'm experimenting with different number of topics, i'm not sure of the overall effect it's having on the quality of those topics. Other than checking the probability of the top 10 words, is there a more robust way of evaluating, rather than manually going through the documents?

I would really appreciate your input, thanks!

**Comment by MaartenGr** [comment]
BM25 is not necessarily a superior version of TF-IDF as its use cases may differ. BM25, for example, is a method for scoring documents with relation to a query in contrast to TF-IDF. Moreover, BM25 has a number of parameters that can be and perhaps should be optimized for each individual use-case resulting in difficulties using the application. Having said that, some of the ideas of BM25 could be implemented in TF-IDF without the query-based structure. 

Typically, you can try to calculate the quality of topics with measures such as topic coherence (e.g., NPMI) or topic diversity. Important to note is that these measures should not be used to grid-search parameters as that may result in lower quality topics. For evaluation, I would highly advise the [OCTIS](https://github.com/MIND-Lab/OCTIS) library as it has many easy-to-use evaluation metrics implemented.

**Comment by MaartenGr** [comment]
As this post is a bit older now, I'll be closing it. However, if you want to continue this discussion I'll make sure to re-open it.
