### ISSUE TITLE
Error when loading serialized topic model

### ISSUE THREAD

**Issue by pratik98** [MaartenGr/BERTopic#409]
i had saved topic model previously using  'BERTopic.save()'  and now when i am trying to reload it, it throws an error.

`%%capture
!pip install bertopic`

`from bertopic import BERTopic`

`post = BERTopic.load("/content/drive/MyDrive/investing/Post_BERTopic_DTM_30")`

**Error:**

`ModuleNotFoundError: No module named 'sklearn.neighbors._dist_metrics'`

**Comment by MaartenGr** [comment]
This is not an issue that I am familiar with but did you make sure that the environments between saving and loading the model are exactly the same? Also, it might be helpful to remove `%%capture` in case something went wrong with installing BERTopic as there are currently issues with HDBSCAN (which you can check out in the pinned issue).

**Comment by KnobKraus** [comment]
I had the same error in a google colab notebook, even though loading worked perfectly fine a few days ago. Downgrading scikit-learn to 1.0.0 solved the issue for me. Used Bertopic 0.9.4 to save and load the model

**Comment by pratik98** [comment]
@KnobKraus Thank you.
