### ISSUE TITLE
Unable to save the model

### ISSUE THREAD

**Issue by DSTeamTsteps** [MaartenGr/BERTopic#410]
Hi Maarten,

I am using below code to create topics.
import tensorflow_hub
embedding_model = tensorflow_hub.load("https://tfhub.dev/google/universal-sentence-encoder/4")
model = BERTopic(verbose=True, embedding_model=embedding_model, n_gram_range=(5, 5), min_topic_size=20, top_n_words=1)
topics, probabilities = model.fit_transform(docs)

I am getting the proper topics. But, I am unable to save this model. Please help me to resolve this.
this is the error I am getting when I tried to save the model
 model.save("Model_Name")
Error is: 
PicklingError: Can't pickle <class 'tensorflow.python.saved_model.load.Loader._recreate_base_user_object.<locals>._UserObject'>: it's not found as tensorflow.python.saved_model.load.Loader._recreate_base_user_object.<locals>._UserObject

Thank you

**Comment by MaartenGr** [comment]
Not entirely sure why but it seems that the tensorflow model cannot be pickled correctly. The quick way of preventing this is to simply run the following instead: 

`model.save("Model_Name", save_embedding_model=False)`

This prevents saving the embedding model. To then load in the trained BERTopic model, you can simply run: 

`BERTopic.load("Model_Name", embedding_model=embedding_model)`

**Comment by DSTeamTsteps** [comment]
Great Maarten.

Working fine now. Thankyou so much
