### ISSUE TITLE
Running Bertopic with Bertweet Embedding Model 

### ISSUE THREAD

**Issue by Tunguyen485** [MaartenGr/BERTopic#415]
Hi MaartenGR,
Thanks for creating the Bertopic. 
Can I use the Bertweet model to embed in the BERTopic?
I see a warning when I run the code below:

import torch
from transformers import AutoModel, AutoTokenizer
bertweet = AutoModel.from_pretrained("vinai/bertweet-large")

docs = sentences[100:500]

model = BERTopic(nr_topics = 5,
                 language = 'english',
                 n_gram_range=(1, 2), 
                 calculate_probabilities = True,
                 embedding_model=bertweet, 
                 verbose=True)

topics, probabilities = model.fit_transform(docs)

Some weights of the model checkpoint at vinai/bertweet-large were not used when initializing RobertaModel: ['lm_head.decoder.bias', 'lm_head.layer_norm.bias', 'lm_head.bias', 'lm_head.dense.bias', 'lm_head.dense.weight', 'lm_head.decoder.weight', 'lm_head.layer_norm.weight']
- This IS expected if you are initializing RobertaModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing RobertaModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of RobertaModel were not initialized from the model checkpoint at vinai/bertweet-large and are newly initialized: ['roberta.pooler.dense.weight', 'roberta.pooler.dense.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
2022-01-18 23:59:28,319 : INFO : Load pretrained SentenceTransformer: all-MiniLM-L6-v2
2022-01-18 23:59:34,132 : INFO : Use pytorch device: cpu

**Comment by MaartenGr** [comment]
It is not possible to directly use transformer models like that in BERTopic as each model can work entirely differently from another. To do this, you would either need to use [Flair](https://maartengr.github.io/BERTopic/getting_started/embeddings/embeddings.html#flair) or create your own custom [back-end](https://maartengr.github.io/BERTopic/getting_started/custom_embeddings/embeddings.html#custom-backend).

**Comment by MaartenGr** [comment]
Due to inactivity, I'll be closing this issue. If you are still experiencing this problem, let me know and I'll make sure to re-open the issue!
