### ISSUE TITLE
ImportError: cannot import name 'Dataset' from 'torch.utils.data' (unknown location)

### ISSUE THREAD

**Issue by km5ar** [MaartenGr/BERTopic#418]
Could you help me with this error?
ImportError: cannot import name 'Dataset' from 'torch.utils.data' (unknown location)![image](https://user-images.githubusercontent.com/54015474/150706469-a65b0a1c-ba3b-4a52-bebc-802ecc6ba62a.png)

**Comment by MaartenGr** [comment]
Hmmm, I am not familiar with this error. However, these kinds of errors typically stem from a dependency conflict. I would advise starting with only `pip install bertopic` and not the other back-ends and seeing if that works out. I have to note though that it is likely that these 4 back-ends cannot be used together simultaneously, so make sure to use only one specific back-end.

**Comment by km5ar** [comment]
I fixed it by creating an independent environment through miniconda.

**Comment by MaartenGr** [comment]
Glad to hear that it worked! Let me know if you run into any other issues and I'll be glad to help.
