### ISSUE TITLE
how to find optimal number of topics for BERTOPIC

### ISSUE THREAD

**Issue by ranjith502** [MaartenGr/BERTopic#419]
Thanks for creating awesome  library 

I want to know is there is a way to find out optimal number of topics for bertopic 

Example:- In LDA i use coherence score as a  metric , the topic with highest coherence score (c_v)  is taken as a optimum topic size 

i know it is not a good idea ,some times it gives bad results... Similarly is there is a way to select no of topics for bertopic

**Comment by MaartenGr** [comment]
Thank you for the kind words! 

It would indeed be very handy to find out the optimal number of topics. The main difficulty here lies in the definition of "optimal". As you mentioned before, for classical models you can use the coherence score (typically npmi) to find the optimal number of topics as for some of these models they have been shown to correlate well with human evaluation. However, it is still a metric that only considers coherence and not, for example, topic diversity. 

Without making this all too complex, it is important to figure out when you think a topic is "good". Which criteria are important to you and evaluate based on those. 

To make it a bit more concrete, you can use `nr_topics="auto"` to merge all topics together that are quite similar to one another. That way, you choose a number of topics that fit with the data without the need to optimize for one or more evaluation metrics. Here, it is also important to choose a `min_topic_size` that makes sense to you as it relates to the number of topics that will be created. I tend to choose a value that generates about 100 topics. If it does, then I run the model again with `nr_topics="auto"` to merge similar topics together.

**Comment by MaartenGr** [comment]
Seeing as this has been inactive for a while now, I'll be closing this issue. Let me know if you need me to re-open this issue if you have any more questions!
