### ISSUE TITLE
HDBScan not properly installed/build under offical installation procedure

### ISSUE THREAD

**Issue by dhvalden** [MaartenGr/BERTopic#424]
HDBScan appears as dependency and it's supposedly installed properly with pip, but once BERTopic is imported I get an import error. It get solved by installing hdbscan using conda forge, but this behaviour is not ideal.

environment used:
```
CentOS Linux release 7.9.2009 (Core)
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

CentOS Linux release 7.9.2009 (Core)
CentOS Linux release 7.9.2009 (Core)
```
- Fresh conda env with explicit python 3.7.*

**Comment by MaartenGr** [comment]
Thank you for the extensive description of the environment. Can you also post the full import error as it is difficult to see what the issue might be without the full message? 

It might be related to the [pinned message](https://github.com/MaartenGr/BERTopic/issues/392) though at the top of the issues page. Currently, there are ABI issues with the interaction between Numpy and HDBSCAN that might be solved manually with the instructions you find there.

**Comment by dhvalden** [comment]
Absolutely:
here is the Error message with the traceback:
```
Python 3.7.12 | packaged by conda-forge | (default, Oct 26 2021, 06:08:21) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from bertopic import BERTopic
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/home01/ptdhv/.conda/envs/bertopic/lib/python3.7/site-packages/bertopic/__init__.py", line 1, in <module>
    from bertopic._bertopic import BERTopic
  File "/home/home01/ptdhv/.conda/envs/bertopic/lib/python3.7/site-packages/bertopic/_bertopic.py", line 21, in <module>
    import hdbscan
  File "/home/home01/ptdhv/.conda/envs/bertopic/lib/python3.7/site-packages/hdbscan/__init__.py", line 1, in <module>
    from .hdbscan_ import HDBSCAN, hdbscan
  File "/home/home01/ptdhv/.conda/envs/bertopic/lib/python3.7/site-packages/hdbscan/hdbscan_.py", line 21, in <module>
    from ._hdbscan_linkage import (single_linkage,
ImportError: /home/home01/ptdhv/.conda/envs/bertopic/lib/python3.7/site-packages/hdbscan/_hdbscan_linkage.cpython-37m-x86_64-linux-gnu.so: undefined symbol: __intel_sse2_strchr
```

### Steps to reproduce:
- Create conda environment with explicit python 3.7.*
- Activate the environment
- run `pip install bertopic`
- Open python and run `from bertopic import BERTopic`

### Workaround:
- Install HDBScan via conda forge: ` conda install -c conda-forge hdbscan`

### Note:
Running on HPC with restricted privileges. The use of environments is required.

**Comment by MaartenGr** [comment]
Based on the error, it seems that there is a conflict between the compiler and the python distribution. Perhaps [this](https://stackoverflow.com/questions/49524083/importing-any-module-in-cython-file-gives-undefined-symbol-error) solves the issue for you (aside from a conda install).

**Comment by dhvalden** [comment]
I see. I also noticed that. I'll dig further on my own and if find a solution I'll create a pull request. For now I'll close the issue.

Best wishes!
