### ISSUE TITLE
transform function documentation's return is different to provided example

### ISSUE THREAD

**Issue by jwaugh28** [MaartenGr/BERTopic#429]
Documentation for the transform function states it returns only a "predictions" object, while the usage example returns both topics and probs objects:
![image](https://user-images.githubusercontent.com/38676301/152060173-0710540e-d3fb-4747-9452-66bbfb2bb2e4.png)

**Comment by fsysean** [comment]
topics are prdicted label and probs are probability.

**Comment by MaartenGr** [comment]
Strange, the probabilities are mentioned in the documentation but it seems that for whatever reasons, MKDOCS does not generate the additional parameters in `.transform()`. Thank you for bringing up this issue and I'll put it on the roadmap!
