### ISSUE TITLE
Theoritical question about :representative docs:

### ISSUE THREAD

**Issue by schetudiante** [MaartenGr/BERTopic#432]
Hey Maarten,

I again by first start thanking you for this awesome package! 

I wanted to know about `representative docs` the results it returns does it mean:
Q1. the documents returns are the closest to the cluster's centre?
What does `representative docs`  mean mathematically?

**Comment by MaartenGr** [comment]
Thank you for the kind words, glad I could help! 

No, BERTopic, in its main algorithm, tends to steer away from focusing on a cluster's center. The issue with looking at the mean value of a cluster is that there is a good chance no points will exist in that center. For example, if you have a number of points on the edge of a circle, then the center of the circle would be empty and have no points. So looking at documents or any other embeddings, that are close to a cluster's center might not always be accurate. 

Here, `representative docs` are the so-called `exemplars` in HDBSCAN which you can find a bit more about [here](https://hdbscan.readthedocs.io/en/latest/soft_clustering_explanation.html#distance-based-membership). Essentially, a cluster can have different shapes and exemplars can be found by focusing on places in a cluster where it is most dense.

**Comment by schetudiante** [comment]
> Thank you for the kind words, glad I could help!
> 
> No, BERTopic, in its main algorithm, tends to steer away from focusing on a cluster's center. The issue with looking at the mean value of a cluster is that there is a good chance no points will exist in that center. For example, if you have a number of points on the edge of a circle, then the center of the circle would be empty and have no points. So looking at documents or any other embeddings, that are close to a cluster's center might not always be accurate.
> 
> Here, `representative docs` are the so-called `exemplars` in HDBSCAN which you can find a bit more about [here](https://hdbscan.readthedocs.io/en/latest/soft_clustering_explanation.html#distance-based-membership). Essentially, a cluster can have different shapes and exemplars can be found by focusing on places in a cluster where it is most dense.

Thank you so much Maarten 😄

**Comment by MaartenGr** [comment]
No problem, glad I could help!
