### ISSUE TITLE
Topic distribution over different timestamps

### ISSUE THREAD

**Issue by sanketjoshi2012** [MaartenGr/BERTopic#433]
Hi @MaartenGr, firstly, I must say that this is a very useful package, but I have a question.

Can a topic with a specific number still be the same topic at different time points - but with different words drawn from it?

When I hover over the visualization of topics_over_time, I see a different set of words for different timestamps but with the same topic number.

**Comment by sanketjoshi2012** [comment]
Hi, @MaartenGr I read the documentation once again and understood the part that the words change when we hover over the graph because those are time-specific representations of the topic.

I am closing this issue. 
And cheers once again for this awesome package!

**Comment by MaartenGr** [comment]
Thank you for your kind words! Glad to hear that the issue is resolved. If you have any other questions, please let me know 😄
