### ISSUE TITLE
Is it possible to see what topics were merged in a reduced topic model?

### ISSUE THREAD

**Issue by simonfelding** [MaartenGr/BERTopic#436]
Dear MaartenGr, is it possible to see what topics were merged in a reduced topic model?
Ideally, I would love to see output like "topic 0: (topic0+topic18+topic58)" and so on, or something like that. I intend to use it for a hierarchical plot to compare the original model with the reduced model :)

**Comment by MaartenGr** [comment]
This is not directly implemented but there are some tricks into getting those topics. It does depend, however, on how you reduced the number of topics. `nr_topics=50` is a different procedure from `nr_topics="auto"`. If you provide an integer, then the topics are reduced by taking the least frequent topic and adding that to the most similar topic until 50 topics are remaining. If you provide `"auto"`, then HDBSCAN is used to cluster the clusters in order to reduce those topics. 

In general, you can extract the mappings as follows:

```python
topic_model.topic_mapper.mappings
```

Where the first column represents the topics as they were trained on initially during HDBSCAN, then, each next column is a mapping. 

To get the exact topic representations before reducing topics, you can run the following after training the model:

```python
import pandas as pd

old_topic_labels = topic_model.hdbscan_model.labels_
docs_df = pd.DataFrame({"Document": docs, "Topic": old_topic_labels, "to_count": docs})
documents_per_topic = docs_df.groupby(["Topic"], as_index=False).agg({"Document": " ".join, "to_count": "count"})
ctfidf, words = topic_model._c_tf_idf(documents_per_topic, fit=False)
labels = sorted(list(documents_per_topic.Topic.unique()))
old_topics = topic_model._extract_words_per_topic(words=words, c_tf_idf=ctfidf, labels=labels)
```

To then compare the mappings, you can run something like this for a single topic (e.g., topic 6 before reducing topics):

```python
old_topic = 6
current_topic = np.array(topic_model.topic_mapper.mappings)[old_topic +1, -1]
old_topics[old_topic ], topic_model.get_topic(current_topic )
```

**Comment by simonfelding** [comment]
I don't entirely understand how the mappings work in `topic_model.topic_mapper.mappings`.
I get output like this:

```
np.array(topic_model.topic_mapper.mappings)[0 +1]
>> array([  0,   0, 167])
```
Does that mean that topic 0 is mapped to topic 0 + topic 167?
Because if that's the case, why do I get this?
```
np.array(topic_model.topic_mapper.mappings)[167 +1]
>> array([167, 167,  23])
```

I'm trying to reduce 197 topics to about 25, so there will necessarily be at least 7 old topics per new topic.

**Comment by MaartenGr** [comment]
The `topic_model.topic_mapper.mappings` represents a topic at each stage of the reduction process. So if you have the following:

```python
np.array(topic_model.topic_mapper.mappings)[0 +1]
>> array([  0,   0, 167])
```

That would mean that topic 0 is first mapped to topic 0 and then mapped to topic 167. That also means that you cannot compare 

```python
np.array(topic_model.topic_mapper.mappings)[0 +1]
>> array([  0,   0, 167])
```

with 

```python
np.array(topic_model.topic_mapper.mappings)[167 +1]
>> array([167, 167,  23])
```

as the process is from left to right where the left side always precedes the topics on the right. Thus, the topic `167` that you find as the last value in `np.array(topic_model.topic_mapper.mappings)[0 +1]` is not related in any way with the first value you find in `np.array(topic_model.topic_mapper.mappings)[167 +1]`.

**Comment by DSgUY** [comment]
Hi @MaartenGr , congrats for this amazing library!

If you want to build some kind of hierarchy you can use `nr_topics="auto"` for example 3 times and use `topic_model.topic_mapper.mappings` to build a 3 level hierarchy?

Regards.

**Comment by MaartenGr** [comment]
@DSgUY That is an interesting approach. In theory that would be possible but I am not sure how accurate that would actually be. The "auto" procedure uses HDBSCAN as a way to cluster the clusters and running that several times is likely to result in poor clusters. Instead, `.visualize_hierarchy()` should be a nice start in representing the possible hierarchical nature.

**Comment by DSgUY** [comment]
Yes I used `.visualize_hierarchy() `  but I think if you want to do some manipulation to the hierarchy you need to tweek the `.visualize_hierarchy()` to returns some extra info to build a tree or sth.

**Comment by MaartenGr** [comment]
To model the hierarchical nature, I would advise trying out the code yourself [here](https://github.com/MaartenGr/BERTopic/blob/master/bertopic/plotting/_hierarchy.py). Another possibility is looking at the [linkage](https://docs.scipy.org/doc/scipy/reference/generated/scipy.cluster.hierarchy.linkage.html) function in scipy on which the `.visualize_hierarchy()` is based. You can use that to generate the hierarchy that you are looking for based on the code in `.visualize_hierarchy()`.

There might already be some work from my side on hierarchical topic modeling but that would still require much testing and experimentation before being implemented. Seeing as we are starting to get a bit off-topic, I'll close this issue for now but feel free to open another issue (or continue in #265) if you want to continue this discussion!
