### ISSUE TITLE
How to evaluate the performance of the model?

### ISSUE THREAD

**Issue by chayankathuria** [MaartenGr/BERTopic#437]
Thanks for creating this package!

However, I wanted to check its performance to compare it with topics generated by LDA. I was hoping it'd have a function for Coherence Score but it doesn't. Any thoughts on how to benchmark and compare its performance with other topic models?
Also, any particular reason for not including Coherence metric within the package?

Thanks!

**Comment by nilsblessing** [comment]
Hi @chayankathuria,

I'm not one hundred percent sure but I guess #428 could help to answer your question.


Kind regards,

Nils

**Comment by MaartenGr** [comment]
When benchmarking BERTopic against other topic models, I would advise using [OCTIS](https://github.com/MIND-Lab/OCTIS) as it has quite a number of metrics implemented and an easy-to-use pipeline for validation. 

This is a risk involved with implementing coherence scores within the package. First, choosing the coherence score by itself can have a large influence on the difference in performance you will find between models. For example, NPMI and UCI may each lead to quite different values. Second, the coherence score only tells a part of the story. Perhaps your purpose is more classification than having the most coherent words or perhaps you want as diverse topics as possible. These use cases require vastly different evaluation metrics to be used. 

The points above bring me to the main reason for not implementing a coherence metric, namely, that there is no one right way of evaluating a topic model over all its possible use cases. If a single coherence metric were to be implemented, you then risk that users are going to be grid-searching parameters to optimize for that coherence metric, which is likely to actually result in lower performances. Instead, I leave it up to the users to select which metrics are suited to their use when evaluating topic models.

**Comment by chayankathuria** [comment]
Got it. Thanks for the elaborate answer!

**Comment by SaudiScientist** [comment]
Thanks Marteen for a detailed answer, it is quite useful. 

I am currently trying to compare the results of BERTopic with LDA and NMF. What is the best way to do that? and What metric would you recommend (Topic Coherence vs. Topic Diversity) or OCTIS?

**Comment by MaartenGr** [comment]
@SaudiScientist My post above is still relevant here I think. There is more to evaluation than just a single type of metric, whether it is topic coherence or diversity. Some of these metrics have even been shown not to correlate well for neural topic models as well as they do for some of the classical models, like LDA. Even when you perform human evaluation, that can still be incredibly biased and measures only one aspect of what it does, quite subjective so if we are talking about merely coherence. A coherent topic does not necessarily mean an accurate topic. This gets complicated further with that BERTopic is a modular framework where you can easily swap around models, especially representation models. So evaluating only the defaults of BERTopic is ignoring everything it has to offer (KeyBERTInspired, PartOfSpeech, MMR, ChatGPT, etc.).

In practice, I would advise focusing on the use case at hand and selecting evaluation measures that fit those best. That way, you can evaluate BERTopic on its functionality and what you are using it for. Depending on your use case, coherence might be more important than diversity and vice versa.
