### ISSUE TITLE
Expose batch_size parameter

### ISSUE THREAD

**Issue by stolam** [MaartenGr/BERTopic#44]
It would be nice to have a control of the batch size that converts the docs to embeddings.
The default is 32 and during my run of the algorithm, the GPU memory never exceeded 2.5/16G. It could improve the speed of the embeddings extraction.

**Comment by MaartenGr** [comment]
At the moment, I am not going to expose that parameter. It's a worthwhile extension and a good idea, don't get me wrong, but I want instead to give users the possibility to use an entire `SentenceTransformer`. This allows them to set whatever parameters they want outside of BERTopic without the need to expose many parameters within BERTopic itself. 

I am not entirely sure how I want to approach though seeing as I might switch out `sentence-transformers` with `flair`, but I will be working on this in the coming weeks!

**Comment by stolam** [comment]
Thank you for your reply. The possibility to use entire `SentenceTransformer` sounds nice.

**Comment by MaartenGr** [comment]
@stolam BERTopic v0.5 has just been released with the option to use both `SentenceTransformer` and `Flair`. See [here](https://maartengr.github.io/BERTopic/tutorial/embeddings/embeddings.html) for the tutorial on how to apply it.
