### ISSUE TITLE
How to get labels for the documents?

### ISSUE THREAD

**Issue by chayankathuria** [MaartenGr/BERTopic#442]
Post fitting the model on my data, I get probabilities of a document belonging to a particular topic. If I have 6 topics, there will be 6 probabilities. So can I just take the argmax? 
However, there is a -1 label as well depicting the "others" topic. How do then I get the correct labels for these 7 categories?

Thanks in advance!

**Comment by MaartenGr** [comment]
Yes, you can just take the `argmax` to get the most probable topic for that document. Technically, the -1 label is not a cluster and is only selected if the HDBSCAN is not convinced it belongs to any actual cluster. To get that label, you can simply use the `topics` variable instead after using `fit_transform`.

**Comment by chayankathuria** [comment]
This is really helpful! Thanks for the prompt response!
