### ISSUE TITLE
Predicting topics in a new set of documents using a saved BERTopic model

### ISSUE THREAD

**Issue by tawfiqam** [MaartenGr/BERTopic#445]
When using mode.transform(NEW DOCUMENTS), the resulting weights do not correspond to the same topics in the model that I trained before. For example, there were 144 topics in the original document, but after transform on a new set of documents, they are expressed using 976 weights. I am not sure why there is a discrepancy. There are no errors, I am just wondering if I misunderstood what transform does?

**Comment by MaartenGr** [comment]
> When using mode.transform(NEW DOCUMENTS), the resulting weights do not correspond to the same topics in the model that I trained before. 

What exactly do you mean by "weights"? Do you mean the topics generated in the variable `topics`,  the probabilities from `probs`, or something else? Also, can you share the code that you have been using for that purpose?

**Comment by tawfiqam** [comment]
Apologies...my bad.
