### ISSUE TITLE
What is normalize_frequency in Visualize_topics_per_class?

### ISSUE THREAD

**Issue by ByungjunKim** [MaartenGr/BERTopic#446]
Hello.
BERTopic is amazing package! Thank you.
I wonder that normalize_frequency parameter in visualize_topics_per_class.
I understand that normalize_frequency parameter means ratio(percent) of class in each topic.
That's why I think that sum of normalized frequency is 1. However, the sum is over 1.
What is normalize frequency in visualize_topics_per_class?

**Comment by spookyuser** [comment]
Could i make a pr that adds something like this to the visualize_topics_per_class function so you could get percentage if you wanted?

```python
if normalize_frequency:
            x = normalize(trace_data.Frequency.values.reshape(1, -1))[0]
        if as_percentage:
            x = trace_data.Frequency.values / trace_data.Frequency.sum() * 100
        else:
            x = trace_data.Frequency
```

**Comment by MaartenGr** [comment]
At the moment, I am not entirely sure if that is something that fits within the current visualizations. As of right now, there are some visualizations that have a normalization procedure but not all. Adding a percentage parameter to only a single graph might not be that user-friendly. Perhaps making sure that all visualizations have some sort of generic `normalize` parameter that takes in string values to indicate the type of normalization would be preferred.

**Comment by spookyuser** [comment]
Yeah that's a great idea!

**Comment by MaartenGr** [comment]
Thanks, glad to hear that! Are there by chance any other normalization procedures that you think would be worthwhile to add?

**Comment by spookyuser** [comment]
I will definitely try to think of more as I go along, but so far the percentage in the topics_per_class graph has been the one I've wanted the most :)

**Comment by arvospec** [comment]
Hi Maarten, Thank you so much for developing this tool. I'm a new learner, but wanted to clarify if the Normalized Frequency is calculated using TF-IDF?

**Comment by MaartenGr** [comment]
@arvospec No, it simply uses scikit-learn's `normalize` function: 

https://github.com/MaartenGr/BERTopic/blob/de7376d3d42960e787a1115e5fe69fb726a7a33d/bertopic/plotting/_topics_per_class.py#L90

**Comment by abeljohn0** [comment]
Hi @MaartenGr, 
I had two questions about topics_per_classes - from my understanding of topics_per_classes, it identifies how strongly topics correlate to a given class. The problem I'm running into is that my data is unlabeled, so topics_per_classes will ask me to create array of the same length as the number of docs, when I want to see which topics correlate strongest to (for example) a set of three categories ["News", "Drama", "Comedy"]. 

More generally, if I wanted to cluster documents according to a pre-selected class, is there a means of doing that? 

Lastly, thanks for developing and supporting BERTopic, it has proven very useful to me recently.

**Comment by MaartenGr** [comment]
@abeljohn0 If you have pre-defined topics that you want to use for assigning documents, I would instead advise to use [zero-shot topic modeling](https://maartengr.github.io/BERTopic/getting_started/zeroshot/zeroshot.html). This method finds the documents that fit within those pre-defined topics but also still allows for clustering documents that do not fit within those categories.
