### ISSUE TITLE
Questions about the c-tf-idf

### ISSUE THREAD

**Issue by sgdantas** [MaartenGr/BERTopic#450]
Hi Maarten, I have some questions about the c-tf-idf implementation

<img width="706" alt="image" src="https://user-images.githubusercontent.com/34652852/154527665-15e2d630-2258-4e08-a7ed-64b9fe070d43.png">

Is there a reason why you're using "A" (average number of words per class)? I saw your past medium post about c-tf-idf and I don't see a clear connection between the two formulas.  According to the code, it seems more like a regularization value, is that right? Also, just to be sure: 
- does `tf_x,c` refer to the count of word `x` divided by the total words across all documents in `c`?
- does `f_x` refer to the count of word `x` divided by the total number of documents?

Thanks, and I appreciate all the work you put in this library :)

**Comment by MaartenGr** [comment]
Yes, the reason that there are discrepancies between the medium post and this implementation (also the implementation at the c-TF-IDF repo) is that there were some optimizations necessary after working on development for BERTopic in the last year. 

> Is there a reason why you're using "A" (average number of words per class)?

Yes, that is meant to get a bit more stability when generating the topic representations. It is very similar to the `N` (total number of documents) in the classic TF-IDF. 

> does tf_x,c refer to the count of word x divided by the total words across all documents in c?

No, it is the raw frequency of words in each class 

> does f_x refer to the count of word x divided by the total number of documents?

No, it is the raw frequency of words across all classes

Lastly, to get a bit more intuitive feeling on what it does, it might be an idea to look at the implementation of c-TF-IDF [here](https://github.com/MaartenGr/BERTopic/blob/master/bertopic/_ctfidf.py).

**Comment by sgdantas** [comment]
Thanks for the help :)

**Comment by juli-sch** [comment]
Hi Maarten, 
I was also a bit confused about the different formulas. This issue helped me to understand it. Thanks for explaining! 
Just to be sure: I assume that the given image in the code is still a leftover from the old implementation, am I right?
I really appreciate your work and the excellent documentation.

**Comment by MaartenGr** [comment]
> Just to be sure: I assume that the given image in the code is still a leftover from the old implementation, am I right?

The image that you can find [here](https://maartengr.github.io/BERTopic/algorithm/algorithm.html) is currently most up-to-date and should reflect the procedure accurately. 

> I really appreciate your work and the excellent documentation.

Thank you for your kind words! If you have any other questions, please let me know.

**Comment by lkluo** [comment]
> Yes, the reason that there are discrepancies between the medium post and this implementation (also the implementation at the c-TF-IDF repo) is that there were some optimizations necessary after working on development for BERTopic in the last year.
> 
> > Is there a reason why you're using "A" (average number of words per class)?
> 
> Yes, that is meant to get a bit more stability when generating the topic representations. It is very similar to the `N` (total number of documents) in the classic TF-IDF.
> 
> > does tf_x,c refer to the count of word x divided by the total words across all documents in c?
> 
> No, it is the raw frequency of words in each class
> 
> > does f_x refer to the count of word x divided by the total number of documents?
> 
> No, it is the raw frequency of words across all classes
> 
> Lastly, to get a bit more intuitive feeling on what it does, it might be an idea to look at the implementation of c-TF-IDF [here](https://github.com/MaartenGr/BERTopic/blob/master/bertopic/_ctfidf.py).

Could you explain why using raw frequency instead of relative one like traditional tf-idf? Thanks.

**Comment by MaartenGr** [comment]
@lkluo Good question! It used to use raw frequency but that has changed some time ago. Now, the raw frequency is normalized in order to make the frequencies a bit more easier to analyzes when multiplying it with the idf calculation as the raw frequency can get quite large when combining documents. You can find the full code for that [here](https://github.com/MaartenGr/BERTopic/blob/master/bertopic/_ctfidf.py). Do note that there might even be some chances to this in the future.

**Comment by lkluo** [comment]
@MaartenGr Thanks for your prompt response. See it implements `normalize`, but I have another question when plotting `topic_over_time` that the values is very large that looks like still raw frequency. According to the equation of c-tf-idf, the values shall be small as tf is less than one, and idf shall be a smaller value too. Guessing c-tf-idf values are not used in the end, see the code below. Can you have a look at it? Thanks.
https://github.com/MaartenGr/BERTopic/blob/10fc8f020d08f9d0ae8d244c170a964ab4fc9ea4/bertopic/_bertopic.py?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L538

**Comment by MaartenGr** [comment]
@lkluo When you use `visualize_topics_over_time`, the y-axis does not represent the c-TF-IDF values but the frequency of the topic itself. In other words, it shows how frequent each topic was at a specific timestamp. The c-TF-IDF values for each topic are used to calculate the topic representations but are not used within the visualization itself as its main purpose is to show topic trends.

**Comment by lkluo** [comment]
Thanks @MaartenGr, it is very clear.
