### ISSUE TITLE
Problems with top_n_words parameter.

### ISSUE THREAD

**Issue by mediote** [MaartenGr/BERTopic#451]
Hi  Maarten.

I'm having some problems with the parameter **top_n_words** . I set the parameter value to 10, but the results are the 5 most frequent words.

Follow the parameters I used:

                       language = 'multilingual',                      
                       top_n_words=10,
                       n_gram_range=(1, 2),
                       min_topic_size=50,   
                       nr_topics = 'auto',        
                       low_memory=True,
                       calculate_probabilities=False, 
                       verbose=True

**Bertopic Version: 0.9.4**

Thanks.

**Comment by MaartenGr** [comment]
I just tried it out myself and I am not getting your issue. Did you try accessing the topic words with `topic_model.get_topic(0)`?

**Comment by mediote** [comment]
I was just looking at the views, so I incorrectly thought it was a problem.

Using the function worked. Thanks.
