### ISSUE TITLE
Custom model training with annotated labels

### ISSUE THREAD

**Issue by nsankar** [MaartenGr/BERTopic#453]
@MaartenGr  kindly let me know how to train/ create a custom topic model using labels pertaining to a specific domain with multiple  categories attribution to a document

1. What should be the format for labels (multiple categories for a doc) e.g. json or csv with a specific structure...
2. How to train and predict 
Thanks in advance

**Comment by MaartenGr** [comment]
If you have labels, then I would advise running a semi-supervised BERTopic instance. To do this, you can follow along with the tutorial [here](https://maartengr.github.io/BERTopic/getting_started/supervised/supervised.html).

**Comment by nsankar** [comment]
@MaartenGr  Ok, I have labels. Thank you.
