### ISSUE TITLE
Use Bertopic output as classification input

### ISSUE THREAD

**Issue by hajarzankadi** [MaartenGr/BERTopic#454]
hello @MaartenGr 
Thank you for this useful package. I trained the bertopic model and generated the topics but what I am interested in, is to use those topics as a classification input.
to do that, I need to generate the feature vector that will contain the weights of the topics and the target will be the topics. is that right ? is there any codes in python you could recommend me or help me with that.
thank you so much

**Comment by MaartenGr** [comment]
So you want to create a predictive model that allows you to predict the topics, right? Out of curiosity, why would you not want to use the `.transform()` function for doing this? 

For any classification algorithm, you will indeed need a feature vector (i.e., X) and the target (i.e., y). Here, I am not entirely sure what you mean with the `weights of the topics` as the feature vector. Are you referring to the probability matrix of each document belonging to a topic? Or are you referring to the c-TF-IDF matrix?

To generate your feature vector, there are a number of options that you can choose from, depending on whether you want features on a document- or topic level:

**Topic level**:
* c-TF-IDF matrix that you can access through `topic_model.c_tf_idf`
* The topic embeddings that you can access through `topic_model.topic_embeddings`

**Document level**:
* The document embeddings: `topic_model._extract_embeddings(docs, method="document"`)
* The reduced document embeddings: `topic_model._reduce_dimensionality(embeddings)`

These are the more straightforward options. There are a few more nuanced variations but that is likely to be a bit out-of-scope here.

**Comment by hajarzankadi** [comment]
Thank you for your quick answer
After reading your reply, I realized that I will not need to do any kind of classification.
Actually,  I believe that each document will be mapped to a range of topics with certain probabilities. So I would like to generate like the top 3 topics (Get the 3 dominant topic for each document). 
![get dominant topic](https://user-images.githubusercontent.com/44951948/155515392-45261cbf-c8d8-48c8-9605-6e07a3d0003f.png)

in the fig above, instead of the dominant topic, I would like to see something like the top K dominant topic, is that possible using the document-topic matrix, which I think it will be the use of topic_model._extract_embeddings(docs, method="document"). i am still figuring out how to make it work. 
Thank you

**Comment by MaartenGr** [comment]
The visualization that you provided above is exactly what you get in the `probs` variable after running BERTopic with `calculate_probabilities=True`. So using that `probs` variable should give you the possibility to extract the top K dominant topics per document. For that, you do not need to be using `topic_model._extract_embeddings(docs, method="document")` since the `probs` variable is the document-topic matrix that you are looking for.

**Comment by hajarzankadi** [comment]
I used probs as mentioned, and I get the dominant topic for each document
Thank you

**Comment by MaartenGr** [comment]
Glad to hear that it worked out!

**Comment by imchlai** [comment]
> 

Hi, 
May I ask how you outputed this table? I've run fit_tranform, with calculate_probabilities=True. But not sure the exact command line of generating this table that displays each document and its repsective probabilities for each topic. 

Here is my command:
topic_model = BERTopic(calculate_probabilities=True)
topics, probabilities = topic_model.fit_transform(doc)

Thank you!

**Comment by imchlai** [comment]
> 



> Glad to hear that it worked out!

Sorry, Maarten, can I ask you the same question I asked hajarzankadi? I've tried to figure out how to generate a table that displays each document and its repsective probabilities for each topic. Not sure the exact command line. 

Thank you!

**Comment by MaartenGr** [comment]
@imchlai If I am not mistaken, I believe you already have that in the `probabilities` variable if you set `calculate_probabilities=True`. The `probabilities` then contains the probability of each topic for each document.

**Comment by hajarzankadi** [comment]
> > 
> 
> Hi hajarzankadi, May I ask how you outputed this figure? I've run fit_tranform, with calculate_probabilities=True. But not sure the exact command line of generating this table that displays each document and its repsective probabilities for each topic.
> 
> Here is my command: topic_model = BERTopic(calculate_probabilities=True) topics, probabilities = topic_model.fit_transform(doc)
> 
> Thank you!

hi @imchlai 
this is the code I used to output the above figure:
```
import numpy as np
# Create Document - Topic Matrix
doc_topic_matrix = probs

# column names
topicnames = ["Topic" + str(i) for i in range(len(set(topics))-1)]

# index names
docnames = ["Doc" + str(i) for i in range(len(docs))]

# Make the pandas dataframe
df_document_topic = pd.DataFrame(np.round(doc_topic_matrix, 2), columns=topicnames, index=docnames)

# Get dominant topic for each document
dominant_topic = np.argmax(doc_topic_matrix, axis=1)
df_document_topic['dominant_topic'] = dominant_topic

# Styling
def color_green(val):
    color = 'green' if val > .1 else 'black'
    return 'color: {col}'.format(col=color)

def make_bold(val):
    weight = 700 if val > .1 else 400
    return 'font-weight: {weight}'.format(weight=weight)

# Apply Style
df_document_topics = df_document_topic.head(15).style.applymap(color_green).applymap(make_bold)
```
As mentioned by @MaartenGr , you need to set calculate_probabilities to True while training your model. also, "**probs**" is "probabilities". 
if you still need more help or explanation, let me know

**Comment by imchlai** [comment]
> def color_green(val):
>     color = 'green' if val > .1 else 'black'
>     return 'color: {col}'.format(col=color)
> 
> def make_bold(val):
>     weight = 700 if val > .1 else 400
>     return 'font-weight: {weight}'.format(weight=weight)
> 
> # Apply Style
> df_document_topics = df_document_topic.head(15).style.applymap(color_green).applymap(make_bold)

Thanks! It works!!

**Comment by hajarzankadi** [comment]
> > def color_green(val):
> > color = 'green' if val > .1 else 'black'
> > return 'color: {col}'.format(col=color)
> > def make_bold(val):
> > weight = 700 if val > .1 else 400
> > return 'font-weight: {weight}'.format(weight=weight)
> > # Apply Style
> > df_document_topics = df_document_topic.head(15).style.applymap(color_green).applymap(make_bold)
> 
> Thanks! It works!!

Glad to hear that
