### ISSUE TITLE
How to assign Topics with Names to the dataframe using model.get_topic_info()['Name'] or is there any other way to assign the documents in dataframe

### ISSUE THREAD

**Issue by nk6june** [MaartenGr/BERTopic#456]
![image](https://user-images.githubusercontent.com/42600970/155514540-10c55cf6-a890-4a31-a0cb-bacb1c613ae3.png)

**Comment by MaartenGr** [comment]
Whenever your run `model.get_topic_info()`, a dataframe will be returned that you can change to your liking. In that dataframe, you can already see a few words of the topic representation which should give you an indication of the possible name. Does that answer your question?

**Comment by MaartenGr** [comment]
Closing this for now. However, if you want to discuss this further, let me know and I'll make sure to reopen the issue!
