### ISSUE TITLE
BERTOPIC dont intalling in VISUAL Studio code

### ISSUE THREAD

**Issue by davimaia01** [MaartenGr/BERTopic#460]
Hi,
I'm trying to install bertopic, but i'm having a error with the scikit learn like the image below.

Thanks by help and responses.

![image](https://user-images.githubusercontent.com/66649761/156017589-54227535-c220-4c81-bac6-c767b324d990.png)
![image](https://user-images.githubusercontent.com/66649761/156017658-db35b6ef-237c-4c98-a69c-28cea0ecf231.png)

**Comment by MaartenGr** [comment]
Ah, HDBSCAN requires Microsft Visual C++ 14.0 or greater. I would advise installing it with the link provided in your error message. Hopefully, that fixes your issue.

**Comment by How-Wang** [comment]
I encounter similar version problem too, when downloading hdbscan.
Then I try to install the recommend package from error message, but it still fail due to version problem.
Finally, **I used a empty `anoconda` env** to solve it, hoping that can help you.
