### ISSUE TITLE
Word Embeddings

### ISSUE THREAD

**Issue by nermeetadhillon** [MaartenGr/BERTopic#462]
For the def _extract_words_per_topic function in the class BERTopic, I am trying to extract the word embeddings of the top 30 words for each topic, but I am getting confused with the parameter words, like what we have to input to get the word embeddings of the top 30 words.

**Comment by nermeetadhillon** [comment]
I am trying to get the word in each topic and the word embeddings associated with the word, however I am struggling.

**Comment by MaartenGr** [comment]
The `_extract_words_per_topic` is an internal function on purpose, as it is not meant for general use outside of the internal functioning of BERTopic. However, if you want to extract the word embeddings for certain words, you can use the following instead after fitting a BERTopic model:

```python
embeddings = topic_model._extract_embeddings(words, method="word", verbose=False)
```

where `words` is a list of strings.

**Comment by MaartenGr** [comment]
Since this issue has been active a while ago, I am going ahead and will close this. Having said that, if you have any further questions, please let me know!
