### ISSUE TITLE
Similarity threshold for automatic topic reduction

### ISSUE THREAD

**Issue by gio3b2** [MaartenGr/BERTopic#464]
Is it possible to change the minimum similarity required to merge topics with automatic topic reduction? While this reduction topics already does a pretty good job at reducing the number of topics, my exercise would gain from further reducing the number of topics by merging those with a lower similarity, say at least 0.5. If this is not possible within this technique, is there another tool within this platform to achieve this goal?

**Comment by MaartenGr** [comment]
If you want to merge the topics even further, I would advise not using the automatic topic reduction method as it uses HDBSCAN to cluster the existing clusters. Instead, use `nr_topics=some_integer` to define the number of topics that you are looking for. That way, you can merge more topics than you would if using the automatic topic reduction. 

Also, note that the automatic topic reduction is not using a minimum similarity score as it used to but instead uses HDBSCAN to automatically merge the topics.

**Comment by MaartenGr** [comment]
This issue has been active a while ago, so I am going to close this for now. If you still run into this issue or any other for that matter, please let me know!
