### ISSUE TITLE
Change number of rows and columns in BERTopic().visualize_barchart

### ISSUE THREAD

**Issue by pradeepgadkari** [MaartenGr/BERTopic#465]
I am trying to visualize a barchart using BERTopic().visualize_barchart. The figure below has has 4 rows and 4 columns, is it possible to change it to 5 rows and 3 columns ?
![image](https://user-images.githubusercontent.com/64259538/156730359-332fafbd-a967-45a9-9c4d-c13ef77b0460.png)

**Comment by MaartenGr** [comment]
Currently, that is not possible as I want to have the visualizations quite similar in the parameters that they contain. Having said that, you can use the code [here](https://github.com/MaartenGr/BERTopic/blob/master/bertopic/plotting/_barchart.py) and simply change the `columns = 4` to whatever value you are looking for.

**Comment by pradeepgadkari** [comment]
I will make the changes in function. Thanks for your help.
