### ISSUE TITLE
Error when saving a model which uses tensorflow_hub use

### ISSUE THREAD

**Issue by armandanusca** [MaartenGr/BERTopic#470]
My code is along the lines:
`
embedding_model = tensorflow_hub.load(
        "https://tfhub.dev/google/universal-sentence-encoder/4")
topic_model = BERTopic(verbose=True, language="english", nr_topics="auto",
                           embedding_model=embedding_model)
topic_model.save(f"models/BERTopic_model_{parameters_str}")
`

And the error that I get is:
`
[PicklingError: Can't pickle <class 'tensorflow.python.saved_model.load.Loader._recreate_base_user_object.<locals>._UserObject'>: it's not found as tensorflow.python.saved_model.load.Loader._recreate_base_user_object.<locals>._UserObject]()
`

**Comment by MaartenGr** [comment]
It seems that I am getting the same error as you when trying to save that particular model. I am not familiar with the error but you can also save the topic model without the embedding by adding `save_embedding_model=False` when trying to save the topic model. That should prevent those errors from happening. Then, when loading in the topic model, you can simply load in the embedding model with it as mentioned [here](https://maartengr.github.io/BERTopic/getting_started/quickstart/quickstart.html#saveload-bertopic-model).
