### ISSUE TITLE
Using BerTopic and PyCaret 

### ISSUE THREAD

**Issue by seannjk** [MaartenGr/BERTopic#471]
Hey @MaartenGr, came across BerTopic after getting recommendations from my lecturer. Have to say it’s amazing. 

Right now, I have a dataset containing tweets and labels(0= Pro-vaccine, 1= antivaccine covid)
I plan to use BerTopic to transform my dataset , and use pycaret afterwards to create a classification model. 

Q1) For the tweets, do i need to clean the tweets first (eg regex) before using BerTopic? What happens to the emoji and hashtags if I do not need to clean the tweets and let BerTopic process the raw tweets? 

Q2) How do I create feature vectors (ie X variable)? I plan to concat this with the current labels that comes with the dataset and use it for pycaret. 

Thank you!

**Comment by MaartenGr** [comment]
Since this issue has not been active for a while, I am going to close this for now. Having said that, if you want to discuss this further, please let me know.
