### ISSUE TITLE
Issue loading previously saved model

### ISSUE THREAD

**Issue by maxsossin** [MaartenGr/BERTopic#474]
Hello there, I am trying to load a previously saved BERTopic model but I keep on seeing this error:

-------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-11-d61b13ac3707>](https://localhost:8080/#) in <module>()
----> 1 topic_model = BERTopic.load("INCEL_500K")

5 frames
[/usr/local/lib/python3.7/dist-packages/numba/core/serialize.py](https://localhost:8080/#) in _unpickle__CustomPickled(serialized)
    206     @abc.abstractclassmethod
    207     def _rebuild(cls, **kwargs):
--> 208         raise NotImplementedError
    209 
    210     # Subclass can override the below methods

TypeError: code() takes at most 15 arguments (16 given)

Do you have any idea what could be causing it or what could fix it? Any help would be greatly appreciated.

**Comment by MaartenGr** [comment]
Although I am not familiar with the error, it does seem that you are using a different version of BERTopic when loading the model compared to saving it. Make sure that the environment in which the model was loaded is the same as when you saved it.

**Comment by MaartenGr** [comment]
Since this issue has not been active for a while, I am going to close this for now. Having said that, if you want to discuss this further, please let me know.
