### ISSUE TITLE
Transforming a new doc: Getting its representative terms for each model topic

### ISSUE THREAD

**Issue by GiorgosPeikos** [MaartenGr/BERTopic#476]
Hello, 

Suppose that we have trained a model and we employ the transform function on a new document. Is it possible to get the document's terms that belong to each model's topic?

**Comment by MaartenGr** [comment]
After you have trained a BERTopic model on a number of documents through either `.fit` or `.fit_transform` you can get the terms that belong to each topic through `.get_topic_info`. Whenever you use the `transform` function to assign a new document to a topic, that topic is not a newly generated topic. So you can use `.get_topic_info` or `.get_topic` to get the terms that belong to the document's topic.
