### ISSUE TITLE
Words per topic

### ISSUE THREAD

**Issue by san7988** [MaartenGr/BERTopic#479]
Hi,

Thanks for this amazing library. 

I have been using it and it has been super useful. 

I have one query/doubt. 
If I provide custom embeddings, bertopic doesnot trim the words per topic and the output contains 30 words per topic. However if I allow Bertopic to generate the embeddings itself, it trims down the topics to configured top_n_words parameter. 

What is the intuition behind this? Can someone explain please?

Thanks,
Sanjeev

**Comment by MaartenGr** [comment]
Hmmm, which version of BERTopic are you using? Also, could you share the code for training the model? What you are describing does sound familiar but I remember it being from an older version.

**Comment by san7988** [comment]
Hi Maarten,

Sorry for the late reply.

We were using version 0.6.0 when we observed this behavior. We tried updating to latest version as well but behavior remains the same. The latest version we tried was 0.9.x.

The code is something similar to:

`topic_model.fit_transform(document=document_df, embeddings=document_embedding)`

 

If `document_embedding` is not `None`, then the topics are not trimmed and they stay at 30 tokens per topic.

I was trying to read through the code to check the reason behind this behavior. Will it be okay if I submit a PR incase I'm able to resolve the issue?

Thanks,
Sanjeev

**Comment by MaartenGr** [comment]
> I was trying to read through the code to check the reason behind this behavior. Will it be okay if I submit a PR incase I'm able to resolve the issue?

Sure! I should note though that I am not able to reproduce your issue so it might be best if we can first find the exact issue. 
I am using BERTopic v0.9.4 as is run as follows:

```python
from sklearn.datasets import fetch_20newsgroups
from sentence_transformers import SentenceTransformer
from bertopic import BERTopic

# Prepare embeddings
docs = fetch_20newsgroups(subset='all',  remove=('headers', 'footers', 'quotes'))['data']
sentence_model = SentenceTransformer("all-MiniLM-L6-v2")
embeddings = sentence_model.encode(docs, show_progress_bar=True)

# Train model
topic_model = BERTopic()
topics, probs = topic_model.fit_transform(docs, embeddings)
```

Then, when I run `topic_model.get_topic(0)`, I get the top 10 words in the topic. It is the same if I run the following:

```python
topic_model = BERTopic()
topics, probs = topic_model.fit_transform(docs)
topic_model.get_topic(0)
```

In both cases, `top_n` is set to 10 as a default. When I use `top_n_words=20` I get the top 20 words in both cases so unfortunately I am not able to reproduce the issue with v0.9.4. Did you try it with the latest version?

**Comment by san7988** [comment]
Hi Maarten,

I tried with version 0.9.0. 
Let me test again at my end. I'll get back with latest test results. 

Regards,
Sanjeev
