### ISSUE TITLE
Memory issues in notebook

### ISSUE THREAD

**Issue by meyerjoe-R** [MaartenGr/BERTopic#484]
Hey Marteen, 

We had some questions about memory. 

We are trying to run bertopic on 100k short documents in a notebook and there seems to be a memory issue.

Based on your recommendations, we have tried several things:

Using gpu for sentence embeddings
Didn't calculate probabilities
setting low_memory = True
Used smaller sentence embedding model
Customized count vectorizer for document term matrix to only tokenize unigrams, and set a minimum document frequency of 100

We receive the error: A worker process managed by the executor was unexpectedly terminated. This could be caused by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker.

It seems that the sentence embeddings are successfully created, and umap works. This occurs during the clustering algo according to progress while verbose = True

**Comment by MaartenGr** [comment]
Could you share the code for training and initializing BERTopic? Also, how much RAM do you have in your environment? Lastly, which versions of BERTopic, HDBSCAN, UMAP, Numpy, and Numba are you running? 

From what I can remember, the error stems from HDBSCAN which might have issues clustering large data if you do not have sufficient RAM. There might also be some [settings](https://github.com/scikit-learn-contrib/hdbscan/issues/345) related to this but I cannot be sure.

**Comment by meyerjoe-R** [comment]
if len(df) > 50000:
    mem = True
    calc_prob = False
    vec_model = CountVectorizer(ngram_range=(1, 1), stop_words="english", min_df=100)
else:
    mem = False
    calc_prob = True
    vec_model = CountVectorizer(ngram_range=(1, 3), stop_words="english")



if torch.cuda.is_available():
        print("gpu being utilized")
    # specify the pretrained model
    if len(df) > 50000:
        sentence_model = SentenceTransformer("all-MiniLM-L6-v2")
        print("low memory consumption embedding model loaded")
    else:
        sentence_model = SentenceTransformer("all-mpnet-base-v2")
        print("base embedding model loaded")

    # sentence_model = SentenceTransformer("distilbert-base-nli-mean-tokens", device="cpu")
    # sentence_model = SentenceTransformer("xlm-r-bert-base-nli-stsb-mean-tokens", device="cpu")
    # sentence_model = SentenceTransformer("roberta-base-nli-stsb-mean-tokens", device="cpu")
    # sentence_model = SentenceTransformer("nq-distilbert-base-v1", device="cpu")
    # sentence_model = SentenceTransformer("stsb-roberta-large", device="cpu")

    # possible combinations

    # num_topics Auto and min topic auto
    # num topics specified and min topic size auto
    # num topics auto and min top size specified

    if num_topics == "auto" and minimum_topic_size == "auto":
        topic_model = BERTopic(
            language="english",
            embedding_model=sentence_model,
            low_memory=mem,
            calculate_probabilities=calc_prob,
            vectorizer_model=vec_model,
            verbose=True,
        )

    elif num_topics != "auto" and minimum_topic_size == "auto":
        num_topics = int(num_topics)
        topic_model = BERTopic(
            language="english",
            embedding_model=sentence_model,
            nr_topics=num_topics,
            low_memory=mem,
            calculate_probabilities=calc_prob,
            vectorizer_model=vec_model,
            verbose=True,
        )

    elif num_topics != "auto" and minimum_topic_size != "auto":
        num_topics = int(num_topics)
        minimum_topic_size = int(minimum_topic_size)
        topic_model = BERTopic(
            language="english",
            embedding_model=sentence_model,
            nr_topics=num_topics,
            min_topic_size=minimum_topic_size,
            low_memory=mem,
            calculate_probabilities=calc_prob,
            vectorizer_model=vec_model,
            verbose=True,
        )

    elif num_topics == "auto" and minimum_topic_size != "auto":
        minimum_topic_size = int(minimum_topic_size)
        topic_model = BERTopic(
            language="english",
            embedding_model=sentence_model,
            min_topic_size=minimum_topic_size,
            low_memory=mem,
            calculate_probabilities=calc_prob,
            vectorizer_model=vec_model,
            verbose=True,
        )

    else:
        raise ValueError("topic model parameters not specified correctly")

**Comment by MaartenGr** [comment]
Based on your code, there are some things that might be related. First, setting a higher `min_topic_size` (to around 300) might be helpful, as well as lowering `min_samples` in UMAP as mentioned in the issue I referenced. Second, it might be related to your environment since a number of different settings are not working for you. Could you share all versions in your environment including the python version? 

> The machine has around 50 RAM.

Do you mean 50GB of RAM?

**Comment by meyerjoe-R** [comment]
I've tried both min_samples and min_topic_size with no luck. 

![Screen Shot 2022-06-03 at 2 20 03 PM](https://user-images.githubusercontent.com/76498051/171954780-11d79b66-62db-4ac6-9bde-e21e81df59d0.png)

**Comment by MaartenGr** [comment]
Thank you for sharing that info. Having said that, I am still missing the HDBSCAN, UMAP, Numpy, and Numba versions, as well as the python version that you are using. 

Based on what is happening, I would advise starting from a completely fresh environment and installing BERTopic there. HDBSCAN has gone through some optimizations in its latest release which might help you fix this issue. Hopefully, hitting the reset button here solves your memory problems!

**Comment by MaartenGr** [comment]
Due to inactivity, I'll be closing this for now. Let me know if you have any other questions related to this and I'll make sure to re-open the issue!
