### ISSUE TITLE
Plot customization

### ISSUE THREAD

**Issue by Huertas97** [MaartenGr/BERTopic#49]
Hi Maarten!

Firstly, congratulations for your work. 

I would like to suggest you allow the BERTopic "_plotly_topic_visualization" function from "visualize_topics()" to not only show the plotly figure but also to return the figure as a variable. This will be useful because with the figure in a variable the user can download the figure as HTML, pdf etc. In my case, I would like to embed the figure in a Dashboard. 

Besides, I would suggest you allow the user to access to the parameters used during the Topic Modelling (i.e, UMAP, HDBSCAN, plotly visualization).

**Comment by MaartenGr** [comment]
Thank you! That is a fair request which I will make sure to put on the roadmap for v0.5 (#46). I am not quite sure how exactly I want to implement it, as some users might simply want the visualization without any additional steps, so perhaps there will be the option to return the figure in some cases. 

You can already access the parameters to the UMAP and HDBSCAN models using `model.umap_model` and `model.cluster_model` where `model` is the trained BERTopic instance. I could look into a function that allows you to extract all model parameters and return them as a dictionary... The difficulty here is that there might be an overload of information if default values are also shown. For example, it is not really interesting to return the default value of `target_metric` in UMAP as this is not a supervised approach.

**Comment by MaartenGr** [comment]
@Huertas97 I just release BERTopic v0.5 which returns the plotly figure when running `visualize_topics()`. Furthermore, you can now use custom UMAP, HDBSCAN, and CountVectorizer models. Finally, use `get_params()` to get all parameters related to BERTopic.

**Comment by Huertas97** [comment]
Thank you so much! Sorry for the late reply. Nice work!
