### ISSUE TITLE
How to get the word distribution per topic ?

### ISSUE THREAD

**Issue by yuanfz98** [MaartenGr/BERTopic#490]
Hi community,

In genism LDA we have method get_topics() to get the term-topic matrix learned during inference. It's the word distribution for each topic. 
Is there a way to get such matrix in bertopic ?

Thanks for your help.

**Comment by MaartenGr** [comment]
It is possible to extract the term-topic matrix if you are not using MMR to diversify the results. The reason for this is that after generating the topic representations with c-TF-IDF, MMR is used to re-order the top n words in each topic. In that case, the c-TF-IDF matrix (term-topic matrix) will not be entirely representative of the results that you get when using MMR. 

Having said that, if you do not set any `diversity` when initiating BERTopic, then you can access the term-topic matrix through `topic_model.c_tf_idf`.

**Comment by yuanfz98** [comment]
> It is possible to extract the term-topic matrix if you are not using MMR to diversify the results. The reason for this is that after generating the topic representations with c-TF-IDF, MMR is used to re-order the top n words in each topic. In that case, the c-TF-IDF matrix (term-topic matrix) will not be entirely representative of the results that you get when using MMR.
> 
> Having said that, if you do not set any `diversity` when initiating BERTopic, then you can access the term-topic matrix through `topic_model.c_tf_idf`.

Thanks for your help !
