### ISSUE TITLE
umap import error

### ISSUE THREAD

**Issue by kalki7** [MaartenGr/BERTopic#497]
While running BERTopic right out of the box, I got this error.
**ImportError: cannot import name 'UMAP' from 'umap'**

umap-learn  v0.5.2
bertopic       v0.9.4

**Comment by kalki7** [comment]
Issue reolved after changing 

**from umap import UMAP**
to
**from umap.umap_ import UMAP**

in the following files 
/bertopic/plotting/_topics.py
/bertopic/_bertopic.py

**Comment by spookyuser** [comment]
Also having this happen and on the latest version of both bertopic and umap-learn

**Comment by MaartenGr** [comment]
@spookyuser This often happens if you have another umap package installed that tends to be used over umap-learn or whenever you have a file named `umap.py`. In practice, starting from a completely fresh environment and installing BERTopic there should work.

**Comment by spookyuser** [comment]
Thanks for the tip! I did uninstall all umap packages like the answers here suggested https://stackoverflow.com/questions/57242208/how-to-resolve-the-error-module-umap-has-no-attribute-umap-i-tried-installi but the only thing that resolved it was changing the files like @kalki7 did
