### ISSUE TITLE
tutorial bug?

### ISSUE THREAD

**Issue by ddobokki** [MaartenGr/BERTopic#503]
first thanks for good library! and i read paper very interest.

i found minor bug

in README.md, in the table of contents [Getting Started] colab code of [(Custom) Embedding Models in BERTopic]
```python
!pip install bertopic[all]
```
is not working and as reslut 
```python
from flair.embeddings import TransformerDocumentEmbeddings
```
is not work

i solved that's problem simply run `!pip install bertopic[flair] `  but i don't know why `!pip install bertopic[all]` is not working

Sorry for the short English and thank you again for the good library!

**Comment by MaartenGr** [comment]
Good catch, thanks! I removed the `all` option as there were quite a number of dependency conflicts happening if you try to install all back-ends at once. I'll make sure the notebook is updated.
