### ISSUE TITLE
option to remove sentence transformers dependency for install

### ISSUE THREAD

**Issue by christianj6** [MaartenGr/BERTopic#504]
**Overview**
Currently sentence-transformers>=0.4.1 is listed in the base_packages required for any installation. However, if one is only using your library with precomputed embeddings (by passing embeddings and texts directly to the BERTopic constructor), then is it perhaps possible to avoid this dependency and thus reduce the ultimate deployment package size? I understand if such an option would compromise the library functionality and thereby be an undesirable feature; just asking if such a thing would be possible from your side.

**Request Details**
- option to remove sentence-transformers dependency during installation
- under these installation parameters, the library can still be used for BERTopic analysis with precomputed embeddings only

Thank you for your time.

**Comment by MaartenGr** [comment]
Thank you for the extensive description! As you mentioned, this would indeed compromise the out-of-the-box functionality of the technique as users will have to manually install sentence-transformers to create the embeddings. 

Although there is the option to install BERTopic without any dependencies using `pip install bertopic pip install --no-deps`, sentence-transformers is the default model to be used when creating a BERTopic instance. Removing that may introduce some difficulties using BERTopic out-of-the-box.

**Comment by christianj6** [comment]
Hi, thank you for your quick and thoughtful response.

Of course the out-of-the-box functionality cannot be compromised; the clarification is much appreciated. 
Perhaps the mentioned ```--no-deps``` approach offers a workaround  for the situation I originally described.

In any case I will close the issue as there is no further need for discussion. Thanks again for your prompt answer.
