### ISSUE TITLE
ValueError: dimension mismatch on topics_over_time()

### ISSUE THREAD

**Issue by ubiest** [MaartenGr/BERTopic#507]
I trained a topic model on a corpus of 1093 documents, applied CountVectorizer() from sklearn

```
vectorizer_model = CountVectorizer(stop_words = custom_stopwords, ngram_range=[1,3])

first_tm = BERTopic(
                    language="english", 
                    calculate_probabilities = True, 
                    verbose = True, 
                    top_n_words = 12, 
                    min_topic_size = 10,
                    n_gram_range = (1,3),
                    vectorizer_model = vectorizer_model,
                    umap_model = umap_model,
                    )

first_tm_topics_over_time = first_tm.topics_over_time(docs, first_topics, timestamps)
```

Got the error message:
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[<ipython-input-39-d47f5e79d02e>](https://localhost:8080/#) in <module>()
----> 1 first_tm_topics_over_time = first_tm.topics_over_time(docs, first_topics, timestamps)

3 frames
[/usr/local/lib/python3.7/dist-packages/scipy/sparse/base.py](https://localhost:8080/#) in __mul__(self, other)
    481         if issparse(other):
    482             if self.shape[1] != other.shape[0]:
--> 483                 raise ValueError('dimension mismatch')
    484             return self._mul_sparse_matrix(other)
    485 

ValueError: dimension mismatch

This appears linked to the use of a custom count_vectorizer, but I cannot figure out what I should do to solve the dimension mismatch.

**Comment by MaartenGr** [comment]
Hmmm, I have not seen this error before when running `topics_over_time`. From your code, it seems that the model is not fitted which may imply that this is not the entire code for running BERTopic. If so, could you share the entire pipeline? Also, is that the complete error message that you are getting? Typically, you will also find where in BERTopic the code originated from. 

One thing that I noticed was that you passed `ngram_range` in the `CountVectorizer` as a list whereas it is supposed to be a tuple. I am not entirely sure if this is the issue but it might be worth trying to switch it to a tuple instead and see if that helps.

**Comment by ubiest** [comment]
Thanks Maarten, for the quick reply.

yes, the model is fitted. Full code below

```
vectorizer_model = CountVectorizer(stop_words = custom_stopwords, ngram_range=(1,3))
umap_model = UMAP(n_neighbors=15, n_components=5, 
                  min_dist=0.0, metric='cosine', random_state=99)

first_tm = BERTopic(
                    language="english", 
                    calculate_probabilities = True, 
                    verbose = True, 
                    top_n_words = 12, 
                    min_topic_size = 10,
                    n_gram_range = (1,3),
                    vectorizer_model = vectorizer_model,
                    umap_model = umap_model,
                    )
first_topics, first_probs = first_tm.fit_transform(docs)
first_tm_topics_over_time = first_tm.topics_over_time(docs, first_topics, timestamps)

```

Here is the full error trace, right after executing the above line

0it [00:00, ?it/s]
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[<ipython-input-35-d47f5e79d02e>](https://localhost:8080/#) in <module>()
----> 1 first_tm_topics_over_time = first_tm.topics_over_time(docs, first_topics, timestamps)

3 frames
[/usr/local/lib/python3.7/dist-packages/bertopic/_bertopic.py](https://localhost:8080/#) in topics_over_time(self, docs, topics, timestamps, nr_bins, datetime_format, evolution_tuning, global_tuning)
    485             documents_per_topic = selection.groupby(['Topic'], as_index=False).agg({'Document': ' '.join,
    486                                                                                     "Timestamps": "count"})
--> 487             c_tf_idf, words = self._c_tf_idf(documents_per_topic, fit=False)
    488 
    489             if global_tuning or evolution_tuning:

[/usr/local/lib/python3.7/dist-packages/bertopic/_bertopic.py](https://localhost:8080/#) in _c_tf_idf(self, documents_per_topic, fit)
   1592             self.transformer = ClassTFIDF().fit(X, multiplier=multiplier)
   1593 
-> 1594         c_tf_idf = self.transformer.transform(X)
   1595 
   1596         self.topic_sim_matrix = cosine_similarity(c_tf_idf)

[/usr/local/lib/python3.7/dist-packages/bertopic/_ctfidf.py](https://localhost:8080/#) in transform(self, X)
     69         if self.use_idf:
     70             X = normalize(X, axis=1, norm='l1', copy=False)
---> 71             X = X * self._idf_diag
     72 
     73         return X

[/usr/local/lib/python3.7/dist-packages/scipy/sparse/base.py](https://localhost:8080/#) in __mul__(self, other)
    481         if issparse(other):
    482             if self.shape[1] != other.shape[0]:
--> 483                 raise ValueError('dimension mismatch')
    484             return self._mul_sparse_matrix(other)
    485 

ValueError: dimension mismatch


Whereas this pipeline, which uses text with the stopwords filtered out beforehand works without issue

```
spacy_tm = BERTopic(
                    language="english", 
                    calculate_probabilities = True, 
                    verbose = True, 
                    top_n_words = 12, 
                    min_topic_size = 10,
                    n_gram_range = (1,3),
                    umap_model = umap_model,
                    )
spacy_topics, spacy_probs = spacy_tm.fit_transform(clean_docs)
spacy_topics_over_time = spacy_tm.topics_over_time(clean_docs, spacy_topics, timestamps)

```

I hope this is helpful

**Comment by MaartenGr** [comment]
Strange, I have trouble reproducing your issue with the 20NewsGroups dataset. Seeing as it suddenly works with your spacy pipeline, it indeed might be relevant to the `CountVectorizer`. I was wondering, what would happen if you set the `stop_words`  parameter to whatever language your documents are in? It might be that the custom stopwords you are using are quite strict and result in empty documents/topics.

**Comment by ubiest** [comment]
Figured it out, the stopwords must be a `set` rather than a `list`, then the bug disappears. I am nonetheless puzzled why this only arises on `topics_over_time()` and not anywhere else.

**Comment by shohil-kishore** [comment]
I experienced the same issue with `CountVectorizer` and `topics_over_time()`, it looks like it's due to empty topics. This has been an issue for both small (~3,000) and relatively large (~300,000) datasets.
