### ISSUE TITLE
Error loading model from disk

### ISSUE THREAD

**Issue by mediote** [MaartenGr/BERTopic#508]
When I use the model load feature, the following error occurs: "AttributeError: module 'transformers.activations' has no attribute 'GELUActivation'"

topic_model = BERTopic.load("./mymodel")

**Comment by MaartenGr** [comment]
Although I am not familiar with the missing `GELUActivation` it does seem to stem from dependency issues. In other words, it might be that you saved BERTopic in one environment and loaded it in another that has different versions of dependencies (e.g., huggingface). 

Did you make sure that the dependencies are the same between environments?

**Comment by mediote** [comment]
I found that the problem is referenced to numba and numpy version.
I'll try to make some updates to the environment.
