### ISSUE TITLE
Question about paper

### ISSUE THREAD

**Issue by mertozlutiras** [MaartenGr/BERTopic#509]
Hello again Maarteen,

I couldn't understand what topk words are you taking for the evaluation of dynamic model in your paper. I wanted to ask you that.

From the library, I see that it's designed in a way that it will return top 5 keywords in DTM, therefore I assume you checked top 5 keywords. Is that true?

And for static models, I assume you are taking top 10 keywords?

**Comment by MaartenGr** [comment]
Yes! For the static models, I indeed took the top 10 keywords and the top 5 keywords were used in DTM. The difference had mostly to do with computational efficiency as I used my personal laptop for the analyses.

**Comment by mertozlutiras** [comment]
Thank you for the quick answer!

As I wanna compare the performance of DTM with static, I wanted to retrieve a higher number of topk (top 10) keywords for dynamic model. I think this functionality is not provided right?

When I looked at your source code, I saw you hardcoded 5 as topk keywords of DTM. Is that correct?

**Comment by MaartenGr** [comment]
I believe you can specify the `topk` in the Trainer class. However, the lda_seq training function indeed does have it hardcoded as 5 which you can just change to either 10 or `self.topk`. It should be noted that the code for the paper is not written to be an out-of-the-box evaluation schema for experimenting with BERTopic. In other words, the code is quick and dirty and I would actually advise using OCTIS in a pipeline yourself as it will allow you much easier customization.

**Comment by mertozlutiras** [comment]
I'm writing the evaluation myself. My question was how to retrieve a higher number of topk keywords after training model.topics_over_time(), in order to use them as an input to my evaluation.

**Comment by MaartenGr** [comment]
Oh, apologies! Yes, as of right now there is no parameter that allows you to select the `top_k` words since only the DataFrame is returned and not the topic representation per *t*. So indeed, you would have to change that value yourself and perhaps also return a set of words aside from the DataFrame.

**Comment by MaartenGr** [comment]
Seeing as this was active a while ago, I am closing this for now. If you run into any issues, please let me know and I'll make sure to re-open it!
