### ISSUE TITLE
huggingface/tokenizers: The current process just got forked, after parallelism has already been used

### ISSUE THREAD

**Issue by paulthemagno** [MaartenGr/BERTopic#51]
I'm having a strange warning during the function `fit_transform`

```python
from bertopic import BERTopic

model_berttopic = BERTopic(language="english", verbose=True, stop_words="english")
topics, probabilities = model_berttopic.fit_transform(documents)
print(topics)
print(probabilities)
model_berttopic.save("bertopic_model")
```

and the output is
```
2021-01-27 11:31:07,461 - BERTopic - Loaded embedding model
2021-01-27 20:53:53,191 - BERTopic - Transformed documents to Embeddings
2021-01-27 20:57:27,904 - BERTopic - Reduced dimensionality with UMAP
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
        - Avoid using `tokenizers` before the fork if possible
        - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
        - Avoid using `tokenizers` before the fork if possible
        - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
        - Avoid using `tokenizers` before the fork if possible
        - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
        - Avoid using `tokenizers` before the fork if possible
        - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
        - Avoid using `tokenizers` before the fork if possible
        - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
```

The program is still running for hours without other logs (I expected **Clustered UMAP embeddings with HDBSCAN**, **Loaded embedding model**, **Transformed documents to Embeddings** and the save of the model). What is happening? There is no feedback of what is doing.

**Comment by MaartenGr** [comment]
Strange, which version of BERTopic are you running? Also, how many documents do you have?

**Comment by paulthemagno** [comment]
Many: 200K documents. Indeed I tried with few documents and all all worked fine.
With this quantity of data I had to insert progress bars because it took many hours to embed the documents (on CPU), about 9 hours. Unfortunately after the embedding, it seems it blocked (still running) on HDBSCAN step.

Version of BERTopic:
```
bertopic               0.4.3
```

**Comment by MaartenGr** [comment]
In that case, I would advise you to set `calculate_probabilities` to False, this is most likely what blocks the progress in the HDBSCAN step. Since BERTopic relies on embeddings, it is typically advised to use GPU. If you do not have one available, then you can use Google Colab with a GPU instead.

**Comment by MaartenGr** [comment]
@paulthemagno BERTopic v0.5 was just released which allows you to set the parameter `low_memory` which should be turned on if you are facing any memory issues. Moreover, `calculate_probabilities` is now automatically set to False to prevent these issues. Full changelog can be found [here](https://maartengr.github.io/BERTopic/changelog.html).

**Comment by leontikos** [comment]
I still have exactly the same warning (however, in the end - after 9h, working on 1 mln short tweets as my documents - the final result is working, i.e., I receive the list of `topics`):

```
2021-12-29 23:54:38,137 - BERTopic - Transformed documents to Embeddings
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
2021-12-30 08:47:55,384 - BERTopic - Reduced dimensionality with UMAP
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
2021-12-30 08:52:22,057 - BERTopic - Clustered UMAP embeddings with HDBSCAN
2021-12-30 08:54:44,008 - BERTopic - Reduced number of topics from 274 to 171
``` 


I am using similar code to @paulthemagno:

```python
topic_model = BERTopic(min_topic_size=400, verbose=True, nr_topics='auto', n_gram_range=(1,3),  low_memory=True)
topics, _ = topic_model.fit_transform(my_data)
```

My bertopic ver: 0.9.4
I use Ubuntu 20.04, RTX 3090. 128GB RAM

**Comment by MaartenGr** [comment]
@vtrokhymenko There are times when I get these warnings but thus far they do not seem to impact either performance or computational efficiency. For now, I am afraid I am not entirely sure how to disable those warnings without disabling too many warnings.

**Comment by AIRobotZhang** [comment]
Hello, I met the same question. That is the program is still running for hours without other logs.
My bertopic version is 0.11.0
When I set calculate_probabilities and low memory following above instructions: 
topic_model = BERTopic(calculate_probabilities=False, low_memory=True)
but I met the following error:
![无标题](https://user-images.githubusercontent.com/20748608/179193002-5dffa3b2-5e46-43ec-a7c6-118735aeddc2.png)

**Comment by MaartenGr** [comment]
@AIRobotZhang It seems the beginning of the error message is missing. Could you share your entire code for running BERTopic and its version? Also, it might be helpful to start from a completely fresh environment and install BERTopic there. Perhaps something is going wrong with the dependencies in your environment.

**Comment by Mosw5871** [comment]
> I still have exactly the same warning (however, in the end - after 9h, working on 1 mln short tweets as my documents - the final result is working, i.e., I receive the list of `topics`):
> 
> ```
> 2021-12-29 23:54:38,137 - BERTopic - Transformed documents to Embeddings
> huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
> To disable this warning, you can either:
> 	- Avoid using `tokenizers` before the fork if possible
> 	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
> 2021-12-30 08:47:55,384 - BERTopic - Reduced dimensionality with UMAP
> huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
> To disable this warning, you can either:
> 	- Avoid using `tokenizers` before the fork if possible
> 	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
> huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
> To disable this warning, you can either:
> 	- Avoid using `tokenizers` before the fork if possible
> 	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
> huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
> To disable this warning, you can either:
> 	- Avoid using `tokenizers` before the fork if possible
> 	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
> huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
> To disable this warning, you can either:
> 	- Avoid using `tokenizers` before the fork if possible
> 	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
> huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
> To disable this warning, you can either:
> 	- Avoid using `tokenizers` before the fork if possible
> 	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
> huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
> To disable this warning, you can either:
> 	- Avoid using `tokenizers` before the fork if possible
> 	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
> 2021-12-30 08:52:22,057 - BERTopic - Clustered UMAP embeddings with HDBSCAN
> 2021-12-30 08:54:44,008 - BERTopic - Reduced number of topics from 274 to 171
> ```
> 
> I am using similar code to @paulthemagno:
> 
> ```python
> topic_model = BERTopic(min_topic_size=400, verbose=True, nr_topics='auto', n_gram_range=(1,3),  low_memory=True)
> topics, _ = topic_model.fit_transform(my_data)
> ```
> 
> My bertopic ver: 0.9.4 I use Ubuntu 20.04, RTX 3090. 128GB RAM

@leontikos May I konw the scale of your data? I also met the same question, the programm is still runing, I really have no idea! 55555~ Besides, @MaartenGr thank you for your work! Is there any solution?

**Comment by MaartenGr** [comment]
@Mosw5871 It might be worthwhile to set the `TOKENIZERS_PARALLELISM` environment variable to `True` in order to prevent the error message from showing up. Do know that although `low_memory=True` will make sure that less memory is used, it will slow down computation. There are also some tricks for speeding up the training process [here](https://maartengr.github.io/BERTopic/getting_started/tips_and_tricks/tips_and_tricks.html#pre-compute-embeddings), [here](https://maartengr.github.io/BERTopic/getting_started/tips_and_tricks/tips_and_tricks.html#speed-up-umap), and [here](https://maartengr.github.io/BERTopic/faq.html#how-can-i-speed-up-bertopic).

**Comment by Mosw5871** [comment]
> @Mosw5871 It might be worthwhile to set the `TOKENIZERS_PARALLELISM` environment variable to `True` in order to prevent the error message from showing up. Do know that although `low_memory=True` will make sure that less memory is used, it will slow down computation. There are also some tricks for speeding up the training process [here](https://maartengr.github.io/BERTopic/getting_started/tips_and_tricks/tips_and_tricks.html#pre-compute-embeddings), [here](https://maartengr.github.io/BERTopic/getting_started/tips_and_tricks/tips_and_tricks.html#speed-up-umap), and [here](https://maartengr.github.io/BERTopic/faq.html#how-can-i-speed-up-bertopic).

Thank you very much! You saved my paper! hhh
