### ISSUE TITLE
Installation dependency issues

### ISSUE THREAD

**Issue by jfb-h** [MaartenGr/BERTopic#512]
Hi, 

BERTopic looks really cool, so thanks for that first of all!

I ran into some issues running the quick start example which I think are related to dependency issues between numpy, torch and numba.

After installing via pip in a clean venv (on Windows), `topic_model.fit_transform(docs)` complains about Numpy not being available. This seems to be the case because of numpy getting downgraded during installation to be compatible with numba (which is required by umap and needs numpy <=1.21). As a result, the installed numpy is not compatible with the numpy compiled into torch anymore, leading to the above error.

I saw your FAQ entry on numpy issues and skimmed through some of the linked discussions but wasn't able to resolve it yet. Do you have any idea how to resolve this?

**Comment by MaartenGr** [comment]
> After installing via pip in a clean venv (on Windows), topic_model.fit_transform(docs) complains about Numpy not being available.

Could you share the error message that you are getting when trying to use `.fit_transform(docs)`? 

> This seems to be the case because of numpy getting downgraded during installation to be compatible with numba (which is required by umap and needs numpy <=1.21).

Could you share the versions of packages that you have in your current environment? Please also include python and BERTopic's version. 

> I saw your FAQ entry on numpy issues and skimmed through some of the linked discussions but wasn't able to resolve it yet. Do you have any idea how to resolve this?

It might depend on the environment in which you are currently working. From a quick look at the dependencies, there does not seem to be any major updates which could explain the issues you are having. My guess would be that it depends on how you have setup your environment and the related dependencies.

**Comment by jfb-h** [comment]
Sure, here's the installed packages:

```
(venv) PS C:\Users\Jakob\Desktop\bertopic_test> pip list
Package               Version
bertopic              0.9.4
certifi               2021.10.8
charset-normalizer    2.0.12
click                 8.1.2
colorama              0.4.4
Cython                0.29.28
filelock              3.6.0
hdbscan               0.8.28
huggingface-hub       0.5.1
idna                  3.3
joblib                1.1.0
llvmlite              0.38.0
nltk                  3.7
numba                 0.55.1
numpy                 1.21.6
packaging             21.3
pandas                1.4.2
Pillow                9.1.0
pip                   22.0.4
plotly                5.7.0
pynndescent           0.5.6
pyparsing             3.0.8
python-dateutil       2.8.2
pytz                  2022.1
PyYAML                5.4.1
regex                 2022.3.15
requests              2.27.1
sacremoses            0.0.49
scikit-learn          1.0.2
scipy                 1.8.0
sentence-transformers 2.2.0
sentencepiece         0.1.96
setuptools            58.1.0
six                   1.16.0
tenacity              8.0.1
threadpoolctl         3.1.0
tokenizers            0.12.1
torch                 1.11.0+cu113
torchaudio            0.11.0+cu113
torchvision           0.12.0+cu113
tqdm                  4.64.0
transformers          4.18.0
typing_extensions     4.2.0
umap-learn            0.5.3
urllib3               1.26.9
```

Here's the error message from the quick start:

```python
>>> topics, probs = topic_model.fit_transform(docs)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Jakob\Desktop\bertopic_test\venv\lib\site-packages\bertopic\_bertopic.py", line 286, in fit_transform
    embeddings = self._extract_embeddings(documents.Document,
  File "C:\Users\Jakob\Desktop\bertopic_test\venv\lib\site-packages\bertopic\_bertopic.py", line 1343, in _extract_embeddings
    embeddings = self.embedding_model.embed_documents(documents, verbose)
  File "C:\Users\Jakob\Desktop\bertopic_test\venv\lib\site-packages\bertopic\backend\_base.py", line 69, in embed_documents
    return self.embed(document, verbose)
  File "C:\Users\Jakob\Desktop\bertopic_test\venv\lib\site-packages\bertopic\backend\_sentencetransformers.py", line 63, in embed
    embeddings = self.embedding_model.encode(documents, show_progress_bar=verbose)
  File "C:\Users\Jakob\Desktop\bertopic_test\venv\lib\site-packages\sentence_transformers\SentenceTransformer.py", line 196, in encode
    all_embeddings = np.asarray([emb.numpy() for emb in all_embeddings])
  File "C:\Users\Jakob\Desktop\bertopic_test\venv\lib\site-packages\sentence_transformers\SentenceTransformer.py", line 196, in <listcomp>
    all_embeddings = np.asarray([emb.numpy() for emb in all_embeddings])
RuntimeError: Numpy is not available
```

And here's the warning I get when I import numpy and torch in a new session:

```python
>>> import numpy
>>> import torch
C:\Users\Jakob\Desktop\bertopic_test\venv\lib\site-packages\torch\_masked\__init__.py:223: UserWarning: Failed to initialize NumPy: module compiled against API version 0xf but this version of numpy is 0xe (Triggered internally at  ..\torch\csrc\utils\tensor_numpy.cpp:68.)
  example_input = torch.tensor([[-3, -2, -1], [0, 1, 2]])
```

**Comment by MaartenGr** [comment]
Since you installed torch before installing BERTopic, the issue might stem from that action. After a quick search, I found [this](https://discuss.pytorch.org/t/numpy-is-not-available-error/146192/2) which makes me believe that it might be due to using python 3.10 to install pytorch on windows. Using python 3.7-3.9 instead might solve your issue.

**Comment by jfb-h** [comment]
Ah thanks, I'll test with an older python version and maybe also on WSL and come back when I know more!

**Comment by jfb-h** [comment]
Downgrading to python 3.9 seems to have done the trick. Thanks for the help!
