### ISSUE TITLE
Question about comparison 

### ISSUE THREAD

**Issue by dex426** [MaartenGr/BERTopic#513]
Hello, 

I've been using the BERTopic package a lot recently and I'm really impressed with it. However I wish to compare a topic model with a representation from LDA. I have created my own coherence method but want to use additional metrics as i cannot score as highly with BERTopic. After reading your paper I noticed you used a package called Octis. I have been trying to get the Octis package to work with BERTopic for a while now with no luck. I was wondering if you could provide a code snippet as it was used in the paper or a very simple example of how to combine the two together? 

Thanks, 

Dex

**Comment by MaartenGr** [comment]
Although I do not have a code snippet at hand, you can try following some of the code in the repo [here](https://github.com/MaartenGr/BERTopic_evaluation) where I posted the validation code for the BERTopic paper. I used OCTIS there to perform the validation.

**Comment by MaartenGr** [comment]
Due to inactivity, I'll be closing this. Feel free to re-open if you run into any issues.
