### ISSUE TITLE
Issues saving BERTopic 

### ISSUE THREAD

**Issue by jasonmorkel** [MaartenGr/BERTopic#514]
Hi again Maarten,

This is my model that I created:
`vectorizer_model = CountVectorizer(ngram_range=(1, 3), stop_words="english")`
`topic_model = BERTopic(vectorizer_model=vectorizer_model, min_topic_size = 50, calculate_probabilities=True, verbose=True).fit(docs, y=categories)`

I am trying to save my topic_model using the following code:
`topic_model.save("my_model")`

But I am getting the following error code:
`RecursionError: Failed in nopython mode pipeline (step: convert to parfors)
maximum recursion depth exceeded while calling a Python object`

Some relevant versions to note that I have installed: 

`numba==0.55.1`
`numpy==1.21.4`
`bertopic==0.9.4`

**Comment by MaartenGr** [comment]
I just tried the following and unfortunately could not reproduce your issue:

```python
from bertopic import BERTopic
from sklearn.datasets import fetch_20newsgroups

# Prepare data 
data = fetch_20newsgroups(subset='all',  remove=('headers', 'footers', 'quotes'))
docs = data["data"]
categories = data["target"]
category_names = data["target_names"]

# Modeling
from sklearn.feature_extraction.text import CountVectorizer
vectorizer_model = CountVectorizer(ngram_range=(1, 3), stop_words="english")
topic_model = BERTopic(vectorizer_model=vectorizer_model, min_topic_size = 50, calculate_probabilities=True, verbose=True).fit(docs, y=categories)

# Save
topic_model.save("my_model")
```

This might then be either related to the environment of the documents/labels that you are using since it is working for me. Could you try again from a fresh environment? Also, how many documents are you passing?

**Comment by jasonmorkel** [comment]
Strange, so I also ran your code above and got the same error.

But, when I changed to 3.9.7 python environment from 3.10 python environment then it worked.

**Comment by DiegoKoz** [comment]
Hi, 

I'm having this same problem with:

python== 3.10.2
numba== 0.56.3
bertopi =='0.14.1'

has anyone found a fix?

thanks!
