### ISSUE TITLE
Issues about Value error and how to visualise the probability of each topic per doc

### ISSUE THREAD

**Issue by HarrywillDr** [MaartenGr/BERTopic#515]
Hi, 

Thank you for your kind share!

I'm trying to use this model on my dataset on colab. My dataset have 110 data and no parameters have been changed.But I meet this error:
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[<ipython-input-27-06aab18a7bcd>](https://localhost:8080/#) in <module>()
      7 
      8 topics, prob = BERTopic(umap_model=umap_model, hdbscan_model=hdbscan_model, vectorizer_model=vectorizer_model, 
----> 9                        calculate_probabilities= False, low_memory= False, nr_topics="auto").fit(docs)

8 frames
[/usr/local/lib/python3.7/dist-packages/hdbscan/hdbscan_.py](https://localhost:8080/#) in _hdbscan_prims_kdtree(X, min_samples, alpha, metric, p, leaf_size, gen_min_span_tree, **kwargs)
    244     # Get distance to kth nearest neighbour
    245     core_distances = tree.query(
--> 246         X, k=min_samples + 1, dualtree=True, breadth_first=True
    247     )[0][:, -1].copy(order="C")
    248 

sklearn/neighbors/_binary_tree.pxi in sklearn.neighbors._kd_tree.BinaryTree.query()

ValueError: k must be less than or equal to the number of training points

Do you have any idea about it? 
Another thing is if I want to see the probability per topic for each document. How can I doing that? the second outputs will be that?

Sorry ! I know my question maybe silly. I'm new learner to NlP. 
Many thanks for your kind help!

Best wishes
Harry

**Comment by HarrywillDr** [comment]
Sorry. I solve the first question by change the neighbours to 5. But I meet another one:

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-29-06aab18a7bcd>](https://localhost:8080/#) in <module>()
      7 
      8 topics, prob = BERTopic(umap_model=umap_model, hdbscan_model=hdbscan_model, vectorizer_model=vectorizer_model, 
----> 9                        calculate_probabilities= False, low_memory= False, nr_topics="auto").fit(docs)

TypeError: cannot unpack non-iterable BERTopic object

Thank you!

**Comment by HarrywillDr** [comment]
Sorry ! Solved again. 
Then my question only will be how to see the probability per topic for each document.

Thank you and apologize for my silly question!

**Comment by MaartenGr** [comment]
Definitely not a silly question! You can see the probability per topic for each document by setting `calculate_probabilities=True`. That way, the `probs` variable will be the topic-document probability matrix.

**Comment by HarrywillDr** [comment]
Thank you so much!
