### ISSUE TITLE
Can't pickle <class 'collections.FlatTree'>: attribute lookup FlatTree on collections failed

### ISSUE THREAD

**Issue by Thiziri-Hafir** [MaartenGr/BERTopic#517]
Hello, 
I've been working with BERTopic and  i'm having this error. Do you have any idea how to fixe this ? Thank you 
![erreur](https://user-images.githubusercontent.com/72195389/165089137-6319fac7-03be-467e-9ce8-0a04557a5abb.png)

**Comment by MaartenGr** [comment]
Unfortunately, I am not familiar with that error. Could you share the code you have been using to come to this error as well as everything before? Also, which versions of python, BERTopic, and its dependencies are you using?

**Comment by Thiziri-Hafir** [comment]
> Unfortunately, I am not familiar with that error. Could you share the code you have been using to come to this error as well as everything before? Also, which versions of python, BERTopic, and its dependencies are you using?

This is the part of the code that gave me the error. When I set low_parameter to False I get longer execution time, and when I set it to True it executes faster but it gives me the error I showed.
`bert_test = list(map(str,bert_test))
topic_model = BERTopic(embedding_model="all-MiniLM-L6-v2",  language="french", low_memory= True,  nr_topics=10, verbose=True)
topics, probas = topic_model.fit_transform(bert_test)`

**Comment by MaartenGr** [comment]
For now, it seems that it would be best to set `low_memory=False` in order to prevent the issue that you are having. It might stem from the way UMAP is handling low memory but I am not entirely sure. 

Just a quick note, this issue has been mentioned before on the UMAP issues page [here](https://github.com/lmcinnes/umap/issues/477#issuecomment-862017068) with a solution that might be helpful to you.

**Comment by Thiziri-Hafir** [comment]
I'll check that. Thank you for your help!

**Comment by jacobceles** [comment]
Just wanted to mention that I faced the same issue and was able to resolve it by using the code [from the link ](https://github.com/lmcinnes/umap/issues/477#issuecomment-862017068) provided by @MaartenGr, although it got really slow. For anyone who wants to skip the reading, just use:
```
import pyspark
import pynndescent
pynndescent.rp_trees.FlatTree.__module__  = "pynndescent.rp_trees"
```
before running any of the code, and everything should work fine.

**Comment by MaartenGr** [comment]
@Thiziri-Hafir If you are working locally, it is important that you start from a completely fresh environment and install the corresponding packages there. That might help you prevent any issues you are having.

**Comment by jacobceles** [comment]
@Thiziri-Hafir What's the error you are facing? If you provide some logs we might be able to help further.

**Comment by Thiziri-Hafir** [comment]
At first, I get connection errors like :
`Connection error, and we cannot find the requested files in the cached path. Please try again or make sure your Internet connection is on.`

Or :
`403 Client Error: Forbidden for url: http://sbert.net/models/all-MiniLM-L6-v2.zip`

So I download the model and use it locally but I get a new error :
`Can't pickle <class 'collections.FlatTree'>: attribute lookup FlatTree on collections failed`


Or :
`Path  /mnt/workspace/work/models/all-MiniLM-L6-v2 not found`

Which is actually my path and contains the config.json file

**Comment by Thiziri-Hafir** [comment]
I think the problem was in my corporate network which is very secure and requires the use of very specific tools. I created my own virtual environment and it works on a small dataset but i noticed that it's very long on a large dataset and I found that it does not use the GPU :/ .

**Comment by MaartenGr** [comment]
@Thiziri-Hafir Ah, I can imagine it is difficult to work in those secure networks with limited access to packages and GPU. It might be worthwhile to install PyTorch from [here](https://pytorch.org/get-started/locally/). Make sure to select a cuda-supported version.

**Comment by MaartenGr** [comment]
Due to inactivity, I'll be closing this for now. Let me know if you have any other questions related to this and I'll make sure to re-open the issue!
