### ISSUE TITLE
Issue with sentencepiece when pip installing bertopic

### ISSUE THREAD

**Issue by moi-stern** [MaartenGr/BERTopic#519]
Trying to install BERTopic on a machine I just moved to, and I'm getting an error with regards to sentencepiece, here's a snapshot of the error I'm getting when I run `pip install bertopic`. 

  ```
Failed to find sentencepiece pkg-config
----------------------------------------
ERROR: Failed building wheel for sentencepiece
```

Is this possibly because of the Python version I'm using? Currently using 3.10.4

**Comment by moi-stern** [comment]
Seems to work in 3.9

**Comment by MaartenGr** [comment]
Glad to hear that it is working now. It might be that some of the dependencies in sentencepiece only work with python <3.10 which seems to be the case for more packages currently.

**Comment by b-mckenna** [comment]
I had the same issue installing with Python 3.10.1. It worked when I tried with Python 3.8.9
