### ISSUE TITLE
 documents_per_topic/TypeError: expected str instance, float found, more details as follows.

### ISSUE THREAD

**Issue by cosmopoli12** [MaartenGr/BERTopic#525]
**Thanks for this great package!!!!**

Could you help TypeError: sequence item 31823: expected str instance, float found, more details as follows.

> 2022-05-03 01:27:39,176 - BERTopic - Transformed documents to Embeddings
> 2022-05-03 01:31:54,812 - BERTopic - Reduced dimensionality
> 2022-05-03 01:32:12,101 - BERTopic - Clustered reduced embeddings

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Input In [10], in <cell line: 11>()
      2 topic_model = BERTopic(top_n_words=10,
      3                        calculate_probabilities=False,
      4                        umap_model= umap_model,
   (...)
      7                        embedding_model= embedding_model,
      8                        verbose=True)
     10 # Train model, extract topics and probabilities
---> 11 topics, probabilities = topic_model.fit_transform(reviews_en)
     12 #topics, _ = topic_model.fit_transform(reviews_en)
     14 '''Returns:
     15             predictions: Topic predictions for each documents
     16             probabilities: The probability of the assigned topic per document.
   (...)
     19                            instead of only the assigned topic. This, however, slows down
     20                            computation and may increase memory usage.'''

File ~\AppData\Local\Programs\Python\Python39\lib\site-packages\bertopic\_bertopic.py:316, in BERTopic.fit_transform(self, documents, embeddings, y)
    313     documents = self._sort_mappings_by_frequency(documents)
    315 # Extract topics by calculating c-TF-IDF
--> 316 self._extract_topics(documents)
    318 # Reduce topics
    319 if self.nr_topics:

File ~\AppData\Local\Programs\Python\Python39\lib\site-packages\bertopic\_bertopic.py:1490, in BERTopic._extract_topics(self, documents)
   1481 def _extract_topics(self, documents: pd.DataFrame):
   1482     """ Extract topics from the clusters using a class-based TF-IDF
   1483 
   1484     Arguments:
   (...)
   1488         c_tf_idf: The resulting matrix giving a value (importance score) for each word per topic
   1489     """
-> 1490     documents_per_topic = documents.groupby(['Topic'], as_index=False).agg({'Document': ' '.join})
   1491     self.c_tf_idf, words = self._c_tf_idf(documents_per_topic)
   1492     self.topics = self._extract_words_per_topic(words)

File ~\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\core\groupby\generic.py:869, in DataFrameGroupBy.aggregate(self, func, engine, engine_kwargs, *args, **kwargs)
    866 func = maybe_mangle_lambdas(func)
    868 op = GroupByApply(self, func, args, kwargs)
--> 869 result = op.agg()
    870 if not is_dict_like(func) and result is not None:
    871     return result

File ~\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\core\apply.py:168, in Apply.agg(self)
    165     return self.apply_str()
    167 if is_dict_like(arg):
--> 168     return self.agg_dict_like()
    169 elif is_list_like(arg):
    170     # we require a list, but not a 'str'
    171     return self.agg_list_like()

File ~\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\core\apply.py:475, in Apply.agg_dict_like(self)
    472     results = {key: colg.agg(how) for key, how in arg.items()}
    473 else:
    474     # key used for column selection and output
--> 475     results = {
    476         key: obj._gotitem(key, ndim=1).agg(how) for key, how in arg.items()
    477     }
    479 # set the final keys
    480 keys = list(arg.keys())

File ~\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\core\apply.py:476, in <dictcomp>(.0)
    472     results = {key: colg.agg(how) for key, how in arg.items()}
    473 else:
    474     # key used for column selection and output
    475     results = {
--> 476         key: obj._gotitem(key, ndim=1).agg(how) for key, how in arg.items()
    477     }
    479 # set the final keys
    480 keys = list(arg.keys())

File ~\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\core\groupby\generic.py:287, in SeriesGroupBy.aggregate(self, func, engine, engine_kwargs, *args, **kwargs)
    284     return self._python_agg_general(func, *args, **kwargs)
    286 try:
--> 287     return self._python_agg_general(func, *args, **kwargs)
    288 except KeyError:
    289     # TODO: KeyError is raised in _python_agg_general,
    290     #  see test_groupby.test_basic
    291     result = self._aggregate_named(func, *args, **kwargs)

File ~\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\core\groupby\groupby.py:1490, in GroupBy._python_agg_general(self, func, *args, **kwargs)
   1487     output[key] = result
   1489 if not output:
-> 1490     return self._python_apply_general(f, self._selected_obj)
   1492 return self._wrap_aggregated_output(output)

File ~\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\core\groupby\groupby.py:1455, in GroupBy._python_apply_general(self, f, data, not_indexed_same)
   1429 @final
   1430 def _python_apply_general(
   1431     self,
   (...)
   1434     not_indexed_same: bool | None = None,
   1435 ) -> DataFrame | Series:
   1436     """
   1437     Apply function f in python space
   1438 
   (...)
   1453         data after applying f
   1454     """
-> 1455     values, mutated = self.grouper.apply(f, data, self.axis)
   1457     if not_indexed_same is None:
   1458         not_indexed_same = mutated or self.mutated

File ~\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\core\groupby\ops.py:761, in BaseGrouper.apply(self, f, data, axis)
    759 # group might be modified
    760 group_axes = group.axes
--> 761 res = f(group)
    762 if not mutated and not _is_indexed_like(res, group_axes, axis):
    763     mutated = True

File ~\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\core\groupby\groupby.py:1467, in GroupBy._python_agg_general.<locals>.<lambda>(x)
   1464 @final
   1465 def _python_agg_general(self, func, *args, **kwargs):
   1466     func = com.is_builtin_func(func)
-> 1467     f = lambda x: func(x, *args, **kwargs)
   1469     # iterate through "columns" ex exclusions to populate output dict
   1470     output: dict[base.OutputKey, ArrayLike] = {}

TypeError: sequence item 31823: expected str instance, float found

**Comment by MaartenGr** [comment]
Based on the error, I think there might be non-strings in your `reviews_en` variable. This could be either a float as the error mentions, a `NaN` value, or empty documents. Could you check whether you have empty strings or some non-string value?

**Comment by cosmopoli12** [comment]
Thanks, yes, my gosh there was 1 Nan value overlooked.
