### ISSUE TITLE
sentencetransformer pandas KeyError: 32066

### ISSUE THREAD

**Issue by cosmopoli12** [MaartenGr/BERTopic#526]
Hi Maarten again,

all nan removed, but now comes to a KeyError, please kindly help! Thanks. 

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
File ~\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\core\indexes\base.py:3621, in Index.get_loc(self, key, method, tolerance)
   3620 try:
-> 3621     return self._engine.get_loc(casted_key)
   3622 except KeyError as err:

File ~\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\_libs\index.pyx:136, in pandas._libs.index.IndexEngine.get_loc()

File ~\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\_libs\index.pyx:163, in pandas._libs.index.IndexEngine.get_loc()

File pandas\_libs\hashtable_class_helper.pxi:2131, in pandas._libs.hashtable.Int64HashTable.get_item()

File pandas\_libs\hashtable_class_helper.pxi:2140, in pandas._libs.hashtable.Int64HashTable.get_item()

KeyError: 32066

The above exception was the direct cause of the following exception:

KeyError                                  Traceback (most recent call last)
Input In [30], in <cell line: 11>()
      2 topic_model = BERTopic(top_n_words=10,
      3                        calculate_probabilities=False,
      4                        umap_model= umap_model,
   (...)
      7                        embedding_model= embedding_model,
      8                        verbose=True)
     10 # Train model, extract topics and probabilities
---> 11 topics, probabilities = topic_model.fit_transform(reviews_en)
     12 #topics, _ = topic_model.fit_transform(reviews_en)
     14 '''Returns:
     15             predictions: Topic predictions for each documents
     16             probabilities: The probability of the assigned topic per document.
   (...)
     19                            instead of only the assigned topic. This, however, slows down
     20                            computation and may increase memory usage.'''

File ~\AppData\Local\Programs\Python\Python39\lib\site-packages\bertopic\_bertopic.py:294, in BERTopic.fit_transform(self, documents, embeddings, y)
    291 if embeddings is None:
    292     self.embedding_model = select_backend(self.embedding_model,
    293                                           language=self.language)
--> 294     embeddings = self._extract_embeddings(documents.Document,
    295                                           method="document",
    296                                           verbose=self.verbose)
    297     logger.info("Transformed documents to Embeddings")
    298 else:

File ~\AppData\Local\Programs\Python\Python39\lib\site-packages\bertopic\_bertopic.py:1362, in BERTopic._extract_embeddings(self, documents, method, verbose)
   1360     embeddings = self.embedding_model.embed_words(documents, verbose)
   1361 elif method == "document":
-> 1362     embeddings = self.embedding_model.embed_documents(documents, verbose)
   1363 else:
   1364     raise ValueError("Wrong method for extracting document/word embeddings. "
   1365                      "Either choose 'word' or 'document' as the method. ")

File ~\AppData\Local\Programs\Python\Python39\lib\site-packages\bertopic\backend\_base.py:69, in BaseEmbedder.embed_documents(self, document, verbose)
     55 def embed_documents(self,
     56                     document: List[str],
     57                     verbose: bool = False) -> np.ndarray:
     58     """ Embed a list of n words into an n-dimensional
     59     matrix of embeddings
     60 
   (...)
     67         that each have an embeddings size of `m`
     68     """
---> 69     return self.embed(document, verbose)

File ~\AppData\Local\Programs\Python\Python39\lib\site-packages\bertopic\backend\_sentencetransformers.py:63, in SentenceTransformerBackend.embed(self, documents, verbose)
     49 def embed(self,
     50           documents: List[str],
     51           verbose: bool = False) -> np.ndarray:
     52     """ Embed a list of n documents/words into an n-dimensional
     53     matrix of embeddings
     54 
   (...)
     61         that each have an embeddings size of `m`
     62     """
---> 63     embeddings = self.embedding_model.encode(documents, show_progress_bar=verbose)
     64     return embeddings

File ~\AppData\Local\Programs\Python\Python39\lib\site-packages\sentence_transformers\SentenceTransformer.py:156, in SentenceTransformer.encode(self, sentences, batch_size, show_progress_bar, output_value, convert_to_numpy, convert_to_tensor, device, normalize_embeddings)
    154 all_embeddings = []
    155 length_sorted_idx = np.argsort([-self._text_length(sen) for sen in sentences])
--> 156 sentences_sorted = [sentences[idx] for idx in length_sorted_idx]
    158 for start_index in trange(0, len(sentences), batch_size, desc="Batches", disable=not show_progress_bar):
    159     sentences_batch = sentences_sorted[start_index:start_index+batch_size]

File ~\AppData\Local\Programs\Python\Python39\lib\site-packages\sentence_transformers\SentenceTransformer.py:156, in <listcomp>(.0)
    154 all_embeddings = []
    155 length_sorted_idx = np.argsort([-self._text_length(sen) for sen in sentences])
--> 156 sentences_sorted = [sentences[idx] for idx in length_sorted_idx]
    158 for start_index in trange(0, len(sentences), batch_size, desc="Batches", disable=not show_progress_bar):
    159     sentences_batch = sentences_sorted[start_index:start_index+batch_size]

File ~\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\core\series.py:958, in Series.__getitem__(self, key)
    955     return self._values[key]
    957 elif key_is_scalar:
--> 958     return self._get_value(key)
    960 if is_hashable(key):
    961     # Otherwise index.get_value will raise InvalidIndexError
    962     try:
    963         # For labels that don't resolve as scalars like tuples and frozensets

File ~\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\core\series.py:1069, in Series._get_value(self, label, takeable)
   1066     return self._values[label]
   1068 # Similar to Index.get_value, but we do not fall back to positional
-> 1069 loc = self.index.get_loc(label)
   1070 return self.index._get_values_for_loc(self, loc, label)

File ~\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\core\indexes\base.py:3623, in Index.get_loc(self, key, method, tolerance)
   3621     return self._engine.get_loc(casted_key)
   3622 except KeyError as err:
-> 3623     raise KeyError(key) from err
   3624 except TypeError:
   3625     # If we have a listlike key, _check_indexing_error will raise
   3626     #  InvalidIndexError. Otherwise we fall through and re-raise
   3627     #  the TypeError.
   3628     self._check_indexing_error(key)

KeyError: 32066

**Comment by MaartenGr** [comment]
Hmm, I am not entirely sure what is happening here. Could you share the BERTopic version you are using as well as its dependencies (sentence-transformers, numpy, hdbscan, etc.)? Also, could you share your entire code for training BERTopic?

Lastly, did you make sure that every document in `reviews_en` is a string?

**Comment by cosmopoli12** [comment]
thanks, it is solved, only the reviews_en became pandas.core.series.Series, now I changed it to list. It works.
