### ISSUE TITLE
Pip installation problem

### ISSUE THREAD

**Issue by alexsomoza** [MaartenGr/BERTopic#527]
Could not fetch URL https://pypi.org/simple/bertopic/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/bertopic/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1091)'))) - skipping
ERROR: Could not find a version that satisfies the requirement plotly<4.14.3,>=4.7.0 (from bertopic[flair]) (from versions: none)
ERROR: No matching distribution found for plotly<4.14.3,>=4.7.0

**Comment by MaartenGr** [comment]
Based on the `Max retries exceeded` error message that you are having, it actually seems that there is an issue with your internet connection or perhaps even your pip version. Could you upgrade pip and try again? For me, `pip install bertopic[flair]` is working without any issues

**Comment by alexsomoza** [comment]
> Based on the `Max retries exceeded` error message that you are having, it actually seems that there is an issue with your internet connection or perhaps even your pip version. Could you upgrade pip and try again? For me, `pip install bertopic[flair]` is working without any issues

I used this command to upgrade pip
pip install --trusted-host=pypi.org --trusted-host=files.pythonhosted.org --user --upgrade pip

Then I tried:
pip install --trusted-host=pypi.org --trusted-host=files.pythonhosted.org --user bertopic[flair]

which finalized with this line:
.................................................................................................................
Collecting transformers==3.5.1
  Downloading transformers-3.5.1-py3-none-any.whl (1.3 MB)
     ---------------------------------------- 1.3/1.3 MB 1.1 MB/s eta 0:00:00
Collecting torch<1.7.1,>=1.4.0
  Using cached torch-1.7.0-cp37-cp37m-win_amd64.whl (184.0 MB)
ERROR: torch has an invalid wheel, torch has an invalid wheel, .dist-info directory not found

**Comment by MaartenGr** [comment]
Due to inactivity, this issue will be closed. Feel free to ping me if you want to re-open the issue!
