### ISSUE TITLE
It´s posible use the BETO embeeding with BertTopic ??

### ISSUE THREAD

**Issue by durannardecchia** [MaartenGr/BERTopic#528]
Hi Maarten

The question I wanted to ask you is if Bertopic can be used with the model of the Spanish version of BERT embeeding, which is called BETO (BETO is a BERT model trained on a big Spanish corpus.. BETO is of size similar to a BERT-Base and was trained with the Whole Word Masking technique) , which is in the following link:  https://github.com/dccuchile/beto

Thanks for your help !!
Eduardo

**Comment by MaartenGr** [comment]
Yes! There are two ways that you can use that model. First, you can load it in using Flair and pass that to BERTopic. You can find instructions for doing so [here](https://maartengr.github.io/BERTopic/getting_started/embeddings/embeddings.html). Second, you can generate the embeddings of the documents yourself and pass those to BERTopic. You can find those instructions [here](https://maartengr.github.io/BERTopic/getting_started/embeddings/embeddings.html#custom-embeddings). Note that the example is done with SentenceTransformers which would need to be replaced by the model you selected. 

Hopefully, this helps a bit!
