### ISSUE TITLE
Problem with numba package 

### ISSUE THREAD

**Issue by mariekevanbuchem** [MaartenGr/BERTopic#53]
I keep having the same installation error, related to the numba package. See error below:

```python
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-160-1d2f5f7c9d67> in <module>
----> 1 from bertopic import BERTopic

/opt/anaconda3/lib/python3.7/site-packages/bertopic/__init__.py in <module>
----> 1 from bertopic._bertopic import BERTopic
      2 from bertopic._ctfidf import ClassTFIDF
      3 from bertopic._embeddings import languages
      4 
      5 __version__ = "0.4.3"

/opt/anaconda3/lib/python3.7/site-packages/bertopic/_bertopic.py in <module>
     10 
     11 # Models
---> 12 import umap
     13 import hdbscan
     14 from sentence_transformers import SentenceTransformer

/opt/anaconda3/lib/python3.7/site-packages/umap/__init__.py in <module>
      1 from warnings import warn, catch_warnings, simplefilter
----> 2 from .umap_ import UMAP
      3 
      4 try:
      5     with catch_warnings():

/opt/anaconda3/lib/python3.7/site-packages/umap/umap_.py in <module>
     45 )
     46 
---> 47 from pynndescent import NNDescent
     48 from pynndescent.distances import named_distances as pynn_named_distances
     49 from pynndescent.sparse import sparse_named_distances as pynn_sparse_named_distances

/opt/anaconda3/lib/python3.7/site-packages/pynndescent/__init__.py in <module>
      1 import pkg_resources
      2 import numba
----> 3 from .pynndescent_ import NNDescent, PyNNDescentTransformer
      4 
      5 # Workaround: https://github.com/numba/numba/issues/3341

/opt/anaconda3/lib/python3.7/site-packages/pynndescent/pynndescent_.py in <module>
     19 import heapq
     20 
---> 21 import pynndescent.sparse as sparse
     22 import pynndescent.sparse_nndescent as sparse_nnd
     23 import pynndescent.distances as pynnd_dist

/opt/anaconda3/lib/python3.7/site-packages/pynndescent/sparse.py in <module>
      8 import numba
      9 
---> 10 from pynndescent.utils import norm, tau_rand
     11 from pynndescent.distances import kantorovich
     12 

/opt/anaconda3/lib/python3.7/site-packages/pynndescent/utils.py in <module>
      6 
      7 import numba
----> 8 from numba.core import types
      9 from numba.experimental import structref
     10 import numpy as np

ModuleNotFoundError: No module named 'numba.core'
```

I am running on macOS Big Sur. Package versions:
bertopic==0.4.3
conda==4.9.2
numba==0.52.0
umap-learn==0.5.0
Python==3.7.6

I've already done a lot of searching on the internet but can't find any solution. Does somebody have the same problem or any idea how to solve this? 

Thanks in advance!

**Comment by MaartenGr** [comment]
Can you try installing BERTopic in a fresh conda env? Problems with numba typically have to do with conflicting dependencies which could be caused by having many different packages in a single environment. If that doesn't work, it might be an idea to first install BERTopic, then uninstall numba and finally install numba again:

```
python -m pip uninstall numba
python -m pip install numba
```

**Comment by mariekevanbuchem** [comment]
Thanks for the quick reply! Even a fresh Conda env did not help, but finally removed all python packages, updated Python to 3.8, and it now works. Great package!

**Comment by MaartenGr** [comment]
Great! Glad to hear that it worked out 😄

**Comment by EndlessVaidurya** [comment]
When I import bertopic from Bertopic,  I keep having the same installation error, related to the numba package . See error below:
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-ab3582836264> in <module>
----> 1 from bertopic import BERTOPIC

D:\ANACONDA\lib\site-packages\bertopic\__init__.py in <module>
----> 1 from bertopic._bertopic import BERTopic
      2 
      3 __version__ = "0.10.0"
      4 
      5 __all__ = [

D:\ANACONDA\lib\site-packages\bertopic\_bertopic.py in <module>
     20 # Models
     21 import hdbscan
---> 22 from umap import UMAP
     23 from sklearn.feature_extraction.text import CountVectorizer
     24 from sklearn.metrics.pairwise import cosine_similarity

D:\ANACONDA\lib\site-packages\umap\__init__.py in <module>
      1 from warnings import warn, catch_warnings, simplefilter
----> 2 from .umap_ import UMAP
      3 
      4 try:
      5     with catch_warnings():

D:\ANACONDA\lib\site-packages\umap\umap_.py in <module>
     45 )
     46 
---> 47 from pynndescent import NNDescent
     48 from pynndescent.distances import named_distances as pynn_named_distances
     49 from pynndescent.sparse import sparse_named_distances as pynn_sparse_named_distances

D:\ANACONDA\lib\site-packages\pynndescent\__init__.py in <module>
      1 import pkg_resources
      2 import numba
----> 3 from .pynndescent_ import NNDescent, PyNNDescentTransformer
      4 
      5 # Workaround: https://github.com/numba/numba/issues/3341

D:\ANACONDA\lib\site-packages\pynndescent\pynndescent_.py in <module>
     14 import heapq
     15 
---> 16 import pynndescent.sparse as sparse
     17 import pynndescent.sparse_nndescent as sparse_nnd
     18 import pynndescent.distances as pynnd_dist

D:\ANACONDA\lib\site-packages\pynndescent\sparse.py in <module>
      8 import numba
      9 
---> 10 from pynndescent.utils import norm, tau_rand
     11 from pynndescent.distances import (
     12     kantorovich,

D:\ANACONDA\lib\site-packages\pynndescent\utils.py in <module>
      7 import numba
      8 from numba.core import types
----> 9 import numba.experimental.structref as structref
     10 import numpy as np
     11 

ModuleNotFoundError: No module named 'numba.experimental.structref'


I've already done a lot of searching on the internet but can't find any solution. Does somebody have the same problem or any idea how to solve this?

Thanks in advance!

**Comment by MaartenGr** [comment]
@EndlessVaidurya Although I am not familiar with that specific error, it does seem to be related to the environment in which you are working. I would advise starting from a completely fresh environment and installing BERTopic there to see if that fixes your issue.
