### ISSUE TITLE
supervised methods test outputs not great

### ISSUE THREAD

**Issue by HarrywillDr** [MaartenGr/BERTopic#530]
Hi,

Thank you for sharing the code.

I first trained the supervised model on 4260 training samples and 243 targets topic.
the model finally generated 39 outputs.
Then I load the trained model and test it on 109 total new training samples (which should generate 5 clusters), but the outputs still 39.

I don't know how to fix that. may I ask for any suggestions? Thank you!
Here is the code:

**#for training**
topic_model = BERTopic(embedding_model=sentence_model, umap_model=umap_model, hdbscan_model=hdbscan_model, vectorizer_model=vectorizer_model, 
                       calculate_probabilities= True, low_memory= False,n_gram_range = (1, 2), nr_topics="auto", verbose = True)

topics, probs = topic_model.fit_transform(docs, embeddings, y=targets)
**# too much, then I try to reduce the number.**
topics_reduced, probs_reduced = topic_model.reduce_topics(docs, topics, nr_topics=6)

topic_model.save("trained_model")
loaded_model = BERTopic.load("trained_model")
#test sentence embedding
sentence_model = SentenceTransformer("all-mpnet-base-v2")
test_embeddings = sentence_model.encode(test_docs)
topics_test, probs_test = loaded_model.transform(test_docs, test_embeddings)

then the output still 39 (with reduce the topics number to 6, the output will be 6,but the cluster very bad, some of them only one sentence)

Thank you!

**Comment by MaartenGr** [comment]
> Then I load the trained model and test it on 109 total new training samples (which should generate 5 clusters), but the outputs still 39.

Strange, it should still generate 5 topics if you have reduced them. I just tried the following and I could not replicate your issue:

```python
from sklearn.datasets import fetch_20newsgroups
from sentence_transformers import SentenceTransformer
from bertopic import BERTopic

# Data
data = fetch_20newsgroups(subset='all',  remove=('headers', 'footers', 'quotes'))
docs = data["data"]
categories = data["target"]
category_names = data["target_names"]

# Prepare embeddings
sentence_model = SentenceTransformer("all-MiniLM-L6-v2")
embeddings = sentence_model.encode(docs,  show_progress_bar=False)

# Train our topic model using our pre-trained sentence-transformers embeddings
topic_model = BERTopic(verbose=True)
topics, probs = topic_model.fit_transform(docs[:5_000], embeddings[:5_000], y=categories[:5_000])

# Reduce the number of topics to 10
topics_reduced, probs_reduced = topic_model.reduce_topics(docs[:5_000], topics, nr_topics=10)

# Save and load the model
topic_model.save("trained_model1")
loaded_model = BERTopic.load("trained_model1")

# Test it on the documents that were left
topics_test, probs_test = loaded_model.transform(docs[5_000:], embeddings[5_000:])
len(set(topics_test))
```

Could you share which version of BERTopic you are using, including its dependencies (numpy, hdbscan, umap, etc.)? Also, It is not clear to me what all parameters in when initializing BERTopic. For example, how did you define `umap_model`?

**Comment by HarrywillDr** [comment]
Hi MaartenGr,

Thank you reply so quickly!

Here is my code 
```
from umap import UMAP
from hdbscan import HDBSCAN
from sklearn.feature_extraction.text import CountVectorizer

umap_model = UMAP(n_neighbors=4, n_components=10, min_dist=0.0, metric='cosine')
hdbscan_model = HDBSCAN(min_cluster_size=10, metric='euclidean', cluster_selection_method='eom', prediction_data=True)
vectorizer_model = CountVectorizer(ngram_range=(1, 2), stop_words="english")

from sentence_transformers import SentenceTransformer

sentence_model = SentenceTransformer("all-mpnet-base-v2")
embeddings = sentence_model.encode(docs)
#training
topic_model = BERTopic(embedding_model=sentence_model, umap_model=umap_model, hdbscan_model=hdbscan_model, vectorizer_model=vectorizer_model, 
                       calculate_probabilities= True, low_memory= False,n_gram_range = (1, 2), nr_topics="auto", verbose = True)

topics, probs = topic_model.fit_transform(docs, embeddings, y=targets)
topics_reduced, probs_reduced = topic_model.reduce_topics(docs, topics, nr_topics=5)
```
I have another question my training data are 4260 training samples and 243 targets cover 31 different topics. Why the model will reduce it(to 39 targets) after training? Is it the reason why I get poor performance? As my test data on the same topic and only 109 training sample, 5 targets.

Thank you so much!

best wishes
Harry

**Comment by HarrywillDr** [comment]
If I want training and testing to be consistent, should the training data be entered in batches? Five targets at a time, and the corresponding inputs. So that the five targets can be output at test time?

Thanks!

**Comment by MaartenGr** [comment]
> I have another question my training data are 4260 training samples and 243 targets cover 31 different topics. Why the model will reduce it(to 39 targets) after training? 

The semi-supervised approach in BERTopic merely nudges the training towards certain classes. However, if these classes give little information then UMAP will not exactly reproduce the clustering found in `y`. Moreover, setting `nr_topics` to `auto` will result in the topics being merged together using HDBSCAN. Lastly, you can increase or decrease the number of topics also through setting the `min_topic_size` parameter. Higher values will lead to fewer clusters and lower values will lead to more clusters. 

> Is it the reason why I get poor performance? As my test data on the same topic and only 109 training sample, 5 targets.

Poor performance can stem from quite a number of things but based on the code, it might be worthwhile to change the UMAP model back to its defaults values as those work quite well. Moreover, extracting only 5 topics from the documents is likely to result in poor performance as it will create very abstract topics. I would advise only using `nr_topics="auto"` and not using `.reduce_topics` after that to such a low value. 

> If I want training and testing to be consistent, should the training data be entered in batches? Five targets at a time, and the corresponding inputs. So that the five targets can be output at test time?

Could you provide the procedure for training and testing? I am not entirely sure how you are comparing those with each other. One thing though is that it is best to put all the data at once in the model for training purposes if you are merely looking for representations of the topics. 

> as my training data from 243 topics and 4260 sentences, but these sentences have different stances. so I shouldn't put them in together as training data, right? should be separated by stance and topic. thanks

What do you exactly mean with 'stances'? Typically, you would want to put all the data in the model together as it will have more information to create the topic representations. In other words, train on all 4260 sentences at once!

**Comment by HarrywillDr** [comment]
Hi

I solve that by optimising my training data! Thanks!

Best wishes
Harry
