### ISSUE TITLE
No dimensionality reduction in Kmeans

### ISSUE THREAD

**Issue by iknoorjobs** [MaartenGr/BERTopic#531]
Hi @MaartenGr 

Brilliant work! Keep it up!

Is there any quick way if I don't want to use dimensionality reduction or not use the umap_model parameter at all for clustering?

Many thanks 
Iknoor

**Comment by MaartenGr** [comment]
Thank you for your kind words!

Yes, the dimensionality reduction algorithm only needs `fit` and `transform` methods. You can create an empty model that simply returns the embeddings without doing any processing. 

```python
class DimensionalityReduction:
    def fit(self, X):
        return self

    def transform(self, X):
        return X

empty_dim_model = DimensionalityReduction()

topic_model = BERTopic(umap_model=empty_dim_model)
```

**Comment by iknoorjobs** [comment]
Great, thanks, @MaartenGr 🙏🏻
