### ISSUE TITLE
Issues when using KMEANS as clustering method

### ISSUE THREAD

**Issue by doubianimehdi** [MaartenGr/BERTopic#532]
Hi Maarten,

I'd like to report problems when I use KMeans as a clustering method:

from bertopic import BERTopic
from sklearn.feature_extraction.text import CountVectorizer
#topic_model = BERTopic.load("my_model")
vectorizer_model = CountVectorizer(ngram_range=(1, 2),stop_words=final_stop_words)
from sklearn.cluster import KMeans

cluster_model = KMeans(n_clusters=50)
topic_model = BERTopic(hdbscan_model=cluster_model,verbose=True,diversity=1,top_n_words=10, embedding_model="malteos/scincl", nr_topics=50,vectorizer_model=vectorizer_model,calculate_probabilities=True)
topics, probabilities = topic_model.fit_transform(abstract)

1°) Later in my code I have an issue with Heat Map function : 

IndexError                                Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_14516/3302089857.py in <module>
----> 1 topic_model.visualize_heatmap(n_clusters=49, top_n_topics=50)

~\AppData\Roaming\Python\Python39\site-packages\bertopic\_bertopic.py in visualize_heatmap(self, topics, top_n_topics, n_clusters, width, height)
   1199         """
   1200         check_is_fitted(self)
-> 1201         return plotting.visualize_heatmap(self,
   1202                                           topics=topics,
   1203                                           top_n_topics=top_n_topics,

~\AppData\Roaming\Python\Python39\site-packages\bertopic\plotting\_heatmap.py in visualize_heatmap(topic_model, topics, top_n_topics, n_clusters, width, height)
     72                              "the total number of unique topics.")
     73 
---> 74         embeddings = embeddings[[topic + 1 for topic in topics]]
     75         distance_matrix = cosine_similarity(embeddings)
     76         Z = linkage(distance_matrix, 'ward')

IndexError: index 50 is out of bounds for axis 0 with size 50

2°) I also use this piece of code to extract the representative documents : 
from itertools import chain, repeat
chainer = chain.from_iterable
rep_docs = pd.DataFrame({'key': list(chainer(repeat(k, len(v)) for k, v in topic_model.representative_docs.items())),'variable': list(chainer(topic_model.representative_docs.values()))})
rep_docs = rep_docs.sort_values(by=['key'])

BUT I have this message : 
AttributeError                            Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_14516/4202219099.py in <module>
     30 from itertools import chain, repeat
     31 chainer = chain.from_iterable
---> 32 rep_docs = pd.DataFrame({'key': list(chainer(repeat(k, len(v)) for k, v in topic_model.representative_docs.items())),'variable': list(chainer(topic_model.representative_docs.values()))})
     33 rep_docs = rep_docs.sort_values(by=['key'])
     34 

AttributeError: 'NoneType' object has no attribute 'items'

Thank you for your help !

**Comment by MaartenGr** [comment]
Thank you for the posting this issue!

It seems that the visualization is expecting there to be outliers in the topics, as typically is the case with HDBSCAN. However, since k-Means does not include any outliers, this throws it off a bit. For now, you can circumvent this issue by setting the following:

```python
topic_model.visualize_heatmap(top_n_topics=50)
```
Since `n_clusters` really does not do anything when you set it very close the number of topics, you can just omit it. However, if you still want to keep it, the following should work:

```python
topic_model.visualize_heatmap(n_clusters=48, top_n_topics=49)
```

**Comment by MaartenGr** [comment]
I just pushed the fix to the master branch, so using that should solve your issue. If not, please let me know!

**Comment by doubianimehdi** [comment]
topic_model.visualize_heatmap(top_n_topics=50) this solutions , works , the other doesn't work !
Thank you !

What about this issue : 

I also use this piece of code to extract the representative documents :
from itertools import chain, repeat
chainer = chain.from_iterable
rep_docs = pd.DataFrame({'key': list(chainer(repeat(k, len(v)) for k, v in topic_model.representative_docs.items())),'variable': list(chainer(topic_model.representative_docs.values()))})
rep_docs = rep_docs.sort_values(by=['key'])

BUT I have this message :
AttributeError Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_14516/4202219099.py in
30 from itertools import chain, repeat
31 chainer = chain.from_iterable
---> 32 rep_docs = pd.DataFrame({'key': list(chainer(repeat(k, len(v)) for k, v in topic_model.representative_docs.items())),'variable': list(chainer(topic_model.representative_docs.values()))})
33 rep_docs = rep_docs.sort_values(by=['key'])
34

AttributeError: 'NoneType' object has no attribute 'items'


get_representative_docs is empty ...

**Comment by MaartenGr** [comment]
> get_representative_docs is empty ...

That is correct! The representative documents are calculated by extracting the exemplar points from HDBSCAN. However, since you are using an algorithm different from HDBSCAN, the representative documents cannot be extracted.

**Comment by doubianimehdi** [comment]
Oh ok ! ... I'll have to deactivate this part of my code and stick with ALL the documents and topics then ... thank you !
