### ISSUE TITLE
Update conda-forge package to v0.10.0

### ISSUE THREAD

**Issue by seb45tian** [MaartenGr/BERTopic#534]
Hi MaartenGr,

would it be possible to update the package provided by conda-forge to the latest version? (cf. https://github.com/conda-forge/bertopic-feedstock/pull/2 ) This would make installation and dependency resolution much easier. 

Many thanks

**Comment by leifericf** [comment]
I want to second this request. The current version available on conda-forge is 0.9.4.

Installing BERTopic via pip in a conda environment on an Apple M1 Pro Mac results in dependency issues.
