### ISSUE TITLE
AttributeError: 'Word2VecKeyedVectors' object has no attribute 'index_to_key'

### ISSUE THREAD

**Issue by HarrywillDr** [MaartenGr/BERTopic#535]
Sorry, I come back again. I have three questions to ask.
---------------------------------First Question---------------------------------
When I try to combine word embedding and sentence embedding. I get this error:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-87-7abd6f68714d>](https://localhost:8080/#) in <module>()
     13         targets = training_pos["target_id"]
     14         #embeddings = sentence_model.encode(docs,  show_progress_bar= True)
---> 15         topics, probs = topic_model.fit(docs, y=targets)
     16         #topics, probs = topic_model.fit_transform(docs, embeddings, y=targets)
     17         #inputs_num.append(len(targets))

6 frames
[/usr/local/lib/python3.7/dist-packages/bertopic/backend/_gensim.py](https://localhost:8080/#) in embed(self, documents, verbose)
     49             that each have an embeddings size of `m`
     50         """
---> 51         vector_shape = self.embedding_model.get_vector(list(self.embedding_model.index_to_key)[0]).shape[0]
     52         empty_vector = np.zeros(vector_shape)
     53 

AttributeError: 'Word2VecKeyedVectors' object has no attribute 'index_to_key'
```

Here is my code:
```
from sentence_transformers import SentenceTransformer
import gensim.downloader as api
from bertopic.backend import WordDocEmbedder

# Word embedding model
ft = api.load('fasttext-wiki-news-subwords-300')

# Document embedding model
sentence_model = SentenceTransformer("all-mpnet-base-v2", device="cuda")

# Create a model that uses both language models and pass it through BERTopic
word_doc_embedder = WordDocEmbedder(embedding_model=sentence_model, word_embedding_model=ft)

topic_model = BERTopic(embedding_model=word_doc_embedder, umap_model=umap_model, hdbscan_model=hdbscan_model, vectorizer_model=vectorizer_model, 
                       calculate_probabilities= True, low_memory= False,n_gram_range = (1, 2), nr_topics="auto", verbose = True)

inputs_num = []
clusters_num = []
# training the model for stance 1
topic_value = pd.unique(data["topic_x"])
for value in topic_value:
    training_pos = data[(data["topic_x"] == value) & (data["stance_x"] == 1)]
    if len(training_pos) < 110:
        continue
    else :
        topictext = []
        result = preprocess(training_pos)
        docs = new_input (result, topictext)
        targets = training_pos["target_id"]
        topics, probs = topic_model.fit(docs, y=targets)
```
I'm not quite sure why and if I want to encode the docs, how can I do that? Thanks
---------------------------------Second Question---------------------------------
For BERTopic, is the more training data it has, the better performance it will get?
---------------------------------Third Question---------------------------------
```
inputs_num = []
clusters_num = []
# training the model for stance 1
topic_value = pd.unique(data["topic_x"])
for value in topic_value:
    training_pos = data[(data["topic_x"] == value) & (data["stance_x"] == 1)]
    if len(training_pos) < 110:
        continue
    else :
        topictext = []
        result = preprocess(training_pos)
        docs = new_input (result, topictext)
        targets = training_pos["target_id"]
        embeddings = sentence_model.encode(docs,  show_progress_bar= True)
        topics, probs = topic_model.fit_transform(docs, embeddings, y=targets)
        inputs_num.append(len(targets))
        clusters_num.append(np.size(probs, 1))

topic_model.save("trained_pos_model")
```
My idea is to send all the docs of one topic at a time into the model training and save the model at the end. Do you think is useful? When I load it again and using follow code to see the topic, it will show the last training topic, why this happened?

`loaded_model.get_topic_info()`

Many many thanks for you reply!

**Comment by MaartenGr** [comment]
> Sorry, I come back again. I have three questions to ask.

No problem! I am happy to help out 🙂

> ---------------------------------First Question---------------------------------
When I try to combine word embedding and sentence embedding. I get this error:

This might be related to the gensim version that you are using. Could you share the version that you have? 

Also, I noticed that you are using the `WordDocEmbedder` to create different embeddings for documents and words. This works quite well if you are using the `diversity` parameter but since this parameter is not set there are no word embeddings generated. In other words, you can remove the `Gensim` model and only use the `SentenceTransformer` model and the results should be the same. 

> ---------------------------------Second Question---------------------------------
> For BERTopic, is the more training data it has, the better performance it will get?

Typically, yes! With more training data more accurate lower-dimensional representations can be created through UMAP and also HDBSCAN will have more clusters/topics to find. I should note however, that this effect becomes smaller and smaller when you are approaching millions of documents. In my experience, you already have an accurate representation with tens of thousands of documents. So if you do not have enough RAM or power available, using a subset of 100,000 documents, if you have millions, would already give you nice results. 

> ---------------------------------Third Question---------------------------------
> My idea is to send all the docs of one topic at a time into the model training and save the model at the end. Do you think is useful? When I load it again and using follow code to see the topic, it will show the last training topic, why this happened?

With most machine learning models that adopt a `fit` method it re-trains the entire model. Thus, you are re-training the entire model with each set of documents and only the most recent one will be saved. Instead, it might be better to simply add all documents at once to BERTopic and perhaps use the `y` parameter if you want a supervised approach.

**Comment by HarrywillDr** [comment]
Hi, thanks!

May I ask how I implement training the model with different data inputs each time, as these data belong to different topics and should not be put into the model at the same time?

**Comment by HarrywillDr** [comment]
I want the (n+1)th batch of data to be trained on top of the model that was trained by the (n)th batch of data.

**Comment by MaartenGr** [comment]
> May I ask how I implement training the model with different data inputs each time, as these data belong to different topics and should not be put into the model at the same time?

The model should capture data that contains data that belong to different topics, so it might actually be worthwhile to put it all into the model at the same time. Having said that, if you want to separate them, you would have to create separate models:


```python
topic_model_1 = BERTopic().fit(docs_1)
topic_model_2 = BERTopic().fit(docs_2)
topic_model_3 = BERTopic().fit(docs_3)
.
.
.
```

> I want the (n+1)th batch of data to be trained on top of the model that was trained by the (n)th batch of data.

At this moment, you cannot continue training the model that was already previously trained. Instead, you would need to combine the data:

```python
topic_model = BERTopic().fit(docs_1 + docs_2)
```

Having said that, if the documents are in the same domain but contain different topics there is a good chance that combining all documents and passing them all at once to the model would actually be preferred.

**Comment by HarrywillDr** [comment]
Thanks!

**Comment by HarrywillDr** [comment]
by the way, if I created separate models means I cannot use the outputs of them all right? Just using one of them for test.

**Comment by MaartenGr** [comment]
> by the way, if I created separate models means I cannot use the outputs of them all right? Just using one of them for test.

That depends on the purpose for which you are using it. In other words, how would you intend on using the outputs?

**Comment by HarrywillDr** [comment]
Thanks!
