### ISSUE TITLE
how can i use gpu on BERTopic on windows10

### ISSUE THREAD

**Issue by sxxyxn** [MaartenGr/BERTopic#539]
I wanna use GPU on BERTopic. But I can't.
```
import os

os.environ["CUDA_DEVICE_ORDER"]="PCI_BUS_ID"]
os.environ["CUDA_VISIBLE_DEVICES"]="0"
```
this is on my code.
but BERTopic runs with only CPU.

and when I use this code:
```
from tensorflow.python.client import device_lib
device_lib.list_local_devices()
```
I can see the "GPU"

```
[name: "/device:CPU:0"
 device_type: "CPU"
 memory_limit: 268435456
 locality {
 }
 incarnation: 16037690728622378684
 xla_global_id: -1,
 name: "/device:GPU:0"
 device_type: "GPU"
 memory_limit: 7027870924
 locality {
    bus_id: 1
    links {
    }
 }
 incarnation: 9015017086130581689
 physical_device_desc: "device: 0, name: NVIDIA GeForce RTX 3080, pci bus id: 0000:01:00.0 compute capability: 8.6"
 xla_global_id: 416903419]
```

and I added this:
```
if tf.config.experimental.list_physical_devics('GPU'):
    with tf.device('/device:GPU:0'):
        model = BERTopic(embedding_model=SentenceTransformer('C:\\Users\\username\\abc'),
                                      vectorizer_model=vectorizer,
                                      nr_topics=7,
                                      top_n_words=10,
                                      calculate_probabilities=True)
        topics, probs = model.fit_transform(df[0])
```
but it works on only CPU neither.

I saw the `cuML`things. but that's not work on windows. right?

how can I use GPU... 
my env is windows10, cuda11.6, rtx3080ti and no connection with internet.

**Comment by MaartenGr** [comment]
> `from tensorflow.python.client import device_lib`
> `device_lib.list_local_devices()`
> I can see the "GPU"

SentenceTransformers uses Pytorch, so although tensorflow can see your GPU this might not be the case for Pytorch. A way of checking whether it is using your GPU is by following [this StackOverflow answer](https://stackoverflow.com/a/48152675). 

After doing so and confirming that you should be using the GPU, it might be helpful to try out SentenceTransformers first to see if you get the speed-up you were looking for:

```python
from sklearn.datasets import fetch_20newsgroups
from sentence_transformers import SentenceTransformer

# Prepare embeddings
docs = fetch_20newsgroups(subset='all',  remove=('headers', 'footers', 'quotes'))['data']
sentence_model = SentenceTransformer("all-MiniLM-L6-v2")
embeddings = sentence_model.encode(docs, show_progress_bar=True)
```

> `if tf.config.experimental.list_physical_devics('GPU'):`
>    `with tf.device('/device:GPU:0'):`

This is not necessary as SentenceTransformers will automatically select your GPU if it can find one. 

> I saw the cuMLthings. but that's not work on windows. right?

I believe that is indeed correct. You can run WSL2 on windows and run Linux there using [this tutorial](https://developer.nvidia.com/blog/run-rapids-on-microsoft-windows-10-using-wsl-2-the-windows-subsystem-for-linux/) but it is not the easiest and most straightforward approach for installing and maintaining this.
