### ISSUE TITLE
Topic 0 is not plotted when using .visualize_topics()

### ISSUE THREAD

**Issue by MennoBruinsma** [MaartenGr/BERTopic#541]
When I plotted my found topics I noticed that the largest cluster which has an index of 0 was not being plotted when using .visualize_topics().

**Comment by MaartenGr** [comment]
That most likely happens when you used a different clustering model, right? In that case, you can find a fix in the main branch of this repo. You can find a similar issue [here](https://github.com/MaartenGr/BERTopic/issues/533). Hopefully, this fixes the issue for you!

**Comment by MennoBruinsma** [comment]
Thanks for the quick response! I used HDBSCAN as clustering model but this fixed the issue. Amazing module by the way!
