### ISSUE TITLE
BERTopic and CuML on Azure Databricks

### ISSUE THREAD

**Issue by nilsblessing** [MaartenGr/BERTopic#542]
Hi all!

My issue is not directly related to BERTopic itself, yet I follow the issues combining CuML and BERTopic for performance acceleration with great interest.

Unfortunately, I have not yet been able to get the CuML implementations of UMAP and HDBSCAN to work on Azure Databricks in conjunction with the latest BERTopic release. I have managed to use CuML on its own with the help of a Docker image, but the installation of BERTopic does not work.

Is there any experience on how I can best get this to work?

Kind regards,
Nils

**Comment by beckernick** [comment]
Would you be able share the Dockerfile/manifest of the container that you're using and what the error you saw was?

**Comment by nilsblessing** [comment]
Sure, maybe some further information also help:

Cluster configuration:
- Diver: Standard_NC6s_v3
- Worker: Standard_NC6s_v3 (1-2)
- Autoscaling enabled
- DBR: 9.1 LTS
- Docker image: databricksruntime/gpu-rapids:cuda11

Error occured:
"ValueError: Invalid Cluster Selection Method: %s"

I used "!conda install -c conda-forge bertopic" first which installed BERTopic 0.94.0 version. Also tried to install the latest version via "!conda install -c conda-forge bertopic==0.10.0" command. (pip command didn't work with the mentioned Docker image)

Code used from #495:

```
from bertopic import BERTopic
from cuml.cluster import HDBSCAN
from cuml.manifold import UMAP

# Create instances of GPU-accelerated UMAP and HDBSCAN
umap_model = UMAP(n_components=5, min_dist=0.0)
hdbscan_model = HDBSCAN(min_samples=20, gen_min_span_tree=True)

# Pass the above models to be used in BERTopic
topic_model = BERTopic(umap_model=umap_model, hdbscan_model=hdbscan_model)
topics, probs = topic_model.fit_transform(docs)
```


Kind regards,
Nils

**Comment by nilsblessing** [comment]
Thanks @beckernick for your efforts to recreate my problem in such detail!

Unfortunately it didn't work on the first try but that's probably because I've only ever used Azure Databricks "off-the-shelf" without any further modifications to the instance. Nevertheless, with a bit of trial and error, I managed to install BERTopic via PIP. However, I received similar warnings as you mentioned.

The import thus worked, a small test run as well. I am curious if and when I will encounter problems related to the warnings. Anyway, thank you so much for your support!

Best regards,
Nils
