### ISSUE TITLE
Topic 0 not appearing in visualize_topics(top_n_topics=20)

### ISSUE THREAD

**Issue by DerSteph** [MaartenGr/BERTopic#546]
Hello,
if I enter the command topic_model.visualize_topics(top_n_topics=20), I get a distance map as expected, but the topic 0 is not displayed here.
![image](https://user-images.githubusercontent.com/37001354/170662455-4f78c945-2e30-4398-b679-1f368ee065bd.png)
I have already seen that there is already a [closed issue](https://github.com/MaartenGr/BERTopic/issues/472) on the topic on another visualization. I have installed the version 0.10.0.

**Comment by MaartenGr** [comment]
@DerSteph Thank you for sharing this. This is a known issue that you can find [here](https://github.com/MaartenGr/BERTopic/issues/533) and [here](https://github.com/MaartenGr/BERTopic/issues/541) which is fixed in the main branch of BERTopic but not yet in a new release. Installing BERTopic through the latest commit will solve your issue.

**Comment by manika-lamba** [comment]
@MaartenGr When will you publish the new release with this fix?

**Comment by jacobceles** [comment]
> Installing BERTopic through the latest commit will solve your issue.

@MaartenGr  Thank you! I was also facing the same issue and this resolved the problem.

**Comment by jacobceles** [comment]
> Hi, @MaartenGr! Could you please share how to install BERTopic through the latest commit? Thanks in advance!

@manika-lamba If you are using pip, you can install the specific commit using the command:
`pip install git+https://github.com/MaartenGr/BERTopic.git@407fd4fdf2e05e80019c1c217972bf3314a41040`

> @MaartenGr When will you publish the new release with this fix?

Based on what was mentioned in #533, I don't think there will be a release anytime soon.

**Comment by manika-lamba** [comment]
@jacobceles Thank you so much!

**Comment by manika-lamba** [comment]
@jacobceles @MaartenGr I used `pip install git+https://github.com/MaartenGr/BERTopic.git@407fd4fdf2e05e80019c1c217972bf3314a41040` but it is still not showing Topic 0 :(
![newplot (9)](https://user-images.githubusercontent.com/67724354/170841926-b4e029ca-d8cf-4281-9f84-0fb45240e434.png)

**Comment by MaartenGr** [comment]
Seeing as this was fixed in v0.11, I will be closing this issue. If, however, you still run into this issue, please let me know!
