### ISSUE TITLE
How to get tweets related with particular topic?

### ISSUE THREAD

**Issue by srbnghosh99** [MaartenGr/BERTopic#548]
Hi,

I am able to get the representative docs under a topic from BERTopic model. 
However, I want get the set of tweets under the topics. Is there any way to extract those tweets.

Also, I want to generate more than 10 words (top_n_words) using the parameter. But I am not getting more or less than 10 words under each topic. 

Please suggest. 

Thanks
Shrabani Ghosh

**Comment by MaartenGr** [comment]
> I am able to get the representative docs under a topic from BERTopic model.
However, I want get the set of tweets under the topics. Is there any way to extract those tweets.

The package follows, to a certain extent, sklearn's API in that whenever you use `transform` on a set of documents, it will return the topics in the same order. Let's say you have the following code:

```python
from bertopic import BERTopic
from sklearn.datasets import fetch_20newsgroups

docs = fetch_20newsgroups(subset='all',  remove=('headers', 'footers', 'quotes'))['data']

topic_model = BERTopic()
topics, probs = topic_model.fit_transform(docs)
```
Here, `docs` is a list of documents on which you train the model. Running `.fit_transform(docs)` will return the variable `topics`. In `topics`, you will find the topics that belong to each documents. The topic in `topics[0]` corresponds to the document in `docs[0]`, `topics[1]` to `docs[1]`, etc. 

You can use that structure to extract the documents under a certain topic by using, for example, the following:

```python
import pandas as pd
results = pd.DataFrame({"Doc": docs, "Topic": topics})
```

> Also, I want to generate more than 10 words (top_n_words) using the parameter. But I am not getting more or less than 10 words under each topic.

If I run the following, I can get the top 20 words per topic:

```python
from bertopic import BERTopic
from sklearn.datasets import fetch_20newsgroups

docs = fetch_20newsgroups(subset='all',  remove=('headers', 'footers', 'quotes'))['data']

topic_model = BERTopic(top_n_words=20)
topics, probs = topic_model.fit_transform(docs)
topic_model.get_topic(0)
```

Could you share your code for training and extracting the top n topics? Perhaps something is going wrong there. Also, which version of BERTopic are you using?

**Comment by srbnghosh99** [comment]
Thank you for your response. 
I have total 37816 unique tweets. 
i have got same number of length of docs.
And I have got 419 topics from the model using model.get_topic_info() --> 419

now how to get all the tweets which are under topic(ex: topic 2)
I believe there are many tweets involved to get one topic.

**Comment by srbnghosh99** [comment]
I am trying with:
representative_docs = topic_model.get_representative_docs(12)
it is showing for each topic , 3 tweets are used. 
how only 3 tweets are stored in each representative doc for each topic?

**Comment by MaartenGr** [comment]
> now how to get all the tweets that are under topic(ex: topic 2)
I believe there are many tweets involved to get one topic.

To get all the tweets that are under a topic (e.g., 2) you can follow along with the code I posted above your post. The `results` variable then contains two columns, one with all documents and one with all topics. So you could find all tweets which are under a topic as follows:

```python
topic = 2
results.loc[results.Topic == topic, :]
```

> I am trying with:
representative_docs = topic_model.get_representative_docs(12)
it is showing for each topic , 3 tweets are used.
how only 3 tweets are stored in each representative doc for each topic?

The reason why you are only seeing 3 tweets is that we do not want to save all possible tweets for each topic in the topic model. Doing so would require quite a lot of a space, especially if you have millions of documents. Moreover, not every tweet is as representative for a topic as another. So focusing on a few representative tweets for each topic helps with the interpretability of the topic.
