### ISSUE TITLE
Run BERTopic on tokenized texts

### ISSUE THREAD

**Issue by vanatteveldt** [MaartenGr/BERTopic#551]
First off, thanks for the great package!

I have a situation where I am not allowed to export full text of documents, but I can run a tokenizer and export the resulting tokens, e.g. using huggingface `transformers.AutoTokenizer`. 

Is it possible to run BERTopic on this preprocessing output rather than on the document texts directly?

Thanks,

Wouter

**Comment by MaartenGr** [comment]
Yes, BERTopic uses a transformer-based model to perform the embeddings and as such requires full text, in the correct order, without too much preprocessing.

**Comment by vanatteveldt** [comment]
Thanks!
