### ISSUE TITLE
get more than 3 representative docs from get_representative_docs()

### ISSUE THREAD

**Issue by studentdave** [MaartenGr/BERTopic#552]
is there a way to get N (more than 3) representative docs from get_representative_docs() ?

**Comment by drob-xx** [comment]
The code explicitly saves only three documents:

```
                  representative_docs[topic] = list(np.random.choice(result, 3, replace=False).astype(int))

        # Convert indices to documents
        self.representative_docs = {topic: [documents.iloc[doc_id].Document for doc_id in doc_ids]
                                    for topic, doc_ids in
                                    representative_docs.items()}

```

What is your use case?

**Comment by studentdave** [comment]
ah. thx you. i'm first curious about how the "representative" doc are selected. and I would like to get more of them. i want like 20 of them. it helps with human review

**Comment by MaartenGr** [comment]
The representative documents are based on HDBSCAN's exemplar points. Essentially, those are points that best represent a density-based cluster. You can find a bit more about that [here](https://hdbscan.readthedocs.io/en/latest/soft_clustering_explanation.html#distance-based-membership). I chose to only save three documents as it can quickly result in saving too much text in the model whenever you have millions of documents. Adding yet another parameter for increasing that value would make it a bit more difficult to use with the number of parameter to not only know about but also tweak. 

Fortunately, the code of BERTopic is rather straightforward and you could adapt it to your use cases as such:

```python
import numpy as np
import pandas as pd
import hdbscan
from bertopic import BERTopic

class BERTopicNew(BERTopic):
    def _save_representative_docs(self, documents: pd.DataFrame):
        """ Save the most representative docs (3) per topic
        The most representative docs are extracted by taking
        the exemplars from the HDBSCAN-generated clusters.
        Full instructions can be found here:
            https://hdbscan.readthedocs.io/en/latest/soft_clustering_explanation.html
        Arguments:
            documents: Dataframe with documents and their corresponding IDs
        """
        # Prepare the condensed tree and luf clusters beneath a given cluster
        condensed_tree = self.hdbscan_model.condensed_tree_
        raw_tree = condensed_tree._raw_tree
        clusters = sorted(condensed_tree._select_clusters())
        cluster_tree = raw_tree[raw_tree['child_size'] > 1]

        #  Find the points with maximum lambda value in each leaf
        representative_docs = {}
        for topic in documents['Topic'].unique():
            if topic != -1:
                leaves = hdbscan.plots._recurse_leaf_dfs(cluster_tree, clusters[topic])

                result = np.array([])
                for leaf in leaves:
                    max_lambda = raw_tree['lambda_val'][raw_tree['parent'] == leaf].max()
                    points = raw_tree['child'][(raw_tree['parent'] == leaf) & (raw_tree['lambda_val'] == max_lambda)]
                    result = np.hstack((result, points))
                
                # CHANGED THE VALUE OF 3 REPRESENTATIVE DOCS TO 20 HERE:
                representative_docs[topic] = list(np.random.choice(result, 20, replace=False).astype(int))

        # Convert indices to documents
        self.representative_docs = {topic: [documents.iloc[doc_id].Document for doc_id in doc_ids]
                                    for topic, doc_ids in
                                    representative_docs.items()}
```

Then, you can use that new class as follows instead of the original BERTopic:

```python
topic_model = BERTopicNew()
topics, probs = topic_model.fit_transform(docs)
```

Do note that each topic should have at least 20 documents for this to work.

**Comment by studentdave** [comment]
extremely helpful. much appreciated #teachingtofish

**Comment by studentdave** [comment]
I attempted to apply your code. i think i'm missing something

```
#build new bert topic class
import numpy as np
import pandas as pd
import hdbscan
from bertopic import BERTopic

class BERTopicNew(BERTopic):
    def _save_representative_docs(self, documents: pd.DataFrame):
        """ Save the most representative docs (3) per topic
        The most representative docs are extracted by taking
        the exemplars from the HDBSCAN-generated clusters.
        Full instructions can be found here:
            https://hdbscan.readthedocs.io/en/latest/soft_clustering_explanation.html
        Arguments:
            documents: Dataframe with documents and their corresponding IDs
        """
        # Prepare the condensed tree and luf clusters beneath a given cluster
        condensed_tree = self.hdbscan_model.condensed_tree_
        raw_tree = condensed_tree._raw_tree
        clusters = sorted(condensed_tree._select_clusters())
        cluster_tree = raw_tree[raw_tree['child_size'] > 1]

        #  Find the points with maximum lambda value in each leaf
        representative_docs = {}
        for topic in documents['Topic'].unique():
            if topic != -1:
                leaves = hdbscan.plots._recurse_leaf_dfs(cluster_tree, clusters[topic])

                result = np.array([])
                for leaf in leaves:
                    max_lambda = raw_tree['lambda_val'][raw_tree['parent'] == leaf].max()
                    points = raw_tree['child'][(raw_tree['parent'] == leaf) & (raw_tree['lambda_val'] == max_lambda)]
                    result = np.hstack((result, points))
                
                # CHANGED THE VALUE OF 3 REPRESENTATIVE DOCS TO 20 HERE:
                representative_docs[topic] = list(np.random.choice(result, 20, replace=False).astype(int))

        # Convert indices to documents
        self.representative_docs = {topic: [documents.iloc[doc_id].Document for doc_id in doc_ids]
                                    for topic, doc_ids in
                                    representative_docs.items()}

hdbscan_model_used = hdbscan(min_cluster_size=700, metric='euclidean', 
                        cluster_selection_method='eom', prediction_data=True, min_samples=25)

#build the topic modeler, lots of customization done here
topic_model = BERTopicNew(embedding_model="all-mpnet-base-v2",
                       hdbscan_model=hdbscan_model_used,
                       min_topic_size=700, #empercially determined to be pretty good. 
                       language="english", 
                       calculate_probabilities=True, 
                       verbose=True)

topics, probs = topic_model.fit_transform(docs)


---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<timed exec> in <module>

TypeError: 'module' object is not callable

```

**Comment by fsysean** [comment]
> The representative documents are based on HDBSCAN's exemplar points. Essentially, those are points that best represent a density-based cluster. You can find a bit more about that [here](https://hdbscan.readthedocs.io/en/latest/soft_clustering_explanation.html#distance-based-membership). I chose to only save three documents as it can quickly result in saving too much text in the model whenever you have millions of documents. Adding yet another parameter for increasing that value would make it a bit more difficult to use with the number of parameter to not only know about but also tweak.
> 
> Fortunately, the code of BERTopic is rather straightforward and you could adapt it to your use cases as such:
> 
> ```python
> import numpy as np
> import pandas as pd
> import hdbscan
> from bertopic import BERTopic
> 
> class BERTopicNew(BERTopic):
>     def _save_representative_docs(self, documents: pd.DataFrame):
>         """ Save the most representative docs (3) per topic
>         The most representative docs are extracted by taking
>         the exemplars from the HDBSCAN-generated clusters.
>         Full instructions can be found here:
>             https://hdbscan.readthedocs.io/en/latest/soft_clustering_explanation.html
>         Arguments:
>             documents: Dataframe with documents and their corresponding IDs
>         """
>         # Prepare the condensed tree and luf clusters beneath a given cluster
>         condensed_tree = self.hdbscan_model.condensed_tree_
>         raw_tree = condensed_tree._raw_tree
>         clusters = sorted(condensed_tree._select_clusters())
>         cluster_tree = raw_tree[raw_tree['child_size'] > 1]
> 
>         #  Find the points with maximum lambda value in each leaf
>         representative_docs = {}
>         for topic in documents['Topic'].unique():
>             if topic != -1:
>                 leaves = hdbscan.plots._recurse_leaf_dfs(cluster_tree, clusters[topic])
> 
>                 result = np.array([])
>                 for leaf in leaves:
>                     max_lambda = raw_tree['lambda_val'][raw_tree['parent'] == leaf].max()
>                     points = raw_tree['child'][(raw_tree['parent'] == leaf) & (raw_tree['lambda_val'] == max_lambda)]
>                     result = np.hstack((result, points))
>                 
>                 # CHANGED THE VALUE OF 3 REPRESENTATIVE DOCS TO 20 HERE:
>                 representative_docs[topic] = list(np.random.choice(result, 20, replace=False).astype(int))
> 
>         # Convert indices to documents
>         self.representative_docs = {topic: [documents.iloc[doc_id].Document for doc_id in doc_ids]
>                                     for topic, doc_ids in
>                                     representative_docs.items()}
> ```
> 
> Then, you can use that new class as follows instead of the original BERTopic:
> 
> ```python
> topic_model = BERTopicNew()
> topics, probs = topic_model.fit_transform(docs)
> ```
> 
> Do note that each topic should have at least 20 documents for this to work.

Sampling is working great. But Some thing wrong with this code. The topic IDs are not matching with documents.

**Comment by MaartenGr** [comment]
@fsysean Could you share your full code for running this? This seems to be working for me and a reproducible example would help greatly in understanding where things might go wrong.

**Comment by fsysean** [comment]
> @fsysean Could you share your full code for running this? This seems to be working for me and a reproducible example would help greatly in understanding where things might go wrong.

import pandas as pd
df=pd.read_csv('')

from sklearn.metrics import silhouette_score


from sentence_transformers import SentenceTransformer

from bertopic import BERTopic

from umap import UMAP
# In BERTopic, we typically use UMAP as it is able to capture both the local and global high-dimensional space in lower dimensions.
import numpy as np
import gensim.corpora as corpora
from gensim.models.coherencemodel import CoherenceModel
from hdbscan import HDBSCAN
from sklearn.feature_extraction.text import CountVectorizer

docs=df['Text'].to_list()

hdbscan_model = HDBSCAN(min_cluster_size=40, metric='euclidean', 
                        cluster_selection_method='eom', prediction_data=True, min_samples=2,cluster_selection_epsilon=0.2)
umap_model = UMAP(n_neighbors=15, n_components=5, min_dist=0.0, metric='cosine', random_state=42)


sentence_model = SentenceTransformer("all-mpnet-base-v2")
embeddings = sentence_model.encode(docs, show_progress_bar=False)


vectorizer_model = CountVectorizer(stop_words="english")





topic_model = BERTopicNew(diversity=0.25,umap_model=umap_model,hdbscan_model=hdbscan_model,top_n_words=10,n_gram_range=(1, 2),vectorizer_model=vectorizer_model).fit(docs)
topics, probs  = topic_model.fit_transform(docs,embeddings)

dfrepresentative = pd.DataFrame.from_dict(topic_model.get_representative_docs())
display(dfrepresentative)

**Comment by fsysean** [comment]
In your function, you has a code 

`clusters = sorted(condensed_tree._select_clusters())`

and in the following topic loop, you has a code 

`leaves = hdbscan.plots._recurse_leaf_dfs(cluster_tree, clusters[topic])`

Then, I have a question. Does those codes mean that cluster id = topic id? 

Why don't you use `leaves = hdbscan.plots._recurse_leaf_dfs(cluster_tree, topic)`

Thank you!

**Comment by fsysean** [comment]
If cluster id != topic id, why did you sort condensed_tree._select_clusters()?

**Comment by fsysean** [comment]
> @fsysean After some testing it seems to be related to the `cluster_selection_epsilon` that you set in your custom HDBSCAN model. Removing that parameter in its entirety resolves the issue. With respect to the questions above, I would highly advise reading through the examples [here](https://hdbscan.readthedocs.io/en/latest/soft_clustering_explanation.html) on the HDBSCAN library as it does a much better job at explaining extracting exemplars than I could.

Thank you so much!

**Comment by peiwenT6** [comment]
> The representative documents are based on HDBSCAN's exemplar points. Essentially, those are points that best represent a density-based cluster. You can find a bit more about that [here](https://hdbscan.readthedocs.io/en/latest/soft_clustering_explanation.html#distance-based-membership). I chose to only save three documents as it can quickly result in saving too much text in the model whenever you have millions of documents. Adding yet another parameter for increasing that value would make it a bit more difficult to use with the number of parameter to not only know about but also tweak.
> 
> Fortunately, the code of BERTopic is rather straightforward and you could adapt it to your use cases as such:
> 
> ```python
> import numpy as np
> import pandas as pd
> import hdbscan
> from bertopic import BERTopic
> 
> class BERTopicNew(BERTopic):
>     def _save_representative_docs(self, documents: pd.DataFrame):
>         """ Save the most representative docs (3) per topic
>         The most representative docs are extracted by taking
>         the exemplars from the HDBSCAN-generated clusters.
>         Full instructions can be found here:
>             https://hdbscan.readthedocs.io/en/latest/soft_clustering_explanation.html
>         Arguments:
>             documents: Dataframe with documents and their corresponding IDs
>         """
>         # Prepare the condensed tree and luf clusters beneath a given cluster
>         condensed_tree = self.hdbscan_model.condensed_tree_
>         raw_tree = condensed_tree._raw_tree
>         clusters = sorted(condensed_tree._select_clusters())
>         cluster_tree = raw_tree[raw_tree['child_size'] > 1]
> 
>         #  Find the points with maximum lambda value in each leaf
>         representative_docs = {}
>         for topic in documents['Topic'].unique():
>             if topic != -1:
>                 leaves = hdbscan.plots._recurse_leaf_dfs(cluster_tree, clusters[topic])
> 
>                 result = np.array([])
>                 for leaf in leaves:
>                     max_lambda = raw_tree['lambda_val'][raw_tree['parent'] == leaf].max()
>                     points = raw_tree['child'][(raw_tree['parent'] == leaf) & (raw_tree['lambda_val'] == max_lambda)]
>                     result = np.hstack((result, points))
>                 
>                 # CHANGED THE VALUE OF 3 REPRESENTATIVE DOCS TO 20 HERE:
>                 representative_docs[topic] = list(np.random.choice(result, 20, replace=False).astype(int))
> 
>         # Convert indices to documents
>         self.representative_docs = {topic: [documents.iloc[doc_id].Document for doc_id in doc_ids]
>                                     for topic, doc_ids in
>                                     representative_docs.items()}
> ```
> 
> Then, you can use that new class as follows instead of the original BERTopic:
> 
> ```python
> topic_model = BERTopicNew()
> topics, probs = topic_model.fit_transform(docs)
> ```
> 
> Do note that each topic should have at least 20 documents for this to work.

I have tried the code, but the output of "representative_docs" is NAN. It is so strange. I just modify "representative_docs[topic] = list(np.random.choice(result, 20, replace=False).astype(int))" to "representative_docs[topic] = list(np.random.choice(result, 5, replace=False).astype(int))"

**Comment by MaartenGr** [comment]
@peiwenT6 You're right! This was on an older version of BERTopic. You can now run it as such:


```python
import numpy as np
import pandas as pd
import hdbscan
from bertopic import BERTopic

class BERTopicNew(BERTopic):
    def _save_representative_docs(self, documents: pd.DataFrame):
        """Save the 3 most representative docs per topic.

        Arguments:
            documents: Dataframe with documents and their corresponding IDs

        Updates:
            self.representative_docs_: Populate each topic with 3 representative docs
        """
        repr_docs, _, _, _ = self._extract_representative_docs(
            self.c_tf_idf_,
            documents,
            self.topic_representations_,
            nr_samples=500,
            nr_repr_docs=20, # CHANGE THIS VALUE
        )
        self.representative_docs_ = repr_docs
```

Note that whenever you change private functions, it cannot be guaranteed to works across versions. I'm using this example for the current latest version, v0.16.4.

**Comment by peiwenT6** [comment]
> @peiwenT6 You're right! This was on an older version of BERTopic. You can now run it as such:
> 
> ```python
> import numpy as np
> import pandas as pd
> import hdbscan
> from bertopic import BERTopic
> 
> class BERTopicNew(BERTopic):
>     def _save_representative_docs(self, documents: pd.DataFrame):
>         """Save the 3 most representative docs per topic.
> 
>         Arguments:
>             documents: Dataframe with documents and their corresponding IDs
> 
>         Updates:
>             self.representative_docs_: Populate each topic with 3 representative docs
>         """
>         repr_docs, _, _, _ = self._extract_representative_docs(
>             self.c_tf_idf_,
>             documents,
>             self.topic_representations_,
>             nr_samples=500,
>             nr_repr_docs=20, # CHANGE THIS VALUE
>         )
>         self.representative_docs_ = repr_docs
> ```
> 
> Note that whenever you change private functions, it cannot be guaranteed to work across versions. I'm using this example for the current latest version, v0.16.4.

Thank you so much for your quick response! But my bertopic model version is 0.15.0. I have tried the above code, unfortunately it does not work for me. I want to know how can I modify the code to adapt to my current version? I am so sorry for my poor programming foundation.

**Comment by MaartenGr** [comment]
@peiwenT6 Couldn't you use v0.16.4 instead? Since you are training, you can easily switch over right?

**Comment by peiwenT6** [comment]
> @peiwenT6 Couldn't you use v0.16.4 instead? Since you are training, you can easily switch over right?

Sure! I apologize for not considering this matter more carefully. Thank you very much for your kind help!
