### ISSUE TITLE
No keywords and weird topic

### ISSUE THREAD

**Issue by km5ar** [MaartenGr/BERTopic#554]
1. There are no keywords for topic 1_cbd_isolate_anxiety_thc
2. topic 2 seems to have a very weird topic while the keywords looks fine

<img width="627" alt="image" src="https://user-images.githubusercontent.com/54015474/171702731-d760e845-31a2-4e1a-8b44-550a20dd1de2.png">

**Comment by MaartenGr** [comment]
From your dataframe, it seems that you have assigned keywords to the wrong topic by indexing on the previous index. Take the image below:

![image](https://user-images.githubusercontent.com/25746895/171720982-020a25a1-a1f6-48a6-ac43-32b440126d36.png)

Here, you can see that the words in topic 3, `addiction`, `quit`, `cravings` and `addicted` actually appear in the keywords of topic 2. This is indicated by the blue rectangles. This is the same for every single topic. The topic words of topic 4 are found with the keywords of topic 3 (red) and the topic words of topic 5 are found with the keywords topic 4 (green).

**Comment by MaartenGr** [comment]
Without looking at the documents, my guess would be that the documents in topic 2 are mostly empty or very short such that the resulting topic representations are empty.
