### ISSUE TITLE
llvmlite Error when install 

### ISSUE THREAD

**Issue by orenschonlab** [MaartenGr/BERTopic#56]
Hi, I am trying to install BERTopic on mac and get the error:
```

    ----------------------------------------
ERROR: Command errored out with exit status 1: ./venv/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/39/88clnp910zlg54lrgy0d7qm40000gn/T/pip-install-0b7qoglk/llvmlite_1f4cd98020be43c1adad1fa52c6be7a7/setup.py'"'"'; __file__='"'"'/private/var/folders/39/88clnp910zlg54lrgy0d7qm40000gn/T/pip-install-0b7qoglk/llvmlite_1f4cd98020be43c1adad1fa52c6be7a7/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/39/88clnp910zlg54lrgy0d7qm40000gn/T/pip-record-mk9vn8xa/install-record.txt --single-version-externally-managed --compile --install-headers ./venv/include/site/python3.9/llvmlite Check the logs for full command output.

```

Any idea?

**Comment by MaartenGr** [comment]
Which version of BERTopic are you currently using? This seems to be an issue with joblib. Make sure the joblib version is lower than v1.0. Moreover, there is currently a new version of BERTopic in the works that will be released in the coming days which should fix a few issues. 

Lastly, there are numpy/pypi issues floating around that might make the installation more difficult (#55, #46). Checking out these resources might help.

**Comment by orenschonlab** [comment]
@MaartenGr I tried to install the latest stable using pip. Downgrading to joblib v0.1 didn't help. I might just wait to the new version - when is it expected?
Thanks

**Comment by MaartenGr** [comment]
Both issues I referenced have a few more things that you can try, including using `--no-cache-dir --no-binary :all: --no-build-isolation` to install the package or sub-packages. Also, click [here](https://github.com/MaartenGr/BERTopic/pull/46#pullrequestreview-580137083) for multiple discussions on this issue in UMAP and HDBSCAN that could help you out. 

It will be released this week and I am hoping I can finish it either today or tomorrow, but I cannot make any promises. The new release should make installation easier. However, it doesn't fully prevent these issues from happening. If, after the new release, you still run into these problems, I strongly suggest you check out the discussions I referenced. It is a complex problem for which there, unfortunately, is no solid solution yet.

**Comment by MaartenGr** [comment]
@orenschonlab I just released BERTopic v0.5 with several improvements to the API, see the [changelog](https://maartengr.github.io/BERTopic/changelog.html). I believe this version should help you with the issues that you are currently facing. If not, let me know!

**Comment by MaartenGr** [comment]
These issues seem to be related to [this](https://github.com/numba/llvmlite/issues/621) discussion. Reading through this I would suggest several things. First, make sure you create a fresh environment without any packages installed. Second, upgrade your `pip` version as old versions may block downloading the corresponding wheels. Finally, if that does not work, please take a look at wenhaomao's comment in the linked discussion.

**Comment by stepthom** [comment]
I also was recieving this error when I tried to `pip install`. The fix for me was to create a blank pip environment and install `bertopic` first.
