### ISSUE TITLE
Question about usage of multilingual model

### ISSUE THREAD

**Issue by leifericf** [MaartenGr/BERTopic#561]
I have a dataset containing texts in four different languages: Danish, Finnish, Norwegian, and Swedish. In addition, I have a machine-translated version of those Nordic languages into English.

When I run BERTopic on the machine-translated English, the results are not great. That is probably because the text is very conversational and contains slang that does not translate well into English.

I see that BERTopic supports 50+ languages, so I want to try it on the original, untranslated texts in the Nordic languages. Still, I couldn't find a more detailed example of how BERTopics should be used in such scenarios.

Can I feed BERTopic four different languages in one go, or do I need to train four separate models, one for each language? Do I need to tell BERTopic what language the data is, or does it figure that out by itself?

Will BERTopic create cross-language categories if fed with several languages at once?

**Comment by MaartenGr** [comment]
> I see that BERTopic supports 50+ languages, so I want to try it on the original, untranslated texts in the Nordic languages. Still, I couldn't find a more detailed example of how BERTopics should be used in such scenarios.

BERTopic supports different embedding models, some of which indeed support these 50+ languages. Typically, you can run a multi-lingual model as follows: 

```python
topic_model = BERTopic(language="multilingual")
```

This automatically selects the `paraphrase-multilingual-MiniLM-L12-v2` model that you can find [here](https://www.sbert.net/docs/pretrained_models.html) which works quite well with embedding multiple languages at once. You could also select `paraphrase-multilingual-mpnet-base-v2` instead if you want a bit more accuracy:

```python
topic_model = BERTopic(embedding_model="paraphrase-multilingual-mpnet-base-v2")
```

> Can I feed BERTopic four different languages in one go, or do I need to train four separate models, one for each language? Do I need to tell BERTopic what language the data is, or does it figure that out by itself?

Yes, you can feed it four different languages in one go but the topic representation might be a bit more interpretable if you do it for one language at a time. Yes, you would also need to tell BERTopic what language the data is by selecting a model that works for one of those languages. 

> Will BERTopic create cross-language categories if fed with several languages at once?

Yes, although documents are written in separate languages there is a chance that the content will end up together if they are similar enough.

**Comment by leifericf** [comment]
Fantastic, thanks for the help and for sharing this great library! I've tried several different approaches, and the best approach seems to be creating separate models for each language. However, in my data visualization, it would be useful to combine them somehow to show synonymous topics between the different languages. I also need to figure out how to map the BERTopic model output back to the initial data frame from which the documents came, so I can create appropriate filters in my data visualization, which uses Dash.

**Comment by leifericf** [comment]
Awesome, thanks gain for the info, @MaartenGr! I will try that approach.
