### ISSUE TITLE
Very slow in dimensionality reduction

### ISSUE THREAD

**Issue by bupianlizhugui** [MaartenGr/BERTopic#565]
I found a problem when I was practicing the code. When the amount of data was more than 1000, the speed of dimensionality reduction was very slow and I could not see the progress. May I ask if there is any way to optimize dimensionality reduction quickly
？
![image](https://user-images.githubusercontent.com/12823207/173978062-6657a84d-6c20-4031-b885-f4a45aa04afc.png)

**Comment by MaartenGr** [comment]
There are ways of speeding up UMAP, which you can find in the documentation [here](https://maartengr.github.io/BERTopic/getting_started/tips_and_tricks/tips_and_tricks.html#speed-up-umap). Also, you can also use `cuml` to GPU-accelerate both HDBSCAN and UMAP which could significantly speed up computation. You can find a bit more about that [here](https://maartengr.github.io/BERTopic/getting_started/tips_and_tricks/tips_and_tricks.html#gpu-acceleration). 

Out of curiosity, how many documents are there in `cq_only_goodsname_lst`? If it is only 1000 documents, UMAP generally should not take 13 minutes to run.

**Comment by MaartenGr** [comment]
Due to inactivity, I'll be closing this for now. Let me know if you have any other questions related to this and I'll make sure to re-open the issue!
