### ISSUE TITLE
Pyyaml dependency clash

### ISSUE THREAD

**Issue by OmriPi** [MaartenGr/BERTopic#567]
Hi, I have a question regarding the pyyaml dependency of BERTopic:
BERTopic v0.10.0 requires pyyaml<6.0, but I'm using another library which requires pyyaml >= 6.0.
Is there a reason why specifically pyyaml<6.0 is required?
Or is it otherwise possible to update the requirement so that I can build my docker? (It refuses to build because of the clash)
Thanks!

**Comment by MaartenGr** [comment]
Yes, pyyaml >= 6.0 has been known to break BERTopic as you can find in the issues [here](https://github.com/MaartenGr/BERTopic/issues/288) and [here](https://github.com/MaartenGr/BERTopic/issues/294). You can try upgrading it but I think that will result in a number of issues, unfortunately.

**Comment by OmriPi** [comment]
Interesting, I have been using it with pyyaml 6.0 without problem so far. Anyway, I have fixed the dependency so it works now, but this remains a limitation.
