### ISSUE TITLE
Add a method to export all model output into a single flat data file

### ISSUE THREAD

**Issue by leifericf** [MaartenGr/BERTopic#568]
Currently, access to BERTopic model internals is through various `get_*` methods. It is a bit cumbersome to combine BERTopic with other data sources, write it to a database, use it in custom data visualization apps, etc.

It would be convenient if BERTopic offered a method to dump all topic- and document data into a single flat data structure containing all dimensions and facts, more readily available to larger data pipelines and non-Python applications.

Then, the user would not have to manually call various `get_*` methods in the correct sequence and join the results.

This `export_data()` method could provide options for different formats, such as CSV, JSON, or Pandas dataframe.

**Comment by MaartenGr** [comment]
> It is a bit cumbersome to combine BERTopic with other data sources, write it to a database, use it in custom data visualization apps, etc.

Could you elaborate on this a bit more? As in, which specific combinations of `get_*` functions are cumbersome to use? That way, I can have a better idea of the specific use cases upon which to improve. 

> It would be convenient if BERTopic offered a method to dump all topic- and document data into a single flat data structure containing all dimensions and facts, more readily available to larger data pipelines and non-Python applications.

The main difficulty here is that all document data is not saved within BERTopic as that results in the trained model being much larger than it needs to be, especially if you already have all the documents in a dedicated database. Having said that, which data would you want to export (cTFIDF matrix, topics, reduced topics, documents, probability matrix, topics over time, topics per class, etc.)?

**Comment by leifericf** [comment]
Thanks for the feedback!

After reading your response and questions, I realized I might have posted this feature request prematurely.

I will implement my solution using the available `get_*` methods to understand better what I need to implement the functionality I have in mind. After that, I will be able to elaborate, and better express my needs for such an export.

**Comment by leifericf** [comment]
I wrote my own wrapper module for the BERTopic `get_*` methods.

This is what it looks like so far:

```python
import pandas as pd
import common_utils
from typing import Union
from bertopic import BERTopic

TOPIC_MODEL = BERTopic.load("models/my_model")


def get_topics() -> pd.DataFrame:
    """Get all topics with top words and their scores."""
    df = pd.DataFrame.from_dict(TOPIC_MODEL.get_topics()).T.add_prefix("word_score_")
    df.reset_index(inplace=True)
    df.rename(columns={"index": "topic_id"}, inplace=True)
    return df


def get_topic(topic_id: int) -> pd.DataFrame:
    """Get words and their scores for a given topic."""
    df = pd.DataFrame(TOPIC_MODEL.get_topic(topic_id))
    df.columns = ["word", "score"]
    return df


def get_topic_frequency(topic_id: int = None) -> Union[pd.DataFrame, int]:
    """Get the the size of topics in descending order."""
    df = TOPIC_MODEL.get_topic_freq(topic_id)
    if isinstance(df, pd.DataFrame):
        df.reset_index(drop=True, inplace=True)
        df.columns = ["topic_id", "count"]
    return df


def get_topic_info(topic_id: int = None) -> pd.DataFrame:
    """Get information about one or all topics."""
    df = TOPIC_MODEL.get_topic_info(topic_id)
    df.reset_index(drop=True, inplace=True)
    df.columns = ["topic_id", "count", "topic_name"]
    return df


def get_documents(topic_id: int = None) -> pd.DataFrame:
    """Get representative documents for one or all topics."""
    df = (
        pd.DataFrame.from_dict(
            TOPIC_MODEL.get_representative_docs(topic_id), orient="index"
        )
        .sort_index()
        .add_prefix("document_")
    )
    df.reset_index(inplace=True)
    df.rename(columns={"index": "topic_id"}, inplace=True)
    return df


def find_topics(search_term: str, n_topics: int = 10) -> pd.DataFrame:
    """Find topics most similar to a given search term."""
    df = pd.DataFrame(TOPIC_MODEL.find_topics(search_term, n_topics)).T
    df[0] = df[0].astype(int)
    df.columns = ["topic_id", "score"]
    return df


def get_tidy_dataframe():
    dataframes = [get_topic_info(), get_topics(), get_documents()]
    df = common_utils.merge_dataframes(dataframes, "topic_id")
    return df
```

The function `get_tidy_dataframe()` will effectively combine topic names, frequencies, words, and documents into a single DataFrame, which I can then join with other datadrames used by my web application.

I also wrote this helper function to merge an arbitrary number of dataframes containing the same key:

```python
def merge_dataframes(dataframes: List[pd.DataFrame], key: str) -> pd.DataFrame:
    merged_dfs = dataframes[0]
    for df in dataframes[1:]:
        merged_dfs = pd.merge(
            merged_dfs,
            df,
            how="outer",
            on=key,
            suffixes=("", "_y"),
            validate="1:1",
        )
        df.drop(df.filter(regex="_y$").columns.tolist(), axis=1, inplace=True)
    return merged_dfs
```

**Comment by MaartenGr** [comment]
Thank you for sharing your code! The difficulty for me here is that if there will be a universal `get` function, it should return, aside from your example, the document-topic assignment, results from different extensions (e.g., topics over time and topics per class.), probabilities, etc. Due to their different dimensional space, I do not think all these sources fit within a single structure. It might be interesting to extend `get_topic_info` instead with a few additional parameters to include more information.

**Comment by leifericf** [comment]
> Thank you for sharing your code!

Of course, it's the least I can do!

Yes, I see what you mean. Making a data structure that works for all those different scenarios would be tricky.

The most cumbersome aspect is that the different `get_*` functions return different data structure types. Some methods, such as `get_topic_frequency()`, returns a DataFrame _or_ an integer. When using the API, I must check the return data type and reformat the data structure to whatever my application needs downstream.

My solution was to wrap all the methods to ensure they always return a DataFrame. I'm not sure if this is the most reasonable approach to take, and I might change it later, but it seems to be working well so far.
