### ISSUE TITLE
topic_model.save erroring out

### ISSUE THREAD

**Issue by studentdave** [MaartenGr/BERTopic#571]
i'm attempting to save a potentially large model (ran on 1.3Mil tweets) and when i try to save it out. i get this error

topic_model.save("topic_model_13mil")
....
>   /opt/conda/lib/python3.7/pickle.py in save_bytes(self, obj)
>     730             self._write_large_bytes(BINBYTES8 + pack("<Q", n), obj)
>     731         elif n >= self.framer._FRAME_SIZE_TARGET:
> --> 732             self._write_large_bytes(BINBYTES + pack("<I", n), obj)
>     733         else:
>     734             self.write(BINBYTES + pack("<I", n) + obj)
> 
> error: 'I' format requires 0 <= number <= 4294967295

not sure how to deal with this?

**Comment by MaartenGr** [comment]
I believe this is an issue with some of the internal settings for dumping large files. Some machines have a maximum of 4GB which you will need to adapt as mentioned [here](https://github.com/MaartenGr/BERTopic/issues/313). Another way of approaching this is by not saving the embedding model during `.save` and setting a `min_df` of at least 10 in a custom CountVectorizer to minimize the size of the resulting file.
