### ISSUE TITLE
How to merge closely related topics after topic reduction

### ISSUE THREAD

**Issue by leifericf** [MaartenGr/BERTopic#575]
After automatic topic reduction, I have 815 topics (down from 1271).

By looking at the topics, it seems like some of them are pretty similar and that it should be possible to reduce the number of topics even further than the automatic topic reduction was able to do.

Below are a few examples of very similar topics.

```
$ cat english_topics_reduced.csv | grep -E 'wait.*long|long.*wait|queue|checkout.*slow'

Topic	Count	Name
18      533     18_wait_long_waiting_too
42      312     42_queue_queuing_queues_checkout
93      129     93_expedition_waiting_long_wait
173     58      173_checkout_checkouts_25_slow
188     53      188_waiting_long_time_consistently
297     35      297_operation_waiting_long_wait
```

Those topics seem to be related to long wait times.

```
$ cat english_topics_reduced.csv | grep -E 'customer.*service|service.*customer'

Topic	Count	Name
24      459     24_customer_customerfriendly_care_service
35      344     35_poor_customer_service_extremely
579     17      579_rude_customerhostile_servicemindness_tyrr
```

Those topics seem to be related to customer service.

```
$ cat english_topics_reduced.csv | grep -E 'cheap|expensive'

Topic	Count	Name
67      180     67_cheap_cheapest_electronics_prices
72      167     72_expensive_budget_too_cheaper
157     70      157_selection_nice_cheapestcheck_enterprising
315     34      315_premium_goods_merchandise_cheap
397     26      397_expensive_soaring_smeared_poor
508     21      508_neronnet_prices_promotions_cheap
780     11      780_sundsvall_expensive_cheap_lacking
```

Those topics seem to be related to pricing.

Is there some mechanism I can use to reduce the topics even further?

My first thought was to use [semi-supervised topic modeling](https://maartengr.github.io/BERTopic/getting_started/supervised/supervised.html) by identifying which documents are in those topics and labeling them accordingly, then retraining the model with those labels. With that approach, I would have to repeat the process for other topics which seems similar. Considering I have around 300.000 documents, that could take some time.

**Comment by leifericf** [comment]
Whoa, cool. I tried to be creative, and it seems like it worked.

I created a recursive function to call `reduce_topics()` recursively:

```python
def auto_reduce_topics(topic_model, docs, topics, probs, iterations=1):
    topics_reduced, probs_reduced = topic_model.reduce_topics(
        docs=docs,
        topics=topics,
        probabilities=probs,
        nr_topics="auto",
    )
    i = 1
    while i < iterations:
        topic_model, topics_reduced, probs_reduced = auto_reduce_topics(
            topic_model, docs, topics_reduced, probs_reduced
        )
        i += 1
    return topic_model, topics_reduced, probs_reduced
```

And then I call it like this:

```python
    # Auto-reduce topics (minimum similarity of 0.915 by default)
    topic_model, topics_reduced, probs_reduced = auto_reduce_topics(
        topic_model, docs, topics, probs, iterations=3
    )
```

It reduces the topics by a lot for each iteration:

```
2022-06-20 14:35:16,981 - BERTopic - Reduced number of topics from 1273 to 817
2022-06-20 14:35:19,602 - BERTopic - Reduced number of topics from 817 to 182
2022-06-20 14:35:20,863 - BERTopic - Reduced number of topics from 182 to 52
```

I'm inspecting the resulting topics now to see if it managed to merge those topics correctly.

**Comment by MaartenGr** [comment]
> Whoa, cool. I tried to be creative, and it seems like it worked, but it might be a dumb approach 🤷

Definitely a creative approach! What you are essentially doing here is running HDBSCAN on the c-TF-IDF matrix multiple times until the topics are merged to whatever value works best for you. 

In practice, however, I think setting a higher `min_topic_size` would benefit you more without the hassle of creating custom functions. Using, for example, `min_topic_size=500` would allow you to develop solid topics without the need to merge them after creation. With 1000 topics, I would imagine many of them are micro topics that are not that interesting for your use case. By setting a high `min_topic_size`, those micro clusters cannot be created.
