### ISSUE TITLE
no bertopic module to be found

### ISSUE THREAD

**Issue by The-Ineffable-Alias** [MaartenGr/BERTopic#579]
i've been dealing with bertopic bugs all day (this, pyaml related, etc) :|. still, amazing tool.
![bertopicissue](https://user-images.githubusercontent.com/82487458/175112718-223d4519-b955-4ee9-807c-446c2b30cdb0.png)

**Comment by MaartenGr** [comment]
Based on your error, it seems that installing BERTopic in your environment did not go as expected. Did you run `!pip install bertopic` in your Google Colab environment? Also, did you make sure to restart the runtime after installing (not hard resetting)?
