### ISSUE TITLE
not able to fit

### ISSUE THREAD

**Issue by The-Ineffable-Alias** [MaartenGr/BERTopic#580]
it's only over 12k tokens but then again i'm quite a noob in linear algebra and even ml
![bertopiclinal](https://user-images.githubusercontent.com/82487458/175169101-4cff6b3c-c8d4-4ff5-9d20-b9c2ddf415d9.png)

**Comment by MaartenGr** [comment]
Could you share how you trained BERTopic? Without it, it is difficult to see what exactly is happening here. Also, how many documents are you passing to BERTopic? In other words, how long is that list of strings?

**Comment by The-Ineffable-Alias** [comment]
i'm passing a column of occupation names. each name turned into a token which in turn becomes a document right? 
my intention was to group the column names by type of occupation. it worked pretty well. thanks!

**Comment by MaartenGr** [comment]
> i'm passing a column of occupation names. each name turned into a token which in turn becomes a document right?

BERTopic typically expects a list of documents directly, it does not convert tokens to documents. As an example, the following `docs`  variable has the structure of what BERTopic expects:

```python
from sklearn.datasets import fetch_20newsgroups
docs = fetch_20newsgroups(subset='all',  remove=('headers', 'footers', 'quotes'))['data']
```

> it worked pretty well. thanks!

Glad to hear that it worked out! If you run into any other issues, please let me know 😄
