### ISSUE TITLE
Failed building wheel for hdbscan even though it is installed already

### ISSUE THREAD

**Issue by Greco1899** [MaartenGr/BERTopic#585]
Hi there!

I'm facing an issue pip installing BERTopic. Error below:
```
C:\Users\<user>\AppData\Local\Temp\pip-build-env-rxyru__v\overlay\Lib\site-packages\Cython\Compiler\Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: C:\Users\<user>\AppData\Local\Temp\pip-install-nrg0t1x_\hdbscan_77911c5f736d4b829b93eb1b4b53ea93\hdbscan\dist_metrics.pxd
        tree = Parsing.p_module(s, pxd, full_module_name)
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for hdbscan
Failed to build hdbscan
ERROR: Could not build wheels for hdbscan, which is required to install pyproject.toml-based projects
```

I already have hdbscan via a precompiled wheel file (as I had issues building the wheel even with Build Tools 2017 installed) but when pip is installing bertopic, it tries to build the wheel again for hdbscan even though it is installed and working.

I've also tried `pip install bertopic --no-cache-dir --no-binary :all:`.
And I checked that I can run `C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x64\\cl.exe`.

OS:
Edition: Windows 10 Enterprise
Version: 20H2
OS build	19042.1766

Steps to replicate:

1. pip install hdbscan via a precompiled wheel file from [Christoph Gohlke](https://www.lfd.uci.edu/~gohlke/pythonlibs/).
2. pip install bertopic

Is there anyway around skipping building the wheel again for hdbscan or point to where it is installed?

**Comment by drob-xx** [comment]
Why do you need to install hdbscan separately? Is the version that you are installing compatible with the version of bertopic you are using?

**Comment by drob-xx** [comment]
Seems like a pip / install issue? You are having trouble getting HDBSCAN installed so you are using a pre-compiled version? When you install bertopic it tries to install HDBSCAN again and you get the error? I'm seeing this on [stackoverlow](https://stackoverflow.com/questions/12759761/pip-force-install-ignoring-dependencies). Someone is recommending:

`pip install {package you want to install} --ignore-installed {installed package you don't want to consider}`

Not sure if this helps.

**Comment by Greco1899** [comment]
Hi @drob-xx. Thanks for the suggestion, the `--ignore-installed` flag didn't help but the [accepted answer](https://stackoverflow.com/a/12759996/13330692) in the stackoverflow link worked perfect for me!

`pip install --no-dependencies bertopic` was what I used and viola.
