### ISSUE TITLE
Bug in visualize_barchart() when using algorithm other than HDBSCAN

### ISSUE THREAD

**Issue by doubianimehdi** [MaartenGr/BERTopic#586]
Hi @MaartenGr , When using an algorithm other than HDBSCAN  , the function visualize_barchart use the sorted function to display the topics in rows and columns but the function uses sorted statement when it shouldn't rendering the order of topic not relevant... could you have a look into it ? Thanks !

**Comment by doubianimehdi** [comment]
in this function def visualize_barchart(topic_model,
                       topics: List[int] = None,
                       top_n_topics: int = 8,
                       n_words: int = 5,
                       width: int = 250,
                       height: int = 250) -> go.Figure:

 # Select topics based on top_n and topics args
    freq_df = topic_model.get_topic_freq()
    freq_df = freq_df.loc[freq_df.Topic != -1, :]
    if topics is not None:
        topics = list(topics)
    elif top_n_topics is not None:
        topics = sorted(freq_df.Topic.to_list()[:top_n_topics])
    else:
        topics = sorted(freq_df.Topic.to_list()[0:6])

If you remove the sorted statement it works ...


For example 

<html>
<body>


Topic | Count | Name
-- | -- | --
10 | 203 | 10_fuel cell_cell en_stack_controller
4 | 198 | 4_gas_connected_hydrogen tank_device
7 | 191 | 7_fuel cell_stack_passage_cathode
16 | 183 | 16_fuel cell_valve_supply_hydrogen
0 | 165 | 0_combustion engine_generator_tank_device
18 | 160 | 18_stack_anode_supply_en fuel


</body>
</html>

BEFORE MODIFICATION : 
![image](https://user-images.githubusercontent.com/33954127/176448069-d126b8b3-a673-493c-8e7b-dda56284ec7a.png)

AFTER MODIFICATION: 
![image](https://user-images.githubusercontent.com/33954127/176448208-838a184c-7e85-4c7a-bb0a-a9ee6f6aa8e0.png)

**Comment by MaartenGr** [comment]
From what I can see, I believe this is not necessarily an issue with the `sorted` function but more with the table that you provided. Typically, after you have trained a BERTopic the resulting topics should be numbered in a decreasing fashion based on their frequency. In other words, topic 0 should be more frequent than topic 10. In your data, however, it seems that topic 10 is actually more frequent than topic 0, which should not be happening. 

It seems that something is happening with how the model was trained. Could you share the code for training BERTopic? Also, did you make any changes to the topics after the model was trained?

**Comment by MaartenGr** [comment]
I just tested it out and I believe it is due to the `nr_topics=50` parameter interacting strangely with the cluster model that you have defined. Fortunately, the solution is very straightforward, simply remove `nr_topics=50` since you already defined the number of topics in your cluster model.
