### ISSUE TITLE
Topic extraction step took too long during training

### ISSUE THREAD

**Issue by localoca5** [MaartenGr/BERTopic#587]
Hi @MaartenGr , 

Thank you for this wonderful repository!

I have an issue that the training took too long and I think it is mainly because of the topic extraction step. 

I have a training set of 2M Chinese news text, and the whole traning process took over 16 hours(and still counting). The topic extraction step(c-tf-idf) alone took over 12hours. Is this normal?

For me, the c-tf-idf topic extraction step seems take a bit too long. It only use 1 CPU of my machine (I use a machine with 4GPUs and 32 CPUs, the cpu usage at topic extraction step is only 100%, I don`t mind it using all my cpus for training).

Below is the log:
Num of training data: 2000000
Batches: 100%|██████████| 62500/62500 [58:28<00:00, 17.81it/s]  
2022-06-29 23:04:12,629 - BERTopic - Transformed documents to Embeddings
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
        - Avoid using `tokenizers` before the fork if possible
        - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
2022-06-30 00:58:06,653 - BERTopic - Reduced dimensionality
2022-06-30 01:51:50,733 - BERTopic - Clustered reduced embeddings

My code is basically as below:
`#file 
import os, sys

#bertopic
from bertopic import BERTopic
from sklearn.feature_extraction.text import CountVectorizer
import jieba
import jieba.posseg as pseg

#cluster algorithms
#I use Kmeans because it doesn`t predict -1 topic for inference
from sklearn.cluster import KMeans

#vecotrizer
#use jieba for Chinese text tokenization
dirname = os.path.dirname(os.path.realpath(sys.argv[0]))
jieba.load_userdict(dirname + "/../data/dict/user_dict.txt")
stopwords = set(line.strip() for line in open(dirname+'/../data/dict/stop_words.txt').readlines())

#filter certain words for topic-words
allow = ['an', 'n', 'nr', 'ns', 'nt', 'nz', 'nrt', 'v', 'vn']

#tokenize and filter out some words
def tokenize_zh(text):
    words = pseg.cut(text)
    res = [w for w,flag in words if w not in stopwords and flag in allow and not w.isdigit() and len(w) > 1]
    return res

vectorizer = CountVectorizer(tokenizer=tokenize_zh, min_df=10)

#cluster model
cluster_model = KMeans(n_clusters=512) 

#load data
docs = []
with open("../data/2M_processed.txt", 'r', encoding='UTF-8') as f:
    for line in f.readlines():
        docs.append(line.strip())
print("Num of training data:", len(docs))

#get few docs for test
#docs = docs[:2000]

#import model
topic_model = BERTopic(embedding_model='distiluse-base-multilingual-cased-v1', verbose=True, vectorizer_model=vectorizer, hdbscan_model=cluster_model, low_memory=True)
topics, probs = topic_model.fit_transform(docs)

#Save model
model_save_path = "my_model_zh_kmeans_512"
topic_model.save(model_save_path)
print("Model saved at:{}".format(model_save_path))`

Could you please give me some hints?

**Comment by MaartenGr** [comment]
> I have a training set of 2M Chinese news text, and the whole traning process took over 16 hours(and still counting). The topic extraction step(c-tf-idf) alone took over 12hours. Is this normal?

No, that typically should not happen as the c-TF-IDF is normally quite fast. Based on your code, my guess would be that is has to do with the following function:

```python
def tokenize_zh(text):
    words = pseg.cut(text)
    res = [w for w,flag in words if w not in stopwords and flag in allow and not w.isdigit() and len(w) > 1]
    return res

vectorizer = CountVectorizer(tokenizer=tokenize_zh, min_df=10)
```

I think that the `tokenize_zh` may be slow since there are quite a number of checks that you are doing there: 
* `w not in stopwords`
* `flag in allow`
* `not w.isdigit()`
* `len(w) > 1`

You can test this out by running `vectorizer.fit(docs)` and see how long that takes. Also, note that the `CountVectorizer` has a `stop_words` argument that you can use instead of `w not in stopwords`. Lastly, I am not familiar with `pseg.cut` but there might also be a potential for a speed up.

**Comment by localoca5** [comment]
> 

Thank you! I found that it is indeed my tokenizer that caused the problem. 

I used `vectorizer.fit(docs)` to test the difference between the `pseg.cut` and the normal 'jieba.cut' on 1000 docs. The pseg one cost 46seconds and  `jieba.cut` cost 5s.

Later on I found that `pseg.cut` will do a POS(part of speed) process besides cutting the text, which is time consuming. 


Here`s my test code:
```python
from sklearn.feature_extraction.text import CountVectorizer
import jieba
import jieba.posseg as pseg
import time
import os, sys

#jieba load stopdict and userdict
dirname = os.path.dirname(os.path.realpath(sys.argv[0]))
jieba.load_userdict(dirname + "/../data/dict/user_dict.txt")
stopwords = set(line.strip() for line in open(dirname+'/../data/dict/stop_words.txt').readlines())
#vecotrizer doesn`t work for Chinese, use jieba
#
#allow = ['an', 'n', 'nr', 'ns', 'nt', 'nz', 'nrt', 'v', 'vn']


#vectorizer
def tokenize_zh(text):
    #pseg
    #words = pseg.cut(text)
    #res = [w for w,flag in words if w not in stopwords and flag in allow and not w.isdigit() and len(w) > 1]
    #normal jieba
    words = jieba.lcut(text)
    res = [w for w in words if not w.isdigit() and w not in stopwords and len(w) > 1]
    return res

vectorizer = CountVectorizer(tokenizer=tokenize_zh, min_df=10)

#load data
docs = []
n = 0
with open("../data/50W_processed.txt", 'r', encoding='UTF-8') as f:
    for line in f.readlines():
        docs.append(line.strip())
        n += 1
        if n > 5000:
            break
print("Fitting {} docs".format(len(docs)))

#time the process
ts = time.time()
vectorizer.fit(docs)
print("Time cost:{}".format(time.time() - ts))
```
I didn`t change 
* `w not in stopwords`
*  `not w.isdigit()` 
*  `len(w) > 1` 
since they are still neccesary in my preprocessing and didn`t cost too much time.

Again, thank you for your suggestion @MaartenGr . It perfectly solved my problem!

**Comment by MaartenGr** [comment]
Glad to hear that it solved your problem! If you run into any other problems, please let me know 😄
