### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by tlerksuthirat** [MaartenGr/BERTopic#589]
I got this error, even though I have installed the Numpy package.

Run on Jupyter notebook
Python version: 3.10.4
numpy version: 1.22.4
<---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Input In [10], in <cell line: 3>()
      1 topic_model = BERTopic()
      2 #fit the model and predict documents-model is generated from 20newsgroup
----> 3 topics, probs = topic_model.fit_transform(doc)

File ~\anaconda3\envs\topic_mod\lib\site-packages\bertopic\_bertopic.py:294, in BERTopic.fit_transform(self, documents, embeddings, y)
    291 if embeddings is None:
    292     self.embedding_model = select_backend(self.embedding_model,
    293                                           language=self.language)
--> 294     embeddings = self._extract_embeddings(documents.Document,
    295                                           method="document",
    296                                           verbose=self.verbose)
    297     logger.info("Transformed documents to Embeddings")
    298 else:

File ~\anaconda3\envs\topic_mod\lib\site-packages\bertopic\_bertopic.py:1362, in BERTopic._extract_embeddings(self, documents, method, verbose)
   1360     embeddings = self.embedding_model.embed_words(documents, verbose)
   1361 elif method == "document":
-> 1362     embeddings = self.embedding_model.embed_documents(documents, verbose)
   1363 else:
   1364     raise ValueError("Wrong method for extracting document/word embeddings. "
   1365                      "Either choose 'word' or 'document' as the method. ")

File ~\anaconda3\envs\topic_mod\lib\site-packages\bertopic\backend\_base.py:69, in BaseEmbedder.embed_documents(self, document, verbose)
     55 def embed_documents(self,
     56                     document: List[str],
     57                     verbose: bool = False) -> np.ndarray:
     58     """ Embed a list of n words into an n-dimensional
     59     matrix of embeddings
     60 
   (...)
     67         that each have an embeddings size of `m`
     68     """
---> 69     return self.embed(document, verbose)

File ~\anaconda3\envs\topic_mod\lib\site-packages\bertopic\backend\_sentencetransformers.py:63, in SentenceTransformerBackend.embed(self, documents, verbose)
     49 def embed(self,
     50           documents: List[str],
     51           verbose: bool = False) -> np.ndarray:
     52     """ Embed a list of n documents/words into an n-dimensional
     53     matrix of embeddings
     54 
   (...)
     61         that each have an embeddings size of `m`
     62     """
---> 63     embeddings = self.embedding_model.encode(documents, show_progress_bar=verbose)
     64     return embeddings

File ~\anaconda3\envs\topic_mod\lib\site-packages\sentence_transformers\SentenceTransformer.py:197, in SentenceTransformer.encode(self, sentences, batch_size, show_progress_bar, output_value, convert_to_numpy, convert_to_tensor, device, normalize_embeddings)
    195     all_embeddings = torch.stack(all_embeddings)
    196 elif convert_to_numpy:
--> 197     all_embeddings = np.asarray([emb.numpy() for emb in all_embeddings])
    199 if input_was_string:
    200     all_embeddings = all_embeddings[0]

File ~\anaconda3\envs\topic_mod\lib\site-packages\sentence_transformers\SentenceTransformer.py:197, in <listcomp>(.0)
    195     all_embeddings = torch.stack(all_embeddings)
    196 elif convert_to_numpy:
--> 197     all_embeddings = np.asarray([emb.numpy() for emb in all_embeddings])
    199 if input_was_string:
    200     all_embeddings = all_embeddings[0]

RuntimeError: Numpy is not available>

**Comment by drob-xx** [comment]
This is a config error in your setup. You can google around for a solution. You might want to check if there is a version mismatch for numpy somewhere. What are your BERTopic model settings?

**Comment by MaartenGr** [comment]
@tlerksuthirat This typically happens if there is something going on with your environment. Typically, one of two things I have found helpful in this case. Either start from an entirely clean environment and re-install NumPy there or upgrade NumPy with `pip install --upgrade numpy`.

**Comment by tlerksuthirat** [comment]
@MaartenGr Thank you very much for the comment. I deleted and recreated a new environment to reinstall BERTopic and reinstall NumPy. I can now analyze the data with BERTopic.
