### ISSUE TITLE
spotting outliers. using probabilities

### ISSUE THREAD

**Issue by The-Ineffable-Alias** [MaartenGr/BERTopic#593]
i've used bertopic to group occupations (of a dataframe column) by type (health, finance, etc). it worked pretty well. (thanks!) particularly taking into account it's a hard use case (nlp for tabular data and only one column). 

now i'd like a way to pick outliers apart in each topic. can i use 'probabilities' for this? do you guys know some tool/library more adequate for this?
 i'm quite new to ml.

**Comment by MaartenGr** [comment]
BERTopic already picks out outliers, that is the -1 topic that you will find when you run `topic_model.get_topic_info()` so there is no need to further pick outliers. However, if you are using other clustering algorithms, such as k-Means, then it highly depends on the clustering algorithm that you are choosing and your definition of what an outlier is in practice. For now, the -1 topic is actually a culmination of all outliers and not actually a topic perse, so you can regard any documents in -1 as outliers.

**Comment by The-Ineffable-Alias** [comment]
yeah i was wondering about a way to pick outliers topic by topic when using kmeans. i think i'll use the outliers given by the default and run bertopic on them alone. i guess i can break it into quite a few topics (it gives me smth bewteen 2000 and 3000 outliers) by increasing nr of components (these outliers are all over the place, it's a rather chaotic dataset overall) and decreasing nr neighbours and nr_topics.  still, really surprised by how well bertopic did on such a messy dataset, specific use case and  with only one column.

**Comment by MaartenGr** [comment]
With k-Means there are other tricks you can do, like finding the points in a cluster that are furthest from the center. I would advise increasing the number of topics by reducing `min_topic_size` as that directly relates to the number of topics, whilst increasing `nr_components` makes it more difficult for the clustering algorithm to properly find clusters.

**Comment by MaartenGr** [comment]
Due to inactivity, I'll be closing this for now. Let me know if you have any other questions related to this and I'll make sure to re-open the issue!
