### ISSUE TITLE
Full document semantic search

### ISSUE THREAD

**Issue by eamonndunne** [MaartenGr/BERTopic#604]
First, thank you for this project, it is really great.

I have a use case where in addition to the topic modelling, I want to provide semantic search over all the documents used to perform clustering. I have an existing instance of faiss where I'm also storing the embeddings that are passed to fit_transform and a set of unique identifiers from the embeddings (postgres) database.

I've overridden fit_transform to store these external ids in the `documents` data frame so `documents.T` maps the external ids to each document. Am I correct in understanding some sort of probability or distance can also be retrieved to communicate just how close a match a document was to a specific topic? If so, any help would be greatly appreciated, thank you.

**Comment by MaartenGr** [comment]
Yes, whenever you run the following:

```python
from bertopic import BERTopic
from sklearn.datasets import fetch_20newsgroups

docs = fetch_20newsgroups(subset='all',  remove=('headers', 'footers', 'quotes'))['data']

topic_model = BERTopic()
topics, probs = topic_model.fit_transform(docs)
```

The `probs` variable represents the probability that a document belongs to a specific topic. I believe you could use that to communicate how close the document is to its topic. If you want to extend that to the probability of a document belonging to *any* topic, then you would have to set `calculate_probabilities=True` in order for the document-topic probability matrix to be calculated. If you set that parameter, then the `probs` will then be the document-topic probability matrix.

**Comment by eamonndunne** [comment]
Great, thank you :+1:
