### ISSUE TITLE
Topic Representation

### ISSUE THREAD

**Issue by AIRobotZhang** [MaartenGr/BERTopic#606]
What is the API for each topic representation?

**Comment by MaartenGr** [comment]
To get the topic representation of a single topic, you could run `topic_model.get_topic(my_topic_ID)` or you could run `topic_model.get_topic_info()` to get a full overview.

**Comment by MaartenGr** [comment]
Ah right, BERTopic works by generating c-TF-IDF representations of the topic. So the main vector representation that you have of these topics can be accessed through `topic_model.c_tf_idf`. That is a sparse matrix where the columns are the words in `topic_model.vectorizer_model.get_feature_names()`. Although it is possible to access the embedding vector of topics, these are merely rough representations based on a weighted average of topic words. You can access these with `topic_model.topic_embeddings` if you have set an embedding model.
