### ISSUE TITLE
Cannot import bertopic though the package is installed but present in site packages and not in conda env bin location

### ISSUE THREAD

**Issue by KumudaBG** [MaartenGr/BERTopic#608]
Hi @MaartenGr , Thank you for an amazing solution to perform topic modeling. 

I have created a new conda environment with Python 3.7.12, installed hdbscan and bertopic with the commands 'conda install -c conda-forge hdbscan' and 'pip install --no-dependencies bertopic[gensim]' respectively.

I see the bertopic package is in python3.7 sit packages.
But the python file (which tries to import bertopic) throws an error saying cannot import bertopic.

Could you please help me on this

**Comment by MaartenGr** [comment]
I am not entirely sure what is happening here but it sounds like an issue with the environment that you are currently working in. I would advise starting a completely new environment and using `pip install bertopic[gensim]` instead there. Do note that the `--no-dependencies` flag also ignores all other dependencies that BERTopic relies, not just HDBSCAN.

**Comment by KumudaBG** [comment]
I tried your approach in two steps :
1. conda create --name topic python
2. source activate topic

but facing ERROR: Failed building wheel for hdbscan
<img width="850" alt="Screen Shot 2022-07-11 at 1 29 40 PM" src="https://user-images.githubusercontent.com/71955355/178353086-265ad32c-e1c3-488a-8779-77bff081a2e6.png">


Also tried this [approach](https://github.com/MaartenGr/BERTopic/issues/392#issuecomment-1006333143)  :
1.  conda create --name topic python
2.  steps mentioned in the link 

-     python -m pip install --upgrade pip setuptools wheel
-     python -m pip install bertopic --no-cache-dir
-     python -m pip uninstall hdbscan -y
-     python -m pip install hdbscan --no-cache-dir --no-binary :all: --no-build-isolation
Bertopic installation successful
<img width="853" alt="Screen Shot 2022-07-11 at 1 40 00 PM" src="https://user-images.githubusercontent.com/71955355/178354289-6ef51750-4d50-42b1-97f8-fc276a5b7898.png">

But the Import error still appears when the file accessing bertopic is executed
<img width="860" alt="Screen Shot 2022-07-11 at 1 42 18 PM" src="https://user-images.githubusercontent.com/71955355/178354749-a0c23e2a-bca0-472b-9cb9-bf533cb70c7b.png">

**Comment by KumudaBG** [comment]
Also I tried with python 3.7. i.e.

1. conda create --name pyt37 python=3.7
2. source activate pyt37
3. pip install bertopic[gensim] and got a error that the specified packages are missing 
<img width="832" alt="Screen Shot 2022-07-11 at 2 23 12 PM" src="https://user-images.githubusercontent.com/71955355/178360843-3a435b66-fbdc-4911-94a6-a21d5ddbd320.png">

On manually installing them and again using the command `pip install altair==3.2.0 astor blinker blis==0.2.4 jsonschema==3.0.1 preshed==2.0.1 spacy==2.1.4 srsly==0.0.7 thinc==7.0.4 numexpr numpy==1.19.2 typing-extensions==3.7.4`

And then running the step 3, got this error. 
<img width="832" alt="Screen Shot 2022-07-11 at 2 28 28 PM" src="https://user-images.githubusercontent.com/71955355/178361755-848cdd8b-6b84-4a45-85fd-3cbaf529a2b9.png">

Looks like its in deadloack state due to numpy and typing-extensions version conflict 

I appreciate if you can suggest me a solution to fix this error

**Comment by MaartenGr** [comment]
> But it throws ModuleNotFoundError: No module named 'bertopic'

I am not entirely sure but it seems there is something strange going on with your conda environment. Could you try to see if it is due to problems with python pathing, as mentioned [here](https://stackoverflow.com/a/55754384/10532563)? 

Also, if the issue is indeed conda, then perhaps using poetry or virtualenv might solve your issue. 

> Looks like its in deadloack state due to numpy and typing-extensions version conflict

That is because you did the pip install with `numpy==1.19.2` and the minimum supported version of numpy in BERTopic is 1.20. Also, the other pip installs are rather strict and relaxing them might prevent the conflicts.

**Comment by KumudaBG** [comment]
You are right. numpy==1.19.2 and other strict version specification in the package names was the issue in conda env=3.7.
Thank you for patiently answering my questions.

**Comment by KumudaBG** [comment]
Issue solved, hence closing this
