### ISSUE TITLE
AttributeError: 'BERTopic' object has no attribute 'diversity'

### ISSUE THREAD

**Issue by SankulR** [MaartenGr/BERTopic#609]
Hello MaartenGr,
I am facing this error while trying to build a topics_over_time visualisation from an already saved BERTopic model.
I was able to do a transform and get the topics successfully but, while trying to visualise it the error pops up. Last time I had seen this error and posted it on git, it was due to me trying to retrain the existing model which was not possible, but now even with trying to visualise topics over time I am facing same error. I have also attached a snap of the code block for a better understanding. Looking forward for your response
![Screenshot 2022-07-11 at 15 18 34](https://user-images.githubusercontent.com/26628198/178273285-dfa1c968-b3dd-46f2-b427-b5be5c8502c7.png)
.

**Comment by MaartenGr** [comment]
Strange..., if the BERTopic model was fitted, then it should have the `diversity` parameter. Which BERTopic version are you currently using? Did you make sure that the environment in which you saved the model is exactly the same as the environment in which you loaded the model? Also, could you share the code for loading the model?

**Comment by SankulR** [comment]
I am current using the bertopic version 0.9.4 and that's the one I used for training also the training environment is preserved and the same is being used. here is the line of code I used to load the models.
model = BERTopic.load(DATA_PATH+"model/ReducedTopicModel")

**Comment by SankulR** [comment]
surprisingly it works but need to check a bit of data since I am getting the frequency of all topics to be 1 throughout
