### ISSUE TITLE
Update conda-forge package to v0.11.0

### ISSUE THREAD

**Issue by leifericf** [MaartenGr/BERTopic#610]
People who use Conda to manage their projects might experience complex dependency-related issues when installing BERTopic via pip within their Conda environment, especially on M1 Macs.

Please update the conda-forge package to v0.11.0 to enable smoother installation via Conda.

**Comment by leifericf** [comment]
Perhaps it would be possible to automate the process of updating conda-forge for future releases?

**Comment by MaartenGr** [comment]
The issues were fixed and the v0.11 version should be available in conda. I'll make sure to make this more of a priority when releasing a new version. I can imagine it to be frustrating not being able to work with the new version simply because the conda version was behind.
