### ISSUE TITLE
classification

### ISSUE THREAD

**Issue by The-Ineffable-Alias** [MaartenGr/BERTopic#612]
i've used BERTopic to cluster occupations (the results are awesome taking into account the poor context and the messiness of the dataset) and now i want to classify them by area (eg: business and management or arts and culture). i'm using only a SET of roughly 20k tokens (around 2 to 4 words each) taken from a column (i'm using all its unique values). 

what algorithms would you suggest? maybe something i can find on hugging face? i'm a beginner in deep learning so i'd prefer something (relatively) simple to use and explain to my colleagues (who, like me, are somewhat comfortable with ml). 
i'm interested in knowing about advanced options too though. feel free to let me know about them (even though i may not use them right now).

**Comment by MaartenGr** [comment]
Glad to hear that BERTopic is working well for you! Out-of-the-box, BERTopic is rather straightforward. Turn documents into vector representations with an embedding model, reduce their dimensionality with UMAP, cluster with HDBSCAN, and extract the representations with c-TF-IDF. 

There are, of course, some optimization here and there and some nuances to all of this but the basic principle should be relatively straightforward to communicate. I think the visualization [here](https://maartengr.github.io/BERTopic/algorithm/algorithm.html) should help a bit. 

With respect to the underlying algorithms, the default embedding model already works quite well. It is the `all-MiniLM-L6-v2` SentenceTransformer model which is trained for semantic similarity purposes. In other words, it is trained such that you can easily find which documents are similar to one another. There are many variations out there for this purpose but I have found that the `all-mpnet-base-v2` model performs incredibly well. 

After selecting the embedding model, you can dive into the parameters for UMAP and HDBSCAN, use variations of BERTopic such as dynamic topic modeling, and even do some manual merging and labeling of topics. This can be quite a lot, so I would advise going through the documentation [here](https://maartengr.github.io/BERTopic/getting_started/quickstart/quickstart.html). I did my best to make it as clear as possible but there is a good chance not everything is as clear as I want it to be. In those cases, feel free to ask any questions here or on the discussion page!

**Comment by The-Ineffable-Alias** [comment]
oh yeah BERTopic is being pretty accessible even to me ( a noob). 
now i was rather thinking about the next phase - classification. any algorithms you found to work particularly well after the (BER)topic modeling?

**Comment by The-Ineffable-Alias** [comment]
yeah i think this question is better suited for the discussions. i'll post there this kind of question next time

**Comment by MaartenGr** [comment]
That's fine, no worries! With respect to the classification, that is something typically handled with the `transform` function in BERTopic. However, you could try to replicate the underlying algorithms with a classification algorithm. I have not tried it out myself extensively, so I cannot yet be much of help here.
