### ISSUE TITLE
Locating to the original sentence of the resulting words?

### ISSUE THREAD

**Issue by wang2hhhhh** [MaartenGr/BERTopic#613]
Hi, I have been using BERTopic and my clients are trying to define medical terms from patient testimonies so they want to know more context when reading the results, because in most of the cases they need the context of patients' words to know exactly what the words really mean (as they really need that certainty when defining terms). I tried n-grams only (so n_gram_range = (4,4) as an example) but the results are not as good as the unigram ones. 
So ideally, after fitting the model, I want to get access to the original document and sentence to show them a couple words before and after the selected word in the document, thus I'm wondering, is there a current way to do so? Or I would be happy to have a few pointers on how you think this can be achieved modifying the current code. 
And if there is any other better way to solve my root problem, I'd be happy to learn about, thanks!

**Comment by MaartenGr** [comment]
Although that is not something currently supported in BERTopic, you could take the words in a topic and search them throughout the documents that belong to that topic. You could either search for the words using a for loop or make use of the CountVectorizer to find the documents that contain the words more easily. For something a little bit more advanced, you can also calculate a [co-occurrence matrix](https://stackoverflow.com/questions/35562789/how-do-i-calculate-a-word-word-co-occurrence-matrix-with-sklearn).

**Comment by wang2hhhhh** [comment]
Thanks for the reply, if you could point out the way to find all documents for a topic/class, it'll save me some time

**Comment by MaartenGr** [comment]
@wang2hhhhh When you run the following `topics, probs = topic_model.fit_transform(docs)`, then each topic in `topics` belongs to a document in `docs`. The order is kept, which means that `topics[0]` is the topic for `docs[0]`, `topics[1]` for `docs[1]`, etc.
