### ISSUE TITLE
How remove stopwords?

### ISSUE THREAD

**Issue by fmafelipe** [MaartenGr/BERTopic#614]
Is there a way or a parameter to specify the stopwords that you don't want to have to get the results?
Many of the words in the topics that the model shows in the results are stopwords.
Thanks.

**Comment by drob-xx** [comment]
You can specify stop_words as a parameter to CountVectorizer:

> from bertopic import BERTopic
> from sklearn.feature_extraction.text import CountVectorizer
> 
> vectorizer_model = CountVectorizer(stop_words="english")
> topic_model = BERTopic(vectorizer_model=vectorizer_model)
> 

You can add your own stop words to the list - see [CountVectorizer](https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html) doco for details.
