### ISSUE TITLE
Can we predict multiple possible topics with transform function?

### ISSUE THREAD

**Issue by NShweta19** [MaartenGr/BERTopic#616]

**Comment by MaartenGr** [comment]
That depends on your use case. If, for example, you have longer documents containing multiple sentences then you can split them up and feed them separately to BERTopic. As a result, each will get their own topic and the documents of which they were part of would then have multiple topics. In other words, it helps splitting up the data in sentences or paragraphs such that we can use the transform function to generate multiple topics for a single document. Moreover, by setting `calculate_probabilities=True` you can get a topic-document probability matrix that gives a bit more information about the potential of multiple topics in a document.

**Comment by MaartenGr** [comment]
Due to inactivity, I'll be closing this for now. Let me know if you have any other questions related to this and I'll make sure to re-open the issue!
