### ISSUE TITLE
Possible to identify documents with stronger association to multiple topics?

### ISSUE THREAD

**Issue by Minyall** [MaartenGr/BERTopic#618]
We already have the heatmap which shows us general topic similarity, but is it possible to surface representative documents that might span both those topics? This would be useful to show how it is possible for two topics to be similar. In the past we've done work using NMF where we focussed specifically on documents that had weaker but still significant associations with multiple topics. Obviously with the clustering approach being used here the idea is to ideally find the tight clusters, but I still wondered if it might be possible.

I figured perhaps working with the `probabilities` would be the best route to go, but I've not managed to find something particularly useful thus far. My code that I've been toying with...

```
probs = pd.DataFrame(probabilities)
probs['doc_id'] = probs.index
filtered_probs = probs.melt(id_vars='doc_id',var_name='topic',value_name='probability')
fig = sns.clustermap(filtered_probs.pivot(index='doc_id',columns='topic',values='probability'))
```
![cluster_grid](https://user-images.githubusercontent.com/14132122/179225042-1de337b6-8cc7-4197-aa0f-28f385b6683a.png)

You can see the very clear clusters of documents that primarily make up the topics, but near the bottom we have the mushy area where it seems like there might be documents with weaker probabilities that might have a greater variety of latent topics.

Any thoughts on the best approach? In a sense a `.get_representative_docs` but with the option to specify more than one topic.

**Comment by MaartenGr** [comment]
Interesting, there is definitely something to say for such a representation. I am right to assume that the `probabilities` that you are using are generated through `calculate_probabilities=True`? 

There is something similar that can be used to have an idea of the potential hierarchy and multitude of topics across a document and that is the recently released `.hierarchical_topics()` function together with `.visualize_hierarchical_documents`. It does not allow for the exact same representation, as the probabilities are not used but it does give a general idea of the potential overlap.

**Comment by MaartenGr** [comment]
Due to inactivity, I'll be closing this for now. Let me know if you have any other questions related to this and I'll make sure to re-open the issue!
