### ISSUE TITLE
AttributeError: 'BERTopic' object has no attribute 'custom_labels'

### ISSUE THREAD

**Issue by AlexisV-hub** [MaartenGr/BERTopic#619]
Hi,

I was trying to manually set topics names by using :

loaded_sw_model_30.set_topic_labels({0: "Delivery"})

![image](https://user-images.githubusercontent.com/81055769/179251815-6ee2a39b-ee63-4c4a-a100-b9acd811a36c.png)

Thanks for your help,

Alexis

**Comment by MaartenGr** [comment]
Seeing as the name of our topic model is `loaded_sw_model_30`, I am assuming that it is an old model that you loaded in. If that is correct, then it might be the case that you are using an older version of BERTopic that does not have the `set_topic_labels` yet. For that, you will need the newest release, v0.11. However, there is a good chance you will have to re-train your model with the newest version as BERTopic does not support loading between versions.
