### ISSUE TITLE
AttributeError: 'BERTopic' object has no attribute 'get_most_relevant_documents'

### ISSUE THREAD

**Issue by Yukelingtay** [MaartenGr/BERTopic#624]
hello, I was wondering if 'get_most_relevant_documents' is still valid? thanks!

**Comment by MaartenGr** [comment]
From the top of my head, `.get_most_relevant_documents` has never actually been a function within BERTopic. I believe you are referring to `.get_representative_docs()` which indeed should still be working if you are using an HDBSCAN model.

**Comment by Yukelingtay** [comment]
Ah I see, yes .get_representative_docs() works! Thanks Maarten!

**Comment by MaartenGr** [comment]
No problem, glad I could help out :)
