### ISSUE TITLE
Memory error with ~1m documents (no GPU available, low_memory=True)

### ISSUE THREAD

**Issue by Rorickt** [MaartenGr/BERTopic#625]
Hi!

First, Thank you for the library, I'm really enjoying working with it!

I am working with documents that are multiple sentences. I split them up and work with each sentence. Afterward I (plan to) merge them back to end up with multiple topics per document.

However, after I split my data I have around a million sentences and this seems to crash the kernel when using `fit_transform()`.
I get the error of not being able to allocate enough memory when doing topic reduction through umap. When I set that to `low_memory = True`, I get the same error. It uses up all 32gb of ram that I have available. I have `calculate_probabilities = False`

Should I just accept the limitations of my system and work with a smaller (randomized) subset of my full data to reduce the load? 
Or are them some tricks I can still apply?

**Comment by MaartenGr** [comment]
Thank you for your kind words!

Scalability can definitely be an issue when handling a million documents. Specifically for that reason, I created an [FAQ](https://maartengr.github.io/BERTopic/faq.html#i-am-facing-memory-issues-help) page that has a bunch of tricks that can help you out with that! Hopefully, these should suffice in making it possible to train your model. 

There are a few other tricks that you can do that might be a bit more advanced:
* `fit` on a smaller portion of the data and `transform` on the rest
* Use another dimensionality reduction algorithm like PCA or another clustering algorithm like k-Means
* Use GPU-accelerated UMAP and HDBSCAN (see [this page](https://maartengr.github.io/BERTopic/getting_started/tips_and_tricks/tips_and_tricks.html#gpu-acceleration))
* Speed up UMAP with PCA-initialization (see [this page](https://maartengr.github.io/BERTopic/getting_started/tips_and_tricks/tips_and_tricks.html#speed-up-umap))

**Comment by MaartenGr** [comment]
No problem! Please feel free to post any questions or concerns you have even if they might already be mentioned somewhere else. It might happen that your use case is different and it would be a shame that a simple fix would be overlooked because of that 😄
