### ISSUE TITLE
inconsistency about outlier class in reduce_topics()

### ISSUE THREAD

**Issue by dopc** [MaartenGr/BERTopic#63]
Hey, thanks for this great work.

The `reduce_topics()` mixes the topic with the biggest id and outlier class which has -1 class id. That happens because of the `_map_probabilities()` method. When the outlier topic determined for `from_topic` or `to_topic` variables, the method modifies the last element of the `probabilities` array which is not outlier class's probability, since outlier class's probability does not exist in the `probability` array.

**Comment by MaartenGr** [comment]
Ah, I see... I had not anticipated that the probabilities did not include the -1 class which messes up mapping the probabilities. So if I am correct, `reduce_topics()` does correctly reduce the topics but fails to map the corresponding probabilities, right? Then, it would be a simple matter of simply not allowing the probabilities of the outlier class to be mapped in `_map_probabilities()`.

**Comment by dopc** [comment]
Yeah, that's right.

Actually, not allowing for the outlier class would not be the correct solution. I have thought that, appending `1-sum(others)` for the outlier class would be a solution if we want to use the probability of outlier class. Below is my trial.

```python
def _append_outlier(probabilities):
     return np.array([np.append(probs, 1 - sum(probs)) for probs in probabilities])
```

**Comment by MaartenGr** [comment]
Great, I will most likely not allow for the outlier class to have a probability due to the nature of the class. That way I can follow the reasoning in the HDBSCAN package for allowing an outlier probability since it is merely a collection of undefined classes.

**Comment by dopc** [comment]
Fair enough.
