### ISSUE TITLE
Merge words in topic representation

### ISSUE THREAD

**Issue by xiangzheng2021** [MaartenGr/BERTopic#631]
Hi developers,

Thank you for your outstanding work. When I was examining the bar chart visualization of the generated topics, I noticed that some words in the representation are actually the same word, like "lab" and "labs", "bio" and "biology." My questions are as follows.

- Is there a convenient way to specify the words to be merged and update the visualization?
- If I have to update it manually, should I sum up the TF-IDF scores of the merged words as the new TF-IDF score?
- How to draw new words and their TF-IDF scores to fill up the blank left by the merged words? I saw the get_topic() method only returns at most 10 words.

**Comment by MaartenGr** [comment]
Thank you for your kind words!

Typically, if words are very similar to one another, then it would help to set the `diversity` parameter when training BERTopic. It is a value between 0 and 1. The higher you set this value, the more diverse the words will be in the same representation. For example, words like "lab" and "labs" are very similar and typically only one will then be used if you have set a higher diversity. It helps to start this off at around 0.2 to get a feeling of its effect. 

> Is there a convenient way to specify the words to be merged and update the visualization?

You might be able to do it as follows:

```python
topic_model.diversity = 0.2
topic_model.update_topics(docs, topics)
```

That way, the topic representations get re-calculated although this time with the updated diversity parameter. 

> If I have to update it manually, should I sum up the TF-IDF scores of the merged words as the new TF-IDF score?

If you were to do it manually, then that depends on your assumptions of merging them. The diversity metric does not merge them and only looks at them as separate, independent instances. 

> How to draw new words and their TF-IDF scores to fill up the blank left by the merged words? I saw the get_topic() method only returns at most 10 words.

This becomes rather tricky as you would have to update the bag of words first and remove those words from its vocabulary. What you could do is find all duplicate words and add them to the `stop_words` in a custom `CountVectorizer` model which you can then pass to `.update_topics`.

**Comment by MaartenGr** [comment]
Glad to hear that that solution also works for you! The `CountVectorizer` definitely is a great method to further process the documents and get the topic representations that you are looking for. If you have any other questions and/or suggestions, please let me know :)
