### ISSUE TITLE
reduce_topics() changes probabilities in-place manner

### ISSUE THREAD

**Issue by dopc** [MaartenGr/BERTopic#64]
When we use the method `reduce_topics()` it mutates the given `probabilities` parameter and it becomes identical with the returned probabilities. It would be better if it does not mutate the given one and 2 different probabilities for before and after.

**Comment by MaartenGr** [comment]
Nice find! I'll make sure to not mutate `probabilities` and instead return a separate variable instead. You will most likely find the fix in the next major release (#60).

**Comment by dopc** [comment]
Thank you.
