### ISSUE TITLE
problem with loading the model in google colab

### ISSUE THREAD

**Issue by mhdr-hami** [MaartenGr/BERTopic#642]
Hii, I too have a problem with loading the model. I hope you could help me.
I am using google colab, and this is my code.

`from bertopic import BERTopic `

`model = BERTopic.load("/content/drive/MyDrive/myModels/lds2")`

clearly the path, is the path I saved my model.

I get this Error:
Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.

Thanks for helping me.

**Comment by MaartenGr** [comment]
This happens when you save the model in a GPU-accelerated instance but load it in an environment without a GPU. In other words, make sure that you keep the environments the same when loading and saving the model.

**Comment by mhdr-hami** [comment]
Thanks!
