### ISSUE TITLE
cuML: AttributeError: predict

### ISSUE THREAD

**Issue by pepi99** [MaartenGr/BERTopic#647]
I train a model in the following way: 

```
hf_model = pipeline("feature-extraction", model="distilbert-base-cased", device=0)
embedding_model = HFTransformerBackend(hf_model)

umap_model = UMAP(n_components=5, n_neighbors=15, min_dist=0.0)
hdbscan_model = HDBSCAN(min_samples=10, gen_min_span_tree=True)

topic_model = BERTopic(nr_topics=15, n_gram_range=(1, 3), verbose=True,
        embedding_model=embedding_model,
        umap_model=umap_model,
        hdbscan_model=hdbscan_model)

```

In another folder, I do: 

```
topic_model = BERTopic.load("cache/crypto_model_full_gpu")
topics, probs = topic_model.transform(docs) # Docs is a list of strings

```

I get an error: 
Traceback (most recent call last):
  File "pretrained_bertopic.py", line 69, in <module>
    topics, probs = topic_model.transform(docs)
  File "/home/ubuntu/miniconda3/envs/rapids-22.06/lib/python3.8/site-packages/bertopic/_bertopic.py", line 404, in transform
    predictions = self.hdbscan_model.predict(umap_embeddings)
  File "cuml/common/base.pyx", line 269, in cuml.common.base.Base.__getattr__
AttributeError: predict

**Comment by beckernick** [comment]
cuML's hdbscan does not yet support `approximate_predict`, so you won't be able to use it with unseen documents for now. In the meantime, you should still be able to use UMAP from cuML and attain a substantial speedup, as UMAP is often the largest bottleneck on medium-to-large datasets.

**Comment by pepi99** [comment]
YES! That worked with relatively the same speed as if I used HDBMAP and UMAP both on GPU! Thanks!

**Comment by rubypnchl** [comment]
Hi,
I am working with BERTopic and have to apply millions of abstracts. I have to keep calculate_probabilities=True for further analysis tasks. To speedup the process, I have installed cuML using rapids on wsl2 after so many errors and trials. I want to ask if is there any way to simply install cuML on windows without using WSL.
