### ISSUE TITLE
question about how to prepare the data

### ISSUE THREAD

**Issue by 652994331** [MaartenGr/BERTopic#652]
hi, nice work, it's really good. when I was using bertopic, I was wondering how did u guys prepare your data? I checked the fetch20_all dataset, I found the data do not look very clear. to my understanding, each row is a sample, which is a doc.However there  are a lot empty rows in the data, do we have 1 or 2 empty rows between the doc? thank you
<img width="474" alt="Screen Shot 2022-08-02 at 19 01 44" src="https://user-images.githubusercontent.com/51428350/182359441-2c2073c9-3d21-435b-95e2-7311bd4b4ddb.png">

**Comment by MaartenGr** [comment]
Typically, the 20NewsGroups data imported from scikit-learn is used for demonstration purposes and indeed is seldom processed in these examples. As a result, these empty documents get aggregated into a single topic thereby showing what would happen if you take an unprocessed dataset and apply BERTopic. However, you can safely remove those empty documents as they do not contribute to the resulting topic representations.

**Comment by 652994331** [comment]
@MaartenGr thanks for your help. problem solved
