### ISSUE TITLE
Solved: load() in BERTopic 0.11.0 Can't Be Called

### ISSUE THREAD

**Issue by NanachiHub** [MaartenGr/BERTopic#654]
The latest BERTopic seems to require numba to be 0.56.0.
<img width="980" alt="image" src="https://user-images.githubusercontent.com/70123136/182540609-dec4fa41-2ad9-4f1f-b075-6f0dc8766d7e.png">
However, numba >= 0.52.0 has removed attribute '_rebuild_function' on module 'numba.core.serialize'. I think the attribute is  somehow called by BERTopic.load().
<img width="872" alt="image" src="https://user-images.githubusercontent.com/70123136/182542181-52782896-6428-44fe-a757-ecee6c49a997.png">
<img width="868" alt="image" src="https://user-images.githubusercontent.com/70123136/182542240-80821a7d-ecd0-413c-88a3-b64b628447b0.png">

Similar issue was recognized in https://github.com/MaartenGr/BERTopic/issues/266. It was then considered as an issue with tensorflow. I'm not sure if it is exactly caused by the problem I mentioned since I'm not familiar with numba.

**Update:**
It's the model I saved on 24 July that cannot be loaded. I remember I successfully loaded it once but now I can't. I trained a new model today and it can be normally saved and loaded. Idk why this happened. But since it worked again, there seems to be no need for me to investigate the issue anymore.

**Comment by MaartenGr** [comment]
Glad to hear that the issue was solved. Most likely, you used a different version of numba between saving and loading the model since numba 0.56.0 was released after 24 July.
