### ISSUE TITLE
Incrementally training on the new corpus

### ISSUE THREAD

**Issue by yanfan0531** [MaartenGr/BERTopic#655]
Hi!

I have a quick question. Is there a method like lda.update(other_corpus) in gensim, to update the model by incrementally training on the new corpus.

I found the following method:
`update_topics(self, docs, topics, n_gram_range=None, vectorizer_model=None)
`
But it seems like to update topic representations on existing topics, instead of using new corpus to discover new topics. Correct me if I miss something obvious, thanks!

**Comment by MaartenGr** [comment]
That is currently not possible in BERTopic due to the underlying algorithms that do not allow for finding new topics after an initial fitting. Having said that, I may or may not already be working on something similar 😄

**Comment by yanfan0531** [comment]
I see, hope we will be able to use new features you're working on soon. Thanks for your amazing work and answering all these questions to maintain this repo :-)
