### ISSUE TITLE
Is BERTopic able to detect new topics?

### ISSUE THREAD

**Issue by Thiziri-Hafir** [MaartenGr/BERTopic#656]
Hello Maarten, first of all thank you for the time you take to answer my questions.
I was wondering about Bertopic's lack of ability to detect new topics (new clusters). 
When the document is about a different topic from the previous ones, Will BERTopic try to classify the document in existing topics or will it classify it in a new class? Thank you

**Comment by MaartenGr** [comment]
No, after having trained a model and finding a set of topics, it will only classify documents to that existing set of topics and will not create any new topics. Having said that, I may or may not be working on something that will support that in the future 😄

**Comment by MaartenGr** [comment]
You can now use [incremental and online topic modeling](https://maartengr.github.io/BERTopic/getting_started/online/online.html) with BERTopic. This should allow you to detect new topics if you are using river.

**Comment by Mhdi-kr** [comment]
Hi Maarten, can we achieve this using representational components in 2025? @MaartenGr

**Comment by MaartenGr** [comment]
@Mhdi-kr You can only do that with representation models if you have all the documents since you currently need those to generate the updated representations. Typically, you do that with `.update_topics`
