### ISSUE TITLE
.visualize_hierarchy() not showing different cluster colors

### ISSUE THREAD

**Issue by ttu-hq** [MaartenGr/BERTopic#657]
Hi Maarten,

I've been using BERTopic for a while and it's an amazing resource! Thank you for all your hard work. I'm wondering if you can help me with an apparent issue I'm seeing:

After updating to the latest version of BERTopic, I'm finding that the .visualize_hierarchy() function is not showing different cluster colors as it used to. I've checked my plotly installation and it's a supported version. Color_threshold is set to default. Not sure what I'm doing wrong. I've attached the PNG of the plot. Any suggestions/advice are greatly appreciated!

<img width="392" alt="newplot" src="https://user-images.githubusercontent.com/110555095/182661390-2c716d13-6390-4933-b00a-17d60c630cda.png">

**Comment by MaartenGr** [comment]
It might be worthwhile to play around with the different values for `color_threshold`. As a default, it is set to 1, so perhaps setting it to 0.5 or 2 changes the results.

**Comment by MaartenGr** [comment]
Due to inactivity, I'll be closing this for now. Let me know if you have any other questions related to this and I'll make sure to re-open the issue!
