### ISSUE TITLE
AttributeError: 'BERTopic' object has no attribute 'topics_over_time'

### ISSUE THREAD

**Issue by nadiafelix** [MaartenGr/BERTopic#66]
AttributeError: 'BERTopic' object has no attribute 'topics_over_time'

**Comment by MaartenGr** [comment]
Although I need more information than this error message, like what code did you run, it does seem you are trying to use the DTM feature that is coming up in v0.6. If you are trying out the pull request, how did you install BERTopic and what code did you run exactly?

**Comment by nadiafelix** [comment]
The code is this:

import re
import pandas as pd
from bertopic import BERTopic

# Prepare data
trump = pd.read_csv('https://drive.google.com/uc?export=download&id=1xRKHaP-QwACMydlDnyFPEaFdtskJuBa6')
trump.text = trump.apply(lambda row: re.sub(r"http\S+", "", row.text).lower(), 1)
trump.text = trump.apply(lambda row: " ".join(filter(lambda x:x[0]!="@", row.text.split())), 1)
trump.text = trump.apply(lambda row: " ".join(re.sub("[^a-zA-Z]+", " ", row.text).split()), 1)
trump = trump.loc[(trump.isRetweet == "f") & (trump.text != ""), :]
timestamps = trump.date.to_list()
tweets = trump.text.to_list()

# Create global topics
model = BERTopic(verbose=True)
topics, _ = model.fit_transform(tweets)

# Topics over time (DTM)
topics_over_time = model.topics_over_time(tweets, topics, timestamps)

# Visualize DTM
model.visualize_topics_over_time(topics_over_time, topcs=[9, 10, 72, 83, 87, 91])

**Comment by MaartenGr** [comment]
This works for me in BERTopic v0.6. Which version of BERTopic are you currently using?

**Comment by nadiafelix** [comment]
This is the problem, I am using the default ===> bertopic-0.5.0. I will test in v0.6
Thank you!

**Comment by nadiafelix** [comment]
By pip we have this error when i have install
!pip install 'bertopic[all]==0.6'

ERROR: Could not find a version that satisfies the requirement bertopic[all]==0.6 (from versions: 0.0.1, 0.1.0, 0.1.1, 0.1.2, 0.2.0, 0.2.1, 0.2.2, 0.2.3, 0.3.0, 0.3.1, 0.3.2, 0.3.3, 0.3.4, 0.4.0, 0.4.1, 0.4.2, 0.4.3, 0.5.0)
ERROR: No matching distribution found for bertopic[all]==0.6

**Comment by MaartenGr** [comment]
That is expected! Although I just merged the pull request that does not mean that pypi is updated. Make sure that when you try to use code from a pull request, you also install it via the branch corresponding to that request. 

Here, that would mean installing it as follows:
```
pip install git+https://github.com/MaartenGr/BERTopic.git@v0.6#egg=bertopic[all]
```

You are in luck as I will push master to PyPi in the coming days.

**Comment by nadiafelix** [comment]
The version that come with this code is 0.5.0. Look the figure:

![image](https://user-images.githubusercontent.com/9355554/109515599-056a7000-7a86-11eb-90d9-680b0fa59db6.png)

**Comment by MaartenGr** [comment]
That is not the version that comes with that code. What happens is that you already have v0.5 installed. You need to have a fresh colab session for this to work or simply remove the v0.5 version.

**Comment by nadiafelix** [comment]
Excellent! Thank you :)
