### ISSUE TITLE
BerTopic Model - Visualization ignores 0th index

### ISSUE THREAD

**Issue by bala1802** [MaartenGr/BERTopic#667]
The BerTopic model resulted the below Topics:

![image](https://user-images.githubusercontent.com/22103095/183829057-30d8b95c-7298-4b40-b4ca-6287c983a3c1.png)

As you can see from the above, the model is finetuned to generate lesser outliers '-1' which has the count of 3 and it appears in the last.

While visualizing the [Topics per class](https://maartengr.github.io/BERTopic/getting_started/topicsperclass/topicsperclass.html),

`topic_model.visualize_topics_per_class(topics_per_class)`

the below interactive visual is generated, and however it ignored the `0th` index, to be precise the `Topic 0`. The Global Topic Representations are displayed from `1, 2, 3, 4, 5, 6, -1`

![image](https://user-images.githubusercontent.com/22103095/183829338-b6721217-79da-4136-ba7d-becb1bac7ef1.png)

1) Is the BerTopic designed in a way that it always assumes the very first index will be an outlier (-1), and eliminates it blindly?
2) Are the generated topics always accessed based on the count size, may be in descending order?

**Comment by MaartenGr** [comment]
Thank you for the extensive description! This is indeed a known issue and has to do with how the topics are accessed. It will be fixed in the next release as there will be some changes to the internal structure and the way topics are accessed.

**Comment by bala1802** [comment]
Thanks a lot for the quick response @MaartenGr , I appreciate your effort. After configuring the mentioned attribute `top_n_topics=None`, I could see the 0th Topic.
