### ISSUE TITLE
I need a fuction like a visualize_distribution, but without figure, that return the topics and probability.

### ISSUE THREAD

**Issue by nadiafelix** [MaartenGr/BERTopic#67]
I need a fuction like a visualize_distribution, but without figure, that return the topics and probability . Is there some like this?

**Comment by MaartenGr** [comment]
To extract the topics and probability you need to run the following:

```python
topic_model = BERTopic(calculate_probabilities=True)
topics, probabilities = topic_model.fit_transform(docs)
```
