### ISSUE TITLE
KeyError: 36 when BERTopic.transform(docs)

### ISSUE THREAD

**Issue by felipelopezp726** [MaartenGr/BERTopic#670]
Hi MaartenGr, thanks a lot for BERTopic!

I have a problem: when I try to obtain the predictions and probabilities of the bertopic model with 36 documents (I understand there should be considered in the order of thousands of samples, but it was just a random test that resulted in my experiments), I get the error:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/conda/envs/topic_modeling/lib/python3.7/site-packages/bertopic/_bertopic.py", line 400, in transform
    probabilities = hdbscan.membership_vector(self.hdbscan_model, umap_embeddings)
  File "/opt/conda/envs/topic_modeling/lib/python3.7/site-packages/hdbscan/prediction.py", line 587, in membership_vector
    clusterer.prediction_data_.cluster_tree)
  File "hdbscan/_prediction_utils.pyx", line 242, in hdbscan._prediction_utils.outlier_membership_vector
  File "hdbscan/_prediction_utils.pyx", line 249, in hdbscan._prediction_utils.outlier_membership_vector
  File "hdbscan/_prediction_utils.pyx", line 227, in hdbscan._prediction_utils.per_cluster_scores
KeyError: 36

The value after "KeyError" is exactly the number of documents with which I do the test, that is, if for example I only pass 20 documents, the resulting error is "KeyError: 20"

Here is the initialization procedure of BERTopic:
```
# initialize the model
from bertopic import BERTopic #bertopic version = 0.11.0
topic_model = BERTopic(embedding_model = 'distiluse-base-multilingual-cased-v2',
                    calculate_probabilities = True,
                    low_memory = True,
                    nr_topics = 2
                    )
docs = ... #list of 36 documents
# fit the model
topic_model.fit(docs)
# make prediction
topics_predicted, probs_predicted = topic_model.transform(docs) #the problem occurs here
```
However, by initializing the model as follows (adding the "min_topic_size" parameter and setting it to 5), the model returns no error and returns the predictions and probabilities:
```
topic_model = BERTopic(embedding_model = 'distiluse-base-multilingual-cased-v2',
                    calculate_probabilities = True,
                    low_memory = True,
                    nr_topics = 2,
                    min_topic_size=5
                    )
# fit the model
topic_model.fit(docs)
# make prediction
topics_predicted, probs_predicted = topic_model.transform(docs) #it works
```

Therefore, I would like to ask you the following questions:

1) What is the real reason for the error that the model throws me when initializing the model with the default value of the "min_topic_size" parameter (which is 10)? (Initially I thought that it was the low number of records (documents) with which I trained the model, but when I changed the parameter "min_topic_size" I realized that this is not really the reason)

2) Is there a default and/or suggested value to use for the "min_topic_size" parameter when I have few records (documents)?

3) Is there any configuration (modifying other parameters such as "nr_topics", "top_n_words", etc.) that is suggested to use when there are few documents to train the model (less than 100 as in my case)?

4) Is there a minimum value of records (documents) that one must consider so that when training the model it does not throw problems like the one that I got?

**Comment by MaartenGr** [comment]
> What is the real reason for the error that the model throws me when initializing the model with the default value of the "min_topic_size" parameter (which is 10)? (Initially I thought that it was the low number of records (documents) with which I trained the model, but when I changed the parameter "min_topic_size" I realized that this is not really the reason)

In order for HDBSCAN to properly find topics, it needs to know a certain minimum cluster size which is highly dependent on the number of documents that you have. In your case, since you have both a low number of topics but a relatively high `min_topic_size`, it throws an error. 

> Is there a default and/or suggested value to use for the "min_topic_size" parameter when I have few records (documents)?

It is important to realize that if you have few documents, the `min_topic_size` cannot be high. So lowering this will result in much better clusters. 

> Is there any configuration (modifying other parameters such as "nr_topics", "top_n_words", etc.) that is suggested to use when there are few documents to train the model (less than 100 as in my case)?

BERTopic is meant for usage on larger datasets, more than a couple hundred documents, as it helps in creating more accurate topic representations. It might also be that other models, such as k-Means might work better. Most importantly, if you are using HDBSCAN, you will need to lower `min_topic_size`. 

> Is there a minimum value of records (documents) that one must consider so that when training the model it does not throw problems like the one that I got?

Since it depends on the sub-models that you are using, such as HDBSCAN and UMAP, there is not a minimum value of documents. k-Means, for example, can handle low frequencies without parameter tuning without issues.

**Comment by MaartenGr** [comment]
Due to inactivity, I'll be closing this for now. Let me know if you have any other questions related to this and I'll make sure to re-open the issue!
