### ISSUE TITLE
errors when running topic_model.fit_tranform

### ISSUE THREAD

**Issue by imchlai** [MaartenGr/BERTopic#672]
Hi,
I am running topics, probs = topic_model.fit_transform(doc), but encountered the following error message. 

OMP: Info #271: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead.

Anyone encountered this issue? I'm using Python 3.7. Thanks.

**Comment by MaartenGr** [comment]
Although I am not familiar with that error message, a quick search indicates that this might be an issue with numba. I would advise starting from a completely fresh environment and installing BERTopic there.

**Comment by MaartenGr** [comment]
Due to inactivity, I'll be closing this for now. Let me know if you have any other questions related to this and I'll make sure to re-open the issue!
