### ISSUE TITLE
a slip of the pen. in the document

### ISSUE THREAD

**Issue by SharkFin-top** [MaartenGr/BERTopic#673]
https://maartengr.github.io/BERTopic/getting_started/topicreduction/topicreduction.html#manual-topic-reduction

in this page, the code

```python
topics_to_merge = [[1, 2]
                   [3, 4]]
topic_model.merge_topics(docs, topics, topics_to_merge)

```

Maybe, there need a "," 

that means

```python
topics_to_merge = [[1, 2],
                   [3, 4]]
topic_model.merge_topics(docs, topics, topics_to_merge)

```

**Comment by MaartenGr** [comment]
Thanks! I'll make sure it gets fixed in the next release.
