### ISSUE TITLE
BERTopic.load issue

### ISSUE THREAD

**Issue by srashtchi** [MaartenGr/BERTopic#678]
I am trying to load saved models but since this morning I get below error. just a week back I was able to load the very same saved model but not anymore.

`ModuleNotFoundError: No module named 'sklearn.metrics._dist_metrics'`

Please help there is a lot of riding on load model in my code!

**Comment by MaartenGr** [comment]
These kind of issues typically happen if you changed packages in your environment between saving and loading the model. Make sure that all dependencies are exactly the same when you saved the model as when you load it in. In your case, it seems that scikit-learn's version was changed.

**Comment by srashtchi** [comment]
I fit the models and saved them after setting up a brand new python env 3.9 with below standard installations:
pip install bertopic
pip install natsort

things were just fine and I was able to load the model easily. 
then I wanted to add evaluation to the code so I added more installations as below:
I  install the evaluation package with pip install . from your "BERTopic_evaluation" repo. Then as soon as I tried to load previous saved model I got that error.

For fixing this I created another brand new environment the same as the BERTopic original one (without the evaluation stuff). But this time I was able to only save the model not loading that.

**Comment by MaartenGr** [comment]
When you save a model in an environment and then install new packages, it might lead to existing dependencies being updated. So when you saved the model, the `pip install .` that you did afterwards might have upgraded or downgraded some of the packages in the environment. It is important to perform version control of your environment whenever you load and save models.

**Comment by srashtchi** [comment]
Thanks, it is clear now.
