### ISSUE TITLE
Paper "BERTopic: Leveraging BERT and c-TF-IDF to create easily interpretable topics"

### ISSUE THREAD

**Issue by nadiafelix** [MaartenGr/BERTopic#68]
Do you have the paper BERTopic: Leveraging BERT and c-TF-IDF to create easily interpretable topics?

**Comment by MaartenGr** [comment]
There currently is no paper accompanying this repository. The difficulty with topic modeling techniques is that evaluation can be quite subjective. There are measures available such as NPMI and Umass but those have their own significant downsides. Now that DTM is introduced in the new version I might write a paper but for now, that is not on the roadmap until I figure out a good strategy for evaluation, perhaps including human assessment.
