### ISSUE TITLE
Make lowercasing optional

### ISSUE THREAD

**Issue by grenwi** [MaartenGr/BERTopic#682]
While you can use your own CountVectorizer to enable / diable lowercasing for the document embeddings, it seems that currently lowercasing is always performed on the document text in the `_preprocess_text` function before extracting words via class-based TF-IDF.

This is probably unwanted for some languages such as German where a number of words switch their meaning decisively. 

Can an lowercasing in this step be made optional?

**Comment by MaartenGr** [comment]
Thank you for sharing this. It seems that lowercasing is quite redundant as the `CountVectorizer` does lowercasing as a default, so I think that step can actually be safely removed without affecting the pipeline. That would mean that you will have to define your own `CountVectorizer` and disable lowercasing there. There is currently a PR in the work for a new version of BERTopic, so I'll make sure to change that there.
