### ISSUE TITLE
Does Bertopic have incremental learning capabilities??

### ISSUE THREAD

**Issue by jjaitley** [MaartenGr/BERTopic#683]
Do we have a capability in Bertopic in which input data is continuously used to extend the existing model's knowledge i.e. to further train the model? Any help in this area would be highly appreciated

**Comment by MaartenGr** [comment]
Such a method would typically need sub-models that support something like `.partial_fit` to further train the model when new data comes in. Some of the underlying models in BERTopic do not support this, such as HDBSCAN. Fortunately, BERTopic supports various sub-models that do support this technique which should allow for the development of such a feature. 

And... you are in luck! Although this feature is currently not implemented in BERTopic, there is already a PR [here](https://github.com/MaartenGr/BERTopic/pull/668) that you can use which supports Online/Batch learning in BERTopic. You can also find instructions there on how it works and which models are necessary for it to work. 

I cannot say when this new feature will officially be released as there are a few other things I need to update, such as the documentation but I hope to release it in the coming weeks.

**Comment by MaartenGr** [comment]
[Online and incremental learning](https://maartengr.github.io/BERTopic/getting_started/online/online.html) is now supported in the v0.12 version of BERTopic. This now allows you to continuously train and update your topic model!
