### ISSUE TITLE
Real world use cases

### ISSUE THREAD

**Issue by slavaGanzin** [MaartenGr/BERTopic#684]
Hello Maarten.

Awesome library, congrats!

I have some questions that I don't find answers to:
1. Is there any way to predefine topics, like "automotive", "political" (as category names, or meaningful words list, or feed data and mark them as categories) and then train topics based on this input?
2. Is there a way to train multilabeled topic model?

**Comment by MaartenGr** [comment]
> Is there any way to predefine topics, like "automotive", "political" (as category names, or meaningful words list, or feed data and mark them as categories) and then train topics based on this input?

There are two ways of achieving this, either using [guided](https://maartengr.github.io/BERTopic/getting_started/guided/guided.html) topic modeling or using [semi-supervised](https://maartengr.github.io/BERTopic/getting_started/supervised/supervised.html) topic modeling. Although both are implemented in BERTopic, do note that they merely nudge the creation of topics towards those predefined topics. It does not mean that it will necessarily find exactly those topics. 

> Is there a way to train multilabeled topic model?

That depends on the clustering model that you use in BERTopic. If you used HDBSCAN, then you could use `BERTopic(calculate_probabilities=True)` to get the topic-document probability matrix from which you can extract multi-labels.

**Comment by slavaGanzin** [comment]
Thanks for explanations
