### ISSUE TITLE
topic_over_time: global tuning issue

### ISSUE THREAD

**Issue by shinhanshiu** [MaartenGr/BERTopic#688]
When using the topic_over_time function with global tuning on, this leads to situations where a term, even though it is absent in the documents in a time bin of a topic, to have non-zero c-Tf-Idf that can make that term one of the top terms if it has a sufficiently high global c-Tf-Idf. 

I am analyzing biological literature and the term really take off in the 2000s, but the 1st time bin in the 70s also has it as a top term when the term does not exist in any documents.

Not a bug, but worry that this may lead to mis-interpretations. This also makes me wonder what is the goal behind such global tuning.

**Comment by MaartenGr** [comment]
The reason for this global tuning is that at certain timestamps there are too few documents to properly create an accurate topic representation. Seeing as we already know the larger representation of the topic it might be worthwhile for certain use cases to use the global tuning. In practice, this might be helpful to some users as words that do not appear in documents can still be used to describe them, for others it might indeed not be useful.
