### ISSUE TITLE
why can't I use gpu to do prediction, please help

### ISSUE THREAD

**Issue by 652994331** [MaartenGr/BERTopic#689]
hi, I am trying to use gpu to do the prediction, then I get some errors like below:
<img width="907" alt="Screen Shot 2022-08-25 at 23 41 43" src="https://user-images.githubusercontent.com/51428350/186709834-9090d45f-aea2-4e75-93a0-9ce0329e8ba0.png">
 it seems there is something wrong with my environment. here is my setting 
<img width="598" alt="Screen Shot 2022-08-26 at 00 03 56" src="https://user-images.githubusercontent.com/51428350/186714513-eda37333-dc2c-468c-bee9-4929a7539910.png">
<img width="476" alt="Screen Shot 2022-08-26 at 00 06 30" src="https://user-images.githubusercontent.com/51428350/186715141-5a464507-178e-4a62-b06a-5dc26b266576.png">
cuda 10.2 and p100 gpu

**Comment by MaartenGr** [comment]
Could you share your code for training the model? Without the code, it is difficult to say what exactly is happening here. 

Having said that, these kinds of issues often relate to the environment you are working in. Starting from a completely fresh environment and installing BERTopic there together with [PyTorch](https://pytorch.org/get-started/locally/) often resolves many issues. It might be worthwhile to try it out.

**Comment by 652994331** [comment]
@MaartenGr thanks for your help, below are my training code
<img width="375" alt="Screen Shot 2022-08-27 at 23 01 34" src="https://user-images.githubusercontent.com/51428350/187035834-38a8d218-908a-472a-92c9-ec6460df8c65.png">
and looks like the version of my bertopic is 0.11.0
and my coda is 10.2, torch version is 1.12.0+cu10.2
<img width="528" alt="Screen Shot 2022-08-27 at 23 00 53" src="https://user-images.githubusercontent.com/51428350/187035815-281456f0-cc7f-4e64-90a4-c1ef22c429c4.png">
e

**Comment by MaartenGr** [comment]
Could you share your entire code? As in, also the code necessary to create `topic_model_ml`, as it is currently unclear what kind of sub-models, parameters, etc. you have chosen for your model.

**Comment by 652994331** [comment]
@MaartenGr sure, the codes are as below:
<img width="512" alt="Screen Shot 2022-08-28 at 15 16 08" src="https://user-images.githubusercontent.com/51428350/187062448-9b862b54-277a-403a-81a2-45c0e137af22.png">
<img width="499" alt="Screen Shot 2022-08-28 at 15 16 40" src="https://user-images.githubusercontent.com/51428350/187062471-b39d7a41-a5ce-4ade-a87f-74b8e1bd4693.png">

**Comment by MaartenGr** [comment]
The code indeed does not seem like something is going on there. I would advise starting from a fresh environment and re-installing what you need there. Hopefully, that will resolve the issue.

**Comment by 652994331** [comment]
@MaartenGr thank you. I found something this afternoon, it seems my cuda version is 10.2 and it requires 11.2 which includes lib_cudart.so.11. right after I installed cuda11.2, the warning disappeared. 
<img width="634" alt="Screen Shot 2022-08-29 at 11 07 03" src="https://user-images.githubusercontent.com/51428350/187115167-165a0e54-d715-431e-98ab-52643e39cef0.png">
during the loading process of that progress bar, the gpu usage rises to 80%. Now, it's in the "transformed  document to embedding" process and gpu usage is 0%. I think this problem's solved and now I will just wait to check the training process

**Comment by MaartenGr** [comment]
Glad to hear that with the other version you do not have those issues anymore. The logging that you received is from huggingface and might happen in certain environments. I believe you can remove those issue by playing around with the environment variable that is mentioned in the output. The logging that you should look for is prefaced with "BERTopic". In your image, that would be "BERTopic - Reduced dimensionality".
