### ISSUE TITLE
Reduce_topics Algorithm logic explanation ?

### ISSUE THREAD

**Issue by djaym7** [MaartenGr/BERTopic#690]
"Finally, by iteratively merging the c-TF-IDF representations of the least common topic with its most
similar one, we can reduce the number of topics to
a user-specified value"

From the paper and the implementation, the least common topic is merged with the most similar one. Why is this done instead of merging the most similar two topics ? As the least common could be very different to the most similar (even with threshold ..)

**Comment by MaartenGr** [comment]
The main reason for doing the reduction this way is to reduce micro-clusters that are being created. Moreover, this is meant as a feature that does something more than what the cluster model is already capable off, namely merging similar topics. Having said that, there are many ways in which you can reduce the topics, from merging them manually based on domain knowledge to using the most similar topics (either based on c-TF-IDF representations or weighted averaged embeddings) and everything in between.

**Comment by djaym7** [comment]
Great, I assumed that you assumed clustering will take care of merging similar clusters and what remains is all dissimilar clusters which is why the least common topic method.
