### ISSUE TITLE
save & load model

### ISSUE THREAD

**Issue by aph61** [MaartenGr/BERTopic#693]
Hi all,

I cannot reload and use an already computed model. My call sequence

```
topic_model = BERTopic(embedding_model=sentence_model,
                                  umap_model=umap_model,
                                  n_gram_range=(1,1),
                                  min_topic_size=minimum_topic_size,
                                  calculate_probabilities=True,
                                  verbose=True)
topics, topic_distribution = topic_model.fit_transform(txt_to_fit, embeddings=sentence_embeddings)
topic_model.save(os.path.join(".", filename + ".model"))
```
topic_model.get_topic_info() gives normal results

restart the kernel

`topic_model.load(os.path.join(".", filename + ".model"))`

topic_model.get_topic_info() gives 
ValueError: This BERTopic instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator."

Just pickling the model does not help either. My hack is to remove the randomization in umap
```
umap_model = UMAP(n_neighbors=15, n_components=5, 
                  min_dist=0.0, metric='cosine', 
                  random_state=42)
```
but I can't use that in the production environment

Anyone had the same experience

best, Andreas

using:  BERTopic 0.11, Python 3.8, Jupyter notebook, Ubuntu 20.x,

**Comment by MaartenGr** [comment]
Based on how you load your model, there might be an issue there. Did you make sure to load your model in as mentioned in the documentation [here](https://maartengr.github.io/BERTopic/getting_started/quickstart/quickstart.html#saveload-bertopic-model)? 

In other words, doing the following:

```python
from bertopic import BERTopic
topic_model = BERTopic.load("my_model")
```

**Comment by aph61** [comment]
if "my_model" is a file, yes, that's exactly how I did it.
I first defined topic_model as a BERTopic() instance,

```
topic_model = BERTopic()
topic_model.load("the file is saved the model to")
```
and the snippet

`topic_model.get_topic_info()`

gives the same result is as before

`ValueError: This BERTopic instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.`

And as far as I understand, a new fit gives you a new model. 
I had this problem also with v0.9. It was not an issue with earlier versions (I don't know if that was 0.08, 0.07..). In those versions I also could save/load the model as a regular pickle file

Best,

Andreas

**Comment by MaartenGr** [comment]
That is the thing, you are actually not doing the following:

```python
topic_model = BERTopic.load("my_model")
```

but you are doing this:

```python
topic_model = BERTopic().load("my_model")
```

The difference here lies in the use of `()`. When you do `BERTopic()` a BERTopic model is created with default parameters. Technically it calls the `__init__` function and does some stuff there. When you do `BERTopic.load()` instead, the `__init__` function is not called and the local model is loaded. This process does not work quite that well if you create a BERTopic with default parameters and load a model on top of that. That is why the documentation states to use `BERTopic.load()` and not `BERTopic().load()`.

**Comment by aph61** [comment]
Thanks! 

I don't know why I changed the code, but the problem is solved (I already checked)

thanks again
