### ISSUE TITLE
Automatic merging of topics by thresholding their cluster separation

### ISSUE THREAD

**Issue by weekend37** [MaartenGr/BERTopic#695]
Hey Maarten, thanks for putting all of this together and making publicly available!

A quick question related to merging topics:

When visualizing the topic hierarchy of my fitted models, I'm constantly seeing them perfectly grouped by the coloring schema (with the default color_threshold for cluster separation) and **I wish to merge these topics automatically** (during or post the model fitting).

Has that functionality already been implemented?
And if not, could you tell me what's the best way to do this? Specifically I'm wondering if you know how the cluster separation is measured - is it the linkage distance?

**Comment by MaartenGr** [comment]
> When visualizing the topic hierarchy of my fitted models, I'm constantly seeing them perfectly grouped by the coloring schema (with the default color_threshold for cluster separation) and I wish to merge these topics automatically (during or post the model fitting).

There are several ways in which topics can be merged in BERTopic. You could start with `BERTopic(nr_topics="auto")` which reduces the topics further using HDBSCAN. Similarly, you can use `BERTopic(nr_topics=any_integer)` to reduce the number of topics to a preselected value by iteratively merging the least frequent topic with its most similar topic. Lastly, you can use `hierarchical_topics = topic_model.hierarchical_topics(docs, topics)` to create different levels of topic hierarchy and then manually merge topics that you feel belong together with `.merge_topics` as described [here](https://maartengr.github.io/BERTopic/getting_started/hierarchicaltopics/hierarchicaltopics.html). There, you will also find something about the linkage distance, which is similarly included in the docstrings.

**Comment by weekend37** [comment]
Got it. The `hierarchical_topics` function was indeed helpful for the manual merging based on the linkage distance.
Thanks Maarten!
