### ISSUE TITLE
Best Practice for Accessing umap.parametric_umap

### ISSUE THREAD

**Issue by denson** [MaartenGr/BERTopic#697]
Parametric UMAP learns the relationship between the data and embedding using a neural network, rather than learning the embeddings directly. 

It should be fairly easy to integrate into BERTopic? However, I'm not sure exactly how to do this.

> Parametric UMAP is simply a subclass of UMAP, so it can be used just like nonparametric UMAP, replacing umap.UMAP with parametric_umap.ParametricUMAP. The most basic usage of parametric UMAP would be to simply replace UMAP with ParametricUMAP in your code:

```
from umap.parametric_umap import ParametricUMAP
embedder = ParametricUMAP()
embedding = embedder.fit_transform(my_data)
```

**Comment by MaartenGr** [comment]
In BERTopic, you can use any dimensionality reduction algorithm as long as they support a few functions as you can see in the documentation [here](https://maartengr.github.io/BERTopic/getting_started/dim_reduction/dim_reduction.html). I would advise reading through that to get an understanding of how to implement other sub-models in BERTopic. Generally, if it supports the necessary functions, you only need to do the following:

```python
from bertopic import BERTopic
from umap.parametric_umap import ParametricUMAP
umap_model = ParametricUMAP()
topic_model = BERTopic(umap_model=umap_model)
```

**Comment by denson** [comment]
Wonderful! BERTopic is so well written it is a pleasure to use.
