### ISSUE TITLE
Evaluation metric missing

### ISSUE THREAD

**Issue by khadkechetan** [MaartenGr/BERTopic#70]
Hi,
I am unable to see the evaluation metric for comparison. It would be difficult to compare the output without comparison.

**Comment by MaartenGr** [comment]
Evaluating topic models is a tricky subject as it can be, to a certain extend, quite subjective. However, there are some metrics that can be used as a proxy for evaluating the model such as NPMI, Umass, information gain, etc. These metrics do bring a significant number of issues with them as they all have major disadvantages. Moreover, there is typically no ground truth to what, objectively, constitutes a "correct" topic. People often differ in that regard which makes evaluation difficult. 

At some point, there will be extensive evaluation but that requires a bit more research into metrics that I feel like (and academically seem to be) the best in evaluating topic models. Now that DTM is introduced in the new version I might write a paper but for now, that is not on the roadmap until I figure out a good strategy for evaluation, perhaps including human assessment.
