### ISSUE TITLE
Why "nr_topics='auto'"

### ISSUE THREAD

**Issue by kaifeijidezxb** [MaartenGr/BERTopic#707]
Hello dear developers, I'm confused when using the reduced topic count. When I set nr_topics='auto', what is the basis for reducing the number of topics. Is there an article here where I can learn this, thanks a lot!

**Comment by MaartenGr** [comment]
When you use `nr_topics="auto"`, HDBSCAN is used to cluster topics using each c-TF-IDF representation. Each topic in a cluster is merged with all other topics in that cluster. The benefit of using HDBSCAN here is that it generates "outlier" topics. These outliers prevent topics from being merged if no other topics are similar.

**Comment by kaifeijidezxb** [comment]
> 使用 时`nr_topics="auto"`，HDBSCAN 用于使用每个 c-TF-IDF 表示对主题进行聚类。集群中的每个主题都与该集群中的所有其他主题合并。在这里使用 HDBSCAN 的好处是它会生成“异常”主题。如果没有其他主题相似，这些异常值会阻止主题被合并。

get!!!! thanksss!!!!!!
