### ISSUE TITLE
Some topic in BERTopic has empty keywords

### ISSUE THREAD

**Issue by ranjonaa** [MaartenGr/BERTopic#708]
Any one can help me with error, 
when I run BERTopic model, i got one or more topic has empty keywords, like this
0: [('', 1e-05),
  ('', 1e-05),
  ('', 1e-05),
  ('', 1e-05),
  ('', 1e-05),
  ('', 1e-05),
  ('', 1e-05),
  ('', 1e-05),
  ('', 1e-05),
  ('', 1e-05),
  ('', 1e-05),
  ('', 1e-05)],

**Comment by MaartenGr** [comment]
This is generally not an error. It might happen that the collection of documents in that topic has very few or perhaps no words. Other than that, it might even be that when you use the `CountVectorizer`, certain documents will end up empty if it only consists of stop words. Have you checked what documents are in that specific topic?

**Comment by MaartenGr** [comment]
Due to inactivity, I'll be closing this issue for now. Feel free to reach out if you want to continue this discussion or re-open the issue!
