### ISSUE TITLE
reduce_topics() got multiple values for argument 'nr_topics'

### ISSUE THREAD

**Issue by Miranda-Saari-Bose** [MaartenGr/BERTopic#712]
Running `new_topics, new_probs = topic_mod.reduce_topics(docs, topics, probs, nr_topics = 3)` produces the error: reduce_topics() got multiple values for argument 'nr_topics'.
I had no issues with the syntax last week and referencing the documentation all seems to be correct. Did something change in the latest update?

**Comment by MaartenGr** [comment]
The function was updated in the new release to accommodate for the inclusion of attributes. You can find in the documentation [here](https://maartengr.github.io/BERTopic/getting_started/topicreduction/topicreduction.html) how you should use the function. Specifically, the parameters `topics` and `probs` are removed and are not necessary anymore. Use it as follows:

```python
topic_mod.reduce_topics(docs, nr_topics = 3) 
topics = topic_mod.topics_
probs = topic_mod.probabilities_
```
