### ISSUE TITLE
question about function: get_representative_docs()

### ISSUE THREAD

**Issue by 652994331** [MaartenGr/BERTopic#713]
Hi, I'd like to ask a quick question about the function: get_representative_docs(). as I understand, this function returns the most representative docs about a topic. My question is, are these docs sorted based on their representative score or something(from the most related to the least) and how it works. much appreciate.

**Comment by MaartenGr** [comment]
These documents are extracted following the density-based clustering principle that HDBSCAN follows. More specifically, it extracts so-called "exemplars", points that should represent clusters well. You can find more about that [here](https://hdbscan.readthedocs.io/en/latest/soft_clustering_explanation.html#distance-based-membership).

**Comment by MaartenGr** [comment]
Due to inactivity, I'll be closing this issue for now. Feel free to reach out if you want to continue this discussion or re-open the issue!
