### ISSUE TITLE
Suggestion: add low_memory parameter in visualize_topics

### ISSUE THREAD

**Issue by lorenzo-bonetti** [MaartenGr/BERTopic#715]
Hi Maarten, first of all thank you for this tool, really amazing job and nice documentation!

I had a memory issue creating the visualization chart, in particular i think it is due to the memory usage of `UMAP` that can be lowered using the parameter `low_memory=True` in [visualize_topics](https://github.com/MaartenGr/BERTopic/blob/master/bertopic/plotting/_topics.py). Do you think it would be a good idea to expose this parameter in the visualize topics as well as you already did in BERTopic constructor?

In my setup i have ~3000 documents, and the problem i think arises when i want to create the visualization chart for all the topics instead of choosing a subset of top_n but i was wondering if adding the parameter `low_memory=True` in that function would solve the problem.

Thank you

**Comment by MaartenGr** [comment]
Hmm, I am not entirely sure if the memory issue you get stems from UMAP since you only have 3000 documents on which the model was trained. To get a better understanding of the issue, can you share your code for training the model? Also, how many topics were created after this training procedure? 

Also, reading through the code, it seems that there might be some optimization possible there but I'll have to try out some things first.

**Comment by lorenzo-bonetti** [comment]
Yes sure, here's the code: 


        vectorizer_model = CountVectorizer(stop_words=self.stop_words, ngram_range=(1, 2))
        
        topic_model = BERTopic(
            language="multilingual",
            top_n_words=10,
            min_topic_size=10,
            vectorizer_model=vectorizer_model,
            verbose=True,
            low_memory=True
            )
        
        topics, _ = topic_model.fit_transform(texts)

        topic_labels = topic_model.generate_topic_labels(nr_words=10,
                                                 topic_prefix=False,
                                                 word_length=10,
                                                 separator=",")

        topic_labels = [", ".join(list(set(sentence.split(",")))[:3]) for sentence in topic_labels]

        topic_model.set_topic_labels(topic_labels)

        topic_model.save(self.storage_path + "/BERTopic_model", save_embedding_model=False)

        self.logger.info("Saved BERTopic model")

        barchart_figure = topic_model.visualize_barchart(
            top_n_topics=50,
            n_words=5,
            width=350,
            height=350)
        barchart_figure.write_html(self.storage_path + "/barchart.html")

        topics_per_class = topic_model.topics_per_class(texts, topics, classes=self.classes)
        topics_per_class_figure = topic_model.visualize_topics_per_class(topics_per_class, top_n_topics=50, custom_labels=True)
        topics_per_class_figure.write_html(self.storage_path + "/topics_per_class.html")

        fig = topic_model.visualize_topics(top_n_topics=50, width=800, height=800)
        fig.write_html(self.storage_path + "/topics_map.html")

Everything works fine until the last two lines which is where my workers fail due to memory issues.
The topics created are 100

**Comment by MaartenGr** [comment]
I am not immediately seeing any strange things happening in your code. Which version of BERTopic are you using? 

The only thing that seems related here is perhaps the size of the c-TF-IDF matrix. Could you run `topic_model.c_tf_idf.shape` or `topic_model.c_tf_idf_.shape` and post the results here? If that size is rather large, then it might be worthwhile to add the following to your code:

```python
vectorizer_model = CountVectorizer(stop_words=self.stop_words, ngram_range=(1, 2), min_df=2)
```

The `min_df` prevents large bag-of-words matrices from being created.

**Comment by lorenzo-bonetti** [comment]
BERTopic version: `0.11.0`
`topic_model.c_tf_idf.shape`: `(97, 1845923)`

... yes i think that may be the issue, i'll try adding the `min_df` parameter and see if that solves the memory issue

**Comment by lorenzo-bonetti** [comment]
New c-tfidf shape after adding `min_df=2`: `(105, 243854)`, and the workers didn't fail

Thank you for your precious help!
