### ISSUE TITLE
topic_model.hierarchical_topics(docs, topics) error on reading embedding 

### ISSUE THREAD

**Issue by PeggyFan** [MaartenGr/BERTopic#720]
I have been able to succesfully run the a variation of the following that builds a BERTopic model:
```
umap_model = UMAP(n_neighbors=15, n_components=5, 
                  min_dist=0.0, metric='cosine', random_state=42)
topic_model = BERTopic(umap_model=umap_model)
topics, probs = topic_model.fit_transform(docs)
```
I would like to get the hierarchy and tree data on topics, but when I ran

```hierarchical_topics = topic_model1hierarchical_topics(docs, topics)```

I kept getting below error:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/tmp/ipykernel_24482/4265581561.py in <cell line: 4>()
      2 ## https://online.stat.psu.edu/stat505/lesson/14/14.4
      3 
----> 4 hierarchical_topics = topic_model.hierarchical_topics(docs, topics)
      5 # topic_model.visualize_hierarchy(hierarchical_topics=hierarchical_topics)
      6 

~/anaconda3/envs/python3/lib/python3.8/site-packages/bertopic/_bertopic.py in hierarchical_topics(self, docs, linkage_function, distance_function)
    855         embeddings = self.c_tf_idf_[self._outliers:]
    856         X = distance_function(embeddings)
--> 857         Z = linkage_function(X)
    858 
    859         # Calculate basic bag-of-words to be iteratively merged later

TypeError: 'list' object is not callable
```

I was able to run other functions without problem, including:
```
topic_model.visualize_barchart()
topic_model.visualize_hierarchy()
topic_model.visualize_topics()
topic_model.get_topic_info()
```

I also tried to uninstall and re-install `bertopic` but same error persists.
What might be the issue here?

**Comment by MaartenGr** [comment]
From the error message, it seems that you upgraded BERTopic to v0.12. In that version, you do not need to pass `topics` anymore. In other words, you should now run it as follows:

```python
hierarchical_topics = topic_model.hierarchical_topics(docs)
```

It often helps to check out the docstrings of a function whenever something goes wrong. There is often quite a bit of information there that should help you figure out what is happening.

**Comment by PeggyFan** [comment]
I see. I did not notice the input parameters have changed with the new version. Thank you for pointing it out.
