### ISSUE TITLE
Named Entity Recognition - spacy - BERTopic?

### ISSUE THREAD

**Issue by Ulrich-Buehlmann** [MaartenGr/BERTopic#729]
Hi Marteen,

is there a simple way to integrate NER (such as customers, products, companies) and lemmatization into BERTopic; either front-up or as a post-process?
I have not much data (~10'000 documents) but each time all with a defined set of products, users and customers. I am turnaround manager with some industrial psychology background trying to understand the real issues in a company as fast as possible.

Thanks a lot - also for developping BERTopic!
Ulrich

**Comment by drob-xx** [comment]
Hi @Ulrich-Buehlmann,

@MaartenGr will be able to give a much more thorough and definitive answer to your question in the meantime this may or may not be helpful:

- Check out [semi-supervised topic modeling](https://maartengr.github.io/BERTopic/getting_started/supervised/supervised.html#semi-supervised-topic-modeling). I haven't used this feature but following the project and reading through the code my understanding is that you can define a vocabulary (your NER'd terms in this case) which will add weight to that vocabulary and increase the likelihood that clusters will be influenced by it.

- I'm not 100% clear on what your use-case is but it may be that your NER terms are orthogonal to a topic model. For example you may have a case where the topics are indicative of different kinds of interactions with products. To flesh this out you could have a situation where a given NER'd term - say a product appears in a number of different topics - say "support", "complaints", "praise", "criticism" etc.etc.

One approach that *might* work would be to segment your documents via the topic model and then run your NER on those using the topic cluster in conjunction with labels gleaned from the NER to do your analysis. It might even make sense to run the NER, identify a subset of documents based on that and then run BERTopic on that subset. 

Remember that HDBSCAN will do its best given its parameters to efficiently cluster documents. However, in my experience the results you get are *highly* dependent on an individual corpus and to get the best results you need to tune HDBSCAN against the UMAP reduction. A well tuned HDBSCAN will generally dramatically reduce the number of outlier documents and theoretically make your clustering better.

**Comment by MaartenGr** [comment]
> is there a simple way to integrate NER (such as customers, products, companies) and lemmatization into BERTopic; either front-up or as a post-process?

Could you explain a bit more about the reason for integrating NER and lemmatization? NER, for example, is used to find out whether something is an entity. So let's say you have a NER algorithm, what exactly do you intend to do with it with respect to topic modeling? In a perfect world, how would you like to see the documents processed in BERTopic? Could you give an example?

**Comment by Ulrich-Buehlmann** [comment]
Hi Marteen,
thanks for your quick reply!
Here is an example as email text as well as a structured WORD doc.
Ulrich
 
1        Your questions
Could you explain a bit more about the reason for integrating NER and lemmatization?
Unify customer and product names, standardize issue names. I never saw these name unified in any company so far.
NER, for example, is used to find out whether something is an entity. So let's say you have a NER algorithm, what exactly do you intend to do with it with respect to topic modeling?
Having all unified NERs as part of the topics in case they exist in at least document.
In a perfect world, how would you like to see the documents processed in BERTopic? Could you give an example?
There is a example from my last project below
2        Background
Since 30+ years I turnaround companies and manufacturing plants by generating liquidity and growth, reducing cost and mainly by motivation the employees for a change. So far, during the first 2 weeks I ran many interviews, checked out the figures and formulated assumptions (topics). Then the clean-up starts. Later we stabilize the organization and then grow. The goal is identifying loss driving products, loss driving customers, inefficient processes and then stop the bleeding.
This all is experience and financial figures driven but I am never sure if I ignore a hidden problems (topic) just because nobody tells me, or everybody assumes I already know it.
If you like to know more, I send you a copy of my turn around book.
3        New approach
I would like to read all corporate documents of the last 12 months (around 10’000) and identify the topics (bad ones to stop bleeding and good ones for motivation).  In parallel I would like to structure the topics into products, customers, suppliers, competitors, processes and link them to people. In my understanding these categories are all NERs, they are easy to identify by downloading from ERP / CRM / HR. Just running a standard topic modelling process might ignore some important customers of the past, coming products, key suppliers in case there are not many documents containing their identifiers (NERs).
Somebody in your team advised me to apply semi-supervised topic modelling. After reading the docs I can see 2 approaches:
4        Data
Nomenclature: “_” is the topic element separator as in BERTopic, “-“ connects 2 tokens, “ “ is space
Customers:

Nestlé, Nestle, Nestle GmbH
Lindt

Products:

BVC 260, BVC260, BVC-260
BVC-180, BVC 180
BVI 400

Quality issues:

Production output too low, sealing not gasproof, bad sealing, label in wrong position

Delivery issues:

Shipping late, shipment late, delivery too late

Pricing issues:

Price too low, price increase not implemented, gross profit too low (that’s tough to track, maybe later)

5        Post process (after standard BERTopic run)
5.1       BERTopic output
I constructed some possible topics:

BVC260_Nestlé_delivery_late
BVC_260_Nestle_shipping_late_GmbH
BVC-260_bad_sealing
Lindt_price_too_low
Lindt_too_pricies_low
Lindt_price_increase_not_implemented
BVI_production_output_400_low

5.2       Unify customer and product names
Looks like a regex job which I don’t really like but it is feasible

BVC260_Nestle_delivery_late
BVC260_Nestle_shipping_late
BVC260_bad_sealing
Lindt_price_too_low
Lindt_too_pricies_low
Lindt_price_increase_not_implemented
BVI400_production_output_low

5.3       Unify issues

Looks like a proximity match / regex task
BVC260_Nestle_delivery-late
BVC260_Nestle_delivery-late
BVC260_bad-sealing
Lindt_price-too-low
Lindt_price-too-low
BVI400_production-output-too-low

5.4       Questions

How do I make sure that the product BVI 180 which is mentioned only in one document gets “topiced” because the machine has to go by airfreight to Brazil?
Any better ideas than regex?
What about NER for customers and products?

6        Preprocess and semi-supervised BERTopic run
6.1       Prepare corpus

Unify and generate all customer NERs, product NERS, (if feasible also issue NERs) in all documents
Lemmatize the corpus (because there are not many documents ~10’000)
Process all docs to identify all NERs and allocate them to the document as given topic elements

Example:
doc4711;Nestle;Lindt;price-too-low
doc4712;Panzani;BVC260;production-output-too-low
doc4713;bad-sealing ; BVC260
6.2       Run a semi-supervised topic modelling
Unified topics items such as customer name, issue names, product identifiers, people are defined as above.
6.3       Questions

Is BERTopic generating a topic even if there is only 1 document with e.g. rare product?
Can I control the hierarchy of the topics in advance?
What is in your opinion the easiest way to get the bi-/trigrams for quality, delivery, price, other issues?

7        Extension to the organization
This is just an idea from a sales director from another company:

Mapping the organization as hierarchy of topics
Reading the emails and appendices
Topic modelling the email bodies and the appendices
As an alternative: map the organization chart and the email traffic into a network such as networx (later to be converted eventually into pandas)
Adding to the network the relation between nodes as a list of topics

 
-----Original Message-----From: "Maarten Grootendorst" ***@***.***>Sent: Tuesday, September 20, 2022 2:35amTo: "MaartenGr/BERTopic" ***@***.***>Cc: "Ulrich-Buehlmann" ***@***.***>, "Mention" ***@***.***>Subject: Re: [MaartenGr/BERTopic] Named Entity Recognition - spacy - BERTopic? (Issue #729)


is there a simple way to integrate NER (such as customers, products, companies) and lemmatization into BERTopic; either front-up or as a post-process?

Could you explain a bit more about the reason for integrating NER and lemmatization? NER, for example, is used to find out whether something is an entity. So let's say you have a NER algorithm, what exactly do you intend to do with it with respect to topic modeling? In a perfect world, how would you like to see the documents processed in BERTopic? Could you give an example?
—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>



Mit freundlichen Grüßen / Best regards
 
Ulrich Bühlmann
Geschäftsführer
 
Bühlmann Projektentwicklung & Management UG
Ferdinandstr. 13
D-47906 Kempen
T: +49 1520 140 9905
M: ***@***.***
W: www.buehlmann-partner.com

**Comment by Ulrich-Buehlmann** [comment]
Sorry - I had to rename some items - the text and content is identical
1	Your questions
Could you explain a bit more about the reason for integrating NER and lemmatization?
Unify customer and product names, standardize issue names. I never saw these name unified in any company so far.
NER, for example, is used to find out whether something is an entity. So let's say you have a NER algorithm, what exactly do you intend to do with it with respect to topic modeling?
Having all unified NERs as part of the topics in case they exist in at least document.
In a perfect world, how would you like to see the documents processed in BERTopic? Could you give an example?
There is a example from my last project below
2	Background
Since 30+ years I turnaround companies and manufacturing plants by generating liquidity and growth, reducing cost and mainly by motivation the employees for a change. So far, during the first 2 weeks I ran many interviews, checked out the figures and formulated assumptions (topics). Then the clean-up starts. Later we stabilize the organization and then grow. The goal is identifying loss driving products, loss driving customers, inefficient processes and then stop the bleeding.
This all is experience and financial figures driven but I am never sure if I ignore a hidden problems (topic) just because nobody tells me, or everybody assumes I already know it.
If you like to know more, I send you a copy of my turn around book.
3	New approach
I would like to read all corporate documents of the last 12 months (around 10’000) and identify the topics (bad ones to stop bleeding and good ones for motivation).  In parallel I would like to structure the topics into products, customers, suppliers, competitors, processes and link them to people. In my understanding these categories are all NERs, they are easy to identify by downloading from ERP / CRM / HR. Just running a standard topic modelling process might ignore some important customers of the past, coming products, key suppliers in case there are not many documents containing their identifiers (NERs). 
Somebody in your team advised me to apply semi-supervised topic modelling. After reading the docs I can see 2 approaches:
4	Data
Nomenclature: “_” is the topic element separator as in BERTopic, “-“ connects 2 tokens, “ “ is space
Customers:
•	Namé, Name, Name GmbH
•	Longy
Products:
•	XYZ 360, XYZ360, XYZ-360
•	XYZ-180, XYZ 180
•	XYA 540
Quality issues:
•	Production output too low, sealing not gasproof, bad sealing, label in wrong position
Delivery issues:
•	Shipping late, shipment late, delivery too late
Pricing issues:
•	Price too low, price increase not implemented, gross profit too low (that’s tough to track, maybe later)
5	Post process (after standard BERTopic run)
5.1	BERTopic output
I constructed some possible topics:
•	XYZ360_Namé_delivery_late
•	XYZ_360_Name_shipping_late_GmbH
•	XYZ-360_bad_sealing
•	Longy_price_too_low
•	Longy_too_pricies_low
•	Longy_price_increase_not_implemented
•	XYA_production_output_540_low
5.2	Unify customer and product names
Looks like a regex job which I don’t really like but it is feasible
•	XYZ360_Name_delivery_late
•	XYZ360_Name_shipping_late
•	XYZ360_bad_sealing
•	Longy_price_too_low
•	Longy_too_pricies_low
•	Longy_price_increase_not_implemented
•	XYA540_production_output_low
5.3	Unify issues
Looks like a proximity match / regex task
•	XYZ360_Name_delivery-late
•	XYZ360_Name_delivery-late
•	XYZ360_bad-sealing
•	Longy_price-too-low
•	Longy_price-too-low
•	XYA540_production-output-too-low
5.4	Questions
•	How do I make sure that the product XYA 180 which is mentioned only in one document gets “topiced” because the machine has to go by airfreight to Brazil?
•	Any better ideas than regex?
•	What about NER for customers and products?
6	Preprocess and semi-supervised BERTopic run
6.1	Prepare corpus
•	Unify and generate all customer NERs, product NERS, (if feasible also issue NERs) in all documents
•	Lemmatize the corpus (because there are not many documents ~10’000)
•	Process all docs to identify all NERs and allocate them to the document as given topic elements
Example: 
doc4711;Name;Longy;price-too-low
doc4712;Panzani;XYZ360;production-output-too-low
doc4713;bad-sealing ; XYZ360
6.2	Run a semi-supervised topic modelling
Unified topics items such as customer name, issue names, product identifiers, people are defined as above.
6.3	Questions
Is BERTopic generating a topic even if there is only 1 document with e.g. rare product?
Can I control the hierarchy of the topics in advance?
What is in your opinion the easiest way to get the bi-/trigrams for quality, delivery, price, other issues?
7	Extension to the organization
This is just an idea from a sales director from another company:
Mapping the organization as hierarchy of topics
Reading the emails and appendices
Topic modelling the email bodies and the appendices
As an alternative: map the organization chart and the email traffic into a network such as networx (later to be converted eventually into pandas)
Adding to the network the relation between nodes as a list of topics

**Comment by MaartenGr** [comment]
@Ulrich-Buehlmann It is a rather extensive use case but I'll do my best to answer wherever possible and focus on the core of your use case.

> I would like to read all corporate documents of the last 12 months (around 10’000) and identify the topics (bad ones to stop bleeding and good ones for motivation). In parallel I would like to structure the topics into products, customers, suppliers, competitors, processes and link them to people. In my understanding these categories are all NERs, they are easy to identify by downloading from ERP / CRM / HR. Just running a standard topic modelling process might ignore some important customers of the past, coming products, key suppliers in case there are not many documents containing their identifiers (NERs).

Based on your use case, I would start as simple as possible and build up from there. Start from just a standard topic modeling process to get an idea of the topics that might be found in your data. The difficulty with integrating NER or semi-supervised modeling beforehand is that you must be very sure that these topics exist in that way. With NER, you are only considering the existence of an entity in a document, which is something entirely different from a topic. Thus, when you run a standard topic modeling process, you can then perform NER on top of that and explore topics across those entities. This would mean that for each document, you get a number of entities and you can explore which entities appear frequently with which topics. You can extend that with [topics per class](https://maartengr.github.io/BERTopic/getting_started/topicsperclass/topicsperclass.html) but for now it should also help you structure your questions. Then, if it fits, you can look into more specific techniques such as semi-supervised modeling but note that it will only nudge topics in a certain direction. 

> How do I make sure that the product XYA 180 which is mentioned only in one document gets “topiced” because the machine has to go by airfreight to Brazil?
> Is BERTopic generating a topic even if there is only 1 document with e.g. rare product?

The difficulty here is that a single document would not necessarily constitute an entire topic but merely an instance of what might be a topic. Typically, it is the culmination of documents so modeling a single document is likely to get you bad results.

**Comment by Ulrich-Buehlmann** [comment]
Sorry had to abstract some industry specific names

1 Your questions
Could you explain a bit more about the reason for integrating NER and lemmatization?
Unify customer and product names, standardize issue names. I never saw these name unified in any company so far.
NER, for example, is used to find out whether something is an entity. So let's say you have a NER algorithm, what exactly do you intend to do with it with respect to topic modeling?
Having all unified NERs as part of the topics in case they exist in at least document.
In a perfect world, how would you like to see the documents processed in BERTopic? Could you give an example?
There is a example from my last project below
2 Background
Since 30+ years I turnaround companies and manufacturing plants by generating liquidity and growth, reducing cost and mainly by motivation the employees for a change. So far, during the first 2 weeks I ran many interviews, checked out the figures and formulated assumptions (topics). Then the clean-up starts. Later we stabilize the organization and then grow. The goal is identifying loss driving products, loss driving customers, inefficient processes and then stop the bleeding.
This all is experience and financial figures driven but I am never sure if I ignore a hidden problems (topic) just because nobody tells me, or everybody assumes I already know it.
If you like to know more, I send you a copy of my turn around book.
3 New approach
I would like to read all corporate documents of the last 12 months (around 10’000) and identify the topics (bad ones to stop bleeding and good ones for motivation). In parallel I would like to structure the topics into products, customers, suppliers, competitors, processes and link them to people. In my understanding these categories are all NERs, they are easy to identify by downloading from ERP / CRM / HR. Just running a standard topic modelling process might ignore some important customers of the past, coming products, key suppliers in case there are not many documents containing their identifiers (NERs). 
Somebody in your team advised me to apply semi-supervised topic modelling. After reading the docs I can see 2 approaches:
4 Data
Nomenclature: “_” is the topic element separator as in BERTopic, “-“ connects 2 tokens, “ “ is space
Customers:
* Namé, Name, Name GmbH
* Longy
Products:
* XYZ 360, XYZ360, XYZ-360
* XYZ-180, XYZ 180
* XYA 540
Quality issues:
* Production output too low, sealing not gasproof, bad sealing, label in wrong position
Delivery issues:
* Shipping late, shipment late, delivery too late
Pricing issues:
* Price too low, price increase not implemented, gross profit too low (that’s tough to track, maybe later)
5 Post process (after standard BERTopic run)
5.1 BERTopic output
I constructed some possible topics:
* XYZ360_Namé_delivery_late
* XYZ_360_Name_shipping_late_GmbH
* XYZ-360_bad_sealing
* Longy_price_too_low
* Longy_too_pricies_low
* Longy_price_increase_not_implemented
* XYA_production_output_540_low
5.2 Unify customer and product names
Looks like a regex job which I don’t really like but it is feasible
* XYZ360_Name_delivery_late
* XYZ360_Name_shipping_late
* XYZ360_bad_sealing
* Longy_price_too_low
* Longy_too_pricies_low
* Longy_price_increase_not_implemented
* XYA540_production_output_low
5.3 Unify issues
Looks like a proximity match / regex task
* XYZ360_Name_delivery-late
* XYZ360_Name_delivery-late
* XYZ360_bad-sealing
* Longy_price-too-low
* Longy_price-too-low
* XYA540_production-output-too-low
5.4 Questions
* How do I make sure that the product XYA 180 which is mentioned only in one document gets “topiced” because the machine has to go by airfreight to Brazil?
* Any better ideas than regex?
* What about NER for customers and products?
6 Preprocess and semi-supervised BERTopic run
6.1 Prepare corpus
* Unify and generate all customer NERs, product NERS, (if feasible also issue NERs) in all documents
* Lemmatize the corpus (because there are not many documents ~10’000)
* Process all docs to identify all NERs and allocate them to the document as given topic elements
Example: 
doc4711;Name;Longy;price-too-low
doc4712;Panzani;XYZ360;production-output-too-low
doc4713;bad-sealing ; XYZ360
6.2 Run a semi-supervised topic modelling
Unified topics items such as customer name, issue names, product identifiers, people are defined as above.
6.3 Questions
Is BERTopic generating a topic even if there is only 1 document with e.g. rare product?
Can I control the hierarchy of the topics in advance?
What is in your opinion the easiest way to get the bi-/trigrams for quality, delivery, price, other issues?
7 Extension to the organization
This is just an idea from a sales director from another company:
Mapping the organization as hierarchy of topics
Reading the emails and appendices
Topic modelling the email bodies and the appendices
As an alternative: map the organization chart and the email traffic into a network such as networx (later to be converted eventually into pandas)
Adding to the network the relation between nodes as a list of topics
 
 
 
-----Original Message-----
