### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by AIGyan** [MaartenGr/BERTopic#73]
Hi I am unable to install , getting the following error.  Any suggestion please.

ERROR: running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.6
  creating build/lib.linux-x86_64-3.6/sentencepiece
  copying src/sentencepiece/__init__.py -> build/lib.linux-x86_64-3.6/sentencepiece
  copying src/sentencepiece/sentencepiece_model_pb2.py -> build/lib.linux-x86_64-3.6/sentencepiece
  copying src/sentencepiece/sentencepiece_pb2.py -> build/lib.linux-x86_64-3.6/sentencepiece
  running build_ext
  Package sentencepiece was not found in the pkg-config search path.
  Perhaps you should add the directory containing `sentencepiece.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'sentencepiece' found
  Cloning into 'sentencepiece'...
  fatal: unable to access 'https://github.com/google/sentencepiece.git/': Could not resolve host: github.com; Name or service not known
  Cloning into 'sentencepiece'...
  fatal: unable to access 'https://github.com/google/sentencepiece.git/': Could not resolve host: github.com; Name or service not known

**Comment by MaartenGr** [comment]
This seems like an issue with your internet connection. Have you tried installing BERTopic in a fresh environment?
