### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'cachedir'

### ISSUE THREAD

**Issue by kannaxp-git** [MaartenGr/BERTopic#731]
Getting the "TypeError: __init__() got an unexpected keyword argument 'cachedir'" when improting bertopic

*******************************
TypeError                                 Traceback (most recent call last)
Cell In [3], line 1
----> 1 import bertopic

File c:\Users\kach\Documents\GitHub\BERT_Topic_Modeling\venv_btm\lib\site-packages\bertopic\__init__.py:1
----> 1 from bertopic._bertopic import BERTopic
      3 __version__ = "0.12.0"
      5 __all__ = [
      6     "BERTopic",
      7 ]

File c:\Users\kach\Documents\GitHub\BERT_Topic_Modeling\venv_btm\lib\site-packages\bertopic\_bertopic.py:23
     20 from typing import List, Tuple, Union, Mapping, Any, Callable, Iterable
     22 # Models
---> 23 import hdbscan
     24 from umap import UMAP
     25 from sklearn.preprocessing import normalize

File c:\Users\kach\Documents\GitHub\BERT_Topic_Modeling\venv_btm\lib\site-packages\hdbscan\__init__.py:1
----> 1 from .hdbscan_ import HDBSCAN, hdbscan
      2 from .robust_single_linkage_ import RobustSingleLinkage, robust_single_linkage
      3 from .validity import validity_index

File c:\Users\kach\Documents\GitHub\BERT_Topic_Modeling\venv_btm\lib\site-packages\hdbscan\hdbscan_.py:509
...
    672 	   Density-based Cluster Selection. arxiv preprint 1911.02282.
    673     """
    674     if min_samples is None:

TypeError: __init__() got an unexpected keyword argument 'cachedir'

********************************

**Comment by MaartenGr** [comment]
This a known issue for which you can find a fix [here](https://github.com/MaartenGr/BERTopic/issues/730). It is due to an update of joblib which was not yet accounted for in HDBSCAN.

**Comment by MaartenGr** [comment]
Closing this in favor of the pinned issue as mentioned in the link above.
