### ISSUE TITLE
Not able to get probabilities with cuml HDBSCAN

### ISSUE THREAD

**Issue by shenghexu** [MaartenGr/BERTopic#732]
I'm running BERTopic with millions of documents and trying to reduce outliers by re-assignment with the probabilities. 
After running
`umap_model = UMAP(n_components=5, n_neighbors=15, min_dist=0.0)
hdbscan_model = HDBSCAN(min_samples=10, gen_min_span_tree=True)
topic_model = BERTopic(umap_model=umap_model, hdbscan_model=hdbscan_model,calculate_probabilities=True,verbose=True)
topics, probs = topic_model.fit_transform(data_lemmatized)`
the probs returned is `None`. I also checked `topic_model.hdbscan_model.probabilities_` but it's a 1-dimensional vector. 

Is there any way to get the probabilities with the cuml models?

**Comment by MaartenGr** [comment]
At the time of writing the code for extracting the probabilities, the cuml-version of HDBSCAN did not yet support extracting the 2-dimensional probabilities. Having said that, they have been working hard on supporting that feature. There are still some things to figure out though so it might take some time before it is fully compatible with BERTopic.

**Comment by shenghexu** [comment]
Thanks! Looking forward to the feature support.

**Comment by shenghexu** [comment]
I think an alternative is to train the model on GPU then transfer it to the CPU version of UMAP and HDBSCAN to calculate the probabilities in parallel. Is there any way to do that? Thanks.

**Comment by MaartenGr** [comment]
I do not think the models are easily exchangeable since their architecture, from a GPU vs. CPU standpoint, is rather different. Moreover, since they are different packages, I can imagine it would not be possible to train with one package and load it with another. They are making impressive steps though with the support for extracting probabilities and several other features 😄 

P.s. a nice summary of the work that has been done can be found [here](https://github.com/MaartenGr/BERTopic/issues/733#issuecomment-1253930743).

**Comment by rubypnchl** [comment]
I am also using cuml version of BERTopic and sadly, not getting probabilities. Is there any way to extract more than 30 words on the topic? As I have to find some kind of associations among topics. For e.g., common words in two topics or a number of documents having some common discussion about two or more two topics/words). This is possible either by calculating the probabilities or the way to extract more than 30 words for a topic but as I can see, these both things are not possible at present. 

If I use BERTopic without cuml and setting calculate_probabilities=True, it takes ages to compute the topics. For e.g., for 0.1million abstracts, I kept running my code for more than 30 hrs and there were no results later on, kernel dies.

Any help is much appreciated!

**Comment by MaartenGr** [comment]
> Is there any way to extract more than 30 words on the topic?

In the latest version of BERTopic, you can access the c-TF-IDF matrix with `topic_model.c_tf_idf_`. That way, you will have the topic-term matrix and can extract the number of words you want per each topic. To access the words themselves, you can use `topic_model.vectorizer_model.get_feature_names_out()`  or `topic_model.vectorizer_model.get_feature_names_out()`. 

> As I have to find some kind of associations among topics. For e.g., common words in two topics or a number of documents having some common discussion about two or more two topics/words). 

You can use the c-TF-IDF matrix (`topic_model.c_tf_idf_`) to extract common and important words across topics or re-calculate the document frequency matrix if you are interested in only the co-occurrence matrix:

```python
documents = pd.DataFrame({"Document": docs,
                          "ID": range(len(docs)),
                          "Topic": topic_mode.topics_})
documents_per_topic = documents.groupby(['Topic'], as_index=False).agg({'Document': ' '.join})
bow = topic_model.vectorizer_model.transform(documents)
```

**Comment by rubypnchl** [comment]
> > Is there any way to extract more than 30 words on the topic?
> 
> In the latest version of BERTopic, you can access the c-TF-IDF matrix with `topic_model.c_tf_idf_`. That way, you will have the topic-term matrix and can extract the number of words you want per each topic. To access the words themselves, you can use `topic_model.vectorizer_model.get_feature_names_out()` or `topic_model.vectorizer_model.get_feature_names_out()`.
> 
> > As I have to find some kind of associations among topics. For e.g., common words in two topics or a number of documents having some common discussion about two or more two topics/words).
> 
> You can use the c-TF-IDF matrix (`topic_model.c_tf_idf_`) to extract common and important words across topics or re-calculate the document frequency matrix if you are interested in only the co-occurrence matrix:
> 
> ```python
> documents = pd.DataFrame({"Document": docs,
>                           "ID": range(len(docs)),
>                           "Topic": topic_mode.topics_})
> documents_per_topic = documents.groupby(['Topic'], as_index=False).agg({'Document': ' '.join})
> bow = topic_model.vectorizer_model.transform(documents)
> ```

Thank you so much! I will try it now only and am also interested to know about the availability of cuml-based HDBSCAN with calculate_probabilities=True feature access. I mean, when will it be available, if someone is interested to utilise that feature.

**Comment by MaartenGr** [comment]
There are still some things to figure out with respect to an in-place replacement of HDBSCAN with that of cuML but I cannot say exactly when and if that will be implemented.

**Comment by shashankgaur3** [comment]
I am facing a similar issue using cuml, fit_transform doesn't return the probabilities, and transform methods error out with Predict function missing for cuml.hdbscan_model object, I use the below code to score new docs:

`from bertopic import BERTopic
from cuml.cluster import HDBSCAN
from cuml.manifold import UMAP
from cuml.cluster.hdbscan.prediction import approximate_predict

cu_topic_model = BERTopic(calculate_probabilities=True,umap_model=umap_model, hdbscan_model=hdbscan_model)
cu_topics, cu_probs = cu_topic_model.fit_transform(docs)

Topic_info_df = cu_topics.get_topic_info()

embeddings = cu_topic_model._extract_embeddings(new_docs,
                                                  method="document",
                                                  verbose=cu_topic_model.verbose)

umap_embeddings = cu_topic_model.umap_model.transform(embeddings)

# approximate_predict will return two series objects, one with the topic ID with the highest prob for the document and the other with the prob score of the topic
cu_topic_score, cu_probs_score = approximate_predict(cu_topic_model.hdbscan_model, umap_embeddings)

`

**Comment by MaartenGr** [comment]
With the newest release of BERTopic, v0.13, probabilities with cuML are now supported. So I'll be closing this issue for now. Feel free to reach out if you want to continue the discussion or re-open the issue.
