### ISSUE TITLE
About the optimal number of topics

### ISSUE THREAD

**Issue by JJery-web** [MaartenGr/BERTopic#735]
Thank you very much for developing this project.

I have a question. Previously, the LDA model can determine the optimal number of topics through the **perplexity**. How does Berttopic implement this function? That is how I determine the best number of topics.

Looking forward to your reply!
Thanks.

**Comment by JJery-web** [comment]
I have another question. Can BERTopic analyze the distribution probability of each topic in a document? For example, there are five topics, and BERTopic is used to predict the **probability distribution** of a document on five topics. I know it can be implemented in LDA.
I'm sorry to bother you again.

**Comment by MaartenGr** [comment]
> I have a question. Previously, the LDA model can determine the optimal number of topics through the perplexity. How does Berttopic implement this function? That is how I determine the best number of topics.

The difficulty with evaluation metrics is that many of them are merely proxies of a topic model's performance. With topic modeling, there is no ground truth and as such evaluating the model from a mathematical perspective becomes quite difficult. As such, no evaluation metrics are implemented in BERTopic as many are specific to certain use cases. Having said that, there are a number of evaluation metrics that you can use in [OCTIS](https://github.com/MIND-Lab/OCTIS). 

> I have another question. Can BERTopic analyze the distribution probability of each topic in a document? For example, there are five topics, and BERTopic is used to predict the probability distribution of a document on five topics. I know it can be implemented in LDA.

When you set `calculate_probabilities=True`, you can get the distribution probability of each topic in a document with `topic_model.probabilities_`.

**Comment by MaartenGr** [comment]
Due to inactivity, I'll be closing this issue for now. Feel free to reach out if you want to continue this discussion or re-open the issue!
