### ISSUE TITLE
KeyError in Classification usage

### ISSUE THREAD

**Issue by MatteoSchifano** [MaartenGr/BERTopic#736]
```
from bertopic import BERTopic
import pandas as pd
df = pd.read_csv('../data/dati.csv').dropna().reset_index(drop=True)

X = df.docs 
y = df.codice

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

topic_model = BERTopic()
topic_model.fit(X_train, y=y_train)
```
After that i'm getting a keyerror exception.

Output exceeds the [size limit](command:workbench.action.openSettings?[). Open the full output data [in a text editor](command:workbench.action.openLargeOutput?aad4310f-5ed2-4a99-9573-3114b0760aa1)
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
File c:\Users\Matteo\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\indexes\base.py:3361, in Index.get_loc(self, key, method, tolerance)
   3360 try:
-> 3361     return self._engine.get_loc(casted_key)
   3362 except KeyError as err:

File c:\Users\Matteo\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\_libs\index.pyx:76, in pandas._libs.index.IndexEngine.get_loc()

File c:\Users\Matteo\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\_libs\index.pyx:108, in pandas._libs.index.IndexEngine.get_loc()

File pandas\_libs\hashtable_class_helper.pxi:2131, in pandas._libs.hashtable.Int64HashTable.get_item()

File pandas\_libs\hashtable_class_helper.pxi:2140, in pandas._libs.hashtable.Int64HashTable.get_item()

KeyError: 576

The above exception was the direct cause of the following exception:

KeyError                                  Traceback (most recent call last)
c:\Users\Matteo\Documents\Python Scripts\CustomerServiceAnalysis\notebook\notebook copy.ipynb Cella 8 in <cell line: 2>()
      [1](vscode-notebook-cell:/c%3A/Users/Matteo/Documents/Python%20Scripts/CustomerServiceAnalysis/notebook/notebook%20copy.ipynb#X10sZmlsZQ%3D%3D?line=0) topic_model = BERTopic()
----> [2](vscode-notebook-cell:/c%3A/Users/Matteo/Documents/Python%20Scripts/CustomerServiceAnalysis/notebook/notebook%20copy.ipynb#X10sZmlsZQ%3D%3D?line=1) topic_model.fit(X_train)

File c:\Users\Matteo\AppData\Local\Programs\Python\Python310\lib\site-packages\bertopic\_bertopic.py:237, in BERTopic.fit(self, documents, embeddings, y)
...
-> 3363         raise KeyError(key) from err
   3365 if is_scalar(key) and isna(key) and not self.hasnans:
   3366     raise KeyError(key)

KeyError: 576

**Comment by MaartenGr** [comment]
Although I am not entirely sure, it might be worthwhile to make sure that the X and y variables you pass to BERTopic are flat lists and not pandas series. More specifically, there is some of the error message missing which makes it difficult to understand where the error is exactly coming from.

**Comment by MatteoSchifano** [comment]
Thanks you, with flat lists it works.
