### ISSUE TITLE
Saved/ pickeled topic_model.transform(XXX) giving inconsistent results

### ISSUE THREAD

**Issue by hubgitadi** [MaartenGr/BERTopic#746]
Hi Maarten,

I have saved my topic_model using pickle and using it to predict topics on a new text/ document. I am not getting consistent results whenever I use topic_model.transform(XXX) on a new text, sometimes I get topic number as -1 or sometimes I get the correct topic number.

I understand the the randomness in the UMAP but will it also impact the saved model? Isn't the saved model should give us the consistent results on a new text? 

Thank you in advance.

-- hubgitadi

**Comment by MaartenGr** [comment]
Yes, the model remains stochastic and saving/loading the model does not chance that. Instead, I would advise using the `random_state` in UMAP to make sure it always generates the same output.

**Comment by hubgitadi** [comment]
Thank you for your suggestion, let me take that approach only.

**Comment by MaartenGr** [comment]
Due to inactivity, I'll be closing this issue for now. Feel free to reach out if you want to continue this discussion or re-open the issue!
