### ISSUE TITLE
Words glued together and min_df parameter

### ISSUE THREAD

**Issue by LeoPerelli** [MaartenGr/BERTopic#752]
Hi, thanks for the wonderful repo. I have a few questions:

1) I have been experiencing an annoying issue in which topics have representations that contain glued words. For example:

`2_moreoffers_more_offers`

From my understanding, this happens due to the vectorizer, for example when there are punctuations or stop words in between the 2 words. But still I dont get why they get merged in a single word rather than being split. This is quite frequent on my dataset and produces poorly readable results and might also influence the topic representations vector (what is the BERT embedding for "moreoffers"?is it similiar to that of "more" and "offers"?). It is difficult to get rid of these words as specifying min_df=2 will not always be enough, and could also lead to min_df > max_df errors.

2) The count vectorizer is applied to all topics together or topic by topic?

3) I had a topic with 50 documents that all contained the word "taxi". Then, there were 3 documents that did not contain it. By setting the min_df=0.01, the topic representation completely ignores "taxi", whereas before it was the word with highest c-tf-idf. How is this possible? Shouldn't min_df remove infrequent words, for example the ones in the 3 documents?

Thanks a lot!

**Comment by MaartenGr** [comment]
> I have been experiencing an annoying issue in which topics have representations that contain glued words. For example:

It is difficult to state what exactly is happening there without looking at the documents that you have used. Moreover, it also depends on how you are using BERTopic and its parameters. Having said that, the vectorizers should typically make sure they are not merged together as the default should keep spaces between them. It might be helpful looking at your documents where those words appear to see why they are being merged together. Could you also share your exact code for fitting your model? 

What you can also do is setting the `diversity` parameter to make sure that duplicates do not wind up in the topic descriptions. 

> The count vectorizer is applied to all topics together or topic by topic?

The vectorizer is applied to each topic individually after the documents in a topic are combined. 

> I had a topic with 50 documents that all contained the word "taxi". Then, there were 3 documents that did not contain it. By setting the min_df=0.01, the topic representation completely ignores "taxi", whereas before it was the word with highest c-tf-idf. How is this possible? Shouldn't min_df remove infrequent words, for example the ones in the 3 documents?

Without seeing the exact data this is difficult to answer but it might have to do with the distribution of words within that topic. If there are thousands of words there and taxi appears in each document but only once, then it does not appear relatively often.

**Comment by LeoPerelli** [comment]
Thanks for answering! Could it happen when the docs dont end with punctuation? When they are merged together, is there some white space only? Unfortunately even with diversity 1.0 the glued words continue to appear.

Unfortunately I cannot share the data here as the dataset is not public, but "taxi" is by far the most common word in the topic and does not appear in the other topics. I dont get how raising the min_df from 0 to 0.01 removes the most frequent word from the topic representation instead of removing the most uncommon. If this really sounds strange to you too I can provide some statistics of the topic by running the tokeniser on this topic only or whatever you think could help you better understand the issue!

**Comment by MaartenGr** [comment]
> Thanks for answering! Could it happen when the docs dont end with punctuation? When they are merged together, is there some white space only? Unfortunately even with diversity 1.0 the glued words continue to appear.

Something like this could happen in an early version of BERTopic but has been removed a while ago. Making sure that you have the newest version (v0.12) should prevent this from happening. 

>  I dont get how raising the min_df from 0 to 0.01 removes the most frequent word from the topic representation instead of removing the most uncommon.

Even if the word `taxi` appears in every document, it might not be a word that actually appears frequently if each document contains thousands of words. A bag-of-words approach merely counts how often certain words appear across all documents. So it might be worthwhile to check the bag-of-words representation and see the absolute value of the word `taxi`. 

Could you also share your exact code for training the model? It is difficult to see what is happening here without either code or data.

**Comment by LeoPerelli** [comment]
Hi Maarten, thanks for your support. I include my training script and confirm that my bertopic is the updated version.
```
best_hyperparams = {'min_cluster_size': 8, 'n_components': 296, 'n_neighbors': 73} #maximized topic coherence
from sklearn.feature_extraction.text import CountVectorizer
from umap import UMAP
from hdbscan import HDBSCAN
from bertopic import BERTopic
import numpy as np

count_vectorizer = CountVectorizer(ngram_range=(1, 3), stop_words="english") #min_df = 0.01

umap_model = UMAP(
    n_neighbors=best_hyperparams["n_neighbors"],
    n_components=best_hyperparams["n_components"],
    min_dist=0.0,
    metric="cosine",
)
hdbscan_model = HDBSCAN(
    min_cluster_size=best_hyperparams["min_cluster_size"],
    min_samples=1,
    metric="euclidean",
    cluster_selection_method="eom",
    prediction_data=True,
)
topic_model = BERTopic(
    vectorizer_model=count_vectorizer,
    umap_model=umap_model,
    hdbscan_model=hdbscan_model,
    calculate_probabilities=True,
    diversity=1.0,
)
topics, probs = topic_model.fit_transform(docs, embeddings=embeddings)
```

Take a look at this cluster, which has the following representation:
```
37_noughtnought_noughtnought noughtnought_noug...
```

The documents for this cluster are:

```
'nought.nought', 'nought.Nothing', 'nought.nought',
       'nought.nothing to change', 'nought.Is there no',
       'nought.No information', 'nought.nought', 'nought.nought',
       'nought.nought', 'nought.nought', 'nought.nought',
       'nought.So leave', 'nought.nought', 'nought.nought',
       'nought.Is there no', 'nought.Is there no', 'nought.nought',
       'nought.nought', 'nought.There is nothing', 'nought.nought',
       'nought.nought', 'nought.nought', 'nought.nought', 'nought.nought',
       'nought.nought', 'nought.nought', 'nought.nought',
       'nought.No information', 'nought.nought', 'nought.nought',
       'nought.Not necessary', 'nought.nought', 'nought.nought',
       'nought.nought', 'nought.nought', 'nought.nought', 'nought.nought',
       'nought.nought', 'nought.nought', 'nought.nought', 'nought.nought',
       'nought.nought', 'nought.Nivhts', 'nought.nought', 'nought.nought',
       'nought.nought', 'nought.nought', 'nought.nought', 'nought.nought',
       'nought.nought', 'nought.nought', 'nought.nought',
       'nought.No information', 'nought.nought', 'nought.nought',
       'nought.nought', 'nought.nought', 'nought.nought', 'nought.nought',
       'nought.nought', 'nought.nought', 'nought.nought',
       'nought.Ok so far', 'nought.nought', 'nought.nothing to write',
       'nought.nought', 'nought.nought', 'nought.nought', 'nought.nought',
       'nought.nought', 'nought.nought', 'nought.Unnecessarily',
       'nought.nought', 'nought.nought', 'nought.nought', 'nought.nought',
       'nought.nought', 'nought.nought', 'nought.nought', 'nought.nought',
       'nought.nought', 'nought.Nothing ^^', 'nought.nought',
       'nought.nought', 'nought.nought', 'nought.nought', 'nought.nought',
       'nought.nought', 'nought.nought', 'nought.nought', 'nought.nought',
       'nought.Let it be', 'nought.nought', 'nought.nought',
       'nought.NotD', 'nought.nought', 'nought.Does not exist',
       'nought.nought', 'nought.nought', 'nought.nought', 'nought.nought',
       'nought.nought', 'nought.nought', 'nought.nought', 'nought.nought',
       'nought.nought', 'nought.nought', 'nought.Is there no',
       'nought.nought', 'nought.nought', 'nought.No idea.',
       'nought.nought', 'nought.nought', 'nought.nought', 'nought.nought',
       'nought.nought', 'nought.satisfied', 'nought.nought',
       'nought.nought', 'nought.nought', 'nought.nought', 'nought.nought',
       'nought.nought', 'nought.nought', 'nought.nought', 'nought.nought',
       'nought.nought', 'nought.nought', 'nought.nought', 'nought.nought',
       'nought.nought', 'nought.nought', 'nought.nought', 'nought.nought',
       'no.nought', 'nought.nought', 'nought.nought', 'spelling.nought',
       'nought.nought', 'nought.Does not make sense', 'nought.nought',
       'nought.nought', 'nought.nought', 'nought.nought', 'nought.nought',
       'nought.nought', 'nought.nought', 'nought.nought',
       'nought.No need', 'nought.nought', 'nought.nought',
       'nought.nought', 'nought.nought', 'nought.nought', 'nought.Not',
       'nought.nought', 'nought.nought', 'nought.nought', 'nought.nought',
       'nought.nought', 'nought.nought', 'nought.nought', 'nought.nought',
       'nought.nought', 'nought.nought', 'nought.satisfied',
       'nought.nought', 'nought.nought', 'nought.nought', 'nought.nought',
       'nought.nought', 'nought.nought', 'nought.nought', 'nought.nought',
       'nought.nought', 'nought.nought', 'nought.nought', 'nought.nought',
       'nought.without words', 'nought.nought', 'nought.Just right',
       'nought.nought', 'nought.nothing', 'nought.nought',
       'nought.nought', 'nought.nought', 'nought.nought', 'nought.nought',
       'nought.nought', 'nought.nought', 'nought.nought', 'nought.nought',
       'nought.nought', 'nought.nought', 'nought.nought', 'nought.nought',
       'nought.nought', 'nought.nought', 'nought.good',
       'nought.there is no', 'nought.nought', 'nought.nought',
       'nought.nought', 'nought.nought', 'nought.nought', 'nought.nought',
       'nought.nought', 'nought.nought', 'nought.nought',
       'nought.Nothing', 'nought.nought', 'nought.nought',
       'nought.nought', 'nought.nought', 'nought.nought',
       'nought.Nothing...', 'nought.nought', 'nought.nought',
       'nought.nought', 'nought.nought', 'nought.nought', 'nought.nought',
       'nought.Not necessary', 'nought.n7chtD7', 'nought.nought',
       'nought.nought', 'nought.nought', 'nought.Is there no',
       'nought.nought', 'nought.nought', 'nought.No need',
       'nought.nought', 'nought.nought', 'nought.nought', 'nought.nought',
       'nought.nothing', 'nought.nought', 'nought.nothing',
       'nought.nought', 'nought.nought', 'nought.nought', 'nought.nought',
       'nought.nought', 'nought.nought', 'nought.nought', 'nought.nought',
       'nought.see above', 'nought.nought', 'nought.nought',
       'nought.No suggestions', 'nought.nought', 'nought.thanks',
       'nought.nought', 'nought.nought', 'nought.nought', 'nought.Not',
       'nought.nought', 'nought.nought', 'nought.nought', 'nought.nought',
       'nought.nought', 'nought.nought', 'nought.nought', 'nought.nought',
       'nought.nought', 'nought.nought', 'nought.nought', 'nought.nought'
```

While no document includes the words "noughtnought" or "noughtnought noughtnought", they end up being the words with the highest c-tf-idf. I suspect there must be something strange happening with the tokeniser somewhere gluing words together.
If I update the topic representation by setting min_df=0.2, the topic representation becomes:

```
37_necessary_information_exist_make sense
```

I dont get how raising the min_df actually shows only the least common words in the topic representation.

**Comment by MaartenGr** [comment]
It took some time to figure out but it seems that it is not related to the CountVectorizer but is an edge case when preprocessing the documents according to:

https://github.com/MaartenGr/BERTopic/blob/09c1732997f838050c263ad00ad3c9474e816863/bertopic/_bertopic.py#L2796

It does this as a default for those who use the default parameters but is an edge-case when you combine custom embeddings but leave the embedding model as is. It should be solved with:

```python
topic_model = BERTopic(
    embedding_model=my_embedding_model,  # Pass your embedding model here! 
    vectorizer_model=count_vectorizer,
    umap_model=umap_model,
    hdbscan_model=hdbscan_model,
    calculate_probabilities=True,
    diversity=1.0,
)

**Comment by LeoPerelli** [comment]
Hi Maarten, thanks so much! I had nailed down the bug to a problem when words have punctuation in between without spaces, such as "hello,goodbye" instead of "hello, goodbye" or "hello ,goodbye". In such cases, they would end up being glued. Seems that the regex handled exactly this, hence I guess this one is solved! Probably makes sense to update the documentation too, for example specify this here: https://maartengr.github.io/BERTopic/getting_started/embeddings/embeddings.html#custom-embeddings

**Comment by MaartenGr** [comment]
Glad to hear that it worked out! I might just change some of the internal structure to account for this instead of adding it to the documentation but I'll have to figure out the best way in doing so as there are quite some interactions going on there. 

> As last question, does the min_df question make sense to you? I still see this issue of raising min_df and common words disappearing instead of the rare ones, for example in the cluster with the docs I posted above.

Do note that the CountVectorizer is only part of the formula. After having created the bag-of-words representation, the c-TF-IDF is calculated from that bag-of-words. Meaning that if the bag-of-words gets updated, so does the c-TF-IDF. It might be so that the distribution of the words in your topics has changed in such a way that it now better recognizes common words and give them lower IDF values.
