### ISSUE TITLE
reduce_topics() missing 1 required positional argument: 'topics'

### ISSUE THREAD

**Issue by Alla-Abdella** [MaartenGr/BERTopic#756]
Code: 
topic_model.reduce_topics(docs, nt_topics = 30) 

Error:
TypeError: reduce_topics() missing 1 required positional argument: 'topics'

**Comment by MaartenGr** [comment]
That parameter was removed in BERTopic v0.12. I believe your issue should be fixed when upgrading BERTopic to its newest version.

**Comment by alla15747** [comment]
Thank you, Maarten. 
Unfortunately, the only version allowed on our work system is bertopic v0.11.0. 
Is there any other recommended solution?

**Comment by alla15747** [comment]
Thanks Maarten, I upgraded it and it works successfully.
