### ISSUE TITLE
Bug in reduce_topics

### ISSUE THREAD

**Issue by emzy013** [MaartenGr/BERTopic#757]
When reduce_topics happens to reduce the -1 outlier group into another topic group, the model.probabilities_ are not updated and the documents are not remapped to the merged topics.

**Comment by MaartenGr** [comment]
Could you provide a minimal and reproducible example of the issue you are facing? That makes it a bit easier for me to see what the issue is, where it originates, and how to potentially fix it.

**Comment by MaartenGr** [comment]
Due to inactivity, I'll be closing this issue for now. Feel free to reach out if you want to continue this discussion or re-open the issue!
