### ISSUE TITLE
Visualization returned blank in jupyter notebook

### ISSUE THREAD

**Issue by PeggyFan** [MaartenGr/BERTopic#764]
Hi, I'm working in a jupyter notebook with a setting ```c.NotebookApp.iopub_data_rate_limit = 1000000```
The clusters from the model is not that big: ```topic_model.c_tf_idf_.shape``` gives ```(21, 14209)```

But when I tried the following nothing shows up:
```
topic_model.visualize_topics(top_n_topics=5)
topic_model.visualize_hierarchy()
topic_model.visualize_barchart()
```

Has anyone run into similar issues? I don't know if this is a jupyter notebook problem.

**Comment by keithcallenberg** [comment]
I am seeing this too. I additionally went through the other visualizations not listed here and they all returned a large blank output, and no errors.

![image](https://user-images.githubusercontent.com/999275/194403627-d2ce2453-b665-4d1c-a6dd-755fcc3d75f2.png)

jupyterlab==3.4.8
matplotlib==3.6.0
plotly==5.10.0

**Comment by keithcallenberg** [comment]
Google Chrome dev console shows this stacktrace:
```
Uncaught ReferenceError: require is not defined
    at <anonymous>:1:17
    at t.attachWidget (jlab_core.716b79be8019e5bdc801.js?v=716b79be8019e5bdc801:2:1589587)
    at t.insertWidget (jlab_core.716b79be8019e5bdc801.js?v=716b79be8019e5bdc801:2:1588938)
    at j._insertOutput (jlab_core.716b79be8019e5bdc801.js?v=716b79be8019e5bdc801:2:921537)
    at j.onModelChanged (jlab_core.716b79be8019e5bdc801.js?v=716b79be8019e5bdc801:2:918714)
    at m (jlab_core.716b79be8019e5bdc801.js?v=716b79be8019e5bdc801:2:1555589)
    at Object.l [as emit] (jlab_core.716b79be8019e5bdc801.js?v=716b79be8019e5bdc801:2:1555249)
    at e.emit (jlab_core.716b79be8019e5bdc801.js?v=716b79be8019e5bdc801:2:1553494)
    at c._onListChanged (jlab_core.716b79be8019e5bdc801.js?v=716b79be8019e5bdc801:2:915141)
    at m (jlab_core.716b79be8019e5bdc801.js?v=716b79be8019e5bdc801:2:1555589)
```
pointing to this line:
```
require(["plotly"], function(Plotly) { 
```

**Comment by keithcallenberg** [comment]
Actually, after refreshing the browser, plotly loaded correctly and all visualizations became functional for me. I think for me it was actually just a temporary networking issue where some javascript assets were not loading properly.

**Comment by MaartenGr** [comment]
@PeggyFan Typically, this is a problem with Plotly and Jupyter where one or the other needs some additional installs or when dependencies do not fully match. As you can see by the responses, it might even be a temporary networking issue. All in all, I would advise reading through the Plotly installation documentation [here](https://plotly.com/python/getting-started/) for some additional help.

**Comment by psyronika** [comment]
@PeggyFan I had this issue once and solved it by setting the plotly.io renderers to **iframe.**

`import plotly.io as pio`
`pio.renderers.default='iframe'`

**Comment by PeggyFan** [comment]
Thank you @psyronika it solved my issue.
Also thank you @keithcallenberg and @MaartenGr - next time I will know what to check.

**Comment by Ravi2712** [comment]
> 



> Actually, after refreshing the browser, plotly loaded correctly and all visualizations became functional for me. I think for me it was actually just a temporary networking issue where some javascript assets were not loading properly.

This worked for me! 👍

**Comment by kungmo** [comment]
> @PeggyFan I had this issue once and solved it by setting the plotly.io renderers to **iframe.**
> 
> `import plotly.io as pio` `pio.renderers.default='iframe'`

Your comment was a hint for me.

I am using jupytrlab 4.2.5, and this code worked.

**import plotly.io as pio
pio.renderers.default = "colab"** # 안 나오면 https://plotly.com/python/renderers/ 참조하여 렌더러 변경

topic_model.visualize_barchart(top_n_topics=len(topic_model.get_topic_info()))

**Comment by paudel54** [comment]
> [@PeggyFan](https://github.com/PeggyFan) I had this issue once and solved it by setting the plotly.io renderers to **iframe.**
> 
> `import plotly.io as pio` `pio.renderers.default='iframe'`

you saved my life thanks.. !!
