### ISSUE TITLE
problem with installing BERTopic (even with older version joblib)

### ISSUE THREAD

**Issue by tisRobin** [MaartenGr/BERTopic#770]
I referred to the stackoverflow post about how using the older version of joblib might do the trick, so I tried the following:

`
!pip install --upgrade joblib==1.1.0
`
`
!pip install bertopic
`
`
from bertopic import BERTopic
`

This still returned the same TypeError. 

`TypeError: __init__() got an unexpected keyword argument 'cachedir'`

Is there a solid solution regarding how to install and import BERTopic without having this error?  Or is something wrong with 
how I wrote the script above? I would appreciate it if I could receive some help on this matter.

**Comment by jasonzou0** [comment]
I have exactly the same issue.

**Comment by nsantiago2719** [comment]
Try installing BertTopic first before downgrading. 
```
!pip install BertTopic
!pip install --upgrade joblib=1.1.0 
```
That works for me at the moment, my hunch is when you install BertTopic it grabs the latest joblib version and upgrades the first one you installed.

**Comment by PiyushKyushu** [comment]
I tried installing joblib as suggested by nsantiago2719 but I am still getting 

> TypeError: __init__() got an unexpected keyword argument 'cachedir'  

Is there any other solution, it would be a great help.

**Comment by iamdank** [comment]
did you restart the kernel after reinstalling joblib?
that’s does the trick for me

**Comment by PiyushKyushu** [comment]
Working for me now after iamdank suggestion. 
Thanks a lots!

**Comment by MaartenGr** [comment]
@mayuripandey I think you need to restart the notebook after doing the pip install. Always make sure that whenever you do a `!pip install` that you restart the notebook before importing any packages. This is necessary as it will use the newest versions of the packages.

**Comment by mayuripandey** [comment]
I did, everything works fine, but while importing hdbscan, i get the same error :( @MaartenGr

**Comment by iamdank** [comment]
![546C1AE8-DCE4-4309-B748-37F82DEAD666](https://user-images.githubusercontent.com/68849237/196142619-4f8408cc-439f-4269-b165-1e9c9d13e4e9.jpeg)

this worked for me. perhaps try installing joblib after bertopic and hdbscan, then restart?

**Comment by iamdank** [comment]
![image](https://user-images.githubusercontent.com/68849237/196144189-d3d75ca8-320f-4623-b354-d0baf5aae629.png)

this works. joblib install after bertopic + hdbscan. then restart.

**Comment by mayuripandey** [comment]
Thank you, @iamdank it worked :)
