### ISSUE TITLE
Question: Is it possible to retrain the saved bertopic model with new data while maintaining the original topics and discovering new additional ones?

### ISSUE THREAD

**Issue by Alla-Abdella** [MaartenGr/BERTopic#771]
I applied a fit_transform() on 40K documents and found almost 56 topics that make sense and represent them. Now, I have a additional 10K documents added to the data. If I apply model.transform() on the new data, I will not discover any new topics that might come recently. 
My question:
I would like to keep the first 56 topics as they make sense and were derived from 40K documents, which is a good amount of data. The 10K documents may also yield some new topics, so I want to see if they do.  Is it possible to retrain the saved bertopic model using new additional data while maintaining the original topics and discovering new ones? Are there any other best practices you recommend using with Bertopic? I appreciate your support.

**Comment by ddenz** [comment]
I am also interested in the answer to this and would like to know if there is any way to do this for dynamic topic modelling. That is, I would like to see the evolution of existing topics over time and then as new data comes in, discover any new ones that might come up, while keeping the old ones. Is this somehow possible?

**Comment by MaartenGr** [comment]
After applying a regular `fit`, it is not possible to discover new topics. This is as a result of the underlying sequence of [algorithms](https://maartengr.github.io/BERTopic/algorithm/algorithm.html) that do not support online/incremental variants. However, you can use the online/incremental variant of BERTopic, with algorithms that support that, in order to add and discover new topics to a previously trained model. You can find more about that [here](https://maartengr.github.io/BERTopic/getting_started/online/online.html). 

You can also use this technique to update the model and generate new topics over time.

**Comment by alla15747** [comment]
Thank you so much Maarten for your answer, will try the partial_fit and it seems river package is needed to do the incremental learning.

**Comment by ddenz** [comment]
Thanks very much Maarten! Very helpful. I had one further small question,
if you don’t mind. The “frequency” of topics in the dynamic topic modelling
is in terms of number of documents, I assume…? I couldn’t find this
specified in the documentation (apologies if I missed it).
André

**Comment by MaartenGr** [comment]
@ddenz Yes, the frequency relates to the number of documents.

**Comment by ddenz** [comment]
Thanks so much Maarten.

I am trying the incremental approach you mention but am encountering an
issue. I am using TfIdfVectorizer (I don’t have access to a GPU) and am
getting the error saying that IncrementalPCA.partial_fit() doesn’t support
sparse input. It says to use fit() instead but how can I do this?

**Comment by MaartenGr** [comment]
@ddenz If you are using the TfidfVectorizer, you indeed will need to create a dense representation instead seeing as IncrementalPCA does not support sparse inputs. You can, for example, use TruncatedSVD to reduce the dimensionality to a few hundred dimensions first before feeding it to the IncrementalPCA model. That way, you will have a dense representation that the model can work with.

**Comment by Thiziri-Hafir** [comment]
Hello @MaartenGr  thank you for all these explanations. I m also interested in Online Topic Modeling. However, I just tested the documentation example (using the same data) but got the following error : 'shape' elements cannot be negative

**Comment by MaartenGr** [comment]
@Thiziri-Hafir Could you share your exact code and also the complete error message? Without it, it is difficult to help out and identify the issue.

**Comment by Thiziri-Hafir** [comment]
The example : 
`# Prepare documents
all_docs = fetch_20newsgroups(remove=('headers', 'footers', 'quotes'))["data"]
doc_chunks = [all_docs[i:i+1000] for i in range(0, len(all_docs), 1000)]

# Prepare sub-models that support online learning
umap_model = IncrementalPCA(n_components=5)
cluster_model = MiniBatchKMeans(n_clusters=50, random_state=0)
vectorizer_model = OnlineCountVectorizer(stop_words="english", decay=.01)


topic_model = BERTopic(umap_model=umap_model,
                       hdbscan_model=cluster_model,
                       vectorizer_model=vectorizer_model)

# Incrementally fit the topic model by training on 1000 documents at a time
for docs in data_chunks:
    topic_model.partial_fit(docs)`

The complete error message : 
![image](https://user-images.githubusercontent.com/72195389/196431724-ec9e4fc3-0686-497d-b20b-1d4202498c1e.png)

**Comment by ddenz** [comment]
Thanks very ouch Maarten. I have got that to work. But I am unsure how to
use the topics over time with the incremental processing. I may not have
explained what I wanted to do adequately.
I would like to view topics over time “in real time”. So at each date,
update the topic model and visualise the topics at each time step, rather
than at the end of all time steps. For examine, updating the topic model
and visualising the topics over time every day. Was that what you
understood and is this possible?

**Comment by MaartenGr** [comment]
@Thiziri-Hafir Based on your code, you might have changed the data input seeing as you are using `data_chunks` instead of `doc_chunks` which tells me that you are not using the exact example as shown in the documentation. More specifically, the following is working for me:

```python
from bertopic import BERTopic
from sklearn.datasets import fetch_20newsgroups
from sklearn.cluster import MiniBatchKMeans
from sklearn.decomposition import IncrementalPCA
from bertopic.vectorizers import OnlineCountVectorizer

all_docs = fetch_20newsgroups(remove=('headers', 'footers', 'quotes'))["data"]
doc_chunks = [all_docs[i:i+1000] for i in range(0, len(all_docs), 1000)]

umap_model = IncrementalPCA(n_components=5)
cluster_model = MiniBatchKMeans(n_clusters=50, random_state=0)
vectorizer_model = OnlineCountVectorizer(stop_words="english", decay=.01)

topic_model = BERTopic(umap_model=umap_model,
hdbscan_model=cluster_model,
vectorizer_model=vectorizer_model)

for docs in doc_chunks:
    topic_model.partial_fit(docs)
```

Could you try the above instead in a fresh environment? Hopefully, this should work.

**Comment by MaartenGr** [comment]
@ddenz What you can do is indeed update the topic model at each date using `.partial_fit`. Then, after each timestep, and not at the end of all timesteps, you can use `.topics_over_time` with the newly updated topic model. That way, you can update the topic model daily and update the visualization of topics over time every day. In pseudocode-ish, a single day would look something like this:

```python
# We make sure to track every topic thus far
topics = topic_model.topics_.copy()

# We update our model and track the new topics
topic_model.partial_fit(docs_from_today)
topics.extend(topic_model.topics_)
topic_model.topics_ = topics

# We re-calculate the topics over time with today's documents
docs = every_document_thus_far + docs_from_today
timestamps = every_timestamp_thus_far + timestamps_from_today
topics_over_time = topic_model.topics_over_time(docs, timestamps )
```

**Comment by Thiziri-Hafir** [comment]
Apologies @MaartenGr, that was a mistake on my part. Indeed, it works but not on my data, I will try to see what is wrong. Thank you!

**Comment by ddenz** [comment]
Thanks Maarten. That is what I ended up trying, but from what I gather it
defeats the purpose of incremental processing as the input is an ever
increasing historical collection of docs rather than just the latest batch
in each iteration. Does that make sense? I guess that is the only way to go
about it?

**Comment by MaartenGr** [comment]
@ddenz 

>  as the input is an ever increasing historical collection of docs rather than just the latest batch in each iteration. 

That is actually not the case here. You can use `.partial_fit` with the latest batch of data to update the model. The only place where you will not to make sure you keep track of all the documents is with calculating the topics over time.

**Comment by Krishika-Ragunathan** [comment]
Hi @MaartenGr I tried implementing the above steps. But I was not able to get new topics for my latest batch of data. Rather the new sets of data are getting updated in my existing topics. I appreciate your support.

**Comment by MaartenGr** [comment]
@Krishika-Ragunathan Which steps did you try out exactly? Did you follow along with the tutorial [here](https://maartengr.github.io/BERTopic/getting_started/online/online.html#river) and used River to find new topics?

**Comment by Krishika-Ragunathan** [comment]
Thank you so much Maarten for your answer, will try using River method.
