### ISSUE TITLE
Custom labels for hovertext in `visualize_documents()`

### ISSUE THREAD

**Issue by satyaborg** [MaartenGr/BERTopic#775]
Hi @MaartenGr,

First off -- BERTopic is simply a great library among all the NTM approaches thus far -- especially the extensive/user-friendly documentation, and active bugfixes. So, congrats!

Now for the "issue" -- is there appetite for custom labels in `hovertext` within the `visualize_documents(..)` function? My use case has mostly been news articles (in which case I want to display the article title only), and more recently, research papers from NeurIPS '21 (similarly, I wanted to display the title). I've already written an override for `visualize_documents(..)` that takes `hover_text_labels` as an additional argument for the same. Here's the [demo](https://satyaborg.com/assets/images/documentation/research-clustering/vis.html) (clustered with title + abstract; displays only `title`).

Happy to do a pull request should the community find it useful.

**Comment by MaartenGr** [comment]
Thank you for the kind words! That might indeed be an interesting feature. I will have to think about this a little bit more as this would also need to be implemented in `visualize_hierarchical_documents`. It definitely looks much nicer than showing a truncated piece of text. Also, as it stands now, I might truncate the hover_text_labels as a default seeing Plotly shows only a part of it.
