### ISSUE TITLE
from bertopic import BERTopic always running and cannot proceed next statement

### ISSUE THREAD

**Issue by chenhep** [MaartenGr/BERTopic#776]
Hi experts,

I installed joblib==1.1.0 and BERTopic==0.11.0 through conda.
But the program always running on the second line

print('test 1')
from bertopic import BERTopic
print('test 2')

The program cannot print test 2 in the terminal. 
That's strange for me. Anyone have the similar program? I need your help. Thanks.

The following packages are automatically installed when installing bertopic 
pytorch==1.10.2
torchvision==0.11.3
sentence-transformers==2.2.2 
transformers==4.23.0

**Comment by MaartenGr** [comment]
The import can take a minute or two depending on your machine due to the relative slow import of [UMAP](https://maartengr.github.io/BERTopic/faq.html#why-does-it-take-so-long-to-import-bertopic). If it still does not work after 10 minutes, there might be something going on with your environment. Starting from a completely fresh environment might help.

**Comment by chenhep** [comment]
Hi, Thanks for your infomation.

I bulided two virtual environments with same packages.
Unfortunately, import BERTopic still there after 10min.

> The import can take a minute or two depending on your machine due to the relative slow import of [UMAP](https://maartengr.github.io/BERTopic/faq.html#why-does-it-take-so-long-to-import-bertopic). If it still does not work after 10 minutes, there might be something going on with your environment. Starting from a completely fresh environment might help.

Hi, Thanks for your infomation.

I bulided two virtual environments with same packages.
Unfortunately, import BERTopic still there after 10min.

**Comment by chenhep** [comment]
> The import can take a minute or two depending on your machine due to the relative slow import of [UMAP](https://maartengr.github.io/BERTopic/faq.html#why-does-it-take-so-long-to-import-bertopic). If it still does not work after 10 minutes, there might be something going on with your environment. Starting from a completely fresh environment might help.

Does it relate to pytorch or transformers version?

**Comment by chenhep** [comment]
I find strange thing on the python console of pycharm as follows:

![dc9330cce75fa3e9d60131459ecccf0](https://user-images.githubusercontent.com/45805727/195486007-3c0f9efb-e556-4df2-83ed-fb7df9c09136.png)

It seems that from bertopic import BERTopic will cause something wrong for python interpreter.

**Comment by MaartenGr** [comment]
Could you try with python 3.8 instead? I remember that a package was better supported with 3.8 but I cannot remember which one. Also, could you share the code for creating the environment and installing BERTopic?

**Comment by chenhep** [comment]
> Could you try with python 3.8 instead? I remember that a package was better supported with 3.8 but I cannot remember which one. Also, could you share the code for creating the environment and installing BERTopic?

Hi, I installed bertopic in a new environment with python=3.8.5 as followed:

(base) C:\Windows\system32>conda create -n btopic python=3.8.5
(base) C:\Windows\system32>conda activate btopic
(btopic) C:\Windows\system32>conda install joblib==1.0.0
(btopic) C:\Windows\system32>conda install bertopic==0.11.0

The problem happened again.
(1) import BERTopic always running when running in .py file.
(2) BERTopic will cause something wrong for python interpreter on the python console of pycharm.

Bye the way, I use the CPU instead of GPU in my laptop computer.
Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz   2.30
16.0 GB  RAM
64bit windows

**Comment by MaartenGr** [comment]
Does it work outside of the python console of pycharm? If so, then there might be something going on with the connection between the created environment within pycharm and its console.

**Comment by chenhep** [comment]
> Does it work outside of the python console of pycharm? If so, then there might be something going on with the connection between the created environment within pycharm and its console.

It doesn't work outside of the python console of pycharm.

**Comment by MaartenGr** [comment]
Strange, then it seems to be related to how BERTopic was installed. Perhaps installing it through `pip` instead might solve your issue.

**Comment by chenhep** [comment]
> Strange, then it seems to be related to how BERTopic was installed. Perhaps installing it through `pip` instead might solve your issue.

I cannot install it through pip.  It show the problems like following.
![微信图片_20221026102617](https://user-images.githubusercontent.com/45805727/197920946-9bf23d2f-c830-4058-927e-6620df1a3a3b.png)

**Comment by MaartenGr** [comment]
If you install the build tools as mentioned in the error message and follow the link, it should be enough to install HDBSCAN.

**Comment by MaartenGr** [comment]
Due to inactivity, I'll be closing this issue for now. Feel free to reach out if you want to continue this discussion or re-open the issue!
