### ISSUE TITLE
Is it possible to create intertopic distance map in 3D?

### ISSUE THREAD

**Issue by ArtemBernatskyy** [MaartenGr/BERTopic#779]
Is it possible to create intertopic distance map in 3D with BERTopic or with low level libraries?
I've succeeded in created something similar but having troubles with displaying colors for clusters.
P.S. I'm new to ML and really a little bit lost.

Thank you!

that's the code that I've tried so far

```python
import numpy as np
from umap import UMAP
from bertopic import BERTopic
import plotly.graph_objects as go
from sklearn.preprocessing import MinMaxScaler


tweets = [...]

topic_model = BERTopic(
    min_topic_size=100,
    embedding_model="all-mpnet-base-v2",
    verbose=True,
)
topics, probs = topic_model.fit_transform(tweets)
topics = topics[:1000]

topic_list = sorted(topics)
words = [" | ".join([word[0] for word in topic_model.get_topic(topic)[:5]]) for topic in topic_list]

all_topics = sorted(list(topic_model.get_topics().keys()))
indices = np.array([all_topics.index(topic) for topic in topics])
embeddings = topic_model.c_tf_idf_.toarray()[indices]
embeddings = MinMaxScaler().fit_transform(embeddings)

u = UMAP(n_neighbors=15, n_components=3, metric='euclidean').fit_transform(embeddings)

fig = go.Figure(data=[go.Scatter3d(x=u[:, 0], y=u[:, 1], z=u[:, 2], hoverinfo="text", hovertext=words, mode='markers')])
fig.show()

```

<img width="597" alt="Captura de Pantalla 2022-10-13 a las 23 55 48" src="https://user-images.githubusercontent.com/13070119/195718290-a6881890-54d8-4fd8-907b-b5fb7c6fbb6d.png">

**Comment by MaartenGr** [comment]
This is mostly related to how Plotly works since you can select the coloring there. I would advise looking through [this](https://plotly.com/python/3d-scatter-plots/) where you can find some more information about 3D plots in Plotly.

**Comment by ArtemBernatskyy** [comment]
@MaartenGr thank you, but how can I access information about clusters?
I have no problem with display, but I have a problem with data, where to get info about clusters...

**Comment by MaartenGr** [comment]
What exactly do you mean with "clusters"? Do you refer to the topics? If so, then the `embeddings`  that you calculated represent a vector for each topic. As such, each individual point would then represent a cluster since you are plotting the topics and not individual tweets.

**Comment by ArtemBernatskyy** [comment]
Hm, now I see it, that makes sense, thank you!
