### ISSUE TITLE
large corpus issue. Always assign -1 topis

### ISSUE THREAD

**Issue by liangyuoutreach** [MaartenGr/BERTopic#78]
I tried to use dataset from the [link](https://github.com/yyeung-lam/earnings-call-text-mining/tree/master/ndefault)

The dataset is related to earning call transcripts.

With current method, it only gets top 30 words.

When i directly apply the method you provided, always assign -1 topic.

With traditional tf-idf LDA method, it seems work.

Just want to know if we can scale out top words size?

**Comment by liangyuoutreach** [comment]
I tried to use dataset from the [link](https://github.com/yyeung-lam/earnings-call-text-mining/tree/master/ndefault)

The dataset is related to earning call transcripts.

With current method, it only gets top 30 words.

When i directly apply the method you provided, always assign -1 topic.

With traditional tf-idf LDA method, it seems work.

Just want to know if we can scale out top words size?

**Comment by MaartenGr** [comment]
In the link you provide, I can find several .txt files. Which are used to create the dataset? How many documents do you end up with? If you have a very small dataset, then it is likely you will not end up with many topics. You can find a little bit more about this described in the [FAQ](https://maartengr.github.io/BERTopic/faq.html#i-have-only-a-few-topics-how-do-i-increase-them). 

What you mean by "it only gets top 30 words"? The top number of words represents the number of words in a topic and is a parameter in BERTopic that you can set yourself with `top_n_words`.
