### ISSUE TITLE
BERTopic - your installed version is: not available

### ISSUE THREAD

**Issue by peanutbutterandjellyfish** [MaartenGr/BERTopic#781]
I have tried installing BERTopic using the following commands in the Anaconda Prompt (Anaconda3) on a Windows10 machine.  

```
conda config --add channels conda-forge
conda config --set channel_priority strict
conda install bertopic
```
After installing for hours, the installations ends with the following output: 

```
Your installed version is: not available

Note that strict channel priority may have removed packages required for satisfiability.
```

Interestingly I get the same message when trying to install Top2Vec, so I assume the issues are linked. 
I cannot however figure out what the problem is. I have attached the entire installation log for BERTopic.
[BERTopicInstallation.txt](https://github.com/MaartenGr/BERTopic/files/9785778/BERTopicInstallation.txt)

Any ideas as to why the installation failed are highly appreciated. 

Thank you, 
Flavia

**Comment by MaartenGr** [comment]
It might be related to the python environment in which you are working this might be either due to a python version that is not supported or not the correct conda environment. It might be worthwhile to install it from python 3.9 and see if it works there.

**Comment by MaartenGr** [comment]
Due to inactivity, I'll be closing this issue for now. Feel free to reach out if you want to continue this discussion or re-open the issue!
