### ISSUE TITLE
Heatmap visualization is shifted because of outliers topic

### ISSUE THREAD

**Issue by aholovenko** [MaartenGr/BERTopic#782]
I was generating the heatmap using `self.model.visualize_heatmap()` method and have noticed that the visualization doesn't match the distance values. 
I think, the issue is that you are including `-1` topic when getting `self.topic_embeddings_` [code](https://github.com/MaartenGr/BERTopic/blob/09c1732997f838050c263ad00ad3c9474e816863/bertopic/_bertopic.py#L2495), but remove it during the `vusualize_heatmap()` [function](https://github.com/MaartenGr/BERTopic/blob/6293bf1fc7af8f926f3ecbfc7347e67ce5beb257/bertopic/plotting/_heatmap.py#L63)

Could you check, please?
https://github.com/MaartenGr/BERTopic/blob/09c1732997f838050c263ad00ad3c9474e816863/bertopic/plotting/_heatmap.py#L93
I guest this provides correct results.
```
    embeddings = embeddings[1:][indices]
```

**Comment by MaartenGr** [comment]
Thank you for sharing this. I will have to look into this a bit more since the shift may or may not happen depending on whether HDBSCAN is used or another clustering algorithm that does not have -1 in its possible classes.

**Comment by aholovenko** [comment]
Thanks @MaartenGr
