### ISSUE TITLE
Visualization does not show up in Jupyter notebooks in GitHub

### ISSUE THREAD

**Issue by tibfabtef** [MaartenGr/BERTopic#783]
Hi, I'm aware of the fact that BERTopic uses Plotly for visualizations and also that GitHub needs the following Plotly setting to store and then show Plotly charts in Jupyter notebooks correctly:

```
import plotly.io as pio
pio.renderers.default = 'svg'
```

This always works for my charts, but with BERTopic I only see two empty canvases in the place of the chart.

This is an example code:

```
fig = model.visualize_documents(docs)
fig.show()
```

To be more specific, the charts are correctly produced in the notebook with 'svg' (losing interactions as expected), but after pushed to GitHub the chart is like disappears; rather, two empty canvases show up instead.

**Comment by tibfabtef** [comment]
I just found [this one](https://github.com/plotly/plotly.py/issues/931), unfortunately, does not work for me either.

**Comment by tibfabtef** [comment]
After further investigation, I found that if I replace all go.Scattergl(...) calls with go.Scatter(...), rendering works as expected also in GitHub viewer. Obviously, WebGL causes some problems here.

It would be really nice to have the possibility to select the proper rendering to get all the superb visualizations working correctly, even in GitHub. Other visualization tools/browsers could also gain an advantage from this.

More info regarding Scatter vs. Scattergl can be found [here](https://plotly.com/python/webgl-vs-svg/).

**Comment by MaartenGr** [comment]
When visualizing the documents, it is necessary to have support for that many points. For that reason, there was specifically chosen to use `go.Scattergl` instead of `go.Scatter` as it scales much better with more datapoints. Although it is a shame that it does not render when posting the notebook in Github, I think adding a parameter for that specific instance would be a bit much. Instead, perhaps saving the figure as html and then loading it in might be a solution although I have not tested it yet:

```python
# Save the figure locally
fig.write_html("my_visualization.html")

# Show the figure
from IPython.display import HTML
HTML(filename="my_visualization.html")
```

**Comment by tibfabtef** [comment]
Yeah, that makes complete sense; in my experience though, you wouldn't necessarily need WebGL as the default engine (it could be overkill). Scatter does a pretty good job too.
So I could think of an automatic engine selection depending on the actual need (i.e., the number of documents to visualize).

**Comment by MaartenGr** [comment]
The thing is, many users are using 100 thousands of documents, and visualizing those get quite difficult with the regular Scatter. Even a couple of thousand becomes difficult if the documents are also loaded in the visualization. Having said that, I believe the express plotly way of doing the visualizations does something like automatically switching, so it might be worth to look into that.

**Comment by MaartenGr** [comment]
Due to inactivity, I'll be closing this issue for now. Feel free to reach out if you want to continue this discussion or re-open the issue!
