### ISSUE TITLE
Truncate max length of tokens usign external embedding model

### ISSUE THREAD

**Issue by bailez** [MaartenGr/BERTopic#785]
For portuguese using bertimbau I am using this code.

`from transformers.pipelines import pipeline

```
model_pt = pipeline("feature-extraction", model='neuralmind/bert-base-portuguese-cased')
corpus = ['a','b','c']
topic_model = BERTopic(embedding_model=model_pt,diversity=0.3)
```

But it seems bertopic is not truncating the max tokens when it starts encoding text:
```
`    239         if self.position_embedding_type == "absolute":
    240             position_embeddings = self.position_embeddings(position_ids)
--> 241             embeddings += position_embeddings
    242         embeddings = self.LayerNorm(embeddings)
    243         embeddings = self.dropout(embeddings)

RuntimeError: The size of tensor a (721) must match the size of tensor b (512) at non-singleton dimension 1
```

**Comment by MaartenGr** [comment]
This seems to be related to the model that you are using which did not specify a maximum length. I believe you would have to change the `max_length` in the tokenizer for it to work:

```python`
from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained('neuralmind/bert-base-portuguese-cased', model_max_length=512)
model_pt = pipeline("feature-extraction", model='neuralmind/bert-base-portuguese-cased', tokenizer=tokenizer)
```

**Comment by MaartenGr** [comment]
Due to inactivity, I'll be closing this issue for now. Feel free to reach out if you want to continue this discussion or re-open the issue!
