### ISSUE TITLE
Cannot Visualize or Extract the Topics-over-time from the saved Bertopic model?

### ISSUE THREAD

**Issue by Alla-Abdella** [MaartenGr/BERTopic#787]
Hello Maarten,

I saved the bertopic model. Then, I loaded the model to ensure that I can get the same visualizations. 
I was able to visualize the topics, the hierarchal clustering, bar-charts, rank_index, etc.

However, when you run:
loaded_model = BERTopic.load("my_model")
topics_over_time = loaded_model.topics_over_time(doc, time_records, datetime_format='%b%M', nr_bins=20)

I got the following error:
TypeError: object of type 'NoneType' has no len()

**Comment by shohil-kishore** [comment]
I am no expert but if all other visualisations work correctly then 'time_records' may be missing. Did you re-load 'time_records' (i.e. timestamps)?

**Comment by MaartenGr** [comment]
It does indeed seem like something is going on there with either the variables, like `time_records`, or perhaps some versions have changed between loading and saving the model. Did you make sure you use the same BERTopic version as when you saved the model?

**Comment by MaartenGr** [comment]
Due to inactivity, I'll be closing this issue. Let me know if you want me to re-open the issue!
