### ISSUE TITLE
find_topic possibly includes outliers (-1) in its output

### ISSUE THREAD

**Issue by ceesroele** [MaartenGr/BERTopic#789]
The method `find_topic` of the topic model includes the outlier "topic" in its output if there is sufficient similarity to the given search term.

As by definition the -1 id refers to outliers, rather than any defined topic, I think it should be excluded. 

Obvious workaround: users can filter out -1 from the result (which is what I did myself)

**Comment by MaartenGr** [comment]
I'll have to look into this a little bit more. In many of the features in BERTopic, the outliers are given but that is not always the case. I believe in `find_topic`  it might make sense to keep it as it indicates that the search term is not similar to any topic.

**Comment by ceesroele** [comment]
For the consideration of consistency: I note that `visualize_barchart` and `visualize_term_rank` do _not_ include the outlier group.

**Comment by MaartenGr** [comment]
Indeed, for some functions, I believe it does not make sense to include outliers whereas for outliers it might provide an additional dimension. The barchart and term rank for example focus on the importance of certain words in a topic whilst the words in the -1 topic generally have no meaning and are not the ones you want to interpret. In comparison, when you find the -1 topic as the most similar topic in `find_topic` it does indicate that the search term does not relate to an actual topic in the model. Having said that, it might already be clear from the similarity scores that were given.
