### ISSUE TITLE
Runtime Error: Numpy not available;  in BERTopic

### ISSUE THREAD

**Issue by chenghungpan** [MaartenGr/BERTopic#799]
Hello,

When I tried to run the Docker built image of Bertopic model, a run-time errors happened at the following line: 

topics, probs = model.fit_transform(docs)

This run-time error was traced back to the following: *********
File "/usr/local/lib/python3.8/site-packages/bertopic/_bertopic.py", line 333, in fit_transform
    embeddings = self._extract_embeddings(documents.Document,
  File "/usr/local/lib/python3.8/site-packages/bertopic/_bertopic.py", line 2244, in _extract_embeddings
    embeddings = self.embedding_model.embed_documents(documents, verbose)
  File "/usr/local/lib/python3.8/site-packages/bertopic/backend/_base.py", line 69, in embed_documents
    return self.embed(document, verbose)
  File "/usr/local/lib/python3.8/site-packages/bertopic/backend/_sentencetransformers.py", line 63, in embed
    embeddings = self.embedding_model.encode(documents, show_progress_bar=verbose)
  File "/usr/local/lib/python3.8/site-packages/sentence_transformers/SentenceTransformer.py", line 197, in encode
    all_embeddings = np.asarray([emb.numpy() for emb in all_embeddings])
  File "/usr/local/lib/python3.8/site-packages/sentence_transformers/SentenceTransformer.py", line 197, in <listcomp>
    all_embeddings = np.asarray([emb.numpy() for emb in all_embeddings])
**RuntimeError: Numpy is not available**

The Dockerfile base image I used, was the following:
FROM python:3.8.15-bullseye
:
I also tried python:3.9.15-bullseye,  python:3.10.15-bullseye, they all have the same run-time errors. 

Could someone please advis the solutions to resolve the issue?

Thank you!

James Pan

**Comment by chenghungpan** [comment]
Hello,
I have some more findings.   After creating a tiny test program:

import torch
import numpy as np
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(x.dim, x.shape)
print(type(x))
abc= x.numpy()
print(abc)
print(type(abc))


 I was able to duplicate the Run-time error and retrieve the following new message:

//tft.py:8: UserWarning: Failed to initialize NumPy: module compiled against API version 0x10 but this version of numpy is 0xe (Triggered internally at  /root/pytorch/torch/csrc/utils/tensor_numpy.cpp:68.)
  x = torch.tensor([[1, 2, 3], [4, 5, 6]])
Traceback (most recent call last):
  File "//tft.py", line 13, in <module>
    abc= x.numpy()
RuntimeError: Numpy is not available
tensor([[1, 2, 3],
        [4, 5, 6]])
<built-in method dim of Tensor object at 0xffff80786390> torch.Size([2, 3])

**Comment by chenghungpan** [comment]
Here is the Dockerfile requirements.txt I used to build the Docker image for this tiny program:

numpy==1.21.0
torch==1.12.1

**Comment by chenghungpan** [comment]
After updating 

numpy==1.23.4

I resolved the issue!

**Comment by MaartenGr** [comment]
Glad to hear that the issue was resolved and thank you for posting the solution! This will definitely help those that are also struggling with this.

**Comment by AbhayGoyal** [comment]
What version of bertopic?

**Comment by AbhayGoyal** [comment]
I get this error RuntimeError: Failed to import transformers.trainer because of the following error (look up to see its traceback):
cannot import name 'EncoderDecoderCache' from 'transformers' (/usr/local/lib/python3.10/dist-packages/transformers/__init__.py)

**Comment by MaartenGr** [comment]
@AbhayGoyal That seems like an issue with your transformers version. I would advise starting from a new environment.

**Comment by AbhayGoyal** [comment]
Worked it out thanks

**Comment by ziggycross** [comment]
Hey! I'm still having this error. Is there a preferred way of installing BERTopic to avoid this error?

Update: I tried several methods of creating a new environment using Conda. The only thing that worked was manually downgrading to numpy v1. I will try look into it and see if this is something solvable in a PR. For me, it seems like BERTopic is incompatible with the latest version of numpy.

**Comment by MaartenGr** [comment]
@ziggycross I don't think this is purely related to numpy. More specifically, I have no problems and using BERTopic in a new environment when simply running `uv add bertopic`. As such, it might be helpful if you used an environment manager like `uv` to create the environment instead of relying on conda.
