### ISSUE TITLE
Predict multiple topics per document

### ISSUE THREAD

**Issue by james-daily** [MaartenGr/BERTopic#8]
Would it be feasible to return the probabilities for all of the topics rather than only returning the best topic?  This would be similar to LDA, where typically proportions or probabilities are returned for all topics.

I think this could be done by changing `transform()` to use `membership_vector()` instead of `approximate_predict()`.

**Comment by MaartenGr** [comment]
From your title and description, it seems there are two results you might want:
* Probability of topics within a document (where `membership_vector()` is definitely an interesting approach!)
* Frequency of topics within a document (which cannot be computed with `membership_vector()` as it is a similarity approach and not a frequency approach)

The first result should be do-able to implement and might even be a proxy of the second result although I am not sure if we can use the probabilities to also approximate topic frequency. What do you think? 

The second can already be achieved by cutting a document up into sentences and passing the sentences through the model as if it were documents. Then, you can take all the sentences and their respective topics in a document and simply create a histogram of the frequency of certain topics. However, this might be rather expensive computationally as the number of document/sentence embeddings increases significantly.

**Comment by james-daily** [comment]
I mean probability of topics within a document, where a document is a sentence or short paragraph.  For example, imagine a news topic model that had topics for sports and countries.  A sentence such as “France has defeated Croatia in the 2018 FIFA World Cup” might have relatively high probabilities for both the sports topic and the countries topic.

**Comment by MaartenGr** [comment]
Took a while but the probabilities are now returned as a default. You can also visualize the distributions for a single document (see **Readme** for an example).
