### ISSUE TITLE
Feature request: title parameter for visualizations

### ISSUE THREAD

**Issue by ceesroele** [MaartenGr/BERTopic#800]
Diagrams saved as images can lead their own life. For this reason it is desirable that they can be clearly titled as part of the picture.

`visualize_barchart` has a `title` parameter that allows for customization of the diagram's title. I use it and like it.

AFAIK, this is the only visualization that allows for setting a title. It would be nice if the other visualizations would have such a parameter too.

**Comment by MaartenGr** [comment]
Thank you for the feature request! I believe I had a reason for only putting that there but I cannot for the life of me remember why I did not do the same for all the other visualizations. I will look into this a little bit to figure out what my thinking was but it is definitely a reasonable request!

**Comment by MaartenGr** [comment]
Since this was added in v0.14, I'll close this issue.
