### ISSUE TITLE
Improving clustering time

### ISSUE THREAD

**Issue by C-monC** [MaartenGr/BERTopic#801]
Is it possible to get real-time speeds?
Real-time, for me, means +- 5000 documents and output clusters within 20 seconds.

tests are on 5000 documents with average character length: 19585.53

This block is for reference, I have the embeddings saved in a db so I'm not adding this to the timing.
```
ctfidf_model = ClassTfidfTransformer(bm25_weighting=True, reduce_frequent_words=True)
stopwords = open("stopwords.txt", encoding="utf-8").read().splitlines()
vectorizer_model = CountVectorizer(stop_words=stopwords, ngram_range=(1, 3))
sentence_model = SentenceTransformer("all-MiniLM-L6-v2")
embeddings = sentence_model.encode(docs, show_progress_bar=True)

topic_model = BERTopic(calculate_probabilities=False,nr_topics=number_of_topics,language="english", diversity=0.5, verbose=True, vectorizer_model=vectorizer_model, ctfidf_model=ctfidf_model)
```

Timing fit_transform and hierarchy:
```
start = time.time()
doc_topics, probs = topic_model.fit_transform(docs, embeddings=embeddings)
print("fit time ", time.time() -start) 

start = time.time()
linkage_function = lambda x: sch.linkage(x, 'ward', optimal_ordering=True)
hierarchical_topics = topic_model.hierarchical_topics(docs, linkage_function=linkage_function)
hierarchical_topics = hierarchical_topics.sort_index()
print("hierarchy time ", time.time() -start)
```
fit_transform takes 51 seconds and hierarchy generation 9 seconds.

I can see token generation is the bulk of the fit_transform: `vectorizer_model.fit_transform(docs)` takes 34s

Is it possible for me save the vectorized/tokenized documents and add them to the topic_model? Pre-fitting the CountVectorizer doesn't change the topic_model.fit_transform speed. If I can save these tokens even using 5 grams becomes an option.

```
class TestCountVectorizer(CountVectorizer):
    def fit(self, docs):
        return self
vectorizer_model = TestCountVectorizer(vectorizer_model.fit(docs))
```
I can't seem to get the above to work. The error is `NotFittedError: Vocabulary not fitted or provided. `What I want is the same as commenting out https://github.com/MaartenGr/BERTopic/blob/09c1732997f838050c263ad00ad3c9474e816863/bertopic/_bertopic.py#L2519

I tried PCA instead of UMAP but it appears to be negligible 0.3 second difference. Do you have any other ideas to speed up the process? I'll give the cuml implementations a go next.

**Comment by C-monC** [comment]
It was a simple as 

```
def fit(docs):
    return None

vectorizer_model = vectorizer_model.fit(docs)
vectorizer_model.fit = fit
```
Chops nearly 60% of the time of the process if I cache the tokens.
This puts it at 30 seconds for the whole process.

**Comment by C-monC** [comment]
> I tried PCA instead of UMAP but it appears to be negligible 0.3 second difference.

This is completely untrue. PCA with 4 principals takes 23 seconds. UMAP with 4 components 32 seconds.

**Comment by MaartenGr** [comment]
Glad to hear that you managed to also speed up the vectorization step! Out of curiosity, if you are focusing on real-time performance, then why are you using `fit_transform` and not `partial_fit`? Do you want a separate topic model at each instance?

**Comment by C-monC** [comment]
Ah thanks for that. A partial fit using the model trained on the entire dataset should probably not be detrimental to accuracy?
I have 50k to 500k documents and am querying sets of 100-5k documents out of that.

I am also worried about memory usage if I store the entire topic_model in memory. I could pickle and load the pickle to make it temporary but during this development I regularly hit 15Gb of RAM usage for the python process.

A new topic model per queried set is almost fast enough. 

Here are a few more points for future readers:
- min_df of 0.005-0.01 reduces my tokens from 1.8 Mil to 750k. Keeping token count low is critical
- max_df is irrelevant to speed. I think it helps for better topics though.
- PCA saves +-30% during dimensionality reduction. I can't notice a difference in the output clusters but there should be an accuracy decrease.
- If you can allow it drop all words with length 2 or less i.e. filter(lambda x: 2 < len(x) <= 30) to decrease token count.

[Spacy](https://spacy.io/usage) Seems to have much better lemmitization/tokeniszation (Still testing). This should reduce the token count and speed up many of the processes.

**Comment by xrtze** [comment]
> 

Sorry, could you elaborate a bit more were you put and executed this code? I can't get it working.

**Comment by MaartenGr** [comment]
Due to inactivity, I'll be closing this issue. Let me know if you want me to re-open the issue!
