### ISSUE TITLE
Dimension mismatch with topics_over_time 

### ISSUE THREAD

**Issue by shohil-kishore** [MaartenGr/BERTopic#802]
Hi there, 

I updated BERTopic to the latest version available (v0.12.0) and now I keep getting a dimension mismatch error when using topics_over_time. I guess I must be missing something simple. This is the line of code I am using:

`aus_topics_over_time = aus_model.topics_over_time(aus_data, aus_timestamps)`

Error:
![Screen Shot 2022-10-25 at 11 43 25](https://user-images.githubusercontent.com/33049612/197643704-c8ffee74-8942-4c4d-83fb-18e77175d22e.png)

You can see the structure of 'aus_data' and 'aus_timestamps' below:
![Screen Shot 2022-10-25 at 11 36 55](https://user-images.githubusercontent.com/33049612/197642853-0f250227-7430-42ea-888f-815f8528e5d1.png)

![Screen Shot 2022-10-25 at 11 37 25](https://user-images.githubusercontent.com/33049612/197642928-fe6a2b92-d19b-4d3d-ab10-950b9fe68d6d.png)

I have tried converting timestamps into integers with no success either. 

Thank you for any help you can provide!

**Comment by MaartenGr** [comment]
Not entirely sure what is happening here... Just to be sure, did you train this model in your v0.12 environment, or was this a model that you saved before?

**Comment by shohil-kishore** [comment]
I have no clue either, I closed my Jupyter Notebook tab, re-ran the same line of code, and things seem to be working fine now! Sorry for the hassle and thanks for the quick reply. 👍
