### ISSUE TITLE
Scipy linkage accepts a condensed matrix under hierarchical_topics()

### ISSUE THREAD

**Issue by rajesh-gupta-14** [MaartenGr/BERTopic#807]
Hi @MaartenGr

Thanks so much for coming up with this wonderful and useful library. I had a question pertaining to the default Scipy linkage function under hierarchical_topics() and the way it accepts a distance matrix. 

```
class BERTopic:
  def hierarchical_topics(*args, **kwargs):
        if distance_function is None:
            distance_function = lambda x: 1 - cosine_similarity(x)

        if linkage_function is None:
            linkage_function = lambda x: sch.linkage(x, 'ward', optimal_ordering=True)

        # Calculate linkage
        embeddings = self.c_tf_idf_[self._outliers:]
        X = distance_function(embeddings)
        Z = linkage_function(X)
```

As per Scipy's documentation [(v1.9.3),](https://docs.scipy.org/doc/scipy/reference/generated/scipy.cluster.hierarchy.linkage.html#scipy.cluster.hierarchy.linkage) the linkage function only accepts a 1-D condensed distance matrix such as the one scipy.spatial.distance.pdist() returns. But by following the above code, the distance matrix (X) seems to be an uncondensed distance matrix with dimensions nxn, with n being the no. of observations (the lower triangular matrix being a duplicate of the upper triangular matrix). Could you please shed some light on this? Thanks for your time in advance!

**Comment by MaartenGr** [comment]
Hmmmm, it seems that during the development of this feature I referenced old documentation where this was not yet explained. I most likely missed this since the results are actually rather nice when ignoring the documentation 😅 Thank you for bringing this to my attention! I believe a fix for this should be rather straightforward:

```python
# Calculate linkage
embeddings = self.c_tf_idf_[self._outliers:]
X = distance_function(embeddings)

# Make sure it is the 1-D condensed distance matrix with zeros on the diagonal 
from scipy.spatial.distance import squareform
np.fill_diagonal(X, 0)
X = squareform(X)

# Use the 1-D condensed distance matrix as an input instead of the raw distance matrix
Z = linkage_function(X)
```

I'll make sure this gets fixed in the next release!

**Comment by rajesh-gupta-14** [comment]
Of course @MaartenGr Thanks once again for a quick response and a wonderful library 🤗
