### ISSUE TITLE
Dealing with large dataset using a for loop.

### ISSUE THREAD

**Issue by hengee** [MaartenGr/BERTopic#809]
```python
import os
from bertopic import BERTopic
from sentence_transformers import SentenceTransformer, models
from sklearn.decomposition import PCA
from sklearn.feature_extraction.text import CountVectorizer
from cuml.cluster import HDBSCAN
from cuml.manifold import UMAP
import numpy as np
import pandas as pd
import torch

import pynndescent
pynn_dist_fns_fda = pynndescent.distances.fast_distance_alternatives
pynn_dist_fns_fda["cosine"]["correction"] = correct_alternative_cosine
pynn_dist_fns_fda["dot"]["correction"] = correct_alternative_cosine

def free_memory(sleep_time=0.1):
    gc.collect()
    torch.cuda.synchronize()
    gc.collect()
    torch.cuda.empty_cache()
    time.sleep(sleep_time)

# main method to run the program
if __name__ == "__main__":
    seed = 174
    free_memory()
    df = pd.read_csv('text.csv') # sample df, actually df consists of 55 million sentences
    
    df = df.sample(frac=1) # Return a random sample of items from an axis of object.
    df_list = np.array_split(df, 20) # Split the df into 20 parts

    stopwords = list(stopwords.words('english')) + ['http', 'https', 'amp', 'com', 'rt', 'usr','url','tweet','link','tweets']

    vectorizer_model = CountVectorizer(ngram_range=(1, 1), stop_words=stopwords, min_df=10)
    embedding_model = SentenceTransformer('all-MiniLM-L6-v2', cache_folder='TRANSFORMERS_CACHE', device='cuda:0')
    umap_model = UMAP(n_neighbors=100, n_components=5, min_dist=0.05, random_state=seed)
    hdbscan_model = HDBSCAN(min_cluster_size=10, min_samples=10,gen_min_span_tree=True,prediction_data=True)

    model = BERTopic(
        umap_model=umap_model,
        hdbscan_model=hdbscan_model,
        embedding_model=embedding_model,
        vectorizer_model=vectorizer_model,
        top_n_words=10,
        language='english',
        calculate_probabilities=True,
        nr_topics = "auto",
        verbose=True,
        min_topic_size=300
    )

    for i in range(20):
        data = Dataset.from_pandas(df_list[i].reset_index(drop=True))
        embeddings = embedding_model.encode(data['text'], show_progress_bar=True, batch_size=52)
        free_memory()
        model.fit(data['text'], embeddings)
        free_memory()
        freq = model.get_topic_info()
        print(freq.head(10))
        model.save('sm_model')
```
Hi, I'm using BERTopic with GPU acceleration, as suggested in the [FAQ](https://maartengr.github.io/BERTopic/faq.html#can-i-use-the-gpu-to-speed-up-the-model) on a million sentences, it worked fine until I proceeded with the whole dataset, which is about 55 million sentences. 

I run into a ```MemoryError: std::bad_alloc: CUDA error```, the error is similar to the post [here](https://github.com/rapidsai/cudf/issues/6087), but I'm working on a single GPU (Nvidia A40, about 48 GB).  

Therefore, I have implemented a workaround by splitting the dataset into 20 smaller subsets and using a for loop to iteratively ```fit``` the model with each subset, as shown above.

Is this option viable?

Thank you in advance!

**Comment by drob-xx** [comment]
I'm sure Maarten will have a more thorough answer but `.fit` just calls `fit_transform()`. `fit_transform` runs UMAP and the HDBSCAN against whatever documents are being passed and produces the model. So every loop here is simply replacing one model with another, it is not additive. You can see this by getting `len(model.topics_)` and you will see that it amounts to 1/20 of your dataset size.

If your dataset is reasonably balanced then you should be able to `fit_transform()` a representative (random) sample and then call `partial_fit()` on the remaining documents. This will use HDBSCAN to calculate the topic clusters for new documents based on an existing model. So break your dataset into two parts - a randomly selected set of documents that doesn't blow up the memory (and this could be a majority of the documents - depends) and then the rest which you will incrementally `fit()`.

One thing you might try is setting `low_memory=True` in the init. I'm actually a bit unclear on what the memory footprint of UMAP is vs. HDBSCAN - low_memory only affects UMAP.

Beyond that I'm curious as to what Maarten has to say. If UMAP is the culprit I have some speculative potential avenues. I've had imbalanced datasets where I used UMAP and then HDBSCAN to identify major clusters and then split the dataset along those lines - it worked very well in that case - but is a bit in the weeds. 

Another approach that might be interesting might be to generate a UMAP reduction by calling UMAP `fit()` on a representative subset of the data and then incrementally call UMAP `transform()` which will reduce the new embeddings incrementally without incurring the overhead of UMAP `fit()` on the entire dataset. Once you have the entire dataset reduced you can pass it into a BERTopic model and bypass the default UMAP behavior.

If HDBSCAN is the culprit then _I think_ the only solution is the partial_fit approach mentioned first. I don't know what the memory footprint of `calculate_probabilities=True` is if any - but it sounds like you really want the probabilities and I've only seen it referenced in the issues as a CPU resource problem - not a memory issue.

**Comment by MaartenGr** [comment]
> If your dataset is reasonably balanced then you should be able to fit_transform() a representative (random) sample and then call partial_fit() on the remaining documents. This will use HDBSCAN to calculate the topic clusters for new documents based on an existing model. So break your dataset into two parts - a randomly selected set of documents that doesn't blow up the memory (and this could be a majority of the documents - depends) and then the rest which you will incrementally fit().

I'm guessing you mean `.fit()` instead of `.partial_fit()` seeing as HDBSCAN does not support online/incremental learning natively. You can find more about how online learning works in BERTopic [here](https://maartengr.github.io/BERTopic/getting_started/online/online.html). 

> One thing you might try is setting low_memory=True in the init. I'm actually a bit unclear on what the memory footprint of UMAP is vs. HDBSCAN - low_memory only affects UMAP.

Since a custom model is chosen for the `umap_model` parameter, the `low_memory=True` parameter will have no effect since it is a parameter of the original UMAP model and not the UMAP variant used in cuML. 

> If HDBSCAN is the culprit then I think the only solution is the partial_fit approach mentioned first. I don't know what the memory footprint of calculate_probabilities=True is if any - but it sounds like you really want the probabilities and I've only seen it referenced in the issues as a CPU resource problem - not a memory issue.

In the current implementation, `calculate_probabilities=True` only works for the original HDBSCAN package and not yet the cuML variant. So using this will have no effect. This will be possible in the future with cuML's approach and, from what I have seen thus far from them, is quite a bit faster and more performant than the original implementation.

**Comment by MaartenGr** [comment]
@hengee  Before going into the possible solution, it might be helpful to detect where exactly the model is consuming so many resources and whether it relates to the size of the data or something within cuML. Looking at your code, it seems that you have `verbose=True` enable when instantiating the model. Could you share all the output it has generated before getting your error? That way, we can zoom in on the underlying issue and detect at which specific step you are getting those memory errors. 

If, by chance, it happens at the HDBSCAN step, then it might be worthwhile to increase the `min_cluster_size` to at least a couple of hundred instead of ten. The reasoning for this is that with 55 million documents, you are bound to get tens of thousands of topics if the minimum topic size is going to be ten.

**Comment by drob-xx** [comment]
@MaartenGr I figured you would have a better answer :)

More analysis is a good idea :). I saw 1M sentences and 48GB memory and figured - yah, that might be an issue. What is the ballpark memory utilization profile for UMAP vs. HDBSCAN btw? I guess I should have stopped when I said that calling fit_transform() iteratively wasn't going to solve any problem here :)

> I'm guessing you mean .fit() instead of .partial_fit() seeing as HDBSCAN does not support online/incremental learning natively. You can find more about how online learning works in BERTopic [here](https://maartengr.github.io/BERTopic/getting_started/online/online.html).

Ok - munged this one pretty badly. I haven't had occasion to deal with any showstopping memory issues myself so I've followed the responses loosely. I didn't have any idea that partial_fit only worked with certain clustering mechanisms - my bad. However, what I was getting at was the process of using a subset to fit the model and then predict new documents incrementally. So I think it should have been: train a BERTopic model using a representative sample and then call `BERTopic.transform` on the other documents (iteratively if necessary) to get predictions. I think I've seen this strategy discussed elsewhere when dealing with resource limitations. If the memory problem can't be solved elsewhere then this would be the only approach, correct?

> Since a custom model is chosen for the umap_model parameter, the low_memory=True parameter will have no effect since it is a parameter of the original UMAP model and not the UMAP variant used in cuML.

Yup. If I had read more closely I would have suggested setting `model.umap_model.low_memory=True` after initialization. However, as you point out - the cuML variant doesn't support this.

Would love to hear more on the relative RAM footprints of HDBSCAN and UMAP.

**Comment by hengee** [comment]
Thanks for the timely response from both @drob-xx and @MaartenGr.

> You can see this by getting len(model.topics_) and you will see that it amounts to 1/20 of your dataset size.

As pointed out by @drob-xx , I can see that the topic frequency for each iteration is about 1/20 of my dataset. 

> If, by chance, it happens at the HDBSCAN step, then it might be worthwhile to increase the min_cluster_size to at least a couple of hundred instead of ten. The reasoning for this is that with 55 million documents, you are bound to get tens of thousands of topics if the minimum topic size is going to be ten.

I have made some modifications as suggested and running the model right now. 

> Looking at your code, it seems that you have ```verbose=True enable``` when instantiating the model. Could you share all the output it has generated before getting your error? That way, we can zoom in on the underlying issue and detect at which specific step you are getting those memory errors.

Unfortunately, I lost my ssh connection due to a Windows update yesterday, all the output is printed to the console. The embedding usually takes 9 hours before passing it into the Bertopic ```model.fit(data['text'], embeddings)```, I will update once I get the actual output (implemented logging this time).

**Comment by hengee** [comment]
@MaartenGr  @drob-xx , here's the Exception I got:

```bash
2022-10-28 00:04:35,322 INFO sentence_transformers.SentenceTransformer Load pretrained SentenceTransformer: all-MiniLM-L6-v2
2022-10-28 02:40:49,464 ERROR root Exception occurred
Traceback (most recent call last):
  File "/bertopic_sm2.py", line 261, in <module>
    model.fit(data['text'], embeddings)
  File "/home/miniconda/conda/envs/rapids-22.10/lib/python3.9/site-packages/bertopic/_bertopic.py", line 269, in fit
    self.fit_transform(documents, embeddings, y)
  File "/home/miniconda/conda/envs/rapids-22.10/lib/python3.9/site-packages/bertopic/_bertopic.py", line 345, in fit_transform
    umap_embeddings = self._reduce_dimensionality(embeddings, y)
  File "/home/miniconda/conda/envs/rapids-22.10/lib/python3.9/site-packages/bertopic/_bertopic.py", line 2284, in _reduce_dimensionality
    self.umap_model.fit(embeddings, y=y)
  File "/home/miniconda/conda/envs/rapids-22.10/lib/python3.9/site-packages/cuml/internals/api_decorators.py", line 409, in inner_with_setters
    return func(*args, **kwargs)
  File "umap.pyx", line 587, in cuml.manifold.umap.UMAP.fit
MemoryError: std::bad_alloc: out_of_memory: CUDA error at: /home/miniconda/conda/envs/rapids-22.10/include/rmm/mr/device/cuda_memory_resource.hpp
```

I'm using Cuda 11.7, but the threads ([1](https://github.com/rapidsai/cuml/issues/4067#issuecomment-885107971),[2](https://github.com/rapidsai/cudf/issues/11796),3) suggested 11.6 would work back in 2021, so I think it might not be the case, continuing my investigation and reading cuML doc

**Comment by MaartenGr** [comment]
@hengee Alright, from your error message it definitely seems to be related to cuML's UMAP, which narrows things down a bit. Even with cuda, something like UMAP can still require a lot of memory since it has to calculate distances between quite a number of points. It may be helpful to play around with certain parameters and see if that works, like lowering `n_neighbors` so that fewer points are looked at. Having said that, it already takes quite some time for you to run all of this, so it may not be an option. It might be helpful to fit on a subset and see where that gets you or you can go directly to the issues page of [cuML](https://github.com/rapidsai/cuml/) to see if they can help you out. Perhaps they know of some tricks that I am unaware of which might help you fit all of the data.
