### ISSUE TITLE
About the feedback of final user

### ISSUE THREAD

**Issue by nadiafelix** [MaartenGr/BERTopic#81]
Do you imagine creating a way to include some user feedback on the topic template presented? Using active learning or semisupervised learning and improve the model in future?

**Comment by MaartenGr** [comment]
In theory that sounds like an interesting feature but I am wondering how you would plan on using such a feature. Do you have any specific use-cases you would use that for?

**Comment by nadiafelix** [comment]
Maybe with "must-link" and "cannot link" constraints. With soft and hard constraints.

**Comment by MaartenGr** [comment]
There are currently no options for such constraints in HDBSCAN as that is where you would, in part, have most of these constraints. There is a (semi)-supervised method in development that would have some of these features.
