### ISSUE TITLE
Segfault when trying to fit_transform model with any size data

### ISSUE THREAD

**Issue by kgoo124** [MaartenGr/BERTopic#812]
Using Python 3.9.13 with Conda on an Intel Macbook Pro and getting this error below
```
zsh: segmentation fault
```

This is my code below copied from the quick start. 
```
from bertopic import BERTopic

docs = fetch_20newsgroups(subset='all',  remove=('headers', 'footers', 'quotes'))['data']
topic_model = BERTopic()
topic_model.fit(docs)
```

**Comment by kgoo124** [comment]
@MaartenGr any ideas what might be causing this issue?

**Comment by MaartenGr** [comment]
Could you try some of the suggestions mentioned in the issue [here](https://github.com/MaartenGr/BERTopic/issues/112)? I believe it may relate to what you are experiencing and hopefully, it will fix your issue. Also, it might be worthwhile to check whether you have a pytorch version that is supported by MacBooks.

**Comment by kgoo124** [comment]
Had to uninstall and reinstall pytorch. Not exactly sure what changed, but that seemed to fix the problem
