### ISSUE TITLE
how to extract multiple topics per document

### ISSUE THREAD

**Issue by Kon3000** [MaartenGr/BERTopic#814]
any coding examples on extracting multiple topics per document? 
for example
1) the input document is split into individual sentences 
2) the model provides the probability for the most likely topics per document?

**Comment by MaartenGr** [comment]
> the input document is split into individual sentences


To split the input up into individual sentences, there are a number of packages you can use like [SpaCy](https://spacy.io/api/sentencizer), [Gensim](https://radimrehurek.com/gensim_3.8.3/summarization/textcleaner.html), and [NLTK](https://www.nltk.org/api/nltk.tokenize.html#nltk.tokenize.sent_tokenize). Each link refers to a specific tokenizer although I have not used the Gensim variant yet. 

> the model provides the probability for the most likely topics per document?

You can use the `calculate_probabilities=True` parameter for that. It will make sure that the resulting `probs` variable is a document-probability matrix that allows you to see the probabilities of the most likely topics per document.

**Comment by cateto** [comment]
@MaartenGr 
Thank you for your sharing awesome project.

![image](https://user-images.githubusercontent.com/60098277/216266026-d456e2dc-2b4f-484f-9909-0f2732a463cd.png)

I want to know why approximate_distribution dataframe is empty.

Have a good day. :)

**Comment by MaartenGr** [comment]
@cateto It is difficult to say what exactly is happening without seeing your full code, could you share that? Also, perhaps `topic_token_distr[1206]` is empty as it has not found any topics for that document, which depends on some parameters in `.approximate_distribution`.
