### ISSUE TITLE
Tuning PCA and k Means 

### ISSUE THREAD

**Issue by andrewliew86** [MaartenGr/BERTopic#817]
Hi Maarten,

Thanks for your work with BERTopic. 

Is there a way we can access the dimensionality reduction and clustering models that are used by BERTopic? I am hoping to use PCA and k Means (instead of UMAP and HDBScan) in my workflow but I'm not sure how to find the optimal paramaters ('n_components' for PCA and 'n_clusters' for k Means) for these models using BERTopic. Is it possible, for example, to create an elbow plot/silhouette coefficient via BERTopic to determine the appropriate 'n_clusters' for k Means?

**Comment by MaartenGr** [comment]
BERTopic aims to be highly modular and as such, there is no method implemented that focuses on these specific models and parameters. Having said that, you could use those models outside of BERTopic to fine-tune them and whenever you have the parameters you are searching for use them back into BERTopic. 

Other than that, you can access the models after training with:

```python
from bertopic import BERTopic
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA

# Define sub models
kmeans = KMeans(n_clusters=20, random_state=0)
pca = PCA(n_components=5)

# Fit topic model
topic_model = BERTopic(hdbscan_model=kmeans, umap_model=pca).fit(docs)

# Access the sub models
topic_model.hdbscan_model
topic_model.umap_model
```

**Comment by MaartenGr** [comment]
Due to inactivity, I'll be closing this issue for now. If, however, you want to continue the discussion or re-open the issue, feel free to reach out!
