### ISSUE TITLE
TypeError: fit_transform() got an unexpected keyword argument 'y'

### ISSUE THREAD

**Issue by suglou** [MaartenGr/BERTopic#819]
Hi Maarten, 

Thanks for making this available!

On my installation of BERTopic the .fit() and .fit_transform() functions do not include the 'y' argument for semi-supervised / supervised learning.

The help() function returns:
    
    Arguments:
        documents: A list of documents to fit on
        embeddings: Pre-trained document embeddings. These can be used
                    instead of the sentence-transformer model
    
    Returns:
        predictions: Topic predictions for each documents
        probabilities: The topic probability distribution which is returned by default.
                       If `low_memory` in BERTopic is set to False, then the
                       probabilities are not calculated to speed up computation and
                       decrease memory usage.`

Is there a particular version of BERTopic that I should be installing? Thanks

**Comment by MaartenGr** [comment]
Which version of BERTopic are you currently using? I might be mistaken but it seems like a rather old version.

**Comment by suglou** [comment]
Turns out it was an older version since my cluster was running an old version of Python, running on 3.7 and installing 0.12.0 worked for me, thanks for the response!
