### ISSUE TITLE
About keyword selection with topic embedding

### ISSUE THREAD

**Issue by dopc** [MaartenGr/BERTopic#82]
Hey,

#79 I have read this issue and it inspired me to ask the below,

Why don't you get weighted embedding of keywords while extracting topic keywords, in [here](https://github.com/MaartenGr/BERTopic/blob/1ffc4569a40bf845d2083bfd63c30c8d648a3772/bertopic/_bertopic.py#L1267)?

Just wondering, whether did you try the way I suggest and see the effect on the keywords?

**Comment by MaartenGr** [comment]
The reasoning for that is that when you use weighted c-TF-IDF embeddings, then there is likely too much emphasis on words that have a high c-TF-IDF value. In practice, we already selected the top 30 words and then use MMR to create a selection from that list of candidates. If we would embed the c-TF-IDF values in the topic representation, then there is a good chance that MMR will basically select the candidates with the highest c-TF-IDF scores.

**Comment by dopc** [comment]
I got what you mean, thanks for explanation.
