### ISSUE TITLE
AttributeError: module 'llvmlite.binding.ffi' has no attribute 'register_lock_callback'

### ISSUE THREAD

**Issue by maiya86** [MaartenGr/BERTopic#820]

**Comment by MaartenGr** [comment]
Could you provide some context? As in, what exactly happened that led you to this error? Was it some specific code, pipeline, or installation perhaps? Did it happen whilst training BERTopic, doing inference, loading, saving, or something else?

**Comment by MaartenGr** [comment]
Could you try installing BERTopic with only `pip install bertopic` in a completely fresh environment? Perhaps that will do the trick.

**Comment by MaartenGr** [comment]
Due to inactivity, I'll be closing this issue for now. If, however, you want to continue the discussion or re-open the issue, feel free to reach out!

**Comment by maiya86** [comment]
Thank you so much. Installing in a new environment helped. Would you by any
chance know how to get the distribution of topics in a document? I thought
I could do it with bertopic but it seems to only give the dominant topic in
a document.

Thank you,

Nishi

**Comment by MaartenGr** [comment]
@maiya86 With the new v0.13 release of BERTopic, you definitely can! You can approximate the distribution of topics with `.approximate_distributions`. You can find more about that [here](https://maartengr.github.io/BERTopic/getting_started/distribution/distribution.html).

**Comment by maiya86** [comment]
Thank you very much, Maarten. I will try it out.

- Nishi

**Comment by maiya86** [comment]
Hi Maarten,

I tried it out, and it seems like .approximate_distributions gives the
topic-term distribution. Is there a way to get document-topic distribution
- i.e., how many topics does a document (tweet/sentence) contain?

Thanks,

Nishi

**Comment by MaartenGr** [comment]
Actually, the `.approximate_distribution` function does not give the topic-term distribution but the topic-document distribution. If you follow the guide in the link mentioned above you will find it returns the `topic_distr` variable. Within that variable, you can find a n X m matrix where n are the topics and m the documents. In other words, it will show for each document the mixture of topics it contains.

**Comment by maiya86** [comment]
Thank you so much. It works like a charm.
