### ISSUE TITLE
Something about paper

### ISSUE THREAD

**Issue by DYH-Devil** [MaartenGr/BERTopic#827]
Hello Maarten! I have read your paper. I have some doubts in the c-tfidf formula. Does A in the formula refer to the average text length in a category, and what does tf in the denominator refer to？refer to how many times the term t appears in the corpus? Please tell me in detail. Thank you

**Comment by MaartenGr** [comment]
You can find more about the c-TF-IDF formula and an extensive description in the documentation [here](https://maartengr.github.io/BERTopic/algorithm/algorithm.html#5-topic-representation). It might also be worthwhile to check out the code for calculating c-TF-IDF [here](https://github.com/MaartenGr/BERTopic/blob/master/bertopic/vectorizers/_ctfidf.py).
