### ISSUE TITLE
KeyError: 699

### ISSUE THREAD

**Issue by SimoneBarandoni** [MaartenGr/BERTopic#834]
Hi,

I am trying to use BERTopic through the Colab Notebook shared. When I try to run the cell which imports BERTopic and uses "fit.transform" I get the following error (when it executes the line "topics, probs = topic_model.fit_transform(..."

KeyError: 699

   3365         if is_scalar(key) and isna(key) and not self.hasnans:
   3364 
-> 3363                 raise KeyError(key) from err
   3362             except KeyError as err:
   3361                 return self._engine.get_loc(casted_key)
[/usr/local/lib/python3.7/dist-packages/pandas/core/indexes/base.py](https://localhost:8080/#) in get_loc(self, key, method, tolerance)
KeyError                                  Traceback (most recent call last)

The above exception was the direct cause of the following exception:

KeyError: 699

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.Int64HashTable.get_item()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.Int64HashTable.get_item()
11 frames

   3362             except KeyError as err:
-> 3361                 return self._engine.get_loc(casted_key)
   3360             try:
[/usr/local/lib/python3.7/dist-packages/pandas/core/indexes/base.py](https://localhost:8080/#) in get_loc(self, key, method, tolerance)
```
KeyError                                  Traceback (most recent call last)
```

**Comment by aleksieva** [comment]
reset the index of your dataframe 
`df.reset_index(inplace = True,drop = True)`

**Comment by SimoneBarandoni** [comment]
> reset the index of your dataframe `df.reset_index(inplace = True,drop = True)`

It worked, thanks a lot
