### ISSUE TITLE
UTF-8 characters deleted when pre-computing embeddings 

### ISSUE THREAD

**Issue by Arthur095** [MaartenGr/BERTopic#835]
Hello, first of all I want to thank you for this awesome job you've done. I'm using Bertopic for french lexicon extraction sorted by themes and it's doing great. However, french language uses accentuated characters that disappear from the output if I'm using pre-computed embeddings with sentence-transformers such as shown in the tips&trick section of the documentation.  Accentuated characters are not deleted if I'm computing embeddings inside the Bertopic object.  I may do something wrong.

I am using python 3.9.13 through conda.
### Sample of code :

```Python3

from bertopic import BERTopic
import pandas as pd
from sentence_transformers import SentenceTransformer
from sklearn.feature_extraction.text import CountVectorizer
from hdbscan import HDBSCAN
from umap import UMAP

from sentence_transformers import SentenceTransformer
df = pd.read_csv("my_csv.csv", delimiter=";", encoding="utf-8")
docs = df["text"].tolist()

sentence_model = SentenceTransformer("dangvantuan/sentence-camembert-base")
embeddings = sentence_model.encode(docs)

vectorizer_model = CountVectorizer(min_df=0.10, max_df=0.90)
cluster_model = HDBSCAN(min_cluster_size=79, min_samples=12, metric='euclidean', prediction_data=True)
umap_model = UMAP(n_neighbors=30, n_components=10, metric='cosine', low_memory=False)

topic_model = BERTopic(umap_model=umap_model, 
hdbscan_model=cluster_model, 
top_n_words = 30, 
vectorizer_model=vectorizer_model, 
calculate_probabilities=True)

topics, probs = topic_model.fit_transform(docs, embeddings)

topic_model.get_topics()
```

### Sample output :

0: [('robots', 0.09960259028216151),
  ('machines', 0.08324071017609015),
  ('mdecins', 0.0453592080888017),  # Instead of "médecins"
  ('robot', 0.04160454145833431),
  ('technologie', 0.03925113576386589),
  ('machine', 0.03911050644917317),
  ('remplacement', 0.036344934869112916),
  ('chmage', 0.03360222075595174), # instead of "chômage"
  ('md  ('machines', 0.08324071017609015),
  ('mdecins', 0.0453592080888017),  # Instead of "médecins"
  ('tches', 0.01653265223200796), # instead of "tâches"
...

**Comment by MaartenGr** [comment]
A default BERTopic model has the following pipeline:

SBERT -> UMAP -> HDBSCAN  -> CountVectorizer -> c-TF-IDF

In the pipeline above, the actual processing of documents for generating the topics is done in the `CountVectorizer` step. Here, we can preprocess the text in a number of ways. The default `CountVectorizer`, however, strips accents that in your case lead to an unwelcome output. To prevent this, you can use the `strip_accents` parameter in the `CountVectorizer` as mentioned [here](https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html) and [here](https://stackoverflow.com/questions/16080726/special-characters-in-countvectorizer-scikit-learn). 

It should fix your issue!

**Comment by Arthur095** [comment]
Thank you for this quick reply. 

I'm a bit confused that changing the strip_accents parameter (setting either None, False, 'ascii') in the code above does not make any change. 
However, using a CountVectorizer outside the BERTopic object does work as expected and according to the documentation page. 
What's more, strip_accents parameter is also taken in account when I'm not using embeddings parameter inside the fit_transform function. I don't have any more clue.

**Comment by MaartenGr** [comment]
Ah, I think it might be because the `embedding_model` was not passed. Could you add `embedding_model=sentence_model` to your code?

**Comment by Arthur095** [comment]
It was what was causing the issue. Thank you!

**Comment by dlotfi** [comment]
When providing pre-computed embeddings, there should be no need to pass embedding_model in BERTopic init.

The root of this problem is that when embedding_model is None, self.language will remain "english" by default which causes 
all non-English characters to be removed in _preprocess_text (_bertopic.py : line 3787). 

As a workaround, one could pass language=None when initializing BERTopic.
