### ISSUE TITLE
Partial fit using GPU and River

### ISSUE THREAD

**Issue by suglou** [MaartenGr/BERTopic#836]
Hi Maarten,

I am trying to run an online BERTopic training using the River package but the training seems to take significantly longer than when using a HDBSCAN cluster model. Fitting the model on approx. 100k docs using the traditional model architecture below takes about 2 minutes.

```
`umap_model = UMAP(
    n_neighbors=20, 
    n_components=10, 
    min_dist=0.0, 
    metric='cosine'
)

hdbscan_model = HDBSCAN(
    min_cluster_size=100, 
    metric='euclidean', 
    cluster_selection_method='eom', 
    prediction_data=True
)

vm = CountVectorizer(
    ngram_range=(1, 2), 
    stop_words="english",
    min_df = 5
)

topic_model_ngram = BERTopic(
    umap_model = umap_model, 
    hdbscan_model=hdbscan_model,  
    verbose=True, 
    top_n_words=10,
    low_memory=False, 
    calculate_probabilities=False, 
    vectorizer_model=vm)`
```

When trying to replace HDBSCAN with the DBSTREAM cluster object from River, this training time jumps up to 35+ mins. Running verbose=True shows that the time increase is entirely in the clustering step.

```
'cluster_model = River(cluster.DBSTREAM())
vectorizer_model = OnlineCountVectorizer(stop_words="english")
ctfidf_model = ClassTfidfTransformer(reduce_frequent_words=True, bm25_weighting=True)
umap_model = UMAP(
    n_neighbors=20, 
    n_components=10, 
    min_dist=0.0, 
    metric='cosine'
)

topic_model = BERTopic(
    umap_model = umap_model,
    hdbscan_model=cluster_model, 
    vectorizer_model=vectorizer_model, 
    ctfidf_model=ctfidf_model,
    calculate_probabilities=False,
    low_memory=False,
    verbose=True
)`
```

I know that there has been some success with cuML but is there a way to combine that with River to get fast online learning?

Thanks

**Comment by MaartenGr** [comment]
The `.partial_fit` function is dependent on the sub-models that you use and differs a bit from how you train with `.fit`. In practice, the `.partial_fit` can be slower as you want to use it in batches and not use `.partial_fit` only once. Knowing that in general `.fit` can be a bit faster than `.partial_fit`, it depends mostly on the sub-model that you are using. In your case, DBSTREAM can be quite a bit slower. Instead,  you can use MiniBatchKMeans instead. However, I would highly advise reading through the documentation of online BERTopic [here](https://maartengr.github.io/BERTopic/getting_started/online/online.html) as it also gives some advice on the sub-models to use. For example, I can see that you are using UMAP, which does not natively support a `.partial_fit` and might hurt the performance of online modeling if it is not fit on a sufficient amount of data before doing the batch modeling.

**Comment by suglou** [comment]
I see, I chose UMAP since it performs significantly better than IncrementalPCA even when initially fitted with only 100k samples vs. IncrementalPCA being fitted with 500k samples (in 100k batches).

If I understand correctly, UMAP will only fit once for the first batch of documents that are passed to it, and potentially over many batches, may end up degrading in performance vs IncrementalPCA if the initial sample deviates too much from incoming batch data?

**Comment by MaartenGr** [comment]
> I see, I chose UMAP since it performs significantly better than IncrementalPCA even when initially fitted with only 100k samples vs. IncrementalPCA being fitted with 500k samples (in 100k batches).

If you do not expect the data to change tremendously, as in going from one domain to entire other domain, then it should be okay fitting UMAP on 100k representative samples vs using IncrementalPCA. The idea here is that if you feed UMAP with enough representative samples and you do not expect the documents to change that much (like training UMAP on medical texts and then switching over to financial texts), I think it should be okay. 

> If I understand correctly, UMAP will only fit once for the first batch of documents that are passed to it, and potentially over many batches, may end up degrading in performance vs IncrementalPCA if the initial sample deviates too much from incoming batch data?

Yep, but that really depends on how much the deviation is. Online learning is typically performed in a setting with a single domain that might change slightly, so it might not be necessary.

**Comment by suglou** [comment]
I see, thanks for the clarifications!
