### ISSUE TITLE
using topics_over_time after online learning with River

### ISSUE THREAD

**Issue by dannylesmy** [MaartenGr/BERTopic#839]
Im trying to visualize topics over time on trump tweets. I followed your instruction about using River with bertopic (https://maartengr.github.io/BERTopic/getting_started/online/online.html#hdbscan) but im getting a value error when I try to use the topics_over_time function : "ValueError: All arrays must be of the same length" . Imanually check the length of the timestamps, the tweets and the list of topics and they are equal. P.s. If im not using River streaming all works fine
I really appreciate your help 
Im using bertopic version 0.12.0
![trump_code](https://user-images.githubusercontent.com/63964315/201523268-397c539d-d47d-418b-bcca-385889b8ec49.PNG)
![trump_error](https://user-images.githubusercontent.com/63964315/201523269-0344a617-6b34-433a-a074-f9de6389363b.PNG)

**Comment by MaartenGr** [comment]
Did you make sure to update the `river_topic_model_online.topics_` according to the guide [here](https://maartengr.github.io/BERTopic/getting_started/online/online.html#example)? From your code, it seems that you are creating `topics_river` but not actually passing it to your topic model. I believe you should also run the following:

```python
river_topic_model_online.topics_ = topics_river
```

**Comment by dannylesmy** [comment]
No I forgot update the model topics. thank you very much for your quick answer. Now Its working
