### ISSUE TITLE
Update about c-tf-idf

### ISSUE THREAD

**Issue by dopc** [MaartenGr/BERTopic#84]
I just want to ask the reason of update about c-tf-idf in v0.6.

Do you have general practical output result of this change for keyword selection? Can you share these results if any?

**Comment by MaartenGr** [comment]
The update improved the stability of the algorithm by making it easier to scale c-TF-IDF values with the number of documents. Previously, I tested mostly on datasets with a similar size which generalized poorly to other datasets. By focusing on the average number of samples across documents the stability of the c-TF-IDF increases.

**Comment by dopc** [comment]
Thanks a lot!
