### ISSUE TITLE
Different topics after training on the same dataset. 

### ISSUE THREAD

**Issue by minchi19** [MaartenGr/BERTopic#841]
Hi,
If I am running BerTopic on my local machine [Windows 10] different times I am able to reproduce my results but same code on Azure Databricks I am not able to reproduce the same results on different iterations.
I want my results to be same on same machine different iterations.
Note - already set random state variable in UMAP.

UMAP version - '0.5.3'
BerTopic version - '0.12.0'

Code
`umap_model = UMAP(n_neighbors=15, n_components=10, min_dist=0.0, metric='cosine', random_state=42)

model = BERTopic(umap_model=umap_model,language="english",verbose=True,n_gram_range=(1,2),top_n_words = 9,nr_topics=21,calculate_probabilities=True)`

Thanks

**Comment by MaartenGr** [comment]
I believe the differences in results across machines stem from using UMAP. Unfortunately, I do not have a solution for that right now other than using a different dimensionality reduction technique. There is a longer thread about that issue [here](https://github.com/MaartenGr/BERTopic/issues/559) that might be worthwhile to read through.

**Comment by minchi19** [comment]
Hi,
Thanks for replying so quickly.
Apart from UMAP, PCA what all different dimensionality reduction we can use.
I only see these two on documentation.

For now I think saving model and then loading it while performing transform will work.

Apart from UMAP + HDBSCAN combination what all combination you think could one try?
(My dataset is of Instagram posts and I am trying to convert unsupervised topic modelling to supervised multi label classification)

Thanks

**Comment by MaartenGr** [comment]
> Apart from UMAP, PCA what all different dimensionality reduction we can use.
I only see these two on documentation.

You can use any dimensionality reduction technique as long as it supports a `.fit`  and a `.transform` function. You can find more about that in the documentation [here](https://maartengr.github.io/BERTopic/getting_started/dim_reduction/dim_reduction.html). 

> Apart from UMAP + HDBSCAN combination what all combination you think could one try?
(My dataset is of Instagram posts and I am trying to convert unsupervised topic modelling to supervised multi label classification)

PCA + k-Means has been tried often, I believe you could also use TruncatedSVD if you have a sparse input. There is also a hierarchical variation of UMAP, called [HUMAP](https://github.com/wilsonjr/humap) which might also be worthwhile to try out. Lastly, from a clustering perspective, I heard some talking about [Genie](https://github.com/gagolews/genieclust) but have not tried it out myself yet.

**Comment by minchi19** [comment]
Hey,
Thanks for your suggestions.
PCA + K-means worked beautifully.
I more thing I have noticed is we are getting nearly same topics by setting random state, but there are sequence is jumbled like iteration 1 topic 1 become iteration 2 topic 4.
Thanks

**Comment by MaartenGr** [comment]
In principle, by setting the random state for both PCA and k-Means, I believe that you should always get the exact same output as long as you are working in the exact same environment.

**Comment by MaartenGr** [comment]
Due to inactivity, I'll be closing this issue for now. If, however, you want to continue the discussion or re-open the issue, feel free to reach out!
