### ISSUE TITLE
bertopic may do not use gpu on my machine

### ISSUE THREAD

**Issue by Buaasinong** [MaartenGr/BERTopic#843]
Hi, 
I write my code as follow and want to use **gpu** to speed up BERTopic. I have seen  " The GPU is automatically used", but it seems like that the number of GPU processes on my server is not increasing. Can you give some suggestions?
![image](https://user-images.githubusercontent.com/47075583/202637977-39236469-0851-4f1e-b5f9-cc6a81e23789.png)

**Comment by Buaasinong** [comment]
Thanks for replying so quickly.
I'm running a Bertopic, and I think it's first step. And I will try with your code suggestion and get back to you.Unfortunately, my python is 3.7, maybe I can use cuml later.
![image](https://user-images.githubusercontent.com/47075583/202642580-4ad12dd8-fc8d-47a6-9c12-71ce5b2862db.png)

**Comment by Buaasinong** [comment]
I have tried your code, but the number of processes for the GPU still doesn't seem to change. 
![image](https://user-images.githubusercontent.com/47075583/202644156-930f3927-1671-4b7c-9a2f-fa253b5629d0.png)

**Comment by Buaasinong** [comment]
By the way, there are four graphics cards on the server, do I need to specify it to run properly on the GPU? I have used `os.environ["CUDA_VISIBLE_DEVICES"]="0"`, but it doesn't seem to work either.  (T＿T)

**Comment by Buaasinong** [comment]
> When you are using `sentence-transformers` it should indeed use the GPU automatically but only for the embedding step. Since you have `verbose=True` you could check if it indeed uses the GPU when embedding the documents. You can also check that with something like this:
> 
> ```python
> from sentence_transformers import SentenceTransformer
> 
> # This is the model that you are using when selecting `language="chinese (simplified)"`
> sentence_model = SentenceTransformer("paraphrase-multilingual-MiniLM-L12-v2")
> embeddings = sentence_model.encode(my_docs, show_progress_bar=True)
> ```
> 
> the UMAP and HDBSCAN models, however, are not by default GPU accelerated. To enable that, please follow along with the guide [here](https://maartengr.github.io/BERTopic/getting_started/tips_and_tricks/tips_and_tricks.html#gpu-acceleration).

**Comment by Buaasinong** [comment]
> When you are using `sentence-transformers` it should indeed use the GPU automatically but only for the embedding step. Since you have `verbose=True` you could check if it indeed uses the GPU when embedding the documents. You can also check that with something like this:
> 
> ```python
> from sentence_transformers import SentenceTransformer
> 
> # This is the model that you are using when selecting `language="chinese (simplified)"`
> sentence_model = SentenceTransformer("paraphrase-multilingual-MiniLM-L12-v2")
> embeddings = sentence_model.encode(my_docs, show_progress_bar=True)
> ```
> 
> the UMAP and HDBSCAN models, however, are not by default GPU accelerated. To enable that, please follow along with the guide [here](https://maartengr.github.io/BERTopic/getting_started/tips_and_tricks/tips_and_tricks.html#gpu-acceleration).

Oh, I think I know where the problem is.
`RuntimeError: The NVIDIA driver on your system is too old (found version 10020). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org/ to install a PyTorch version that has been compiled with your version of the CUDA driver.`

**Comment by MaartenGr** [comment]
@Buaasinong Glad to hear that you found the source of the issue. It indeed seems like upgrading your driver should fix the issue!
