### ISSUE TITLE
BERTopic clusters

### ISSUE THREAD

**Issue by rashaduph26** [MaartenGr/BERTopic#844]
Hi @MaartenGr, 

First of all, thank you for BERTopic. It is really useful. 

I have a one generalized question. Is it possible to define the specific clusters in BERTopic? For example, if the cluster topics are let's say, "New York museums", "Oslo museums", and the code looks for texts that only matches for these two clusters, and the ones that do not match are still under -1. 

I have tried HDBSCAN, KMeans, Agglomerative, but all assigns the clusters automatically. 

Thanks in advance, 
Rashad Naghiyev

**Comment by MaartenGr** [comment]
I believe this is related to [semi-supervised](https://maartengr.github.io/BERTopic/getting_started/supervised/supervised.html) or [guided](https://maartengr.github.io/BERTopic/getting_started/guided/guided.html) topic modeling. However, it will not do exactly as you mention since it will only nudge the topic creation towards those two cluster topics. In order to do something like this, you will need some semi-supervised clustering model of which there are not many out there aside from connectivity constraint-like algorithms.

**Comment by rashaduph26** [comment]
Thanks for the comment! It really helped me to build a model. 

One additional question. Is it possible to use OpenAI Embedding models in Bertopic?

For example: 
embedding_model = 'text-embedding-ada-002'

model = BERTopic(
  embedding_model=embedding_model
) 

model.fit_transform(train_data)

I have tried to use text-embeddings-ada-002 embedding model that OpenAI released lately, but as I understood, Bertopic is only taking huggingface's models as embedding model, right?

**Comment by MaartenGr** [comment]
@rashaduph26 Although BERTopic supports quite a [number of embedding models](https://maartengr.github.io/BERTopic/getting_started/embeddings/embeddings.html), it is not possible to pass the OpenAI models themselves in BERTopic but it is possible to pass the embeddings when fitting the model. You can find more about that [here](https://maartengr.github.io/BERTopic/getting_started/embeddings/embeddings.html#custom-embeddings). With respect to OpenAI, I think it should be done as follows:

```python
# Generate OpenAI embeddings
def get_embedding(text, model="text-embedding-ada-002"):
   return openai.Embedding.create(input = [text], model=model)['data'][0]['embedding']
 
embeddings = [get_embedding(doc) for doc in docs]

# Pass them to BERTopic
topic_model = BERTopic()
topics, probs = topic_model.fit_transform(docs, embeddings)
```

**Comment by MaartenGr** [comment]
Due to inactivity, I'll be closing this issue. Let me know if you want me to re-open the issue!
