### ISSUE TITLE
Error installing hdbscan on AWS Sagemaker

### ISSUE THREAD

**Issue by mvitha** [MaartenGr/BERTopic#845]
Hello! Love this library, but have trouble moving it from local to AWS Sagemaker Studio

it seems like I am unable to install hdbscan and am getting below error

ERROR: Failed building wheel for hdbscan
Failed to build hdbscan
ERROR: Could not build wheels for hdbscan, which is required to install pyproject.toml-based projects

Solutions from previous issues have not worked... any other ideas?

**Comment by MaartenGr** [comment]
I believe the entire error message will also state something like this:

```
  error: command 'gcc' failed with exit status 1                                                                       
  ----------------------------------------                                                                             
  ERROR: Failed building wheel for hdbscan                                                                             
  Running setup.py clean for hdbscan                                                                                   
Failed to build hdbscan                                                                                                
ERROR: Could not build wheels for hdbscan which use PEP 517 and cannot be installed directly  
```

which is the underlying issue here. In order to fix that, I believe running the following should suffice before installing HDBSACN:

```bash
apt-get update 
apt-get install -y build-essential
```

**Comment by mvitha** [comment]
Thanks so much for the prompt reply! The code worked for installing hdbscan, but I am still receiving the below error once I have pip installed joblib, bertopic, hbscan, and sentence-transformers


from bertopic import BERTopic

_ModuleNotFoundError: No module named 'bertopic'_

**Comment by MaartenGr** [comment]
@mvitha When it cannot find the module, then it is likely due to the environment. Make sure that, if you are in jupyter for example, the correct kernel is selected. You can also check whether it is correctly installed (in the right environment) with `pip freeze`. If that does not work, I would advise starting from a fresh environment and installing it there.

**Comment by MaartenGr** [comment]
Due to inactivity, I'll be closing this issue. Let me know if you want me to re-open the issue!
