### ISSUE TITLE
Documentation of `BERTopic.partial_fit` is not consistent with code when `umap_model` has no `partial_fit` method

### ISSUE THREAD

**Issue by XiaomoWu** [MaartenGr/BERTopic#849]
In documentation about [online training](https://maartengr.github.io/BERTopic/getting_started/online/online.html) it says 

> Moreover, you can use dimensionality reduction algorithms that do not support .partial_fit functions but do have a .fit function to first train it on a large amount of data and then continously add documents. The dimensionality reduction **will not be updated** but may be trained sufficiently to properly reduce the embeddings without the need to continuously add documents.

So my understanding of the sentence "The dimensionality reduction **will not be updated**" is that if `umap_model` has no `partial_fit` method (e.g., the default `UMAP` class), then at the first run, BERTopic will try to fit `umap_model` while in the following runs, it will only call the `transform` method and skip the `fit` stage. 

However, in the source code of [`_reduce_dimensionality`](https://github.com/MaartenGr/BERTopic/blob/e5a2912a04624af9898ca295b5204c830eb6ef4d/bertopic/_bertopic.py#L2274):
```python
# Partial fit
if partial_fit:
    if hasattr(self.umap_model, "partial_fit"):
        self.umap_model = self.umap_model.partial_fit(embeddings)
    elif self.topic_representations_ is None:
        self.umap_model.fit(embeddings)
```

We can see even if `umap_model` doesn't support a `partial_fit` method, BERTopic will try to fit the dimensional reduction method anyway. That means the dimensional model will be updated each time `partial_fit` is run. This contradicts the statement in the documentation that 

> The dimensionality reduction **will not be updated** but may be trained sufficiently to properly reduce the embeddings without the need to continuously add documents.

**Comment by MaartenGr** [comment]
The variable `self.topics_representations_` starts out as a None value. When you run `partial_fit` the very first time, it gets filled with certain topic representation. This means that when you run `partial_fit` a second time it is **not** a None value. 

In other words, the following will not be triggered:

```python
elif self.topic_representations_ is None:  # This statement only holds true for the first `partial_fit` run
    self.umap_model.fit(embeddings)
```

Thus, based on that `elif` statement, it actually does not seem that the dimensional model gets updated each time `partial_fit` is run. 

Whenever you run the `partial_fit` the very first time, the variable `self.topic_representations_` gets filled. It

**Comment by XiaomoWu** [comment]
@MaartenGr Thanks for the clarification! I'm closing the issue now.
