### ISSUE TITLE
dictionary changed size during iteration

### ISSUE THREAD

**Issue by Siegi96** [MaartenGr/BERTopic#85]
Hey, when i want to plot my topics with visualize_topics() i get the following errormessage:

`---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-33-b4310f82b15e> in <module>()
      1 print(bmodel.get_topic(-1))
----> 2 bmodel.visualize_topics()
      3 

5 frames
/usr/local/lib/python3.7/dist-packages/plotly/express/_core.py in build_dataframe(args, attrables, array_attrables)
    911         # argument_list and field_list ready, iterate over them
    912         # Core of the loop starts here
--> 913         for i, (argument, field) in enumerate(zip(argument_list, field_list)):
    914             length = len(df_output)
    915             if argument is None:

RuntimeError: dictionary changed size during iteration`

getTopic(),.... works fine.

Greets

**Comment by MaartenGr** [comment]
You typically get this issue if you did not install the correct plotly version. I would advise you to create a fresh environment and install bertopic as follows:

```bash
pip install bertopic[visualization]
```

**Comment by Siegi96** [comment]
Thanks!
