### ISSUE TITLE
AttributeError: 'BERTopic' object has no attribute 'get_feature_names_out'

### ISSUE THREAD

**Issue by chrislalk** [MaartenGr/BERTopic#852]
Hi there!

I was running topics per classes for a large dataset (100k documents). When I ran topics per class, the following error occured:

 `AttributeError: 'BERTopic' object has no attribute 'get_feature_names_out'`

My code is: 

```
import re
import os
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from bertopic import BERTopic

# df_pat contains all documents and classes
list_pat = df_pat["Patient"].tolist()
classes_pat = df_pat["Class"]

model = BERTopic(language="german", top_n_words = 10, nr_topics="auto", n_gram_range = (1,3), calculate_probabilities=True, verbose = True)
topics, probabilities = model.fit_transform(list_pat)


model_div = model # duplicate Model
# diversify model
div = BERTopic(diversity=0.2)
model_div.update_topics(list_pat, vectorizer_model=div)
model_div.get_topic(9)

topics_per_class = model_div.topics_per_class(list_pat, classes=classes_pat)
```
I use python 3.10 on PyCharm and I have installed bertopic==0.12.0

Any suggestions, what could be causing the error here?

**Comment by MaartenGr** [comment]
> div = BERTopic(diversity=0.2)
> model_div.update_topics(list_pat, vectorizer_model=div)

You are passing an empty `BERTopic` model as the vectorizer, which does not work since BERTopic is not a vectorizer model. You can find more about how to use vectorizers in BERTopic [here](https://maartengr.github.io/BERTopic/getting_started/vectorizers/vectorizers.html).

**Comment by chrislalk** [comment]
Thanks a lot! That did it!
