### ISSUE TITLE
.find_topics(text) throwing error AttributeError: 'Transformer' object has no attribute 'do_lower_case'

### ISSUE THREAD

**Issue by debabrata963** [MaartenGr/BERTopic#86]
Hello,

Previously I have made a model and saved it on my device. Now when I am trying to load the model and get the topics of a word I am getting this error.

This is my code:
```
model = BERTopic.load('/content/drive/MyDrive/Colab Notebooks/model')
pred = model.find_topics("course")[0][0]
```
And this is the error that I'm getting:
```
Exception ignored in: <generator object tqdm_notebook.__iter__ at 0x7fa8b86c9650>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/tqdm/notebook.py", line 220, in __iter__
    self.sp(bar_style='danger')
AttributeError: 'tqdm_notebook' object has no attribute 'sp'
---------------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-70-cf00a7f54361> in <module>()
      1   model = BERTopic.load('/content/drive/MyDrive/Colab Notebooks/model')
----> 2   pred = model.find_topics("course")[0][0]

5 frames
/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py in __getattr__(self, name)
    946                 return modules[name]
    947         raise AttributeError("'{}' object has no attribute '{}'".format(
--> 948             type(self).__name__, name))
    949 
    950     def __setattr__(self, name: str, value: Union[Tensor, 'Module']) -> None:

AttributeError: 'Transformer' object has no attribute 'do_lower_case'
```

I can't figure it out, any help is very appreciated.

**Comment by MaartenGr** [comment]
If I save a new model using BERTopic v0.6, load it, and then use `model.find_topics("some string here")` then it seems to work for me. 

This means that it is likely causes by something that happened between you saving the model and subsequently loading it. Did you update BERTopic versions between instances? Which BERTopic version are you using? Are you using the exact same environment or a different one?

**Comment by debabrata963** [comment]
I tried to do it using the previous version (v0.5) also, but it didn't work.

Moreover, all the other functions are working fine. Only ```.find_topics()``` is not working.

**Comment by MaartenGr** [comment]
Are you using the same environment you used when you first saved the model? Do you know with which version of BERTopic you saved the file?

**Comment by debabrata963** [comment]
Yes I am using the same virtual environment. 
I saved the model in v0.5.

**Comment by MaartenGr** [comment]
Strange, I tried to reproduce the issue by first training a BERTopic v0.5 topic model, save the model, load it in a new instance, and finally use `model.find_topics("some search term")` and I cannot reproduce the issue. Were any packages updated between saving and loading the topic model? 

Can you reproduce the issue with a new environment? If so, that would greatly help in finding the issue.

**Comment by debabrata963** [comment]
I don't remember updating any package between saving and loading the model. 

I can reproduce it only if I know where this error came from. Without that, I won't be able to reproduce it.

**Comment by MaartenGr** [comment]
You likely do not need to know where the error came from in order to reproduce the issue. With these kinds of issues, it is sufficient for me if you can retrace your steps and execute them as you did before. If you then run into the same issue we have a pipeline of steps that allows us to reproduce the behavior. With that pipeline, I can start looking where the error came from.

**Comment by debabrata963** [comment]
I repeated all the possible previous steps but did not recieve any error.
