### ISSUE TITLE
got the same embedding_model in version 0.10.0,  when using any of hugging face pipeline models

### ISSUE THREAD

**Issue by zhzhx2008** [MaartenGr/BERTopic#860]
Hi, I found something wrong with the code of bertopic version==0.10.0.

bertopic==0.10.0
transformers==4.18.0
torch==1.11.0

my code：

    model = AutoModel.from_pretrained(model_name)
    tokenizer = AutoTokenizer.from_pretrained(model_name)
    config = AutoConfig.from_pretrained(model_name)
    hf_model = pipeline("feature-extraction", model=model, tokenizer=tokenizer, config=config)
    topic_model = BERTopic(embedding_model=hf_model)
    predictions, probabilities = topic_model.fit_transform(documents)

In debug mode, When step into fit_transform function of this file,
 "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/bertopic/_bertopic.py",
I found that, no matter I use any of hugging face pipeline models, select_backend function in below always return the same embedding_model,  SentenceTransformerBackend("all-MiniLM-L6-v2").
It shouldn't be like this, right?

part of /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/bertopic/_bertopic.py

    # Extract embeddings
    if embeddings is None:
        self.embedding_model = select_backend(self.embedding_model,
                                              language=self.language)

**Comment by MaartenGr** [comment]
Thank you for sharing this. Do note that the current release is v0.12 and that v0.13 is not that far away. I would advise upping your BERTopic version to prevent this issue.

**Comment by zhzhx2008** [comment]
I got it, thanks for your advise.
