### ISSUE TITLE
ValueError: operands could not be broadcast together with shapes (96,) (0,) 

### ISSUE THREAD

**Issue by mamingsuper** [MaartenGr/BERTopic#862]
I run     topics, probs = topic_model.fit_transform(maxtext)

but got   

Output exceeds the [size limit](command:workbench.action.openSettings?[). Open the full output data [in a text editor](command:workbench.action.openLargeOutput?ca3bb754-69f1-4f58-a5da-8db20a5e48e3)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[116], line 1
----> 1 topics, probs = topic_model.fit_transform(maxtext)

ValueError: operands could not be broadcast together with shapes (96,) (0,) 

Any advice is highly appreciated!

**Comment by xinzhuohkust** [comment]
I got the same error when I was modeling. 

```
Error in py_call_impl(callable, dots$args, dots$keywords) : 
ValueError: operands could not be broadcast together with shapes (96,) (0,)
```

**Comment by MaartenGr** [comment]
Could you share your entire code for training BERTopic? Also, what kind of variable is `maxtext`? Is that a List of strings or a single document?

**Comment by MaartenGr** [comment]
Due to inactivity, I'll be closing this issue. Let me know if you want me to re-open the issue!
