### ISSUE TITLE
BERTopic.load() Error

### ISSUE THREAD

**Issue by njiang8** [MaartenGr/BERTopic#863]
@MaartenGr Hope you are doing well! I have used the latest version of bertopic (i.e., 0.12.0), but this morning one of my save models can not be loaded. Here is the error message I have got. 

Looking forward to your reply!
Thank you!

<img width="812" alt="Screenshot 2022-12-02 at 2 18 33 PM" src="https://user-images.githubusercontent.com/42579046/205369831-01e5d276-6ad4-41b5-a67c-84d9e7335507.png">

**Comment by MaartenGr** [comment]
Did you make sure that the environments in which you saved the model and loaded the model are the same? In other words, do they not only contain packages with the same dependencies but are they also in the same Python version?

**Comment by wfkhrrzi** [comment]
I realized that we're both using colab and encountered this error. Environment-wise, I believe the python version is still the same. I can't figure out whether the dependencies used when saving the model are similar to the current ones because I didn't save the list of dependencies. But I have used colab from the beginning and 2 weeks before it was working fine.

**Comment by njiang8** [comment]
> 
Thanks for your reply. The model was saved using the bertopic (i.e., 0.12.0), and so does the loading. I am using colab, I am not sure how they manage the package. As for the python version, I don't think colab changed the python version.

**Comment by njiang8** [comment]
> I realized that we're both using colab and encountered this error. Environment-wise, I believe the python version is still the same. I can't figure out whether the dependencies used when saving the model are similar to the current ones because I didn't have a record of previous dependencies (would be very helpful if someone can guide me on this 😅). But I have used colab from the beginning and 2 weeks before it was working fine.

Is the error still there in your code? What's your python version for the Colab now? Mine is 3.8.15

**Comment by wfkhrrzi** [comment]
> Is the error still there in your code? What's your python version for the Colab now? Mine is 3.8.15

Yes, the error is still there. I have the same python version as well.

**Comment by njiang8** [comment]
Hello all! @MaartenGr @wfkhrrzi 
I just found out that Colab upgraded their python version to 3.8. This might be the reason causing our loading issue. I downgraded the python from 3.8.15 to 3.7.15. Now my model can be loaded properly. You can try to downgrade your Colab python and then load your model.

<img width="589" alt="Screenshot 2022-12-05 at 9 24 11 AM" src="https://user-images.githubusercontent.com/42579046/205667081-941d69c7-8d44-4b4e-9db6-f548c341c61e.png">

**Comment by njiang8** [comment]
I have used these two sources to change my python version in Colab. Hope it helps!

1: [https://www.datasciencelearner.com/change-python-version-in-google-colab-steps/](url)
2: [https://stackoverflow.com/questions/60775160/install-python-3-8-kernel-in-google-colaboratory](url)
<img width="799" alt="Screenshot 2022-12-05 at 1 22 05 PM" src="https://user-images.githubusercontent.com/42579046/205713041-18de2961-59ae-4eb6-9ffa-075423d55d4d.png">

**Comment by RanAl2020** [comment]
thank you, it work fine with when I change the python version, but the error still there when I try to install bertopic.
any help?

**Comment by RanAl2020** [comment]
thank you, it work fine with me when I change the python version, but the error still there when I try to install bertopic.
any help?

**Comment by njiang8** [comment]
> thank you, it work fine with me when I change the python version, but the error still there when I try to install bertopic. any help?

Check this link
[Colab update](https://medium.com/google-colab/colab-updated-to-python-3-8-4922f9970a72)

You can search "Use fallback runtime version" by clicking the icon circled in this Figure. I think it will not last long. I have redone everything with the new python version and locally. 

<img width="1155" alt="Screenshot 2022-12-05 at 4 20 08 PM" src="https://user-images.githubusercontent.com/42579046/205746727-a2d88c8d-b2eb-41c0-bc84-2722c6f6f4bf.png">

**Comment by Na987** [comment]
Hello all
Before I worked on Bert topic model in Colab with Version 3.7. 
But now the Version updated to 3.8 and I can not load Bert model.

I used the below command to downgrade Version to 3.7 in colab:

!sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.7 1

but give me the message: update-alternatives: error: alternative path /usr/bin/python3.7 doesn't exist


Could you please share the commands that should be used to downgrade python version to 3.7 in colab?
and which commands should be used to re-install Bert model to fix the error for load bert model?

**Comment by RanAl2020** [comment]
> I have used these two sources to change my python version in Colab. Hope it helps!
> 
> 1: [https://www.datasciencelearner.com/change-python-version-in-google-colab-steps/](url) 2: [https://stackoverflow.com/questions/60775160/install-python-3-8-kernel-in-google-colaboratory](url) <img alt="Screenshot 2022-12-05 at 1 22 05 PM" width="799" src="https://user-images.githubusercontent.com/42579046/205713041-18de2961-59ae-4eb6-9ffa-075423d55d4d.png">

thanks for your help, I uses this command to change my python version in Colab to 3.7, but when I try to install bertopic give me an error, could you please show us how to install it , this what i was used
I use this command
pip install bertopic
and  I got this error
`note: This error originates from a subprocess, and is likely not a problem with pip.

ERROR: Failed building wheel for hdbscan
Failed to build hdbscan
ERROR: Could not build wheels for hdbscan, which is required to install pyproject.toml-based projects`
