### ISSUE TITLE
python setup.py egg info did not run successfully 

### ISSUE THREAD

**Issue by li-yuduan** [MaartenGr/BERTopic#864]
@MaartenGr  Hope you are doing well! I have used the latest version of bertopic (i.e., 0.12.0), but i can not install bertopic because of the followng error. Here is the error message I have got.
Looking forward to your reply!
Thank you!
<img width="962" alt="image" src="https://user-images.githubusercontent.com/65487612/205616562-bf0f6754-6703-47fc-8aa3-57122965370c.png">

**Comment by MaartenGr** [comment]
In what kind of environment are you currently working? Which python and pip versions do you have? Also, how did you exactly run the install before getting this error?

**Comment by MaartenGr** [comment]
Due to inactivity, I'll be closing this issue. Let me know if you want me to re-open the issue!
