### ISSUE TITLE
TopicMapper mappings don't make sense

### ISSUE THREAD

**Issue by yunyu** [MaartenGr/BERTopic#865]
I have a set of topics, and try merging the following topic IDs with .merge_topics (along with the documents that were originally passed in):

```
to_merge = [[0, 13], [45, 6, 4, 34], [56, 47]]
topic_model.merge_topics(orig, to_merge)
```

I now call `topic_model.topic_mapper_.get_mappings(original_topics=True)`. I would expect that 0 and 13 in the original mappings would point to the same topic ID in the result (and same for the other merges), but they don't (and neither do the other 2 merges):

```
{-1: -1,
 0: 0,
 1: 0,
 2: 1,
 3: 48,
 4: 44,
 5: 1,
 6: 43,
 7: 0,
 8: 0,
 9: 29,
 10: 3,
 11: 10,
 12: 18,
 13: 25,
 14: 25,
 15: 14,
 16: 52,
 17: 35,
 18: 37,
 19: 16,
 20: 2,
 21: 36,
 22: 45,
 23: 39,
 24: 6,
 25: 51,
 26: 23,
 27: 34,
 28: 49,
 29: 11,
 30: 40,
 31: 28,
 32: 27,
 33: 13,
 34: 4,
 35: 12,
 36: 26,
 37: 21,
 38: 15,
 39: 38,
 40: 33,
 41: 41,
 42: 5,
 43: 32,
 44: 30,
 45: 50,
 46: 17,
 47: 7,
 48: 31,
 49: 8,
 50: 46,
 51: 47,
 52: 22,
 53: 24,
 54: 20,
 55: 9,
 56: 19,
 57: 42}
```

What is going on/am I misinterpreting how topic_mapper_ works? I tried `.get_representative_docs` with the remapped IDs and they still don't match. I am running version 0.12.0, and am not running any code other than print statements between `.merge_topics` and `.get_mappings`.

**Comment by MaartenGr** [comment]
The `.topic_mapper_` is a bit more involved than you what describe here. When you run BERTopic the very first time, it generates a number of clusters. These clusters are then sorted based on their relative frequency. This process is already a mapping from the original topics, which are generated through clustering, to the sorted topics. When you run `topic_model.topic_mapper_.get_mappings(original_topics=True)` you get the mappings from the unsorted topics as generated by the clustering algorithm to the most current state. In your case, you have the generated the mappings between the unsorted topics and the merged topics. Instead, it might be worthwhile to check out `topic_model.topic_mapper_.mappings_` instead. There, you will find all the mappings at every single step. In your case, you would have to take the topics in the last two columns.

**Comment by yunyu** [comment]
Understood, thanks for the clarification
