### ISSUE TITLE
Loading bertopic model error

### ISSUE THREAD

**Issue by tanstephenjireh** [MaartenGr/BERTopic#867]
Hi not sure why I'm getting this error when loading a bertopic model in google colab

TypeError                                 Traceback (most recent call last)
[<ipython-input-5-6ff854248653>](https://localhost:8080/#) in <module>
----> 1 cust_model = BERTopic.load('/content/""/bertopic_Q4.model')

5 frames
[/usr/local/lib/python3.8/dist-packages/bertopic/_bertopic.py](https://localhost:8080/#) in load(cls, path, embedding_model)
   2195                 topic_model.embedding_model = select_backend(embedding_model)
   2196             else:
-> 2197                 topic_model = joblib.load(file)
   2198             return topic_model
   2199 

[/usr/local/lib/python3.8/dist-packages/joblib/numpy_pickle.py](https://localhost:8080/#) in load(filename, mmap_mode)
    646         filename = getattr(fobj, 'name', '')
    647         with _read_fileobject(fobj, filename, mmap_mode) as fobj:
--> 648             obj = _unpickle(fobj)
    649     else:
    650         with open(filename, 'rb') as f:

[/usr/local/lib/python3.8/dist-packages/joblib/numpy_pickle.py](https://localhost:8080/#) in _unpickle(fobj, filename, mmap_mode)
    575     obj = None
    576     try:
--> 577         obj = unpickler.load()
    578         if unpickler.compat_mode:
    579             warnings.warn("The file '%s' has been generated with a "

[/usr/lib/python3.8/pickle.py](https://localhost:8080/#) in load(self)
   1210                     raise EOFError
   1211                 assert isinstance(key, bytes_types)
-> 1212                 dispatch[key[0]](self)
   1213         except _Stop as stopinst:
   1214             return stopinst.value

[/usr/lib/python3.8/pickle.py](https://localhost:8080/#) in load_reduce(self)
   1587         args = stack.pop()
   1588         func = stack[-1]
-> 1589         stack[-1] = func(*args)
   1590     dispatch[REDUCE[0]] = load_reduce
   1591 

[/usr/local/lib/python3.8/dist-packages/numba/core/serialize.py](https://localhost:8080/#) in _unpickle__CustomPickled(serialized)
     95     Uses `NumbaPickler` to load.
     96     """
---> 97     ctor, states = loads(serialized)
     98     return _CustomPickled(ctor, states)
     99 

TypeError: an integer is required (got type bytes)

**Comment by MaartenGr** [comment]
This has to do with the environment in which you trained the model. As with scikit-learn models, it is important that the environment remains the same as the way the internals are handled between package and python versions might differ. Google Colab just recently updated their python version to 3.8.15 which might explain why you get an error even though the model loaded fine before. You can find more about this issue in the thread [here](https://github.com/MaartenGr/BERTopic/issues/863) and ways for circumventing this.

**Comment by tanstephenjireh** [comment]
Thank you! The solution for me was just to search the "Use fallback runtime version".
