### ISSUE TITLE
get all of ducuments per topics

### ISSUE THREAD

**Issue by kimkyulim** [MaartenGr/BERTopic#870]
Hi, @MaartenGr ,

I saved the model and loaded it. 
Now I need want to get all of ducuments per topics. not get representitive_docs.

I had saw "Retrieve text docs for each topic #189", but it didn't work for me.

I need to your help.

Tks.

**Comment by MaartenGr** [comment]
After you have loaded the model, you can use the internal attributes to access the topics that were generated for each document. These topics are ordered such that you can run the following to get all documents per topic:

```python
import pandas as pd
df = pd.DataFrame({"Document": docs, "Topic": topic_model.topics_})
```

**Comment by BonzoWhitesnake** [comment]
Hi, @MaartenGr !

Is it possible to export my data (in my case xlsx document) with topic-labeled documents? Meaning, I want to transfer Bertopic's results in my datasheet. 

Thank you in advance!

**Comment by kimkyulim** [comment]
> After you have loaded the model, you can use the internal attributes to access the topics that were generated for each document. These topics are ordered such that you can run the following to get all documents per topic:
> 
> ```python
> import pandas as pd
> df = pd.DataFrame({"Document": docs, "Topic": topic_model.topics_})
> ```

Thnak u so much!
It works well :)

In addition to inquiry, How shoud I show the full text of Document?
There's a lot of document content, so the back of the document looks like that " ... " 
 I can find document manually. but They are a lot. 

Plz. I waiting for your relpy!

**Comment by MaartenGr** [comment]
@BonzoWhitesnake 

> Is it possible to export my data (in my case xlsx document) with topic-labeled documents? Meaning, I want to transfer Bertopic's results in my datasheet.

Yes, if you have a dataframe loaded in, for example `df`, then you would only need to do the following:

```python
import pandas as pd
from bertopic import BERTopic

# Load in data for training
df = pd.read_excel("my_data.xlsx")
docs = df.text.tolist()

# Train model (an example, put your own code for training here)
topics, _ = BERTopic().fit(docs)

# Export data with topic-labeled documents
df["topic"] = topics
df.to_excel("my_updated_data.xlsx")
```

I would highly advise getting familiar with pandas as it will allow you to manipulate the data and results as you wish.

**Comment by MaartenGr** [comment]
@kimkyulim 

> In addition to inquiry, How shoud I show the full text of Document?
There's a lot of document content, so the back of the document looks like that " ... "
I can find document manually. but They are a lot.

It really depends on how you want to show the full text. When it relates to a pandas dataframe, you can make it wider with something like this:

```python
pd.options.display.max_colwidth = 100
```

**Comment by BonzoWhitesnake** [comment]
> @BonzoWhitesnake
> 
> > Is it possible to export my data (in my case xlsx document) with topic-labeled documents? Meaning, I want to transfer Bertopic's results in my datasheet.
> 
> Yes, if you have a dataframe loaded in, for example `df`, then you would only need to do the following:
> 
> ```python
> import pandas as pd
> from bertopic import BERTopic
> 
> # Load in data for training
> df = pd.read_excel("my_data.xlsx")
> docs = df.text.tolist()
> 
> # Train model (an example, put your own code for training here)
> topics, _ = BERTopic().fit(docs)
> 
> # Export data with topic-labeled documents
> df["topic"] = topics
> df.to_excel("my_updated_data.xlsx")
> ```
> 
> I would highly advise getting familiar with pandas as it will allow you to manipulate the data and results as you wish.

Dear Maarten,

Thank you very much! 

I will definitely check Panda more precisely. For social scientist whole programming stuff is rather challenging to get familiar with:D

**Comment by MaartenGr** [comment]
@Trembo-Bo With the v0.13 release of BERTopic, it is now possible to extract document metadata without the need to get familiar with pandas. You can use `topic_model.get_document_info(docs)` to get that information. You can find more about that [here](https://github.com/MaartenGr/BERTopic/releases/tag/v0.13.0).
