### ISSUE TITLE
How to run GPU enabled pretrained BERTopic model on CPU?

### ISSUE THREAD

**Issue by ven716** [MaartenGr/BERTopic#876]
I have a trained BERTopic model that used GPU for acceralation. However, I also have to run this pretrained model on a machine that does not have access to a GPU. Is there a way to load a pretrained model on a CPU?

**Comment by AlfanDindaR** [comment]
hello @MaartenGr i have problem while i'm load model trained with GPU and load with CPU.
```
   1577             elif module in _compat_pickle.IMPORT_MAPPING:
   1578                 module = _compat_pickle.IMPORT_MAPPING[module]
-> 1579         __import__(module, level=0)
   1580         if self.proto >= 4:
   1581             return _getattribute(sys.modules[module], name)[0]

ModuleNotFoundError: No module named 'cuml'
```
if we run in cpu we cant install cuml.
can you explain how to load model trained with cuml and load with CPU?

**Comment by MaartenGr** [comment]
@AlfanDindaR Since cuML does not support CPU inference, it is not possible to load it in a CPU-environment. Instead, you can choose to remove the cuML models entirely before saving the model through `del topic_model.hdbscan_model` but inference would then not work on your CPU environment.

**Comment by AlfanDindaR** [comment]
Ah isee, thanks @MaartenGr
