### ISSUE TITLE
how can I get more than 10 topic words

### ISSUE THREAD

**Issue by 652994331** [MaartenGr/BERTopic#879]
Hi, I am using bertopic to cluster some docs. after I got a model, I hope I can use model.get_topic() to get 20 key words (default value is 10). i tried to modify the top_n_words as below, but it didn't work, I still got 10 keywords as result. Can you help? thanks

**Comment by 652994331** [comment]
I read an issue about my question.  and here's what u guys said:
<img width="844" alt="Screen Shot 2022-12-15 at 10 49 11" src="https://user-images.githubusercontent.com/51428350/207761118-284466a0-be7b-43b4-9ee2-7bd95bd7bb5a.png">
so does that mean I need to re-train my bertopic model and this time, set BERTopic(top_n_Words = 20) at the initialization step? or I can modify somewhere to make it work?  it really took long time to train......

**Comment by MaartenGr** [comment]
Generally, yes, you would have to re-train the topic model to increase the `top_n_words`. You can, however, with a bit of a hack, increase the top n words with the following:

```python
# Set to whatever value you want
topic_model.top_n_words = 100

# Here, it is very important that the `vectorizer_model`, `ctfidf_model`, and `n_gram_range` parameters are exactly 
# the same as when you trained the model
topic_model.update_topics(docs)
```

**Comment by 652994331** [comment]
@MaartenGr thanks for your help! I am re-training my model now. btw I noticed that there are some confusing logs as below:
<img width="641" alt="Screen Shot 2022-12-16 at 00 04 45" src="https://user-images.githubusercontent.com/51428350/207909337-d69a382b-6db7-48f5-ad28-95af7e29bcb5.png">
from the log, it seems the progress bar only mentions one batch? cause my docs are almost 900,000, but it shows only parts of them(30118) in loading process? am I using the whole dataset(90,000) in embedding transformation?

**Comment by MaartenGr** [comment]
You are indeed using the whole dataset here but SentenceTransformers is passing them as batches instead of processing them one at a time.
