### ISSUE TITLE
intertropic-dist-map & dendogram

### ISSUE THREAD

**Issue by tanstephenjireh** [MaartenGr/BERTopic#881]
Hello does intertropic distance map uses umap at the back? because it doesn't seem to match with the hierarchical clustering dendogram generated on my end.

**Comment by MaartenGr** [comment]
Yes, the intertopic distance map uses UMAP to reduce the c-TF-IDF embeddings to 2-dimensional space. You can find more about that in the code here: 

https://github.com/MaartenGr/BERTopic/blob/d63566ac1c2cf0a63a085b3bfa7049f4d9b280c2/bertopic/plotting/_topics.py#L60-L65

**Comment by tanstephenjireh** [comment]
Thanks! Is there a way though were I can change the metric to cosine instead?
