### ISSUE TITLE
Reducing the clusters - choosing the best number of clusters

### ISSUE THREAD

**Issue by As2066** [MaartenGr/BERTopic#884]
After training the model, there are about 700 clusters. How can I reduce the number of clusters, and, how can I find the best number of clusters

**Comment by MaartenGr** [comment]
You can reduce the number of clusters in several ways after training the model. You can find more about that [here](https://maartengr.github.io/BERTopic/getting_started/topicreduction/topicreduction.html). However, I would typically advise increasing the `min_topic_size` parameter as it will lead to fewer clusters being generated. 

The best number of clusters highly depends on your use case and what your objective measure is to evaluate what is "best". Unfortunately, there is no one statistic that can help you with that. Having said that, I would typically advise involve relevant stakeholders in this process as domain knowledge often helps to understand the number of clusters that would seem logical.

**Comment by MaartenGr** [comment]
Due to inactivity, I'll be closing this issue. Let me know if you want me to re-open the issue!
