### ISSUE TITLE
Question: Extract documents per bin from Topic_over_time?

### ISSUE THREAD

**Issue by alla15747** [MaartenGr/BERTopic#885]
Hello Maarten!

I have a question, and I appreciate it if you could answer that.
In Topic_over_time dataframe, we have ['Topic', 'Words', Frequency', 'Timestamp']

For example: 
Topic 1 has 100 documents. 
Number of bins = 5 
Results: 
The first Bin has: 40 documents
The second Bin has: 20 documents
The third Bin has: 15 documents
The fourth Bin has: 15 documents
The fifth Bin has: 10 documents

I want to retrieve the 40 documents associated with bin 1, and the 20 documents associated with bin 2, ..etc.

I conditioned the dataframe on the timestamps to solve that, but this is inefficient as if I change the number of bins, the timestamps will change accordingly. Thus, does BERTopic support extracting the documents on the bin level automatically?
 
Thanks,

**Comment by MaartenGr** [comment]
Good question! That is currently indeed quite difficult to do and not at all intuitive. I might add an additional column to the output with document indices so that this process is a bit more intuitive. However, for now, you can use the following hacky approach:

```python
nr_bins = 20
datetime_format = None

documents = pd.DataFrame({"Document": docs, "Topic": topic_model.topics_, "Timestamps": timestamps})


if isinstance(timestamps[0], str):
    infer_datetime_format = True if not datetime_format else False
    documents["Timestamps"] = pd.to_datetime(documents["Timestamps"],
                                             infer_datetime_format=infer_datetime_format,
                                             format=datetime_format)
if nr_bins:
    documents["Bins"] = pd.cut(documents.Timestamps, bins=nr_bins)
    documents["Timestamps"] = documents.apply(lambda row: row.Bins.left, 1)
```

You can then access the `documents` dataframe that contains the timestamps.

**Comment by alla15747** [comment]
Thanks Maarten for your response. 
I want to add that, my intuition about extracting the documents on the bin level is to use the words within bin as another sub-topic from the main one.

**Comment by alla15747** [comment]
The solution by Maarten answers my question.
