### ISSUE TITLE
Ways to increase representative documents for a topic?

### ISSUE THREAD

**Issue by GeorgeDittmar** [MaartenGr/BERTopic#896]
Hello and apologies if this is not the right method to ask for guidance with BERTopic. I am performing topic modeling and want to get the representative docs for a topic but most seem to only return the default 3 documents when I would like to return say the top n most relevant documents. My intuition says to grab the topic_embeddings_ list and compare the embedding for the doc with that and rank based on cosine similarity, but I saw in another thread from a few months ago that the topic_embeddings_ list is only the avg and not recommended but the docs seem to indicate its the weighted avg now? For my document embeddings, from sentence bert for example, would I need to recalculate them to take into consideration the c_tfidf weights similar to how you generate them in the code to get better similarity ranking?

Thanks and love this framework. Will def be contributing back to it :)

**Comment by MaartenGr** [comment]
In the [v0.13](https://github.com/MaartenGr/BERTopic/pull/840) release of BERTopic, representative documents can now be calculated for any cluster model aside from HDBSCAN. This is relevant because it uses c-TF-IDF to approximate which documents best described the topic representations that we have extracted. The code is rather straightforward and you can use it to extract the number of documents that you are interested in. 

```python
import pandas as pd
import numpy as np
from bertopic import BERTopic
from sklearn.metrics.pairwise import cosine_similarity

# Train your topic model
topic_model = BERTopic()
topics, _ = topic_model.fit_transform(docs)

# This is a dataframe of your documents and their corresponding topics
documents = pd.DataFrame({"Doc": docs, "Topic": topics})
top_n_representative_docs = 3

# Extract top n documents
documents_per_topic = documents.groupby('Topic').sample(n=500, replace=True).drop_duplicates()
representative_docs_ = {}
for topic in documents['Topic'].unique():

    # Calculate similarity
    selected_docs = documents_per_topic.loc[documents_per_topic.Topic == topic, "Document"].values
    bow = topic_model.vectorizer_model.transform(selected_docs)
    ctfidf = topic_model.ctfidf_model.transform(bow)            
    sim_matrix = cosine_similarity(ctfidf, topic_model.c_tf_idf_[topic + topic_model._outliers])

    # Extract top 3 most representative documents
    indices = np.argpartition(sim_matrix.reshape(1, -1)[0], -top_n_representative_docs )[-top_n_representative_docs :]
    representative_docs_[topic] = [selected_docs[index] for index in indices]
```

You can then use `representative_docs_` to access the representative documents per topic.

**Comment by GeorgeDittmar** [comment]
Thanks for the code that is very helpful. Just to be sure I am understanding, is the code you posted what I would need to do to get representative docs via a model using HDBSCAN? I am assuming thats the case since its using defaults for BERTopic and building up the ctfidf matrix. Thanks again and have a great new year!

**Comment by MaartenGr** [comment]
The code I posted is what you need to get the representative docs for a non-HDBSCAN model. For HDBSCAN, I am using some of its internal structure to extract the so-called exemplar documents.

**Comment by GeorgeDittmar** [comment]
ok so if I just look at the code inside bertopic I should be able to come up with a similar strategy then?

**Comment by MaartenGr** [comment]
Yes, you can find the relevant code here:

https://github.com/MaartenGr/BERTopic/blob/06dcd47a019854185a39146ed693d16dc3a27651/bertopic/_bertopic.py#L2968

**Comment by GeorgeDittmar** [comment]
Awesome thanks!
