### ISSUE TITLE
ValueError: empty vocabulary; perhaps the documents only contain stop word

### ISSUE THREAD

**Issue by As2066** [MaartenGr/BERTopic#897]
Hi, I tried to reduce the outliers in my BERTopic model, I used the first and third ways [here](https://maartengr.github.io/BERTopic/faq.html#which-embedding-model-should-i-choose) but I got this error in both ways:
ValueError: empty vocabulary; perhaps the documents only contain stop words.

function to delete stopword:
```
# Remove Stopwords
def remove_stopwords(txt):
    txt_clean = [word for word in txt.split(' ') if word not in stop_words] #txt.split(' ')
    new_txt_clean = ' '.join(txt_clean)
    return new_txt_clean
```

training the model:
```
cluster_model = KMeans(n_clusters=50)
topic_model = BERTopic(hdbscan_model=cluster_model)
topics, probs = topic_model.fit_transform(documents)
```
what is the reason for this error and how can I solve it

**Comment by MaartenGr** [comment]
Thank you for your description! Can you also provide the full error message? That way, it is easier to see where the issue exactly stems from. Moreover, you mention that you got errors in both ways although the code that you show above is only used for the third way. Could you provide the code for the full training pipeline? Perhaps there is something else that might explain things.

**Comment by erikmagneto** [comment]
Hi! Seems like I have the same issue. **Here is my code**:

```
from bertopic import BERTopic
import pandas as pd
from tqdm import tqdm
import glob, pandas as pd, numpy as np, re
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from pandas.core.common import random_state

sws = stopwords.words("russian")

df2 = pd.read_csv('my_data.csv')

from nltk import word_tokenize, WordNetLemmatizer

stopwordSet = set(stopwords.words("russian"))


lemma = WordNetLemmatizer()

def cleanup_sentences(sentence):
    text = re.sub('[^а-яА-Я]'," ", str(sentence)) # Removing non a-z characters
    text = text.lower() # Lowering all text
    text = word_tokenize(text, language="russian") # Splitting each word into an element of a list
    text = [lemma.lemmatize(word) for word in text if(word) not in stopwordSet] # Lemmatizing words and removing stopwords
    text = " ".join(text) # Putting words back into a single string.
    return text


df2['text_cleaned'] = df2['text'].apply(cleanup_sentences)

docs3 = df2['text_cleaned']

docs3.reset_index(inplace = True,drop = True)

topic_model = BERTopic()
topics, probs = topic_model.fit_transform(docs3)  
```

**And the full error message:**

ValueError                                Traceback (most recent call last)
Input In [12], in <cell line: 2>()
      1 topic_model = BERTopic()
----> 2 topics, probs = topic_model.fit_transform(docs3)

File ~\anaconda3\lib\site-packages\bertopic\_bertopic.py:355, in BERTopic.fit_transform(self, documents, embeddings, y)
    352     documents = self._sort_mappings_by_frequency(documents)
    354 # Extract topics by calculating c-TF-IDF
--> 355 self._extract_topics(documents)
    357 # Reduce topics
    358 if self.nr_topics:

File ~\anaconda3\lib\site-packages\bertopic\_bertopic.py:2389, in BERTopic._extract_topics(self, documents)
   2380 """ Extract topics from the clusters using a class-based TF-IDF
   2381 
   2382 Arguments:
   (...)
   2386     c_tf_idf: The resulting matrix giving a value (importance score) for each word per topic
   2387 """
   2388 documents_per_topic = documents.groupby(['Topic'], as_index=False).agg({'Document': ' '.join})
-> 2389 self.c_tf_idf_, words = self._c_tf_idf(documents_per_topic)
   2390 self.topic_representations_ = self._extract_words_per_topic(words)
   2391 self._create_topic_vectors()

File ~\anaconda3\lib\site-packages\bertopic\_bertopic.py:2519, in BERTopic._c_tf_idf(self, documents_per_topic, fit, partial_fit)
   2517     X = self.vectorizer_model.partial_fit(documents).update_bow(documents)
   2518 elif fit:
-> 2519     self.vectorizer_model.fit(documents)
   2520     X = self.vectorizer_model.transform(documents)
   2521 else:

File ~\anaconda3\lib\site-packages\sklearn\feature_extraction\text.py:1283, in CountVectorizer.fit(self, raw_documents, y)
   1267 """Learn a vocabulary dictionary of all tokens in the raw documents.
   1268 
   1269 Parameters
   (...)
   1280     Fitted vectorizer.
   1281 """
   1282 self._warn_for_unused_params()
-> 1283 self.fit_transform(raw_documents)
   1284 return self

File ~\anaconda3\lib\site-packages\sklearn\feature_extraction\text.py:1330, in CountVectorizer.fit_transform(self, raw_documents, y)
   1322             warnings.warn(
   1323                 "Upper case characters found in"
   1324                 " vocabulary while 'lowercase'"
   1325                 " is True. These entries will not"
   1326                 " be matched with any documents"
   1327             )
   1328             break
-> 1330 vocabulary, X = self._count_vocab(raw_documents, self.fixed_vocabulary_)
   1332 if self.binary:
   1333     X.data.fill(1)

File ~\anaconda3\lib\site-packages\sklearn\feature_extraction\text.py:1220, in CountVectorizer._count_vocab(self, raw_documents, fixed_vocab)
   1218     vocabulary = dict(vocabulary)
   1219     if not vocabulary:
-> 1220         raise ValueError(
   1221             "empty vocabulary; perhaps the documents only contain stop words"
   1222         )
   1224 if indptr[-1] > np.iinfo(np.int32).max:  # = 2**31 - 1
   1225     if _IS_32BIT:

ValueError: empty vocabulary; perhaps the documents only contain stop words

**Comment by MaartenGr** [comment]
@erikmagneto As a quick side note, I believe BERTopic only takes in a list of strings and not a pd.series so converting that might help. 

On-topic: It is typically advised **not** to remove stopwords when training the model but instead pass them to the CountVectorizer. The reason for this is that when you transform text using transformer-based models, it often needs to the full text, without any major preprocessing like lemmatization and stopword removal, to get an accurate representation of the text. 

I would advise not to perform lemmatization and stopword removal and instead do something like this:

```python
from bertopic import BERTopic
import pandas as pd
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import CountVectorizer


# Prepare data
df2 = pd.read_csv('my_data.csv')
docs = df2['text'].values.tolist()

# Remove stopwords **after** generating the clusters
# NOTE: You can also perform the lemmatization here
my_stopwords = stopwords.words("russian")
vectorizer_model = CountVectorizer(stop_words=my_stopwords)

# Train the model
topic_model = BERTopic(vectorizer_model=vectorizer_model)
topics, probs = topic_model.fit_transform(docs)  
```

**Comment by JeongbaeChoi** [comment]
Hi Maarten,
Can I get to know how to conduct the lemmatization **after** generating the clusters?

**Comment by MaartenGr** [comment]
@JeongbaeChoi You can do that using the [CountVectorizer](https://maartengr.github.io/BERTopic/getting_started/vectorizers/vectorizers.html#countvectorizer) which is applied after generating the cluster. Create a custom tokenizer/analyzer that does the lemmatization.
