### ISSUE TITLE
topics_over_time gets stuck

### ISSUE THREAD

**Issue by oscarm3l1n** [MaartenGr/BERTopic#901]
Hello!

I am trying to run the `topics_over_time()` function, in order to later run `visualize_topics_over_time()`. However when I run `topics_over_time()`, it runs for `1 it`, and then it's stuck.

![image](https://user-images.githubusercontent.com/48945939/210110062-5d2cf8a9-62bb-4dea-bc93-f07b624c8513.png)

* I am using GPU
* The size of my text corpus is 80,000 documents

Please help!

Kind regards

**Comment by MaartenGr** [comment]
Could you share your entire code for this and the version of BERTopic you are using? Also, is it possible to create a reproducible example? As of right now, there is much hidden from me which makes it difficult to see what exactly is going on here.

**Comment by MaartenGr** [comment]
Due to inactivity, I'll be closing this issue. Let me know if you want me to re-open the issue!
