### ISSUE TITLE
BERTopic with custom embeddings

### ISSUE THREAD

**Issue by Matheusadler** [MaartenGr/BERTopic#902]
Hello!
I've been studying BERTopic and doing some experiments for my dissertation work and I have a question. Why do I get different results when I use BERTopic(language='multilingual', nr_topics='auto') and BERTopic(nr_topics='auto) with custom embeddings but generated with the same multilingual model paraphrase-multilingual-MiniLM-L12-v2 in the same documents?

thanks and great work!

**Comment by MaartenGr** [comment]
The reason for this is that BERTopic uses UMAP for reducing the embeddings which is a stochastic model. You can read more about it in the FAQ [here](https://maartengr.github.io/BERTopic/faq.html#why-are-the-results-not-consistent-between-runs).

**Comment by Matheusadler** [comment]
The results are very different when using the custom embeddings, including the number of topics generated (200+ topics difference). Is there any indication for using the nr_topics='auto' parameter when using custom embeddings?

**Comment by MaartenGr** [comment]
Did you try generating the topics by setting a random state first using the method I mentioned above? The results can differ depending on a number of things, including the parameters that you have set for both UMAP and HDBSCAN but also the number of documents that you have passed. In practice, when you have a stochastic nature in the topic generation and on top of that you run an automatic topic reduction method, the results can differ quite largely. Therefore, I would advise starting with a random state and building from there.

**Comment by MaartenGr** [comment]
Due to inactivity, I'll be closing this issue. Let me know if you want me to re-open the issue!
