### ISSUE TITLE
bump pyyaml

### ISSUE THREAD

**Issue by vindex10** [MaartenGr/BERTopic#903]
Hi! Is there any reason BERTopic still caps pyyaml to <6.0 ?

It seems the main issue was with Google Colab: https://github.com/MaartenGr/BERTopic/issues/288
(from October 2021)

I checked on Colab now, and `from bertopic import BERTopic` doesn't fail anymore with PyYAML==6.0

you can play with this branch:

```
!pip install git+https://github.com/vindex10/BERTopic@feature/bump_pyyaml
```

Do you think we can allow higher versions?

**Comment by vindex10** [comment]
Thank you, Maarten, for your reply! I look forward to new updates :)

**Comment by rxavier** [comment]
Hi @MaartenGr. Have you had a chance to test the version bump?

**Comment by MaartenGr** [comment]
I have not had a chance to test it yet but seeing as the original was quite old I kinda expect there to be few or no problems increasing the version. I'll make sure to check this out before the new release. In the meantime, you can try it out with a higher version yourself by upgrading pyyaml after installation or by using `--no-deps` when installing BERTopic.
