### ISSUE TITLE
skip the dimension reduction

### ISSUE THREAD

**Issue by Gibran910** [MaartenGr/BERTopic#909]
hi marteen, i just wanna know what happen if we dont use the dimension reduction for the clustering?, and how to skip the dimension reduction step?he dimension reduc

**Comment by MaartenGr** [comment]
If we do not use dimensionality reduction then the clustering will be directly done on the raw embeddings. You can find more about that here](https://maartengr.github.io/BERTopic/getting_started/dim_reduction/dim_reduction.html#skip-dimensionality-reduction).

**Comment by Gibran910** [comment]
in your experience what the difference between using the dimension reduction an not using it??

thanks

**Comment by MaartenGr** [comment]
The link that I posted gives you an idea about the need to perform dimensionality reduction. You can also find more about that step in the pipeline [here](https://maartengr.github.io/BERTopic/algorithm/algorithm.html). In general, it is often advised to perform dimensionality reduction as clustering algorithms might have difficulties handling data in high-dimensional space.
