### ISSUE TITLE
Introducing new words after topics have been formed

### ISSUE THREAD

**Issue by joshmyersdean** [MaartenGr/BERTopic#91]
Hello!

Is there a way to perform inference of some sort on new documents after the topics have been formed?

Thank you!

**Comment by MaartenGr** [comment]
After fitting Bertopic with either `model.fit(docs)` or `model.fit_transform(docs)` you can use `model.transform(new_docs)` to predict the topics of unseen documents with unseen words. 

Does that answer your question?

**Comment by joshmyersdean** [comment]
Yes, thank you!
