### ISSUE TITLE
words similarity

### ISSUE THREAD

**Issue by kimkyulim** [MaartenGr/BERTopic#913]
Hi, Martin.
First of all, happy new year.
I am applying it to various data using Bertopic.

I want to find the similarity between the words in the topic, so can I know the vector for each word in the topic?

For example,
Topic 1 consists of 30 words and I want to know the background of words 5, 6, 7, 15, and 30.

Thank you for your answer in advance.

**Comment by MaartenGr** [comment]
Thank you, best wishes to you too! 

The vectors for words in a topic are not saved within BERTopic but you can easily calculate them yourselves with:

```python
word_embeddings = topic_model._extract_embeddings(my_list_of_words, method="word", verbose=True)
```

**Comment by kimkyulim** [comment]
@MaartenGr 
Thank u for your replying!
How can I make my_list_of_words?
Should I make it manually?

**Comment by MaartenGr** [comment]
Yes, you can extract the words for each topic using `topic_model.get_topics()`

**Comment by kimkyulim** [comment]
Thank u so much, @MaartenGr 
When I made the list in get_topics, I made the topic(-1) without removing it.
It's okay because it's sequential, right?

**Comment by MaartenGr** [comment]
It depends on how you approach any comparisons afterwards but as long as you keep track of the topics it should be okay.

**Comment by kimkyulim** [comment]
Hello @MaartenGr MaartenGr.
Are you doing well?

I calculated and used the keywords vector in the topic you told me last time.
I tried to find the cosine similarity between the calculated keywords, but the similarity was too low.
Even between keywords in the topic, the similarity of keywords was lower than 0.2.

So for example, the similarity between topic 1 and topic 2 is about 0.8.
The similarity between keyword1 in topic 1 and keyword2 in topic 2 is about 0.1.
Even among the keywords in topic 1, the similarity was lower than 0.2.

Question 1. Can you tell me the definition and keywords of the topics in Bertopic?

Question 2. Can you explain if the similarity between keyswords is low? Is it because the vector of keyswords exists in clustered topics that I am inferring now? 
However, I do not understand in detail. Can you tell me?

**Comment by MaartenGr** [comment]
> Question 1. Can you tell me the definition and keywords of the topics in Bertopic?

The keywords are a result of the c-TF-IDF calculation of the topic representation. You can find more about that [here](https://maartengr.github.io/BERTopic/getting_started/ctfidf/ctfidf.html) and [here](https://maartengr.github.io/BERTopic/algorithm/algorithm.html#5-topic-representation).

> Question 2. Can you explain if the similarity between keyswords is low? Is it because the vector of keyswords exists in clustered topics that I am inferring now?

The cosine similarity depends on the embedding model that you use. Some or more suited for longer sequences than others. Moreover, the cosine similarity simply may take lower values if the model was not optimized for that. Do note that similarities within clusters tend to be much higher than between clusters.

**Comment by kimkyulim** [comment]
Thank you for your reply. @MaartenGr 

I have more questions after seeing your answer.

I've searched a lot on my own to understand your answer, but I haven't fully understood it yet.

I'll ask you an additional question. Please give me an answer.

Q1.

What do you mean by "some or more reserved for longer sequences than others"?

Q2.

What do you mean by "if the model was not optimized for that?"

Q3.
Like you said, "Don't that similarities with in clusters end to be much higher than between clusters." Similarities within the same cluster should be high, but I want to know why it's so low between 0.1 and 0.2.

**Comment by kimkyulim** [comment]
@MaartenGr 

Ultimately, what I'm curious about is why the cosine similarity between keywords existing within the same topic is low.

Bertopic clusters similar documents and seeks topic expressions, so the keywords that make up the topic are in similar positions, right?
But I don't understand why the similarity between keywords in the same topic is low.

I appreciate your reply in advance.

**Comment by kimkyulim** [comment]
Thnak u for your replying @MaartenGr 


Bertopic's topics are composed of similar topics through clustering, but the keywords that make up the topics are constructed through c-tf-idf, so the similarity may not be high, right?


I want the keywords that make up the topics to be composed of keywords that are similar to each other.

What should I do?

**Comment by MaartenGr** [comment]
There is a [pull request](https://github.com/MaartenGr/BERTopic/pull/977) for the upcoming version of BERTopic that allows you to use a model on top of BERTopic called `KeyBERTInspired`. Essentially, it is a model that focuses on finding words close to a single representation of a topic. This method tends to find words that are more related to one another. You could use that model that create keywords that are similar to each other. Another option is to create the keyword embeddings yourself and find keywords in the vocabulary that closely match those in a topic.
