### ISSUE TITLE
AttributeError: 'BERTopic' object has no attribute 'topic_names'

### ISSUE THREAD

**Issue by AlbertoDeBenedittis** [MaartenGr/BERTopic#914]
Hello everyone! 

I was following [a Kaggle tutorial](https://www.kaggle.com/code/meetnagadia/topic-modeling-using-bertopic/notebook) on BERTopic while I got an error: AttributeError: 'BERTopic' object has no attribute 'topic_names'. 

Through the `help`,  I noticed that the function `topic_names` is no more supported. 

Do you know if there is an equivalent function to it? 

I am using bertopic Version: 0.13.0.

Thank you for your help

**Comment by MaartenGr** [comment]
You can find an overview of BERTopic's attributes [here](https://github.com/MaartenGr/BERTopic#attributes) but seeing the code, I think this is most likely very similar to the `.topic_labels_` attribute.

**Comment by AlbertoDeBenedittis** [comment]
Thanks a lot ! It worked !
