### ISSUE TITLE
 There was an error running on my own dataset

### ISSUE THREAD

**Issue by dingjing1998** [MaartenGr/BERTopic#92]
docs = pd.read_csv("data1.csv")
topics, probs = model.fit_transform(docs)

ValueError                                Traceback (most recent call last)
/usr/local/lib/python3.7/dist-packages/pandas/core/internals/managers.py in create_block_manager_from_arrays(arrays, names, axes)
   1691     try:
-> 1692         blocks = form_blocks(arrays, names, axes)
   1693         mgr = BlockManager(blocks, axes)

8 frames
ValueError: could not broadcast input array from shape (49967) into shape (2)

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
/usr/local/lib/python3.7/dist-packages/pandas/core/internals/managers.py in create_block_manager_from_arrays(arrays, names, axes)
   1695         return mgr
   1696     except ValueError as e:
-> 1697         raise construction_error(len(arrays), arrays[0].shape, axes, e)
   1698 
   1699 

ValueError: Shape of passed values is (2, 3), indices imply (49967, 3)

**Comment by MaartenGr** [comment]
Fortunately, that is to be expected! `fit_transform()` takes in a list of strings and not a pandas dataframe. Convert your column to a list of strings and you are good to go 😄
