### ISSUE TITLE
'BERTopic' object has no attribute 'probabilities_'

### ISSUE THREAD

**Issue by missa7481** [MaartenGr/BERTopic#921]
I am trying to look at the probabilities for all topics, and my codes followed as a tutorial, but it returns a warning as above. My bertopic version has been updated to the latest (0.13.0) . May I know how to fix it?

**Comment by MaartenGr** [comment]
Could you share the code you have been using for this? Also, did you make sure to restart the notebook after installing BERTopic? Could you also check your BERTopic version with `import bertopic; bertopic.__version__`? The latest update should make `topic_model.probabilities_` accessible so my guess is that there is something going on with your installation/environment.

**Comment by missa7481** [comment]
it works now,thanks!
