### ISSUE TITLE
POS-tagging

### ISSUE THREAD

**Issue by Gibran910** [MaartenGr/BERTopic#925]
Hi Marteen!

i wanna know can we implement POS-Tagging in topic representation for BERTopic, and how you implement it

thanks

**Comment by MaartenGr** [comment]
You can apply POS-tagging in BERTopic by using the [CountVectorizer](https://maartengr.github.io/BERTopic/getting_started/vectorizers/vectorizers.html#tokenizer). Essentially, you would have to pass your tagger to either the tokenizer or the analyzer in the vectorizer. That way, you can apply POS-tagging when tokenizing the documents and perhaps do some filtering if necessary. An example of this would be [KeyphraseVectorizers](https://github.com/TimSchopf/KeyphraseVectorizers).

**Comment by MaartenGr** [comment]
You can now also implement POS tagging with the [`bertopic.representation.PartOfSpeech`](https://maartengr.github.io/BERTopic/getting_started/representation/representation.html#partofspeech) model.
