### ISSUE TITLE
probabilities returned as NoneType after calling fit_transform() on a list of strings

### ISSUE THREAD

**Issue by IoannisAntypas** [MaartenGr/BERTopic#93]
Hello, first of all absolutely impressive work, both from a technical pov and with the documentation and clear instructions!

I am replicating the `20newsgroups` guide you have posted on two local machines and in both instances after calling `fit_transform()` on the `docs` I get the topics `topics` and can visualize and search them but `probabilities` returns a `NoneType`. 

Here is my code, I do not diverge from the guide - just reduce the number of documents for speed.

```
from bertopic import BERTopic
from sklearn.datasets import fetch_20newsgroups

docs = fetch_20newsgroups(subset='all',remove=('headers', 'footers','quotes'))['data']
docs = docs[:100]
model = BERTopic(nr_topics = 'auto')
topics, probabilities = model.fit_transform(docs)
```

`print(type(probabilities))` simply returns `NoneType`

Wondering if there is some dependency I am lacking or something wrong with my installation?

Thank you again for this brilliant work!

**Comment by MaartenGr** [comment]
Thank you for the kind words! You should set `BERTopic(nr_topics = 'auto', calculate_probabilities=True)` and it should work 😄 

The reason for setting this to False as a default is calculating the probabilities for many documents can decrease the computation time significantly. So, only set this to True if you have less than 100.000 documents.

**Comment by MaartenGr** [comment]
Also, I have thought about making it possible to calculate the probabilities separately but that would require a significant chance to the API which I am not a fan of. This is the hacky solution for now. If somebody has a better solution, please let me know!

**Comment by IoannisAntypas** [comment]
Yes indeed! 

I was digging deeper in the documentation and found this and rushed back to specify that it can't possibly be an issue, but you beat me to the punch!

Thanks again for the great work!
