### ISSUE TITLE
Deteriorating probabilities for documents' topics for identical documents.

### ISSUE THREAD

**Issue by LucVermeer** [MaartenGr/BERTopic#932]
I have a short-sentence dataset with about 1k documents with a decent amount of identical documents (e.g. 50 times the same word, which happens a hand full of times). When analyzing the spreadsheet I created with .get_document_info() over all docs, I found that for a lot of the identical documents there exist multiple probabilities for the same topic, even though these identical documents are all classified as representative documents. Do you have an idea why this could happen? Thanks

**Comment by MaartenGr** [comment]
The `probabilities` column will contain flat probabilities if `calculate_probabilities=False` or will contain the maximum probability if `calculate_probabilities=True`. So if you have set `calculate_probabilities=True`, then an approximation will be made and the resulting probabilities might slightly differ. Having said that, if its set to False, then that seems to be a result of HDBSCAN building up its clusters.

**Comment by LucVermeer** [comment]
With `calculate_probabilities=True` results in vastly different probabilities (0,334 and 1) for identical documents (surely identical as they are only 2 or 3 words) within the same topic. In several cases, documents are assigned to the outlier class while their copy is assigned to a topic cluster. Where could the cause of this be?

**Comment by MaartenGr** [comment]
That most likely depends on two things. First, the underlying embedding model. This, to an extent, decides the features of the input documents and as a result, might and can change the features drastically even if documents are very similar to each other. The second is setting `calculate_probabilities=True`. This enables the soft clustering capabilities of HDBSCAN as described [here](https://hdbscan.readthedocs.io/en/latest/soft_clustering_explanation.html). This soft clustering approach can be viewed as a post-hoc approximation of the probabilities and as such try to estimate the probabilities which give in to different probabilities. You can read more about that in the link about soft clustering.

**Comment by jiannan-xu** [comment]
I encountered the same problem. For two identical messages under the same topic, they are assigned different probabilities (0.9 v.s. 0.1). Is it because of soft clustering? Thanks!

**Comment by MaartenGr** [comment]
Yes, the soft clustering in HDBSCAN is merely an approximation and calculates predictions differently from when it was trained. As a result, both the topic and its probability might change between `fit` and `transform`. You can read more about soft-clustering in HDBSCAN [here](https://hdbscan.readthedocs.io/en/latest/soft_clustering_explanation.html).

**Comment by MaartenGr** [comment]
Due to inactivity, I'll be closing this issue. Let me know if you want me to re-open the issue!
