### ISSUE TITLE
cannot import name 'UMAP' from 'umap' 

### ISSUE THREAD

**Issue by JonathanAlis** [MaartenGr/BERTopic#935]
After installing bertopic on my environment today, I tried the basic script from the quickstart documentation:

> from bertopic import BERTopic
> from sklearn.datasets import fetch_20newsgroups
> 
> docs = fetch_20newsgroups(subset='all',  remove=('headers', 'footers', 'quotes'))['data']
> 
> topic_model = BERTopic()
> topics, probs = topic_model.fit_transform(docs)

The error happens on importing bertopic:

> ImportError                               Traceback (most recent call last)
Input In [1], in <cell line: 1>()
----> 1 from bertopic import BERTopic
      2 from sklearn.datasets import fetch_20newsgroups
      4 docs = fetch_20newsgroups(subset='all',  remove=('headers', 'footers', 'quotes'))['data']
> File ~/TST/ijuri_env/lib/python3.8/site-packages/bertopic/__init__.py:1, in <module>
----> 1 from bertopic._bertopic import BERTopic
      3 __version__ = "0.13.0"
      5 __all__ = [
      6     "BERTopic",
      7 ]
> File ~/TST/ijuri_env/lib/python3.8/site-packages/bertopic/_bertopic.py:26, in <module>
     24 # Models
     25 import hdbscan
---> 26 from umap import UMAP
     27 from sklearn.preprocessing import normalize
     28 from sklearn import __version__ as sklearn_version
> ImportError: cannot import name 'UMAP' from 'umap' (/mnt/home/jonathanalis/TST/ijuri_env/lib/python3.8/site-packages/umap/__init__.py)

In my pip freeze I have:

> umap==0.1.1
> bertopic==0.13.0

And I am using python 3.8.10.
How can I solve?
Thanks in advance

**Comment by MaartenGr** [comment]
It seems that you have the wrong UMAP package installed. I would advise either starting from a completely fresh environment and installing BERTopic there, are remove the UMAP package and installing the correct one with `pip install umap-learn`.

**Comment by MaartenGr** [comment]
Due to inactivity, I'll be closing this issue. Let me know if you want me to re-open the issue!
