### ISSUE TITLE
Stopwords appearing after outlier reduction

### ISSUE THREAD

**Issue by hbeelee** [MaartenGr/BERTopic#936]
Hi Maarten,

I'm trying to update my bertopic model after outlier reduction using .reduce_outliers. 
It works without any errors, but the problem is that after updating the model, .get_topic() returns bunch of stopwords that had been removed just fine before outlier reduction.

I guess it'd be clearer to explain with codes.

The below works just fine (but result in outliers) and returns clear keywords with stopwords removed:

```
class CustomTokenizer:
    def __init__(self, tagger):
        self.tagger = tagger
    def __call__(self, sent):
        sent = sent[:1000000]
        word_tokens = self.tagger.morphs(sent)
        result = [word for word in word_tokens if len(word) > 1 and word not in stopwords]
        return result

custom_tokenizer = CustomTokenizer(Mecab())
vectorizer = CountVectorizer(tokenizer=custom_tokenizer, max_features=3000, stop_words=stopwords, ngram_range=(1, 2))
hdbscan_model = HDBSCAN(min_cluster_size=50, min_samples=5, metric='euclidean', prediction_data=True)

model_name ="klue/bert-base"
sentence_model = SentenceTransformer(model_name)
embeddings = sentence_model.encode(keywords, show_progress_bar=True)

model = BERTopic(embedding_model=sentence_model,
                 vectorizer_model=vectorizer,
                 hdbscan_model=hdbscan_model,
                 min_topic_size=5,
                 top_n_words=10,
                 nr_topics="auto",
                 calculate_probabilities = True,
                 #diversity=0.3,
                 n_gram_range=(1,2),
                 #umap_model=umap_model,
                 verbose=True)

topics, probs = model.fit_transform(keywords)
model.get_topics() 
```

But when i run the next code, outlier reduction, the resulting keywords suddenly includes the formerly-removed stopwords and the topics are just so different from the previous result (before outlier reduction).

I would appreciate any help. Thanks in advance.

```
new_topics = model.reduce_outliers(keywords, topics)
model.update_topics(keywords, topics=new_topics)
model.get_topics() # results with stopwords and different topics
```

**Comment by MaartenGr** [comment]
When you use `.update_topics` it is important to use the exact same parameters as you did when you instantiated the topic model. This function is meant to update the topics and their representation, so any parameters related to that when instantiating the model are now removed if you did not explicitly pass them. In other words, you should run the following:

```python`
model.update_topics(keywords, topics=new_topics, vectorizer_model=vectorizer)
```

**Comment by hbeelee** [comment]
> 

Thanks a lot, Maarten. I really appreciate your dedication not only to bertopic but also to NLP and AI as a whole. Keep up the good work!

**Comment by MaartenGr** [comment]
Thanks for your kind words! If you run into any other issues, feel free to reach out.
