### ISSUE TITLE
Please help with inference endpoint (hugging face).

### ISSUE THREAD

**Issue by CandyFiend** [MaartenGr/BERTopic#937]
Hello. I'm trying to create an endpoint using a custom endpoint handler by loading a trained model. I understand that my code is not very correct, but at least it works locally. Attempts to load using AutoModel Class ended up with me not knowing where to get config.json. Can you tell me how to do it correctly? I spent the whole day, but I couldn't find a single clue. AWS crashes with an error at the launch stage of the inference.

```
from typing import Dict, List, Any
from bertopic import BERTopic
from transformers import pipeline, AutoModel, AutoConfig
from sentence_transformers import SentenceTransformer

class EndpointHandler():
    def __init__(self, path=""):
        self.model = BERTopic.load(/repository/model)
        self.model.calculate_probabilities = False


    def __call__(self, data: Dict[str, Any]) -> List[Dict[str, Any]]:
        """
       data args:
            text (:obj: `str`)
      Return:
            A :obj:`list` | `dict`: will be serialized and returned
        """
        # get inputs
        text = data.pop("text")


        # run normal prediction
        prediction = self.model.transform([text])
        return prediction
```

**Comment by MaartenGr** [comment]
What is exactly the error that you are getting and can you also share the exact code that you are running? One thing to note here is that you created the class as if it were a function, perhaps that gives an error?

**Comment by CandyFiend** [comment]
I used [this instruction](https://huggingface.co/docs/inference-endpoints/guides/custom_handler) to create my handler. Authors load models through their module classes, but its need pytorch and tensorflow models. I ran this code on my computer via test.py , it works and returns a response. This class is needed in order to run the model from the repository in automatic mode (in a couple of clicks) and change the business logic, for example, not to return the topic and keywords, but to generate images for each word using a different model and return an array of images.

[Repository HuggingFace](https://huggingface.co/homester/bertopic_20news)
[AWS log pastebin](https://pastebin.com/ppGhh5Fa)

**Comment by MaartenGr** [comment]
Unfortunately, I am not that familiar with these endpoints and how that works together with AWS. From the log, it does seem that there might be something wrong with importing the saved BERTopic file. Do note that when you save the BERTopic model, you do not need to supply it with a `.bin` at the end, perhaps something might went wrong there and it tried to compile the numba.

**Comment by CandyFiend** [comment]
I understand that I am most likely using this class incorrectly. I need help with how to deploy the model correctly. Maybe there are ways to get config.json by changing the model format? Then I would be able to load the model in their standard way.

**Comment by MaartenGr** [comment]
In BERTopic, there is no config.json structure that you can use to load the model so I do not think something like that will work. It might be worthwhile to try out saving the BERTopic model without the `.bin`.

**Comment by CandyFiend** [comment]
I try. [Log](https://pastebin.com/zNaVt4Gn)

**Comment by MaartenGr** [comment]
Hmmm, I am not entirely sure what is happening but did you make sure that the environment in which you trained the model is exactly the same as the environment in which you loaded the model? This includes the version of packages and their dependencies as well as the python version your are using.

**Comment by CandyFiend** [comment]
Not at all. I can't influence it. I understand your version and will probably check it if possible, but we have already decided to do it in a different way. You can close the issue.
