### ISSUE TITLE
Model from the transformers library

### ISSUE THREAD

**Issue by ericchagnon15** [MaartenGr/BERTopic#941]
I'm trying to use a model from the transformers library, and I think the verbose output is telling me that the default model is being used and I wanted to check and make sure this was working as intended.

```python
from transformers import *
SciBERT = AutoModel.from_pretrained('allenai/scibert_scivocab_uncased')

topic_model = BERTopic(embedding_model=SciBERT, language="english", nr_topics="auto", verbose=True )
topics, probs = topic_model.fit_transform(docs)
```

The following is output when I run the above code and I am unsure if the model I loaded is being used or not:

loading configuration file /root/.cache/torch/sentence_transformers/sentence-transformers_all-MiniLM-L6-v2/config.json
Model config BertConfig {
  "_name_or_path": "/root/.cache/torch/sentence_transformers/sentence-transformers_all-MiniLM-L6-v2/",
  "architectures": [
    "BertModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 384,
  "initializer_range": 0.02,
  "intermediate_size": 1536,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 6,
  "pad_token_id": 0,
  "position_embedding_type": "absolute",
  "transformers_version": "4.25.1",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 30522
}

loading weights file /root/.cache/torch/sentence_transformers/sentence-transformers_all-MiniLM-L6-v2/pytorch_model.bin
All model checkpoint weights were used when initializing BertModel.

All the weights of BertModel were initialized from the model checkpoint at /root/.cache/torch/sentence_transformers/sentence-transformers_all-MiniLM-L6-v2/.
If your task is similar to the task the model of the checkpoint was trained on, you can already use BertModel for predictions without further training.
loading file vocab.txt
loading file tokenizer.json
loading file added_tokens.json
loading file special_tokens_map.json
loading file tokenizer_config.json
Batches: 100%
583/583 [00:49<00:00, 94.37it/s]
2023-01-17 21:20:24,267 - BERTopic - Transformed documents to Embeddings
2023-01-17 21:20:44,771 - BERTopic - Reduced dimensionality
2023-01-17 21:20:45,848 - BERTopic - Clustered reduced embeddings
2023-01-17 21:20:55,548 - BERTopic - Reduced number of topics from 213 to 150

**Comment by MaartenGr** [comment]
It seems that you passed the variable `embed_model` to BERTopic and not the variable `SciBERT`, so there might be source of your issue.

**Comment by ericchagnon15** [comment]
I tried using another model from the transformers library (https://huggingface.co/allenai/aspire-sentence-embedder) with the following usage:
```python
from transformers import *
ASPIRE = pipeline("feature-extraction", model="allenai/aspire-sentence-embedder")
less_docs = arxiv_docs[200:]

topic_model = BERTopic(embedding_model=ASPIRE, language="english", nr_topics="auto", verbose=True )
topics, probs = topic_model.fit_transform(less_docs)
```
Where arxiv docs is a subset of the Arxiv dataset, specifically the concatenation of the title and abstract. 
This code yielded the same verbose output as my original code in the issue which indicates that the default embedding model is being used.

But when I run the code from the huggingface section of your page (https://maartengr.github.io/BERTopic/getting_started/embeddings/embeddings.html):
```python
embedding_model = pipeline("feature-extraction", model="distilbert-base-cased")
example_model = BERTopic(embedding_model=embedding_model, verbose = True)
example_topics, example_probs = example_model.fit_transform(less_docs)
```
 I do not get this output and the code behaves normally. I was hoping you could shed some light on why these models do not seem to work with BERTopic or if I am using the transformers library incorrectly with BERTopic. Thanks!

**Comment by MaartenGr** [comment]
I am not entirely sure why there are these differences between those models other than they are trained and used on different use cases. I should note though that the following is working for me as long as I take the token limit into account:

```python
from transformers import *
from sklearn.datasets import fetch_20newsgroups
from bertopic import BERTopic

ASPIRE = pipeline("feature-extraction", model="allenai/aspire-sentence-embedder")
docs = fetch_20newsgroups(subset='all',  remove=('headers', 'footers', 'quotes'))['data']
topic_model = BERTopic(embedding_model=ASPIRE, language="english", nr_topics="auto", verbose=True )
topics, probs = topic_model.fit_transform(docs[:10])
```

So there might be some issue with caching going on which a new environment might fix.

**Comment by ericchagnon15** [comment]
I tried using the SciBERT model with pipeline instead of the AutoModel() function and that seemed to do the trick as I don't see anymore verbose output indicating that the default model is being used.

**Comment by MaartenGr** [comment]
My apologies, I completely glanced over that! Indeed, in order to use huggingface within BERTopic you will need to make use of a `pipeline` component instead of the `AutoModel`.

**Comment by ericchagnon15** [comment]
Understood, I was also able to get these models to work using flair as well.

**Comment by ericchagnon15** [comment]
I have also been trying to get Galactica, Meta's new language model, to work with BERToptic but have been running into similar issues. I opened an issue on their page asking if they had any advice on getting Galactica to integrate with BERTopic since I was unable to get it to work with any of the methods I tried previously.
