### ISSUE TITLE
Importing BERTopic: A "ModuleNotFoundError: No module named sklearn.externals.joblib"

### ISSUE THREAD

**Issue by Xrmkm** [MaartenGr/BERTopic#945]
I am installing BERTopic with Python 3.6.8 and had referred to Maarten's comment [here](https://github.com/MaartenGr/BERTopic/issues/333#issuecomment-979878015) on getting BERTopic to work with 3.6.

I also reinstalled joblib and scikit-learn (instead of sklearn), and the error persists. I restart the notebook each time, of course!

**Comment by MaartenGr** [comment]
At the moment, BERTopic has no direct support for python 3.6 as I remember there were some dependencies that stopped supporting python 3.6. You could try installing it with the `--no-dependencies` flag and installing all dependencies manually, but you would have to take extra care in installing the dependencies. For example, the error that you are getting might likely be that you installed a too recent version of sklearn that requires a newer version of joblib which in turn requires python 3.6.

**Comment by Xrmkm** [comment]
Thank you, Maarten, for your take on this. Closing this issue!
