### ISSUE TITLE
Text pre-processing for CountVectorizer (topic embedding)

### ISSUE THREAD

**Issue by gau-nernst** [MaartenGr/BERTopic#947]
First off, thank you for creating this library.

Is there a way to pre-process the text only for CountVectorizer? I understand that for document representation (transformer encoder), I should use the raw text. However, I want to do special pre-processing before CountVectorizer. The built-in pre-processing is not sufficient for my use case.

Also, my tokens contain hashtags, but the word distribution doesn't have any hashtags. Is there a step where you remove hashtags (and other punctuations?) from the top keywords? I already specify `tokenizer=str.split` inside CountVectorizer to use whitespace tokenization in order to preserve the hashtags.

**Comment by gau-nernst** [comment]
I just found out the method `._preprocess_text()`, which is called before applying the Vectorizer. It only keeps letters and digits if the language is English (default) which leads to my problem. This behavior doesn't seem to be documented anywhere.

I have 2 suggestions:

- Expose `_preprocess_text()` so users can specify the preprocessing function before Vectorizer
- Document the default `_preprocess_text()` behavior

**Comment by MaartenGr** [comment]
Thank you for the feedback! I'll take it into account for a new release. For now, you can override this preprocessing step if you provide the BERTopic model with an embedding model instead of selecting `language="english"`. For instance, this should override the preprocessing step:

```python
from sentence_transformers import SentenceTransformer

sentence_model = SentenceTransformer("all-MiniLM-L6-v2")
topic_model = BERTopic(embedding_model=sentence_model)
```

**Comment by gau-nernst** [comment]
Thank you for your reply. In the end I passed `language=None` to not apply `._preprocess_text()` while still using `all-MiniLM-L6-v2`.

But I have to say, having a special pre-processing step, which cannot be turned off directly, when `language="english"` doesn't really make sense.

**Comment by MaartenGr** [comment]
The underlying idea for this is that not everyone is a power user and that the default settings will maximize the ease of performing topic modeling without the need to perform additional processing. Having said that, some of this is already taken into account with the vectorizer, so I might just move it toward the default vectorizer model or explore a different solution.

**Comment by gau-nernst** [comment]
I do understand that. Also, I just remembered that by default, CountVectorizer only considers alphanumeric characters (see parameter `token_pattern` [here](https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html). Therefore, the default `._preprocess_text()` would not affect the default CountVectorizer behavior.

**Comment by MaartenGr** [comment]
I know, what I meant was suggesting that I might move the default preprocessing into the CountVectorizer and set that as a default which can be overridden with a custom CountVectorizer.

**Comment by MaartenGr** [comment]
Due to inactivity, I'll be closing this issue. Let me know if you want me to re-open the issue!
