### ISSUE TITLE
Example usage of BERTopic

### ISSUE THREAD

**Issue by lorenzobalzani** [MaartenGr/BERTopic#950]
I recently faced a challenge in which I had to use BERTopic to tackle a text clustering task. Let me know @MaartenGr if a PR - with the notebook as a usage example - could be appreciated.

**Comment by MaartenGr** [comment]
Glad to hear that you are willing to share your use case! I am actually planning to collect a bunch of use cases in the upcoming weeks just not in a notebook format. These tend to be rather large and I would actually want to prevent a large repo. Instead, it would be great if you could share a short description of the usage. I am planning to share the link to the form somewhere this week, so I'll let you know if you want, where you can share that use case.

**Comment by lorenzobalzani** [comment]
Sounds great. I'll be waiting for the link.

**Comment by MaartenGr** [comment]
I posted the link online yesterday and you can find more about sharing your use case [here](https://github.com/MaartenGr/BERTopic/issues/956).
