### ISSUE TITLE
Preprocessing for BERTopic

### ISSUE THREAD

**Issue by aleksandar-devedzic** [MaartenGr/BERTopic#960]
Should we use some kind of preprocessing before we pass documents to BERTopic (english, german, multilingual text)?
Can that increase or decrease performance of the model? 
For example:

1. removing stop-words
2. removing punctuations
3. removing special chars
4. keeping only certain types of words (NOUNS, VERBS etc.)

**Comment by MaartenGr** [comment]
There are two types of preprocessing in BERTopic. The first is preprocessing the documents before passing them to BERTopic. Whether you should do preprocessing at this step depends on the embedding model that you use. For example, if you use a transformer-based model, then it is often nog necessary to perform preprocessing. However, if you are using a Bag-of-Words like approach as the embedding model, then you typically do want to preprocess the data. 

The second is preprocessing the documents after generating the clusters but before creating the topic representations. You can do this by passing a `CountVectorizer` to BERTopic and changing the preprocessing scheme there. You can find more about the vectorizers [here](https://maartengr.github.io/BERTopic/getting_started/vectorizers/vectorizers.html) and the general pipeline of BERTopic [here](https://maartengr.github.io/BERTopic/algorithm/algorithm.html).

**Comment by MaartenGr** [comment]
Due to inactivity, I'll be closing this issue. Let me know if you want me to re-open the issue!
