### ISSUE TITLE
Add stopword support for generate_topic_labels

### ISSUE THREAD

**Issue by dschwalm** [MaartenGr/BERTopic#962]
Hi Maarten,

Topics labels frequently contain stop words that are not informative at all (she, her, and, my, steven, john, <any domain specific stopword>). It would be great if generate_topic_labels would support a stopwords arguments, which would prevent these stop words getting into topic labels.
I am more than happy to create a pull request if you think that is something that BERTopic should support.
It would be definitely useful for me.

Thanks,
Daniel

**Comment by MaartenGr** [comment]
If you want to remove stopwords from the topic labels, I would advise using the `CountVectorizer` for that. It allows for removing stopwords and general processing of the topic labels without needing to affect the input documents. You can find more about removing stopwords [here](https://maartengr.github.io/BERTopic/getting_started/vectorizers/vectorizers.html#stop_words) and [here](https://maartengr.github.io/BERTopic/faq.html#how-do-i-remove-stop-words).

**Comment by dschwalm** [comment]
Thanks. But this would remove stopwords from the text representations themselves, what I am fine with.
I am afraid that removing the stopwords like this would affect the performance of the modeling, I think that is what I read from you somewhere. But if you think that this is the proper solution, I will go to this direction.

**Comment by MaartenGr** [comment]
Removing stopwords using the `CountVectorizer` will not affect the underlying clustering in any way, so it is perfectly fine to remove stopwords using this approach. What you might have read is that removing stopwords **before** passing them to BERTopic is typically not advised. However, using the `CountVectorizer` will remove stopwords **after** creating the clusters and hence will not affect the clustering process in any way. It might be worthwhile to check out the [algorithm](https://maartengr.github.io/BERTopic/algorithm/algorithm.html) page to get a more intuitive understanding of the effect of each model in BERTopic's pipeline.
