### ISSUE TITLE
Online topic modeling - precomputed embeddings 

### ISSUE THREAD

**Issue by lila-97** [MaartenGr/BERTopic#966]
Hi Martin! Thanks for creating this amazing library... I have a (possibly dumb) question: I have precomputed embeddings with Sentence Transformer on a massive dataset (3.5+ million tweets), but I don't have enough RAM on my machine for all the other training steps, so I was thinking of using online topic modeling... can I use the embeddings I already computed? 
From the documentation I would assume I can, but I see you use .partial_fit() directly on the docs, not on the embeddings, so I'm not sure how? 
Thank you in advance for any help on this issue.

**Comment by MaartenGr** [comment]
Yes, you definitely can! When you run `.partial_fit`, there is the option to supply it with the embeddings for each set of documents. So it would be something like the following:

```python
doc_chunks = [all_docs[i:i+1000] for i in range(0, len(all_docs), 1000)]
embedding_chunks = [embeddings[i:i+1000] for i in range(0, len(embeddings), 1000)]

for doc_chunk, embedding_chunk in zip(doc_chunks, embedding_chunks):
    topic_model.partial_fit(doc_chunk, embedding_chunk)
```

**Comment by lila-97** [comment]
thank you so much for your quick reply! 

I am assuming the `embeddings` variable generated by `embeddings = sentence_model.encode(docs)` has the same indexing as `docs`... is that correct?

**Comment by MaartenGr** [comment]
Yes, that is correct which should save you quite some problems finding the document with the right embedding.

**Comment by lila-97** [comment]
Good to know! I have one more question... what is the right way to visualize documents + topics when the model has been trained with this method? 
I trained my model in 10 batches and saved it, alongside the embeddings (which were done all at once) 
Now, when I run 
`my_model.visualize_documents(tweets, embeddings=embeddings)`
I get this almost empty visualization: 
![bertopic_error](https://user-images.githubusercontent.com/94906550/215462239-dac04e9e-d54d-4862-9ef2-2c1d84dd80d9.PNG)
Could you please explain why this happens and how to fix it? Thank you so much in advance

**Comment by MaartenGr** [comment]
Most likely, you did not update the internal `.topics_` to match with every single batch. With `.partial_fit` and online learning in general, only the latest batch of predictions is typically saved. This means that everything before is not saved within the model and you will need to update that yourself.

**Comment by lila-97** [comment]
Hi Marteen, could you please confirm that if I run 
```
# Incrementally fit the topic model by training on 1000 documents at a time and track the topics in each iteration
topics = []
```
`for docs in doc_chunks:`
    `topic_model.partial_fit(docs)`
    `topics.extend(topic_model.topics_)
`
`topic_model.topics_ = topics`

and then run `topic_model.save()`, I will actually be saving the model trained on the WHOLE dataset? Or is there any additional step to take? 
Thank yo uvery much in advance for your help

**Comment by MaartenGr** [comment]
@lila-97 Yes, when you run `.partial_fit` sequentially, it will be fit on the whole dataset unless you performed a regular `.fit` afterward.

**Comment by MaartenGr** [comment]
Due to inactivity, I'll be closing this issue. Let me know if you want me to re-open the issue!
