### ISSUE TITLE
TypeError: Cannot use scipy.linalg.eigh for sparse A with k >= N. Use scipy.linalg.eigh(A.toarray()) or reduce k.

### ISSUE THREAD

**Issue by cpoptic** [MaartenGr/BERTopic#97]
```
from bertopic import BERTopic

docs = ["Hi i'm a doc", "i'm also a doc", "I'm a document", "this is an apple", "yet another topic"]

topic_model = BERTopic()
topics, _ = topic_model.fit_transform(docs)
```

> 
> Running BERTopic model...
> C:\ProgramData\Anaconda3\envs\my_project\lib\site-packages\umap\umap_.py:2213: UserWarning: n_neighbors is larger than the dataset size; truncating to X.shape[0] - 1
>   warn(
> C:\ProgramData\Anaconda3\envs\my_project\lib\site-packages\scipy\sparse\linalg\eigen\arpack\arpack.py:1593: RuntimeWarning: k >= N for N * N square matrix. Attempting to use scipy.linalg.eigh instead.
>   warnings.warn("k >= N for N * N square matrix. "
> ---------------------------------------------------------------------------
> TypeError                                 Traceback (most recent call last)
> <ipython-input-28-7dcfeabe3647> in <module>
>       1 print('Running BERTopic model...')
>       2 # topics, _ = tqdm(topic_model.fit_transform(docs))
> ----> 3 topics, _ = tqdm(topic_model.fit_transform(short_docs))
> 
> C:\ProgramData\Anaconda3\envs\my_project\lib\site-packages\bertopic\_bertopic.py in fit_transform(self, documents, embeddings)
>     279 
>     280         # Reduce dimensionality with UMAP
> --> 281         umap_embeddings = self._reduce_dimensionality(embeddings)
>     282 
>     283         # Cluster UMAP embeddings with HDBSCAN
> 
> C:\ProgramData\Anaconda3\envs\my_project\lib\site-packages\bertopic\_bertopic.py in _reduce_dimensionality(self, embeddings)
>    1101                                         low_memory=self.low_memory).fit(embeddings)
>    1102         else:
> -> 1103             self.umap_model.fit(embeddings)
>    1104         umap_embeddings = self.umap_model.transform(embeddings)
>    1105         logger.info("Reduced dimensionality with UMAP")
> 
> C:\ProgramData\Anaconda3\envs\my_project\lib\site-packages\umap\umap_.py in fit(self, X, y)
>    2551 
>    2552         if self.transform_mode == "embedding":
> -> 2553             self.embedding_, aux_data = self._fit_embed_data(
>    2554                 self._raw_data[index], n_epochs, init, random_state,  # JH why raw data?
>    2555             )
> 
> C:\ProgramData\Anaconda3\envs\my_project\lib\site-packages\umap\umap_.py in _fit_embed_data(self, X, n_epochs, init, random_state)
>    2578         replaced by subclasses.
>    2579         """
> -> 2580         return simplicial_set_embedding(
>    2581             X,
>    2582             self.graph_,
> 
> C:\ProgramData\Anaconda3\envs\my_project\lib\site-packages\umap\umap_.py in simplicial_set_embedding(data, graph, n_components, initial_alpha, a, b, gamma, negative_sample_rate, n_epochs, init, random_state, metric, metric_kwds, densmap, densmap_kwds, output_dens, output_metric, output_metric_kwds, euclidean_output, parallel, verbose)
>    1052     elif isinstance(init, str) and init == "spectral":
>    1053         # We add a little noise to avoid local minima for optimization to come
> -> 1054         initialisation = spectral_layout(
>    1055             data,
>    1056             graph,
> 
> C:\ProgramData\Anaconda3\envs\my_project\lib\site-packages\umap\spectral.py in spectral_layout(data, graph, dim, random_state, metric, metric_kwds)
>     325     try:
>     326         if L.shape[0] < 2000000:
> --> 327             eigenvalues, eigenvectors = scipy.sparse.linalg.eigsh(
>     328                 L,
>     329                 k,
> 
> C:\ProgramData\Anaconda3\envs\my_project\lib\site-packages\scipy\sparse\linalg\eigen\arpack\arpack.py in eigsh(A, k, M, sigma, which, v0, ncv, maxiter, tol, return_eigenvectors, Minv, OPinv, mode)
>    1596 
>    1597         if issparse(A):
> -> 1598             raise TypeError("Cannot use scipy.linalg.eigh for sparse A with "
>    1599                             "k >= N. Use scipy.linalg.eigh(A.toarray()) or"
>    1600                             " reduce k.")
> 
> TypeError: Cannot use scipy.linalg.eigh for sparse A with k >= N. Use scipy.linalg.eigh(A.toarray()) or reduce k.

**Comment by MaartenGr** [comment]
Although I am not familiar with the specific error, it definitely seems to be caused by the number of documents you are passing to BERTopic. If you were to pass a few hundred documents and preferably at least a few thousand, this issue should not be raised.

**Comment by mararn1618** [comment]
Getting the same error with

- 306 documents
- vectorizer_model = CountVectorizer(ngram_range=(1, 2), stop_words="english")
- model = BERTopic(
  - top_n_words=15,
  - nr_topics="auto",
  - embedding_model="all-MiniLM-L6-v2",
  - verbose=True,
  - vectorizer_model=vectorizer_model )

**Comment by MaartenGr** [comment]
@mararn1618 Could you share your entire code for preparing the data and fitting the model? Also, which version of BERTopic and its dependencies are you using? Also, it might be worthwhile to double the number of documents (by simply creating duplicates) to see if that results in the same issues which might point towards the number of documents.

**Comment by markus-arndt-senacor** [comment]
Hey @MaartenGr, sure. I have actually realized that I did only have ~129 documents and had also applied your suggested workaround (duplicating the documents; "STEP 5" in my sourcecode).

My code consists of two files:
- bertopic_02.py (main file)
- jira_make_pandas_dataframe.py (convert jira tickets in json format to dataframe)

Unfortunately I can not provide the document data (jira json) publicly, but the JSONs can be pulled via browser via # `https://<JIRA-INSTANCE>.atlassian.net/rest/api/3/search?jql=project=<PROJECT>&startAt=0&maxResults=9000&expand=renderedFields&fields=key,description,summary,comments,issuetype,status,parent,project,assignee,reporter`


**bertopic_02.py**
```
import jira_make_pandas_dataframe
from bertopic import BERTopic
from sklearn.feature_extraction.text import CountVectorizer
import re
import pandas as pd


# STEP 1 Read Data
data: pd.DataFrame = jira_make_pandas_dataframe.jiraJsonToPandas(
    [
        'data-rendered/jira_2022-04-14_startAt_000.json',
        'data-rendered/jira_2022-04-14_startAt_100.json',
        'data-rendered/jira_2022-04-14_startAt_200.json',
        'data-rendered/jira_2022-04-14_startAt_300.json',
     ]
)
data = data.fillna("")

# Remove Jira Subtasks
data = data[data["Issue Type"] != "Subtask"]

# STEP 2 Build Documents from Jira Tickets
def calculateContent(data: pd.DataFrame) -> pd.Series:
    return data.apply (lambda row: calculateContentForOneRow(row), axis=1)
def calculateContentForOneRow(row: pd.Series) -> str:
    rowContent = ""
    if row["Parent summary"] is not None and len(row["Parent summary"])>0:
        rowContent = rowContent + row["Parent summary"] + ". "
    if row["Summary"] is not None and len(row["Summary"])>0:
        rowContent = rowContent + row["Summary"] + ". "
    if row["Description"] is not None and len(row["Description"])>0:
        rowContent = rowContent + row["Description"]
    return rowContent.lower()
data["content"]: pd.Series = calculateContent(data)

# STEP 3 Data Cleaning
def cleanse(s: pd.Series) -> pd.Series:
    s = s.replace(to_replace='from:(.*\n)',value='',regex=True) ##remove from to email
    s = s.replace(to_replace='lines:(.*\n)',value='',regex=True)
    #s = s.replace(to_replace='[\\.!"#$%&\'()*+,/:;<=>?@[\\]^_`{|}~]',value=' ',regex=True) #remove punctuation except
    #s = s.replace(to_replace='-',value=' ',regex=True)
    #s = s.replace(to_replace='\s+',value=' ',regex=True)    #remove new line
    s = s.str.replace(r'\[https?://.+\|(.+)\|.+\]',r'\1',regex=True) # replace jira link with anchor test
    s = s.str.replace(r'\[https?://.+\|(.+)\]',r'\1',regex=True) # replace jira link with anchor test
    s = s.replace(to_replace='!image.+!',value='',regex=True) #remove jira images
    s = s.replace(to_replace='https?://[^\s]+',value='',regex=True) #remove jira urls
    s = s.replace(to_replace='[\*]',value='',regex=True) #remove some jira stuff
    s = s.replace(to_replace='[\n\[\]]',value='',regex=True) #replace some jira stuff with whitespace
    s = s.replace(to_replace='  ',value=' ',regex=True)
    s = s.apply(lambda x:x.strip()) # Ltrim and Rtrim of whitespace
    return s
data["content"] = cleanse(data["content"])

data_small = data[['Summary', 'Issue key', 'Issue id', 'Issue Type', 'Status', 'Project key','content']]


# STEP 4 Fit model
# BERTopic https://towardsdatascience.com/interactive-topic-modeling-with-bertopic-1ea55e7d73d8
# Pretrained models https://www.sbert.net/docs/pretrained_models.html
# stop words - https://github.com/MaartenGr/BERTopic/issues/40#issuecomment-808160695
vectorizer_model = CountVectorizer(ngram_range=(1, 2), stop_words="english")

model = BERTopic(top_n_words=15,
                 nr_topics="auto",
                 embedding_model="all-MiniLM-L6-v2",
                 verbose=True,
                 vectorizer_model=vectorizer_model
                 )


# STEP 5 - Workaround for low number of Documents
bertopic_docs = data_small["content"].to_list()
if len(bertopic_docs) < 300: # Workaround if not enough documents https://github.com/MaartenGr/BERTopic/issues/97 , https://github.com/MaartenGr/Concept/issues/5
    bertopic_docs.extend(bertopic_docs)

topics, probabilities = model.fit_transform(bertopic_docs)


# STEP 6 Print

print("docs: {}\n".format(model.get_representative_docs()))
print(model.get_topic_info())

bar_chart = model.visualize_barchart(n_words=15)
# bar_chart.show()

map_chart = model.visualize_topics()
# map_chart.show()
```


**jira_make_pandas_dataframe.py**

```

# https://<JIRA-INSTANCE>.atlassian.net/rest/api/3/search?jql=project=<PROJECT>&startAt=0&maxResults=9000&expand=renderedFields&fields=key,description,summary,comments,issuetype,status,parent,project,assignee,reporter

from bs4 import BeautifulSoup
import pandas as pd
from typing import List
import json


defColumns = ['Summary', 'Parent summary', 'Description', 'Issue key', 'Issue id', 'Issue Type', 'Status', 'Assignee', 'Reporter', 'Project key']


def jiraJsonToPandas(jiraFileNames: List[str]) -> pd.DataFrame:

    frames = [ jiraJsonToPandas_OneFile(fileName) for fileName in jiraFileNames ]
    finalDF = pd.concat(frames).reset_index(drop=True)

    return finalDF

def jiraJsonToPandas_OneFile(jiraFileName: str) -> pd.DataFrame:

    f = open(jiraFileName)
    data = json.load(f)
    issues_list = data["issues"]
    allDataRows = []

    for issue in issues_list:
        summary = issue["fields"]["summary"]
        description = issue["renderedFields"]["description"]

        parentSummary = ""
        try:
            parentSummary = issue["parent"]["fields"]["summary"]
        except:
            parentSummary = ""
        issueKey = issue["key"]
        issueId = issue["id"]
        issueType = issue["fields"]["issuetype"]["name"]
        status = issue["fields"]["status"]["name"]

        assignee = ""
        try:
            assignee = issue["fields"]["assignee"]["accountId"]
        except:
            assignee = ""

        reporter = ""
        try:
            reporter = issue["fields"]["reporter"]["accountId"]
        except:
            reporter = ""

        projectKey = issue["fields"]["project"]["key"]

        #clean html
        description = BeautifulSoup(description, "lxml").text

        row = [summary,parentSummary,description,issueKey,issueId,issueType,status,assignee,reporter,projectKey]
        allDataRows.append(row)

    f.close()

    df = pd.DataFrame(data = allDataRows,columns=defColumns)
    return df

```

**Comment by mararn1618** [comment]
Hey @MaartenGr, sure. I have actually realized that I did only have ~129 documents and had also applied your suggested workaround (duplicating the documents; "STEP 5" in my sourcecode).

My code consists of two files:
- bertopic_02.py (main file)
- jira_make_pandas_dataframe.py (convert jira tickets in json format to dataframe)

Unfortunately I can not provide the document data (jira json) publicly, but the JSONs can be pulled via browser via # `https://<JIRA-INSTANCE>.atlassian.net/rest/api/3/search?jql=project=<PROJECT>&startAt=0&maxResults=9000&expand=renderedFields&fields=key,description,summary,comments,issuetype,status,parent,project,assignee,reporter`


**bertopic_02.py**
```
import jira_make_pandas_dataframe
from bertopic import BERTopic
from sklearn.feature_extraction.text import CountVectorizer
import re
import pandas as pd


# STEP 1 Read Data
data: pd.DataFrame = jira_make_pandas_dataframe.jiraJsonToPandas(
    [
        'data-rendered/jira_2022-04-14_startAt_000.json',
        'data-rendered/jira_2022-04-14_startAt_100.json',
        'data-rendered/jira_2022-04-14_startAt_200.json',
        'data-rendered/jira_2022-04-14_startAt_300.json',
     ]
)
data = data.fillna("")

# Remove Jira Subtasks
data = data[data["Issue Type"] != "Subtask"]

# STEP 2 Build Documents from Jira Tickets
def calculateContent(data: pd.DataFrame) -> pd.Series:
    return data.apply (lambda row: calculateContentForOneRow(row), axis=1)
def calculateContentForOneRow(row: pd.Series) -> str:
    rowContent = ""
    if row["Parent summary"] is not None and len(row["Parent summary"])>0:
        rowContent = rowContent + row["Parent summary"] + ". "
    if row["Summary"] is not None and len(row["Summary"])>0:
        rowContent = rowContent + row["Summary"] + ". "
    if row["Description"] is not None and len(row["Description"])>0:
        rowContent = rowContent + row["Description"]
    return rowContent.lower()
data["content"]: pd.Series = calculateContent(data)

# STEP 3 Data Cleaning
def cleanse(s: pd.Series) -> pd.Series:
    s = s.replace(to_replace='from:(.*\n)',value='',regex=True) ##remove from to email
    s = s.replace(to_replace='lines:(.*\n)',value='',regex=True)
    #s = s.replace(to_replace='[\\.!"#$%&\'()*+,/:;<=>?@[\\]^_`{|}~]',value=' ',regex=True) #remove punctuation except
    #s = s.replace(to_replace='-',value=' ',regex=True)
    #s = s.replace(to_replace='\s+',value=' ',regex=True)    #remove new line
    s = s.str.replace(r'\[https?://.+\|(.+)\|.+\]',r'\1',regex=True) # replace jira link with anchor test
    s = s.str.replace(r'\[https?://.+\|(.+)\]',r'\1',regex=True) # replace jira link with anchor test
    s = s.replace(to_replace='!image.+!',value='',regex=True) #remove jira images
    s = s.replace(to_replace='https?://[^\s]+',value='',regex=True) #remove jira urls
    s = s.replace(to_replace='[\*]',value='',regex=True) #remove some jira stuff
    s = s.replace(to_replace='[\n\[\]]',value='',regex=True) #replace some jira stuff with whitespace
    s = s.replace(to_replace='  ',value=' ',regex=True)
    s = s.apply(lambda x:x.strip()) # Ltrim and Rtrim of whitespace
    return s
data["content"] = cleanse(data["content"])

data_small = data[['Summary', 'Issue key', 'Issue id', 'Issue Type', 'Status', 'Project key','content']]


# STEP 4 Fit model
# BERTopic https://towardsdatascience.com/interactive-topic-modeling-with-bertopic-1ea55e7d73d8
# Pretrained models https://www.sbert.net/docs/pretrained_models.html
# stop words - https://github.com/MaartenGr/BERTopic/issues/40#issuecomment-808160695
vectorizer_model = CountVectorizer(ngram_range=(1, 2), stop_words="english")

model = BERTopic(top_n_words=15,
                 nr_topics="auto",
                 embedding_model="all-MiniLM-L6-v2",
                 verbose=True,
                 vectorizer_model=vectorizer_model
                 )


# STEP 5 - Workaround for low number of Documents
bertopic_docs = data_small["content"].to_list()
if len(bertopic_docs) < 300: # Workaround if not enough documents https://github.com/MaartenGr/BERTopic/issues/97 , https://github.com/MaartenGr/Concept/issues/5
    bertopic_docs.extend(bertopic_docs)

topics, probabilities = model.fit_transform(bertopic_docs)


# STEP 6 Print

print("docs: {}\n".format(model.get_representative_docs()))
print(model.get_topic_info())

bar_chart = model.visualize_barchart(n_words=15)
# bar_chart.show()

map_chart = model.visualize_topics()
# map_chart.show()
```


**jira_make_pandas_dataframe.py**

```

# https://<JIRA-INSTANCE>.atlassian.net/rest/api/3/search?jql=project=<PROJECT>&startAt=0&maxResults=9000&expand=renderedFields&fields=key,description,summary,comments,issuetype,status,parent,project,assignee,reporter

from bs4 import BeautifulSoup
import pandas as pd
from typing import List
import json


defColumns = ['Summary', 'Parent summary', 'Description', 'Issue key', 'Issue id', 'Issue Type', 'Status', 'Assignee', 'Reporter', 'Project key']


def jiraJsonToPandas(jiraFileNames: List[str]) -> pd.DataFrame:

    frames = [ jiraJsonToPandas_OneFile(fileName) for fileName in jiraFileNames ]
    finalDF = pd.concat(frames).reset_index(drop=True)

    return finalDF

def jiraJsonToPandas_OneFile(jiraFileName: str) -> pd.DataFrame:

    f = open(jiraFileName)
    data = json.load(f)
    issues_list = data["issues"]
    allDataRows = []

    for issue in issues_list:
        summary = issue["fields"]["summary"]
        description = issue["renderedFields"]["description"]

        parentSummary = ""
        try:
            parentSummary = issue["parent"]["fields"]["summary"]
        except:
            parentSummary = ""
        issueKey = issue["key"]
        issueId = issue["id"]
        issueType = issue["fields"]["issuetype"]["name"]
        status = issue["fields"]["status"]["name"]

        assignee = ""
        try:
            assignee = issue["fields"]["assignee"]["accountId"]
        except:
            assignee = ""

        reporter = ""
        try:
            reporter = issue["fields"]["reporter"]["accountId"]
        except:
            reporter = ""

        projectKey = issue["fields"]["project"]["key"]

        #clean html
        description = BeautifulSoup(description, "lxml").text

        row = [summary,parentSummary,description,issueKey,issueId,issueType,status,assignee,reporter,projectKey]
        allDataRows.append(row)

    f.close()

    df = pd.DataFrame(data = allDataRows,columns=defColumns)
    return df

```

**Comment by MaartenGr** [comment]
In that case, I think it might be that you have too few documents to work with. Although you tried to increase that value by doubling the number of documents, it might still be too few for it to train UMAP on. Having said that, which version of the dependencies are you using?

**Comment by mararn1618** [comment]
Hey Maarten, to clarify a misunderstanding: Duplicating the documents did actually help.

I'm using:
 - bertopic 0.9.4
 - sentence-transformers 2.2.0
 - umap-learn 0.5.2
 - hdbscan 0.8.28
 - scikit-learn 1.0.2
 - numpy 1.21.6

**Comment by MaartenGr** [comment]
Since duplicating documents helped, then it might be that you have too few documents to work with in order for UMAP to create lower-dimensional representations. You could use the duplication trick to train your model and then divide all frequencies by 2 to get the correct values.

**Comment by anton-purnama** [comment]
How to solve this kind of issue?

**Comment by MaartenGr** [comment]
@anton-purnama Did you try increasing the number of documents you pass to the model? That is mainly what this issue is about and what we discussed above.

**Comment by buhrmann** [comment]
See here for the probable reason and fix: https://github.com/lmcinnes/umap/issues/201

The number of dimensions you're embedding into with UMAP must be at least 2 less than the number of samples (documents). So you cannot e.g. embed into 10 dimensions if you haven't got at least 12 samples. 

Not sure how to configure that in BERTopic though...

**Comment by kstohr** [comment]
I know this issue is closed. However, we're running a short time window model and that sometimes results in a low sample document size and came across this error.  The fix is to update a few parameters.

Say you have 5 documents.... The min component size (embedding size) on UMAP Is set to `bertopic.umap_model.n_components = 5`.  You can reduce `bertscan.umap_model.n_components=3`, and you will avoid this error. As indicated above this is 2 less than the number of sample documents.

However, with this minimum number of documents, you may also find that you get clustering errors. For example, if you are using HDBSCAN you may get an error like this: 

`ValueError: k must be less than or equal to the number of training points`

Similarly, in that case, you need to reduce the minimum cluster size (k) from the default of 10 to, say, 3: `topic_model.hdbscan_model.min_cluster_size = 3`

Of course, this is likely a terrible model. However, there are times in testing, production when the number of sample documents may be smaller than expected.

code: 
```
## Example for training a bert topic model

from bertopic import BERTopic

# Create a BERTopic instance
topic_model = BERTopic()

print("Default dimensionality reduction n-components %s", topic_model.umap_model.n_components)
topic_model.umap_model.n_components = 3
print("Updated dimensionality reduction n-components %s", topic_model.umap_model.n_components)

print("Default cluster size %s", topic_model.hdbscan_model.min_cluster_size)
topic_model.hdbscan_model.min_cluster_size = 3
print("Updated cluster size %s", topic_model.hdbscan_model.min_cluster_size)

print("Default min samples %s", topic_model.hdbscan_model.min_samples)
topic_model.hdbscan_model.min_samples = 3
print("Updated min samples %s", topic_model.hdbscan_model.min_samples)

# Define the documents
documents = [
    "Philadelphia is the largest city in Pennsylvania.",
    "Machine learning algorithms build a mathematical model based on sample data, known as training data.",
    "The elections are held in November every year.",
    "General elections determine the members of the national legislature.",
    "Supervised learning is a type of machine learning where the model is trained on labeled data.",
    # "New York City is known as the Big Apple.",
    # "I love hot dogs in New York City.",
    # "HDBSCAN is a clustering algorithm used in unsupervised machine learning.",
    # "UMap is a dimensionality reduction technique often used in machine learning.",
    # "BERT is a transformer-based model designed for natural language processing tasks.",
    # "NLP stands for Natural Language Processing, a field of AI focused on the interaction between computers and human language.",
]

# Fit the model and transform the documents into topics
topics, probabilities = topic_model.fit_transform(documents)

# Print the topics
for _, topic in topic_model.get_topic_info().iterrows():
    print(f"Topic #{topic['Topic']}:")
    print(topic_model.get_topic(topic["Topic"]))

```

output: 
```
Default dimensionality reduction n-components %s 5
Updated dimensionality reduction n-components %s 3
Default cluster size %s 10
Updated cluster size %s 3
Default min samples %s None # no change
Topic #-1:
[('the', np.float64(0.231226896048332)), ('learning', np.float64(0.1656644944566249)), ('data', np.float64(0.1656644944566249)), ('is', np.float64(0.1656644944566249)), ('machine', np.float64(0.12506362281783115)), ('in', np.float64(0.12506362281783115)), ('model', np.float64(0.12506362281783115)), ('elections', np.float64(0.12506362281783115)), ('of', np.float64(0.12506362281783115)), ('on', np.float64(0.12506362281783115))]
```
