### ISSUE TITLE
`.transform()` on an existing model killing kernel

### ISSUE THREAD

**Issue by sbarbat** [MaartenGr/BERTopic#970]
Hey @MaartenGr, first of all thanks for the awesome work with BERTopic.

I've created a model that I saved on disk and when I load it and try to do a `transform()` for inference of a new set of documents (around 7000) the kernel dies.

I'm working on an AWS Ubuntu 20.04 `p3.2xlarge` machine which has 64Gb RAM and a Tesla 100V GPU, so don't think is a problem with the hardware.

The weird thing is that if I recreate the model with `fit_transform()`, and straight after trying the `transform()` of these documents, it works.

I'm using `cuML` to use GPU when generating the model:

```python
# Create instances of GPU-accelerated UMAP and HDBSCAN
umap_model = UMAP(n_components=5, n_neighbors=15, min_dist=0.0)
hdbscan_model = HDBSCAN(min_samples=10, gen_min_span_tree=True, prediction_data=True)

topic_model = BERTopic(embedding_model='sentence-transformers/all-mpnet-base-v2',
                       umap_model=umap_model,
                       hdbscan_model=hdbscan_model,
                       calculate_probabilities=True,
                       verbose=True)
topics, probs = topic_model.fit_transform(docs, embeddings=matrix)
topic_model.get_topic_info()
```

On the meantime, I thought of running the `UMAP` with `random_state` parameter, so doesn't matter if I have to generate the model again, will get the same results, right?

**Comment by sbarbat** [comment]
Im not getting an error on my Jupyter notebook when the kernel dies either..

**Comment by drob-xx** [comment]
@sbarbat See #934 re: cuML UMAP reproducibility for a bug and a work-around.

**Comment by sbarbat** [comment]
Brilliant @drob-xx, thank you for answering, will close this one and leave yours
