### ISSUE TITLE
Finding Sentiments of Topics in BERTopic

### ISSUE THREAD

**Issue by gulyazici** [MaartenGr/BERTopic#971]
Hi Maarteen,

I am using BERTopic to do topic modeling on a dataset. I also want to do sentiment analysis and I can do it with using NLTK library. But when I get topics from BERTopic algoritm, can't I find the sentiments of each topic?

I mean like below:
![image](https://user-images.githubusercontent.com/82728792/215340760-d132721f-7d3b-43d5-a323-8d1ab9a8bca7.png)

I am really looking forward to hearing your reply soon!

**Comment by MaartenGr** [comment]
Sentiment analysis is not something that is implemented within BERTopic as that is currently outside of its scope. Having said that, the image that you created should be possible to create for topics generated within BERTopic. Let's say you created a topic model with BERTopic and that gives you back 10 different topics. To generate the image above, you can extract the main sentiment for each document in each topic and aggregate the results. These results should then give you the distribution of sentiment across each topic.

**Comment by Yzcddk** [comment]
> 嗨马丁，
> 
> 我正在使用 BERTopic 对数据集进行主题建模。我也想做情绪分析，我可以用 NLTK 库来做。但是当我从 BERTopic 算法中获取主题时，我不能找到每个主题的情绪吗？
> 
> 我的意思是像下面这样： ![图像](https://user-images.githubusercontent.com/82728792/215340760-d132721f-7d3b-43d5-a323-8d1ab9a8bca7.png)
> 
> 我真的很期待很快听到你的回复！

Hello gulyazici, sorry to bother you, I am very interested in the picture(Topic-Based Review Emotions) you attached, can you tell me where it comes from? Thank you so much!

**Comment by gulyazici** [comment]
Hi,
I guess, it is tableu program, from this paper: https://www.researchgate.net/publication/358796996_The_Voice_of_the_Consumer_on_sVoD_Systems_During_Covid-19_A_Service_Opportunity_Mining_Approach

**Comment by Yzcddk** [comment]
> Hi, I guess, it is tableu program, from this paper: https://www.researchgate.net/publication/358796996_The_Voice_of_the_Consumer_on_sVoD_Systems_During_Covid-19_A_Service_Opportunity_Mining_Approach

Pretty thanks! This worked for me.
