### ISSUE TITLE
Load a trained model on a dataset with different length doing hierarchical topic modeling 

### ISSUE THREAD

**Issue by beeman-93** [MaartenGr/BERTopic#974]
Hello Maarten, I have a question about how to load a trained model on a dataset with different length to do hierarchical topic modeling. 
I trained my model on for example 1M lines of texts and saved that model. Now I want to use that model to do hierarchical topic modeling on 10M lines of texts. 
When I run .hierarchical_topics(texts), it gives me the error: 
All arrays must be of the same length
Is it possible to fix this issue? 
Thanks a lot.

**Comment by MaartenGr** [comment]
The hierarchical topic modeling can only be performed on the documents it was trained on as it internally uses the c-TF-IDF representation of those documents, as well as the topics found during training. If you are happy with the topics that were found during the 1M training process, then there is no need to perform hierarchical topic modeling on the 10M lines of text especially if the 1M text is a representative sample of the 10M text.

**Comment by beeman-93** [comment]
Thank you for the quick response. Understood! 👍
