### ISSUE TITLE
custom labels on visualize_topics(), visualize_hierarchy()

### ISSUE THREAD

**Issue by dschwalm** [MaartenGr/BERTopic#976]
Some visualize* methods support custom topic labels, others don't.
I would like to see my custom labels using the two methods in the subject.
Any plans to add this option to these two?

Thanks,
Daniel

**Comment by MaartenGr** [comment]
`visualize_hierarchy` can be a bit more complex due to the new topics that are created which might be confusing on the API level if you can only pass the lower-level labels, in contrast to all other visualizations. Custom labels will be added for `.visualize_topics`.
