### ISSUE TITLE
fit_transform taking exceptionally long to run

### ISSUE THREAD

**Issue by cpoptic** [MaartenGr/BERTopic#98]
From the `quickstart`,

```
from bertopic import BERTopic
from sklearn.datasets import fetch_20newsgroups
 
docs = fetch_20newsgroups(subset='all',  remove=('headers', 'footers', 'quotes'))['data']

topic_model = BERTopic()
topics, _ = topic_model.fit_transform(docs)
```

the `fit_transform()` method call in the last line above is taking exceptionally long to run on this newsgroups dataset.
What could be causing this?  There is zero feedback while running that line so it appears to hang for hours.

I have even tried setting the `low_memory` parameter to True

```
model = BERTopic(language="english",
                min_topic_size=1,
                nr_topics=3,
                low_memory=True)
```

**Comment by MaartenGr** [comment]
Sorry to hear you are facing this issue. To start off, it may be helpful if you were to set `verbose` to True when instantiating BERTopic. This enables logging and should give you an idea of where it hangs for you. 

Second, if the 20Newsgroups example is running for hours then it is highly likely you are not using a GPU. For example, if I were to run this example on a GPU-enabled Google Colab session it runs without any issues.

Lastly, the `low_memory` parameter does not speed up BERTopic but merely allows you to actually run it in case you have little memory available. In practice, this will often reduce its speed.

**Comment by cpoptic** [comment]
Ah yes, I was running on a CPU not a GPU.
The `fit_transfor()` on the fetch_20newsgroups took 1 hour 29 minutes to run, am I'm guessing that was due to using a CPU.

Thanks for the suggestion to set `verbose` parameter to True when instantiating BERTopic; that logging should definitely help.
Similarly, I think supporting a progress-bar such as `tqdm` would help give users progress updates while the model is running.
