### ISSUE TITLE
reduce_outliers assigning outliers to pre-merge topics

### ISSUE THREAD

**Issue by Var3n** [MaartenGr/BERTopic#980]
Hi Maarten,

I have a (hopefully) quick question regarding outlier reduction:

Before I used the  c-TF-IDF Method to reduce outliers, I merged a handful of similar topics by using merge_topics. Now, when I use reduce_outliers some of them get assigned to topics that have been merged. Is there an easy way to get a mapping between the old and new topics to re-assign the outliers to the merged topics or is there some additional thing I have to consider before using outlier reduction after merging topics?

Thanks in advance!

**Comment by MaartenGr** [comment]
You can get all assignments of topics and how they have changed with `topic_model.topic_mapper_.mappings_`. That contains a numpy matrix where each column represents the topics. The last column will be the manual merging that you did with `.merge_topics`. In order to do this, I think you would have to make use of the original topic assignments from `topic_model.hdbscan_model.labels_`. 

Having said that, I am quite surprised that the outlier reduction would assign documents to topics that you had before using `.merge_topics`. Could you share the code and show exactly how this assignment is going wrong?

**Comment by Var3n** [comment]
Thanks for the quick reply, that should work as a work around. Unfortunately, I won't be able to try it out or share my code before Monday as I am using my work PC for that. But I'll do so as soon as I am back at work.

But just fyi, other functions such as `.topics_over_time` or `.topics_per_class` work fine and use the merged topics.

**Comment by Var3n** [comment]
So here would be my code:

```
model = pipeline("feature-extraction", model="deepset/gbert-large")#, use_fast=False)
embedding_model = HFTransformerBackend(model)
embeddings = embedding_model.embed(docs, verbose = True)

#get UMAP and HDBSCAN from Topic Tuner
topic_model = tmt.getBERTopicModel(66, 13)
topic_model.fit_transform(docs, tmt.embeddings)
topic_model.get_topic_info()

umap_model = topic_model.umap_model
hdbscan_model = topic_model.hdbscan_model

topic_model = BERTopic(language = 'multilingual', calculate_probabilities=True, verbose=True, top_n_words = 10, min_topic_size = 50, umap_model=umap_model, hdbscan_model=hdbscan_model)
topics, probs = topic_model.fit_transform(docs, tmt.embeddings)
topic_model.get_topic_info()

tagger_partial = functools.partial(custom_pos_tagger, texts = top_df['text_chunk'].values, lemmas = top_df['lemma_chunk'].values)
vectorizer = KeyphraseCountVectorizer(pos_pattern='<ADJ.*>*<N.*>+', stop_words='german', lowercase = False, workers = 8, custom_pos_tagger=tagger_partial)

topic_model.update_topics(docs, vectorizer_model=vectorizer, diversity=0.4)

topics_to_merge = [[39, 10], [46, 56], [16, 25], [55, 15], [31, 29], [41, 58], [34, 63], [19, 38], [45, 47], [62,13], [12, 32, 57, 40]]
topic_model.merge_topics(docs, topics_to_merge)

new_topics = topic_model.reduce_outliers(docs, topics, strategy="c-tf-idf", threshold=0.01)
```

**Comment by MaartenGr** [comment]
Ah, it seems that you supplied the old `topics` to `.reduce_outliers`. When you run `.merge_topics`, the internal topics get updated, namely `topic_model.topics_`. 

In other words, whenever you update your topics using `.merge_topics` or `.update_topics` the internal topics `.topics_` get updated. This means that you would have to run the following for it to work:

```python
new_topics = topic_model.reduce_outliers(docs, topic_model.topics_, strategy="c-tf-idf", threshold=0.01)
```

**Comment by Var3n** [comment]
I see, now that you mention it, it's pretty clear. So it was just inattention on my part. Thanks for your help (and the great package) and sorry for having you correcting my code.

**Comment by MaartenGr** [comment]
No problem! If you have any other questions, feel free to reach out.
