### ISSUE TITLE
Issues with parameter setting in Dynamic Topic Modeling

### ISSUE THREAD

**Issue by beeman-93** [MaartenGr/BERTopic#983]
Hello Maarten, I have a question regarding setting parameters in global_tuning and evolution_tuning in Dynamic Topic Modeling. 

I have built my model on 1M tweets on 1000 topics with a time frame from year 2010 to 2021. There are hardly any tweets from year 2010 to 2015, so the tweets are skewed to recent years. I name the model as my_model

I try to visualize the evolution of topics over time by: 
topics_over_time = my_model.topics_over_time(texts, timestamps, 
                               global_tuning=True, evolution_tuning=True,     
                              nr_bins=20,datetime_format="%a %b %d %H:%M:%S %z %Y")

my_model.visualize_topics_over_time(topics_over_time, top_n_topics=10)

I successfully got the result. 

Then I tried global_tuning=False and evolution_tuning=True and tested the result, I found the graph to be identical to setting the parameters with global_tuning=True and evolution_tuning=True. 

I then tried global_tuning=False and evolution_tuning=False and found the graph to be identical to setting the parameters with global_tuning=True and evolution_tuning=True again. 

What could be the reason for this issue? Thanks for your time.

**Comment by MaartenGr** [comment]
The graph itself, the points and lines, will indeed be identical regardless of the `global_tuning` and `local_tuning` parameters. These parameters will only influence the topic representations at the specific timesteps, so when you hover over a single point

**Comment by beeman-93** [comment]
So when I hover over a single point, could you continue explaining. The rest of your sentence did not load fully. 
Thanks a lot.

**Comment by MaartenGr** [comment]
Apologies, seems something went wrong there. 

The graph itself, the points and lines, will indeed be identical regardless of the global_tuning and local_tuning parameters. These parameters will only influence the topic representations at the specific timesteps, so when you hover over a single point you will see a bunch of keywords for that topic at that specific timestep. These keywords will change depending on whether you set `global_tuning` or `local_tuning`. The lines themselves, however, will not be influence by these parameters.

**Comment by beeman-93** [comment]
Thanks for your kind reply. Understood!
