### ISSUE TITLE
got less than 5 topics

### ISSUE THREAD

**Issue by 652994331** [MaartenGr/BERTopic#984]
hi, I am using dataset around 2000 paragraphs.(2000samples) and default model setting. after the training, I got 2 topics, one has 1400+ relative paragraphs and another has 300+. how can I get relative large number of topics with such a small dataset, thank you.

**Comment by MaartenGr** [comment]
I would advise reading through the documentation on [parameter tuning](https://maartengr.github.io/BERTopic/getting_started/parameter%20tuning/parametertuning.html). In your example, I would advise starting with the `min_topic_size` parameter and reducing that to a lower value, for example, `5`. That will typically increase the number of topics generated.

**Comment by drob-xx** [comment]
@652994331 I wrote [TopicTuner](https://github.com/drob-xx/TopicTuner) for this use case. It is fully compatible with BERTopic and facilitates a thorough search through HDBSCAN parameters to help find the right parameters for HDBSCAN for any given dataset.

**Comment by 652994331** [comment]
@drob-xx @MaartenGr  really appreciate guys. I would have a try. Also I found a solved issue before(sorry I forgot the details), it said, clean some meaningless words would help the model to find more topics. I tried and it worked.

**Comment by 652994331** [comment]
@drob-xx I checked your code, very impressive work, here I got a question. I think you used grid search to different setting of min_cluster_size and min-samples and did some experiments, I also checked BaseHDBSCANTuner and gridSearch, pseudoGridSearch and randomSearch function. But I am still having problems about how this "grid search" or more exactly, these functions help the parameters setting.

**Comment by drob-xx** [comment]
@652994331 I can answer the question but probably best to do it in a [TopicTuner discussion](https://github.com/drob-xx/TopicTuner/discussions). If you start a new one there I'll respond.

**Comment by 652994331** [comment]
@drob-xx thank you, will do that
