### ISSUE TITLE
How to use other pre-trained BERT models to improve accuracy？

### ISSUE THREAD

**Issue by cauzp** [MaartenGr/BERTopic#986]
I would like to use some other pre-trained BERT models to improve the accuracy of topic segmentation in Chinese. Can you provide some help? This is the BERT pre-training model I want to use：https://github.com/ymcui/Chinese-BERT-wwm

**Comment by MaartenGr** [comment]
If you want to use any other embedding model in BERTopic, I would advise reading through the guide [here](https://maartengr.github.io/BERTopic/getting_started/embeddings/embeddings.html).

**Comment by cauzp** [comment]
Your advice is very valuable, thank you again!
