### ISSUE TITLE
PredictionData not generated.

### ISSUE THREAD

**Issue by josepius-clemson** [MaartenGr/BERTopic#988]
Getting the following error:
ValueError: PredictionData not generated. Please call clusterer.fit again with prediction_data=True

When I run the below code following your article:
https://medium.com/rapids-ai/faster-topic-modeling-with-bertopic-and-rapids-cuml-5c7559aba898

from bertopic import BERTopic
from cuml.cluster import HDBSCAN
from cuml.manifold import UMAP
import pandas as pd

df = pd.read_json(PATH, lines=True, nrows=100000)
docs = df.reviewText.tolist()

umap_model = UMAP(n_components=5, n_neighbors=15, min_dist=0.0)
hdbscan_model = HDBSCAN(min_samples=10, gen_min_span_tree=True)

topic_model = BERTopic(umap_model=umap_model, hdbscan_model=hdbscan_model,calculate_probabilities=True)
topics, probs = topic_model.fit_transform(docs)
 Pls help.

**Comment by MaartenGr** [comment]
If you want to calculate probabilities, you would have to initialize the HDBSCAN model as follows:

```python
hdbscan_model = HDBSCAN(min_samples=10, gen_min_span_tree=True, prediction_data=True)
```

**Comment by josepius-clemson** [comment]
I am trying that,but getting an error:
MemoryError: std::bad_alloc: out_of_memory: CUDA error at: /project/include/rmm/mr/device/cuda_memory_resource.hpp:70: cudaErrorMemoryAllocation out of memory

Is it because of insufficient GPU memory ? I see one of my GPU is unused when the program is running. Can you advice how to work with multiple GPUs if that is the issue?

**Comment by MaartenGr** [comment]
Most likely, it indeed would be as a result of insufficient GPU memory. It might be worthwhile to fit on a smaller subset of the data and transform all others.

**Comment by MaartenGr** [comment]
Also, I am not entirely sure if cuML supports multi-gpu, so that might be an issue.

**Comment by MaartenGr** [comment]
Due to inactivity, I'll be closing this issue. Let me know if you want me to re-open the issue!
