### ISSUE TITLE
the sentence/text length could be bigger than 512 or any length with official scripts

### ISSUE THREAD

**Issue by ucas010** [MaartenGr/BERTopic#993]
hi,dear
in the official scripts , 
```
from bertopic import BERTopic
from sklearn.datasets import fetch_20newsgroups
 
docs = fetch_20newsgroups(subset='all',  remove=('headers', 'footers', 'quotes'))['data']

topic_model = BERTopic()
topics, probs = topic_model.fit_transform(docs)
```
the sentenc/text in the docs,such as 
`len(docs[1])>512`
I see many "\n" in the sentence, must I sep the big sentence with "\n" 
pls help me ?
thx

**Comment by MaartenGr** [comment]
It depends. If you assume that the the first 512 tokens represent the document rather well, it is actually not an issue to pass the documents as is. However, if you assume that documents might contain multiple topics, then you can either split them up into sentences/paragraphs or calculate the [topic distributions](https://maartengr.github.io/BERTopic/getting_started/distribution/distribution.html) after fitting the model.

**Comment by MaartenGr** [comment]
Due to inactivity, I'll be closing this issue. Let me know if you want me to re-open the issue!
