### ISSUE TITLE
functions：get_document_info(docs)

### ISSUE THREAD

**Issue by li-yuduan** [MaartenGr/BERTopic#994]
Hi Maarteen,
I am using BERTopic to do topic modeling on a dataset.I have a question about the functions : get_document_info(docs), Is what it does assign each document the topic with the highest probability? As shown in the figure, probability and topic represent the most probable topic corresponding to this document
<img width="1136" alt="image" src="https://user-images.githubusercontent.com/65487612/217745558-1c942b3c-09fc-4e14-9675-8c8bf3c1036b.png">
I am really looking forward to hearing your reply soon!

**Comment by MaartenGr** [comment]
The `.get_document_info` does no internal calculations. It simply takes the topic model's internal attributes, such as `topic_model.topics_` and `topic_model.probabilities_` and put them in a single dataframe such that information can easier be visualized.

**Comment by liyuduan817** [comment]
Thanks! so How can I know the probability that each document belongs to a topic？topic_model.probabilities_ only Provide one probability score, but we are not only one topic.
<img width="1101" alt="image" src="https://user-images.githubusercontent.com/65487612/217778414-a6a0ff1e-9916-439d-bebf-b76acee68e05.png">
such as this example you provide, does it represent the maximum probability that each doc belongs to the corresponding topic.
row with index 0 belongs to topic 0,  probability is 1.000000
row with index 1 belongs to topic -1,  probability is 0.000000
row with index 2 belongs to topic 20,  probability is 0.550719
<img width="1078" alt="image" src="https://user-images.githubusercontent.com/65487612/217779006-226cd23c-665a-44b1-abb7-b17bf4ec060d.png">

**Comment by MaartenGr** [comment]
If you want the topic-document probability matrix, you would need to set `calculate_probabilities=True` when instantiating BERTopic. You could also calculate the [topic distributions](https://maartengr.github.io/BERTopic/getting_started/distribution/distribution.html) using `.approximate_distribution`.

**Comment by liyuduan817** [comment]
Got it! huge thanks! I am also want to ask about  functions  get_document_info(docs), As shown below，what does the column（topic and probability）represent?
<img width="1171" alt="image" src="https://user-images.githubusercontent.com/65487612/217795995-c5f992e7-6e12-49ca-ace5-b6c1b7ad1047.png">

**Comment by MaartenGr** [comment]
The topic is the assigned topic based on the cluster model that you used. It is the same as `topic_model.topics_`. The probability is the probability, according to HDBSCAN, that the document belongs to that cluster. It is the same as `topic_model.probabilities_`. It might be worthwhile to checkout the docstring of that function as it contains a description of what can be found in the output.

**Comment by liyuduan817** [comment]
Huge thanks！

**Comment by liyuduan817** [comment]
Another question, is there any way to divide topic -1 into other topics if i am not setcalculate_probabilities=True
<img width="728" alt="image" src="https://user-images.githubusercontent.com/65487612/217830337-89854b7d-89d8-4808-a558-c533b5a7abb9.png">

**Comment by MaartenGr** [comment]
Yes, there is a function called `.reduce_outliers` that you can use for that. I would recommend going through the documentation [here](https://maartengr.github.io/BERTopic/getting_started/outlier_reduction/outlier_reduction.html) or [here](https://maartengr.github.io/BERTopic/faq.html#how-do-i-reduce-topic-outliers) as those are the suggested ways of reducing outliers in BERTopic and allow for the most flexibility without the need to re-train parts of your model.

**Comment by liyuduan817** [comment]
Thank you very much, you are so nice!!
