### ISSUE TITLE
How to get coherence per topic?

### ISSUE THREAD

**Issue by zhimin-z** [MaartenGr/BERTopic#997]
As I follow [this tutorial](https://towardsdatascience.com/understanding-topic-coherence-measures-4aa41339634c) and would like to access the coherence score per topic. Any idea to achieve it? @MaartenGr 
<img width="417" alt="1676164451846" src="https://user-images.githubusercontent.com/8592144/218287891-f7939119-df53-43b7-828e-4dcc26093269.png">

**Comment by MaartenGr** [comment]
There is an open issue [here](https://github.com/MaartenGr/BERTopic/issues/90) where you can find some examples and discussions on how to calculate the topic coherence.
