### ISSUE TITLE
Loading Model

### ISSUE THREAD

**Issue by Mansoor021** [MaartenGr/BERTopic#999]
Hello,
I fitted and transformed a model in **Colab** and I saved it on my drive. Then I download it, so I can use it on my local system; however when I try to load it, I get key error. I really appreciate it if you help me with this issue. Here is the error:

```
KeyError                                  Traceback (most recent call last)
Input In [22], in <cell line: 2>()
      1 import joblib
----> 2 topic_model = BERTopic.load("C:\\Users\\manso\\Downloads\\corrected_review_lemma_withfreqfood_350_embedding",)

File D:\Python\lib\site-packages\bertopic\_bertopic.py:2740, in BERTopic.load(cls, path, embedding_model)
   2738     topic_model.embedding_model = select_backend(embedding_model)
   2739 else:
-> 2740     topic_model = joblib.load(file)
   2741 return topic_model

File D:\Python\lib\site-packages\joblib\numpy_pickle.py:577, in load(filename, mmap_mode)
    575     filename = getattr(fobj, 'name', '')
    576     with _read_fileobject(fobj, filename, mmap_mode) as fobj:
--> 577         obj = _unpickle(fobj)
    578 else:
    579     with open(filename, 'rb') as f:

File D:\Python\lib\site-packages\joblib\numpy_pickle.py:506, in _unpickle(fobj, filename, mmap_mode)
    504 obj = None
    505 try:
--> 506     obj = unpickler.load()
    507     if unpickler.compat_mode:
    508         warnings.warn("The file '%s' has been generated with a "
    509                       "joblib version less than 0.10. "
    510                       "Please regenerate this pickle file."
    511                       % filename,
    512                       DeprecationWarning, stacklevel=3)

File D:\Python\lib\pickle.py:1213, in _Unpickler.load(self)
   1211             raise EOFError
   1212         assert isinstance(key, bytes_types)
-> 1213         dispatch[key[0]](self)
   1214 except _Stop as stopinst:
   1215     return stopinst.value

KeyError: 166
```

**Comment by drob-xx** [comment]
Basically it won't work. Models are generally not portable across different architectures.

**Comment by MaartenGr** [comment]
When you create a model in Colab, you will have done so in an environment with a specific set of package and python versions. Then, when you download the model and try it out locally, that local environment typically has a different set of package and python versions. If you want to be able to use your model locally, then it is important that local environment is the same as the Colab one. In other words, make sure that the package and python versions are exactly the same. To check the versions of BERTopic's dependencies, you can run `pip freeze` and check the [following](https://github.com/MaartenGr/BERTopic/blob/master/setup.py#L14) packages. Then, you can create a local environment, through conda or something else, with the same versions of those dependencies.

**Comment by Mansoor021** [comment]
> When you create a model in Colab, you will have done so in an environment with a specific set of package and python versions. Then, when you download the model and try it out locally, that local environment typically has a different set of package and python versions. If you want to be able to use your model locally, then it is important that local environment is the same as the Colab one. In other words, make sure that the package and python versions are exactly the same. To check the versions of BERTopic's dependencies, you can run `pip freeze` and check the [following](https://github.com/MaartenGr/BERTopic/blob/master/setup.py#L14) packages. Then, you can create a local environment, through conda or something else, with the same versions of those dependencies.

Thank you so much for your time and helpful guidance.
